### ISSUE TITLE
Toolbar icons blend in with dark themes

### ISSUE THREAD

**Issue by Enkouyami** [zim-desktop-wiki/zim-desktop-wiki#1003]
It's hard to distinguish the icons on the toolbar from the background with using dark desktop themes. The only two icons unaffected by this are the "Attach File" and "Link" icons.

[![Zim-toolbar-dark-theme-icons.png](https://i.postimg.cc/q7bthZjW/Zim-toolbar-dark-theme-icons.png)](https://postimg.cc/B8FZRNWC)

**Comment by brandum** [comment]
I'm having the same issue. A dark theme (Plata-Noir) on Solus's Budgie DE.
![Screenshot from 2020-03-26 15-21-52](https://user-images.githubusercontent.com/47691573/77658145-8c5dc100-6f76-11ea-99ce-d16a876feb4a.png)

**Comment by introt** [comment]
Candidate for merging with  #1727

**Comment by jaap-karssenberg** [comment]
Should be less of an issue in the latest version, since many icons are now
"symbolic" which means color is actually changed based on the theme.
