### ISSUE TITLE
Feature-Request: Automatically tag tasks with the name of the page

### ISSUE THREAD

**Issue by sprudel79** [zim-desktop-wiki/zim-desktop-wiki#1006]
I am using the great Zim app mainly to track my tasks. Since I work with multiple pages for different contexts it would be great if the tasks defined on those pages (e.g. by using a checkbox) could be automatically tagged with the name of the page so when I switch to the Task List I would have the perfect overview.
Of course this feature can be enabled/disabled in the options so it's up to the user to decide.
Thanks a lot in advance!

**Comment by nelas** [comment]
Hi @sprudel79, I believe this feature is already available. Try activating the checkbox:

`File > Properties > Task List > Turn page name into tags for task items`

Is that what you were looking for?

**Comment by sprudel79** [comment]
Hi @nelas, thanks for your reply.
That's exactly the feature I was looking for!
I didn't realize there are other options available in File -> Properties, I was only checking the Plugin options.
Thanks again!
