### ISSUE TITLE
Journal templates not applied

### ISSUE THREAD

**Issue by fladd** [zim-desktop-wiki/zim-desktop-wiki#1011]
On MacOS, running Zim from source, the Journal templates (for year, month, day) are not applied, but always the default wiki template for some reason. Hence, Jan 25 2020 will get the following title:
```
25
==
Created Saturday 25 January 2020
```
instead of
```
Saturday 25 Jan 2020
====================
```

**Comment by krisztianmukli** [comment]
Which version of Zim? Are you using the default Journal template or a custom template, which is working with a previous version? In v0.70 Journal plugin was changed and old templates don't work with the new plugin. If you use a custom template, just open it, and change every line with "calendar_plugin" to "journal_plugin".

**Comment by fladd** [comment]
Zim 0.72, default Journal template:

```
[% IF calendar_plugin.page_type == 'day' -%]
======= [% strftime("%A %d %b %Y", calendar_plugin.date) %] =======

[%- ELSIF calendar_plugin.page_type == 'week' -%]
======= [% strfcal("Week %W %Y", calendar_plugin.date) %] =======
[% strftime("%d %B", calendar_plugin.date) %] to [% strftime("%d %B", calendar_plugin.end_date) %]

[% FOREACH day IN calendar_plugin.days() %]
=== [% strftime("%A %d %B", day) %] ===

[% END %]


[%- ELSIF calendar_plugin.page_type == 'month' -%]
======= [% strftime("%B %Y", calendar_plugin.date) %] =======

[%- ELSIF calendar_plugin.page_type == 'year' -%]
======= Year [% strftime("%Y", calendar_plugin.date) %] =======

[%- ELSE -%]
======= [% page.basename %] =======
[% gettext("Created") %] [% strftime("%A %d %B %Y") %]

[%- END %]
```

**Comment by krisztianmukli** [comment]
No, this is the old default. I guess, maybe you open the template for editing in the Zim's old version, when Zim copy the template file to user's home. When you update the program, this template keeps in the user's folder and new Zim try to use that old version. If you didn't edited this template, try to delete from your home (~/.local/share/zim/templates/Journal.txt in Linux, I don't know where is in MacOs but I guess it should be in the same place). After restart Zim, it will be use new version from source. Of course, you can keep this version, too.

That's a trick, if you must use new version (0.70+) and old version (0.69.x) in the same time just copy that lines to the top of the template, and change "journal_plugin" and "calendar_plugin" to "plugin", similar to that:
```
[% IF calendar_plugin.date != None %]
[%   SET plugin = calendar_plugin %]
[% ELSIF journal_plugin.date != None %]
[%  SET plugin = journal_plugin %]
[% END %]

[% IF plugin.page_type == 'day' -%]
======= [% strftime("%A %d %b %Y", plugin.date) %] =======

[%- ELSIF plugin.page_type == 'week' -%]
======= [% strfcal("Week %W %Y", plugin.date) %] =======
[% strftime("%d %B", plugin.date) %] to [% strftime("%d %B", plugin.end_date) %]

[% FOREACH day IN plugin.days() %]
=== [% strftime("%A %d %B", day) %] ===

[% END %]


[%- ELSIF plugin.page_type == 'month' -%]
======= [% strftime("%B %Y", plugin.date) %] =======

[%- ELSIF plugin.page_type == 'year' -%]
======= Year [% strftime("%Y", plugin.date) %] =======

[%- ELSE -%]
======= [% page.basename %] =======
[% gettext("Created") %] [% strftime("%A %d %B %Y") %]

[%- END %]
```

**Comment by fladd** [comment]
Thanks!
