### ISSUE TITLE
Open Zim without creating new instance

### ISSUE THREAD

**Issue by fladd** [zim-desktop-wiki/zim-desktop-wiki#1016]
It would be nice if opening Zim would first check if there is already a Zim instance running and only if not open a new one (and if there is, just bring the already open one into focus). At least under Windows, when using the `zim_debug.exe` (which one has to use if one wants to use user plugins, due to another bug), a new Zim instance is opened.

**Comment by krisztianmukli** [comment]
I'm never heard about zim_debug.exe, so maybe I ask to be stupid, but did you set the default notebook in Open Notebook window (CTRL+O)? My Zim working exactly as you wish, after I sets it, and it open a new window after I delete this settings (with disabled Tray icon plugin, but you can try enabling Tray icon plugin too).

**Comment by fladd** [comment]
Yes, I have a default notebook set. With the normal `zim.exe` the behaviour is also as expected, but not with `zim_debug.exe`, which I unfortunately need to use due to this bug: https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/843.

**Comment by introt** [comment]
Are you still having this issue with Zim 0.74? If so, please open a new issue. Thank you!
