### ISSUE TITLE
Allow float in font size

### ISSUE THREAD

**Issue by sineway** [zim-desktop-wiki/zim-desktop-wiki#1018]
It seems at the moment (v 0.72.1) only integer is allowed.
You cannot set font size equal to 10.5 points (14px), because it will be rounded to 10 points.

**Comment by introt** [comment]
We use a [Gtk.FontButton](https://lazka.github.io/pgi-docs/Gtk-3.0/classes/FontButton.html) which doesn't support floats, so another solution is needed. See #1204 for a related issue.
