### ISSUE TITLE
Pages with "name: example" at the top text dissapears

### ISSUE THREAD

**Issue by Xour21** [zim-desktop-wiki/zim-desktop-wiki#1020]
Whenever I have a page with a colon style list at the top the words start to dissapear. e.g. if the first line of my page is

Name: Example

Then that line of text will dissapear. when I open the file in notepad++ it shows the time a date stamp which is hidden in Zim. It adds the "Name: Example" line to the date stamp and makes it hidden when you view it in zim.

An example from one of the files 
"
Name: Cave Spider
Content-Type: text/x-zim-wiki
Wiki-Format: zim 0.4

Health: 10
Energy: 27
"
The Content Type and Wiki-forsmat ends up belom the Name section and so it can't be seen when you view it in Zim, the Health and Energy bit can be seen but after a random amount of time it also dissapears into the header.

I know I can change everything from a colon to fix it but I really would prefer not to.
Thanks in advance for any ideas or fixes!

**Comment by jaap-karssenberg** [comment]
What version of zim are you using?  I believe this is fixed in the latest
versions.

Regards,

Jaap

**Comment by Xour21** [comment]
I'm on version 0.69.1 for windows. It seemed to wrok before I changed laptops from windows 10 to windows 8 as well.

**Comment by jaap-karssenberg** [comment]
Afraid there is no installer yet for the 0.7x versions for Windows. However
bug is fixed in newer versions.

Regards,

Jaap

Op ma 17 feb. 2020 05:14 schreef Xour21 <notifications@github.com>:

**Comment by Xour21** [comment]
is there a way to update without the installer or is it just not out for Windows? If not any idea when the next version will be released?

Thanks heaps for your help 
Xour21

**Comment by jaap-karssenberg** [comment]
You can run from source under the "msys" environment as mentioned in the
README file.

The installer is waiting for new volunteers to update it.

Regards,

Jaap

**Comment by introt** [comment]
Bug is fixed in Zim >= 0.70
