### ISSUE TITLE
Pasting indented text

### ISSUE THREAD

**Issue by sojusnik** [zim-desktop-wiki/zim-desktop-wiki#1021]
If you copy and paste the following indented text (used tab once), then you'll see that the first line of the last paragraph won't be intended fully, followed by sentences without indentation:

![grafik](https://user-images.githubusercontent.com/1245718/74875644-e6111100-5362-11ea-92a9-6e9d05f4ca90.png)

Try yourself:
```
Lorem borem ipsum morem, lorem morem bum bum borem, lorem morem bum bum borem
	Lorem borem ipsum morem, lorem morem bum bum borem, lorem morem bum bum borem, lorem morem bum bum borem, lorem morem bum bum borem, lorem morem bum bum borem, lorem morem bum bum borem, lorem morem bum bum borem
	Lorem borem ipsum morem, lorem morem bum bum borem, lorem morem bum bum borem, lorem morem bum bum borem, lorem morem bum bum borem, lorem morem bum bum borem, lorem morem bum bum borem, lorem morem bum bum borem
```

As I'm copying and pasting such kind of text quite often, this is really annoying! Would love to see a fix soon.

Happens on Ubuntu with Zim 0.72.1.

**Comment by elcste** [comment]
I think this is the same bug that I reported on launchpad a few years ago: https://bugs.launchpad.net/zim/+bug/1685550

**Comment by introt** [comment]
Can't reproduce with 0.74. @ me if you need to reopen this issue

**Comment by sojusnik** [comment]
Still there with 0.74.3 on Ubuntu, see
https://user-images.githubusercontent.com/1245718/146175521-7dd9a50f-2f5d-4527-a67f-b077636336fe.mp4
After refreshing, the text is aligned correctly, but not after pasting.

**Comment by jaap-karssenberg** [comment]
Cannot reproduce in the development branch. @introt could you check again, and if you still see the issue give more detailed steps how to reproduce, because i might miss a step ?

**Comment by introt** [comment]
Can reproduce with 0.74.3 but not the latest `develop` using the same paste.
