### ISSUE TITLE
Wrong order of notes

### ISSUE THREAD

**Issue by sciurius** [zim-desktop-wiki/zim-desktop-wiki#1024]
I cannot explain why the last two notes are not sorted properly...

![scrot20200226205857](https://user-images.githubusercontent.com/1118804/75382513-e701ef80-58da-11ea-8a3d-1effff20658e.png)

**Comment by jaap-karssenberg** [comment]
Please include some information like the version of zim you are running and
the language settings of your system.

Could be an issue that is already fixed in newer versions, but no way to
say without some context info.

-- Jaap

**Comment by sciurius** [comment]
Fedora 31 (but also happened on Fedora 29).
Zim is 0.72.1 running from git 7d7d1364dc74c892bc81ef1399957406d1be4c61.
System language is en_GB.

Setting the system language to something else caused the indices to be rebuilt and now the sorting order is ok.
Changing the system language back to en_GB caused the indices to be rebuilt again but the sorting order is still ok.

Probably a temporary glitch somewhere... Closing.

**Comment by jaap-karssenberg** [comment]
Yes, in the past changing language could mess up the records, so I added a
check & rebuild for that.

However still wondering what else could cause the glitch in the first
place....
