### ISSUE TITLE
URLs unreadable when using dark theme (Ubuntu)

### ISSUE THREAD

**Issue by hellocatfood** [zim-desktop-wiki/zim-desktop-wiki#1026]
I'm using Zim 0.72.1 on Ubuntu 19.10 and with the default Yaru theme URLs can be easily read. However, here's what it looks like

With the Adwaita dark them
![Screenshot from 2020-03-03 15-49-02](https://user-images.githubusercontent.com/151947/75793279-0c717c00-5d67-11ea-83bc-67e79addaf4a.png)

With the Yaru dark theme
![Screenshot from 2020-03-03 15-49-07](https://user-images.githubusercontent.com/151947/75793398-36c33980-5d67-11ea-807f-34b1d4f7336f.png)

Is there any way to change the URL colour either automatically or manually when using a dark theme?

**Comment by nelas** [comment]
Hi @hellocatfood, have a look at #935 for how to change the colors manually

**Comment by hellocatfood** [comment]
Thanks, that worked great!
