### ISSUE TITLE
Links don't find pages and folder although they are ther

### ISSUE THREAD

**Issue by AnetteMM** [zim-desktop-wiki/zim-desktop-wiki#1030]
I experience quite suddenly that the links do not work anymore. They worked fine before.  

This report was shown:

This is zim 0.69.1
Platform: nt
Locale: de_DE cp1252
FS encoding: mbcs
Python: (2, 7, 14, 'final', 0)
Gtk: (2, 24, 10)
Pygtk: (2, 24, 0)
No bzr version-info found

======= Traceback =======
  File "zim\gui\pageview.pyo", line 5598, in do_link_clicked
  File "zim\notebook\page.pyo", line 352, in new_from_wiki_link
  File "zim\notebook\page.pyo", line 159, in makeValidPageName
ValueError: Not a valid page name:  020 - Ideation (was: -> 020 - Ideation)

**Comment by introt** [comment]
This issue is related to a really old Zim version - please reopen if the issue persists on later versions. Thank you!
