### ISSUE TITLE
Zim  automatically creates ( unwanted ) new pages

### ISSUE THREAD

**Issue by joe-pirat** [zim-desktop-wiki/zim-desktop-wiki#1033]
For a while now, I've been busy at Zim deleting pages that Zim creates automatically.
in some cases I can not even delete these pages.
How can I stop it? 

How does this bug happen?
I am writing for examble : " http://coindesk.com  "  and than remove the " http://  " Zim will automatically make it a link to another new page called " coindesk.com ". 

I use 0.71.1   on Ubuntu 18.04

**Comment by jaap-karssenberg** [comment]
This is expected behavior: when you create a link to a page, that page
shows up in the index.  If you want a web link, use the "edit link" option
to change the text but keep the "http://" target.

-- Jaap
