### ISSUE TITLE
Text files as attachments

### ISSUE THREAD

**Issue by zogommog** [zim-desktop-wiki/zim-desktop-wiki#1035]
Sometimes I want to add file attachments to a page that are text files and they commonly (from the source) come with txt file extensions. There are a few reasons for this, such as preserving the original file attribute information, date-timestamp, etc. and wanting the document to open with a default text editor. While I appreciate Zim's handling of text, sometimes I just don't want it processed, or I want it processed in a specialized manner when I'm viewing it.

Whenever this situation comes up, Zim  creates a new node off the place where the txt file attachment was copied and then it displays the text inside Zim. I can see why some people may want this, but unless I am missing something, I haven't seen any way to turn this behavior off. My work-around has been to manually rename all txt files without the extension, but this isn't ideal.

I'm not sure what technical issues may arise from addressing this, but appreciate it being considered.

Thanks!

**Comment by maclomhair** [comment]
I'm pretty sure this is being addressed in #907 :)
