### ISSUE TITLE
Feature Requested: Linking to a section.

### ISSUE THREAD

**Issue by amoksito** [zim-desktop-wiki/zim-desktop-wiki#1037]
I was wondering if is it possible to link a tag to a specific section, and, if not, if you could add this useful feature. For example:

This is the DocuWiki syntaxt for what I mean:

Linking to a specific section is possible, too. Just add the section name behind a hash character as known from HTML. This links to this Section.

This links to [[syntax#internal|this Section]].

**Comment by lcabrini** [comment]
Or perhaps to be able to add a named anchor at any location. That way, if you wanted to be able to link to a section, you'd just put an anchor in front of it. You could also use this to for example link to code, an image, a table, anything really.

**Comment by jaap-karssenberg** [comment]
This is a double. Please check existing issue list before opening a new one.

Op vr 20 mrt. 2020 21:52 schreef Lorenzo Cabrini <notifications@github.com>:

**Comment by rscmbbng** [comment]
I guess that means #978
