### ISSUE TITLE
Feature request: Add warning when deleting a page 

### ISSUE THREAD

**Issue by sineway** [zim-desktop-wiki/zim-desktop-wiki#1038]
This will prevent accidental loss of data.

**Comment by Nick222** [comment]
But it delete into recover bin...

**Comment by dreua** [comment]
I actually needed google to learn that deleted pages end up in the [system recycle bin](https://zim-wiki.org/manual/Help/Pages.html). While I dislike these "Are you sure" dialogues, I wonder if steps could be taken to make restoring a mistakenly deleted page easier, e.g. with undo or a new "restore deleted page" item somewhere.

**Comment by sineway** [comment]
> But it delete into recover bin...

Oh.. thank you.

**Comment by jaap-karssenberg** [comment]
- windows has a "confirm trash" dialog popping up from the OS, so make warning linux specific
- maybe also add some preferences for trash vs delete
- considered a notebook specific trash, but I realized most of the time I delete pages using Ctrl-A Delete - which is not trashed anyway -- version control is the better option here
