### ISSUE TITLE
AssertionError: BUG: processing empty string

### ISSUE THREAD

**Issue by nasafix-nasser** [zim-desktop-wiki/zim-desktop-wiki#1043]
Opening a page in zim produces the following bug report:

> This is zim 0.72.1
Platform: posix
Locale: en_US UTF-8
FS encoding: utf-8
Python: (3, 5, 2, 'final', 0)
PyGObject: (3, 20, 0)

> ======= Traceback =======
  File "/usr/lib/python3/dist-packages/zim/gui/pageview.py", line 5431, in set_page
    tree = page.get_parsetree()
  File "/usr/lib/python3/dist-packages/zim/notebook/page.py", line 570, in get_parsetree
    self._parsetree = parser.parse(text, file_input=True)
  File "/usr/lib/python3/dist-packages/zim/formats/wiki.py", line 498, in parse
    wikiparser(builder, input)
  File "/usr/lib/python3/dist-packages/zim/formats/wiki.py", line 91, in __call__
    self.block_parser(builder, text)
  File "/usr/lib/python3/dist-packages/zim/parser.py", line 398, in __call__
    assert text, 'BUG: processing empty string'
AssertionError: BUG: processing empty string

The file which produce this error is `test.txt` (see bellow). Note that editing the file and adding/removing some characters eliminates the error. I carefully  checked the file contents using `hexdump` to see any non-ascii data but there were nothing.

>$ hexdump -C test.txt
00000000  31 74 65 73 74 3a 0a 68  74 74 70 73 3a 2f 2f 61  |1test:.https://a|
00000010  62 63 64 65 66 2e 63 6f  2f 0a 0a                 |bcdef.co/..|
0000001b

[test.txt](https://github.com/zim-desktop-wiki/zim-desktop-wiki/files/4433205/test.txt)

May be related to #696

**Comment by introt** [comment]
Can't reproduce on 0.74 - please reopen if the issue persists.
