### ISSUE TITLE
Shared property in notebook.zim config is not respected

### ISSUE THREAD

**Issue by seihtam** [zim-desktop-wiki/zim-desktop-wiki#1049]
In a newly created notebook "shared" is set to True by default in notebook.zim. If "shared" is set to False then index.db and state.conf is still only updated in the AppData folder on the Windows machine I tested. I also tried to create the .zim folder manually but it still didn't work.

(See section "Notebook config file" for more information on the notebook.zim config file: https://zim-wiki.org/manual/Help/Config_Files.html)

**Comment by charleybebbaag** [comment]
Reproduced on version 0.73.2 for Windows

Workaround: create a bat file that sets XDG_CACHE_HOME and launches zim with --standalone option
The contents of the file that is supposed to be next to the notebook folder: 

```
set XDG_CACHE_HOME=%~dp0\.cache
"c:\programs\Zim Desktop Wiki\zim.exe" --standalone %~dp0\zim2\notebook.zim
```
