### ISSUE TITLE
global search bug, version 0.72.1

### ISSUE THREAD

**Issue by Silentdoer** [zim-desktop-wiki/zim-desktop-wiki#1055]
Hi，in my page has these words:即会dump文件;
and I use global search(Ctrl+Shift+F) with key dump can't selected dump.
but I use Ctrl+F search with key dump it works.
and then I use key with whole words 即会dump文件 it works;
，then I replace the content with:即会 dump 文件;(has space in dump side)
the global search works with key dump and selected the dump word；

**Comment by jaap-karssenberg** [comment]
Probably it is not a bug, just unexpected. The search function looks for whole words by default. If you want to look for partial words, you need to search for "*dump*" instead.

I'm aware that the way the word boundaries are handled is not fully aligned with how it is expected for Chinese language content. But I see no elegant way to improve this at the moment.
