### ISSUE TITLE
Dissapearing symbols: ''

### ISSUE THREAD

**Issue by RomanPomykacz** [zim-desktop-wiki/zim-desktop-wiki#1056]
Hello,

i want to save some SQL from developing, but i have a problem.

When i copy/paste this ( small sql sample ):

>  SELECT hpc1.nazev, hpc1.id, 1 kod, 'Celkova vytizenost' popis, 
> 	CASE WHEN VALUE ( vyr.druh, '' ) = '' THEN '0' ELSE CAST ( CAST ( ( cpc1 / rozpeti ) * 100 AS decimal ( 7,2 ) ) AS varchar ( 20 ) ) END hodnota 
>   FROM hpc1 
>   LEFT JOIN cpc1 ON cpc1.nazev = hpc1.nazev AND cpc1.id = hpc1.id 
>   LEFT JOIN vyr ON vyr.stroj = hpc1.nazev AND vyr.stroj_id = hpc1.id 
>   UNION 
>   SELECT hpc2.nazev, hpc2.id, 2 kod, 'Normální vytíženost' popis, 
> 	CASE WHEN VALUE ( vyr.druh, '' ) = '' THEN '0' ELSE CAST ( CAST ( ( cpc2 / hpc2.hpc2 ) * 100 AS decimal ( 7, 2 ) ) AS varchar ( 20 ) ) END hodnota 

It seems to be ok. But when i change tab or close program. And then go back. the '' disapear, and there is:

>  SELECT hpc1.nazev, hpc1.id, 1 kod, 'Celkova vytizenost' popis, 
> 	CASE WHEN VALUE ( vyr.druh,  **) =  THEN** '0' ELSE CAST ( CAST ( ( cpc1 / rozpeti ) * 100 AS decimal ( 7,2 ) ) AS varchar ( 20 ) ) END hodnota 
>   FROM hpc1 
>   LEFT JOIN cpc1 ON cpc1.nazev = hpc1.nazev AND cpc1.id = hpc1.id 
>   LEFT JOIN vyr ON vyr.stroj = hpc1.nazev AND vyr.stroj_id = hpc1.id 
>   UNION 
>   SELECT hpc2.nazev, hpc2.id, 2 kod, 'Normální vytíženost' popis, 
> 	CASE WHEN VALUE ( vyr.druh,  ) =  THEN '0' ELSE CAST ( CAST ( ( cpc2 / hpc2.hpc2 ) * 100 AS decimal ( 7, 2 ) ) AS varchar ( 20 ) ) END hodnota 
( second and last line changed )

What is strange, when i open the .txt files directly with something else the '' symbols are present.
So this is problem with displaying text. Not with saving.

I dont know why. Mayby it is not bug, but feature. But i glad to know what is goint on.

Tested on windows ( 0.69.1 ) and linux ( 0.68-rc1 -  from repozitory )
Czech keyboard, dont know if this change something.

Thanks

**Comment by RomanPomykacz** [comment]
I just discowere Source View plugin.
With it, there is no problem. Works good, and symbols dont disapear.
But i still wonder why in plain text does.

**Comment by jaap-karssenberg** [comment]
Because the wiki formatting is the same symbols.

Op do 23 apr. 2020 13:50 schreef RomanPomykacz <notifications@github.com>:

**Comment by RomanPomykacz** [comment]
Ok. Thanks for answer.
