### ISSUE TITLE
Uncaught exception when sorting "None" string in util.natural_sort_key

### ISSUE THREAD

**Issue by datenwurm** [zim-desktop-wiki/zim-desktop-wiki#1061]
Zim version: 2.20.9-0ubuntu7.14
Architecture: amd64
CurrentDesktop: ubuntu:GNOME
DistroRelease: Ubuntu 18.04

An uncaught Exception occurs when sorting None string in util.natural_sort_key. The exception was triggered by the Table Editor plugin when trying to sort a column with empty cells.

```
# tableeditor.py:765, in sort_by_number_or_string
data2 = natural_sort_key(liststore.get_value(treeiter2, colid))
# utils.py, in natural_sort_key
string.strip() # AttributeError: "NoneType" object has no attribute 'strip'
```

**Comment by datenwurm** [comment]
I'm not quite sure whether it really has something to do with table sorting though. 

Ideally i guess the liststore should never return None but an empty string instead?
But maybe a quick fix in utils.natural_sort_key is also sufficient here:
```
string = string.strip() if string else ""
```

**Comment by introt** [comment]
Can reproduce on 0.74, though fails silently
