### ISSUE TITLE
Version Control does not work

### ISSUE THREAD

**Issue by Schweber** [zim-desktop-wiki/zim-desktop-wiki#1065]
Hello,

I am using Zim 0.72.1 on Manjaro, git is installed.

Still, the Version Control does not work at all. If i select File -> Save Version the "Save Version" window appears. However, if i then select "Save" the window disappears but nothing happens, e.g. no Versions under File -> Versions and no git files in the notebook directory.

I then enabled the autosave options in the configuration of the Version Control Plugin but this has no effect either. 

In the options of the Version Control Plugin it says:

Dependencies
• bzr - Failed (Optional)
• hg - Failed (Optional)
• git - OK
• fossil - Failed (Optional)

I'm at a loss for what to do and suspect a bug. However, I am rather new to Linux and appreciate any help.

**Comment by jaap-karssenberg** [comment]
Probably some error from git. Have a look at the debug output. Or try
initializing the git repository manually first.

Op vr 1 mei 2020 08:37 schreef Schweber <notifications@github.com>:

**Comment by Schweber** [comment]
Where can i see the debug output please?





1. Mai 2020, 08:50 von notifications@github.com:

**Comment by dreua** [comment]
I'd try running him from command line

**Comment by Schweber** [comment]
I am sorry, i don't know what you mean resp. how to do that. I started with Linux 3 months ago...







1. Mai 2020, 12:53 von notifications@github.com:

**Comment by dreua** [comment]
1. Close all Zim windows
2. Search for a program called Terminal or  Command Line
3. A black window with white text should appear
4. Type `zim`, press Enter
5. In Zim try to save version
6. See if anything appears in the Terminal, if so copy and paste it here (Bonus points for letting Github format it as Code to preserve white space and readability.)
7. Close Zim as usual. The Terminal should give you a prompt (Typically `[user@pcname] $` i.e. it shows you that your zim command is done and Terminal expects further instructions.) You can close the Terminal now. If it doesn't return with a prompt (i.e. zim is still running in some visible or invisible form) you can press Ctrl+C to stop it. (Make sure Terminal has the focus.)

**Comment by dreua** [comment]
If nothing interesting appears in terminal try again with `zim --debug` as command in 4. (I know this by looking at `zim --help` or `man zim`)

**Comment by jaap-karssenberg** [comment]
If you start zim from the commandline with the "--debug" option it will
output logging to the terminal. Be aware to first close all instances -
else you only get logging of the instance connecting to the existing
process.

-- Jaap

**Comment by dreua** [comment]
You haven't used git with this user account before have you?
To fix this, run in terminal:
`git config --global user.email "you@example.com"`
and
`git config --global user.name "Your Name"`

I'd recommend using your actual email address and Name in case you end up using git for other stuff in the future but Zim should work afterwards regardless of the values you use.

**Comment by Schweber** [comment]
Thank you for your extensive reply, "zim --debug" led to helpful output.

The problem was "fatal: unable to auto-detect email address"

I ran 

` git config --global user.email "you@example.com"
  git config --global user.name "Your Name"`

Now "Save a Version" is working as expected.

While it may be obvious for an experienced user to setup git via CLI before running the Version Control Plugin for Zim, this wasn't obvious for me at all and wasn't helped by the fact that Zim did not display an error message on its GUI after "Save a version" failed.

Maybe i am just "the 1% of Linux users who don't know something that obvious" but i kindly suggest to either amend the FAQ/Manual of Zim to help with this issue or better still show a helpful error message on its GUI.

Anyway, thank you very much for your assistance and have a nice day!

**Comment by Schweber** [comment]
> You haven't used git with this user account before have you?
> To fix this, run in terminal:
> `git config --global user.email "you@example.com"`
> and
> `git config --global user.name "Your Name"`
> 
> I'd recommend using your actual email address and Name in case you end up using git for other stuff in the future but Zim should work afterwards regardless of the values you use.

Exactly, thank you very much.

If i may add my impression as a new user:

I was under the impression, that the Version Control plugin would just perform a local operation and therefore not require any Setup at all, especially as there was no visible error message for me as a "normal/naive" user

**Comment by dreua** [comment]
You're welcome and welcome to the wold of the Linux Terminal! :smiley: It's a powerful tool in Linux and I can only recommend to try and learn something about it every now and then. 

> I was under the impression, that the Version Control plugin would just perform a local operation

It does, but git needs the setup even for local only operation.

> Maybe i am just "the 1% of Linux users who don't know something that obvious"

It's not obvious imo. Most developers will just have their git set up before they start using Zim and therefore don't run into this problem. 
Some error message in the GUI would certainly be a good idea, I think it should be quite easy to check the return code of `git commit` and just show it's output on failure.

**Comment by shawnhcorey** [comment]
On 2020-05-01 9:26 a.m., David Auer wrote:
>
> You're welcome and welcome to the wold of the Linux Terminal! 😃 It's 
> a powerful tool in Linux and I can only recommend to try and learn 
> something about it every now and then.
>
Some commands you should memorize:

  * pwd (print working directory) -- prints where you are in the file system
  * cd (change directory) -- make another directory the working directory
  * ls (list) -- list the contents of the working directory
  * man (manual) -- print information about Unix commands

>     I was under the impression, that the Version Control plugin would
>     just perform a local operation
>
> It does, but git needs the setup even for local only operation.
>
Yes and no. Zim wants to use the username and email in git, so if 
they're not set, it causes problems. But you can use git without setting 
them.

**Comment by jaap-karssenberg** [comment]
> Yes and no. Zim wants to use the username and email in git, so if
> they're not set, it causes problems. But you can use git without setting
> them.

This is not correct - zim does not "want to use the username and email" -
git requires them by default to commit a version, nothing to do with zim
especially.

Agree that as a GUI tool zim should intercept the error and present the
user with an option to move forward, however no-one has gotten around to
implement such a feature.

Regards,

Jaap

**Comment by shawnhcorey** [comment]
On 2020-05-01 11:08 a.m., Jaap Karssenberg wrote:
> This is not correct - zim does not "want to use the username and email" -
> git requires them by default to commit a version, nothing to do with zim
> especially.
You're correct. But the `man git-commit` page does not say this. :(
