### ISSUE TITLE
Can't set links with new snapshot version

### ISSUE THREAD

**Issue by sojusnik** [zim-desktop-wiki/zim-desktop-wiki#1067]
After installing 0.72.1-SNAPSHOT-t202005011925~ubuntu19.10.1 from the PPA, it's not possible to set links nor update them. After reverting to the stable version, everything works fine again.

**Comment by jaap-karssenberg** [comment]
Pushed a fix for this repression in the develop tree - next snapshot should work again.

Thanks for reporting !
