### ISSUE TITLE
Indexing database/cache location insecure for encrypted notebooks

### ISSUE THREAD

**Issue by shivams** [zim-desktop-wiki/zim-desktop-wiki#1069]
I noticed that the cache of each notebook is stored inside `~/.cache/zim`. Many years back, it used to be stored inside the notebook folders (inside `.zim` folder).

If someone is encrypting their notebooks using one of the suggested methods on the Wiki, then having the notebook's index available in an unencrypted folder defeats the purpose.

Is there a possibility of storing the index inside the notebook folder itself?

**Comment by jaap-karssenberg** [comment]
There is a setting for that, but it is a bit hard to find - see the manual
https://zim-wiki.org/manual/Help/Config_Files.html for the "shared"
property.

**Comment by shivams** [comment]
Oh yes. It's right there in the documentation. And for the exact case of encrypted notebooks. I feel silly for opening this issue now. :sweat_smile:

Anyways, for anyone needing the setting, it's as simple as adding the line `shared=False` inside your `notebook.zim` file. This will disable storing the cache in the shared folder. 

Thank you @jaap-karssenberg for thinking about such small corner cases.
