### ISSUE TITLE
Question: how do I copy highlighted text?

### ISSUE THREAD

**Issue by evan54** [zim-desktop-wiki/zim-desktop-wiki#1070]
When copying highlighted text from zim it copies it as underlined text instead.

Is there a way to ensure it gets copied over with the highlighting?

Alternatively, I found in the appdata/config that I can modify the settings so it colours it instead or in addition but that also doesn't seem to get copied over. Any thoughts?

**Comment by mikem23** [comment]
I'm trying to replicate this with Zim-0.73.3-1 in Fedora and I'm unable, but perhaps I'm not doing the right thing. How are you copying the text and where are you copying to? E.g. is this from Zim to itself or to another app?  What is your `copy_format` setting?

**Comment by mbakstars** [comment]
I'm having the opposite issue. Underline turns into highlighting. W10 with google drive backend. 0.73.5

**Comment by jaap-karssenberg** [comment]
Zim has a "mark" style which can be rendered as either highlight or
underline. Default config uses highlight in zim, but could indeed turn to
underline in export.
