### ISSUE TITLE
[Feature Request] Portable Version

### ISSUE THREAD

**Issue by itprojects** [zim-desktop-wiki/zim-desktop-wiki#1071]
This is in two parts:

1. Can you provide a portable Linux (amd64) zipped version for Zim Desktop Wiki?

The intended usage is USB drives, running from a single folder: cache, config, default notebook.

2. Can you provide compilation/build instructions to make Zim Desktop Wiki from source into a portable application installed (into one folder)?

**Comment by jaap-karssenberg** [comment]
Please read the installation instructions that are in the source folder.
For portable use you can just run from source, but you will need to include
all the pre-requisites as well, which is probably more difficult depending
on how portable you need to be.

-- Jaap

**Comment by itprojects** [comment]
Thanks.
