### ISSUE TITLE
URI too long - Zim crash while edit

### ISSUE THREAD

**Issue by Nick222** [zim-desktop-wiki/zim-desktop-wiki#1072]
> URI too long

Xubuntu 19.10
Zim 0.72-1

Crash while editing - copy - paste text

[Zim_crash.zip](https://github.com/zim-desktop-wiki/zim-desktop-wiki/files/4582751/Zim_crash.zip)

(System crash report and log debug-mode from terminal)

**Comment by Nick222** [comment]
It seems that the file system limitations were the source of the problems.

It may be necessary to change the format of information storage in the program:

store all note files in the same folder, and in the note-file-header indicate the name of the parent note?

**Comment by Nick222** [comment]
Move to Discussion, pls...

**Comment by introt** [comment]
See #54 for alt struts
