### ISSUE TITLE
seqdiag not in Xubuntu 20.04

### ISSUE THREAD

**Issue by Nick222** [zim-desktop-wiki/zim-desktop-wiki#1075]
Plugin seqdiag cannot work in Xubuntu 20.04 - program not in Ubuntu PPA

**Comment by Nick222** [comment]
In Xubuntu 20.04 there is python3-seqdiag instead seqdiag  - and plugin do not work...

**Comment by nasedil** [comment]
I can confirm that on Ubuntu 20.04 python3-seqdiag is not recognized by zim.  Installing using pip `sudo pip3 install seqdiag` also does not help.

The reason is that in Ubuntu 20.04 seqdiag binary is called seqdiag3.

A quick workaround downstream is to make a symlink:
```
ln -s /usr/bin/seqdiag3 ~/bin/seqdiag
```
