### ISSUE TITLE
Can user see backlinks on another Zim-notebook ?

### ISSUE THREAD

**Issue by Nick222** [zim-desktop-wiki/zim-desktop-wiki#1081]
Can user see backlinks on another Zim-notebook ?

User create link on a note in Notebook2 - in a note in Notebook1.

Can user view this link in backlinks-list in Notebook1 ?

**Comment by shivams** [comment]
Currently, this is not possible. But I would also love to have this feature.

**Comment by introt** [comment]
Duplicate of #899
