### ISSUE TITLE
Can Diagram plugin insert SVG

### ISSUE THREAD

**Issue by Nick222** [zim-desktop-wiki/zim-desktop-wiki#1083]
As GraphViz can create SVG - not only PNG - can Zim`s Diagram plugin create SVG (as option, for example)?

**Comment by Self-Perfection** [comment]
I'd really love to store as many diagrams and schemes in SVG instead of PNG. It has many advantages:

1. Works better with version control
2. Usually this files are smaller
3. And can be zoomed in/out without blurring

Gnuplot and seqdiag support SVG output as well.

**Comment by introt** [comment]
Closing this issue - feel free to open a separate discussion if the comment doesn't feel sufficient
