### ISSUE TITLE
using Zim equation editor package

### ISSUE THREAD

**Issue by marty0801** [zim-desktop-wiki/zim-desktop-wiki#1089]
I have installed the requisite dependencies (latex, dvipng) but have no idea how to proceed from here. Equations like those displayed in the manual page for equation editor are not rendered in latex. Example: c = \sqrt{ a^2 + b^2} is not replaced by the latex when I hit enter. It remains unaffected. Please help!

**Comment by Nick222** [comment]
Menu: Insert - Formula

Paste c = \sqrt{ a^2 + b^2} - button Preview

OK

**Comment by sanjarcode** [comment]
@marty0801 Please close the issue now.
