### ISSUE TITLE
Find in page doesn't find text in code blocks (0.72.1)

### ISSUE THREAD

**Issue by groarg** [zim-desktop-wiki/zim-desktop-wiki#1091]
Is there any way to implement that? Would be very helpful for me...

**Comment by max-ant** [comment]
Bug https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/384 from march 2018.
"pro critical" but does not fixed more than two years...

**Comment by introt** [comment]
Duplicate of #384. @max-ant don't worry, it's no longer labeled as critical :)

**Comment by jaap-karssenberg** [comment]
This feature is still on my "1.0" work list. Together with undo for code
blocks and other objects. Afraid it is a slow moving target.

Op wo 15 dec. 2021 16:45 schreef introt ***@***.***>:
