### ISSUE TITLE
Update PPA to Focal

### ISSUE THREAD

**Issue by sojusnik** [zim-desktop-wiki/zim-desktop-wiki#1094]
Would be great to have the latest version of Zim on Ubuntu 20.04 by having the corresponding packages for Focal on the official [PPA](https://launchpad.net/~jaap.karssenberg).

**Comment by introt** [comment]
![image](https://user-images.githubusercontent.com/26069787/146217440-d25cad0e-8214-4091-a4d2-df238b45f3e9.png)
