### ISSUE TITLE
Fails running external programs on Windows

### ISSUE THREAD

**Issue by fmos** [zim-desktop-wiki/zim-desktop-wiki#1097]
For example editing a template with an external editor fails with the error dialog "Failed running: C: \Program Files\Sublime Text 3\subli...".

This is the debug log:

    DEBUG: Action: show_templateeditor
    DEBUG: Opening dialog "Templates"
    DEBUG: open_file(C:\Users\xyz\AppData\Roaming\zim\data\zim\templates\wiki\Journal.txt, text/plain)
    DEBUG: Loading config from: C:\Users\xyz\AppData\Roaming\zim\data\applications\sublime text 3-usercreated-1.desktop
    INFO: Spawning: ('C:\\Program Files\\Sublime Text 3\\sublime_text.exe', 'C:\\Users\\xyz\\AppData\\Roaming\\zim\\data\\zim\\templates\\wiki\\Journal.txt') (cwd: C:\Program Files\Zim)
    DEBUG: Running ErrorDialog
    DEBUG: Failed running: C:\Program Files\Sublime Text 3\sublime_text.exe
    Traceback (most recent call last):
      File "zim/applications.py", line 352, in spawn
    gi.repository.GLib.GError: g-exec-error-quark: Hilfsprogramm (Invalid argument) konnte nicht ausgeführt werden (19)
    ERROR: Failed running: C:\Program Files\Sublime Text 3\sublime_text.exe
    DEBUG: Running MessageDialog
    DEBUG: Closed dialog "Templates"

**Comment by jaap-karssenberg** [comment]
I think the "hilfsprogramm" referred to in the error is a executable
shipped with Gtk for windows that is used for starting sub processes.

Have to dig back in my memory how it is called though.

-- Jaap

**Comment by Atronach** [comment]
The error "Failed running: ..." also happens when trying to edit the source of a page. Unfortunately I can't supply the debug log since this is another thing which doesn't work for me.

Tested with Zim v0.73.1 on Win10.

**Comment by jaap-karssenberg** [comment]
Need to include gspawn-win64-helper.exe and gspawn-win64-helper-console.exe
with the installer.

( If you see this issue when running from source, something may have gone
wrong with your environment, make sure those executables are available. )

**Comment by fmos** [comment]
Ah, thanks for the hint Jaap! Will do and provide a PR.

> Am 14.07.2020 um 08:38 schrieb Jaap Karssenberg <notifications@github.com>:
> 
> ﻿
> Need to include gspawn-win64-helper.exe and gspawn-win64-helper-console.exe
> with the installer.
> 
> ( If you see this issue when running from source, something may have gone
> wrong with your environment, make sure those executables are available. )
>
