### ISSUE TITLE
entering full screen mode a second time causes page view to disappear completely

### ISSUE THREAD

**Issue by mooseyboots** [zim-desktop-wiki/zim-desktop-wiki#1100]
hit f11, full screen mode, no problem, f11 again, revert, no problem, f11 to enter full-screen mode a second time, and the page view disappears completely, the window is blank except for the index side pane and the file menu / toolbar (if enabled).

afaik i have to close zim and re-open to return to my work. clicking on an index entry doesn't display a page. nor does 'update index', nor does creating a new page.

zim 0.72 on debian.

**Comment by introt** [comment]
I can't reproduce this with 0.74 on my system - can you do it on yours?
