### ISSUE TITLE
when linking to a page, hitting enter doesn't fill the field with the item selected

### ISSUE THREAD

**Issue by mooseyboots** [zim-desktop-wiki/zim-desktop-wiki#1101]
often when creating a link to a page with ctrl-l ("insert link") i want to start typing the name of the page, select the one i want then hit enter (or tab) to fill out the "link to:" field with my chosen page. 

this works about 1/2 the time, the rest of the time i hit enter and the field does not update, leaving only the few letters i had typed to search in the field. if i don't notice, i create a link to a new page with that (useless) name. the only way around this is to use the mouse and click on the entry.

the problem never arises in the "jump to page:" field (ctrl-j).

am running zim 0.72 on debian.

**Comment by sojusnik** [comment]
Maybe related to https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/536?

**Comment by mooseyboots** [comment]
yes sounds like it's that, thx i didn't manage to find the existing issue.

interesting the discussion about where the mouse is. i'll try to work out if in my case it only happens when the mouse is over the box.

as i said, i think for me this never happens with page jump, only with creating links. but otherwise sounds like the same issue.

**Comment by mooseyboots** [comment]
can confirm it happens to me even when the cursor is not over the "edit link" dialogue box.

**Comment by mooseyboots** [comment]
ah, ok so when cursor is over the autocomplete window is when it happens, as per existing issue.


can close this as duplicate.
