### ISSUE TITLE
Version control plugin (git) - unicode filenames are not displayed properly

### ISSUE THREAD

**Issue by Nick222** [zim-desktop-wiki/zim-desktop-wiki#1104]
Hello!

I used to use the bazaar version control system to work with Zim, but since it is now being replaced by another system, I decided to switch to git.

Everything works fine with git, with one exception: when viewing differences between versions in Zim, note names are shown not in letters (as before in the bazaar), but in encoding:

> --- "a/\320\220_\320\223\320\273\320\260\320\262\320\275\320\260\321\217_\320\277\320
> +++ "b/\320\220_\320\223\320\273\320\260\320\262\320\275\320\260\321\217_\320\277\320

I have all the names of notes in Russian - that is, 100% is not-Latin.

In another git-version-viewer Russian names of notes are OK.

Is it possible to fix this problem?

Xubuntu 20.04
Zim 0.72.1

Thank :)

**Comment by jaap-karssenberg** [comment]
What version of zim are you using?

**Comment by Nick222** [comment]
I edit post above...

Xubuntu 20.04
Zim 0.72.1

**Comment by jaap-karssenberg** [comment]
Testing with 0.73.0 on a page containing unicode but cannot reproduce.

Have you checked what the content is when using git commandline tools?

**Comment by Nick222** [comment]
Unicode page-name:

a) githg - good page-name

b) Inside Zim 0.73 - Menu - File - Versions - See changes:

First line:

> diff --git "a/\320\221_\320\224\320\276\320\263\320\276\320\275\321\217\321\216\321\211\320\270\320\265_\320\276\320\261\321\211\320\265\321\201\321\202\320\262\320\260/1_\320\242\320\265\320\276\321\200\320\270\321\217_\320\240\320\276\321\201\321\201\320\270\321\217-\320\241\320\241\320\241\320\240/4_\320\236\321\201\320\274\321\213\321\201\320\273\320\265\320\275\320\270\320\265/\320\240\320\276\321\201\321\201\320\270\321\217_-_\320\274\320\260\320\272\321\200\320\276\320\260\320\275\320\260\320\273\320\270\320\267.txt"

**Comment by Nick222** [comment]
Excuse me, I cannot understand - what command it must be

`git diff ` and what?

**Comment by Nick222** [comment]
`git diff 3586198 ccad1b5`

> diff --git "a/\320\221_\320\224\320\276\320\263\320\276\320\275\321\217\321\216\321\211\320\270\320\265_\320\276\320\261\321\211\320\265\321\201\321\202\320\262\320\260/1_\320\242\320\265\320\276\321\200\320\270\321\217_\320\240\320\276\321\201\321\201\320\270\321\217-\320\241\320\241\320\241\320\240/4_\320\236\321\201\320\274\321\213\321\201\320\273\320\265\320\275\320\270\320\265/\320\240\320\276\321\201\321\201\320\270\321\217_-_\320\274\320\260\320\272\321\200\320\276\320\260\320\275\320\260\320\273\320\270\320\267.txt" "b/\320\221_\320\224\320\276\320\263\320\276\320\275\321\217\321\216\321\211\320\270\320\265_\320\276\320\261\321\211\320\265\321\201\321\202\320\262\320\260/1_\320\242\320\265\320\276\321\200\320\270\321\217_\320\240\320\276\321\201\321\201\320\270\321\217-\320\241\320\241\320\241\320\240/4_\320\236\321\201\320\274\321\213\321\201\320\273\320\265\320\275\320\270\320\265/\320\240\320\276\321\201\321\201\320\270\321\217_-_\320\274\320\260\320\272\321\200\320\276\320\260\320\275\320\260\320\273\320\270\320\267.txt"

But diff-content look good:

> -их факторы и сущность
> -* Первобытное общество.
> -* Традиционное общество.

**Comment by jaap-karssenberg** [comment]
I see what you mean now. Unicode page content is rendered well, but unicode
filenames are not.
Afraid this is something that is due to how git produces the diff, because
the whole blob of text comes directly from git and the content of the pages
is rendered properly. So will need post-processing of the diff format to
correct it.

**Comment by Nick222** [comment]
OK
But user cannot recognize filename and sometimes this is a problem...

**Comment by jaap-karssenberg** [comment]
I agree it is a problem.

It can be solved by post-processing the diff before displaying.

-- Jaap

**Comment by pfalcon** [comment]
@Nick222: Any chance that you can update the ticket title to correspond to the actual issue reported? It should be something like: "version control plugin: git: unicode filenames are not displayed properly".

I myself noticed this issue, but would submit a duplicate report, as it's completely unclear what's wrong from this ticket's title (I found it by a chance).

**Comment by pfalcon** [comment]
Thanks for the update. And here's a solution: https://stackoverflow.com/a/22828826/496009

In short, run `git config core.quotepath off` when inside repository. @jaap-karssenberg: It may be advised to run that as part of plugin's repository initialization.

**Comment by Nick222** [comment]
Thanks - all OK now :)

**Comment by pfalcon** [comment]
I submitted https://github.com/zim-desktop-wiki/zim-desktop-wiki/pull/1254 to solve this for future unsuspecting users.
