### ISSUE TITLE
[abrt] Zim: do_selection_changed(): preferencesdialog.py:281:do_selection_changed:TypeError: Argument 1 does not allow None as a value

### ISSUE THREAD

**Issue by cheese** [zim-desktop-wiki/zim-desktop-wiki#1108]
https://bugzilla.redhat.com/show_bug.cgi?id=1844670

Description of problem:
Open preference dialog

Version-Release number of selected component:
Zim-0.72.1-1.fc32

Additional info:
reporter:       libreport-2.13.1
cgroup:         0::/user.slice/user-1000.slice/session-2.scope
cmdline:        /usr/bin/python3 /usr/bin/zim
crash_function: do_selection_changed
exception_type: TypeError
executable:     /usr/bin/zim
interpreter:    python3-3.8.3-1.fc32.x86_64
kernel:         5.6.15-300.fc32.x86_64
runlevel:       N 5
type:           Python3
uid:            1000

Truncated backtrace:
preferencesdialog.py:281:do_selection_changed:TypeError: Argument 1 does not allow None as a value

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/zim/gui/preferencesdialog.py", line 281, in do_selection_changed
    path = selected[0].get_path(selected[1])
TypeError: Argument 1 does not allow None as a value

Local variables in innermost frame:
self: <preferencesdialog.PluginsTab object at 0x7f59b99d3ec0 (zim+gui+preferencesdialog+PluginsTab at 0x555e61802190)>
selection: <Gtk.TreeSelection object at 0x7f59b9c15d00 (GtkTreeSelection at 0x555e611ea520)>
treeview: <preferencesdialog.PluginsTreeView object at 0x7f59b83880c0 (zim+gui+preferencesdialog+PluginsTreeView at 0x555e604e0bc0)>
selected: (<preferencesdialog.PluginsTreeModel object at 0x7f59b997eac0 (zim+gui+preferencesdialog+PluginsTreeModel at 0x555e617fcb30)>, None)

**Comment by introt** [comment]
Are you still having this issue with 0.74?
