### ISSUE TITLE
MacOS file permissions error

### ISSUE THREAD

**Issue by lhagan** [zim-desktop-wiki/zim-desktop-wiki#1109]
I'm running Zim 0.72.1 installed via `homebrew` on Catalina (10.15.5), and it works fine if I open Zim from the terminal using the `zim` command. However, when I start Zim using the [wrapper](https://github.com/jaap-karssenberg/zim-wiki/wiki/Mac-OSX-App-(wrapper)), Zim can't access the folder where I keep my notebooks (`~/Documents`). Opening an existing notebook or creating a new notebook yields this error: "Could not read the contents of Documents. Error opening directory ...: Operation not permitted". I haven't tried every folder, but the same is true for `~/Downloads` as well.

I tried giving the Zim.app wrapper Full Disk Access in Preferences > Security & Privacy, but that had no effect. I also tried granting access to the version of Python that Zim is using (`/usr/local/Cellar/python@3.8/3.8.3/Frameworks/Python.framework/Versions/3.8/Resources/Python.app`), but that also did not help.

Searching the web, I found similar file permission issues reported for other apps running on Catalina (including Gimp), but I didn't see an obvious solution. In some cases, dragging and dropping the file or folder to the app instead of trying to open from the app's file dialog solved it, but this isn't an option in Zim.

Interestingly, Zim can access other folders in `~/`, so my workaround for now is to move my notes out of `~/Documents` and into their own folder (`~/Notes`).

**Comment by jnnkB** [comment]
I tried adding `/usr/local/Cellar/zim/0.73.3/libexec/bin/zim` which also did not work.

**Comment by hysan** [comment]
To get that wrapper to work, I had to:
1. go to System Preferences > Security & Privacy > Full Disk Access
2. unlock and click on the + button
3. add `/bin/sh`
    * to get to the folder with `sh` in the file dialog that appears, do `CMD` + `Shift` + `g`
    * then type in `/bin`
4. (optionally) click on the lock to re-lock

There's a StackOverflow answer somewhere that explains this, but I didn't bookmark it.

**Comment by dehesselle** [comment]
We do have an app for macOS now which does not exhibit this problem. Give it a spin!

**Comment by murattepegoz** [comment]
Folks, I still cannot open files in Zim due to permissions error. Added add /bin/sh to full disk access, didn't help.
Installed zim macOS binary, it didn't help either. 
The wiki (and all files) are on icloud folders though. I am not sure if it changes anything.
Any ideas?

**Comment by dehesselle** [comment]
@murattepegoz Please create a new issue and give as many details as possible: all the relevant version numbers, step-by-step instructions on how to reproduce, exact locations for the app and your wiki files etc.  
There is no general issue with Zim, my wiki is in iCloud as well (as my Documents folder is in iCloud). So we need to find out what's wrong on your end.
