### ISSUE TITLE
SyntaxWarning on install on Ubuntu 20.04

### ISSUE THREAD

**Issue by rolfkleef** [zim-desktop-wiki/zim-desktop-wiki#1111]
When upgrading Zim on Ubuntu 20.04 I get a syntax warning:

```Preparing to unpack .../zim_0.73.0-SNAPSHOT-t202006061317~ubuntu20.04.1_all.deb ...
Unpacking zim (0.73.0-SNAPSHOT-t202006061317~ubuntu20.04.1) over (0.72.1-SNAPSHOT-t202004091842
~ubuntu19.10.1) ...
Setting up zim (0.73.0-SNAPSHOT-t202006061317~ubuntu20.04.1) ...
/usr/lib/python3/dist-packages/zim/plugins/attachmentbrowser/thumbnailer.py:289: SyntaxWarning:
 'NoneType' object is not callable; perhaps you missed a comma?
  raise None(None)
```

Looking [at line 289](https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/master/zim/plugins/attachmentbrowser/thumbnailer.py#L289) and other code in that file, my guess would be it should read [`return None, None` as in line 260](https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/master/zim/plugins/attachmentbrowser/thumbnailer.py#L260), or perhaps [`raise ThumbnailCreatorFailure` as in line 94](https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/master/zim/plugins/attachmentbrowser/thumbnailer.py#L94)?

**Comment by jaap-karssenberg** [comment]
Definitely a bug, weird it pops up now - that line is 3 years old
