### ISSUE TITLE
Bogus link page generation for www.bar.org

### ISSUE THREAD

**Issue by osamuaoki** [zim-desktop-wiki/zim-desktop-wiki#1117]
Thank you for the nice tool zim.

**How to reproduce:**

Let's consider the following text copied from a text editor gedit and pasted to a new zim page (zim was installed from the upstream 0.73.0 deb package to Debian GNU/Linux Buster 10 ).  (Not typed directly from keyboard for simplicity.)

```
BOL
www.bar.org
http://www.foo.org
foo:bar
EOL
```
(This updates this zim page with the exact copy buffer text content without any conversion)

Only ```http://www.foo.org```  is highlighted.

After a while, in the index pane, grayed italic text of ```www.foo.org``` shows up and  ```www.foo.org```  is also highlighted in the page.  (background process seems to be at work.)

Please note the difference between ```http://www.foo.org``` and ```www.foo.org```.  Both generated clickable external links as expected by treating them as the external link.

Key code is:
```
./formats/wiki.py:	'(www\.|https?://|\w+://)'			# autolink & autourl prefix
```

But auto page / index generation code in zim seems to treat ```www.foo.org``` as internal link which I think is bogus and undesirable internal link.

On the top of this, there seem no easy ways to disable links for ```http://www.foo.org``` and ```www.foo.org```. 

**Reminder**

I understand UI design is a delicate art of balance of ease of use.

It seems old annoying behavior around `:` in the raw text is gone.  Texts containing `:` inside are still converted to internal page link as they are typed-in to the zim GUI and stored explicitly with `[[....]]`` in the raw text form.   Although this may have broken presentation of older data, this was a good move.  Now we can disable link manually via menu while keeping ease of use to generate links.  I think the same UI of requiring explicit mark-up  for ```http://www.foo.org``` and ```www.foo.org``` will be nice.  

If this UI change is not pursued for some reason, please consider adding some mark-up syntax to disable remote link so right clicking link can have functioning menu for "Remove Link".

FYI: I updated wiki page around "Tomboy import script".

**Comment by introt** [comment]
On 0.74 both are highlighted straight away, and no bogus pages appear. The quoted part of regex hasn't changed, but the surrounding code looks like it has:

```python3
_url = r'''
    (www\.|https?://|\w+://)            # autolink & autourl prefix
    (?P<domain>([\w\-]+\.)*[\w\-]+)     # domain sections (GFM says "2 or more", so "+" instead of "*")
    [^\s<]*                             # any non-space char except "<"
    '''

```

Can you reproduce this on the latest version @osamuaoki ?

**Comment by osamuaoki** [comment]
I confirmed this bug to be fixed
