### ISSUE TITLE
Can't open a window in existing instance

### ISSUE THREAD

**Issue by kbrenneman** [zim-desktop-wiki/zim-desktop-wiki#1127]
If Zim is already running, then running it again starts a new instance, rather than just sending a command to the existing instance.

I think the problem stems from #1029. The socket it uses lives in the temporary directory, and each process gets a different temporary directory now, so the second process never sees the socket from the first process.

**Comment by kbrenneman** [comment]
On Linux at least, if `XDG_RUNTIME_DIR` is set, then using `$XDG_RUNTIME_DIR/zim` as a fixed directory should work. By the spec, XDG_RUNTIME_DIR is supposed to be writable only by the current user, so it should avoid the problem in #1028.

**Comment by jaap-karssenberg** [comment]
Your absolutely right - that is a stupid mistake on my side :/
Will fix tomorrow and roll a 0.73.1 release

-- Jaap

**Comment by jborme** [comment]
Thanks to this "mistake", zim 0.73.0 allowed to edit two pages side by side, which was an enjoyable feature for time time it last. It even warned of save conflicts and offered to reload externally-modified page. It went against my habit of calling zim from the OS application menu to have the running instance being un-minimized or gain focus, but that was the price to pay for what I thought was a new feature of multiple page edition.

Is there another way to achieve the edition of another page in parallel? A CLI parameter --new-window to open a another instance would do, but I guess this breaks the interprocess communication. The "Open in another window" calls a read-only mode, could this be changed?

**Comment by jaap-karssenberg** [comment]
There is a command line switch called standalone.  However the risk with
two instances is that you overwrite a change in another instance

Op wo 24 jun. 2020 16:53 schreef jborme <notifications@github.com>:
