### ISSUE TITLE
Advanced Task List

### ISSUE THREAD

**Issue by Nick222** [zim-desktop-wiki/zim-desktop-wiki#1128]
May be use this https://gist.github.com/muguu/1d5910ef05259595fe49cde4c9db9d39 for patch Zim task list:

- task comment (in list)
- see (in list) completed task - or save history as separate list of completed task
- option for autocomplete task
and so on

**Comment by introt** [comment]
This seems to imply fixing #486 (Show "completed" tasks in the task list) and #708 (Add date completed metadata when completing tasks)

**Comment by jaap-karssenberg** [comment]
Gist is not applicable to Gtk3 / Python3 which we use since version 0.70. Closing this issue for now, if there is an update somewhere, please file it as a pull request.

**Comment by jaap-karssenberg** [comment]
Closed by miss typing in commit comment
