### ISSUE TITLE
Zim missing Python abri in Fedora 33

### ISSUE THREAD

**Issue by tuxedotje** [zim-desktop-wiki/zim-desktop-wiki#1129]
in Fedora 33 Terminal after try to instal Zim

Error: 
 Problem: conflicting requests
  - nothing provides python(abi) = 3.8 needed by Zim-0.72.1-1.fc33.noarch
(try to add '--skip-broken' to skip uninstallable packages)

**Comment by jaap-karssenberg** [comment]
Please report to fedora package maintainer instead of here

**Comment by cheese** [comment]
I tested that Zim is installable in Fedora 33 (Rawhide) now.

**Comment by mikem23** [comment]
Installing Zim in a Fedora 33 container works without error. The current version is Zim-0.73.4-1.fc33.noarch.

**Comment by tuxedotje** [comment]
Thank you, I will close the bug
