### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by jcjessen** [zim-desktop-wiki/zim-desktop-wiki#1132]
Add Murat's advanced "tasklist" plugin features into zim.

**Comment by muguu** [comment]
features are:
- history of ticked tasks (with ticked date)
- collect and view comments to tasks (with the comments plugin)
- tick open tasks / untick ticked tasks directly in task list

**Comment by introt** [comment]
@muguu May I ask why you haven't submitted any of [your features](https://gist.github.com/muguu) upstream? The PRs are open and many would appreciate your work!

**Comment by introt** [comment]
This issue is a duplicate of #1128

**Comment by jaap-karssenberg** [comment]
Closing this issue for now, if there is an update somewhere, please file it as a pull request.
