### ISSUE TITLE
autoformat for sub- and super-script by typing ^.. and _{..} doesn't work

### ISSUE THREAD

**Issue by SignificantCell2** [zim-desktop-wiki/zim-desktop-wiki#1133]
Hello, 
In the changelog file it was stated:
> Add autoformat for sub- and super-script by typing ^.. and _{..}

However, when I try that in Ubuntu 20.04, that doesn't work. For example, when I type:
`a^b` or `F_2` nothing happens.

Thanks

**Comment by Nick222** [comment]
Work `F_{2}`  after go to another note and return

**Comment by jaap-karssenberg** [comment]
In preferences there is a setting "reformat wiki markup on the fly" which
needs to be enabled.

For numbers, typing e.g. "x^2" will result in the the "2" being
superscript. For non-numbers use "^{...}" including the brackets.
For subscript use "_{..}" including the brackets

**Comment by SignificantCell2** [comment]
@jaap-karssenberg : Thank you very much. I think this should be added as a note to the changelog?
Another note when using superscripts and Arithmetics:
When I write something like this
7<sup>2</sup>= and I press F5 it returns 72
So this formatting cannot be used with Arithmetic (**Tools** > **Arithmetic**)

**Comment by introt** [comment]
> Another note when using superscripts and Arithmetics

Please open a separate issue for this. Thanks!
