### ISSUE TITLE
How to add GTK emojis to symbols.list

### ISSUE THREAD

**Issue by OpenFoam-User** [zim-desktop-wiki/zim-desktop-wiki#1135]
In Ubuntu, One can right click and add emojis. Is there a way to add custom shortcuts to some GTK emojis (with colors) in the file` ~/.config/symbols.list?`
Thanks

**Comment by jaap-karssenberg** [comment]
Not sure. But if the emoji have Unicode codes you can add them in the list.

Op za 20 jun. 2020 13:47 schreef SignificantCell2 <notifications@github.com

**Comment by sanjarcode** [comment]
> In Ubuntu, One can right click and add emojis. Is there a way to add custom shortcuts to some GTK emojis (with colors) in the file` ~/.config/symbols.list?`
> Thanks

To enter an emoji, use this shorcut:
```Ctrl .```
Works on Ubuntu 18.04
No need to change symbols.list
Close the issue if this works @SignificantCell2.

**Comment by introt** [comment]
If that doesn't work, you can try https://github.com/introt/zim-plugin-text-replacer
