### ISSUE TITLE
Windows files use capital letters when linux files are not

### ISSUE THREAD

**Issue by AlexItaca** [zim-desktop-wiki/zim-desktop-wiki#1139]
When sharing a notebook between linux and windows, each os uses a convention. New linux files are  not capital letters as i.e. home.txt While windows uses capital letters HOME.TXT.
This is mostly a problem when syncing repertories and tracking changes.

**Comment by jaap-karssenberg** [comment]
Zim just uses the capitalization how you type it for a new page. If it ends
up in all caps, maybe your syncing setup is doing something weird ?

-- Jaap

**Comment by AlexItaca** [comment]
Hi,
I've already checkthe syncing, but it finds 2 different files. Maybe there
is something in the default  parameters of the windows version?
Alex

Le mar. 23 juin 2020 à 09:20, Jaap Karssenberg <notifications@github.com> a
écrit :

**Comment by fdt-dev** [comment]
Another possibility that happens with Windows-Linux file sync is that sometimes Windows-filesystems are mounted as upper case only, which would result in creating upper case file names when syncing back from Linux.

Some file-sync tools also try to sync Linux to Windows as upper case only. Reason: Windows file-systems are case in-sensitive, while Linux file-systems are case sensitive. I have seen that specific behaviour of a sync software which wasn't fully aware of these details once a few years back.

Which file-sync software are you using? Are you using different machines or are you dual booting? Or is it perhaps a network share? Then it would depend on the server sharing the network share and how the respective operating system interprets the file names.

Zim running under Linux also creates filenames the way I enter them: upper and lower case as required.

Whenever I sync a Zim notebook from Linux to Windows, the file names stay in their correct case, so no issues here. It depends on the file sync software.
