### ISSUE TITLE
Equations hard to read in dark theme

### ISSUE THREAD

**Issue by sum01** [zim-desktop-wiki/zim-desktop-wiki#1143]
All pictures are with `Arc-Dark` theme from [the Arc theme](https://github.com/jnsh/arc-theme), but the results are equally bad with the `Breeze-Dark` from the Breeze theme.

Here's the manual page, which is practically illegible.
![image](https://user-images.githubusercontent.com/19376155/85658083-d7c06200-b680-11ea-8936-f1ea3af7c732.png)
And here's a random equation from my wiki page. This one is at least legible, but it's not great.
![image](https://user-images.githubusercontent.com/19376155/85658691-98464580-b681-11ea-8915-3264bdd3f8b7.png)

Maybe some sort of white drop-shadow, an option for a lighter/custom foreground color, or even just white/lighter text color would fix this issue.

---

System info
Arch Linux kernel 5.7.5
Theme Arc-Dark (icon theme Arc)
Zim version 0.73.0

**Comment by stelzch** [comment]
You can edit the latex template for the equations: `~/.local/share/zim/templates/plugins/equationeditor.tex`

The xcolor package can be used to change the font color:
```tex
\documentclass[12pt]{article}
\pagestyle{empty}

\usepackage{amssymb}
\usepackage{amsmath}
\usepackage[usenames]{color}
\usepackage{xcolor}

\DeclareMathSizes{12}{16}{12}{9}

\begin{document}

% No empty lines allowed in math block !
\textcolor{white}{
  \begin{align*}
  [% equation -%]
  \end{align*}
}

\end{document}
```

You will have to regenerate already inserted equations though.

**Comment by jaap-karssenberg** [comment]
Keep it open, ideally it should be controlled by a preference option of the
plugin.

-- Jaap
