### ISSUE TITLE
link has higher priority than checkbox in 0.73.0

### ISSUE THREAD

**Issue by chihchun** [zim-desktop-wiki/zim-desktop-wiki#1150]
The [18b106b commit](https://github.com/zim-desktop-wiki/zim-desktop-wiki/commit/18b106b842e8fa2ac44dd6c72eee159771e7878a) in 0.73.0 breaks the style of the link. 

The 0.72.1 version will allow checked-box, xchecked-box and migrated-box to overwrite the style of the link (eg, I set the style of checked-box as grey, so link become grey after I checked). After 0.73.0, The link style always has the default foreground blue color even when the checkbox is checked.

**Comment by jaap-karssenberg** [comment]
Yes, afraid this is a "won't fix" for now - we can set priority, but the priority affects all properties, so I can't split out the priority of e.g. bold style and color.
