### ISSUE TITLE
prevent expression with {{}} from being  converted to the image

### ISSUE THREAD

**Issue by yasharne** [zim-desktop-wiki/zim-desktop-wiki#1151]
Hi
Every time I try to put a string in my document which consists of {{}} it will change to the image automatically,
e.g. if I put {{ ansible_managed | comment }} in my document it will change to this:
![image](https://user-images.githubusercontent.com/7656049/85946376-3162ae00-b959-11ea-8f69-97506994e5bc.png)
How can I prevent this?

**Comment by ts14ic** [comment]
One way would be escaping that snippet with `'`.  Double `''` for in-line `''{{ ansible_managed | comment }}''` and for blocks use triple:
```
'''
{{ ansible_managed | comment }}
'''
```
