### ISSUE TITLE
Invalid config value when switching locale

### ISSUE THREAD

**Issue by swsnr** [zim-desktop-wiki/zim-desktop-wiki#1152]
ZIM 0.72.0 (from the `0.72.0-1` zim package in Ubuntu 20.04) warns about invalid config values when changing `LC_MESSAGES`:

```console
$ zim --version
zim 0.72.0
[…]
$ env LC_MESSAGES=en_GB.UTF-8 zim
$  env LC_MESSAGES=de_DE.UTF-8 zim
WARNING: Invalid config value for grid_lines: "with lines" - Value should be one of ('mit Linien', 'keine Gitternetzlinien', 'Horizontale Linien', 'Senkrechte Linien')
WARNING: Invalid config value for granularity: "Day" - Value should be one of ('Tag', 'Woche', 'Monat', 'Jahr')
```

These warnings original from the `grid_lines` setting in the `TableEditorPlugin` section and from the `granularity` setting in the `JournalPlugin` section respectively.  The permitted values in each warning message contain the German translation of the original English values.

I can also "reverse" the error: If I start Zim with `de_DE.UTF-8` and configure it (opening the preferences dialog and pressing "Ok" seems to be sufficient) I subsequently get a warning when starting with `en_GB.UTF-8`:

```console
env LC_MESSAGES=en_GB.UTF-8 zim
WARNING: Invalid config value for grid_lines: "mit Linien" - Value should be one of ('with lines', 'no grid lines', 'horizontal lines', 'vertical lines')
WARNING: Invalid config value for granularity: "Tag" - Value should be one of ('Day', 'Week', 'Month', 'Year')
```

It looks as if the affected settings seem to store the localized value and subsequently fail to parse the configuration if the locale changes.

**Comment by introt** [comment]
Confirmed on Zim 0.74.3/`develop`. Affected plugins should be modified to not use the translatable display string as the config value.

**Comment by swsnr** [comment]
I'm not using zim anymore, so I'm closing this because I don't care for this being fixed anymore.

**Comment by Folaht** [comment]
I do care about this since I've recently been using zim.  
I only have this with the build script though.
