### ISSUE TITLE
Since symbol ∵ (HTML code 8757) missing in symbol.list

### ISSUE THREAD

**Issue by sanjarcode** [zim-desktop-wiki/zim-desktop-wiki#1153]
There's no since/because symbol(∵) in symbols.list
https://www.toptal.com/designers/htmlarrows/math/because/

![image](https://user-images.githubusercontent.com/48156230/86041669-9acee380-ba63-11ea-8ebe-e0c5cac68dbe.png)
8757 is absent.

Alternative Tried:
Edited the symbols.list file
/bec 8757

But the shortcut becomes /, bec is just rejected.

**Comment by sanjarcode** [comment]
```/bec + Space```
Works fine for me.

**Comment by introt** [comment]
You need to restart Zim for the change to get picked up. I'll add it to the list.
