### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by wethecom** [zim-desktop-wiki/zim-desktop-wiki#1154]
please add an autofill to the Insert link ..that will grab the link from your clipboard

**Comment by stelzch** [comment]
What do you mean by autofill?

**Comment by introt** [comment]
Assuming you mean "please add an option to fill the `Link to` field of the Insert link dialog" automatically from the clipboard". Please edit the title @wethecom

**Comment by jaap-karssenberg** [comment]
This is a "won't fix" - I think it is better to just press Ctrl-V to paste the link explicitly. I want to avoid unexpected behavior for other users.

**Comment by wethecom** [comment]
place a clipboard button that dose it..
