### ISSUE TITLE
For Windows users (zim-desktop-wiki-0.73.1-setup.exe) the Journal (calendar) utility is no longer available

### ISSUE THREAD

**Issue by myusernamej** [zim-desktop-wiki/zim-desktop-wiki#1156]
![pasted_image003](https://user-images.githubusercontent.com/51192347/86227254-0c568100-bb8d-11ea-8787-9a20f7a686ba.png)
As you can see, the calendar option (journal) is no longer available. I have searched on every menu deeply, but it is not here.
Ill downgrade to 0.69.1 version.
Journal/Calendar option is really important to me, I would be please if you can fix it for windows users.

Best regards.

**Comment by jaap-karssenberg** [comment]
Works on my system. Have you enabled the plugin in the preferences dialog?

Op wo 1 jul. 2020 11:24 schreef myusernamej <notifications@github.com>:

**Comment by myusernamej** [comment]
Wow. I have just discovered the plugin world. Great!
This software is becaming really useful.
Thank you jaap-karssenberg!
