### ISSUE TITLE
Windows version (zim-desktop-wiki-0.73.1-setup.exe) won't start on Win7

### ISSUE THREAD

**Issue by treborxy** [zim-desktop-wiki/zim-desktop-wiki#1157]
Hi,
first: Thank you so much for giving us a Win - Version again! 
Unfortunately on my maschine (Win 7) it's not possible to start - neither 'normal' nor 'portable'. It throws a fatal error saying "failed to execute script pyboot01_bootstrap" - anything I have to install prior to installing zim ?

While I like much more Linux, on my job I'm forced to use Win. So it was a bit difficult to use the new version with Linux and the 'old' version with Win, because the 'old' version cripples the formatting (obviously it can't handle the new multi-formatting (which is cool!)).

**Comment by jaap-karssenberg** [comment]
Afraid this will be a "Won't fix". My understanding is that Windows 7 is
effectively end-of-life with no support from Microsoft anymore.

Probably your best bet is to try installing the msys environment (
https://www.msys2.org/) if that works, you can use the pacman package
manager to install the necessary packages and run zim directly from source.

Hope this helps,

Jaap

**Comment by treborxy** [comment]
Thanks again, tried Win 8.1, and this works :-)

**Comment by sergioflorespereira** [comment]
Hi,
So great that there has been an attempt to provide a windows installer again. Been working with v0.69.1 till now.
  
I tried to install the "zim-desktop-wiki-0.73.1-setup.exe" on windows 10 - 64bit. Got the following error indicated in the screen-shot below.

Also had to navigate the zim start-up, (to select the note book) using tabs and with difficulty the laptop's mouse pad. Zim would not recognise my wacom tablet's input. 

![zim_bug](https://user-images.githubusercontent.com/68057852/87028664-d8a3d880-c1d6-11ea-96e4-486354882790.jpg)

Thank you so much for zim ... even v0.69 is amazing. 
Hope one day there will be an Android version.

Thank you.
Sergio
