### ISSUE TITLE
portable Win 0.73.1: Sidepane No triangle indicating sub-pages

### ISSUE THREAD

**Issue by treborxy** [zim-desktop-wiki/zim-desktop-wiki#1159]
Unlike Linux-Version the Win - Version works a bit uncomfortable with sub-pages in the sidepane: 
- there are no triangles indicating "there are sub-pages"
- it is not possible to fold-in the sub-pages by clicking the main page: unfolding stays open until an other mainpage opens its sub-pages

**Comment by Sandman1973** [comment]
Yes this is the first thing thing I noticed having just downloaded the windows build. You can manually open and close by clicking just to the left of the item title. So the function is there, just not the graphic.

It's great to have an build for windows again! I love this application.

**Comment by jaap-karssenberg** [comment]
Need to include the "pan-*-symbolic" icons in the installer - probably best
to include the whole "ui" section from the default Adwaita theme.

-- Jaap
