### ISSUE TITLE
portable Win 0.73.1: Attachment pane - rightclick on files shows crippled option-window

### ISSUE THREAD

**Issue by treborxy** [zim-desktop-wiki/zim-desktop-wiki#1160]
When right-clicking a file in attachment-pane, only a crippled "window" shows up (about a text-line hight, about 10 characters wide. While moving the mousepointer over it, fragments of option-text scrolls in.

Similar oddity with right-clicking the app-icon: a small window shows up, but is empty - only when you move the mouse-pointer to the bottom of this window, the options scroll up and populate the window as expected.

**Comment by Sandman1973** [comment]
This was actually the second thing I noticed. We seem to be in tune and noticing the same things.

The "menu" does not seem to be fully formed when you right click in both these cases.

**Comment by dwu** [comment]
I see the same behavior on Linux with the current develop head (d2d93a8). Populating the popup menu before calling `gtk_popup_at_pointer` does seem to fix the issue.

```diff
diff --git a/zim/plugins/attachmentbrowser/filebrowser.py b/zim/plugins/attachmentbrowser/filebrowser.py
index 1cd1f434..0bf93b6c 100644
--- a/zim/plugins/attachmentbrowser/filebrowser.py
+++ b/zim/plugins/attachmentbrowser/filebrowser.py
@@ -332,8 +332,8 @@ class FileBrowserIconView(Gtk.IconView):
                        pathinfo = iconview.get_path_at_pos(x, y)
                        if pathinfo is not None:
                                iconview.grab_focus()
-                               gtk_popup_at_pointer(popup_menu, event)
                                self.do_populate_popup(popup_menu, pathinfo)
+                               gtk_popup_at_pointer(popup_menu, event)
                                        # FIXME should use a signal here
                                return True
                return False
```
