### ISSUE TITLE
Server, export, and index

### ISSUE THREAD

**Issue by sciurius** [zim-desktop-wiki/zim-desktop-wiki#1163]
When I enable the built-in web server from Zim, I get a list of subpages for each parent document. For example:
````
Foo
   Bar
   Blech
````
then document `Foo` will show a `<ul>` list with `Bar` and `Blech`.

When I export the documents to HTML, the exported document for `Foo` is empty. No list.

Is this intentional?

**Comment by jaap-karssenberg** [comment]
This is a feature of the webserver to handle non-existing pages. The export
function does not have the same feature.

Regards,

Jaap

Op ma 6 jul. 2020 19:48 schreef Johan Vromans <notifications@github.com>:

**Comment by sciurius** [comment]
thx
