### ISSUE TITLE
Export: page.meta not always initialized

### ISSUE THREAD

**Issue by sciurius** [zim-desktop-wiki/zim-desktop-wiki#1164]
In an export template I want to use the page meta data. For example (simplified):
````
[% FOR page IN pages %]
[% title %]
[% IF page.meta %]
[% IF page.meta.get("Template") %]
Template [% page.meta.get("Template") %]
[% END %]
[% END %]
[% page.content %]
[% END %]
````
This generates an annoying warning `WARNING: No such parameter: page.meta` for all pages that do not have any meta data.

So while there is a safe way to **fetch** a meta data (line 4, `meta.get("Template")`) that yields `None` if the item does not exists, it is not possible to **check** whether the page has meta data at all (line 3) without getting a warning. 

Note that the pages that Zim kindly automatically generates during export (e.g. `Home.html`) do not have meta data so even if all my pages have meta data, I still get one or more warnings.

Suggestion: Allow `page.meta` to return `None` without warning. Better, but harder to implement: Make `page` a neatly behaving `dict` so we can use `page.get("meta")`.

**Comment by jaap-karssenberg** [comment]
Actually, the intended behavior is for "meta" to always exist even when
empty. Need to figure out why it is broken.
The parameter "page" is an object, not a dict, so it's attributes should
not be variable.

-- Jaap
