### ISSUE TITLE
upgrade 0.69 to 0.72.1 causes loss of side pane

### ISSUE THREAD

**Issue by galenthurber** [zim-desktop-wiki/zim-desktop-wiki#1167]
after upgrading 0.69 on MX Linux to 0.72.1 the side pane is gone, even on new noteboks.
expect side panes to show

**Comment by jaap-karssenberg** [comment]
Yes, it is a plugin now - please enable the "pageindex" plugin via the
preferences dialog.

-- Jaap

**Comment by gut5** [comment]
I have probably been using the wiki the wrong way, is there a way to easily make all index pages inherit their subpages or child pages? 
The side pane suddenly becoming a plugin is going to throw off a lot of people who have been using it this way.

**Comment by introt** [comment]
There's nothing wrong with your way, migration was just a bit rough- the page index plugin is enabled by default on new installations. The filesystem hierarchy hasn't changed.
