### ISSUE TITLE
GTK bug ?

### ISSUE THREAD

**Issue by Nick222** [zim-desktop-wiki/zim-desktop-wiki#1180]
When Zim start - I see in terminal:

`(zim:43855): Gtk-CRITICAL **: 12:46:20.286: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar`

Xubuntu 20.04
Zim 0.73.1 (debug mode)

**Comment by jaap-karssenberg** [comment]
Sorry but please don't report these kind of gtk warnings. Only report if
you actually have an issue in using zim.

Regards,

Jaap

Op ma 13 jul. 2020 11:54 schreef Nick222 <notifications@github.com>:

**Comment by Nick222** [comment]
It is not an error?
