### ISSUE TITLE
Cannot delete pages

### ISSUE THREAD

**Issue by dualhammers** [zim-desktop-wiki/zim-desktop-wiki#1186]
![Screen Capture_zim_20200716155835](https://user-images.githubusercontent.com/7495830/87726984-4cb52200-c77d-11ea-95b4-2e42b0f13c9c.gif)

See gif for issue. I meant to write "compiled from source."

When I run in terminal I get no error.

**Comment by jaap-karssenberg** [comment]
Can you run Zim with debug commandline switch and check for error message?

Op do 16 jul. 2020 23:59 schreef Eruanno Astalda <notifications@github.com>:

**Comment by dualhammers** [comment]
I ran it via the terminal and saw no error message - is that separate from
a specific debug switch?

**Comment by jaap-karssenberg** [comment]
If you run from the terminal with the "--debug" option you'll get more
output


Op do 6 aug. 2020 22:44 schreef Eruanno Astalda <notifications@github.com>:

**Comment by derSebbl** [comment]
I'm having the same issue on arch, "zim --debug" output:
``` 
INFO: Move /home/seb/MEGA/Studium/Projektmaster/Notizen/Studienaufbau/test.txt to trash
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/zim/notebook/operations.py", line 243, in <lambda>
    GObject.idle_add(lambda: next(my_iter, False), priority=GObject.PRIORITY_LOW)
  File "/usr/lib/python3.8/site-packages/zim/notebook/operations.py", line 270, in __iter__
    progress = next(self._do_work)
  File "/usr/lib/python3.8/site-packages/zim/notebook/notebook.py", line 897, in trash_page_iter
    self._trash_page(path)
  File "/usr/lib/python3.8/site-packages/zim/notebook/notebook.py", line 922, in _trash_page
    re = helper.trash(file) or re
  File "/usr/lib/python3.8/site-packages/zim/newfs/helpers.py", line 88, in trash
    raise error
  File "/usr/lib/python3.8/site-packages/zim/newfs/helpers.py", line 78, in trash
    ok = f.trash()
gi.repository.GLib.Error: g-io-error-quark: Unable to find or create trash directory for /home/seb/MEGA/Studium/Projektmaster/Notizen/Studienaufbau/test.txt (0) 
```

**Comment by jaap-karssenberg** [comment]
Zim should catch that error and allow delete instead. However it is a weird
error - there should always be a ~/.Trash folder that is accessible for
applications to trash to in a standard linux environment. Is there
something special in your setup ?

-- Jaap

**Comment by derSebbl** [comment]
No, nothing special in my setup. 

The command:
`cd ~ && ls -a | grep Trash` 
yields
`drwx------   5 seb  seb  4.0K 19. Jun 14:34 .Trash`

The folder exists and zim is running as user 'seb', so it should work.

The folder '~/.local/share/Trash' also exists btw.

**Comment by introt** [comment]
Given the changes to the file system parts, are you still having this problem on the latest version?
