### ISSUE TITLE
Can't install spell checker plugin

### ISSUE THREAD

**Issue by schiessle** [zim-desktop-wiki/zim-desktop-wiki#1190]
I'm running Zim 0.72 from Debian testing and can't install the Spell Checker Plugin:

![image](https://user-images.githubusercontent.com/1589737/87828010-5bcec980-c87c-11ea-9aca-1754b61b991c.png)

According to the documentation I have to install python3-gtkspellcheck and gir1.2-gtkspell3-3.0, both are installed:

````
$ apt policy gir1.2-gtkspell3-3.0
gir1.2-gtkspell3-3.0:
  Installed: 3.0.10-1
  Candidate: 3.0.10-1
  Version table:
 *** 3.0.10-1 500
        500 http://ftp.uni-stuttgart.de/debian bullseye/main amd64 Packages
        100 /var/lib/dpkg/status
````

````
$ apt policy python3-gtkspellcheck
python3-gtkspellcheck:
  Installed: 4.0.5-2
  Candidate: 4.0.5-2
  Version table:
 *** 4.0.5-2 500
        500 http://ftp.uni-stuttgart.de/debian bullseye/main amd64 Packages
        100 /var/lib/dpkg/status
````

**Comment by sum01** [comment]
For me, I needed aspell as well as gtkspell3. So maybe try it after installing `aspell-en` (or whichever lang you want). I believe the documentation mentions that.

**Comment by schiessle** [comment]
Thanks for the quick answer. "aspell-en" is installed as well. "gtkspell3" doesn't exists on Debian, I checked the stable,testing and unstable repository. What exists and what is installed as well: " gir1.2-gtkspell3-3.0" and "libgtkspell3-3-0"

**Comment by jaap-karssenberg** [comment]
For this plugin either of the dependencies is ok. Have you tried enabling
it?

Op za 18 jul. 2020 12:13 schreef Björn Schießle <notifications@github.com>:

**Comment by schiessle** [comment]
Indeed, just enabling works :see_no_evil: I was to irritated by the red "failed" so that it didn't come to my mind to just trying it...
