### ISSUE TITLE
Windows 0.73.1: The menu that comes up when right-clicking the Zim icon in the Windows taskbar will be empty, and one cannot quit Zim from there (or do anything else)

### ISSUE THREAD

**Issue by fladd** [zim-desktop-wiki/zim-desktop-wiki#1192]
![image](https://user-images.githubusercontent.com/2971539/87137943-f7b96d80-c29d-11ea-8379-5e909aa5c49d.png)\

#1169

**Comment by introt** [comment]
Are you still having this problem on the latest version?
