### ISSUE TITLE
Windows 0.73.1: There are no folder indicators (triangles?) in the Index pane

### ISSUE THREAD

**Issue by fladd** [zim-desktop-wiki/zim-desktop-wiki#1194]
![image](https://user-images.githubusercontent.com/2971539/87137860-d9537200-c29d-11ea-83ed-d657d812a0d7.png)

#1169

**Comment by jaap-karssenberg** [comment]
Duplicate

Op ma 20 jul. 2020 13:26 schreef Florian Krause <notifications@github.com>:

**Comment by zionly** [comment]
Sorry, but I can't understand why this bug report was closed : Can't find any information in this report, neither in #1169... 
This bug report is not a duplication of #1169 : it was asked to open a single report for each issue reported in #1169.
