### ISSUE TITLE
Windows 0.73.1: Additional user plugins do not load (or at least don't show in the interface)

### ISSUE THREAD

**Issue by fladd** [zim-desktop-wiki/zim-desktop-wiki#1197]
This might still be related to the bug from before, where plugins would only load when Zim is started in Debug Mode (cannot confirm, as there is no Debug Mode executable anymore in the new version)

#1169

**Comment by fladd** [comment]
For example, the Now Button plugin does not show up in the plugin list, and cannot be enabled:

![image](https://user-images.githubusercontent.com/2971539/89019304-62018300-d31d-11ea-82cd-b483809a1d37.png)

Worked fine in previous versions (i.e. <0.73).

**Comment by jaap-karssenberg** [comment]
Yes, these plugins are not compatible with python3 / gtk3. Please contact
the author of those plugins.

**Comment by fladd** [comment]
Yes, I just realized that I did not update the plugin yet (I rewrote it some time ago to be compatible with the new version). It works now. Sorry for the confusion.
