### ISSUE TITLE
Exception with relative link to page starting with .. 

### ISSUE THREAD

**Issue by rongcuid** [zim-desktop-wiki/zim-desktop-wiki#1202]
When I try to create a relative link to previous level, like `[[..:test]]`, an exception occurs: 

```
This is zim 0.72.0
Platform: posix
Locale: en_US UTF-8
FS encoding: utf-8
Python: (3, 8, 2, 'final', 0)
PyGObject: (3, 36, 0)

======= Traceback =======
  File "/usr/lib/python3/dist-packages/zim/gui/pageview.py", line 5816, in do_activate_link
    self._do_activate_link(link, hints)
  File "/usr/lib/python3/dist-packages/zim/gui/pageview.py", line 5826, in _do_activate_link
    self.page, HRef.new_from_wiki_link(link)
  File "/usr/lib/python3/dist-packages/zim/notebook/page.py", line 357, in new_from_wiki_link
    names = Path.makeValidPageName(href.lstrip('+'))
  File "/usr/lib/python3/dist-packages/zim/notebook/page.py", line 158, in makeValidPageName
    raise ValueError('Not a valid page name: %s (was: %s)' % (newname, name))
ValueError: Not a valid page name: .:test (was: ..:test)
```
This forces me to use absolute path to page on levels above current page.

**Comment by jaap-karssenberg** [comment]
Names are resolved upward by default, so "Test" will link to page on parent
level by default unless there is a page "Test" as well on the current
level. In that case you can use a partial path to be explicit on the
version you mean.

Please see https://zim-wiki.org/manual/Help/Links.html for an example

**Comment by rongcuid** [comment]
According to the page, names are resolved on the same level by default. I am referring to this kind of structure:

```
A
- A:B
- A:C
-- A:C:E
-- A:C:D
--- A:C:D:E
- A:E
-- A:E:F
```

Now, assume I am in `A:C:D`, and I want to refer to `A:E`. 
`[[E]]` would link to `A:C:E`, not `A:E`.
In addition, what if I want to refer to `:A:C`? Or `:A:E:F`?
Currently I can only use absolute path for all these cases.

**Comment by jaap-karssenberg** [comment]
Yes that is correct. But if you have so many redundant names on different
level, probably using absolute names is the best way to go anyway to avoid
confusion what you are linking to.

**Comment by rongcuid** [comment]
Well that is only an example. My use case is more like linking `A:E:F` from `A:C:D`, without the redundant names.
