### ISSUE TITLE
libgtksourceview-3.0 package outdated

### ISSUE THREAD

**Issue by faliagas** [zim-desktop-wiki/zim-desktop-wiki#1203]
The libgtksourceview-3.0 package required by the plugin "Source View" is outdated in the latest version of Ubuntu Linux. Please update.

**Comment by akbcode** [comment]
You also need to install gir1.2-gtksource-3.0 package on Ubuntu to enable source view plugin.

**Comment by casperl** [comment]
Thank you, installing gir1.2-gtksource-3.0 package on Ubuntu 20.04 worked and the plugin has been installed.

I suggest updating the Zim manual notebook page on Plugins:Source View from this:

Dependencies: This plugin depends on the gtksourceview package. On Ubuntu this dependency can be satisfied by installing the libgtksourceview-3.0 package.

To this:

Dependencies: This plugin depends on the gtksourceview package. On Ubuntu this dependency can be satisfied by installing the libgtksourceview-3.0 as well as the gir1.2-gtksource-3.0 package.

Failing that I can do a Git clone/commit/push with the appropriate change in the Manual Notebook (provided I can locate the manual) in the repo.
