### ISSUE TITLE
Bug:  Editing pages introduce spaces between heading levels

### ISSUE THREAD

**Issue by TammyJess** [zim-desktop-wiki/zim-desktop-wiki#1205]
**Original:**
====== Heading 1 ======
===== Heading 2 =====
==== Heading 3 ====
=== Heading 4 ===
== Heading 5 ==
Hillo

**after inserting/editing** Zim saves the page thusly:
====== Heading 1 ======

===== Heading 2 =====

==== Heading 3 ====

=== Heading 4 ===

== Heading 5 ==
Hello

**Comment by jaap-karssenberg** [comment]
This is by design. Our wiki format has a mandatory blank line before a
heading.

Op zo 26 jul. 2020 09:22 schreef TammyJess <notifications@github.com>:

**Comment by TammyJess** [comment]
Okay!
Not a bug.     :)  Forgive me, though, if I set up a script to remove those blank lines outside of Zim.   :P  
It doesn't seem to affect the page rendering without them, just how the pages get written back to disk.

Side note, I get to do an awful lot of professional page-layout for traditional print-media, so I'm conditioned to having the spacing controls that layout programs like 'InDesign' offer.  Not going to have that within Zim, certainly!  But the gap between headings irritates like a burr under my top.
