### ISSUE TITLE
Zim portable uses local config files

### ISSUE THREAD

**Issue by Atronach** [zim-desktop-wiki/zim-desktop-wiki#1206]
Zim portables seems to inherit $XDG_CONFIG_HOME and $XDG_DATA_HOME of the local Zim installation. E.g. it uses a local notebook on the host computer with path like:
`c:\user\david\documents\zim notebook`
...instead of the notebook on a flash drive like:
`g:\zim notebook`
So notebooks can't travel with the Zim portable on the same flash drive.

The default text editor is also inherited from the local Zim installation. So I'm stuck with basic editors which are preinstalled on all Windows OSes like Notepad or WordPad.

Tested with Zim v0.73.2 on Win10 x64.

**Comment by gittx7765** [comment]
I agree with.
Please make the protable function working.
It is an essential feature.
thanks

**Comment by jaap-karssenberg** [comment]
@fmos can you advice how to tackle this in the installer?

My idea would be to use a hook like "hook-data.py" to read in some intialization script from the same folder as the executable which can setup the environment before loading the zim modules. However that script should only be installed for the portable version and not for the normal version (or a different script for each version).

Is it possible to make the installer place one file or another based on whether it is portable install or not ?

Thanks,

Jaap

**Comment by dardoor** [comment]
How about offering the portable version as a zip/7z archive instead of the installer? This way you also wouldn't need to run as Admin on Windows, like you do now (it's possible to make an installer not elevate, but I think an archive is better anyway).


Also, I don't know what why the "portable" setup is called that way. All the settings, including those of the notebooks, are still in AppData on Windows (the 'shared=False' for the notebook doesn't work, but I guess that's a bug).
Do I need to do something else to make the settings go in the Zim folder? I've seen a mention of an ini file, but that's for an older (deprecated) portable/PAF version, right?
I personally don't like the PAF format at all and would prefer a simple archive that can be extracted and used.

**Comment by fmos** [comment]
> @fmos can you advice how to tackle this in the installer?
> 
> My idea would be to use a hook like "hook-data.py" to read in some intialization script from the same folder as the executable which can setup the environment before loading the zim modules. However that script should only be installed for the portable version and not for the normal version (or a different script for each version).
> 
> Is it possible to make the installer place one file or another based on whether it is portable install or not ?

Yes. This needs to be done at https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/9808183182638276ad1e4dd8ff204b05a65320ac/windows/src/zim-installer.nsi#L168 

I.e. using an "else" branch there e.g. to create/touch a flag file. And checking in hook-data.py for the existence of the flag file.

**Comment by jaap-karssenberg** [comment]
Working on fix for this issue, but got stuck do to broken pyinstaller. Got
hit by issue https://github.com/pyinstaller/pyinstaller/issues/5058

-- Jaap

**Comment by midaspt** [comment]
Excuse me if I'm being dense, but why not default to relative paths in the portable case?

As in '_notebooks\files_', '._\notebooks\files_' (or even '_..\notebooks\files\_') -- they seem easier and more human friendly...

Also, check <https://www.portablefreeware.com/forums/viewtopic.php?t=17712> for a discussion of **Zim** _portability_.

@dardoor: for this specific definition of "_portable_", see the FAQ page at <https://www.portablefreeware.com/faq.php#portable>.

**Comment by jaap-karssenberg** [comment]
Actually this has been fixed with latest release - "portable" install now contains an "environ.ini" config file that configures the lookup paths relative to the install location.

**Comment by dardoor** [comment]
The latest version still writes files in AppData, though.

@midaspt : I think you misunderstood my post, but it doesn't matter.

**Comment by jaap-karssenberg** [comment]
Op za 5 dec. 2020 23:43 schreef dardoor <notifications@github.com>:

> The latest version still writes files in AppData, though.
>

Can you elaborate?


@midaspt <https://github.com/midaspt> : I think you misunderstood my post,

**Comment by dardoor** [comment]
There's a zim folder in AppData\Roaming, which contains a folder with the notebook name and two files: index.db and state.conf.
In AppData\Local\Temp there are also some zim related files and folders (and they don't get deleted on exit).

**Comment by jaap-karssenberg** [comment]
Thanks for checking !

Can you change the "environ.ini" and change "XDG_CACHE_DIR" into
"XDG_CACHE_HOME"
And could you add a new line "TEMP=../temp"

This should prevent the access to the APPDATA folders.

Will patch in next release as well.
