### ISSUE TITLE
Arrow icons in Journal tree

### ISSUE THREAD

**Issue by azarian57** [zim-desktop-wiki/zim-desktop-wiki#1207]
Hello,

I am not sure if it is a bug or not but I would like to report that I cannot see the arrow icons in Journal (which it is presented in the screenshots of the Zim) in windows 10 version. Please have a look below:
![image](https://user-images.githubusercontent.com/2576452/88530728-bd6c0200-cff9-11ea-8df3-3c6c63d9a65d.png)

Kind regards,

**Comment by jaap-karssenberg** [comment]
duplicate report, should be fixed in 0.73.2

**Comment by pfalcon** [comment]
> duplicate report, should be fixed in 0.73.2

Should be closed then, especially that there's no further response.

**Comment by introt** [comment]
Your wish is my command @pfalcon!
