### ISSUE TITLE
Send to fails because of equation

### ISSUE THREAD

**Issue by teufelweich** [zim-desktop-wiki/zim-desktop-wiki#1213]
When I try to use `File > Send To ...` I get the following stack trace:
```python
This is zim 0.73.1
Platform: posix
Locale: en_US UTF-8
FS encoding: utf-8
Python: (3, 7, 8, 'final', 0)
PyGObject: (3, 34, 0)

======= Traceback =======
  File "/usr/lib/python3.7/site-packages/zim/actions.py", line 115, in do_activate
    self.__get__(instance, instance.__class__)()
  File "/usr/lib/python3.7/site-packages/zim/actions.py", line 98, in func
    return self.func(instance, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/zim/gui/uiactions.py", line 174, in email_page
    text = ''.join(self.page.dump(format='plain'))
  File "/usr/lib/python3.7/site-packages/zim/notebook/page.py", line 646, in dump
    return format.Dumper(linker=linker).dump(tree)
  File "/usr/lib/python3.7/site-packages/zim/formats/__init__.py", line 1174, in dump
    tree.visit(self)
  File "/usr/lib/python3.7/site-packages/zim/formats/__init__.py", line 554, in visit
    self._visit(visitor, self._etree.getroot())
  File "/usr/lib/python3.7/site-packages/zim/formats/__init__.py", line 565, in _visit
    self._visit(visitor, child) # recurs
  File "/usr/lib/python3.7/site-packages/zim/formats/__init__.py", line 565, in _visit
    self._visit(visitor, child) # recurs
  File "/usr/lib/python3.7/site-packages/zim/formats/__init__.py", line 565, in _visit
    self._visit(visitor, child) # recurs
  [Previous line repeated 1 more time]
  File "/usr/lib/python3.7/site-packages/zim/formats/__init__.py", line 570, in _visit
    visitor.append(node.tag, node.attrib, node.text)
  File "/usr/lib/python3.7/site-packages/zim/formats/__init__.py", line 1244, in append
    strings = method(tag, attrib, [])
  File "/usr/lib/python3.7/site-packages/zim/formats/__init__.py", line 1290, in dump_object
    assert isinstance(output, (list, tuple)), "Invalid output: %r" % output
AssertionError: Invalid output: './equation.png'
```
Exporting to HTML is working fine. `equation.png` is a LaTeX equation generated with the Equation Editor.
### Reproduction: 
   1. Create new notebook. 
   2. Insert equation with `Insert > Equation`.
   3. Export with `File > Send To ...` .

**Comment by Nick222** [comment]
Xubuntu 20.04
Zim 0.73.2

> DEBUG: Action: email_page
> DEBUG: open_url(mailto:?subject=%D0%91%20%D0%94%D0%BE%D0%B3%D0%BE (and so on - many pages)
> DEBUG: Got type "x-scheme-handler/mailto" for "mailto:?subject=%D0%91%20%D0%94%D0%BE%D0 (and so on - many pages)
> DEBUG: Loading config from: /usr/share/applications/exo-mail-reader.desktop
> INFO: Spawning: ('exo-open', '--launch', 'MailReader', 'mailto:?subject=%D0%91%20%D0%94%D0%BE%D (and so on - many pages)
> DEBUG: Running ErrorDialog
> DEBUG: Ошибка запуска exo-open
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/zim/applications.py", line 352, in spawn
>     GObject.spawn_async(argv, flags=flags, working_directory=cwd)
> gi.repository.GLib.GError: g-exec-error-quark: Не удалось выполнить процесс-потомок «exo-open» (Слишком длинный список аргументов) (5)

(too long list of arguments)

**Comment by pfalcon** [comment]
> When I try to use File > Send To ...

Worse, this happens even when trying to cut/copy a wiki fragment with "object" to clipboard. In my case, I have a GraphViz diagram and get:

```
  File "/mnt/hdd/projects-3rdparty/PIM/zim-desktop-wiki/zim/formats/__init__.py", line 1249, in append
    strings = method(tag, attrib, [])
  File "/mnt/hdd/projects-3rdparty/PIM/zim-desktop-wiki/zim/formats/__init__.py", line 1295, in dump_object
    assert isinstance(output, (list, tuple)), "Invalid output: %r" % output
AssertionError: Invalid output: './diagram.png'
```

And just as in https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/1248, nothing is visibly reported to user.

(git master 81576e621b1766b40fb6960c7aa609efb3a844d7)

@jaap-karssenberg: Can you please triage this, arguably high-priority, issue? Thanks.

**Comment by pfalcon** [comment]
Ok, quick-hack fix I came to is:
~~~
--- a/zim/plugins/base/imagegenerator.py
+++ b/zim/plugins/base/imagegenerator.py
@@ -87,7 +87,10 @@ class BackwardImageGeneratorObjectType(ImageGeneratorObjectType):
                        if attrib['type'].startswith('image+'):
                                attrib = attrib.copy()
                                attrib['type'] = attrib['type'][6:]
-                       return dumper.dump_img(IMAGE, attrib, None)
+                       res = dumper.dump_img(IMAGE, attrib, None)
+                       if isinstance(res, str):
+                               res = [res]
+                       return res
 
 
 class ImageGeneratorModel(SignalEmitter):
~~~

With that, I can cut diagram object and paste it back to the same page.

But if I paste to another page, it doesn't really work. Because object "attachment" files are never moved along. Were inter-page object pastes ever tested at all?

Likewise, if I copy object and paste even to the same page, no code cares to make copies of the attachments under different names. So, instead of 2 independent objects, it becomes a kind of "symlink" to a single underlying data. Which is kinda cool in some sense and may have its use, but not what user expects when they copy/paste stuff.

**Comment by pfalcon** [comment]
> But if I paste to another page, it doesn't really work. Because object "attachment" files are never moved along. Were inter-page object pastes ever tested at all?

Related: https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/45
