### ISSUE TITLE
Suggestion for improving "Turn page name into tags for task items"

### ISSUE THREAD

**Issue by fladd** [zim-desktop-wiki/zim-desktop-wiki#1214]
The option "Turn page name into tags for task items" is currently behaving rather unexpectedly:

It creates tags not only for the page itself, but also for all parent pages. So if the page is `Projects:ProjectA:Ideas:AwesomeIdea`, and there is a task on that page, then the task gets the tags "Projects", "ProjectA", "Ideas" and "AwesomeIdea". This will very quickly clutter the tags view in the task list, as there will be many "tags" like this.

It currently also creates tags for journal pages, leading to tags called, for instance, "02", which is not that informative and also clutters the tags view.

Often it is also not even desirable to have the page the task is on itself be the tag, but rather a certain parent (not all parents).

My suggestion would hence be to mark pages that should become tags for tasks on them and their subpages (e.g. by including some meta data property). The default would be that new pages are not getting that property. The user could then actively mark pages that they want to show as tags (if they have tasks), and in the examples below, one could, for instance, only have that task tagged as "ProjectA", by giving only the "ProjectA" page that property. I believe this would be much more flexible and, more importantly, much more useful.

**Comment by pfalcon** [comment]
> This will very quickly clutter the tags view in the task list, as there will be many "tags" like this.

Can you please explain how to access this "tags view in the task list"? I'm asking because I enabled "Turn page name into tags for task items" option in my notebook, and don't see any visible effects of it all. I'm using Zim 0.73.2. (Which version is yours?)

**Comment by nelas** [comment]
@pfalcon you have to open the Task List window `View > Task List (Shift+Alt+T)`

**Comment by pfalcon** [comment]
> you have to open the Task List window View > Task List

Interesting, thanks. The doc, https://zim-wiki.org/manual/Plugins/Task_List.html , doesn't seem to mention such a menu item, and I personally overlooked it. (My primary way to interact with tasks was "Tasks" pane on the edge of the main window, similar to "Index", "Tags", "Journal" panes).

**Comment by jaap-karssenberg** [comment]
Making this "won't fix" - I understand your use case, but I'm thinking in a different direction
