### ISSUE TITLE
FR: Write protect links

### ISSUE THREAD

**Issue by diovudau** [zim-desktop-wiki/zim-desktop-wiki#1217]
This is only a mild inconvenience, but I wanted to ask anyway:

Quite often I accidentaly input a letter in the middle of a link (my zim start site is a list of links). The link will then link to a new empty page.

Maybe make editing in the middle of a link impossible, except with context menu -> edit link?

**Comment by jaap-karssenberg** [comment]
Does the "toggle editable" button on the toolbar help?

Op ma 3 aug. 2020 09:04 schreef diovudau <notifications@github.com>:

**Comment by diovudau** [comment]
Unfortunately not since it is global. If I could the whole page read-only that would be an acceptable workaround. For the times I write on the start page (that is also the place for my "most urgent tasks") I could re-activate writing.

**Comment by jaap-karssenberg** [comment]
Can I ask why you often for accidently in links? Is there something to fix
to avoid mistyping?

My thinking is that mistyping is always bad, not just in links.

Op ma 3 aug. 2020 10:08 schreef diovudau <notifications@github.com>:

**Comment by diovudau** [comment]
After clicking a link, or moving the cursor there and press enter, and then going back to the previous page the cursor is in the link.
Sometimes I think I have a different window in focus and start typing, but zim was still in focus.

**Comment by pfalcon** [comment]
> My thinking is that mistyping is always bad, not just in links.

+1. "Easy to mistype" is the reverse side of "easy to type", and that's the selling point of Zim. In normal wiki, you would look at static page, if you want to edit, to you would click a button, make a changes, click "diff" button to review changes and see there're no mistypes, then click "save" button. In Zim, you just edit right away.

I don't think that adding arbitrary restrictions to editing (e.g. editing of links) in Zim would cut for most users. The way to get the best of both worlds (WYSIWYG editing and staged editing) would be to enable version control (Git integration), review pending changes, undo mis-edits, and the commit good updates periodically.
