### ISSUE TITLE
Cannot create new pages.

### ISSUE THREAD

**Issue by luyten7268A** [zim-desktop-wiki/zim-desktop-wiki#1220]
While trying to create a new page, sometimes this error appears ![2020-08-07_05-30-35](https://user-images.githubusercontent.com/69336687/89609504-f6b13700-d86f-11ea-815c-d2dd59e77fcd.png)
, and then strange behaviour occurs - objects stop appearing in the index, or jump around when hovered on with the mouse, or show as being subpages when they are root-level pages.
![image](https://user-images.githubusercontent.com/69336687/89609796-c74efa00-d870-11ea-8e70-6c976d35ed14.png)
![image](https://user-images.githubusercontent.com/69336687/89609859-f2394e00-d870-11ea-9b70-1899cc7b8a37.png)
There seems to be little rhyme or reason to why this happens - on restarting the program and trying to create new subpages, I managed to create four before trying to create the actual one I _wanted_ to create, at which point the same error appeared.
![image](https://user-images.githubusercontent.com/69336687/89610004-58be6c00-d871-11ea-9475-c4b2401e4fef.png)

I'm running windows 10, english (en-uk) language.
Apologies if my etiquette on here is bad - this is my first time using github.

**Comment by jaap-karssenberg** [comment]
What version of zim are you using? The recent 0.7x installer or the older
0.6x installer ?

Are you using a "special" folder, e.g. dropbox shared folder etc.?  I
assume not given the file path, just checking.

Wondering if there might be an issue due to the length of the file names -
can you try creating them manually in the file browser?  (The full name as
shown in the error message including the ".zim-new~" postfix.

Regards,

Jaap

P.S. if the index is out of whack, try the "tools" -> "update index" menu
item, that should refresh the index state

**Comment by luyten7268A** [comment]
It's not in a special folder or anything either, no.
It seems like filename length may be the issue here - on trying to manually create the text file for the page, it stops accepting input after a while. Would moving the notepad to a directory at the root of the filesystem perhaps alleviate this? I attempted to enable NTFS long paths in regedit/gpedit but that seemed to Not Work. (I did not actually know win10 had a file path length limit before this, huh!)
![image](https://user-images.githubusercontent.com/69336687/89671925-c30bf680-d8db-11ea-967c-ae6a7c6885e0.png)

Also to answer the first question: I'm running 0.69.1 - should I update?

Thanks for your help
-Caz

**Comment by luyten7268A** [comment]
Actually also on the note of relocating the notepads... how do I do that (and change the default zim directory), actually? The only things I've been able to find on that are for linux and don't seem applicable to the win10 install

**Comment by fdt-dev** [comment]
Sorry to chime in on that issue. As far as I remember NTFS has a path lenght limit of 260 characters. I'm not sure whether this information is still valid. (I originally thought the path length limit on Windows systems is really only 256, but apparently it is slightly longer.) There seem to be exceptions (see the article linked below) but I'm not completely sure under which circumstances those apply. 
See here:
[https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#maximum-path-length-limitation](url)

**Comment by jaap-karssenberg** [comment]
My advice is to just use shorter page names and put the full title in the
page itself. The page name and the title in the page do not need to be the
same.

In Zim 0.73 you get a better error message for path length.





Op vr 7 aug. 2020 23:46 schreef fdt-dev <notifications@github.com>:
