### ISSUE TITLE
Issue: If it asks for example for HTML input zim will paste HTML formatted text automatically

### ISSUE THREAD

**Issue by thejeshgn** [zim-desktop-wiki/zim-desktop-wiki#1221]
> Default format for copying text to the clipboard allows you to set the preferred format when you copy some text from zim and paste it in an other application. Default is just plain text, but you can also choose to paste wiki formatted text. This option will only affect copy-pasting where the receiving application asks for text input (like a text editor), if it asks for example for HTML input zim will paste HTML formatted text automatically.

https://www.zim-wiki.org/manual/Help/Preferences.html

I try to copy from zim and paste it into Google Doc or Gmail rich ext. It actually pastes it as "text" or "Wiki" or other markup specified in the preference. It doesn't paste the rendered HTML. I usually do print to browser and copy from browser. But I was wondering if there is anything that I am missing.

**Comment by thejeshgn** [comment]
Oh, found this. https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/326

**Comment by jaap-karssenberg** [comment]
Good point - should probably update the manual

This is broken at the moment due to issues with the Gtk3 API for copy-paste
- it should work om zim 0.6x versions (Gtk2) but I don't recommend going
back to those

See https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/326

-- Jaap
