### ISSUE TITLE
Double curly braces do weird stuff with pasted code

### ISSUE THREAD

**Issue by dgloriaweb** [zim-desktop-wiki/zim-desktop-wiki#1225]
Hi, I use zim wiki for software development knowledge base, and Laravel Blade syntax seems like doing weird things.
Is there a way to escape these characters not to transfer my code to unknown stuff?
Example: 

```
            @foreach($assignments as $assignment)
            <option value="{{ $assignment['color_id'] }}">
                {{ $assignment['color']['color_no'] }}
            </option>
            @endforeach
```

Appears as: 
```
			@foreach($assignments as $assignment)
			<option value=" X">
				X
			</option>
			@endforeach
```

I've found one solution, changing text to verbatim, that doesn't remove the {{ }} bit, is there a better way?

**Comment by jaap-karssenberg** [comment]
Yes, format it as verbatim text or use the source view plugin.

Zim uses wiki formatting, so your code gets interpreted if you don't make
it a verbatim or code block.

Op di 11 aug. 2020 21:11 schreef Beatrix Gloria Ducz <
notifications@github.com>:

**Comment by jaap-karssenberg** [comment]
Latest version also has "paste as verbatim" in the context menu to make this case easier.
