### ISSUE TITLE
Unexpected error (the worst type)!

### ISSUE THREAD

**Issue by hrbruen** [zim-desktop-wiki/zim-desktop-wiki#1226]
The following is from the  server output

ERROR: Unexpected error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/zim/www.py", line 255, in __call__
    content = self.render_page(page)
  File "/usr/local/lib/python3.6/site-packages/zim/www.py", line 317, in render_page
    title=page.get_title(),
  File "/usr/local/lib/python3.6/site-packages/zim/notebook/page.py", line 720, in get_title
    return tree.get_heading_text() or self.basename
  File "/usr/local/lib/python3.6/site-packages/zim/formats/__init__.py", line 396, in get_heading_text
    return self._elt_to_text(heading_elem)
  File "/usr/local/lib/python3.6/site-packages/zim/formats/__init__.py", line 390, in _elt_to_text
    strings.append(self._elt_to_text(e)) # recurs
  File "/usr/local/lib/python3.6/site-packages/zim/formats/__init__.py", line 391, in _elt_to_text
    return ''.join(strings)
TypeError: sequence item 0: expected str instance, NoneType found
127.0.0.1 - - [12/Aug/2020 18:23:42] "GET /Cleanup_2020/Database/club/datadict.html HTTP/1.1" 500 21

the browser itself juat showa a blank page with "Internal Server Error"

any clues?
tia
HR Bruen

**Comment by hrbruen** [comment]
Found it!
It happens when the page title has "doubled" embedded formats. Here's an example where the italics+bod attributes in the source page cause the error:

Content-Type: text/x-zim-wiki
Wiki-Format: zim 0.6
Creation-Date: 2020-08-12T13:55:34+09:30

====== Data Dictionary for table: //**club**// ======

Created Wednesday 12 August 2020

===== Columns =====
| column    | description                                                                       | position | datatype | notnull | ispk | idx  |
|-----------|-----------------------------------------------------------------------------------|----------|----------|---------|------|------|
| name      | The name of the registered club                                                   | 1        | text     | true    | true | true |
| hometrack | (FK) The usual sportsground where the club condudts meetings                      | 2        | bpchar   | true    |      | true |
| level     | Rates the club as a professional (PRO), amateur (AM) or picnic(PICNIC) level club | 3        | varchar  |         |      |      |
| rastate   | The State Authority  governing  the club                                          | 4        | varchar  |         |      | true |
| url       | The internet web site for the club                                                | 5        | varchar  |         |      |      |
| raname    | The internet short name for the club                                   		    | 6        | text     |         |      | true |

**Comment by jaap-karssenberg** [comment]
Double of #1240
