### ISSUE TITLE
How to change the default language for zim，I can't find icon or method

### ISSUE THREAD

**Issue by Franklyn1987** [zim-desktop-wiki/zim-desktop-wiki#1227]
How to change the default language for zim，I can't find icon or method

**Comment by jaap-karssenberg** [comment]
You need to set an environment variable "LANG" before zim starts.

-- Jaap

**Comment by pdecat** [comment]
FWIW, I had to set `LANGUAGE` to force English on my system. It has [higher priority than `LANG`](https://www.gnu.org/software/gettext/manual/html_node/Locale-Environment-Variables.html).

**Comment by micha06de** [comment]
Does this also work when starting via zim.py in MSYS2 MSYS?
the environment variable is set
```
micha@LAP-9 MSYS ~
$ echo $LANG 
de
```
but the language is still not German.
Is "de" correct for Germany?

**Comment by jaap-karssenberg** [comment]
This works for me running from source in MSYS

  $ LANGUAGE=de_DE python3 ./zim.py

**Comment by micha06de** [comment]
Hello since the update to 7.5.1 this no longer works. What has changed, how can I set the language now?

**Comment by jaap-karssenberg** [comment]
Just tested and works fine for me. If you are running from source you might
need to run "./setup.py build_trans" first.

--- Jaap

**Comment by micha06de** [comment]
> "./setup.py build_trans"

Thanks for the quick reply, that was it!
