### ISSUE TITLE
Notebook not editable on other computers

### ISSUE THREAD

**Issue by pmaen** [zim-desktop-wiki/zim-desktop-wiki#1228]
I use Zim on different computers. I sync the folders with MEGAsync (all files included; double checked to be on the safe side).
Now if I try to open a notebook created on Computer1 (Ubuntu 20.04) on Computer2 (Win10) I can view all pages and all links work but I'm unable to edit the document.
I'm not sure if this is of interest but after having installed Zim on Computer2 I had to update my system variables because Zim made it unable for Texmaker (LaTeX-Software) to compile documents.
Also Zim export to any file type except HTML isn't working.

**Comment by jaap-karssenberg** [comment]
If you are not able to edit please check:
1. You did not accidentally hit the "toggle editable" button in the toolbar
2. Files actually have read/write permissions and you have folder
permission to create new files

**Comment by pmaen** [comment]
Thanks. For some odd reason the read/write permissions had been restricted
