### ISSUE TITLE
Strange loading message in status bar

### ISSUE THREAD

**Issue by thejeshgn** [zim-desktop-wiki/zim-desktop-wiki#1229]
* It was only one loading message yesteray
* today it became two
* Closing and reopening doesn't help

![2020-08-14T05:54:15](https://user-images.githubusercontent.com/76114/90248973-49ce4f80-de57-11ea-9c14-d1084adc4559.png)

**Comment by thejeshgn** [comment]
version : 0.73.2
Ubuntu

**Comment by jaap-karssenberg** [comment]
I just checked the code base and the string "...loading..." does not appear
anywhere in our code.

From the screenshot it looks like the message appears in the bottom pane.
Do you have any non-standard plugins?

**Comment by thejeshgn** [comment]
I did have a couple. I removed copy as HTML pugin but I also restarted computer. I dont know which one fixed it.
