### ISSUE TITLE
Move menubar to new headerbar

### ISSUE THREAD

**Issue by sojusnik** [zim-desktop-wiki/zim-desktop-wiki#1233]
Love the new GTK headerbar!

To follow Gnome's HID, I propose to put the menubar in the new headerbar, as f.i. implemented in Gedit.

![grafik](https://user-images.githubusercontent.com/1245718/90617246-bb6b1c80-e20e-11ea-87ea-2ddd32c56f74.png)

**Comment by jaap-karssenberg** [comment]
No need to open a ticket for that. I'm well aware of the hid. Just work in
progress.

Would be great help to actually have a design how to organize all items of
the current menu (minus "format" and "insert") in a popover menu.

Regards,

Jaap

Op wo 19 aug. 2020 11:26 schreef sojusnik <notifications@github.com>:

**Comment by sojusnik** [comment]
The obvious first step could be just mirroring all the top level menu entries (see green rectangle) and then making a small survey here to determine the 4-6 most used commands (see red rectangle) and add them separately before the expandable top level menu entries? Settings, help and about are usually always at the bottom, as shown in the screenshot.

![grafik](https://user-images.githubusercontent.com/1245718/98444305-2db61380-2111-11eb-9c7b-d269719e1894.png)

**Comment by introt** [comment]
What'll happen to the Alt+mnemonic -shortcuts? In Gedit, those can be accessed after the additional step of opening the popup with F10, but in addition to worse UX that doesn't seem to be a standard; in Nautilus F10 opens the Actions menu instead and there doesn't seem to be a shortcut for opening the hamburger menu at all!

> making a small survey here to determine the 4-6 most used commands

Idea: instead of n most used actions, we could integrate a Command Palette ("a search dialog to allow quickly executing menu entries") style search box into the popover menu and focus the input field automatically when opened via the keyboard shortcut.

**Comment by sojusnik** [comment]
> What'll happen to the Alt+mnemonic -shortcuts? In Gedit, those can be accessed after the additional step of opening the popup with F10, but in addition to worse UX that doesn't seem to be a standard; in Nautilus F10 opens the Actions menu instead and there doesn't seem to be a shortcut for opening the hamburger menu at all!

I'm for the Gedit approach.

> Idea: instead of n most used actions, we could integrate a Command Palette ("a search dialog to allow quickly executing menu entries") style search box into the popover menu and focus the input field automatically when opened via the keyboard shortcut.

Or instead of integrating this command palette in the popover, [this](https://github.com/zim-desktop-wiki/zim-desktop-wiki/pull/1376) plugin could be made a default Zim plugin. This would also solve the above-mentioned Alt+shortcuts issue.

**Comment by jaap-karssenberg** [comment]
There is a command palette plugin in the dev branch already :)

Op wo 8 sep. 2021 15:01 schreef sojusnik ***@***.***>:

**Comment by introt** [comment]
> Or instead of integrating this command palette in the popover, this plugin could be made a default Zim plugin. This would also solve the above-mentioned Alt+shortcuts issue.

That's the one I was referring to; it's been renamed to Command Palette and it's included with Zim as of commit 737811a0a5f8bbdea0733d9b954dad30645c1565. It's a bit different than mnemonics though, needs way more keypresses for the same things.
