### ISSUE TITLE
Make the new actionbar optional

### ISSUE THREAD

**Issue by sojusnik** [zim-desktop-wiki/zim-desktop-wiki#1234]
Since I completely rely on keyboard shortcuts, I would love to have an option to hide the new actionbar to declutter the interface.

**Comment by jaap-karssenberg** [comment]
Have been looking into how to make it auto-hiding as an option. But fully
hiding could be first step.

Op wo 19 aug. 2020 11:31 schreef sojusnik <notifications@github.com>:

**Comment by sojusnik** [comment]
Would appreciate that!
