### ISSUE TITLE
Mermaid diagrams

### ISSUE THREAD

**Issue by evan54** [zim-desktop-wiki/zim-desktop-wiki#1237]
Is there a way to do mermaid diagrams in zim? Or would this be possible to add through a plugin?

**Comment by jaap-karssenberg** [comment]
I have no idea what "mermaid" is. If it looks like one of the things we
have a plugin for probably a plugin is not too hard.

Op wo 19 aug. 2020 17:13 schreef evan54 <notifications@github.com>:

**Comment by evan54** [comment]
Sorry was referring to this

https://mermaid-js.github.io/mermaid/#/n00b-overview

Some way of doing flow chart diagrams I guess

**Comment by jaap-karssenberg** [comment]
Ah yes, very similar to other diagram plugins. If you start with the
"diagrameditor.py" plugin, it can easily be modified to run mermaid instead.

-- Jaap

**Comment by k4nzdroid** [comment]
@evan54 https://github.com/zim-plugins/insert_mermaid.git  

give it a shot.

**Comment by evan54** [comment]
didn't work for me - do I need to somehow run a npm server or smth similar for mermaid?

![image](https://user-images.githubusercontent.com/10644399/107509379-78ac5080-6b70-11eb-9c3a-8630e2da3617.png)
