### ISSUE TITLE
Verbatim background color doesn't change

### ISSUE THREAD

**Issue by type2b** [zim-desktop-wiki/zim-desktop-wiki#1238]
`[Tag pre]
foreground=#000000
background=#e8e8e8
paragraph-background: #e8e8e8`

There is white space between lines.
(It would be nice to add a "border-radius")

**Comment by sanjarcode** [comment]
Try this, works for me.
![image](https://user-images.githubusercontent.com/48156230/102082314-c2f6a700-3e37-11eb-9eb1-b23449d146ce.png)

I've tried to add a border-radius, coz I don't like rectangular highlight, couldn't do it from style.conf. I've also editing ```~.config/gtk-3.0/gtk.css``` too, but couldn't do it. I think Zim has an internal render mechanism, with custom tags, which I cannot figure out by just looking at the code. 
See this https://zim-wiki.org/manual/Help/Config_Files.html

**Comment by pfalcon** [comment]
Makes me wonder if github has deeply ingrained light grey background for preformatted (both char- and line-based) in everyone's brain, and it just should be set by default.

**Comment by jaap-karssenberg** [comment]
The textview styles are indeed not controlled by css, this is not specific
to Zim but how the gtk textview is implemented.

Op ma 14 dec. 2020 13:49 schreef Muhammad Sanjar Afaq <
notifications@github.com>:

**Comment by pfalcon** [comment]
In my Markdown branch, I now render light gray background for preformatted text by default: https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/26#issuecomment-755966971

Like, it would be nice to let use override that, but I want to have good default by default, without digging into config files. Especially if it's unclear if config files work. (And I dunno if my changes would only complicate that, and that's the whole point - I don't want to munge config files for such trivialities in the first place.)
