### ISSUE TITLE
Plugin "source view", misinterpretation of '/'

### ISSUE THREAD

**Issue by ghost** [zim-desktop-wiki/zim-desktop-wiki#1239]
To me, it seems like the "source view" plugin is misinterpreting the forward slash '/'.

I'm running the newest zim version from github.

For example, a screenshot of an authorized_keys file displayed in the source view plugin.

![zim-issue-misinterpretation-of-slash](https://user-images.githubusercontent.com/30551733/90984943-bf819c00-e578-11ea-8975-a45fbf0369b1.png)

**Comment by pfalcon** [comment]
> I'm running the newest zim version from github.

"newest zim version from github" is always changing, please specify the exact commit you used at that time.

> For example, a screenshot of an authorized_keys file displayed in the source view plugin.

And, what's wrong there? Please explain with words, not just pictures. And also the steps to reproduce it - a developer who'll look into this won't have your authorized_keys.

**Comment by introt** [comment]
Seems you've selected an inappropriate highlight language. Ghost busted.
