### ISSUE TITLE
Theme path on Windows doesn't match manual

### ISSUE THREAD

**Issue by Sifayne** [zim-desktop-wiki/zim-desktop-wiki#1241]
I'm on the latest Zim-0.73.2 windows installer (installed as portable but this also happened when installed "normally").

The manual lists the configuration paths for Windows as:
![image](https://user-images.githubusercontent.com/17114940/91471999-0f4fb400-e854-11ea-9ae5-566da6bed14d.png)

And further down it lists the path for gtk theming as:
![image](https://user-images.githubusercontent.com/17114940/91472066-33ab9080-e854-11ea-88db-7a2d80aa3333.png)

But if I create the gtk-3.0/gtk.css file none of the theming effects zim.
(at ...\AppData\Roaming\zim\config\gtk-3.0\)

But if I put the theme at ...\AppData\Local\gtk-3.0\ 
Then everything works just fine.

So I'm thinking there's a file path not being recognized for gtk. 
Because everything else in the regular config location, like the rest of the preferences are recognized properly.

**Comment by jaap-karssenberg** [comment]
Gtk is loaded even before these paths are set. (And I'm not sure it would
look at the paths on windows anyway - will need to test that.)

Way to get it working it to use "etc/" and "share/" paths relative to the
folder where the executable is installed.

-- Jaap

**Comment by grnwood** [comment]
I've wrestled with that one before, the solution I like is to just set the XDG paths in Win as 

![image](https://user-images.githubusercontent.com/1699293/92485675-de0aa880-f1b0-11ea-9d3f-eb8bb461cf62.png)

(I run from source but shouldn't matter).

Then 'config' folder has gtk theme I want under it.

config/gtk-3.0/...
