### ISSUE TITLE
Link is removed when formating text to strike

### ISSUE THREAD

**Issue by ddomingues1970** [zim-desktop-wiki/zim-desktop-wiki#1245]
When formatting a link to strike the link is removed. 

**Step 1 - Inserting Link**

Menu -> Insert -> Link...
Link to: https://www.google.com/
Text: Google

**Step 2 - Formatting Link Text**

Mark (select) _Google_ Text
Menu -> Format -> Strike

**Comment by jaap-karssenberg** [comment]
What version of Zim are you using?

Op wo 2 sep. 2020 16:44 schreef Daniel Domingues <notifications@github.com>:

**Comment by mikem23** [comment]
I believe I'm seeing the same issue. Here is what I'm doing.

1. Make two lines of text where the first is plain and the second is a link. E.g.

```
Ut enim ad minim veniam,
[[http://localhost/|quis nostrud exercitation ullamco laboris.]]
```

2. Select both lines and apply a format. I've tried italics, strikethrough, and highlight.

Initially the text will appear correct, but the underlying markup will be:

```
~~Ut enim ad minim veniam,[[http://localhost/|
quis nostrud exercitation ullamco laboris.]]~~
```

Upon page reload, the text does not appear as intended because the markup is invalid.

I would have expected this:

```
~~Ut enim ad minim veniam,~~
~~[[http://localhost/|quis nostrud exercitation ullamco laboris.]]~~
```

**Comment by mikem23** [comment]
Attaching my example

[link_format_bug.txt](https://github.com/zim-desktop-wiki/zim-desktop-wiki/files/5831327/link_format_bug.txt)

**Comment by mikem23** [comment]
I'm using Zim-0.73.4-1.fc32.noarch on Fedora 32

**Comment by mikem23** [comment]
The problem replicates if I run from master branch.

Python version: python3-3.8.6-1.fc32.x86_64

**Comment by jaap-karssenberg** [comment]
@mikem23 my guess is that what you report is not what @ddomingues1970 meant.

Before version 0.73 formats were mutually exclusive, so striking through a link removes the link formatting.

In version 0.73 and newer you can combine the formats, but there is a bug in handling the newline.

Will use this ticket to track the bug for version 0.73 and newer.

**Comment by mikem23** [comment]
Thank you! Fix works for me
