### ISSUE TITLE
version control plugin: "View Annotated" is broken, no visible error reported to user.

### ISSUE THREAD

**Issue by pfalcon** [zim-desktop-wiki/zim-desktop-wiki#1248]
git master 81576e621b1766b40fb6960c7aa609efb3a844d7

Steps to reproduce:

1. Have VCS enabled for notebook (git in my case).
2. File -> Versions
3. Select "Page" radiobox.
4. Click "View Annotated" button.
5. Nothing happens.

In the log, following is shown:
```
Traceback (most recent call last):
  File "/mnt/hdd/projects-3rdparty/PIM/zim-desktop-wiki/zim/plugins/versioncontrol/__init__.py", line 857, in <lambda>
    ann_button.connect('clicked', lambda o: self.show_annotated())
  File "/mnt/hdd/projects-3rdparty/PIM/zim-desktop-wiki/zim/plugins/versioncontrol/__init__.py", line 999, in show_annotated
    annotated = self.vcs.annotated(file)
AttributeError: 'GITApplicationBackend' object has no attribute 'annotated'
```

So, the issue seems to be a typo in the source code - `.annotated()` used instead of `.annotate()`. But much bigger issue is that no error is reported to user (and the log is not shown by default, and is hard to get to).

I know that in some place, a GUI dialog showing an exception backtrace is presented to user, can this please be made consistent for cases like this? (Or there can be unknown number of similar bugs lurking around.)

Independent from that, it would be nice to promote a way of running Zim when log is output to stderr, to be before users' eyes.

**Comment by jaap-karssenberg** [comment]
Oops - typo in commit message

**Comment by introt** [comment]
thanks, i've included the fix in a related pr

yep, some things are broken silently - feel free to open a new thread under the development category to discuss that
