### ISSUE TITLE
Discussion: Hyphens in tag names

### ISSUE THREAD

**Issue by pfalcon** [zim-desktop-wiki/zim-desktop-wiki#1250]
It seems that currently (0.73.2) hyphen character is not recognized as a part of tag: Using `@foo-bar` in a page renders as **@foo**-bar, and consequently "foo" is used as a tag.

I'd like to open discussion whether it makes sense to support hyphens in tags. There definitely should be a way to make long, multiword tags, and current way to do that would be to @use_underscores, but some people think that @hypens-are-more-aesthetically-pleasing.

Then, there're 2 opposite arguments for supporting (resp. not supporting) hyphens in tag names:

1. It clearly doesn't make much sense to be able to write **@foo**-bar, where "foo" is a tag, and "-bar" is randomly suffixed to it. Then, why not include hyphen in the allowed chars, and let people use it, if they want?
2. OTOH, there's a question of interoperability. If other software/systems don't support hyphen, it may become a point of unneeded surprises and frustration for users who got used to hyphens with Zim. As an example, Twitter doesn't seem to allow hyphens in its hashtags. In this case, it may be a good idea to actively discourage users from using hyphens in Zim, and that's effectively what it currently does.

**Comment by sojusnik** [comment]
I'm d'accord with you on your second point — consistency and simplicity outweigh the flexibility of having hyphens in tags.

**Comment by fnx2k** [comment]
I **do need** hyphen in tags.

In french there are some words with hyphen, 
In addition, I would like to use hyphen for strings like project name or part number (ex:  ProjectA-UseCase, D-PADT, THX-2154)
