### ISSUE TITLE
Links with Multipe Words Via Syntax 

### ISSUE THREAD

**Issue by mtwb47** [zim-desktop-wiki/zim-desktop-wiki#1251]
I don't know if this is already possible or not (I didn't find it in the docs, but maybe I missed it), but it'd be nice if it were possible to add in links that contained multiple words without having to use the link dialogue box or using the keybinding. For example

`+New Ideas`

In vimwiki I think this is done by using [[]] so maybe something like + [[]] would work, IDk.

**Comment by pfalcon** [comment]
Type `[[New Ideas]]`, hit Ctrl+R. This is in the docs (that you can enter arbitrary markup this way).

**Comment by mtwb47** [comment]
Awesome! Thanks so much!
