### ISSUE TITLE
Pane proportions resets to default

### ISSUE THREAD

**Issue by seihtam** [zim-desktop-wiki/zim-desktop-wiki#1252]
When opening a notebook though the "Open another notebook..." file menu the second time in the same session, then the pane proportions gets reset to default in the opened notebook.

How to reproduce:
1. Create two notebooks: test1 and test2.
2. Change the pane proportions to something non-default in notebook test2. In the `state.conf` this will for example look like:
```
left_pane=[true,65,"PageIndexWidget"]
right_pane=[true,868,"SidePaneToC"]
```
3. Close both notebooks.
4. Open notebook test1.
5. Open notebook test2 by clicking "File > Open another notebook..." in notebook test1 and close notebook test2 again. Notice the non-default pane proportions are still intact in the GUI and also in `state.conf`.
6. Open notebook test2 again through "File > Open another notebook..." in the same notebook test1 session. The pane proportions for notebook test2 are immediately reset to the default value when the notebook is opened. The `state.conf` for notebook test2 will now for example look like this:
```
left_pane=[true,200,"PageIndexWidget"]
right_pane=[false,200,null]
```
7. All subsequent openings of notebook test2 from the same notebook test1 session will result in the pane proportions to be reset.

Both left and right pane proportions is reset. This only happens when opening the notebook through "File > Open Another Notebook...". It doesn't happen when opening notebook by clicking the .zim file.

I reproduced this on a fresh installation of Zim. I'm using Zim version 0.73.2 on Windows 10, but it also happened in ealier versions.

**Comment by introt** [comment]
Can you reproduce this with the latest version of Zim?

**Comment by seihtam** [comment]
No I am not able to reproduce the issue in Zim 0.74.3. Seems like it got fixed at some point :)
