### ISSUE TITLE
"HACKING" doc/notebook is mentioned in various docs, but was gone in the meantime

### ISSUE THREAD

**Issue by pfalcon** [zim-desktop-wiki/zim-desktop-wiki#1256]
It was removed in commit ed0cef97e7a9cc7d86b683a0291baa9c791f8578. BTW, that commit has a description of "Created CONTRIBUTING.md", but that doesn't tell the whole truth, again, the main effect of that commit is removing a "HACKING" notebook. So, would be nice to have more detailed commit messages, detailing both what actually being done, and *why*.

And quickly looking thru the commit diff, it seems that not all info was converted over to CONTRIBUTING.md (but most was, yeah).

I'll add links to places where HACKING is still mentioned as time permits.

**Comment by pfalcon** [comment]
https://github.com/jaap-karssenberg/zim-wiki/wiki/Plugins :

> Best resource to start is the notebook in the zim source code. 

Doesn't mention "HACKING" explicitly, but apparently about it.

**Comment by jaap-karssenberg** [comment]
Fixed in b020567388375c5e5b5173944de95e79dcbd84a6
