### ISSUE TITLE
Support tel: links

### ISSUE THREAD

**Issue by thejeshgn** [zim-desktop-wiki/zim-desktop-wiki#1257]
May we can support bunch of operating system deep links (URI). Popular ones are

1. maito:   already supported
2. git://
3. webcal

Official list is here. https://en.wikipedia.org/wiki/List_of_URI_schemes

May be we can allow user to add/edit just like emojis or wiki urls.

**Comment by Self-Perfection** [comment]
Related discussion: [Can't use geo: URI in links (or any arbitrary URI scheme)](https://bugs.launchpad.net/zim/+bug/1572542)

**Comment by introt** [comment]
Duplicate of #513
