### ISSUE TITLE
zim doesn't start: AttributeError: 'ElementTree' object has no attribute 'getiterator'

### ISSUE THREAD

**Issue by kparal** [zim-desktop-wiki/zim-desktop-wiki#1258]
Hello, I recently upgraded my system to Fedora 33 (in development), which contains Python 3.9 (not sure if it's the cause of the problem or not), and Zim can't be started at all (even with a clean profile). It opens up a message box containing:

```
This is zim 0.73.2
Platform: posix
Locale: en_US UTF-8
FS encoding: utf-8
Python: (3, 9, 0, 'candidate', 1)
PyGObject: (3, 36, 1)

======= Traceback =======
  File "/usr/lib/python3.9/site-packages/zim/gui/pageview.py", line 5630, in set_page
    self.set_parsetree(tree, template)
  File "/usr/lib/python3.9/site-packages/zim/gui/pageview.py", line 5740, in set_parsetree
    tree.resolve_images(self.notebook, self.page)
  File "/usr/lib/python3.9/site-packages/zim/formats/__init__.py", line 467, in resolve_images
    for element in self._etree.getiterator('img'):
AttributeError: 'ElementTree' object has no attribute 'getiterator'
```

After that, Zim's window opens and the sidebar seems functional, but not actual document contents is shown, for any document (just the error message keeps repeating).

Versions:
```
Zim-0.73.2-2.fc33.noarch
python3-3.9.0~rc1-2.fc33.x86_64
```

**Comment by jaap-karssenberg** [comment]
Afraid python 3.9 broke the etree interface. Patched in several places but
looks like this is a new one. Let me look into it.

Op do 10 sep. 2020 14:25 schreef Kamil Páral <notifications@github.com>:
