### ISSUE TITLE
0.73.2 (debian) separator lines shown in side panel content tab

### ISSUE THREAD

**Issue by nh3oh** [zim-desktop-wiki/zim-desktop-wiki#1260]
0.73.2 (debian) separator lines shown in side panel content tab

Most everything is in the title,
I don't know if it is a wanted improvement,
but I feel this as kind of noise that gives no valued information in the content tab.

Best regards to the Zim's folk.

**Comment by pfalcon** [comment]
This is duplicate report, please search issues first.

Go to the plugin settings and configure the behavior you want from it.

**Comment by nh3oh** [comment]
Thanks for answer.

Sorry, but I've done a search with "separator" keyword without any matching entry.
And the same in Zim's Manual => 2 answers for " : " in links syntax.

I wish you to spend a gooday.
Good bye!
