### ISSUE TITLE
0.73.2 where is launch zim with debug mode

### ISSUE THREAD

**Issue by menthalo37** [zim-desktop-wiki/zim-desktop-wiki#1270]
Hello
I used previously 0.68 version of Zim on windows, and there was a "launch zim with debug mode.exe" 
Could you please tell me if there is such executable available in v 0.73.2 version ?
Thanks.

**Comment by jaap-karssenberg** [comment]
It is no longer included. Instead there is a debug log written to file. See
the "tools" menu to open it directly from zim.

-- Jaap
