### ISSUE TITLE
Zim 0.73.2 config location of plugins

### ISSUE THREAD

**Issue by menthalo37** [zim-desktop-wiki/zim-desktop-wiki#1271]
Hellon
In ZIM version 0.68, there was a config directory located in (in my computer) S:\Zim\ZimAppli\App\Config\zim\customtools
Quite every custom tool had a config file, named (for instance for text mind map) :
and content was like this (see below), containing "precious" information like Name, Comment and Command line (Exec Tool) as strings.

[Desktop Entry]
Type=X-Zim-CustomTool
Version=1.0
GenericName=
Name=textmindmap
Comment=text_mind_map
Exec=
TryExec=
Icon=
MimeType=
Terminal=false
NoDisplay=false
X-Zim-ExecTool=python S:\Zim\ZimAppli\App\Data\zim\plugins\textmindmap.py %s
X-Zim-ReadOnly=false
X-Zim-ShowInToolBar=false
X-Zim-ShowInContextMenu=Page
X-Zim-ReplaceSelection=false

Could you tell me if such config files still exist, and where they are stored in ZIM version 0.73.2 ? 

Thanks.
E.

**Comment by jaap-karssenberg** [comment]
These by default go under "%APPDATA%/zim" (try typing it in windows File
Explorer - it understands those "%")

If you were using the portable version, please wait for the next update of
the installer.

-- Jaap

**Comment by arafel** [comment]
Hi

I've just tried and found:

* it will go %APPDATA%\zim\data\zim\plugins, but
* that folder didn't exist (even though I had plugins enabled) until I clicked "open plugins folder" in the Plugins prefs menu.

Hope that helps
