### ISSUE TITLE
Zim 0.73.2 : plugin location

### ISSUE THREAD

**Issue by menthalo37** [zim-desktop-wiki/zim-desktop-wiki#1273]
2 questions about  plugin location in Zim 0.73.2
1) when I click on "open plugin directory" in "Edit > Preferences > Greffons", ZIM version 0.73.2 asks me if I want to create a plugin directory; if I answer yes, the following directory appears
C:\Users\d37050\AppData\Roaming\zim\data\zim\plugins
There seems to be a sort of temporary file
In version 0.68, such location was a sub-directory of Zim application (for instance : S:\Zim\ZimAppli\App\Data\zim\plugins)
Moreover, a plugin sub-directory exists in ZIM 0.73.2 : for me , here : T:\UTIL\zim732\share\zim\plugins
Could you precise me if there are 2 plugins directories ?

2) I had a plugin to insert a Plant UML diagram. Everything worked in ZIM 0.68, thanks to a .py code file, whose location is in plugin directory (so : S:\Zim\ZimAppli\App\Data\zim\plugins)
After copy-pasting the same .py code file in T:\UTIL\zim732\share\zim\plugins (zim 0.73.2 plugin directory, cf. 1)), and restarting Zim appli, I am not able to see how to add this plugin in menus.
Could you precise me how to include a plugin in menus ? 

Thanks.
E.

**Comment by jaap-karssenberg** [comment]
Plugins <0.7x are not by default compatible due to the change to Python3 &
Gtk3 as of version 0.70.

This is actually the right folder under "%appdata%/zim" - if you were using
the portable install previously, please wait for the next update.

-- Jaap

**Comment by dehesselle** [comment]
Closing: has been answered and no further activity.
