### ISSUE TITLE
export in HTML page : bad link to png image generated from plugin

### ISSUE THREAD

**Issue by menthalo37** [zim-desktop-wiki/zim-desktop-wiki#1274]
Hello
When using a plugin like GNU R, diagram generator or seqdia , an image (.png) is generated, whose name is the same as .dot (txt generator source code for the plugin).

When exporting in HTML one page containing such an object, it appears the link is bad generated : 
`<img src="../01-utiliser_GNU_R_files/gnu_r_plot.png">`
for instance, where only 
`<img src="./01-utiliser_GNU_R_files/gnu_r_plot.png">`
is needed.

As a consequence, no image is displayed by the browser when loading the generated HTML page.
Is it an issue you could fix or a bad usage of Zim I can correct myself ?
Thanks
E.

**Comment by jaap-karssenberg** [comment]
In my testing all works fine. Can you make the example more specific?

-- Jaap

**Comment by menthalo37** [comment]
It seems to work, in fact. Sorry for this wrong issue.

However, Latex or mht exporting seems not to be ok, but it's already in other issues.
Thanks.
