### ISSUE TITLE
Menus on wrong screen

### ISSUE THREAD

**Issue by Nodd** [zim-desktop-wiki/zim-desktop-wiki#1275]
I have  Windows 10 PC with 3 screens. The menus and context menus always open on the 3rd screen. When the main windows is on the first or second screen, the menu appears on the side of the screen towards the window. I can still use the program but it's really annoying !

I have version 0.73.2.
My main screen (with the task bar) is the first screen on the left, the third screen corresponds to the laptop itself, I don't know if it matters.

**Comment by jaap-karssenberg** [comment]
Afraid this is an issue with the Gtk toolkit, not the zim application code.
So also not something that can be fixed within zim.

-- Jaap

**Comment by Nodd** [comment]
The problem was fixed somehow.
