### ISSUE TITLE
Cannot delete pages

### ISSUE THREAD

**Issue by HisMaj3sty** [zim-desktop-wiki/zim-desktop-wiki#1278]
I am using Manjaro and I have issue that is very similar to #1186. The visible behaviour is the same. However I see no errors in "zim --debug":
```
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck finished
DEBUG: Action: delete_page
DEBUG: Opening ProgressDialog: Removing Links
DEBUG: Trash page: Home:fadsf:asdfas
INFO: Move /mnt/DATA/Notebooks/Notes/Home/fadsf/asdfas.txt to trash
DEBUG: Index file: /mnt/DATA/Notebooks/Notes/Home/fadsf/asdfas.txt
```
Tested with zim master branch

**Comment by HisMaj3sty** [comment]
I solved the problem
The problem in my case was in the wrong permissions on NTFS formatted drive
Underlying Gio library was not trashing the file while not returning an error, maybe should report this to them as a bug

**Comment by jaap-karssenberg** [comment]
Thanks for the update!
