### ISSUE TITLE
Word Dokumente in Zim inkl. gespeicherte Bilder einfügen

### ISSUE THREAD

**Issue by ViroStar** [zim-desktop-wiki/zim-desktop-wiki#1279]
gibt es eine Möglichkeit Word-Dokumente die auch Bilder enthalten in Zim Wiki zu kopieren?

Er kopiert immer nur den Text

Danke

**Comment by jaap-karssenberg** [comment]
Not directly. But you can copy text and images independently. To copy an
image select the image as an object in Word and copy it.

-- Jaap

**Comment by ViroStar** [comment]
sehe gerade er übernimmt ja noch nicht einmal Überschriften oder Zeilenumbrüche.

Ganz lieben Dank für die Antwort, 
so macht Zim keinen Sinn für mich
