### ISSUE TITLE
"Ctrl+G" doesn't work after "Ctrl+F"

### ISSUE THREAD

**Issue by sojusnik** [zim-desktop-wiki/zim-desktop-wiki#128]
Since this is a quite old and common request (we have 2 [tickets](https://bugs.launchpad.net/zim/+bug/1036821) on [launchpad](https://bugs.launchpad.net/zim/+bug/1589085) and some mentions in the mailing list) I open this issue here, in the hope to fix this issue quickly:

When using "find" (normally Ctrl+F) within a page, then searching for the next search result with "Ctrl+G" (search again) doesn't work, because the focus stays on the "find entry", as mentioned [here](https://bugs.launchpad.net/zim/+bug/1036821/comments/3).

The solution seems obvious. Maybe somebody could have a quick look on that?

**Comment by jaap-karssenberg** [comment]
To be exact: if you start Ctrl-F but don't finish it by <Enter> the focus remains on the find entry and Ctrl-G doesn't work. If you close by <Enter> it will as intended.

There is another ticket open that claims correct behavior is to always keep focus on the find entry, so repeated <Enter> is repeated find. Need to take these two tickets together.

... if only I could find the ticket number ...
