### ISSUE TITLE
[tasklist]  start date information not exported

### ISSUE THREAD

**Issue by menthalo37** [zim-desktop-wiki/zim-desktop-wiki#1283]
Start date of a task (prefixed with ">") is not copyied nor stored as exported information.
- User has only "due date" column 
Moreover, unactive tasks (start date in future) are in grey in task list, but printed ("print" button from task list window) as other tasks (in black).

Could it be an improvement /enhancement in future Zim version ?
Thanks

**Comment by jaap-karssenberg** [comment]
Links to #873
