### ISSUE TITLE
how to change theme in 0.73.2

### ISSUE THREAD

**Issue by menthalo37** [zim-desktop-wiki/zim-desktop-wiki#1284]
Hello
I used both of these following links to try to change theme on 0.73.2 version of Zim, without success.
https://github.com/jaap-karssenberg/zim-wiki/wiki/Theme-manager-(Windows-Version-of-Zim)
--> "theme manager" plugin is not loaded after restarting Zim
https://github.com/jaap-karssenberg/zim-wiki/wiki/Set-a-dark-theme-and-background
--> specified directories are not available for 0.73.2 version (especially "etc" : I cannot find "gtk-2.0/gtkrc" text file that used to contain something like this in 0.68 version)
`gtk-theme-name = "MS-Windows"`

**Comment by jaap-karssenberg** [comment]
Please check recent discussion on the mailing list for instructions how to do this.

Would be good if someone updates the wiki pages for gtk3 

Regards,

Jaap

**Comment by wyrdxx** [comment]
"distraction free editing " plugin is an alternative way to use a custom theme.

**Comment by jaap-karssenberg** [comment]
CLosed by a66477e136e78fb7e6c265950ae40098d96e9277
