### ISSUE TITLE
Empty line is inserted before heading

### ISSUE THREAD

**Issue by Rogach** [zim-desktop-wiki/zim-desktop-wiki#1287]
If heading directly follows a chunk of text, then empty line is inserted between when page is saved and then opened again.

Example page:
```
Content-Type: text/x-zim-wiki
Wiki-Format: zim 0.6
Creation-Date: 2020-10-11T21:34:32+00:00

====== Test ======
Created 2020-10-11

2020-10-11T21:34:58 UTC
== header-5 ==
```
If I open this page in Zim, save, close, and then reopen again then empty line will be inserted between `2020-10-11T21:34:58 UTC` and `== header-5 ==`.

In the code of `OldParseTreeBuilder` I found the following comment:

> There should be an empty line before each 'h', 'p' or 'pre'

Why is empty line required before a heading?

**Comment by jaap-karssenberg** [comment]
This is on purpose. Our formatting uses a blank line before headings.


Op ma 12 okt. 2020 08:08 schreef Rogach <notifications@github.com>:
