### ISSUE TITLE
Modules and ZIM

### ISSUE THREAD

**Issue by Nick222** [zim-desktop-wiki/zim-desktop-wiki#1290]
Not all ZIM modules (created by the author of the program) say that they are supplied with this program.

Is it possible to give a complete list of the modules supplied with the program or indicate in all such modules their belonging to the program (for a number of modules this is indicated in the description, and for a number of others - including those created by the ZIM author himself - there is no such indication).

This is necessary in order to know which modules should be regularly checked for updates separately.

**Comment by jaap-karssenberg** [comment]
I have no idea what you are talking about. All Zim code is contained in the
"Zim"python module.

Op wo 14 okt. 2020 11:29 schreef Nick222 <notifications@github.com>:

**Comment by Nick222** [comment]
Some modules have the text "This is a basic module; supplied with ZIM" in the description, while others do not.

Do all modules that do not have such text need to be updated by the user himself - regardless of who the author of the module is?

**Comment by jaap-karssenberg** [comment]
I think you are talking about plugins. The plugins installed with the main
program in the "Zim"module are part of the default release.

Op wo 14 okt. 2020 15:23 schreef Nick222 <notifications@github.com>:

**Comment by Nick222** [comment]
But how user can define plugins installed with the main
program as part of the default release - and other plugins?

**Comment by Nick222** [comment]
In Russian translate plugins named as "modules" - it is wrong - as I think...

**Comment by jaap-karssenberg** [comment]
Most (all?)  default plugins mention in their description that they are a default plugin. Otherwise there is no descrimination between default and other plugins.
