### ISSUE TITLE
Russian Zim translate

### ISSUE THREAD

**Issue by Nick222** [zim-desktop-wiki/zim-desktop-wiki#1291]
Who is currently involved in the translation of Zim into Russian?

Where can we discuss Russian translation?

**Comment by sojusnik** [comment]
Translations moved to Weblate recently, see

https://hosted.weblate.org/projects/zim/master/
https://hosted.weblate.org/projects/zim/develop/

You can contribute freely there.

**Comment by Nick222** [comment]
I registered there already - but I cannot understand - how start conversation about translation...

**Comment by sojusnik** [comment]
I think that you can comment on translation strings there, but you seem to look for a central place to chat with all Russian translators regarding a unified terminology?

Did you dig deeper into Weblate? Maybe they have something similar like chatrooms or a mailing list for all translators from a language pair?

**Comment by Nick222** [comment]
Yes.

I cannot find any chat-room or mail-list on Weblate :(

It is need something like forum or like Google-group...

Zim need good forum - as i think!

**Comment by sojusnik** [comment]
@Nick222 I see you already made a [corresponding proposal](https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/1054) to have a forum dedicated to Zim.
