### ISSUE TITLE
Date format in Zim

### ISSUE THREAD

**Issue by hbozhkov** [zim-desktop-wiki/zim-desktop-wiki#1299]
Hello, I would like to know if there's a way to edit the date format in Zim for denoting when a page was created. I've successfully updated the Insert Date function in $XDG_DATA/zim/dates.list, but still new notes are created with listing the full day name. You can find the comparison in the screenshot attached. 
![Screenshot from 2020-10-23 12-18-17](https://user-images.githubusercontent.com/6433919/96986159-f00a9580-1529-11eb-9a80-728078ca8b92.png)

**Comment by pfalcon** [comment]
Edit -> Templates -> wiki -> Default

**Comment by hbozhkov** [comment]
Thanks a lot!
