### ISSUE TITLE
relative addressing on windows starting with ".." not working

### ISSUE THREAD

**Issue by EvgenyD** [zim-desktop-wiki/zim-desktop-wiki#1301]
Just noticed, I can put images from subpages, or from pages on the same "level" as the active one (eg: "/abc1/def.jpg" or "./abc2/def.jpg"), but when I try an arbitrary folder with more then one "." in the address, it shows missing image icon.

**Comment by jaap-karssenberg** [comment]
Just tested it, but works fine for me. Can you give a concrete example of
what the link looks like ?

-- Jaap

**Comment by EvgenyD** [comment]
So apparently it is an issue with 3 dots not 2.

here is an example:
![ZIM IMAGES](https://user-images.githubusercontent.com/7352805/97429086-37709780-1917-11eb-8710-35cce39c4409.png)

The active page looks like this :
```
THIS PAGE(.\AAC1.jpg): 	{{.\AAC1.jpg}}

1 LEVEL UP (..\ab1.jpg):	{{..\ab1.jpg}}

2 LEVELS UP (..\A1.jpg) :	{{..\A1.jpg}}
1 LEVELS UP 2 LEVELS DOWN(..\AAC2\AABD1\AABD1.jpg): 	{{..\AAC2\AABD1\AABD1.jpg}}

2 LEVELS UP 1 LEVELS DOWN(..\AB2\ab2.jpg): 			{{..\AB2\ab2.jpg}}

```
1 and 2 level ups have both two dots in the address.

**Comment by jaap-karssenberg** [comment]
Sorry, but I don't understand. What do you mean by "3 dots" ?  I don't see
a difference between "..\ab1.jpg" and "..\A1.jpg" so my guess would be that
"A1.jpg" does not exist. If you really want 2 levels up, it should read
"..\..\A1.jpg" - is that what you intended ??

**Comment by EvgenyD** [comment]
So, now i have a better understanding of what seems to be a problem. sorry, for a bit of confusion. 
Yes, you are right, it should read "..\..\A1.jpg" but...
if you do insert->image, browse to the picture that is higher than 1 level up, insert it, the address will always start with single "..\".
When I edit txt page manually and put correct address (as you wrote), it work correct after refresh, but...
If I edit the image's properties, repeating "..\" in the beginning of the address disappear and the address become once again wrong.
