### ISSUE TITLE
Could not open: Journal.txt

### ISSUE THREAD

**Issue by andrejserafim** [zim-desktop-wiki/zim-desktop-wiki#1302]
Zim fails to open templates after the ubuntu 20 upgrade (python version switch I think is part of that).

Copy - copies the templates. But neither of View, Edit, etc do - they report: "Could not open: Journal.txt".

And of course the templates aren't effective :) Which is the biggest problem.

**Comment by fdt-dev** [comment]
I recently upgraded to Ubuntu 20.04 LTS as well (I'm assuming that's the one you're talking about).
Editing of templates works for me. Clicking on 'Edit' or 'View' from within Zim works.
Possibly missing library? Does re-installing Zim make a difference? Or it could be a permissions issue with the template folder.

**Comment by andrejserafim** [comment]
@fdt-dev yes, that's the one I meant. Sorry.

Tried reinstalling, no difference.

I don't know how to check if a library is missing. If there a way I could get the error log?

I'm using 0.72.0 - the one that comes from ubuntu repos.

**Comment by andrejserafim** [comment]
Updating to 0.73.3 (from the downloads page) also behaves the same.

**Comment by fdt-dev** [comment]
I'm fresh out of ideas. Sorry about it. I'm really only a user of this software as well. So, maybe somebody else has any ideas. Hopefully.

**Comment by jaap-karssenberg** [comment]
Try running zim from a terminal with "zim --debug", then try accessing the
templates and see what errors are printed in the terminal.

**Comment by fdt-dev** [comment]
Jaap, are you replying to me? I don't have an issue. My Zim setup works. I just tried to help the OP.

Thank you.

**Comment by andrejserafim** [comment]
@jaap-karssenberg thanks! `--debug` rocks!

So the problems were: 

- default text editor was messed up after the upgrade.  I've fixed that.
- the Journal.txt plugin needed to be search/replaced for `calendar_plugin` to `journal_plugin`. 

All is working now. Thanks for your help!
