### ISSUE TITLE
[Bug] Command line options doesn't work

### ISSUE THREAD

**Issue by pidgeon777** [zim-desktop-wiki/zim-desktop-wiki#1303]
I'm running Zim v0.73.3.

When I open a new terminal session and I execute:

`C:\path\zim.exe --version`

nothing is reported in the terminal. The same for the remaining arguments:

https://zim-wiki.org/manual/Help/Commandline_Options.html

Thus I cannot start Zim in debug mode.

I tried both portable and full local installation.

**Comment by jaap-karssenberg** [comment]
Yes, this is because windows executables do not return output to the
terminal
