### ISSUE TITLE
Notebook become readonly

### ISSUE THREAD

**Issue by sisso** [zim-desktop-wiki/zim-desktop-wiki#1304]
zim 0.73.2
Ubuntu 19

One of my notebooks become read-only. 

Remove the notebook. Restarting the machine, removing the .zim and notebook.zim, and re-add the notbook, cause the same issue. 

When I copy the same files into a new folder (cp -r zim-ti zim-ti-2), add the notebook (zim-ti-2), it will works normally. If I remove the old folder and move the folder back to the previous name (rm -rf zim-ti && mv zim-ti-2 zim-ti), I am back in the same issue. 

The strange is: If I add the notebook from any other folder, the Zim do a full reindex of the files, but when I added the folder of this notbeooke, it don't reindex, looks like there is already some index in my machine  that I can not find. 

Any idea where I should look for?

**Comment by sisso** [comment]
Ok, found, I post here to early

running zim locally with 
`python3 zim.py -V -D`

I found this line
`DEBUG: Set XDG_CACHE_HOME to /home/brasilie/.cache`

Removing the caching for zim solves the issue
`rm -rf /home/brasilie/.cache/zim`

**Comment by jaap-karssenberg** [comment]
Probably you accidentally hit the "toggle read-only" button in the toolbar
and wiping the cache also wiped that state.

Wil make the button more obvious in future versions.

-- Jaap

**Comment by sisso** [comment]
The "Notebook editable" button. I believe I use zim for 10 years, I didn't know this exists, and I have to check every single button. You get used to something soo much that you get blind :)

@jaap-karssenberg I think maybe just add a new option in File menu to switch back to "editable" mode would be nice. At least File and File->Properties were the first places I searched when trying to find what was happening.
