### ISSUE TITLE
Column of note dates in search results

### ISSUE THREAD

**Issue by Nick222** [zim-desktop-wiki/zim-desktop-wiki#1314]
It is very necessary in the search results window (with a list of notes) to add a column of the date of the note (with the possibility of sorting by it).

Often I remember the approximate content of a note and can definitely find it only by date.

**Comment by pfalcon** [comment]
How does this differ from https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/1288 ?

**Comment by Nick222** [comment]
Pardon - I am stupid :)
