### ISSUE TITLE
Can't open http links with firefox

### ISSUE THREAD

**Issue by Kommynct** [zim-desktop-wiki/zim-desktop-wiki#1318]
It's the darndest thing.

I've tried changing the default shortcut to specify my profile.

No matter what I try i seem to get this error.

![image](https://user-images.githubusercontent.com/13646790/98621859-37d53f00-22d6-11eb-9d77-497f1dcaf291.png)

I would give more info but i'm unsure what would be helpful.

I'm on arch. Using wayland but to work around a bug with another piece of software I use it in x.org mode.

**Comment by jaap-karssenberg** [comment]
This error is not generated by zim, but probably by firefox itself - so
looks like the handover from zim to firefox did work. Not sure why firefox
doesn't work after that.

-- Jaap

**Comment by zogommog** [comment]
I've seen cases where Firefox will close itself, due to an update, and you think it isn't running - but it is, and in order to get rid of messages like that one, you need to manually find and kill the process.
