### ISSUE TITLE
Search/filter not functional in OpenDialog

### ISSUE THREAD

**Issue by sanjarcode** [zim-desktop-wiki/zim-desktop-wiki#1319]
**Problem**
In the 'Notebook open dialog', if you start typing, a textbox appears. 
But it does not do anything(I want it to filter the list).
Currently, I have to scroll the list to find a notebook(assuming its not my default notebook).
<img src="https://user-images.githubusercontent.com/48156230/98762776-68b09380-23fe-11eb-8b20-f254f838e6a5.png" height="300px">    

The feature is present in all dialogs that have a list, and it works(filters) fine:
1. In Preferences > Plugins
2. In Preferences > Key Bindings

Apparently, the searchBox disappears on taking a screenshot, so I had to use a Camera:
<img src="https://user-images.githubusercontent.com/48156230/98763134-600c8d00-23ff-11eb-8c9b-5a399f3461aa.png" height="300px">

**Action**
I cannot find where this functionality(search as you type) is in the code.
Can someone implement this, or atleast guide me how to do it. I have no experience with GTK, but I think the task is not that difficult.

**Comment by jaap-karssenberg** [comment]
This is a default feature in Gtk, not specific in zim code. Probably there
is an API in GtkTextView to let this feature know which column of the model
to search.

-- Jaap
