### ISSUE TITLE
Plugin for structured data-notes

### ISSUE THREAD

**Issue by Nick222** [zim-desktop-wiki/zim-desktop-wiki#1322]
I would like to see a plugin for Zim, which allows you to create pages with structured data of the TreeLine type http://treeline.bellz.org/ , as well as allowing you to view and edit them.

Does Zim have a mechanism to write plugins that work with different types of pages?

**Comment by jaap-karssenberg** [comment]
My thinking is that you would define an inline object that has structured data fields. See plugin writing documentation on inline objects. As an example look at the "source view" plugin. If you also want to index this data have a look at the "tasklist" plugin for indexing extensions.
