### ISSUE TITLE
Zoom in/out does not work [Linux, OpenSUSE, Tumbleweed, Gnome3]

### ISSUE THREAD

**Issue by benopotamus** [zim-desktop-wiki/zim-desktop-wiki#1323]
The zoom in and out functions do not work on my machine. I'm happy to provide more details but not sure what would be relevant - just let me know.

I'm running OpenSUSE Tumbleed and Gnome3 on an Apple Macbook 14,1 (https://github.com/Dunedan/mbp-2016-linux)

I have scale set to 200% but setting to 100% didn't resolve the issue.

I tried using the menu options, keyboard shortcuts, and ctrl+mousewheel.

**Comment by jaap-karssenberg** [comment]
Just tested with the latest version of zim under Ubuntu Gnome3 desktop.
Using e.g. keybindings works fine. Do note that zoom only affects text
size, not images.

If you want to debug, you can run zim from a terminal with "zim --debug"
(after closing open windows) and check for output when you try to zoom. It
should log an action like "DEBUG: Action: zoom_in". If you don't see this,
something is wrong with the keybindings - if you do see this, but nothing
happens to the text size, something is wrong in the zoom function itself.

Regards,

Jaap

**Comment by Nick222** [comment]
This option are not "really zoom" - it only change font for "textview" (see Zim options)...

**Comment by benopotamus** [comment]
--debug reports:

```
DEBUG: Action: zoom_in
DEBUG: Switching to custom font implicitly because of zoom action
ERROR: FIXME
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/zim/gui/pageview.py", line 6810, in _zoom_increase_decrease_font_size
    self.text_style['TextView']['font'] = font.to_string()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xec in position 2: invalid continuation byte
DEBUG: Loading config from: <ConfigFile: /home/ben/.config/zim/style.conf>
```

**Comment by jaap-karssenberg** [comment]
That is a weird one - looks like the font name or description contain invalid UTF-8 !?
What font are you using? 
Can you try chancing the font and see if the same issue persists?

**Comment by benopotamus** [comment]
Gnome Tweaks tells me I'm using `Cantarell Regular` for normal text and `Source Code Pro Regular` for monospace. 

Unfortunately, before I got to try changing the font, the issue went away. I was curious so I cloned the repo with the intention of adding in a few print statements and I received this output when zooming (using ./zim.py --debug of the cloned repo)

```
DEBUG: Action: zoom_in
DEBUG: Switching to custom font implicitly because of zoom action

(zim.py:3807): Gtk-CRITICAL **: 06:34:09.845: _gtk_css_array_value_new_from_array: assertion 'values != NULL' failed
Segmentation fault (core dumped)
```
And then decided I'd just cheat and put a print statement in `/usr/lib/python3.8/site-packages/zim/gui/pageview.py`. I put it in the exception block, but it didn't get executed because zooming now works! The zooming now works in both the system installed zim and the cloned repo zim. 

I'm happy to do provide more info if you would like or we can close the issue.

**Comment by jaap-karssenberg** [comment]
Let's keep this one open for a bit just in case anyone else stumbles on the same issue. I'll close it after some time if there is not further activity.

**Comment by osky85** [comment]
Zoom in/out was not working for me (Manjaro KDE), I read this issue and tried changing the font and now it works using the menu options. The hotkey however does not work.

**Comment by zapateo** [comment]
Same problem on Fedora 33 Workstation, Gnome Shell running on X11. Sometimes I can't zoom in/zoom out.

**Comment by benopotamus** [comment]
On this machine (OpenSUSe Tumleweed with Gnome 40.4.0), the menu and keyboard bindings for zoom worked with the default settings*, but not ctrl+mousewheel zooming. 

*I have explicitly set the font now, but I think it was working before that

I tried `zim --debug` to see what was happening but that command prints a few debug messages to the terminal, launches zim, and then waits for the user to type another command. It doesn't print any debug messages beyond those initial ones.

This is what I see in the terminal:
```
ben@localhost:~> zim --debug
INFO: This is zim 0.73.5
DEBUG: Python version is sys.version_info(major=3, minor=8, micro=11, releaselevel='final', serial=0)
DEBUG: Platform is posix
DEBUG: Not running from a source dir
DEBUG: Set XDG_DATA_HOME to /home/ben/.local/share
DEBUG: Set XDG_DATA_DIRS to [<Dir: /home/ben/.local/share/flatpak/exports/share>, <Dir: /var/lib/flatpak/exports/share>, <Dir: /usr/local/share>, <Dir: /usr/share>]
DEBUG: Set XDG_CONFIG_HOME to /home/ben/.config
DEBUG: Set XDG_CONFIG_DIRS to [<Dir: /etc/xdg>, <Dir: /usr/etc/xdg>]
DEBUG: Set XDG_CACHE_HOME to /home/ben/.cache
DEBUG: Connecting to /run/user/1000/zim-0.73.5-e63203e4
DEBUG: Dispatched command ('--debug',)
ben@localhost:~> 
```
