### ISSUE TITLE
link to google meet create new page

### ISSUE THREAD

**Issue by Jairjua** [zim-desktop-wiki/zim-desktop-wiki#1325]
When I create a link to some google meet location appear a new page (see image).
![image](https://user-images.githubusercontent.com/9156799/99387821-62656000-28b3-11eb-89d8-89abc2cde80a.png)

**Comment by jaap-karssenberg** [comment]
Try starting the link with "http://"

**Comment by jaap-karssenberg** [comment]
See #1324
