### ISSUE TITLE
numbered lists and headings do not work together

### ISSUE THREAD

**Issue by pronti** [zim-desktop-wiki/zim-desktop-wiki#133]
When I create a list and then format it as heading1 everything seems ok.
After saving and reloading the format gets screwed up.
Example
1. text1
2. text2
3. text3

After reloading the text is still heading1 but the numbers of the list items are separated and are normal text.

1.
text1
2.
text2
3.
text2

**Comment by Osndok** [comment]
While I cannot say that behavior is "expected", exactly.... Zim does not support overlapping styles. Lists are expected to be lists, and headings are expected to be headings.

On the outside, it probably should have "included the number" when converting the list to heading lines, but it is not expected to have any of the list features (like indentation, automatic numbering, etc.).

**Comment by Xunius** [comment]
The way I work around is: type in the text of the heading, e.g. "this is heading", format it to a heading by e.g. Ctrl+2, then navigate to the beginning and manually type in the number, e.g. 4.1.
Another way is goto "Edit source" where you put the numbering inside the heading formatting token "="

BTW, I am curious why not overlapping styles? Things like bold+italic are totally comman and legit, I use italic to indicate a literal quote, and want to hightlight a keyword in bold.

**Comment by sojusnik** [comment]
It's connected to [this](https://bugs.launchpad.net/zim/+bug/1124666) issue on Launchpad.

At the moment applying a number to an already formatted header is working, but not when turning a list item into a header.

**Comment by jaap-karssenberg** [comment]
Fix by making sure "apply heading" removes list(& indent?) formatting
