### ISSUE TITLE
Crash when trying to open another notebook on Big Sur

### ISSUE THREAD

**Issue by gaelbb** [zim-desktop-wiki/zim-desktop-wiki#1330]
Hi,

First of all, I would like to thank you for the development of this very useful software! 

Since updating to Big Sur, Python 3.9 (python@3.9-3.9.0_1) crashes on macOS when trying to open another notebook.
I tried to reinstall Zim (zim-0.73.4) and its dependencies with brew, but it didn't change anything.

You can find below to the log of the crash.
Do you have an idea of the source of this bug?

I thank you in advance,

Cheers, 

Gaël

```
Process:               Python [32769]
Path:                  /usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/Python
Identifier:            org.python.python
Version:               3.9.0 (3.9.0)
Code Type:             X86-64 (Native)
Parent Process:        zsh [10406]
Responsible:           Terminal [77527]
User ID:               501

Date/Time:             2020-11-22 19:20:51.159 +0100
OS Version:            macOS 11.0.1 (20B29)
Report Version:        12
Anonymous UUID:        C680F852-294E-A501-B709-D6D4E76C21A7

Sleep/Wake UUID:       C6BF86AB-F77D-4478-9EB1-8D3EE23C0517

Time Awake Since Boot: 340000 seconds
Time Since Wake:       6300 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
Assertion failed: (!surface->finished), function _cairo_surface_release_source_image, file cairo-surface.c, line 2092.
```

**Comment by jaap-karssenberg** [comment]
Afraid this is an error thrown by the Gtk library, not something in zim itself. Maybe another version of Gtk fixes it ?  (Either newer or older as a work around)

**Comment by gaelbb** [comment]
It is completely beyond my knowledge but it has maybe something to do with this: https://gitlab.freedesktop.org/cairo/cairo/-/issues/420
I will try to find a work around or wait for a fix of cairo/gtk.
Thanks!

**Comment by eni24** [comment]
Hi @gaelbb. Did you make any progress on this? I have the same issue and can't seem to fix it (despite all efforts). I currently use a linux docker container and xquartz as workaround. It works but it's got usability issues - would be great  to have a better solution...
Cheers!

**Comment by rasisin** [comment]
I’m in the same situation: the current Mac Zim application still crashes on opening.

**Comment by rasisin** [comment]
The problem appears to have been solved with the latest update of Cairo. Zim is opening notebooks fine on my Mac again.

**Comment by jovarela** [comment]
Confirmed, the problem is also solved using brew since yesterday, they opted for a patch in the previous version:  
# Avoid segfaults on Big Sur. Remove at version bump.
# https://gitlab.freedesktop.org/cairo/cairo/-/issues/420

https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/cairo.rb

In my case required a "brew reinstall cairo"

**Comment by gaelbb** [comment]
Solved for me also, by updating Cairo:
`brew upgrade`
