### ISSUE TITLE
Inconsistent Recognition of Plugin Dependencies

### ISSUE THREAD

**Issue by geekkid1** [zim-desktop-wiki/zim-desktop-wiki#1331]
I'm not sure if I've done something wrong and it's a problem with the "Insert Diagram" plugin, or if I've done things right and it's a problem with the "Link Map" plugin, but I have encountered an issue where the same dependency is recognized for one plugin but not for the other.

On the "Insert Diagram" plugin:
![image](https://user-images.githubusercontent.com/23391383/100149065-a1735280-2e6b-11eb-966f-ad42215a23f5.png)
As you can see, it recognized graphviz, as I added its folders to PATH.

On the other hand, there is the "Link Map" plugin:
![image](https://user-images.githubusercontent.com/23391383/100149144-be0f8a80-2e6b-11eb-875f-7326df23eb3b.png)
Despite installing both graphviz _and_ xdot, zim recognizes neither one.

In addition, despite my confirmation that GraphViz is properly installed, working, and recognition by zim itself, I have not actually been able to use the "Insert Diagram" plugin with zim without encountering an error message that gives me no information as to the actual error.

**Comment by jaap-karssenberg** [comment]
"xdot" is imported as a python module by zim. Depending on your desktop /
package manager, the xdot application maybe installed without the module
being available for other applications.

The difference in the GraphViz dependency is that the "Insert Diagram"
plugin looks for an executable called "dot" while the "Link Map" plugin
looks for an executable called "fdp", both should be part of the GraphViz
package.

Hope this helps,

Jaap

**Comment by geekkid1** [comment]
I have made sure that the installs for graphviz are correct, and yet I still encounter this issue with the dependencies. In addition, as I said earlier, when I try to use the "Insert Diagram" plugin (which is the only one I can get to install) it gives me a nondescript error and fails without doing much of anything, despite the fact that it thinks it can properly access graphviz dot.

**Comment by geekkid1** [comment]
I am still working on figuring out whether my install can access the "xdot" package and I will update you if I end up figuring that out.
