### ISSUE TITLE
Empty journal section preference gets reset after restart

### ISSUE THREAD

**Issue by sineway** [zim-desktop-wiki/zim-desktop-wiki#1338]
**How to reproduce**
1. Open `File > Preferences > Journal` and make `Section` field empty
2. Restart application and reopen preferences

**Expected behavior**
Journal section field should be empty _(`<Top>` placeholder)_

**Actual behavior**
Journal  section is `:Journal` 

**Software version**
0.73.3

**Comment by jaap-karssenberg** [comment]
Sorry but that is the correct behavior. The plugin can not function without
a section preference, so empty is not an allowed value for this preference.



Op za 5 dec. 2020 15:39 schreef Sineway <notifications@github.com>:

**Comment by sineway** [comment]
I got it, thanks
