### ISSUE TITLE
Option to edit each note in its own windows

### ISSUE THREAD

**Issue by nickbe** [zim-desktop-wiki/zim-desktop-wiki#1346]
I'd like to suggest that it should be possible to edit each note in a seperate "note only" window.

**Comment by sojusnik** [comment]
Already possible in the [snapshots version](https://launchpad.net/~jaap.karssenberg/+archive/ubuntu/zim-snapshots).

**Comment by nickbe** [comment]
Are windows binaries of the snapshots ?  😁

**Comment by nickbe** [comment]
I found a windows version  0.73.4. If this is the right one then how can I make notes open each in their own edit window?

**Comment by sojusnik** [comment]
Can't help you with the Windows versions, but to open a note in a separate window, right-click on a page in the index or tag pane and select "open in a new window" or use the menu bar (file > "open in a new window"). There's also a keyboard shortcut for this, which is editable in the settings of Zim.

**Comment by jaap-karssenberg** [comment]
No there is no windows installer for development snapshots. You can run
from source, see the instructions in the git archive. Else justst be
patient until the next release.



Op za 2 jan. 2021 09:57 schreef sojusnik <notifications@github.com>:

**Comment by mikem23** [comment]
This appears to be a duplicate of #153

**Comment by sia1984** [comment]
The feature is implemented on the develop branch and [works well](https://github.com/zim-desktop-wiki/zim-desktop-wiki/commit/2ea404d71c600fb0cbfea5387dcf33d31663d5dd#commitcomment-46782664), @nickbe :)

> I tried this with `pip install --user https://github.com/zim-desktop-wiki/zim-desktop-wiki/archive/develop.zip` and it works well. Consider this feature end-user integration tested :)

**Comment by nickbe** [comment]
Thanks, but I'll wait until the next full windows release. I don't have python installed right now anyway.

**Comment by nickbe** [comment]
I downloaded the latest version now, but although it's now possible to open a note in a new window there's no way to edit the note there or make it open in a new window by default.
Or did I miss something?

**Comment by nickbe** [comment]
Is the feature to edit each note in its own window in the current version already?

**Comment by sojusnik** [comment]
AFAIK, only in the snapshots version, as mentioned above.

**Comment by introt** [comment]
Included in 0.74
