### ISSUE TITLE
Aplications to open files don't accept environment variables nor simple "wordpad" command

### ISSUE THREAD

**Issue by Atronach** [zim-desktop-wiki/zim-desktop-wiki#1353]
I want to use WordPad as the default text editor. It only works if I put the absolute path in the "Command" field in the dialog box for adding new application:
`"C:\Program Files\Windows NT\Accessories\wordpad.exe"`

However, when using Zim portable I'd like to cover possible different drive letters of the boot (=OS) partition with the help of environment variable:
`"%ProgramFiles%\Windows NT\Accessories\wordpad.exe"`
...but this way I'm getting error: 
![Zim Error](https://user-images.githubusercontent.com/12926163/103804527-8ee75e00-5052-11eb-88cb-749a49153c18.png)

I'm also getting the same error when typing in only "wordpad" even though "notepad" is accepted and works.

Tested with Zim 0.73.4 on Win10x64.

**Comment by introt** [comment]
Environment variables are not supported as applications aren't launched via a shell. You may ask for workarounds over at Discussions. Thanks for your understanding.
