### ISSUE TITLE
New Feature Request: Code blocks

### ISSUE THREAD

**Issue by klebann** [zim-desktop-wiki/zim-desktop-wiki#1356]
Would it be possible to add the ability to create code-blocks in Zim?
This is possible by SourceView, but it is very buggy, my Zim crashes when I open page with 'Code Blocks' blocks.
It should be embeded in Zim, by typing ( ` ) for inline code and (```) for multiline code, both like in .md files

Example:
```php
<?php
echo "Hello World!";
?>
```

As a programmer I'm using a Zim a lot and it would be very useful to have this feature to save quickly important code and make notes about it.

**Comment by sanjarcode** [comment]
It buggy, like 60% of the time, when I have to move things. One thing that works is ensuring that the codeblock is not indented. This greatly reduces buggy behavior. 

Several Issues have been created for this, e.g [](https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/1317)

Please close this issue.

**Comment by jaap-karssenberg** [comment]
Check out the "verbatim" formatting, I think that is what you are looking
for.

Next release will also support a "paste as verbatim" action in the context
menu.

Op do 7 jan. 2021 10:31 schreef Jakub Kleban <notifications@github.com>:
