### ISSUE TITLE
Fwd: [abrt] Zim: do_size_allocate(): pathbar.py:348:do_size_allocate:IndexError: list index out of range

### ISSUE THREAD

**Issue by cheese** [zim-desktop-wiki/zim-desktop-wiki#1357]
https://bugzilla.redhat.com/show_bug.cgi?id=1911864

Description of problem:
I am using Fedora 33 with the latest version of the Gnome DE

I had Calibre PDF manager open in one half of the desktop, to the right I had Zim snapped to the other half. 
I deleted one subpage, then tried to make another I believe and it crashed. It wasn't serious, and the application continued
on as usual, no restart required. 

Version-Release number of selected component:
Zim-0.73.4-1.fc33

Additional info:
reporter:       libreport-2.14.0
cgroup:         0::/user.slice/user-1000.slice/user@1000.service/app-gnome-zim-11051.scope
cmdline:        /usr/bin/python3 /usr/bin/zim
crash_function: do_size_allocate
exception_type: IndexError
executable:     /usr/bin/zim
interpreter:    python3-3.9.1-1.fc33.x86_64
kernel:         5.9.16-200.fc33.x86_64
runlevel:       N 5
type:           Python3
uid:            1000

Truncated backtrace:
pathbar.py:348:do_size_allocate:IndexError: list index out of range

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/zim/plugins/pathbar.py", line 348, in do_size_allocate
    available = allocation.width - widths[anchor] - 2 * border
IndexError: list index out of range

Local variables in innermost frame:
self: <pathbar.RecentPathBar object at 0x7f63fa515640 (zim+plugins+pathbar+RecentPathBar at 0x5583e03d1460)>
allocation: <Gdk.Rectangle object at 0x7f63f9ea31c0 (GdkRectangle at 0x5583e01a9d90)>
children: [<Gtk.ToggleButton object at 0x7f63f9ffe7c0 (GtkToggleButton at 0x5583e057de40)>, <Gtk.ToggleButton object at 0x7f63fa62b940 (GtkToggleButton at 0x5583e02d8d40)>, <Gtk.ToggleButton object at 0x7f63fa62ba00 (GtkToggleButton at 0x5583e04d0800)>, <Gtk.ToggleButton object at 0x7f63fa62bc00 (GtkToggleButton at 0x5583e08405c0)>, <Gtk.ToggleButton object at 0x7f63f9f90340 (GtkToggleButton at 0x5583e02d89a0)>, <Gtk.ToggleButton object at 0x7f63f9f64840 (GtkToggleButton at 0x5583e04d0290)>, <Gtk.ToggleButton object at 0x7f63f9f64ec0 (GtkToggleButton at 0x5583e04d0460)>, <Gtk.ToggleButton object at 0x7f63f9f60580 (GtkToggleButton at 0x5583e0840790)>, <Gtk.ToggleButton object at 0x7f63f9f8df40 (GtkToggleButton at 0x5583e0840220)>]
direction: 1
anchor: 9
border: 1
widths: [54, 75, 227, 250, 100, 88, 163, 96, 229]
total: 1284
show_scroll_buttons: True
first: 9
last: 9

**Comment by introt** [comment]
Needs more info; please open a new issue if you can find the required steps to reproduce on the latest version. Thank you.
