### ISSUE TITLE
Unable to edit keybindings in ui

### ISSUE THREAD

**Issue by mikem23** [zim-desktop-wiki/zim-desktop-wiki#1359]
The Key bindings tab in the Preferences window says "Key bindings can be changed by selecting the action in the list and pressing the new key binding. To disable a keybinding, select it in the list and use Backspace." However, neither of these work. Pressing new key combinations does not seem to have any effect, nor does pressing Backspace on a line with a key binding set.

I'm running Zim-0.73.4-1 on Fedora 32.

**Comment by jaap-karssenberg** [comment]
Rather than just selecting the line, you need to click directly on the
field with the key combo, it will change into "new accelerator..." and then
you can press the new key combo.

Probably need to clarify the help text.

**Comment by mikem23** [comment]
Ah thank you
