### ISSUE TITLE
Not a valid page name

### ISSUE THREAD

**Issue by codingRubbish** [zim-desktop-wiki/zim-desktop-wiki#1363]
Hello,

Before I get to the issue I'd just like to say I love this software, use it on all my computers, so thank you for all your hard work. I'd like to contribute but my programming skills are rubbish. Anyway had to sign up to post this bug which happened when I was making a note of so regex I was using in a process. The regex was:

```
(\r\n\[[^\]]+\]\r\n)
```

The `^` character went blue after reloading the page (Ctrl-R). And the regex now appeared like this:

```
(\r\n\^\+\]\r\n)
```

Assuming something to do with the square brackets and how they related to links. When I clicked on the blue `^` a bug window popped up with this message:

```
This is zim 0.73.4
Platform: nt
Locale: en_GB cp1252
FS encoding: utf-8
Python: (3, 8, 5, 'final', 0)
PyGObject: (3, 38, 0)

======= Traceback =======
  File "zim/gui/pageview.py", line 6003, in do_activate_link
  File "zim/gui/pageview.py", line 6013, in _do_activate_link
  File "zim/notebook/page.py", line 355, in new_from_wiki_link
  File "zim/notebook/page.py", line 156, in makeValidPageName
ValueError: Not a valid page name:  (was: ^\)
```

Hope this helps, pretty much the epitome of an edge case!

Thanks again for the software.

Edit: forgot to say once the regex was enclosed in Verbatim tags, no issues.

**Comment by jaap-karssenberg** [comment]
Best to use verbatim formatting when you include code in a page. That
protects it from being interpreted as wiki syntax.

Op do 14 jan. 2021 15:28 schreef codingRubbish <notifications@github.com>:

**Comment by codingRubbish** [comment]
Apologies for the late reply and thanks for you reply.

I didn't think it was a proper bug but thought I would post due to the bug window popping up just in case.

I'll try and keep any reports to proper bugs next time.

**Comment by jaap-karssenberg** [comment]
Actually very good you reported it - makes me think whether the error
message in this case should be a "bug" message or something more
informative

-- Jaap
