### ISSUE TITLE
Cannot find system default text editor (`text/plain`)

### ISSUE THREAD

**Issue by smac89** [zim-desktop-wiki/zim-desktop-wiki#1364]
```
Zim (latest master): https://aur.archlinux.org/packages/zim-git/
System: Linux ArcoB 5.4.87-1-lts #1 SMP Wed, 06 Jan 2021 14:56:05 +0000 x86_64 GNU/Linux
```

I tried to view debug logs (<kbd>Tools</kbd> > <kbd>View debug log</kbd>) and I encounter the following error message:

![ArcoLinux_2021-01-14_16-01-19](https://user-images.githubusercontent.com/8305511/104654612-02582380-5682-11eb-948a-37d37a64be40.png)

I have already went to preferences and made sure that the app is using the system default text editor

![ArcoLinux_2021-01-14_16-01-34](https://user-images.githubusercontent.com/8305511/104654734-359ab280-5682-11eb-8509-503a0b01cb8f.png)

And I have confirmed that there exists an application on my system which can handle opening files with mimetype `text/plain`

![ArcoLinux_2021-01-14_16-01-55](https://user-images.githubusercontent.com/8305511/104654792-506d2700-5682-11eb-9f7f-11fcd4db480c.png)

**Comment by jaap-karssenberg** [comment]
Quick fix is to explicitly configure the editor in Zim preferences.
Apparently your desktop uses a different way than Zim to set the default.

Op do 14 jan. 2021 23:07 schreef smac89 <notifications@github.com>:

**Comment by roland-ruedenauer** [comment]
Current zim code doesn't implement the latest XDG specification. It is looking for a 'defaults.list' file in various locations. XDG [mime-apps-spec](https://specifications.freedesktop.org/mime-apps-spec/latest/ar01s02.html) documents one should look for 'mimeapps.list' files instead. On Manjaro/KDE I found no 'defaults.list' files.

But I already wondered why zim isn't using Gio to get system XDG defaults/recommendations (keeping the fallback to persist it's own preferences).

Using this small addition did work for me and also detects the current system browser application:
```
diff --git a/zim/gui/applications.py b/zim/gui/applications.py
index 11c29f01..558dd8bd 100644
--- a/zim/gui/applications.py
+++ b/zim/gui/applications.py
@@ -260,6 +260,10 @@ class ApplicationManager(object):
                ## generic implementation, it will behave sanely and fall back to system
                ## defaults.
 
+               entry = Gio.app_info_get_default_for_type(mimetype, True) if Gio else None
+               if entry:
+                       return klass.get_application(entry.get_id())
+
                ## TODO: optimize for being called very often ?
 
                for dir in _application_dirs():
```

**Comment by jaap-karssenberg** [comment]
Handling this report as a double of #657
