### ISSUE TITLE
Equation editor does not work

### ISSUE THREAD

**Issue by smac89** [zim-desktop-wiki/zim-desktop-wiki#1365]
At first I thought I was just not using it right, but then I went to the wiki [screenshot page](https://zim-wiki.org/screenshots.html) and tried to replicate what one of the screenshots show

![ArcoLinux_2021-01-14_15-30-36](https://user-images.githubusercontent.com/8305511/104655402-51eb1f00-5683-11eb-955e-b2fdae8b7a11.png)

Only to be met with the following error:

![ArcoLinux_2021-01-14_15-30-52](https://user-images.githubusercontent.com/8305511/104655459-629b9500-5683-11eb-89f9-44a982e8321b.png)

Pressing <kbd>View Log</kbd> shows nothing because of #1364.

I also have all the dependencies installed

**Comment by jaap-karssenberg** [comment]
Please set text editor explicitly in preferences in order to see the log.

**Comment by DeusVermiculus** [comment]
I have the same problem. I tried to follow your instruction but i cannot set a text editor in the preferences (tried to set Libre writer with the Command "/usr/bin/libreoffice --writer --norestore" but just ended up with another error: 

![Screenshot from 2021-01-23 17-40-14](https://user-images.githubusercontent.com/77892780/105608076-14cd0e00-5da2-11eb-81ce-0309e1b04b12.png)


i tried /usr/bin/gedit, same problem Both paths start the app from my terminal without a problem. If i press View Log, it doesnt generate any output.

**Comment by smac89** [comment]
@DeusVermiculus I think you meant to post that comment here: https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/1364

**Comment by DeusVermiculus** [comment]
no. i simply documented why i could not follow Jaap's directions, because this other bug prevents us from doing so. i still have the exact same problem you opened the issue for.

**Comment by introt** [comment]
@DeusVermiculus since the linked issue has been fixed, are you still having this problem: does the equation editor work on your system now?
