### ISSUE TITLE
URL link gets clipped

### ISSUE THREAD

**Issue by swestlake** [zim-desktop-wiki/zim-desktop-wiki#1368]
zimbook 0.71.1(linux)

When a URL is pasted in a notebook page it always loses one character at the end if the character is a brace.

eg, 
If the user pastes,
"https://en.wikipedia.org/wiki/Network_analysis_(electrical_circuits)"

Then Zim-wiki stores the link as
https://en.wikipedia.org/wiki/Network_analysis_(electrical_circuits

Observation:
 - If the user tries to fix the link with Edit-Link from a context menu, and then add the brace manually, the following happens.

Observation 2:
 - The user temporarily can fix the URL-link so long as they don't change pages.
 - Once the user goes to another page and comes back the URL-link now appears without the added brace.

**Comment by mikem23** [comment]
Hmm. I was able to replicate this briefly, but it suddenly stopped working. Even when it did work, the underlying markup text was correct, and the problem disappeared on reload.

**Comment by jaap-karssenberg** [comment]
Can't reproduce exactly as described. Logic for pasting such link changed
in b7ea7b3d6ce572eb558b22a6dc0f4cef723da52f, let's check again after next
release.

-- Jaap

**Comment by introt** [comment]
@swestlake can you reproduce this on 0.74?
