### ISSUE TITLE
Enter key doesn't work when changing height of image

### ISSUE THREAD

**Issue by sanjarcode** [zim-desktop-wiki/zim-desktop-wiki#1369]
When resizing an image, if you change the height and press Enter, the change is not registered. I need to manually press OK.

This does not happen if the width is being changed. In this case Enter must be pressed twice: The first one changes input focus to height and the second one registers the change.

This is small problem, but can be a problem if the user changes height and thinks it's done, but actually it hasn't.

Is the bug in zim-wiki or is it a GTK behavior?

**Comment by introt** [comment]
Fixed by the addition of a new ID field in cc692fb254cf5a9b2530144eb3989316a5807833. The ID field is correctly saved on enter, so this issue can be closed after the 0.74 release.
