### ISSUE TITLE
version control plugin does not commit on "save version" with git on windows

### ISSUE THREAD

**Issue by billguastalla** [zim-desktop-wiki/zim-desktop-wiki#1371]
Environment:
   - Windows 10 x64, en-gb
   - Zim version 0.73.4, installed via "zim-desktop-wiki-0.73.4-setup-w64_x86.exe"

Initial contitions:
  - git installed and available in system path, with (_global_!) user settings configured correctly in git.
  - a notebook with the version control plugin installed and feature enabled, where the git repository has been successfully initialised by the tool.

Steps to reproduce:
  1. Open notebook in zim
  2. Make some changes
  3. File -> Save version...
  4. Write a comment
  5. Click save

Expected result:
  - A new commit is visible in the git repository with all changes, shown either via "git log" or through the zim "File -> Versions.." gui.

Actual result:
  - in top-level folder of notebook when "git status" is ran: changes have been staged for commit, but the commit hasn't happened.
  - when "git log" is ran: no new commit has been made.

Extra notes:
  - in version control settings in zim, both commit on exit and autosave are enabled.
  - zim has managed to initialise a git repo and stage changes, but never commits a change.
  - I have tried separately changing the default commit text editor of git from nano to vim, with no effect on zim's ability to commit.
  - I have tried running zim with "zim.exe --debug" in "git bash (git for windows)" and in cmd, but no logging information is produced (this command works on fedora but there's no issue on fedora)
  - When opening the same notebook with zim in fedora 33, committing new versions works correctly.

Let me know if you need more information.

**Comment by jaap-karssenberg** [comment]
Please try a manual commit and see whether it succeeds. MIght be missing
git configuration or similar.

**Comment by billguastalla** [comment]
Manual commits work with no problem in this set up, and zim will still not commit afterwards.

**Comment by jaap-karssenberg** [comment]
You can check the debug log via "Tools -> View debug log" - maybe some
error logged there ?

**Comment by billguastalla** [comment]
Choosing "Tools -> View debug log" shows this dialogue box:
![image](https://user-images.githubusercontent.com/25847495/105201556-f0222d80-5b38-11eb-8a7c-00ce9f3c59aa.png)
(text editors are installed and usual file extensions are assigned to them (log,txt,text,md etc))

**Comment by billguastalla** [comment]
Okay the problem has a workaround now:
   - The log shows that git commit asks for a user/email. The global .gitconfig for user/email isn't picked up in the cmd instance that zim invokes.
   - I had to via the cmd line add a user name and email local to the repository for committing to work.
   (via "git config user.name" etc, _without_ the  --global option)

There is a fix required for this, or at least a note in the documentation, but I don't know how you get the cmd instance to read the user .gitconfig in windows.

**Comment by introt** [comment]
@billguastalla please let me know if you find [c7aa8bc](https://github.com/introt/zim-desktop-wiki/commit/c7aa8bc8a19f042bb5471cbe4cc260707cd75eb9) satisfactory, thanks!

Edit: added you as a [co-author](https://gist.github.com/ad30bcbdf789aed5bba43082741c7769), thanks for figuring out the workaround!
