### ISSUE TITLE
Dark Theme For Background

### ISSUE THREAD

**Issue by xXBreeKevn42Xx** [zim-desktop-wiki/zim-desktop-wiki#1372]
Hello All,

I am trying to follow this walkthrough for setting Zim to be a dark theme:

https://github.com/jaap-karssenberg/zim-wiki/wiki/Set-a-dark-theme-and-background

It mentions going into the folder:

\Zim Desktop Wiki\etc\gtk-2.0\gtkrc

However, I do not have /etc/ folder in my installation, regardless what version (portable or normal) for Windows. 

Did I miss something or what file do I need to edit in order to change my theme to dark? 

Any help or guidance is appreciated. Thanks!

**Comment by jaap-karssenberg** [comment]
As of zim version 0.70 we use Gtk 3.0 so instructions should be updated to
reflect that.

Please see https://zim-wiki.org/manual/Help/Config_Files.html for
information on Gtk 3 configuration files.

-- Jaap

**Comment by xXBreeKevn42Xx** [comment]
Appreciate the help but reading through, it wants me to edit or reference the file / folder:

"The file location of this configuration is: $XDG_CONFIG_HOME/gtk-3.0/gtk.css . You need to re-start zim to see it take effect."

I do not have that folder gtk-3.0 or the gtk.css anywhere. 

It also references "In addition there are some settings that are not in CSS but can be configured via $XDG_CONFIG_HOME/gtk-3.0/settings.ini ."

Again I do not have that folder, is there something I am missing? 

Thanks,

**Comment by jaap-karssenberg** [comment]
When these files do not exist, you can create them. For your questoin,
especially the settings file is of interest. Please try:

[Settings]
gtk-application-prefer-dark-theme=1

This should trigger default theme to use dark flavor.

Will add a bit more text to the manual and add this example :)


Op do 21 jan. 2021 16:08 schreef BreeKevn <notifications@github.com>:

**Comment by xXBreeKevn42Xx** [comment]
Okay, I wasn't aware of that. Appreciate the input, however, I suppose in this case, I am not too knowledgeable in how to go about this. I created a gtk-3.0 folder inside AppData\Roaming\zim\config\

And from there I created a settings.ini file that contained the "[Settings]
gtk-application-prefer-dark-theme=1" 

Is there anything else I need to do beyond that? It did not change anything inside the application. I apologize with my ignorance in this case.

**Comment by roland-ruedenauer** [comment]
Put your settings.ini file in one of these folders (Windows10 using latest Zim) :
```
<zim-installation-dir>\share\gtk-3.0
<zim-installation-dir>\etc\gtk-3.0
%LOCALAPPDATA%\gtk-3.0
%ProgramData%\gtk-3.0
```

**Comment by xXBreeKevn42Xx** [comment]
Thank you so much! It was the AppData\Local\gtk-3.0 folder by adding the settings.ini file changed it to dark mode. 

Appreciate your input @roland-ruedenauer  & I appreciate your help @jaap-karssenberg  as well!

**Comment by jaap-karssenberg** [comment]
Added note to the manual with this information
