### ISSUE TITLE
Double listing of entries with "ä, ö, ü" in index

### ISSUE THREAD

**Issue by wknds** [zim-desktop-wiki/zim-desktop-wiki#1382]
Hi all,

Entries in an index that contain "ä, ü, ö" could be presented twice (see screenshot below):
<img width="345" alt="Bildschirmfoto 2021-01-27 um 10 20 15" src="https://user-images.githubusercontent.com/25268078/105970822-af1ea180-6081-11eb-8f7c-505776140493.png">

When I create a new subpage with an entry name that also contains one of the character set, then the index is presented correctly:
﻿<img width="288" alt="Bildschirmfoto 2021-01-27 um 10 29 58" src="https://user-images.githubusercontent.com/25268078/105971387-60253c00-6082-11eb-8bea-bcb365aabce1.png">

I am using Zim 0.73.4 on Mac OS 10.14.6 and I am using nextcloud to synchronize the notepad across different devices. Other devices operate on debian buster.

I am not able to reproduce this problem. I created a new subpage and named it with one of the charset above. Zim handles it correctly with no double listing on the index. I also created a textfile on the mac folder with one of the mentioned charset. Zim also handles it correctly. The only thing I observed in between the two approaches is that "ä, ü, ö" have different byte representation:

```
0007020   163 164 054 137 055 137 146 165 314 210 162 137 102 165 147 056
           s   t   ,   _   -   _   f   u    ̈  **   r   _   B   u   g   .
```

```
0007120   071 040 124 145 163 164 137 303 244 137 303 274 137 303 266 056
           9       T   e   s   t   _   ä  **   _   ü  **   _   ö  **   .
```

**Comment by jaap-karssenberg** [comment]
The additional entry in the index is probably caused by a link that uses a
variation in the unicode encoding. Could you check for "backlinks" on the
greyed out page and include the raw unicode for the link as well as for the
correct page name ?

Thanks,

Jaap

**Comment by wknds** [comment]
Here is the octal byte representation of the links from the content of the backlinks that lead to the greyed out entries from above:

```
0003520   052 040 122 157 165 163 163 145 141 165 054 040 112 145 141 156
           *       R   o   u   s   s   e   a   u   ,       J   e   a   n
0003540   055 112 141 161 165 145 163 072 040 133 133 053 102 303 274 143
           -   J   a   q   u   e   s   :       [   [   +   B   ü  **   c
0003560   150 145 162 072 122 157 165 163 163 145 141 165 054 040 112 145
           h   e   r   :   R   o   u   s   s   e   a   u   ,       J   e
0003600   141 156 055 112 141 161 165 145 163 040 055 040 105 155 151 154
           a   n   -   J   a   q   u   e   s       -       E   m   i   l
0003620   040 157 144 145 162 040 303 274 142 145 162 040 144 151 145 040
               o   d   e   r       ü  **   b   e   r       d   i   e    
0003640   105 162 172 151 145 150 165 156 147 174 105 155 151 154 040 157
           E   r   z   i   e   h   u   n   g   |   E   m   i   l       o
0003660   144 145 162 040 303 274 142 145 162 040 144 151 145 040 105 162
           d   e   r       ü  **   b   e   r       d   i   e       E   r
0003700   172 151 145 150 165 156 147 135 135 012 052 040 106 162 151 163
           z   i   e   h   u   n   g   ]   ]  \n   *       F   r   i   s
```

```
0005660   147 163 153 157 155 160 141 163 163 135 135 012 052 040 123 143
           g   s   k   o   m   p   a   s   s   ]   ]  \n   *       S   c
0005700   150 155 151 144 054 040 127 145 162 156 145 162 072 040 133 133
           h   m   i   d   ,       W   e   r   n   e   r   :       [   [
0005720   053 102 303 274 143 150 145 162 072 123 143 150 155 151 144 054
           +   B   ü  **   c   h   e   r   :   S   c   h   m   i   d   ,
0005740   040 127 145 162 156 145 162 040 055 040 107 154 303 274 143 153
               W   e   r   n   e   r       -       G   l   ü  **   c   k
0005760   174 107 154 303 274 143 153 135 135 012 052 040 123 143 150 167
           |   G   l   ü  **   c   k   ]   ]  \n   *       S   c   h   w
```

**Comment by wknds** [comment]
The name of the file which are referred to by the links:

```
0000000   122 157 165 163 163 145 141 165 054 137 112 145 141 156 055 112
           R   o   u   s   s   e   a   u   ,   _   J   e   a   n   -   J
0000020   141 161 165 145 163 137 055 137 105 155 151 154 137 157 144 145
           a   q   u   e   s   _   -   _   E   m   i   l   _   o   d   e
0000040   162 137 165 314 210 142 145 162 137 144 151 145 137 105 162 172
           r   _   u    ̈  **   b   e   r   _   d   i   e   _   E   r   z
0000060   151 145 150 165 156 147 056 164 170 164 012                    
           i   e   h   u   n   g   .   t   x   t  \n                    
0000073
```

```
0000000   123 143 150 155 151 144 054 137 127 145 162 156 145 162 137 055
           S   c   h   m   i   d   ,   _   W   e   r   n   e   r   _   -
0000020   137 107 154 165 314 210 143 153 056 164 170 164 012            
           _   G   l   u    ̈  **   c   k   .   t   x   t  \n            
0000035
```

**Comment by jaap-karssenberg** [comment]
Created a test case for the test suite but cannot reproduce the issue.
Tried different representations of "Gluck" (with the umlaut on the u) and
combinations of first creating the page or first creating the link. But so
far all seems to work correctly and no redundant placeholder shows up in
the index.

Only thing I can still think about is that the behavior *might* be
localization - so will check in the test in the test suite.

If you happen to find out how to reproduce this issue, please let me know.

Regards,

Jaap

**Comment by jaap-karssenberg** [comment]
Interestingly, same test succeeds on windows but fails now I run it on linux ... something to track down here :)

**Comment by jaap-karssenberg** [comment]
Believe I have a fix - cannot test on Mac, but fixes the issue on Linux

**Comment by wknds** [comment]
In the meanwhile, I managed to reproduce the error on my setup.
On Debian Buster:
1. Create a subpage with a umlaut in the name
2. Make a link to that subpage from a page above
3. Sync over Nextcloud

On Mac:
4. Sync over Nextcloud
5. Subpage from step 1 is redundant.

I try to test your changes in the next days.

**Comment by jaap-karssenberg** [comment]
Can you test with the develop branch?  Commit  65b71e8 should fix this
issue.

**Comment by wknds** [comment]
I tested on the development branch. It yields the following result:
### Test 1
On Debian Buster (`development` branch):

1. Create a subpage with a umlaut in the name
2. Make a link to that subpage from a page above
3. Sync over Nextcloud

On Mac (`development` branch):
4. Sync over Nextcloud
5. Subpage from step 1 is **not** redundant **anymore**.

### Test 2
On Debian Buster (`0.68`):

1. Create a subpage with a umlaut in the name
2. Make a link to that subpage from a page above
3. Sync over Nextcloud

On Mac (`development` branch):
4. Sync over Nextcloud
5. Subpage from step 1 is redundant.

### Comment
From test 1 i would say it is fixed now. Did your fix change the way how links with umlaut are stored in the text files?

**Comment by jaap-karssenberg** [comment]
No, I did not change how things are stored, but how they are indexed. The
key used for resolving links is normalized unicode, so both representations
match the same page. Same way links also resolve case-insensitive.

-- Jaap
