### ISSUE TITLE
improve table integration

### ISSUE THREAD

**Issue by eoli3n** [zim-desktop-wiki/zim-desktop-wiki#1392]
If you create a table with the table plugin, and backspace it, you can't restore it with CTRL+Z

**Comment by sanjarcode** [comment]
Yes, the table does not support many conventional features, like undo, redo, next cell, etc.
I don't think this a bug, it is primitive by design.

**Comment by eoli3n** [comment]
so consider this as a feature request for a less primitive table integration :)

**Comment by eoli3n** [comment]
no news about this ? A wiki without the ability to safely use a table is not cool.

**Comment by dehesselle** [comment]
Every fix and every feature needs someone to work on it. If you don't contribute the necessary changes yourself but want others to do it for you, you can only be patient. Our resources are limited.

**Comment by eoli3n** [comment]
What a useful text.

**Comment by dehesselle** [comment]
There was actually no passive/aggressive intent in my answer. But always assuming the worst in people you don't know - nice one.

Also I don't see how "someone needs to do the work - if it's not you, be patient" is "nothing". It's the exact answer to why there have been no updates in this issue yet.

Do you want to reconsider and reopen?

**Comment by eoli3n** [comment]
Yes, I took your previous message the bad way, it can be read as the classic "That's FOSS, just PR what you want", but I'm not a dev.
I was just poping up that issue, to see if someone is interested by the feature as I am.

**Comment by jaap-karssenberg** [comment]
Actually this is one of my most high prio things to fix, see https://github.com/zim-desktop-wiki/zim-desktop-wiki/wiki/Planning#2-usability-issues-that-must-be-fixed-for-100

For now consider it duplicate of #203
