### ISSUE TITLE
Unicode chars input unsupported since Zim 0.73.3

### ISSUE THREAD

**Issue by Atronach** [zim-desktop-wiki/zim-desktop-wiki#1394]
In my Zim pages I used to type Unicode characters by pressing Ctrl+Shift+U... an underscored _U_ would appear and then I'd type an Unicode character code point in hexadecimal as found at [https://www.fileformat.info/info/unicode/char/search.htm](https://www.fileformat.info/info/unicode/char/search.htm).

E.g when typing the "degree sign" which code is "U+00B0" I'd press Ctrl+Shift+U, type "00b0" and then hit space. The result would be the degree sign.

But now in Zim 0.73.5 it doesn't work. I checked it goes back through 0.73.4 to 0.73.3. 0.73.2 is the last Zim version which accepts Unicode characters this way.

The Insert symbol plugin alternative is not ideal since it only contains a subset of Unicode characters and sometimes they are difficult to find in the _symbols.list_ file.

Tested on Win10x64.

**Comment by jaap-karssenberg** [comment]
To be honest I never heard of that feature before - not coded in zim
itself, might be a Gtk core feature ?

Could extend the "insert symbol" plugin to also accept key codes directly

**Comment by Atronach** [comment]
I've search the Internet and it indeed is reported to be a feature of either the GTK library or ibus:
https://bbs.archlinux.org/viewtopic.php?id=171531
https://wiki.archlinux.org/index.php/IBus
https://bugreports.qt.io/browse/QTBUG-8
https://github.com/keepassxreboot/keepassxc/issues/1872
https://github.com/telegramdesktop/tdesktop/issues/1288
https://en.wikipedia.org/wiki/Unicode_input
https://askubuntu.com/questions/557147/why-has-my-ctrlshiftu-key-for-unicode-input-stopped-working

It's little confusing since some of the above mentioned links report it to be a function of ibus but it worked for me on Windows where ibus isn't available and thus it probaby isnn't packaged in the Windows Zim installer.

I guess I could report the bug at https://gitlab.gnome.org/GNOME/gtk/-/issues??utf8=%E2%9C%93, but I don't know what version of GTK is packaged with Zim 0.73.2 and the last one which I suspect they will want to know.

**Comment by Atronach** [comment]
OK, I've found the GTK version in the "libgtk-3-0.dll" file in the Zim installation directory. So I've reported bug at: https://gitlab.gnome.org/GNOME/gtk/-/issues/3693

Feel free to add information if deemed necessary.

**Comment by jaap-karssenberg** [comment]
Btw. not sure how many chars you typically use, but if it is just a
handful, you can use the "insert symbol" plugin and configure your own
shortcuts by modifying the configuration file. You don't need to use the
dialog, you can also directly type the shortcuts and they will be converted
on the fly.

-- Jaap

**Comment by Atronach** [comment]
OK, I've found a fix here:
https://www.fileformat.info/tip/microsoft/enter_unicode.htm
...method 1: Universal works and does exactly what I want. It allows to uniformly input ANY Unicode character based on its hexadecimal code regardless of the selected keyboard layout. I only had to create the described registry key.
