### ISSUE TITLE
link page cannot be unlinked

### ISSUE THREAD

**Issue by totohaha** [zim-desktop-wiki/zim-desktop-wiki#1399]
when note "android.hardware.bluetooth@1.0-service" in the zim page,
it will automatically create a new page (greyed out) named the same.
and it cannot be deleted even choose "Remove Link" from right mouse click.

**Comment by j41rj** [comment]
when I add an e-mail address in some note, zim always create a link. If I "remove link" and open again the note, It returns! There is some way to avoid this?

**Comment by jaap-karssenberg** [comment]
URLs and email addresses are auto-formatted. Only way to prevent that is to
put them in "verbatim" formatting.

**Comment by totohaha** [comment]
Thanks
