### ISSUE TITLE
feature request: order of pages

### ISSUE THREAD

**Issue by CRZeiss** [zim-desktop-wiki/zim-desktop-wiki#1403]
The order of the pages in a notebook is automatically alphabetical at all levels.
Is there any possibility to rearrange the pages manually?

For example: first "Home", then "Development", then "Customers", then "Documentation"

**Comment by roland-ruedenauer** [comment]
Guess you're not the first one missing this feature ... see #32. I'd also appreciate having more control over the page ordering in Zim.

**Comment by quesada** [comment]
I'm looking fwd to this feature too. It's on the v1 milestone I think. I imagine Jaap categorizes it as a 'hard one' because internally zim notes are files and folders.

**Comment by ihavenomouth** [comment]
My workaround is to name the files with a number. E.g.
1 Installation
2 Configuration
3 Use
...

**Comment by introt** [comment]
Duplicate of #32
