### ISSUE TITLE
Is there any way to modify the inter-paragraph space?

### ISSUE THREAD

**Issue by quesada** [zim-desktop-wiki/zim-desktop-wiki#1405]
On the current setup, I press enter to leave space between paragraphs. by default it's the same as inter-line space. This makes for harder-to-read text.

It might be an easy fix, but I don't know the internals of the GTK view used.

**Comment by sojusnik** [comment]
This should help, if I understand you correctly: 
https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/86
https://bugs.launchpad.net/zim/+bug/1537876
https://answers.launchpad.net/zim/+question/264064

**Comment by quesada** [comment]
Thanks, yes that solves the problem. I had to go to 20 to see the effect.

**Comment by sojusnik** [comment]
> Thanks, yes that solves the problem. I had to go to 20 to see the effect.

Great! Close this issue then?
