### ISSUE TITLE
Cannot cut (copy) a paragraph with equation inside.

### ISSUE THREAD

**Issue by Farid010** [zim-desktop-wiki/zim-desktop-wiki#1406]
I have a paragraph with an equation in the middle of it. I have inserted the equation using the "Insert Equation" plugin. It is not possible to copy or cut that paragraph and paste it in another location of the same file.

![Screenshot 2021-02-24 114122](https://user-images.githubusercontent.com/51115900/108988949-57318580-7695-11eb-9c69-7c41d6ca3484.png)

**Comment by Daksol** [comment]
Have you tried looking at the underlying source code via the Tools -> Edit Source option? That should make it clear how that particular content type is handled - and if you cut and paste a paragraph containing the formula to elsewhere in the file, you should find it works.

**Comment by jaap-karssenberg** [comment]
Yes, copy-pasting inline objects (like an equation) needs fixing - it is
high on my list (but given speed will take a while ...)

**Comment by introt** [comment]
Can't reproduce with 0.74 - may be already fixed?
