### ISSUE TITLE
Windows 10 (Touchpad) Scrolling

### ISSUE THREAD

**Issue by pdev77** [zim-desktop-wiki/zim-desktop-wiki#1408]
Using zim-desktop-wiki-0.73.5-setup-w64_x86.exe (and earlier versions of 0.73 too) there are bugs in touchpad scrolling on windows10.
This isn't exclusive to one particular laptop/setup - as I have both a Dell & HP install that behave exactly the same.
Whilst the GUI looks beautiful with 0.73 (the reason for upgrading from 0.71 I think it was where the GUI appeared blurred) - scrolling particularly with the touchpad results in screen tearing, and results in editing the wrong line etc.
Mouse wheel scrolling is better - but not right. 
What other information can I provide ?

**Comment by jaap-karssenberg** [comment]
Can't reproduce on my system. Fron the sound of it, this might be Gtk
related and not Zim specific. There is no code in zim directly handling
scroling.

-- Jaap

**Comment by pdev77** [comment]
Is there anything I could do help diagnose this ?
Or how would this be raised with Gtk? Version 0.68 doesn’t have this issue – so I’ve reverted to that for now – but it suffers the Win10 blurriness to some degree – but thats better than tearing…

Paul

**Comment by pdev77** [comment]
I've done some more testing, the issues are possibly down to Windows10.. (as you probably suspected)
On a HP ProBook x360 laptop - zim 0.73 tears badly eg-
![Screenshot 2021-03-03 142828](https://user-images.githubusercontent.com/17301585/109952071-57a1d000-7cd6-11eb-8678-d59c73ef1997.png)
However, on a external monitor all works fine (even scrolling with the touchpad)
Using zim 0.69 behaves fine, however text is somewhat blurred. 
Applying the Windows10 "High DPI scaling override 'Application'" corrects the blurry text - and still no tearing occurs.

**Comment by pdev77** [comment]
I found out this is due to the sourceview plugin - no issues with that disabled.
Issue affects both windows and linux desktops
