### ISSUE TITLE
Windows installer: 'silent install' switch requested

### ISSUE THREAD

**Issue by bkidwell** [zim-desktop-wiki/zim-desktop-wiki#141]
An anonymous user in the chat room requested a silent install mode in the Windows installer package, for enterprise deployment.

This should be added to the installer AND to the uninstaller script.

Please assign this to @bkidwell .

**Comment by MarshP** [comment]
Bumping this. The installer can now be added to enterprise Ninite (and choco?) app repos if it has a silent install.

**Comment by jaap-karssenberg** [comment]
Sorry for my lack of understanding / experience with these repos - but what
should this switch do ?

-- Jaap

**Comment by MarshP** [comment]
Allow silent install once the installer is launched; no user intervention and no notifications.

**Comment by jaap-karssenberg** [comment]
You mean no windows, or also no terminal output ?

Probably this requires someone with more NSIS experience to look into.

-- Jaap
