### ISSUE TITLE
Task List plugin bug ?

### ISSUE THREAD

**Issue by Nick222** [zim-desktop-wiki/zim-desktop-wiki#1410]
Xubuntu 20.10
Zim 0.73.5

Open TaskList and then close.

In terminal-window:

> DEBUG: Opening dialog "Task List"
> (zim:119830): Gtk-CRITICAL **: 20:56:59.880: gtk_button_box_set_child_secondary: assertion 'gtk_widget_get_parent (child) == GTK_WIDGET (widget)' failed
> (zim:119830): Gtk-CRITICAL **: 20:56:59.880: gtk_button_box_set_child_non_homogeneous: assertion 'gtk_widget_get_parent (child) == GTK_WIDGET (widget)' failed
> (zim:119830): Gtk-CRITICAL **: 20:56:59.880: gtk_button_box_set_child_secondary: assertion 'gtk_widget_get_parent (child) == GTK_WIDGET (widget)' failed
> (zim:119830): Gtk-CRITICAL **: 20:56:59.880: gtk_button_box_set_child_non_homogeneous: assertion 'gtk_widget_get_parent (child) == GTK_WIDGET (widget)' failed
> DEBUG: Closed dialog "Task List"

**Comment by introt** [comment]
Gtk warnings are mostly harmless, and can be ignored if everything's working fine.
