### ISSUE TITLE
table sort with negative numbers

### ISSUE THREAD

**Issue by zihlmalb** [zim-desktop-wiki/zim-desktop-wiki#1411]
When I add a table like following which contains negative numbers in a column, sorting by the number column doesn't work correctly.

- Initial Table:
![image](https://user-images.githubusercontent.com/73816411/109980551-538aa800-7d00-11eb-9200-71315f09aced.png)

- After sorting by number:
![image](https://user-images.githubusercontent.com/73816411/109980744-7fa62900-7d00-11eb-97f9-e1f8e97b2478.png)

Zim 0.73.5
on Ubuntu 20.04

**BTW**: It would be nice to have the sorting-feature disengageable. Sorting can destroy a given table row ordering without the possibility for undoing.

**Comment by introt** [comment]
Consider merging this with #1414
