### ISSUE TITLE
Update help entry on hyperlinks in Table cells

### ISSUE THREAD

**Issue by Daksol** [zim-desktop-wiki/zim-desktop-wiki#1413]
This is hopefully the sort of issue that any development team should like. Some feature actually works rather better than the Help documentation says.

In the "Superior Table Operations" page in the Help it says that 

`You can not use a special link text. The link text is the url, the mail-address or the Title of the linked page.`

In fact this can be done.

>`Links in cells can be entered like this:-`
>`[[https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues\|Zim wiki issues on Github]]`

The only tricky bit is the inclusion of a backslash before the vertical line character to "escape" it.

**Comment by introt** [comment]
Good catch! Furthermore, it seems the backslash is added automatically while editing via the GUI. Adding a link without one via editing the source file breaks the table.
