### ISSUE TITLE
Feature request: change background color of CTRL+T text

### ISSUE THREAD

**Issue by mid-kid** [zim-desktop-wiki/zim-desktop-wiki#1416]
I'm currently abusing the CTRL+T feature to create unhighlighted code blocks, as well as `inline` highlighted terms, like people do in a lot of wikis, as opposed to using "quotes".

Just like here on github issues, I'd like to change the background color of CTRL+T'd text, just like it appears `here on github`. Currently, all that changes is the text color, and it becomes monospaced, but I find this to be hard to tell apart at times.

**Comment by sojusnik** [comment]
Try to play around with `~/.config/zim/style.conf`, see Zim's manual for further references.

I use:
```
[Tag code]
background=#f0f0f0

[Tag pre]
background=#f0f0f0
paragraph-background=#f0f0f0
```

**Comment by mid-kid** [comment]
Thanks, that's significantly better and solves my issue.
