### ISSUE TITLE
MacOS: No "File --> Properties"?

### ISSUE THREAD

**Issue by fladd** [zim-desktop-wiki/zim-desktop-wiki#1422]
I am not sure how to edit a notebook's properties on MacOS. On Windows there is a "File --> Properties" menu entry, but this does not exist under MacOS.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/2971539/111210919-1f4f9b00-85ce-11eb-9001-64bab6aa6adc.png">

I am using version 0.73.4.

**Comment by gagarine** [comment]
With the MacOS Menu Bar plugin activated I do not have such a problem.

**Comment by dehesselle** [comment]
Issue not present in current release.
