### ISSUE TITLE
Win10: external link to zim notebook and page

### ISSUE THREAD

**Issue by CRZeiss** [zim-desktop-wiki/zim-desktop-wiki#1424]
Hi,
I would like to create a .lnk-file leading to a zim notebook and a specific page.

For example:
Notebook: G:\notebook.zim
Page: Handbuch:Zugang:Rechner

Link to the notebook G:\notebook.zim works and opens the notbook.
Link to G:\notebook.zim#Handbuch:Zugang:Rechner does not work

Is there any possibility to create external links to a specific page of a notebook???

Carl

**Comment by Nick222** [comment]
+100500 :)

**Comment by CRZeiss** [comment]
?????

**Comment by jaap-karssenberg** [comment]
If you open the text file for the page with Zim, it will figure out the
notebook. So challenge is to make a link file that knows to use zim.

Op zo 21 mrt. 2021 06:27 schreef CRZeiss ***@***.***>:

**Comment by Nick222** [comment]
But how to force the system to open it in Zim using a link to such a file?
