### ISSUE TITLE
Suggestion: add option in Preferences to stop auto-folding sub-sections that losed focus

### ISSUE THREAD

**Issue by hsandt** [zim-desktop-wiki/zim-desktop-wiki#1425]
Currently, a sub-section that gains focus is immediately unfolded, which is fine. But as soon as I select another page/section (that is not under this sub-section), the sub-section folds back. This is problematic when trying to compare to sub-pages or quickly navigate between deep pages under the same section (e.g. for a given project).

This seems to only happen for sub-sections, not root sections. It seems to be by design, so instead of asking for a fix that would disable auto-folding, I am requesting an option in the Preferences to enable/disable auto-folding sub-sections that lose focus (or, to be more exact, when user focuses on another page/section that is not a direct or indirect child of that sub-section).

Bonus: an option to enable/disable auto-unfolding. It doesn't bother me but in cases where a page has many sub-pages, and the user just wanted to check the root, it may be desirable. The user can still click on the folding arrow to manually unfold it.

Even though it's a suggestion, I can give repro steps similar to bugs to show an example of auto-folding:

Reproduction:
1. Create a hierarchy with Root Section > 2 Sub-Sections > 1 page in each sub-section
2. Click on Root Section to reveal the 2 Sub-Sections
3. Click on the first Sub-Section. It automatically unfolds. You can click on its child.
4. Click on the second Sub-Section. The first Sub-Section automatically folds back.

Tested on:
Linux Ubuntu 18.04 - Zim 0.73.4

**Comment by nelas** [comment]
Hi @hsandt,

This option already exists. Go to `Edit > Preferences > Plugins > Page Index > Configure` and un-check `Automatically collapse sections on close page`.

Cheers

**Comment by hsandt** [comment]
Wow, thanks, I didn't expect it to be in a plugin!

I'll close this ticket now.
