### ISSUE TITLE
macOS: Default Text Editor do not launch system default text editor

### ISSUE THREAD

**Issue by gagarine** [zim-desktop-wiki/zim-desktop-wiki#1427]
In the preferences text editor is set to system default:
![Screenshot 2021-03-24 at 20 10 38](https://user-images.githubusercontent.com/164074/112369885-038a7a00-8cdd-11eb-9fb6-7979df70e2c6.png)

With this configuration, Zim do not find a text editor on macOS (for example when opening the log file).

Adding an application with command `open /System/Applications/TextEdit.app ` seems to works.

**Comment by dehesselle** [comment]
This is fixed in our (now official) app for macOS.
