### ISSUE TITLE
italic style unrendered

### ISSUE THREAD

**Issue by pityhero233** [zim-desktop-wiki/zim-desktop-wiki#1429]
this happens sometimes, when I make a line italic (selecting a line, pressing Ctrl-I), and open it later, it will show as is in the raw format instead of rendering as italics:

what should be

_(using elementary knowledge, treating Gaussian as the process of elementary elimination):_

now becomes

//(using elementary knowledge, treating Gaussian as the process of elementary elimination)://

**Comment by jaap-karssenberg** [comment]
Known issue due to the ":" believe it is fixed in recent versions

Op do 25 mrt. 2021 09:13 schreef Shi Zhengyu ***@***.***>:

**Comment by bttrx** [comment]
> Known issue due to the ":" believe it is fixed in recent versions

Doesn't seem to be fixed. Occurs to me in version 0.75.2 on Linux Mint 20.2 MATE.

Example:

![grafik](https://github.com/zim-desktop-wiki/zim-desktop-wiki/assets/15858666/334c8d70-e539-4779-8fca-41083f1ad3a6)

**Comment by bttrx** [comment]
But bold, underline, and stroked, work fine with a trailing colon `:`.

**Comment by jaap-karssenberg** [comment]
Yes there is a special case for italic due to the "://" combination
triggering URL detection. Can only solve this by changing the parser from a
one-pass to a two-pass method. It is on my backlog, but not highest prio.

--- Jaap
