### ISSUE TITLE
Alt + V can't be used for keybind

### ISSUE THREAD

**Issue by heylix** [zim-desktop-wiki/zim-desktop-wiki#1431]
If you want to use the keybind `Alt+V`, Zim just doesn't register it.

Fedora 33 with KDE/Kwin-X11. All other keys seem to work in combination with `Alt`. `Alt+Shift+V` works, too.

I didn't bind it in KDE's shortcuts.

**Comment by jaap-karssenberg** [comment]
Afraid that is Gtk upstream then, nothing we do in zim specific to handle keybindings that limits this
