### ISSUE TITLE
Gmail formatting

### ISSUE THREAD

**Issue by mbakstars** [zim-desktop-wiki/zim-desktop-wiki#1432]
Gmail formatting of text both to and from is corrupting different ways. Is there something I am doing wrong. W10. I use the app for writing SOP that's missing in my office and would like to include template as for emailing other departments within my large office environment (not the owner). 

As noted in another post underline is also not working correctly to and from any program on windows. Wasn't sure if the two issues are related. 

Thank you!

**Comment by jaap-karssenberg** [comment]
Can you give a concrete example that can be reproduced as a test case?

Op za 27 mrt. 2021 18:19 schreef mbakstars ***@***.***>:

**Comment by mbakstars** [comment]
Sure the info I will have to change (internal procedures). Will get to that later today .

**Comment by mbakstars** [comment]
Zim
![image](https://user-images.githubusercontent.com/31328113/113335257-287c7f80-92d1-11eb-9c1e-eb9cbc293117.png)

gMail
![image](https://user-images.githubusercontent.com/31328113/113335313-3af6b900-92d1-11eb-9edd-6d7052e0da5d.png)

**Comment by mbakstars** [comment]
Note the highlight should be underline, as I did ctrl+U but it shows as (zim) as highlight. Gmail does handle tabs different, it does not accept tab as formatting but UI. So in order to tab, shortcut wise, in gmail you use CTRL+[ . Hope this helps.

**Comment by mbakstars** [comment]
It also seems that more than one tab to even a column isn't supported directly in gmail too, might contribute to my issue.

**Comment by jaap-karssenberg** [comment]
The underline being rendered as highlight is a "feature" - zim does not
have a separate underline style, so mark is used, and default rendered as
highlight. You can change the style config in the "styles.conf" file.

The tabs are very hard to get right in any case - probably the only way to
get those correct would be to implement an "paste as table" feature, which
would insert a table and give you some options how to convert text to
columns (like e.g. Excel import text )

**Comment by mbakstars** [comment]
Many thanks! I am getting back into coding - so this will be great to work on.
