### ISSUE TITLE
Export Preferences Feature Request/Options?

### ISSUE THREAD

**Issue by mbakstars** [zim-desktop-wiki/zim-desktop-wiki#1433]
Hoping there is way to export preferences from one system to another. 

Background: I tried installing the portable version on Windows, well portable apps drive, and it deleted the entire directory/drive.  So, I installed the windows versions on the 4 pcs I use for work, with google drive folder as the backend.  

Need: I was hoping to sync the preferences as I change them on each system by exporting. Or if there was a way I could export their values if nothing else.

Notes: I'm more an end user than programmer, so I am unsure how to go about this myself. 

Thank you for this wonderful program, helping me to write SOPs for my office!

**Comment by jaap-karssenberg** [comment]
Well, there are not that many preferences, so unless you change them very
often I think having an export / sync feature is a bit over doing it. If
you want you can pick the "preferences.conf" file from one system and copy
it to the next. That should do it.

**Comment by mbakstars** [comment]
Many thanks. I will try this and let you know if I run into any issues. I am on W10E PCs.
