### ISSUE TITLE
Spellcheck not working - I am also unable to access spell checks options. - Zim 0.73.5

### ISSUE THREAD

**Issue by Just-Another-Gnumer** [zim-desktop-wiki/zim-desktop-wiki#1435]
I cannot access the "configure" options in the spell check plugin.
![image](https://user-images.githubusercontent.com/78667207/113343949-01996a00-9320-11eb-8669-ac3407b7a994.png)

I ran pip3 install pyenchant pygtkspellcheck and installed all of these packages.

![image](https://user-images.githubusercontent.com/78667207/113344203-491ff600-9320-11eb-96ab-03d60c2e2496.png)

Is there anyway to fix this? I would like to have the spellcheck working.

**Comment by jaap-karssenberg** [comment]
From the screenshot it looks like spellcheck is in fact enabled, did you
try using it ?

If it does not work, have a look at the debug output (zim --debug) and
check you have dictionaries installed for gtkspellcheck to use

-- Jaap

**Comment by Just-Another-Gnumer** [comment]
I just checked by right clicking and it does work. I don't know what went wrong or if I missed something.
