### ISSUE TITLE
Double selection of a title within a note?

### ISSUE THREAD

**Issue by Nick222** [zim-desktop-wiki/zim-desktop-wiki#1437]
When I click on one of the section headings within a note, that heading is highlighted.
However, it cannot be copied.
To copy it, you have to remove the selection, and then select it again with your hands.

Why is this happening and how to get rid of this double selection?

Xubuntu 20.10
Zim 0.73.5

**Comment by jaap-karssenberg** [comment]
The search function does highlighting but it is not the same as selection

Op zo 4 apr. 2021 10:47 schreef Nick222 ***@***.***>:
