### ISSUE TITLE
What is the maximum no of nodes with text is supported?

### ISSUE THREAD

**Issue by javadevelopment4** [zim-desktop-wiki/zim-desktop-wiki#1440]
Hi,

What is the maximum no of nodes with text is supported to do full content search...

In in the initial version, the search was slow for 2,000 nodes.

Thanks

**Comment by javadevelopment4** [comment]
Import of entire files got failed and crashed. attached the sample files for reference  - https://easyupload.io/ry11mq

**Comment by jaap-karssenberg** [comment]
Please report error message here
