### ISSUE TITLE
Issue with retrolink (trackbacks) in HTML export

### ISSUE THREAD

**Issue by Damienbis** [zim-desktop-wiki/zim-desktop-wiki#1445]
Hello, I have a problem with retrolinks on HTML export.
When I click on a retrolink at the bottom of the page, it takes me to a page that cannot be found because the link has been shortened.
For example, if the retrolink is normally: mysite/page/file/abcdef; for some reason, the link at the bottom of the page reads: mysite/page/file/abc ("d.e.f" is missing). I don't know why when exporting, retrolinks that are long are systematically cut off. Hope my question is clear. Thank you for your answers.

**Comment by jaap-karssenberg** [comment]
Can you give a more specific example to reproduce ?

-- Jaap

**Comment by Damienbis** [comment]
Thank you for the answer. I hope that this exemple will help you to
understand:

For example when I click to the retrolink in this page :
[image: image.png]

It sends me to a wrong page with the address:
[image: image.png]
*"https://veritas-liberabit-vos.go.yo.fr/Home/Th%C3%A9ologie/Th%C3%A9ologie_Morale/Fondements_bibliques_de_la_Th%C3%A9ologie_Morale/1._Introduction_(l
<https://veritas-liberabit-vos.go.yo.fr/Home/Th%C3%A9ologie/Th%C3%A9ologie_Morale/Fondements_bibliques_de_la_Th%C3%A9ologie_Morale/1._Introduction_(l>"*

But, in fact, the right address is :
*"https://veritas-liberabit-vos.go.yo.fr/Home/Th%C3%A9ologie/Th%C3%A9ologie_Morale/Fondements_bibliques_de_la_Th%C3%A9ologie_Morale/1._Introduction_(l'%C3%89criture_Sainte,_%C3%A2me_de_la_th%C3%A9ologie_morale).html
<https://veritas-liberabit-vos.go.yo.fr/Home/Th%C3%A9ologie/Th%C3%A9ologie_Morale/Fondements_bibliques_de_la_Th%C3%A9ologie_Morale/1._Introduction_(l'%C3%89criture_Sainte,_%C3%A2me_de_la_th%C3%A9ologie_morale).html>"*
It missed a part of the address. Maybe it's too long.

Best regards
Damien

Le mer. 9 juin 2021 à 09:54, Jaap Karssenberg ***@***.***> a
écrit :

> Can you give a more specific example to reproduce ?
>
> -- Jaap
>

**Comment by jaap-karssenberg** [comment]
Can't see the images - they dropped out of your post I'm afraid. But I think the apostrophe in this link is probably a good clue on what triggers the issue. Can you confirm the issue only occurs with backlinks that contain a apostrophe ?

**Comment by Damienbis** [comment]
I tried others links and indeed it seems connected with the " *'* "
(apostrophe):

-
https://veritas-liberabit-vos.go.yo.fr/Home/%C3%89critures_Saintes/Ancien_Testament/Nevi
(vs.
https://veritas-liberabit-vos.go.yo.fr/Home/%C3%89critures_Saintes/Ancien_Testament/Nevi'im.html
)
- https://veritas-liberabit-vos.go.yo.fr/Home/Histoire/Histoire_de_l (vs.
https://veritas-liberabit-vos.go.yo.fr/Home/Histoire/Histoire_de_l'%C3%89glise/Renaissance/II._Les_causes_religieuses_de_la_R%C3%A9forme.html
)
- https://veritas-liberabit-vos.go.yo.fr/Home/Th%C3%A9ologie/L (vs.
https://veritas-liberabit-vos.go.yo.fr/Home/Th%C3%A9ologie/L'homme_dans_la_gr%C3%A2ce_de_Dieu/V._La_gr%C3%A2ce_sanctifiante.html
)

Thank you for your help

Le mer. 9 juin 2021 à 13:18, Jaap Karssenberg ***@***.***> a
écrit :
