### ISSUE TITLE
"redo" und "undo" commands are not working

### ISSUE THREAD

**Issue by brainbow1** [zim-desktop-wiki/zim-desktop-wiki#1446]
I have set the following keybinds:

Strg+Left: undo
Strg+Right: redo

first everything worked great, but then I upgraded to new version (installing via PPA ob ubuntu 20.04) and now this function is not working anymore. Neither via Keybind nor per dropdown menu.

Appreciate ur help.
Thanks for this great zim tool! I love it!

**Comment by jaap-karssenberg** [comment]
Please have a look at the debug output, should tell whether the action does not get triggered or whether an error occurs during the action

**Comment by brainbow1** [comment]
how can I get to the debug output?

**Comment by brainbow1** [comment]
I just sent the debug output to u via email

**Comment by jaap-karssenberg** [comment]
understood via mail that issue disappeared - please re-open if it returns
