### ISSUE TITLE
Ordered lists exporting to markdown won't convert letters to numbers

### ISSUE THREAD

**Issue by whydnct** [zim-desktop-wiki/zim-desktop-wiki#1447]
Might be an issue with Pandoc rather than with Zim but, when exporting to markdown, letter ordered lists wont convert to number ordered lists in markdown, and won't be recognized as ordered lists

**Comment by jaap-karssenberg** [comment]
Agree this is a bug - markdown does not support letter numbered lists, so
should be converted to numbered on export
