### ISSUE TITLE
auto-copy when selected

### ISSUE THREAD

**Issue by Mojusko** [zim-desktop-wiki/zim-desktop-wiki#1448]
Hello, I update to a newever version of Zim and it has an annoying feature when selecting a word it automatically puts it in a clipboard and deselects it. I want to disable this function; can you point me to the solution or is this a bug?

**Comment by jaap-karssenberg** [comment]
Have not heard of this issue before. Can you be more specific on the zim
version and the platform (windows / linux / ...) ?  Also please include
detailed steps *how* you select.

Thanks,

Jaap

**Comment by Mojusko** [comment]
Sorry. It was not zim related. It was wrong plasma settings.
