### ISSUE TITLE
taskdate plugin (formerly duedate)

### ISSUE THREAD

**Issue by muguu** [zim-desktop-wiki/zim-desktop-wiki#145]
I updated the **duedate** plugin to work with ZimWiki > 0.66 with the new start date / due date format.
As there is also a start date possible now, I renamed the plugin to **taskdate**.

Any feedback welcome!
Regards,
Murat

Download at following link:
https://gist.github.com/muguu/114c3ac0e1dad0a1b16a3bf9af6745d3#file-taskdate-py

This plugin provides a dialog to quickly add a start and/or due date for a task.
It activates on > or < within a task or via keyboard shortcut \<CTRL> + (period).
All new formats are accepted. The old due date format is changed to the new format.

**Keys used:**
\<TAB>: You can switch between the start and the due date with the TAB key (same as mouse click on the tab)

\<ENTER>: The date is inserted into the page. If both dates are altered, both are inserted.

\<Mouse double click on calendar>: Same as \<ENTER>

\<SHIFT + ENTER> : Both dates are inserted into the page, no matter if they were altered or not.

\<SHIFT + Mouse double click on calendar>: Same as \<SHIFT + ENTER>

\<ALT + c>: Expand / hide calendar

\<Select day with mouse in calendar> : Take the selected day into the entries

\<Select day with mouse> THEN <SHIFT + Select day with mouse> :
Take earlier day as start, later day as due date and mark the days in the calendars

\<SHIFT + Select day with mouse double click > : Take earlier day as start,
later day as due date and mark the days in the calendars AND insert both dates

\<CURSOR UP / DOWN>: Increase / Decrease Day/Month/Year/Today+, depending on the cursor focus
\<CURSOR LEFT / RIGHT> Switch between Day/Month/Year/Today+
\<POS 1> : Show today
\<Picture Up / Down > Increase / Decrease Month

**Some logic behind:**

If a date already exists, the date and its format is respected. Otherwise the selected
date format from the preferences is used for new dates (Inherit date)

If the start date and the due date do not match, they will be highlighted in red.

Within the dialog, if the start date is later than the due date or vice versa, the
date title will turn red.

The time between the start and the due date is marked within the calendar.

If a date is changed, then switched to the other date and is also changed
or just ENTER is pressed, both dates are inserted into the page after ENTER key

If < or > is used to activate, then TAB is pressed and then ENTER, both dates
are inserted into the page

If a date is changed by entering the number into a field, the ENTER key needs
to be pressed to accept that number. To insert that date into the page, the ENTER
key needs to be pressed again.

Options (see preferences):
 - Select the preferred date format
 - Choose to inherit the date format if a date exists
 - Add x number of days to a start or due date
 - Show calendar expanded
 - Re-order the dates to start date then due date and group them (see options).

**Comment by jaap-karssenberg** [comment]
@muguu - what is the intended "action" for this issue ticket?

**Comment by muguu** [comment]
@jaap-karssenberg - You might want to label it as enhancement and include it into Release 0.68

**Comment by jaap-karssenberg** [comment]
To have it considered for inclusion as a core plugin this code would need to be ported to python3 / Gtk3 version of zim. Also would need test case coverage (at >2000 lines this is a lot of code to import untested!) and a manual page.

**Comment by jaap-karssenberg** [comment]
Closing this issue as the code is not ported to Gtk3 / Python3. If an update is available somewhere, please file it as a pull request.
