### ISSUE TITLE
List auto formatting resets heading formatting

### ISSUE THREAD

**Issue by nelas** [zim-desktop-wiki/zim-desktop-wiki#1457]
Hi, the list auto formatting is removing the heading formatting in Zim 0.73.5. See the video below:

https://user-images.githubusercontent.com/361179/116893111-e24c7000-ac30-11eb-9ade-925d46967cf2.mp4

Cheers,
Bruno

**Comment by sojusnik** [comment]
Confirming! Happens with Zim 0.73.5 on Ubuntu 20.10.

**Comment by sojusnik** [comment]
@nelas Fix is released, close this issue?

**Comment by nelas** [comment]
Great! Works for me now. According to the [guidelines](https://github.com/zim-desktop-wiki/zim-desktop-wiki/wiki/Issues), the issue should get the `Fix available` tag and remain open until the fix is available in the main branch.

**Comment by sojusnik** [comment]
Thanks for pointing out!

**Comment by nelas** [comment]
Hey, although the original issue is fixed, I noticed that the problem also occurs when duplicating a list item (ctrl+shift+d):

https://user-images.githubusercontent.com/361179/133080124-0a422658-517d-49ff-b806-7e4201328595.mp4
