### ISSUE TITLE
Make front- and backarrow more distinguishable by having different colors

### ISSUE THREAD

**Issue by sojusnik** [zim-desktop-wiki/zim-desktop-wiki#1459]
The newly implemented [backarrow](https://github.com/zim-desktop-wiki/zim-desktop-wiki/pull/1332) has the same color, read yellow, as the frontarrow, making them hard to distinguish from each other at first glance. This could be easily solved by changing the color of one of the arrows. So the frontarrow could stay yellow, while the new backarrow could have a darker color, f.i. orange.

I'm lacking coding skills, but would appreciate if somebody could tweak the color of the backarrow, maybe @RonnyPfannschmidt?

**Comment by RonnyPfannschmidt** [comment]
@sojusnik im happy to do so, got a specific color suggestion? else ill just darken it (i just flipped the pixmap for the front arrow as a starting point)

**Comment by jaap-karssenberg** [comment]
Also had this on my todo list. I found the yellow doesn't give good
contrast anyway, so maybe go with two shades of blue for the arrows ?

I highly recommend choosing colors from the "Tango color palette" - see Tango
Desktop Project - Wikipedia
<https://en.wikipedia.org/wiki/Tango_Desktop_Project> for a table.

Thanks,

Jaap

**Comment by sojusnik** [comment]
> I found the yellow doesn't give good contrast anyway, so maybe go with two shades of blue for the arrows?

I have two concerns in this regard, namely that the color blue could visually interfere with the default blue of a linked text and that two shades of blue would not differentiate themselves sufficiently, as I suspect, without having a visual example. If we don't have any restrictions on the color, then why not use f.i. orange (frontarrow) and plum (backarrow) from the Tango palette? I think that they are the best contrast-wise.

![image](https://user-images.githubusercontent.com/1245718/117134317-b8688a00-ada5-11eb-92d9-cfedcea960c4.png)

**Comment by jaap-karssenberg** [comment]
Sure - let's just give it a try

**Comment by RonnyPfannschmidt** [comment]
its on my todo now, i'll give it a spin tommorow as im a bit stretched - thanks for the input !

**Comment by RonnyPfannschmidt** [comment]
short update , i underestimated my stretch,  but im relatively confident i get the necessary time this week

**Comment by sojusnik** [comment]
Thanks for keeping us up-to-date!

**Comment by sojusnik** [comment]
> short update , i underestimated my stretch, but im relatively confident i get the necessary time this week

Hope you are well! Just a friendly reminder that it would be awesome, if you could have a look on this issue in the near feature.

**Comment by RonnyPfannschmidt** [comment]
thanks for the ping, i just started digging in, i toon note that multiple shares are used, im investigating doing it nicely

**Comment by RonnyPfannschmidt** [comment]
@sojusnik first iteration is done ^^

**Comment by sojusnik** [comment]
Checked the new checkboxes in [GitHub's preview](https://github.com/zim-desktop-wiki/zim-desktop-wiki/pull/1332/commits/fe0caa0780d05c91f788f7d8579ba95525f8fe72?short_path=6326a8a#diff-6326a8ad6302146c52f62cb2bdcce1310a0205e98c3e4a66e451c5c1a1eb584b) and spotted two small things:

1. The inner area of the checkbox is transparent in the new checkboxes, while it is gray in the old one.
2. The new arrows are not completely coloured, because only the lower part of the horizontal line of the arrow is in color, while the other part is transparent.

Is this really the case or due to some quirks in GitHub?

**Comment by RonnyPfannschmidt** [comment]
i used transparency in the arrows/checkboxes to enable the color scheme of the user to shine through, i can use full color as well

**Comment by sojusnik** [comment]
I can't judge which looks better, coloured or transparent checkboxes/arrows, because I'm waiting for the merge and the release, but then all checkboxes should be unified, either as coloured or transparent. So if we decide to use transparent checkboxes/arrows, then the remaining checkboxes, like done, undone, not done, should also be redesigned.

**Comment by RonnyPfannschmidt** [comment]
true, i forgot about that detail

i'll reiterate in the evening, thanks for elaborating

**Comment by RonnyPfannschmidt** [comment]
finally gotten around filling it, i think i need to lighten the bruising a bit up to make it finally fit

**Comment by sojusnik** [comment]
While enjoying using the backarrow, I find that the backarrow in "plum" doesn't stand out enough in front of the grey checkbox. Did you take the "plum" from the second or the third column, mentioned [here](https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/1459#issuecomment-832617779)? If it's taken from the second, maybe let's try the one from the third?

Additionally, the horizontal white stripe on the front- and backarrow makes the arrows thinner than they already are. So what about removing this white stripe altogether?

That's how these arrows are rendered currently:
![grafik](https://user-images.githubusercontent.com/1245718/129475653-008b242a-cc42-4e40-8526-09784808e28d.png)
![grafik](https://user-images.githubusercontent.com/1245718/129475642-aa3d3103-4bae-47e6-86b3-ffa1f6233b2b.png)

BTW, the front- and backarrow aren't displayed, when a page is exported as "print to browser". Is this already on someone's radar?
