### ISSUE TITLE
Zim does not seem to respect "shared=False" setting (causing a security vulnerability)

### ISSUE THREAD

**Issue by TeroK** [zim-desktop-wiki/zim-desktop-wiki#1460]
Hi!

According to the docs (https://zim-wiki.org/manual/Help/Config_Files.html) setting shared=False in .zim file should prevent it caching stuff to home directory, but placing it in .zim folder under the notebook.

However this does not appear to have effect at least on 0.73.5 Win64 build. If that's true, it's a significant security vulnerability.

BR Tero

PS thanks for the great app! Rivals (joplin, zettlr, obsidian) are still behind, I evaluated them all.

**Comment by TeroK** [comment]
Sounds like recent commit on master does hopefully fix this. Not sure so I'll keep the issue open for devs to confirm.

**Comment by jaap-karssenberg** [comment]
Yes, I believe the recent patch fixes that issue, but probably I need to
add a test case as well to ensure it stays fixed.

Plan to release next version in ~ one month, unfortunately no fast track to
get this out earlier.

-- Jaap

**Comment by jaap-karssenberg** [comment]
Test case added in commit ba80a8
