### ISSUE TITLE
Mobile Android App for zim

### ISSUE THREAD

**Issue by javadevelopment4** [zim-desktop-wiki/zim-desktop-wiki#1461]
Hi,

Is there is any mobile app for Zim wiki?
How to use Zim wiki in mobile?

Thanks

**Comment by sojusnik** [comment]
At the moment there is no dedicated Zim app for Android, but you can use Markor ([Google Play](https://play.google.com/store/apps/details?id=net.gsantner.markor) & [Homepage](https://gsantner.net/project/markor.html)) in the meantime. Markor is able to properly display the Zim Wiki format, if you choose it in the file options.

**Comment by Simplenuity** [comment]
+1 for the recommendation of @sojusnik 

[(tip for Android users: Markor - Markdown Editor)](https://answers.launchpad.net/zim/+question/695809)

**Comment by Self-Perfection** [comment]
Whoa! This is a life-saver!
I'd like to add that markor turns out to be not just an Android with basic Zim Wiki format support, but also free / open source app and [available at F-Droid](https://f-droid.org/repository/browse/?fdid=net.gsantner.markor). This quite important for me.
