### ISSUE TITLE
Spam in Zim Wiki

### ISSUE THREAD

**Issue by Temmon** [zim-desktop-wiki/zim-desktop-wiki#1466]
Submitting here because the github Zim wiki doesn't have an issues area. Someone is making spam articles in the wiki documentation. I deleted most of them, but I left one up on purpose so you can see it and there's a chance I missed one or two. I think I deleted 15 or so. They were all made by the same user, and the time stamp was consistent at 7 days before 5/16/21. Letting you know in case there are security measures so you can vet wiki contributors, block that guy, or at least so you know it happened. 

[Remaining spam article](https://github.com/jaap-karssenberg/zim-wiki/wiki/Would-you-feel-like-working-if-your-organization-does-not-give-you-salary-on-time%3F)

**Comment by sojusnik** [comment]
Reported this user several days ago. He created 19 sites, of which you already deleted 17. Additional to the [remaining](https://github.com/jaap-karssenberg/zim-wiki/wiki/Would-you-feel-like-working-if-your-organization-does-not-give-you-salary-on-time%3F) spam article [this](https://github.com/jaap-karssenberg/zim-wiki/wiki/uPVC-windows-adds-less-value-to-your-home) one is left. I'm OK with it, if we delete both remaining spam articles.

**Comment by Temmon** [comment]
I'll delete them and close this issue. My goal was informing primary maintainers and that's been accomplished.

**Comment by jaap-karssenberg** [comment]
Thanks for taking care !
