### ISSUE TITLE
Empty points in lists are deleted on reload

### ISSUE THREAD

**Issue by seihtam** [zim-desktop-wiki/zim-desktop-wiki#1468]
Empty points on bullet lists, numbered lists and checkbox lists are deleted on reload.
Example:
- A
- 
- B

Will after reloading the page turn into:

- A
- B

Tested on Zim 0.73.5.

**Comment by Nick222** [comment]
Confirm

Xubuntu 21.04
Zim 0.73.5

**Comment by fdt-dev** [comment]
I'd ask the question whether that's actually really a bug. I mean, what would be the meaning of an empty bullet point anyway? I always found it to be good that Zim autoremoves these empty bullet points. Or at least there's an easy workaround.
(This behaviour has been in Zim ever since I have started using it ... that must have been 0.58)

**Comment by seihtam** [comment]
The case where I found it a problem is when I added empty indented bullet points to mark that I needed to fill in some information, then switching page to read up on something else before filling in the information.
I've been using Zim for a long time and haven't noticed until now. So maybe this behaviour is fine and actually intended. And it's not a problem for me now that I know this is the way it works. I'll let Jaap decide.

**Comment by vossenjp** [comment]
On 5/21/21 2:35 AM, fdt-dev wrote:
> I'd ask the question whether that's actually really a bug. I mean, what would be the meaning of an empty bullet point anyway? I always found it to be good that Zim autoremoves these empty bullet points. Or at least there's an easy workaround.
> (This behaviour has been in Zim ever since I have started using it ... that must have been 0.58)

+1 for this.  This is a *feature* not a bug!

Likewise the fact that it cleans up bogus bullets or check-boxes in headers.  That allows me to switch large blocks of text that include various empty lines and headers from bullet to check-box, which I do several times a week as part of a con call notes work-flow.

Later,
JP
--  -------------------------------------------------------------------
JP Vossen, CISSP | http://www.jpsdomain.org/ | http://bashcookbook.com/
