### ISSUE TITLE
emojis don't appear on MacOS

### ISSUE THREAD

**Issue by aparrish** [zim-desktop-wiki/zim-desktop-wiki#1470]
Typing emojis into a page inserts an emoji-width empty space. I can verify that the emojis are actually in the file by `cat`ing the file on the command line (or opening it with another program). I've tried the [workaround on the wiki](https://github.com/jaap-karssenberg/zim-wiki/wiki/Fallback-Font-and-Larger-Checkbox) (i.e., explicitly listing a fallback font with emojis in `style.conf`), but with no success.

This is with Zim 0.73.4 (installed via homebrew) on MacOS 10.14.6 (Mojave). I assume the problem has to do with some miscommunication between GTK and fontconfig and Homebrew, but I'm not really sure how to start unraveling all of that!

**Comment by fancsali** [comment]
I can see the same issue...

**Comment by introt** [comment]
Please try the new MacOS installer/package and open a new issue if the problem persists
