### ISSUE TITLE
New page (txt file) not always indexed/recognized

### ISSUE THREAD

**Issue by TeroK** [zim-desktop-wiki/zim-desktop-wiki#1481]
It seems that sometimes Zim fails to notice that a new page (txt file) gets added to the wiki. Typically happens when I host the wiki in git, and add new page on another computer, and then pull changes to other machine.

The new file/page simply does not get listed to the Index tree. Tools->Update Index does not solve it, or restarting the app.

The only workaround I've figured is to delete Zim cache database (index.db). 

Idea of better workaround: perhaps Update Index should also re-scan for new files?

(extra info: zim is always running when I pull the changes from git. and the version is 0.73.5).

**Comment by TeroK** [comment]
By quick test, it seems to be repeatable for me even if Zim is not running: just duplicate any .txt file to different file name. The new file doesn't get added to Index.

**Comment by jaap-karssenberg** [comment]
What operating system / file system are you using ?

For information: the indexer checks the modified date of the folder to
determine whether it should scan for new files. Could there be any reason
why mtime is not updated in your use case ?

-- Jaap

**Comment by TeroK** [comment]
This happens at least on Windows 10 and disk volume is exFAT filesystem on Veracrypt (encrypted filesystem container). Perhaps that combo triggers the issue.

I'll keep eye if this happens on other OS'es as well (I'm using also zim on mac and linux).

**Comment by jaap-karssenberg** [comment]
Let me know if you see similar issues on "vanilla" filesystems.

Thinking whether we should have a "don't trust the mtime" option for the
indexer. However that would cause a lot of additional indexing actions for
folders that have not changed. Also an option that is to "cryptic" to put
in the user interface, so will only help few expert users.

Alternative would be to have a tool that forces update of a single folder
regardless of mtime - e.g. for the current page. Need to think how / where
this option would fit in the UI.

Maybe the "update index" should be replaced with a "force index update"
which then prompts a dialog to choose between full notebook, or only
current page.

Let me know if you have suggestions how to put this in in such a way you
would have found it when you first ran into this problem.

-- Jaap
