### ISSUE TITLE
Windows: Missing Icon in Font Chooser Dialog

### ISSUE THREAD

**Issue by StefRe** [zim-desktop-wiki/zim-desktop-wiki#1482]
The [Windows binaries installer](https://zim-wiki.org/downloads/zim-desktop-wiki-0.73.5-setup-w64_x86.exe) fails to install the `list-remove` icons needed for the font chooser dialog:
![grafik](https://user-images.githubusercontent.com/19879328/120810878-b718b180-c54b-11eb-89a9-11b7ceefedf2.png)

The icon should be included in [zim.spec](https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/master/windows/src/zim.spec).

As a workaround for the time being, you can get them from your `mingw-w64-x86_64-gtk3` installation (`\msys64\mingw64\share\icons\Adwaita\...\legacy`) or, if you don't have gtk3 installed, you can download the current Adwaita icon theme from [gnome](https://download.gnome.org/sources/adwaita-icon-theme/40/).  

The missing `list-remove` icons need to be copied to the `...\zim\share\icons\Adwaita\...\legacy` folders of your zim installation.

**Comment by roland-ruedenauer** [comment]
Could you also please add 'process-working-symbolic' to the list. The spinner icon is missing in the search dialog (located directly behind the search text input control).

**Comment by StefRe** [comment]
@roland-ruedenauer : Hm, couldn't find the search dialog you're referring to. Obviously not this one:
![grafik](https://user-images.githubusercontent.com/19879328/120937019-520bba00-c70b-11eb-8195-15a649129dad.png)

Can you describe how to open the dialog you're talking about or send a screenshot?

PS: While looking through all the dialogs I found another missing icon for "create new folder", will add it tomorrow.

**Comment by roland-ruedenauer** [comment]
Ah ... it's the full-text search in the top right corner of your screenshot.
Entering text and pressing enter will show up this dialog:

![image](https://user-images.githubusercontent.com/3630067/120939772-e54bec00-c719-11eb-8bfd-0892c3dcd363.png)

(this screenshot here is from my Manjaro system)

**Comment by StefRe** [comment]
@roland-ruedenauer : Ah, I see (when searching a relatively small notebook the spinner only shows so briefly that I overlooked it). It's `\msys64\mingw64\share\icons\Adwaita\scalable-up-to-32\status\process-working-symbolic.svg` and it should go into `\zim\share\icons\Adwaita\scalable-up-to-32\status\process-working-symbolic.svg`. Thanks for pointing it out.

**Comment by StefRe** [comment]
Further missing icons in file chooser dialog: `folder-new` and `drive-harddisk`. There are some mime types missing too, but I don't think that they're so important.
![grafik](https://user-images.githubusercontent.com/19879328/120986031-76ec4580-c77c-11eb-92cf-6b8b8485dc07.png)
