### ISSUE TITLE
Reload pages opened in new window

### ISSUE THREAD

**Issue by zauberparacelsus** [zim-desktop-wiki/zim-desktop-wiki#1484]
When you right-click a page and select `Open in New Window`, that page cannot be reloaded with the CTRL-R shortcut.  It has to be manually closed and then reopened to get it to reload.

I'd like to have the ability to reload with the CTRL-R shortcut, and maybe also add Reload as an option in the window's right-click menu.

**Comment by jaap-karssenberg** [comment]
More generic the page window needs a menu and keybinding with all
applicable actions.

Op vr 4 jun. 2021 16:54 schreef Zauberin Paracelsus <
***@***.***>:

**Comment by introt** [comment]
Fixed in later versions
