### ISSUE TITLE
SyntaxWarning on upgrade to 0.73.5-SNAPSHOT-t202106031854

### ISSUE THREAD

**Issue by rolfkleef** [zim-desktop-wiki/zim-desktop-wiki#1487]
I just saw a SyntaxWarning when upgrading on Ubuntu 21.04:

    Unpacking zim (0.73.5-SNAPSHOT-t202106031854~ubuntu20.10.1) over (0.73.5-SNAPSHOT-t202105070819~ubuntu20.10.1) ...

    Setting up zim (0.73.5-SNAPSHOT-t202106031854~ubuntu20.10.1) ...
    /usr/lib/python3/dist-packages/zim/gui/pageview/__init__.py:7887: SyntaxWarning: "is" with a literal. Did you mean "=="?
      if self._image_data['width'] is 1:`

looking at that file, it seems to be in

    def do_file_changed(self):
        # Prevent images becoming one pixel wide
        if self._image_data['width'] is 1:
            self.reset_dimensions()

**Comment by introt** [comment]
Yeah that one's on me. Thanks for thorough reporting, I've submitted a fix.

**Comment by rolfkleef** [comment]
I'll close the issue then :-)
