### ISSUE TITLE
Unable to recover from not responding

### ISSUE THREAD

**Issue by itsnotsaved** [zim-desktop-wiki/zim-desktop-wiki#1489]
I was using zim with multiple notebooks for a while with making many changes. Meanwhile i needed to attach a file so i tap the "attach" button then zim seems happening not responding

I already wait around 1hr (no device slow) but i cannot recover zim from not responding. I can't quite it because i worry then my recent works will lose.

![image](https://user-images.githubusercontent.com/73447325/120984251-af077e80-c7a4-11eb-92cc-1c2d9ed68319.png)

1. At such time, is there way to recover from not responding manually?
2. Can you add feature to with configurable time interval option as onenote to auto save changes? eg: every 1min, 5min etc. currently i dont see such option and often save manually

Zim 0.73.5-t202105070815~ubuntu20.04.1 | ubuntu 20.04.02

**Comment by itsnotsaved** [comment]
#405

**Comment by jaap-karssenberg** [comment]
Zim actually does autosave - it is default a few minutes and it also saves
when focus switches away from the editor. So it should be quite save to
kill the process if it hangs up.

There is an option to change the interval but it is hidden in the config
file - please see the manual.

-- Jaap

**Comment by itsnotsaved** [comment]
Thanks. Found it https://zim-wiki.org/manual/Help/Config_Files.html

![image](https://user-images.githubusercontent.com/73447325/121310809-f5d4b000-c92d-11eb-9d4b-69c59813fbd4.png)

In the UI --> File then there's two options; save version and save but i'm looking for normal save. I'm not sure if that config is correct for it

**Comment by itsnotsaved** [comment]
// or `autosave_timeout=15`; is it the particular config for save interval?

**Comment by jaap-karssenberg** [comment]
I think the group name "VersionControlPlugin" should be a give away ;)

Check the option "autosave_timeout" below "GtkInterface" group

**Comment by itsnotsaved** [comment]
Thank you 😊
May be it's good to bring that save interval option to UI same as onenote (some're may especially looking for it)
