### ISSUE TITLE
New Feature Request: Way to set link text with autoformat

### ISSUE THREAD

**Issue by DustanBower** [zim-desktop-wiki/zim-desktop-wiki#1491]
I use zim to organize a lot of nested hierarchies for a tabletop game I run.  The reason I use zim is so I can link everything together and make it easier to find related things.  As such I make a lot of links while typing, but I essentially never want the full link path visible in any situation.  For example, I can type `:Space:Outer_Rim:Dathomir` to link to Dathomir quickly, but I only want "Dathomir" visible, so I'd have to edit the link in the UI anyway.  As a result I have to make each link in the UI, which I'd rather not do.  Occasionally I assign other text rather than just using the target page's name without the path, but that's the general pattern.

It'd be really handy if there was a syntax for setting the visible text on links through autoformatting.  I don't really have any particular views on what that syntax would be, but I've tried to use "|" in the past multiple times since a lot of wikis use that.  If that worked I could just type `:Space:Outer_Rim:Dathomir|Dathomir` and go on with my business without having to repeatedly open the popup.  As I use zim mainly for the purpose of linking to other things, I frequently have a lot of page links.

**Comment by jaap-karssenberg** [comment]
There is an option for "short links". Not sure if already released or in
dev branch.

Op ma 7 jun. 2021 20:37 schreef DustanBower ***@***.***>:

**Comment by DustanBower** [comment]
I see short_relative_links on the dev branch but I'm having trouble determining what it actually does.  I'm not able to observe a difference in behavior whether it's selected or not, whether I'm copying text or locations via copy location.

As best I can tell it only affects pasting, which wouldn't affect my use-case.  It also seems to only affect relative links, which I tend to avoid.

**Comment by jaap-karssenberg** [comment]
You're right. What I could do is also let the "insert link" dialog use the
same property, e.g. you type "^L" to open the dialog "Some:Page" and the
text field gets filled in with only "Page" by default. Would that work ?

-- Jaap

**Comment by DustanBower** [comment]
That would save me an _immense_ amount of time, yes.  Provided it also worked for absolute links.  I have a lot of trouble with relative links and I try to avoid them by default.  For example if I have an ":Individuals"  and then I'm editing the ":Space:Outer Rim:Dathomir" page above, sometimes when I add a reference to Individuals:Whoever it'll add it as ":Space:Outer Rim:Dathomir:Individuals:Whoever" instead of the intended ":Individuals:Whoever".  That'd be a mere annoyance if I noticed right away, but I usually only notice once this has happened a bunch of time and have to go and untangle it all.  I'm just using this syntax to mark how it appears in the tree, by the way.

So while I do use relative links, I use absolute links pretty aggressively as well and the links I add most often are intended to be in other trees.
