### ISSUE TITLE
Auto collapse rest of directories when move between more than two or three pages

### ISSUE THREAD

**Issue by itsnotsaved** [zim-desktop-wiki/zim-desktop-wiki#1492]
If user have lot of pages with subpages eg: 20-25 folders; if most are expanded then it's quite annoying to move between them. so i suggest when move between different directories (folders) then auto collapse rest of directories except recent worked two or three folders. Provide it has optional feature to enable/disable.

Furthermore, it's better if zim remember about those collapse directories expanded position then when expand manually, it expand to previous state

**Comment by jaap-karssenberg** [comment]
There is an option for this in the page index plugin.

Op di 8 jun. 2021 08:21 schreef Not ***@***.***>:

**Comment by itsnotsaved** [comment]
>If user have lot of pages with subpages eg: 20-25 folders; if most are expanded then it's quite annoying to move between them. so i suggest when move between different directories (folders) then auto collapse rest of directories except recent worked two or three folders.

Page index plugin already enabled by default or myself without knowing but it seems not doing above mentioned task. Any other main directories or subpage directories don't get collapsed automatically when i work on other main directory(folder)

It says (GUI) " [ok] Automatically collapse sections on close page"
I'm not sure if that saying about above mentioned thing

![image](https://user-images.githubusercontent.com/73447325/121312987-2584b780-c930-11eb-9360-d07b670ba52b.png)

**Comment by jaap-karssenberg** [comment]
It does what it says: if folders where expanded automatically, they are
also closed automatically. If you open them explicit (by clicking the small
arrow or "+" in the tree) they stay open.

As described here: Zim - a desktop wiki (zim-wiki.org)
<https://zim-wiki.org/manual/Plugins/PageIndex.html>

-- Jaap

**Comment by itsnotsaved** [comment]
Now i got it and how to get benefit from that plugin feature.
Thank you
