### ISSUE TITLE
make all signs available for naming pages in the tree-page-view on the left

### ISSUE THREAD

**Issue by brainbow1** [zim-desktop-wiki/zim-desktop-wiki#1495]
In the left page area I am organizing my pages via Pages and Subpages of course.
Also with
A)
B)
C)
....
I am able to impact the order of the pages in this tree-view.
But any signs like the following:
~ # - / | < > -> <- >> * ( ) 
are just not visible / possible to type as a page name as they are not shown on the left side in the tree view and seems buggy or just not able to handle these symbols within that tree-view.

I really do like the alphabetical order, but would highly appreciate if theres a way to make the signs mentioned above to work.. 
Is there any possibility to fix / implement that?
Maybe an extension?

all the best and thank u so much for that amazing tool!

**Comment by jaap-karssenberg** [comment]
By design page names are only allowed to start with a alpha numeric
character, no other symbols.

Op za 12 jun. 2021 18:01 schreef brainbow1 ***@***.***>:

**Comment by brainbow1** [comment]
okay, that means, that is a limitation of the software which is determined by its structure and design, and there is no way to add the functionality/ability for using other symbols. is that correct?

**Comment by jaap-karssenberg** [comment]
Correct, cannot make page names start with other characters. Key reason is
that it makes parsing wiki syntax very hard and especially compatibility
with multiple source formats because in wiki syntax many characters have a
special meaning.

Op ma 14 jun. 2021 18:50 schreef brainbow1 ***@***.***>:
