### ISSUE TITLE
xdot - dependency is not working

### ISSUE THREAD

**Issue by brainbow1** [zim-desktop-wiki/zim-desktop-wiki#1496]
I installed zim wiki in debian bullseye, via the debian repositories.
Before that I installed **xdot** and **graphviz** from the debian repositories.

When I go to settings > add ons / extensions > link structure add on
it shows me:
graphviz - OK (green)
xdot - missing / not fulfilled (red)

sorry for my bad english... im using the german version of zim.

Hope for any help.

best regards!

**Comment by jaap-karssenberg** [comment]
The plugin tries to import xdot as a python library. Please check you have
the python3 version installed.

You can test it from the commandline with "python3 -m xdot" which may
return an error but should at least find the module.

-- Jaap

**Comment by brainbow1** [comment]
thank u for the answer!
I checked that terminal command:

`~$ python3 -m xdot
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/usr/lib/python3/dist-packages/xdot/__init__.py", line 26, in <module>
    from . import ui
  File "/usr/lib/python3/dist-packages/xdot/ui/__init__.py", line 3, in <module>
    from .window import DotWidget, DotWindow
  File "/usr/lib/python3/dist-packages/xdot/ui/window.py", line 40, in <module>
    from . import actions
  File "/usr/lib/python3/dist-packages/xdot/ui/actions.py", line 21, in <module>
    from xdot.ui.elements import Jump
  File "/usr/lib/python3/dist-packages/xdot/ui/elements.py", line 29, in <module>
    import numpy
ModuleNotFoundError: No module named 'numpy'
`

**Comment by jaap-karssenberg** [comment]
Looks like an unsatisfied dependency on the "numpy" package - might be
worth reporting towards the debian packager for xdot.

**Comment by brainbow1** [comment]
alright will do that, thank u for the information!!

**Comment by stefanor** [comment]
Thanks for the email :)

I missed the addition of numpy in 1.2 (which was silly, it's the first line of the diff).

It would be nice to have dependencies documented in the setuptools metadata, to avoid these kind of mistakes.

**Comment by brainbow1** [comment]
now I got the update with numpy and xdot via respositories of debian 11! thank u so much for ur effort! all the best!
