### ISSUE TITLE
Spell checking slows down page load & render

### ISSUE THREAD

**Issue by vossenjp** [zim-desktop-wiki/zim-desktop-wiki#1497]
For the record I'm running Zim from PPA on Linux Mint-19 and 20, e.g., 0.73.5-t202106081846~ubuntu18.04.1.

My $WORK PC is old and slow and I run Zim in a VM on it.  The VM has only 2 slow CPUs, and switching between 2 common and long pages ("work" is ~3,000 lines, calls ~2,600) takes 5-10 seconds or more, very frustrating.  I also And I experience seconds of delay when clicking on a ToC heading to jump to that section.  But when I turn off spell checking, both operations are much faster, almost instant.  My spelling and typing are horrible though, so spell checking is required. :-)

Is it possible to add an option (default = 0) to delay spell checking until some time after the page is rendered and/or the page location changes due to header click?

Related, an option to only spell check when Zim is "idle" might be nice.

I know that is a my problem due to my old and slow hardware, but I doubt I'm the only person stuck with crap hardware.

**Comment by jaap-karssenberg** [comment]
Spell checking is implemented in an external library. So would require
patching the library rather than Zim itself.

Op za 12 jun. 2021 19:37 schreef JP Vossen ***@***.***>:

**Comment by vossenjp** [comment]
OK, I see that.  But in Zim you can also do Edit > Prefs > Plugins > Spell Checker: on|off.  What about turning that _off_ during page transition and header navigation, then back _on_ after `delay`?

**Comment by vossenjp** [comment]
**tl;dr:** If Zim is very slow or if the spell checker is misbehaving, try removing `gtkspellcheck` and using `gtkspell` instead.  For Ubuntu, Mint, etc.:

* `sudo apt purge python3-enchant python3-gtkspellcheck`
* `sudo apt install gir1.2-gtkspell3-3.0 libgtkspell3-3-0`
* `sudo add-apt-repository ppa:jaap.karssenberg/zim && sudo apt update  && sudo apt install zim`

## Details:

I've had various problems with the spell checker (which I require :), e.g. #2167, #1497, and maybe #1596, which I believe all started with the move to Python3.  I've the same problems on multiple machines, running Mint-19.x, 20.x and 21.0, with various resources.  In particular, they persisted when I built a brand new 16 core Ryzen 7 which should not present any performance problems.  Related to performance, note I do keep Zim wiki files on a remote SSH FileSystem mount, but it's a local 1G LAN.

I had the "ah ha" moment when I build a brand new Mint-21.0 VM for work, installed Zim from PPA, and it Just Worked Great, with none of the problems.  When I looked into it, I saw "Edit > Preferences > Plugins > Spell Checker: gtkspell - OK (gtkspellcheck - Failed)".  Meanwhile, all the bad ones had "gtkspellcheck - OK" I assume for some historical reason or other.  When I switched a bad one from `gtkspellcheck` to `gtkspell` all the problems went away!

I did not specifically install either `gtkspellcheck` or `gtkspell` on this new VM, so I assume that `gtkspell` is (now?) the default somewhere.  So I am thinking that the move to Python3 somehow broke `gtkspellcheck` in a Zim context?  And maybe since `gtkspell` seems to be the default now, that's why most folks don't have this problem?
