### ISSUE TITLE
Suggestion for Change of Structure

### ISSUE THREAD

**Issue by Commandante-che** [zim-desktop-wiki/zim-desktop-wiki#1500]
I've only been using Zim for a month or so.  I think it's great.  Many thanks to the team.  It feels to me that the structure is not quite right.  I have  a number of Wikis, but there is no way of listing them.  I think I should be clicking on the Zim icon and seeing a list of my wikis then either choosing one or opening them all.  
At the moment, I have to open one of the Wikis then choose to open another wiki from within the one that's already open.  This doesn't mirror the structure which is Zim->Wikis->open rather than Zim->open-Wiki->open other wikis.
I hope you'll agree and change the structure as suggested.  I also hope this suggestion is useful.  
Thanks for your time

**Comment by jaap-karssenberg** [comment]
Have you checked out the "open notebook" dialog?  If you have multiple
notebooks defined and there is no default notebook zim will always start
with this dialog.

Op do 17 jun. 2021 17:27 schreef Commandante-che ***@***.***>:
