### ISSUE TITLE
[tasklist] deprecated tasklist options not actually hidden

### ISSUE THREAD

**Issue by mikem23** [zim-desktop-wiki/zim-desktop-wiki#1504]
[Running develop branch]

I was poking at the tasklist code and noticed this bit:

```
    hide_preferences = ('nonactionable_tags', 'tag_by_page', 'use_workweek')
        # These are deprecated, but I don't dare to remove them yet
        # so hide them in the configuration dialog instead
```

However, these preferences are not hidden in the UI. I think this is because they are handled as properties instead of preferences. Doesn't look like this field is honored for properties.

**Comment by jaap-karssenberg** [comment]
Issue addressed in development branch: nonactionable_tags is really hidden, tag_by_page and use_workweek are re-instated in some way
