### ISSUE TITLE
some characters get replaced with a red symbol (forbidden)

### ISSUE THREAD

**Issue by sala19** [zim-desktop-wiki/zim-desktop-wiki#1507]
when using some characters in the text like {{}} which later get corrupted. I hope that can be changed

**Comment by jaap-karssenberg** [comment]
This is because we store notes in wiki text and those symbols have a
special meaning in our wiki syntax. If you want them literally use the
"verbatim" style to protect them from wiki interpretation.

-- Jaap

**Comment by sala19** [comment]
thanks it works, maybe it would be nice later if there is an option to activate the verbatim mode permanent. I will close the issue at the moment.
