### ISSUE TITLE
Writing on mounted WEBDAV isdisfuncional

### ISSUE THREAD

**Issue by DarkDau** [zim-desktop-wiki/zim-desktop-wiki#1508]
I have 2 Debian bullseye installations here.
On one (T500) ZIM 0.73.5 works fine.
On the second system (Tuxedo) I have the following error.
I tried Zim 0.73.5 and with the developer and master version.
There I can create a new page, but it is not editable, just like all other files on the mounted webdav filesystem.
No hint in the debug log. How can I narrow down the error?
On T500 is **Wayland**, on Tuxedo is **Xorg**, but that should not be the cause, or will it?

**Comment by jaap-karssenberg** [comment]
What do you mean by not editable? How do you create the page without
editing ?

**Comment by DarkDau** [comment]
By creating a new file. it is created in example 
```
cat ~/MagentaCloud/Notizen/xyz.txt 
Content-Type: text/x-zim-wiki
Wiki-Format: zim 0.6
Creation-Date: 2021-06-23T10:22:48+02:00

====== xyz ======
Angelegt Mittwoch 23 Juni 2021

```
But this correctly created page is not editable by zim on Tuxedo. With nano or with zim on the first client t500 it is writable. Strange or?

**Comment by jaap-karssenberg** [comment]
Zim checks writing permission both on file and folder level - so might be
something goes wrong with permissions in WebDav ?

Specifically both the notebook folder and the ".zim" subfolder of the
notebook need to be writable (allow to create new files) else whole
notebook is assumed read-only.

Debug output should state something on read-only status.

**Comment by DarkDau** [comment]
File permission are correct an in the debug log is no notice to a access problem.

I am on the way to solve it.
I've created a testuser and open the notebook on webdav, this is working.
Seems a messed up config on my side.

**Comment by DarkDau** [comment]
solved.
The error disappeared when narrowing it down.
i think the group rights were on root and not on user.
Unfortunately, the edit switch iritated me, it was still on editable : wrong
So thank you. No error by zim, but by me :-)

**Comment by jaap-karssenberg** [comment]
Good point - probable there should be better UI feedback on read-only state
for cases like this
