### ISSUE TITLE
Open folder with menu key

### ISSUE THREAD

**Issue by DvP17** [zim-desktop-wiki/zim-desktop-wiki#1509]
There is a minor issue with opening links to folders on Windows.

When you click the link to a folder with using your mouse, the right location opens in a new window. Everything is perfect.

However, if you only use the keyboard and try to open the link it is only possible to "open folder" instead of "open" with the menu key. When you select "open folder" not the linked folder is opened but the main folder (folder above) the specific folder.

Thank you very much! Kind regards!

**Comment by introt** [comment]
Reproducing doesn't require the menu key nor Windows - the right-click menu has the same behavior.

The link behaves correctly when followed using alt + enter (or the mouse), so considering this to be a wontfix for now, but pull requests are open!
