### ISSUE TITLE
Temporary folder & file creation (Zim portable 0.73.5, Win10)

### ISSUE THREAD

**Issue by shulist** [zim-desktop-wiki/zim-desktop-wiki#1512]
this post was a result of problem I encountered in #1511 

Location: `...PortableApps\cache `
is there an issue with Zim creating many folders in the `cache` directory and not removing any of them? In a recent look into a problem I found Zim had created 12 folders (over the course of 6 months) here of which only three were actually needed. Why are all of these kept and should Zim delete them at some point?

Location: `C:\Users\[Username]\AppData\Local\Temp` 
It also seems to create numerous folders in here and leaves those without removing them later (in my recent look there were at least 46 folders created by Zim in this folder) . They each only contain a `zim.log` file. Is it not possible that this log file be written to the PortableApps `cache` folder and then be deleted upon close? Or keep the last five or something like that?

**Comment by jaap-karssenberg** [comment]
Typically the operating system takes care of purging temp and cache
folders, so not implemented in the application itself.

 But agree it might make sense to do so for the portable version because
the os does not know about it.

Op vr 25 jun. 2021 16:14 schreef shulist ***@***.***>:

**Comment by shulist** [comment]
@jaap-karssenberg said:
> Typically the operating system takes care of purging temp and cache folders,

However in both locations mentioned above Zim creates an increasing number of  folders and none are ever deleted. In my look at it according to Microsoft: 

> Windows never automatically cleans the %TEMP% directory by default.

in Win10 this is a setting but in other versions it is done manually by the user.

I do not see why the portable version actually uses the folder `C:\Users\[Username]\AppData\Local\Temp` as that seems to go against the principles of Portable Apps:

- A portable app is self-contained in a single directory with sub-directories and files within
- A portable app doesn't leave files or folders behind except those automatically generated by Windows

Why not create a `Log` folder within the Zim (install) folder and write all Log, DB and Conf files there and purge them when required?

**Comment by jaap-karssenberg** [comment]
Access to global %TEMP% has been fixed in the installer for portable installs - you can control it via the "environ.ini" file in the install folder
