### ISSUE TITLE
Get More Plugins Online - Crash

### ISSUE THREAD

**Issue by teamayu** [zim-desktop-wiki/zim-desktop-wiki#1513]
If you go to preferences and click this link, Zim crashes everytime.

Apart from that, beautiful software. Really fast. Perfect for what I need, thank you.

**Comment by jaap-karssenberg** [comment]
Works fine on my system. Can you provide an debug log or error messages ?

-- Jaap

**Comment by teamayu** [comment]
Hi Jaap,

The error log doesn't show much. This is the last few lines of note:

`WARNING: Invalid config value for toggle_panes: "['left_pane']" - Unknown pane names in: ['left_pane']
DEBUG: Accelmap: Q:\Portable-Software\Zim\config\zim\accelmap
DEBUG: Add window: MainWindow
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck found out-of-date
DEBUG: Index folder: Q:\Portable-Software\Zim\Notebooks\CLIENTS
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck finished
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck finished
DEBUG: Action: show_preferences
DEBUG: Loading description for plugin: arithmetic
DEBUG: Opening dialog "Preferences"`

After that it crashes. Windows 10, 64 Bit. If I download a clean copy and just go straight to Preferences and click "Get More Plugins Online" it just crashes.

**Comment by teamayu** [comment]
It's nothing to worry about really. I can just copy / paste the link into the browser.

Great software though. Love how fast it is. Really cool.
