### ISSUE TITLE
Code Block Plugin Cannot Be Disabled

### ISSUE THREAD

**Issue by teamayu** [zim-desktop-wiki/zim-desktop-wiki#1514]
Nothing major, but wanted to mention it. If you enable the 'Code Block' plugin, it cannot be disabled as it disappears from the plugins list.

**Comment by jaap-karssenberg** [comment]
Assume you mean the "source view" plugin. Cannot reproduce this issue,
please check debug log for errors.

Regards,

Jaap

Op wo 30 jun. 2021 04:52 schreef teamayu ***@***.***>:

**Comment by teamayu** [comment]
Ah, sorry Jaap, my mistake. Yes, 'Source View', not 'Code Block'. So, not a bug, sorry. You can delete this message.
