### ISSUE TITLE
Formatted text clears header format

### ISSUE THREAD

**Issue by sojusnik** [zim-desktop-wiki/zim-desktop-wiki#1518]
When pasting formatted text or formatting text (happens only with bullets, numbers and checkboxes) before a header, then the header loses its format, as shown in the following video:

https://user-images.githubusercontent.com/1245718/124015580-2071d000-d9e5-11eb-8fd2-00aa179f22d0.mp4

Observed under Zim v0.73.5 from the [Snapshots PPA](https://launchpad.net/~jaap.karssenberg/+archive/ubuntu/zim-snapshots) under Ubuntu 20.10.

**Comment by nelas** [comment]
Possibly related to #1457

**Comment by jaap-karssenberg** [comment]
Yes, consider this a duplicate of #1457

Op vr 2 jul. 2021 10:38 schreef Bruno C. Vellutini ***@***.***

**Comment by sojusnik** [comment]
Thanks, works flawlessly now!
