### ISSUE TITLE
Table formatting 

### ISSUE THREAD

**Issue by xade93** [zim-desktop-wiki/zim-desktop-wiki#1521]
![image](https://user-images.githubusercontent.com/24752033/124522414-c24e4e00-de25-11eb-9edf-467925153a88.png)
Table head shown as this after restart of zim.

**Comment by introt** [comment]
Maybe related: a table of mine got its empty cells filled with `<td />` on page reload. It had `[[links:to#anchors|with text]]` with `<` inside link texts, if that's in any way relevant.

**Comment by jaap-karssenberg** [comment]
Could you provide information on how to reproduce? Otherwise afraid this report will not help towards a solution.
