### ISSUE TITLE
Renaming a page breaks Undo

### ISSUE THREAD

**Issue by zauberparacelsus** [zim-desktop-wiki/zim-desktop-wiki#1522]
If you rename a page in zim, then the Undo function will cease to work, whether it is activated via CTRL-Z or from the Edit menu.  This applies to both past edits and to edits made after renaming the page.

If you reload the page, or open another page before reopening the page you just renamed, then undo will start working again.  So, those present some workarounds until a fix is implemented.

**Comment by jaap-karssenberg** [comment]
In no case will undo work for past edits after a rename. The undo stack is
no longer valid after reloading the page from a new file location. Would be
a great feature though.

At least in the development branch I cannot reproduce the issue where undo
also stops working for new edits.

Regards,

Jaap
