### ISSUE TITLE
Error with image path at exporting to md

### ISSUE THREAD

**Issue by aloboa** [zim-desktop-wiki/zim-desktop-wiki#1526]
I have found the following error at exporting one single zim page with an
attached image to md (zim v. 0.73.5):

The path of the original image in the zim page is:
/home/alobo/Dropbox/WikiMind/notes/Notebooks/ZimNotes/Home/Work/ImProc/Segmentation/MeanShift/MS-OTB_Tests/A_Practical_Guide_of_Mean-Shift_Segmentation_using_OTB/pasted_image.png

The image is copied during the export to:
./A_Practical_Guide_of_Mean-Shift_Segmentation_using_OTB_files/Home/Work/ImProc/Segmentation/MeanShift/MS-OTB_Tests/A_Practical_Guide_of_Mean-Shift_Segmentation_using_OTB/pasted_image.png

But the created md has the following, non-existing path, which seems a
mix of both:

./A_Practical_Guide_of_Mean-Shift_Segmentation_using_OTB_files/Home/Work/08ClasesySeminarios/MASTER_CREAF/2021/TFMs/LeonardoTorijano/pasted_image.png

**Comment by introt** [comment]
Please reopen using the new templates and cleaned up steps to reproduce, thanks!

**Comment by aloboa** [comment]
I confirm it works right with 0.74.3
