### ISSUE TITLE
Update PPAs for Ubuntu 21.04

### ISSUE THREAD

**Issue by sojusnik** [zim-desktop-wiki/zim-desktop-wiki#1530]
Would love to see if your PPAs would be updated to work with Ubuntu 21.04:

https://launchpad.net/~jaap.karssenberg/+archive/ubuntu/zim
https://launchpad.net/~jaap.karssenberg/+archive/ubuntu/zim-snapshots

**Comment by Nick222** [comment]
+100500

**Comment by sojusnik** [comment]
Thanks for updating the snapshots PPA!
