### ISSUE TITLE
Ability to add text anywhere on a page

### ISSUE THREAD

**Issue by itsnotsaved** [zim-desktop-wiki/zim-desktop-wiki#1533]
Currently zim only support to write as common text editor, writer etc means row by row but we also interest to add contents/notes anywhere on a page. In onenote, it the default way; when we click on anywhere on page then appear a textbox so we can write in it, add tasklist, image, resizable and able to move each textbox to different areas on page.

So i am asking to add this feature as optional while keep current way as default. maybe, you can add textbox button to toolbar then when necessary we can click on it next click on anywhere on page then it auto create textbox and we can type anything necessary.
When textbox button hasn't toggled then user able to write as now.

**Comment by introt** [comment]
That's out of scope for Zim, "a graphical text editor used to maintain a collection of wiki pages" where "[a]ll data is stored in plain text files with wiki formatting".

For software with functionality similar to what you've described, see for example [Xournal++](https://github.com/xournalpp/xournalpp).

**Comment by itsnotsaved** [comment]
> For software with functionality similar to what you've described, see for example [Xournal++](https://github.com/xournalpp/xournalpp).

There're no perfect alternative to onenote for linux except zim so far and i see its better if this additional features comes with zim although follows wiki formatting

**Comment by jaap-karssenberg** [comment]
Yes, this is out of scope for zim. However I would encourage you to think
through why you want to add text boxes on a canvas. What is the benefit for
a specific use case compared to "linear" text ?  Is there any other way to
achieve the same benefit with e.g. an embedded object, or a special plugin
pane on the side ?

-- Jaap

**Comment by itsnotsaved** [comment]
>What is the benefit for a specific use case compared to "linear" text ? 

Well, basically we expect professional level note taking solution eg: as suitable for business guys. They need to put temporally notes that erase later, new data immediately to organize them or perform a checkup later that related to main contents written in rows or extra things that need to memorize for specific task, project or needed to discuss things etc. It's really uncomfortable when has to write them as now, or whole page become unclear or taking more space then difficult to read entire thing etc

And you have mentioned in readme about "Zim can be used to"

1. Keep a daily or weekly journal
2. Take notes during meetings or lectures
3. Organize task lists
4. Do brainstorming

[1][2] for such users, sometimes they need to add or re-add additional or less important details, explanations belong to specific topics, subjects etc and put particular topic or tasks contents as a summery in small area to read and recognize easily
   
[2] zim doesn't going to work well for them. eg: if it a person that gather and categorize the core purposes, ideas, plans, requests, comments from everyone related to each idea etc in a meeting then zim become headache when has to write row by row. 

[4] ofcourse, for such users definitely need this; i don't need to explain

**Comment by vossenjp** [comment]
I do all of those things with Zim, no "text anywhere" feature needed.  Aside from UI issues, adding such a feature would  reduce the ability to make sense of the plain text files underneath Zim, at best, and those files are a major advantage to Zim.  My vote is no as well.

If you absolutely require such a feature, Zim isn't the right tool for you.
