### ISSUE TITLE
text strange disappearing

### ISSUE THREAD

**Issue by pityhero233** [zim-desktop-wiki/zim-desktop-wiki#1537]
when I type the following text and press enter, the line I just entered disappears.
e.g. (without double quotes) "A." "a." "123."

I am on Archlinux with zim-0.73.5-1.
attached screen recording.
https://user-images.githubusercontent.com/24752033/128593989-9406a7cc-2bf9-4a84-ad65-f9f7830a0198.mp4

**Comment by jaap-karssenberg** [comment]
Yes, this text is seen as a list item. Empty list items are removed when
reloading the page.

This is a know feature/issue.



Op za 7 aug. 2021 10:24 schreef Shi Zhengyu ***@***.***>:
