### ISSUE TITLE
Manually adding Plugin (Windows)

### ISSUE THREAD

**Issue by freyana** [zim-desktop-wiki/zim-desktop-wiki#1538]
Hi,

I have just installed zim-desktop-wiki-0.73.5-setup-w64_x86.exe on Windows 10, and have selected the **portable** installation.

Now, I am trying to install the following plugins: 
- Instant Search Plugin
- Tag Autocompletion Plugin (for Zim >= 0.70)

I put the Plugin .py Files into the folder Q:\Zim\data\zim\plugins (with Q:\Zim\Zim-Install being my installation directory). This is also the folder which gets opened if I click on "Open plugins folder" in Zim.

After restarting Zim, the Plugins still do not turn up in the Plugin configuration and there is also no new functionality. What am I doing wrong?

Thanks for your help.
Freyana

**Comment by jaap-karssenberg** [comment]
They should show up in the plugin list preferences dialog. But there could
be an error loading then. First open the preferences and then have a look
at the debug log to see if this is the case

Op za 7 aug. 2021 13:42 schreef freyana ***@***.***>:

**Comment by freyana** [comment]
Yes you are right, I can find the following log entries:
```
ERROR: Could not load plugin tagcomplete
Traceback (most recent call last):
  File "zim/gui/preferencesdialog.py", line 362, in __init__
  File "zim/plugins/__init__.py", line 420, in get_plugin_class
  File "zim/utils.py", line 35, in get_module
  File "Q:\Zim\data\zim\plugins\tagcomplete.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
```

```
ERROR: Could not load plugin instantsearch
Traceback (most recent call last):
  File "zim/gui/preferencesdialog.py", line 362, in __init__
  File "zim/plugins/__init__.py", line 420, in get_plugin_class
  File "zim/utils.py", line 35, in get_module
  File "Q:\Zim\data\zim\plugins\instantsearch.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
```

**Comment by jaap-karssenberg** [comment]
I think the file contents are not correct. Could it be that you
accidentally downloaded a  html page instead of the raw .py file?

Op za 7 aug. 2021 16:42 schreef freyana ***@***.***>:

**Comment by freyana** [comment]
You are right, somehow I messed up the files. Now I could activate the Plugins. Sorry for the confusion and thank you very much for the fast help :-)
