### ISSUE TITLE
Convert bullet to checkbox and vice versa while typing

### ISSUE THREAD

**Issue by jaap-karssenberg** [zim-desktop-wiki/zim-desktop-wiki#154]
When I type "[ ]" at the start of a bullet item, the bullet should be replaced by a checkbox
When I type "*" at start of a checkbox, it should be replaced by a bullet 

When I press <kbd>F12</kbd> at a bullet item, it should change into a checkbox

**Comment by vossenjp** [comment]
I do that pretty often, so... nice-to-have.

**Comment by jaap-karssenberg** [comment]
Fixed in version 0.73
