### ISSUE TITLE
Open page created from custom tool

### ISSUE THREAD

**Issue by js-dot-js** [zim-desktop-wiki/zim-desktop-wiki#1545]
Hey thanks for everything you all do to keep Zim going. I use it all day, every day. It has been a game changer for me over the past few years.

Just had a quick question. I made a custom tool that just creates a file with a timestamp. I would like to have that file opened automatically after it is created. Is there a way to do that? Or do I need to get into creating a plugin to unlock that ability?

Thanks!

**Comment by jaap-karssenberg** [comment]
No, a custom tool cannot tell the application to open a page, that could be
done in a rather simple plugin.

However, depending on the use case, you could have a flow of e.g. inserting
a link to the new page in the current page so you go to the new page by a
single click.

Btw. thinking of it - you might try calling zim from your custom tool as a
commandline tool with "zim NOTEBOOK PAGE" and see if that works - but
afraid it could also deadlock as zim is calling the custom tool when this
call happens. Need to test it to be sure.

-- Jaap

**Comment by js-dot-js** [comment]
Right on, great ideas. Thanks! ⭐
