### ISSUE TITLE
Insert current date (fixed to today) into text file?

### ISSUE THREAD

**Issue by shulist** [zim-desktop-wiki/zim-desktop-wiki#1547]
## Use Case:
I use Zim to record notes of activities during the day. The format of my "Journal" is a file for each month and a line entry for each day of the month as follows:

<hr>
` 
2021-08

Created 2021-08-01

2021-08-08 updated some. 
2021-08-11 Cleared out old.
2021-08-12 Installed the panel.
2021-08-13 Copied all of the files. Have to repurpose 750 GB drive.
`

<hr>

However my fat fingers routinely stumble across entering the date correctly.

## What's needed:
Is there a way to have Zim:

- insert the current date in the file when I hit return (probably not desirable) OR 
- is there a shortcut key to insert the current date? OR
- Is there an alternate way to achieve this? AND
- Insert a date so that it is fixed to the current date as it does in templates?

I have read though all documentation I have found but either I missed the obvious or have not seen the item being discussed. I've only just begun to use ZIM on a cross platform basis so I am somewhat of a NOOB. Anyone point me in the right direction?

**Comment by pfalcon** [comment]
Yes, you missed something obvious, it's exactly where your fingers expect it to be - Ctrl+D. That's one of the problems of Zim - it has too many features already, and people want to add more, instead of learning what it already can do (and stick to that).

**Comment by introt** [comment]
Hi @shulist! 

I'm glad you've found your way to the repository. From your profile it seems you're familiar with Python- hope to see you join our gang! Just ignore the few grumpy fellas, everyone's welcome here.

As to the matter at hand, the aforementioned Ctrl+D does bring up the date insertion dialog, but then you have to click buttons and stuff- boooring. Let's make Zim add the dates for us!

1. Open "Edit" > "Templates"
2. Scroll down and select "wiki" > "Journal". Press "Edit"
3. This is the template used by the Journal plugin. Find the entry for month, which looks like this:

```
[%- ELSIF journal_plugin.page_type == 'month' -%]
======= [% strftime("%B %Y", journal_plugin.date) %] =======
```

Oof. That's a bit bare. Let's make it less so! To make it create pages identical to the ones you're currently typing in yourself, edit it to look like this:

```
[%- ELSIF journal_plugin.page_type == 'month' -%]
======= [% strftime("%B %Y", journal_plugin.date) %] =======
[% gettext("Created") %] [% strftime("%A %d %B %Y") %]

[% FOREACH day IN journal_plugin.days() %]
[% strftime("%Y-%m-%d", day) %] 
[% END %]
```

Note the space at the end of the strftime-line for maximum comfort. Now, make sure the Journal plugin is enabled and set to create a page per month (File > Properties > Journal > Use a page for each > Month). Now, pressing Alt+D will take you to the current month's Journal page, which'll look like this:

```
====== August 2021 ======
Created Sunday 15 August 2021

2021-08-01 
2021-08-02 
2021-08-03 
...
2021-08-31 
```

At the end of the month, you can remove empty dates via the search-and-replace tool of the text editor of your choice. In my case, that's Vim and looks a little like this: `:%s/^\d\{4}\(-\d\d\)\{2} \n//`.

If you have any other questions, the best place to get help is our mailing list: https://launchpad.net/~zim-wiki

Welcome aboard!

**Comment by shulist** [comment]
@pfalcon & @introt thank you both for the suggestions. As to CTL-D -- duh! Must have read it too quickly, though the  Help-Keybindings document says "Inserts timestamp" when perhaps it should say "Inserts Date and Time" as that's the actual screen title.

And @introt I attempted to use your suggested template changes. 
Here's what my Journal template looks like:

`[%- ELSIF journal_plugin.page_type == 'month' -%]
======= [% strftime("%B %Y", journal_plugin.date) %] =======
[% gettext("Created") %] [% strftime("%Y-%m-%d") %]


[% FOREACH day IN journal_plugin.days() %]
[% strftime("%Y-%m-%d", day) %] 
[% END %]`

and here is the error I get when I use that template:

`This is zim 0.73.5
Platform: nt
Locale: en_CA cp1252
FS encoding: utf-8
Python: (3, 8, 5, 'final', 0)
PyGObject: (3, 38, 0)

======= Traceback =======
  File "zim/gui/widgets.py", line 3075, in do_response
  File "zim/gui/uiactions.py", line 502, in do_response_ok
  File "zim/templates/__init__.py", line 130, in get_template
  File "zim/templates/__init__.py", line 158, in __init__
  File "zim/templates/parser.py", line 156, in parse
  File "zim/templates/parser.py", line 163, in __call__
  File "zim/parser.py", line 437, in __call__
  File "zim/parser.py", line 459, in _raise_exception
AttributeError: 'AssertionError' object has no attribute 'message'`

And using ALT-D gives me this error:

`This is zim 0.73.5
Platform: nt
Locale: en_CA cp1252
FS encoding: utf-8
Python: (3, 8, 5, 'final', 0)
PyGObject: (3, 38, 0)

======= Traceback =======
  File "zim/gui/pageview.py", line 5658, in set_page
  File "zim/notebook/notebook.py", line 1122, in get_template
  File "zim/templates/__init__.py", line 130, in get_template
  File "zim/templates/__init__.py", line 158, in __init__
  File "zim/templates/parser.py", line 156, in parse
  File "zim/templates/parser.py", line 163, in __call__
  File "zim/parser.py", line 437, in __call__
  File "zim/parser.py", line 459, in _raise_exception
AttributeError: 'AssertionError' object has no attribute 'message'`

Any suggestions for a repair of the template?

**Comment by introt** [comment]
Re:manual, please submit a PR if you have the time, thanks!

Strange, did ALT+D give you that error before?

To restore your templates, depending on your installation type you could either
* just delete the modified one so Zim'll fall back to the one shipped with it
* copy a fresh one from here: https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/master/data/templates/wiki/Journal.txt
* copy the modified one which works on my system: https://gist.github.com/introt/24497f9219646c4c49ec70cb0225c6bd

I recommend trying the third option, as if that keeps crashing there's a bug to be found.

Excuse my brevity, I'm a tad bit short on time; will get back to you shortly!

**Comment by shulist** [comment]
@introt 

>>submit a PR
Will do.
>>Strange, did ALT+D give you that error before?
No.

We're all out of time these days so I completely understand. Also you did leave me enough information to solve my issue. I used your third option and now Alt-D works correctly. Also the Journal month page creation works as expected. 

So I have an additional related question:

1. How do I modify the Journal Template to name each Journal Month file to be YYYY-MM, that is as August would be 2021-08? I'm slowly trying to learn Zim inner secrets.

**Comment by introt** [comment]
I seem to have misread in my haste- Alt+D takes you to today's journal page, and thus breaks identically to other ways of opening said page. The error message should probs hint that your template is broken- actually, there really should be a check after modifying one, but that's another issue.

~As to modifying the templates, see [0] for general Zim template writing and [1] for formatting dates.~ Oops, almost did it again! There's no option for editing the page names that I know of, but if you insist, you can edit the plugin; find this line here:

https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/febdc744de2409f289071d4034ad9a45898a82fe/zim/plugins/journal.py#L136

and change the `:` into a `-` (or `'%Y:%m'` into `'%Y:%Y-%m'` if you want the month pages to still be under year pages). Do note that the file will be overwritten by updates, so you'll probs want to make a copy of the plugin and use that instead of the built-in one.

0. https://zim-wiki.org/manual/Help/Templates.html
1. https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes

**Comment by shulist** [comment]
@introt thanks for that you've given me a direction to go in and will follow it.
