### ISSUE TITLE
Is there a way to run zim-wiki on iPad OS?

### ISSUE THREAD

**Issue by brainbow1** [zim-desktop-wiki/zim-desktop-wiki#1553]
Hello!

I am still dreaming of this to be possible.
Is it realistic that this will be possible in the future?

Best regards

**Comment by mbakstars** [comment]
I'd love this. I am using the program to write SOP manual and would love to edit it while be comfortable on my couch. =)

**Comment by jaap-karssenberg** [comment]
Short answer: no.

Longer answer: I plan to support markdown in future releases - long term
plan for now - so you could at least use other markdown editors to edit the
same content.

By comparison on android the "markor" app is now a good candidate for
editing zim wiki content.

**Comment by ehremington** [comment]
I have gotten a hack version of this to work and it is OUTSTANDING (at least for me and the notes that I keep).

Here's how I do it:
1. Keep Zim Notebook in Dropbox
2. Use @pfalcon 's zim-markdown fork here: https://github.com/pfalcon/zim-desktop-wiki-markdown . I use this on any linux laptop I have
3. Use 1Writer app on iphone and ipad. This syncs with Dropbox, and has a good keyboard for editting markdown. The sidepane shows notes and folder in the zim directory, so navigation is nearly the same as zim itself. And you can switch easy from editting to previewing the rendered markdown.

This has been working excellently for me so far. Conversion of zim to markdown wasn't painless but I'm making small corrections as I get to them (mostly verbatim quotes). Code plugin also doesn't work as far as I can tell. 

I think 1Writer is the way to go on the iPad side though once Zim fully supports markdown.

**Comment by introt** [comment]
@ me if you'd like to continue this discussion over at Discussions
