### ISSUE TITLE
copy-pasting images with relative path does not work as intended

### ISSUE THREAD

**Issue by mtill** [zim-desktop-wiki/zim-desktop-wiki#1554]
Hi!

when copy-pasting text containing images, relative paths to these images will not be adapted correctly when pasted into the new location.

steps to reproduce:
1. paste some image data from clipboard into a newly created page A (ctrl-v)
2. create a new subpage B of that page A, select the content of page A including the image and paste it to subpage B.

Best regards
mtill

**Comment by jaap-karssenberg** [comment]
Can you give an example for a specific test case?

**Comment by mtill** [comment]
steps to reproduce:

    paste some image data from clipboard into a newly created page A (ctrl-v)
    create a new subpage B of that page A, select the content of page A including the image and paste it to subpage B.

**Comment by jaap-karssenberg** [comment]
Just tested in the development version and there it works fine. If you are
on a release version, it will be in the next release.

**Comment by mtill** [comment]
Thank you very much for your kind reply, Jaap. 
Do you expect a longer time frame until the new release will be ready to download?

**Comment by roland-ruedenauer** [comment]
@jaap-karssenberg could you maybe provide some details regarding your plans to release a new version of zim?

**Comment by introt** [comment]
New version has been released
