### ISSUE TITLE
Support continued numbered lists & bullet points

### ISSUE THREAD

**Issue by diaasami** [zim-desktop-wiki/zim-desktop-wiki#1556]
In Github Markdown, it's possible to have a list of bullets or a numbered list with text in between, something like this:

The following source 
```
1. Item 1
Item 1 explanation
1. Item 2
    Item 2 explanation
1. Item 3

* Item
    Item explanation
* Item
Item explanation
* Item
```

becomes:

1. Item 1
Item 1 explanation
1. Item 2
    Item 2 explanation
1. Item 3

* Item
    Item explanation
* Item
Item explanation
* Item

You can notice that:
1. The explanation text is properly indented.
2. The numbering is properly continued after the explanation.

I believe this writing structure is common and it does not seem to be supported in zim desktop wiki.

**Comment by diaasami** [comment]
1. item 1
2. item 1
3. item 1
4. item 1
2.

**Comment by introt** [comment]
There's also this other type of continued numbering which seems common with image annotations; it's not supported by GitHub's markdown, but won't get renumbered either (thought indenting will turn the detected numbering into roman numerals)

First group
1. one
2. two
3. three

Second group
4. four
5. five
6. six

Third group
7. seven
8. eight
9. nine

**Comment by jaap-karssenberg** [comment]
This will be a "won't fix" for current zim wiki format. Aware that this needs to change in order to support MarkDown
