### ISSUE TITLE
Command line batch export for make systems.

### ISSUE THREAD

**Issue by AlastairGrowcott** [zim-desktop-wiki/zim-desktop-wiki#1558]
I have a project where I have authored some initial documentation using Zim. During the build process I want the documentation to be exported to HTML to be included in the installer. This needs to be an automatic step as part of the build process.

It looks like Zim uses non-standard markdown. Certainly Markdown.pl (http://daringfireball.net/projects/markdown/) totally barfed on it. Plus I like the idea of having an HTML export template.

It would be great if you could include a command line based file exporter in the Zim installation. Syntax could be something like:

zim-export -z &lt;zim file&gt; -o &lt;output directory&gt; -i &lt;index filename&gt; -t &lt;template HTML file&gt;

I appreciate that this will probably take some time...and I need an exporter now...so I probably will be switching away from using Zim for this project unless I can find an alternative that does at least roughly what I want.

**Comment by AlastairGrowcott** [comment]
I think I tried zim --help and zim -? but not zim -h. I also tried the in GUI help if I remember correctly.

Thanks for the info.

**Comment by vossenjp** [comment]
On 8/31/21 2:53 AM, AlastairGrowcott wrote:
> I think I tried zim --help and zim -? but not zim -h. I also tried the in GUI help if I remember correctly.

Huh, `zim --help` just worked for me (zim 0.73.5 on Linux Mint-19.3).  `zim /?` did not, as expected.  I haven't looked at the GUI manual in a long time, if things are missing or have gotten out-of-sync that's probably a good bug request, and it might be a great "first project" for someone not comfortable diving into the Python code.


> Thanks for the info.

You're welcome.


Later,
JP
--  -------------------------------------------------------------------
JP Vossen, CISSP | http://www.jpsdomain.org/ | http://bashcookbook.com/
