### ISSUE TITLE
ToC pane missing Copy Location & Drag'n'drop for links

### ISSUE THREAD

**Issue by introt** [zim-desktop-wiki/zim-desktop-wiki#1560]
Given #1293 the ToC pane should support the same linking-related UX as the other TreeView panes, as in being able to copy links to headings that aren't currently visible in the editor.

Edit: "Open in New Window" would also be useful when reworking the structure of longer notes

**Comment by introt** [comment]
@roland-ruedenauer would you be interested to tackle this? I can also try later when I find the time, real busy atm in flesh life

**Comment by roland-ruedenauer** [comment]
I will have a look into this.
