### ISSUE TITLE
Add variable for creation origin to wiki page template context

### ISSUE THREAD

**Issue by introt** [zim-desktop-wiki/zim-desktop-wiki#1561]
A `page.origin`, if you will; this would have the attributes `.name`, `.section` and `.basename` corresponding to those of the page containing the link the user opened to get to this yet-nonexistent page.

### Alternative implementations
- Exposing `page.backlinks` to page template context
  - Not very useful as it won't get updated after page creation
- Exposing the page history?
  - With len > 1 would allow interesting use cases like easy journaling of one's wiki voyage

### Use case
I have a dictionary section in my notebook to make it easy to link and look up terms and acronyms. Currently, when I come across a new term while taking notes, I link to a non-existing page and (later) open it to write a brief description of the term. When coming across a term later on I create a link to its dictionary page; thus I can't determine its first appearance - usually containing its broader definition - by BackLinks alone.

**Comment by jaap-karssenberg** [comment]
Would prefer "history" over "origin". 

Not sure about the use case though, for this to work, you need to both create the link *and* then visit the page from that link *and* edit / safe the page for the template to work.

Sounds more like a custom tool / plugin that allows highlighting the word and click "add to index".

**Comment by introt** [comment]
> Sounds more like a custom tool / plugin that allows highlighting the word and click "add to index".

Agreed. I remember building something like this on top of [Text Replacer](https://github.com/introt/zim-plugin-text-replacer), but don't think I got very far prior to having to change my workflow for external reasons.
