### ISSUE TITLE
Line sorter plugin shortcuts still don't work in single page window

### ISSUE THREAD

**Issue by sojusnik** [zim-desktop-wiki/zim-desktop-wiki#1565]
As mentioned [here](https://github.com/zim-desktop-wiki/zim-desktop-wiki/commit/a3b9c7bc86253988ccc0f1b6cfc61603ee3bad92#commitcomment-56123609).

**Comment by jaap-karssenberg** [comment]
Good point - will just add a menubar to the page window to make sure all
extensions work the same
