### ISSUE TITLE
surprise deletion of higher-up nodes

### ISSUE THREAD

**Issue by swestlake** [zim-desktop-wiki/zim-desktop-wiki#1572]
release: 0.74
platform: Linux 

If a user creates a node called "somethingA:somethingB"...

.. there will be two nodes, "somethingB" will be a sub-node of "somethingA".

There is no warning of multiple nodes getting deleted when the user removes node somethingB.

Example.

Create a top-node called "a", 

and then create a sub-node called "somethingA:somethingB".

Now delete the "third node" called "somethingB" (since Zim automatically created it).

node somethingA and somethingB both get deleted.

**Comment by jaap-karssenberg** [comment]
Sorry but can you make your example more specific? With these instructions
I cannot reproduce the issue you report.

Op wo 15 sep. 2021 04:36 schreef swestlake ***@***.***>:

**Comment by swestlake** [comment]
make sure the test-user does not add anything else to the parent page.

for example,
create a node called "a:b", and do not create any page content on "a" otherwise it will not get auto-deleted.
simply creating node "a:b" then deleting node "b" then makes node a to also go away.

I've had this issue with prior releases, but never bothered to report it because I may have thought there was a feature in the work since the parent-nodes will not get auto-deleted when there is content with them.

But I realize it's been too long as a work-in-progress so this is why I am thinking this could be a bug.

This problem has been going on much earlier than 0.74, but it doesn't get in the way of tasks I wish to perform.

the very few times I would like to use ":" in the page title is when it always happens..

but the bug is there and I can always replicate it.


fwiw, the bug also happens when using multiple ":" characters such as "a:b:c:d".

When I delete node "d", then nodes a, b, c also get auto-deleted with it..

so there's definitely a bug around ":" in the page titles...

**Comment by jaap-karssenberg** [comment]
This is not a bug, but a feature. Empty pages don't really exist in zim -
there is not file in the folder to represent them if there is no content.
So if you remove the last sub-page that does have content, the empty parent
is cleaned up automatically. If you want the parent page to be persistent,
you should add some content.

The ":" in a page name is used as separator between parent- and sub-pages
(like "/" or "\" in file names) so you can't really use ":" as part of a
page name as it has a special meaning. However you can use it in the page
_title_ without problem, that is just text on top of the page.

-- Jaap

**Comment by swestlake** [comment]
This is not-intuitive because if a user wants to remove a sub-node a week later, they would have forgotten completely that they generated the multiple parent nodes using ":" and the deletion behavior is not standard.

What if the user wishes to retain the parent nodes? 

The standard behaviour, is to remove one node, or I think the least option should be given to the user as a form of a prompt, asking the user if he wishes to also delete "a list of parent nodes" that was autogenerated with ":".

I think the standard deletion should be better to utilize as it is everywhere, because it is too confusing to remember where ":" was used previously and exactly when+how it was used.

Is there more documentation about this? Perhaps there is some encompassing feature I am not noticing..
Is there a way to disable this feature?

thanks for explaning what is happening, but I'm not sure how this is a helpful feature as it is difficult to remember which nodes were created with ":", and which ones aren't -- there's no indicator on which ones are, so I am not sure how this is supposed to be a helpful feature.. Most of the time I would wish to retain parent nodes and not have them auto-deleted, even if the pages are empty in content.

I am not sure what other users think about having pages auto-generated as a feature, perhaps most users haven't thought about using ":" in page titles, but I think the majority of users would agree with me that this kind of auto-deletion is very confusing and should be an opted feature where the user can enable/disable it. It is impossible to tell which pages were auto-generated using the : character, and the standard behaviour of deleting pages should definitely be what the user expects there to be.. not surprise auto-deletion of parent nodes even if those parent nodes are empty.

thanks
