### ISSUE TITLE
Inconsistent attachment copying behavior

### ISSUE THREAD

**Issue by introt** [zim-desktop-wiki/zim-desktop-wiki#1574]
### Version and platform

Zim 0.74.0 on Linux

### Expected behavior
All attached images get treated equally, regardless of whether they're embedded in the page with or without the relative path `./`.

### Actual behavior
When moving images to a subpage, they will get copied if their location starts with a path (including `./`), but linked (source becomes `../`) if not.

### Suggested behavior
In my opinion, all relative paths, with or without `./` should always be linked instead of copied when using Move Selected Text -- I'd even go as far as move the attachments along with the text, but that'd be too fragile in the real world -- in contrast to copying text, where attachments should always get copied. Furthermore, cutting [should](https://www.youtube.com/watch?v=pWdd6_ZxX8c) act like Move Selected Text, not like Copy + delete.

### Steps to repro/test

1. Create a page with the below contents, including attachments:
```
=== image ===
{{pasted_image.png}}

==== image with path ====

{{./pasted_image001.png}}

=== image with props ===
{{pasted_image002.png?height=100}}

=== image with both props and path ===
{{./pasted_image003.png?height=100}}
```

2. Select the above and use Move Selected Text to move it to a subpage
3. Inspect the page source (currently as shown below) and the amount of attachments (2)

```
=== image ===
{{../pasted_image.png}}

==== image with path ====

{{./pasted_image001.png}}

=== image with props ===
{{../pasted_image002.png?height=100}}

=== image with both props and path ===
{{./pasted_image003.png?height=100}}
```

**Comment by jaap-karssenberg** [comment]
Please see my notes in the commit. Did it on purpose like this, because
images with "../" are already linked from another page and not an
attachment of the text being copy-pasted or moved.

Did not move images because I cannot checked whether that breaks links
elsewhere in the notebook. Left as future improvement when we can check /
update file links same as page links on page move.

-- Jaap

**Comment by introt** [comment]
Sorry, I'm uncertain which commit you mean. 3f78578113be9920c3108d8a2efc5cb77b011805 -> Move text shares implementation with copy, which I can agree with, but that still leaves us with inconsistent behavior, regarding which I'm guessing c28cde55159ae848ad5b6e586b742231cd717b9a is relevant:

> Copy image attachments on copy-paste of formatted text with images
> to either another page or another notebook. For images where the
> source is not a direct attachment, the source link will be updated
> but the file is not copied.

I understand copying images that are linked from parent or beyond (`../`), but images with `./` are direct attachments- shouldn't they be treated as such? 

Ie. the rel path `./` is should be a special case, as unlike the other relative paths it refers to direct attachments (This does bring up the edge cases of eg. `./../whatever.jpg` and `./subpage/pic.png`, but maybe allow max one `/` or something- not sure what happens with Windows). It's also automatically prepended when using the properties dialog or pasting from clipboard.

**Comment by jaap-karssenberg** [comment]
The logic does not directly check for "./" as it is written in the wiki
source. The file path is resolved first, so the check applies to any file
that is in, or below the attachment folder of the source page.

So "image.png", "./image.png" and "./subpage/image.png" all are treated
equal, only "../image.png" and "/image.png" and "file://.../image.png" are
referred by linking.

Hope that clarifies.

-- Jaap

**Comment by jaap-karssenberg** [comment]
P.S. should have written "*should* all be treated equal" instead of "all
are treated equal" - let's add test cases to verify if there are bugs
lurking here

**Comment by introt** [comment]
Re: my earlier message,  "images with `./`" is too imprecise; here's a few examples to illustrate what I'm after:

**Direct attachments of :Parent:ThisPage**
- {{img.png}} (gets linked)
- {{./img.png}} (gets copied)
- {{../ThisPage/img.png}} <- this one's real shady
- (all refer to the same file, at least the top 2 should be handled the same but currently are not)

**Not direct attachments, linked from other pages**
- {{./subpage/img.jpg}}
- {{../parent.jpg}}
- {{../sibling/pic.jpg}}
- {{./../sibling/pic.jpg}}
- these are correctly copied

Re: @jaap-karssenberg 

Emphasis on should -- the unequal treating is demonstrated in the issue -- I thought the wiki text mattered because it did :)

Thanks for clarifying the design, I'll try writing some tests for the behavior!

**Comment by introt** [comment]
So- I ran the tests as seen in the main branch and then did the minimal change

```
diff --git a/tests/pageview.py b/tests/pageview.py
index 284781c8..c2efa576 100644
--- a/tests/pageview.py
+++ b/tests/pageview.py
@@ -3819,7 +3819,7 @@ class TestMoveTextDialog(tests.TestCase):
                pageview = setUpPageView(notebook, text='''\
 Some **bold** test
 
-An image {{./zim.png}}
+An image {{zim.png}}
 And a link [[+Foo]]
 
 All in one page
```

resulting in the failure depicted below:

```

======================================================================
FAIL: runTest (tests.pageview.TestMoveTextDialog)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gurgeh/Repositories/zim-desktop-wiki/tests/pageview.py", line 3843, in runTest
    self.assertEqual(newpage.dump('wiki')[-2:], [
AssertionError: Lists differ: ['An image {{../Test/zim.png}}\n', 'And a link [[Test:Foo]]\n'] != ['An image {{./zim.png}}\n', 'And a link [[Test:Foo]]\n']

First differing element 0:
'An image {{../Test/zim.png}}\n'
'An image {{./zim.png}}\n'

- ['An image {{../Test/zim.png}}\n', 'And a link [[Test:Foo]]\n']
?               ------

+ ['An image {{./zim.png}}\n', 'And a link [[Test:Foo]]\n']

```
For what it's worth, I couldn't find any tests for attachments without `./` or `../` (don't think the matches in /tests/data are used by the clipboard test suite) - we might want to look into that after finding this bug's source.

```
$ grep "[^{]{{[^.{%']" tests/*.py
tests/formats.py:		text = '{{id: test}}'
tests/pageview.py:An image {{zim.png}}
```
