### ISSUE TITLE
"Floating point exception (core dumped)" for "~~ideation~~"

### ISSUE THREAD

**Issue by benopotamus** [zim-desktop-wiki/zim-desktop-wiki#1575]
Does Zim not like ideation? ;-) I've attached a file that reliably causes Zim to crash/quit with the following debug message: 

`Floating point exception (core dumped)`

This behaviour was produced with the a fresh download of the source today from GitHub.

Running environment is OpenSUSE Tumbleweed and Gnome 40.4

[Floating_point_test.txt](https://github.com/zim-desktop-wiki/zim-desktop-wiki/files/7169453/Floating_point_test.txt)

**Comment by jaap-karssenberg** [comment]
This is a duplicate - upstream issue in GDK - fix is available in new
version of that library

**Comment by jaap-karssenberg** [comment]
See issue #1548 for details
