### ISSUE TITLE
Incorrect label on sidepanel tasklist

### ISSUE THREAD

**Issue by sallirom** [zim-desktop-wiki/zim-desktop-wiki#1576]
Hi, 

there is one thing funny with the label on sidepanel tasklist. At first I thought it was a bad translation, so I visited weblate to search for it, but now I think there is no problem with the translation because it is correct.

I use zim in spanish, and the task sidepanel is labeled "Etiqueta de la pestaña para el panel lateral". The translation is correct, but the content doesn't, because it is a placeholder. In english it means something like "Tab label for the side panel". This makes me wonder if the problem is elsewhere.

I hope this helps.

![imagen](https://user-images.githubusercontent.com/12543652/133424510-adc3eb72-b9bd-4406-8a30-58212368b1b1.png)

I am using Manjaro linux, BTW.

**Comment by introt** [comment]
Hi! Seems like a translator error. From your screenshot it looks like you're using an older version of Zim. I can't find the string from 0.74.0's sources, so this might've been fixed already; if not, please let us know!

**Comment by sallirom** [comment]
Gee, how silly of me not posting zim versión (it was indeed 0.73.5).

Thank you so much  for the answer and for showing me a way to verify it for myself next time.  ;)

I am happy it is already fixed.

All the best!
