### ISSUE TITLE
Formatting toolbar 0.74 place

### ISSUE THREAD

**Issue by Nick222** [zim-desktop-wiki/zim-desktop-wiki#1577]
Very good new version of Zim! :)

But - how to switch off formatting toolbar (bold, italic etc) under note?

And - may be move INS-OVR indicator up - near Toggle editable button/indicator?

Thank You!

**Comment by jaap-karssenberg** [comment]
Please read the release bulletin - there is a toolbar plugin that allows
you to revert to the old toolbar style.

**Comment by Nick222** [comment]
OK - but when I switch off this Toolbar plugin - I see formatting toolbar under each note...

**Comment by jaap-karssenberg** [comment]
Yes, this is as designed

**Comment by Nick222** [comment]
And can user switch off this formatting toolbar and how ?

**Comment by jaap-karssenberg** [comment]
Sorry, but this kind of question belongs in the new "discussion" section,
not as an issue. Would help me a lot if you can formulate the topic / short
description as an actual question.

To answer your question: no, you cannot turn it off, you can file a feature
request to allow turning it off and I will look into it in due time.
(Please then formulate the issue as a feature request.)

Thanks,

Jaap
