### ISSUE TITLE
Table of Contents (ToC) plugin collapses headings

### ISSUE THREAD

**Issue by Nick222** [zim-desktop-wiki/zim-desktop-wiki#1579]
If user create a hierarchical system of headings in a note, then expand all the headings, then save the note - and reload the program - all headings in the note content window, except for the first level headings, will be collapsed.

Previously version, the state of the headings in this window was remembered.

Zim 0.74
Xubuntu 21.04

**Comment by jaap-karssenberg** [comment]
What is the "content window" - are you talking about the "table of
contents" plugin ?

**Comment by Nick222** [comment]
Yes - in Russian another name, but in English "Table of content"
Excuse me

**Comment by Nick222** [comment]
Very strange...

When I create another note without heading in it - save all - and restart - Zim open this note.
Then I go to note with heading - and in "TOC-plugin" window everything OK.

But when I edit and save note with heading in it - save and restart Zim - then in "TOC-plugin" window heading collapsed.

Are this understand?

**Comment by sojusnik** [comment]
I observe with `0.74.0-SNAPSHOT-t202109171459~ubuntu21.04.1` that the entries in the "table of contents" left sidebar are always collapsed after a fresh start of Zim. The same is true when a separate window is opened.

Would prefer if the state of collapsed/expanded would be saved across Zim sessions (in the main window and the separate windows) or there will be an option in the plugins settings that the default state of headings should be either collapsed or expanded.

**Comment by jaap-karssenberg** [comment]
Needs investigation. Inspected the diff between versions 0.73.5 and 0.74.0 and cannot understand the different behavior. Seems to me that ToC should be expanded more often instead of collapse.

**Comment by Nick222** [comment]
What should I do in this situation ?

**Comment by jaap-karssenberg** [comment]
Nothing for now. Tag means I recognize the issue, just haven't found how to solve it yet. Hopefully other contributors have a good idea ;)
