### ISSUE TITLE
Verbatim Formatting

### ISSUE THREAD

**Issue by pityhero233** [zim-desktop-wiki/zim-desktop-wiki#1583]
Is it possible to have support for multi-line verbatim? Considering the current code block support for zim is quite broken ([#1317](https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/1317), [#642](https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/642)), frequently the need to write multiline code / pseudo algorithm via verbatim emerge.

However, the current verbatim format resets on a newline (as with any other format). it is VERY troublesome, as usually the code has indentation, and If you have to repress Ctrl-V on the beginning of each line after indentation, the spaces before the cursor will not be marked as verbatim and hence will not be monospace. In practice it usually lead to considerable amount of micro-management of spaces and indentations. 

I wonder if it's possible to, say, add a checkbox for "multi-line verbatim by default". That will significantly make it easier!

Thanks :D

**Comment by jaap-karssenberg** [comment]
Under the hood it is supported. If you direct multiple lines and select
verbatim it will be a continuous block in the wiki format.



Op wo 15 sep. 2021 21:20 schreef Shi Zhengyu ***@***.***>:

**Comment by pityhero233** [comment]
To do that I have to write code in another monospace editor first, paste it into zim, then perform formatting.

What I was looking for is that there have an option of 'maintaining verbatim after newline', so that the user can type in pseudo code stuff while thinking.

**Comment by jaap-karssenberg** [comment]
Understood.

Work around could be to select 2 empty lines, format verbatim, and then
start typing on the first line.

Op do 16 sep. 2021 13:21 schreef Shi Zhengyu ***@***.***>:

**Comment by ZtzEAcRsND** [comment]
If your use case is typing in write multiline code / pseudo algorithm that is formatted verbatim similar to the code block, then another way to do this that isn't a work around:

* start a new newline
* enter three single quotes ''' then enter <RETURN>
* type your lines of text or multi-line code with <RETURN> after each line
* after your last line of type enter <RETURN>
* enter three single quotes ''' , then enter <RETURN>
* then reload the page refresh with either menubar>view>reload or <ctrl>R
* zim will reload the page. Your text will be formatted in monospace font and indented. The three single quotes before and after the block will disappear.
* you can create new lines in the verbatim block by enter <RETURN> after any line in the verbatim block.
e.g., 
```
'''
1st line
2nd line
'''
```
NOTES
1. This works in zim 0.73.5 through 0.74.1 on linux
2.  Entering wiki-syntax formatting codes is described in the zim manual under 'markup' at https://www.zim-wiki.org/manual/Help/Wiki_Syntax.html
3. Verbatim block/multi-line format (three ''')  is different than the single line verbatim format (two ''). The different format possibilities are described under 'GUI style config file' at https://www.zim-wiki.org/manual/Help/Config_Files.html ; e.g., verbatim block/multi options use the 'pre' tag section and verbatim single line options are under the 'code' tag section. 
4. The same help text describes how to modify the GUI styles. e.g., try adding 'background=#E3E3E3' to the 'pre' section to get a gray background similar to the code block plugin.
5. A manual reload is needed as zim will not automatically reload/reformat the manually entered verbatim block codes even if the 'menu>preference>edit>reformat wiki codes on the fly' is checked (on).
6. IMO this method is easier than formatting two or more lines with <ctrl>T, then typing your text.

...and thanks @jaap-karssenberg for all you've done.

**Comment by pityhero233** [comment]
Thanks for all your generous help! Issue closed.
