### ISSUE TITLE
0.74 not available for windows

### ISSUE THREAD

**Issue by mtill** [zim-desktop-wiki/zim-desktop-wiki#1589]
exe file is missing under /download dir

**Comment by jaap-karssenberg** [comment]
Yes I know. Will do the work of compiling an installer with the first
"point" release with fixes.



Op do 16 sep. 2021 21:29 schreef mtill ***@***.***>:

**Comment by mtill** [comment]
Thank you Jaap for your reply.
I was curious today on how to build that windows executable and found the howto here:
https://github.com/zim-desktop-wiki/zim-desktop-wiki/tree/master/windows

following these steps was quite easy so i successfully build that exe file on my own

** Thank you for this really great piece of software!
