### ISSUE TITLE
Paragraphs displayed as links at zim-wiki.org homepage

### ISSUE THREAD

**Issue by oturpe** [zim-desktop-wiki/zim-desktop-wiki#1592]
Every or most paragraphs on zim-wiki.org
start with part that is displayed as link,
i.e. reddish color and gets underlined on hover.
It seems that the first real link in the paragraph terminates this
and the rest of the paragraph is formatted normally.

Operating System: Fedora 34
Browser: Firefox 92.0

Example from the main page:
![kuva](https://user-images.githubusercontent.com/5121186/133879309-d3dea3bc-a573-4eae-ac37-3c81f92b0b4d.png)

**Comment by jaap-karssenberg** [comment]
Yes, issue has been fixed already in the master branch, will upload new
website with next point release
