### ISSUE TITLE
Optional edit bar

### ISSUE THREAD

**Issue by robertvazan** [zim-desktop-wiki/zim-desktop-wiki#1594]
The new edit bar at the bottom of the window forces the window to be about 4cm wider than before. Most of my notes are lists, so I keep the window narrow and use the rest of the screen for other stuff. I have no use for the edit bar anyway, so the easiest solution would be to turn it off, but there's no way to remove it, because it's not a plugin like other toolbars and side panes. Please either turn the edit bar into a plugin or add an option to disable it or give it responsive layout that adapts to narrow windows.

Related: #578 #1582

**Comment by robertvazan** [comment]
BTW: The whole point of placing UI in the header bar is to make the UI unobtrusive and to maximize content area instead. Zim however fails to place menu in the header bar and it even uses this opportunity to force additional UI on the user in the form of the edit bar. Proper use of the header bar should actually make it easier to use the app in a narrow window.

**Comment by introt** [comment]
Hi! By popular demand, Jaap has made the new edit bar optional. The option will be included in 0.74.1, hold on tight (or grab a copy from the develop branch)!

**Comment by vossenjp** [comment]
Meanwhile, activating the new "Toolbar" plugin will make the "edit bar" disappear, but until the change discussed here you have to have one or the other.

Note, the "Edit bar" tells you in both "pressed buttons" and words about both formatting and header level.  The "Toolbar" tells you what formatting is applied in "pressed buttons" but not words, and it omits the header level.  I have to confess I have difficultly visually distinguishing header levels and sometimes the code style, so I need the clue.

**Comment by jaap-karssenberg** [comment]
My original plan was to make edit bar auto-hiding as an option. Next
release I added option to just hide it. Auto-hide hopefully release +2

Will also work on removing the menu bar. So screen real estate should be
maximized.

Op zo 19 sep. 2021 03:57 schreef JP Vossen ***@***.***>:
