### ISSUE TITLE
0.74 release notes: Remove statusbar - Is information shown somewhere else?

### ISSUE THREAD

**Issue by Simplenuity** [zim-desktop-wiki/zim-desktop-wiki#1595]
I found it extremely helpful to see the header level on the statusbar. Now that the bar is gone, is this info as easily available somewhere I didn't discover it yet?

PS: Thanks for all the effort. It's an outstanding piece of software, No 1 in my daily work & life

**Comment by jaap-karssenberg** [comment]
It is shown in the edit bar at the bottom of the editor screen

Op za 18 sep. 2021 21:58 schreef Simplenuity ***@***.***>:

**Comment by Simplenuity** [comment]
Thanks, Jaap!
Unfortunately this info is not displayed when the Edit Bar gets included in the Tool Bar what I had activated. Is this by design?

**Comment by jaap-karssenberg** [comment]
Yes, haven't found a good place to show it in that version.

Op zo 19 sep. 2021 12:37 schreef Simplenuity ***@***.***>:

**Comment by Simplenuity** [comment]
At the very bottom there is a bar showing the number of attachments with plenty of space to the right. Wouldn't that be a suitable place, right aligned? On that note, I'd suggest to move the "Clear Formatting" button to the Edit Bar as it's an edit action. Opposed to the two for information only fields (<format> and INS/OVR)

**Comment by jaap-karssenberg** [comment]
Afraid not, that bar showing attachments is only there if you have the
attachment browser plugin enabled, if you move that around the bar is not
shown. Only way to reliably show it at the bottom is to bring back the
statusbar, but I feel that is a waste of vertical space in the editor
window.

The default edit bar has an "clear formatting" button. Maybe you are
thinking of the edit actions in the toolbar plugin "classic toolbar" option
?

-- Jaap

**Comment by Simplenuity** [comment]
Ah, sorry, didn't realize that bar was related to the attachment bar with quite a few plugins activated.

Reg. the "clear formatting' button, maybe there's a misunderstanding. I was referring to this button sitting on the very right of the edit bar. As it's an action button AND part of editing/formatting IMHO it would make more sense to move it to the left together with all the other action buttons for formatting. Not a biggie though.

As for me I didn't/wouldn't mind the status bar, esp. if as much helpful info as possible gets displayed there. Like combining the attachment and the status bar, or even in addition with the path bar... I know it will be hard to match everyone's ideas/needs.

**Comment by Simplenuity** [comment]
original question has been answered, it wasn't an issue/bug
Thanks, Jaap!
I guess discussions about the different bars are better suited in the new discussion area

**Comment by jaap-karssenberg** [comment]
Good idea, feel free to start a topic on this

Op ma 20 sep. 2021 10:12 schreef Simplenuity ***@***.***>:
