### ISSUE TITLE
zim hangs while updating index (Ubuntu 18.04)

### ISSUE THREAD

**Issue by gileyro** [zim-desktop-wiki/zim-desktop-wiki#1599]
Ubuntu 18.04
Zim 0.74.0-t202109161818~ubuntu18.04.1
![zim-hangs](https://user-images.githubusercontent.com/40139494/134026245-df9ef1d5-adac-46aa-8404-01f70e638a58.png)
I cannot start Zim anymore.
Every time I start it it shows "Updating index" and hangs.

**Comment by gileyro** [comment]
I started Zim with -D option, it stuck on 

```
...
DEBUG: New extendable: <mainwindow.MainWindow object at 0x7f47b3d03318 (zim+gui+mainwindow+MainWindow at 0x22c0290)>
DEBUG: Load extension: <class 'zim.plugins.bookmarksbar.BookmarksBarMainWindowExtension'>
DEBUG: Load extension: <class 'zim.plugins.pathbar.PathBarMainWindowExtension'>
DEBUG: Load extension: <class 'zim.plugins.quicknote.QuickNoteMainWindowExtension'>
DEBUG: Load extension: <class 'zim.plugins.trayicon.TrayIconMainWindowExtension'>
DEBUG: Add window: StatusIconTrayIcon
DEBUG: Accelmap: /home/mgil/.config/zim/accelmap
DEBUG: Opening ProgressDialog: Updating index
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck found out-of-date
DEBUG: Index file: /home/mgil/zim/todo.txt

```
then I invoked `Ctrl-C` and it resumed 'Updating index'
I'm waiting for the result.

**Comment by gileyro** [comment]
OK. I seems that the problem disappeared. After several minutes the updating index finish and the application works again.

**Comment by jaap-karssenberg** [comment]
Sorry, but I'll need more information than that to be able to solve it.
Please try command line "zim --index --debug path/to/notebook".

Op ma 20 sep. 2021 17:03 schreef gileyro ***@***.***>:
