### ISSUE TITLE
Is there any way to access the temporary xdot file that the linkmap plugin generates?

### ISSUE THREAD

**Issue by quesada** [zim-desktop-wiki/zim-desktop-wiki#1600]
My goal is to display it in a way where I can move the nodes around/cluster them

**Comment by jaap-karssenberg** [comment]
You will have to wrap your own version of the plugin for that kind of stuff

Op ma 20 sep. 2021 17:10 schreef Jose Quesada ***@***.***>:

**Comment by jaap-karssenberg** [comment]
Question - please use "discussions" forum for further discussion
