### ISSUE TITLE
FR: moving multiple pages at once

### ISSUE THREAD

**Issue by quesada** [zim-desktop-wiki/zim-desktop-wiki#1601]
Right now, you can right click a single page and change parent. I'd like to do that for a selection of pages in the Index sidebar, instead of going one by one.  
I know pages and subpages are folders. 
I've tried moving the folders in the filesystem and rebuilding the index. This doesn't work, right now, but if it did it could be a wonderful transitory solution till something with a better UX gets implemented (I know it's in Jaap's mind)

**Comment by jaap-karssenberg** [comment]
Actually moving the files and re-indexing should work fine. Zim does not
keep any state of page content other than the files and the index.

Only catch is that by moving does you can break links.

Op ma 20 sep. 2021 17:21 schreef Jose Quesada ***@***.***>:

**Comment by quesada** [comment]
Yeah, this is what I mean by 'not working', links break.

**Comment by introt** [comment]
Please use #2015 for further discussion, thanks!
