### ISSUE TITLE
Zim on Raspberry Pi 4

### ISSUE THREAD

**Issue by Nick222** [zim-desktop-wiki/zim-desktop-wiki#1603]
I install Zim on Raspberry Pi 4 - but it is only Zim 0.68 for it.

How van I install latest stable Zim version on Raspberry Pi 4 ?

**Comment by jaap-karssenberg** [comment]
Please use the "discussions" forum for this kind of question, not an issue
ticket. Thanks.



Op di 21 sep. 2021 12:00 schreef Nick222 ***@***.***>:
