### ISSUE TITLE
Data lost when renaming page

### ISSUE THREAD

**Issue by TwonkyHardware** [zim-desktop-wiki/zim-desktop-wiki#1616]
I posted an issue, but it turned out to be my own error.  Everything is fine, no data lost.  Don't know how to delete this post.

**Comment by TwonkyHardware** [comment]
User error, please ignore.  Everything is fine, no data lost.  Don't know

**Comment by jaap-karssenberg** [comment]
For information / other users who might end up here: yes the colon is the
"namespace" separator, so a page name "Category: Page" will result in a
file "Category/Page.txt". Content should be in this file. If the index does
not reflect it correctly please first run "update index".

-- Jaap
