### ISSUE TITLE
Travis-CI.org is shutdown

### ISSUE THREAD

**Issue by pdecat** [zim-desktop-wiki/zim-desktop-wiki#1620]
I could not find zim-desktop-wiki at Travis CI:
- https://app.travis-ci.com/search/zim-desktop-wiki returns nothing
- https://app.travis-ci.com/github/zim-desktop-wiki/zim-desktop-wiki/ does not work

Is it gone with https://travis-ci.org/?

> Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on.

https://blog.travis-ci.com/2021-05-07-orgshutdown

**Comment by pdecat** [comment]
Ok, it is at https://travis-ci.org/github/zim-desktop-wiki/zim-desktop-wiki/ but defunct since travis-ci.org shutdown.

**Comment by pdecat** [comment]
@jaap-karssenberg Would you accept a PR switching from Travis CI to Github Actions? It would provide better integration with Github UI.

**Comment by jaap-karssenberg** [comment]
Yes very much interested in using GitHub actions. Especially if we can also
get test coverage for windows and/or Mac os :)

Op za 25 sep. 2021 10:25 schreef Patrick Decat ***@***.***>:

**Comment by pdecat** [comment]
Submitted https://github.com/zim-desktop-wiki/zim-desktop-wiki/pull/1621 which for now is on par with the former Travis CI build.

Will look into adding more checks later.

**Comment by pdecat** [comment]
Hi @jaap-karssenberg,

tests are now also run Windows and MacOS, but some are failing, see https://github.com/zim-desktop-wiki/zim-desktop-wiki/pull/1621#issuecomment-930123726

**Comment by jaap-karssenberg** [comment]
Hi Patrick,

Thanks for looking into this !  Testing on multiple platforms is going to
be a real quality boost :)

I see errors with file system logic - this is artifact of the test suite.
I'm busy porting all modules to the "newfs" objects. This will not
automatically fix these issues, but let's revisit them once this port is
complete. Tracking via issue #107 .

There is one issue with sorting order, this is likely depending on locale
settings - can those be forced in the test environment ?

There is one issue with MacOs key binding - this should be patched by
making the test case bit more intelligent.

Regards,

Jaap

**Comment by jaap-karssenberg** [comment]
Development branch now running testing via GitHub actions
