### ISSUE TITLE
Toolbar Plugin does not switch off the toolbar at the bottom of the edit window (Windows version 0.74.1)

### ISSUE THREAD

**Issue by fdt-dev** [zim-desktop-wiki/zim-desktop-wiki#1629]
The toolbar plugin allows to place the toolbar at the top, to the left, to the right or to the bottom. Unlike the version of Zim Wiki 0.74.1 running on Linux, the Windows version does not switch off the additional toolbar at the bottom of the edit window. (See attachment)

Expected: Toolbar plugin switches off the additional toolbar at the bottom at the edit window.

![Zim Wiki - Toolbar](https://user-images.githubusercontent.com/35032197/134863789-a6083f19-4835-4245-bce3-a53ae96b7e05.png)

**Comment by fdt-dev** [comment]
I was a bit too hasty in writing this bugreport. It's true that the additional toolbar at the bottom (as seen in my screenshot) will be shown initially. But after switching pages the additional toolbar at the bottom vanishes.

But then the additional toolbar is never really shown again even after disabling the toolbar plugin.

The behaviour is a bit strange.

**Comment by jaap-karssenberg** [comment]
I think things can get out of sync when playing with the settings. But
after restart of the application it should behave again.




Op ma 27 sep. 2021 13:22 schreef fdt-dev ***@***.***>:

**Comment by fdt-dev** [comment]
It's possible. The screenshot was what initially happened, even without playing with the settings.
It's a minor issue.
