### ISSUE TITLE
Sidepane is extremely small and cant resize it on windows

### ISSUE THREAD

**Issue by arkydon** [zim-desktop-wiki/zim-desktop-wiki#1630]
After I updated Zim to 0.74.1 on Windows 10, the interface is changed and the sidebar is so thin that I can't see subpage names anymore. The size is locked and I can't resize it because dragging does nothing except when the program is maximized.

**Comment by jaap-karssenberg** [comment]
Maybe you can add a screenshot. Works fine on my install on windows.

Op ma 27 sep. 2021 15:20 schreef Arky ***@***.***>:

**Comment by arkydon** [comment]
Check out this recorded video

https://user-images.githubusercontent.com/7901865/135438102-edd0c94c-3047-4e16-b741-b1fadd6ae1ba.mp4

**Comment by arkydon** [comment]
Check out this video I recorded.

https://user-images.githubusercontent.com/7901865/135438392-620548a1-a4c9-4a69-9737-c9699aabc747.mp4

**Comment by jaap-karssenberg** [comment]
The reason is that the main editing area is already it's minimum size
(specifically the edit bar along the bottom). If you make the window
bigger, there is more room to make the sidepane bigger.

**Comment by arkydon** [comment]
Oh okay thanks.

> The reason is that the main editing area is already it's minimum size (specifically the edit bar along the bottom). If you make the window bigger, there is more room to make the sidepane bigger.
