### ISSUE TITLE
Toolbar - Plugin: Icons dont execute Scripts

### ISSUE THREAD

**Issue by peterX24** [zim-desktop-wiki/zim-desktop-wiki#1631]
In the new Toolbar Plugin userdefined Scripts are shown, but they cannot be executed -- nothing happens.
Using the Main Menu - Item "Werkzeuge" (Tools) everything works fine.

Using ZIM 0.74.1 under Ubuntu 20.04 LTS.

Any help appreciated

**Comment by borzole** [comment]
I have exactly the same problem.
When I run with --verbose or --debug flag there are no errors. Just like nothing happened ;(

Using: 
Zim 0.74
Fedora 34

**Comment by jaap-karssenberg** [comment]
Stupid error in implementation, my bad, will fix

**Comment by borzole** [comment]
Thank You ! !!
:D

**Comment by peterX24** [comment]
Works great, thanks a lot.
