### ISSUE TITLE
Enable users to control the title bar

### ISSUE THREAD

**Issue by charles-esterbrook** [zim-desktop-wiki/zim-desktop-wiki#1633]
## Title bar template preference

Zim would benefit from a new Interface preference that uses a Python templated string to let the user control the title bar. 

Fields could include:

- page name ("ZimIsGreat")
- page location ("NoteTaking:Applications")
- page path ("NoteTaking:Applications:ZimIsGreat")
- notebook name ("My Life")
- notebook path ("/home/me/Notes/MyLife")

Examples:

- `{notebook name} - Zim`
  - "My Life - Zim"
  - Zim 0.6x style
- `{page path} - {notebook name}`
  - "NoteTaking:Applications:ZimIsGreat - My Life"
  - Zim 0.74 style
- `{notebook name} - {page path}`
  - "My Life - NoteTaking:Applications:ZimIsGreat"
  - for #1339
- `Zim: {notebook name} in {notebook path}`
  - "Zim: My Life in /home/me/Notes/MyLife"
- `Page {page name} in {notebook name} - Zim`
  - "Page ZimIsGreat in My Life"
- etc.

Python's .format() method would be called on the template as in `titleBarTemplateStr.format(**fieldsDict)`, probably with `try:except KeyError:` protection.

## Motivation

When moving form Zim 0.6x to Zim 0.7x, I can no longer efficiently use the Windows 10 taskbar window previews to choose a notebook, due to changes in the title bar. Note that the window previews are shown when left clicking the Zim app icon in the taskbar. Right clicking shows a basic menu ("Zim Desktop Wiki", "Unpin from taskbar", "Close all windows").

You can see the taskbar-triggered window previews in the screenshot at this unrelated superuser issue:
https://superuser.com/questions/1136612/how-to-refresh-windows-10-taskbar-thumbnail-previews

Note that all the title bars are clipped with "...". You can only read the beginning of each title bar. This is key.

Suppose you have multiple Zim notebooks open and their names are:

- Artificial Intelligence
- TechNotes

Then the title bars in Zim 0.6x are:

- Artificial Intelligence - Zim
- TechNotes - Zim

And the Windows 10 window previews will show:

- Artificial Intel...
- TechNotes...

Which is easy to use (meaning choose from) because these are the names of the notebook, or at least their beginnings.

However, in Zim 0.7x, the title bars will start with the _current page name_ which changes quite frequently. Note only can the constant change of the beginning of the title bar make it more difficult to pick the notebook from a list, but two notebooks may have the identical name among the windows previews. Suppose you are looking at the page "Applications" in both notebooks. Then their window title bars are:

- Applications - Artificial Intelligence
- Applications - TechNotes

But the window list shows:

- Applications ...
- Applications ...

... that's _my_ situation. In #1339, another user wants to put the full path of the page in the title bar - after the notebook name. I personally don't want the page name let alone its full path, but I understand that people have different needs which may also vary by window manager. My needs could even change if I move from Windows to Mac or Linux.

**Comment by jaap-karssenberg** [comment]
Open to have this configureable but would like to have it as a "hidden"
preference - or in some kind of "advanced" section of the preferenes
dialog.
