### ISSUE TITLE
Page title heading's formatting lost in html exports

### ISSUE THREAD

**Issue by introt** [zim-desktop-wiki/zim-desktop-wiki#1649]
Though not demonstrated in the example below, this is limited to the page title heading alone and does not affect other headers of the same level.
 
```
====== __t__e[[+subtest|s]]t ======

=== **__M//a[[+subtest|r]]k//ing__** headings ===

Here's some __mark__ action

```

![image](https://user-images.githubusercontent.com/26069787/135651988-62f04b72-0082-429d-a9de-dcbe2bbb3cf0.png)

```html
<!-- Wiki content -->

<div class='pages'>
	<div class='heading'>
	<h1>test <a name='test'></a></h1>
	</div>

	<div class='content'>
	<h4><b><u>M<i>a<a href="/test/subtest.html" title="r" class="page">r</a>k</i>ing</u></b> headings<a id="marking-headings" class="h_anchor"></a></h4>

<br>

<p>
Here's some <u>mark</u> action
</p>
```

Ever-so-slightly related issue: Underlining Headings #71 (just wanted to let @jmoseman01 know they can now underline headings, in case they're running an older version :)

Sidenote: could we have both underline _and_ highlight simultaneously? Even HTML has a separate `<mark>` element nowadays 0:) (Related issue: Deprecated tags in HTML exported document #410 )

**Comment by jaap-karssenberg** [comment]
The title heading is treated differently in the template. Need to be updated to allow nested content as well
