### ISSUE TITLE
"Page not available" error in search

### ISSUE THREAD

**Issue by PierreRust** [zim-desktop-wiki/zim-desktop-wiki#1656]
For some time (probably around 2 or 3 weeks, but I'm not sure with which version it started), when doing a  search in a notebook I get the following error: 
> Page not available: Journal:2017:03
> This page name cannot be used due to a conflicting file in the storage

If running with `--debug`, I get the following trace: 
````
DEBUG: Opening dialog "Search"
INFO: Searching for: test
DEBUG: Running ErrorDialog
DEBUG: Page not available: Journal:2017:03
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/gui/searchdialog.py", line 90, in _search
    self.results_treeview.search(string)
  File "/usr/lib/python3/dist-packages/zim/gui/searchdialog.py", line 176, in search
    self.selection.search(self.query, callback=self._search_callback)
  File "/usr/lib/python3/dist-packages/zim/search.py", line 272, in search
    self.update(self._process_group(query.root, selection, callback))
  File "/usr/lib/python3/dist-packages/zim/search.py", line 370, in _process_group
    results = self._process_content(
  File "/usr/lib/python3/dist-packages/zim/search.py", line 520, in _process_content
    generator = list(map(self.notebook.get_page, self.notebook.pages.walk()))
  File "/usr/lib/python3/dist-packages/zim/notebook/notebook.py", line 454, in get_page
    raise PageNotAvailableError(path, file)
zim.notebook.notebook.PageNotAvailableError: Page not available: Journal:2017:03

This page name cannot be used due to a conflicting file in the storage

ERROR: Page not available: Journal:2017:03

````

If I use the index pane to navigate to that page, I find it but when clicking on it I get a popup:
> File exists, do you want to import ? 
> The File "03.txt" exists but is not a wiki page. Do you want to import it ?

When looking at the file directly, I see that it always happens on file without frontmatter (the section with content-type and other metadatas).

I've tried adding the front-matter manually, for example: 

> Content-Type: text/x-zim-wiki
> Wiki-Format: zim 0.4
> Creation-Date: 2017-03-03T09:30:19+01:00
>
> ====== Friday 03 Mar 2017 ======

This solves the issue for that page, but it appears again on another page and I have no idea how many pages without front-matter this notebook contains (it's more than 5 years old).

From what I understand, the search now bloks when encountering such file, while it did not before.

The solution seems to be: 
* insert the front matter on all file that don't have one. I could write a script to do that but that would only solve the issue for me.
* or make the search (and probably the insert) less sensitive about the front-matter, and probably insert one automatically when it's missing.

What do you think ?

Thanks !

**Comment by jaap-karssenberg** [comment]
Double of #1602
