### ISSUE TITLE
Overwritten data

### ISSUE THREAD

**Issue by SpaceLizards** [zim-desktop-wiki/zim-desktop-wiki#1657]
Installing this program erased an entire folder and it was unrecoverable. Hours and hours of work completely destroyed for nothing. Great job.

**Comment by jaap-karssenberg** [comment]
Sorry to hear things went horribly wrong. Could you add information on what
package/installer version you installed on what platform. What went wrong
exactly ?

Thanks,

Jaap

**Comment by jaap-karssenberg** [comment]
Might be double of #1615

**Comment by jaap-karssenberg** [comment]
Treating as a double of #1615 for now. Please include more information if this is not the case.
