### ISSUE TITLE
Search in Zim 74.1 is Failing to Return Pages When the Search String Contains an Underscore "_"

### ISSUE THREAD

**Issue by tigerbrain** [zim-desktop-wiki/zim-desktop-wiki#1659]
Search is not finding files that contain the exact word with an underscore.  For example, doing a search for "table_name" does not return any results in version 74.1

**Comment by jaap-karssenberg** [comment]
Did a quick test and works for me 

* type "foo_bar" in a page
* search "foo_bar"
* result is one page returned

Any specific circumstances that trigger the issue ? Did you check debug log for errors ?

**Comment by tigerbrain** [comment]
Hi Jaap, my apologies for bugging you with this.  It was user error.  I was searching for TABLE_NAME and was wondering why it wasn't returning anything but forgot to double check that my data is really XX_TABLE_NAME.  So my search string should have been *TABLE_NAME in order for search to return the result.
