### ISSUE TITLE
Zim 0.74.2 - GoTo Function does not list all possible entries

### ISSUE THREAD

**Issue by fdt-dev** [zim-desktop-wiki/zim-desktop-wiki#1688]
**Describe the bug**
Zim 0.74.2: The Goto function does no list all possible entries upon typing. For instance I have got 20 entries starting with the substring 'KW'. Upon typing 'kw' it only lists the first 19 entries. It doesn't seem like it is limited to 19 entries, because it lists another entry that has the substring 'kw' within the name.

**To Reproduce**
1. Press Ctrl-J
2. start entering part of a page name
3. See error: list isn't complete (assuming you have similar scenario than me)

**Expected behavior**
Pick-list should display all possible pages.

**Environment (please complete the following information):**
 - Version 0.74.2 
 - OS: Linux Ubuntu 20.04 LTS
 - Language: German

**Comment by jaap-karssenberg** [comment]
Could you help with a test set to reproduce this? E.g. list of page names where you observe this might be helpful to test completion logic.

**Comment by fdt-dev** [comment]
I will try. Would a complete Zim notebook be helpful? I would then create one for this purpose, put it in a zip archive and upload it here. Might take a day or two, though, since my time is a little limited.

**Comment by jaap-karssenberg** [comment]
Sure that would be ideal. No hurry, can't promise I can directly look at it
either. December is a busy month.



Op di 30 nov. 2021 22:23 schreef fdt-dev ***@***.***>:

**Comment by fdt-dev** [comment]
Hello Jaap,
I think the attached Wiki should illustrate the issue:
[Notes.zip](https://github.com/zim-desktop-wiki/zim-desktop-wiki/files/7719336/Notes.zip)

1. open this Wiki
2. re-index
3. select Ctrl-J
4. enter '2'
5. Zim only lists 20 entries for the quick-selection drowdown thing (can't produce a screenshot of that), but there are more than 20 entries which contain a '2' in their name.

This behaviour could be desired, I'm not sure. It's up to you to make a decision.

**Comment by jaap-karssenberg** [comment]
Yes, this is a hard limit that is coded to ensure the completion goes fast enough if you just type a single character for large notebooks. 

My assumption is that you are not going to hunt down a very long list in a dropdown menu but instead type more characters to narrow down the list. Otherwise the search function can help you to find what you are looking for (e.g. using the `name:` keyword)
