### ISSUE TITLE
Cannot drag pages in Index

### ISSUE THREAD

**Issue by aloboa** [zim-desktop-wiki/zim-desktop-wiki#1698]
**Describe the bug**
Cannot drag pages to another place or to make it a subpage in Index

**To Reproduce**
1. Go to Index
2. Click on any page
3. Try to drag it to another position in the index
4. No movement

**Expected behavior**
The page should move to another position in the Index

**Screenshots**
NA

**Environment (please complete the following information):**
 - Version 0.74.2
 - OS: linux ubuntu-based 21.04
 - Language: english

**Comment by Nick222** [comment]
There are option in plugin config...
