### ISSUE TITLE
Sort lines plugin: line moving out of the visible area without scrolling

### ISSUE THREAD

**Issue by Pseudavid** [zim-desktop-wiki/zim-desktop-wiki#1713]
If I use Ctrl+Arrow to move a line up and down (sort lines plugin feature) and the line moves out of the visible area of the page, the window doesn't scroll following the line.

1. Enable the sort lines plugin
2. Open a page with long text that needs scrolling
3. Press Ctrl+ArrowDown to move a line to the bottom, until it goes beyond the visible area, and keep pressing the keys
4. The line keeps moving down, but it's invisible, because there is no scroll.

**Expected behavior**
The window should scroll to keep the line you're moving visible at all times. That was the behaviour before the September 2021 update.

**Environment (please complete the following information):**
 - Version 0.74.2
 - OS: Linux, Windows

**Comment by vossenjp** [comment]
Just grabbed the PPA build 0.74.2-t202110301214~ubuntu18.04.1 and this is much better!
