### ISSUE TITLE
Prevent hashtag usage from automatically becoming anchor links

### ISSUE THREAD

**Issue by borisjoffe** [zim-desktop-wiki/zim-desktop-wiki#1716]
I saw the the anchor links feature make it into Zim which I think is great:
https://github.com/zim-desktop-wiki/zim-desktop-wiki/pull/1293

However, I use hashtags pretty often to organize my notebook content e.g. `#workProject1`. It's really useful for marking content for quick searching, and I picked up this habit from a previous organization I worked for where this was commonly done.

I don't use zim tags with "@" since that's commonly used to tag people's usernames or specify times or locations. I also don't need or use any zim-specific "@" tag functionality

**Problem**
When I type in a hashtag starting with the pound sign, it automatically gets converted to an anchor tag, which is not what I want, and really breaks up my workflow.

**Current workaround**
I either have to select the hashtag, press Ctrl-9 to clear the formatting (and then re-apply bold or other formatting that I used), or I have to add a space after the pound sign, write the "tag name" I want, press space, then go back and delete the space between the pound sign and the tag name. This is a very long process, and since I use hashtags often, eats up a lot of time.

Hashtags are very common in social media, news, and pop culture, so I think other users would also experience this as well.

**Describe the solution you'd like**
I'm open to solutions. A simple one would be to change the automatic anchor insertion to occur after the insertion of two hashtags instead of one.

**Describe alternatives you've considered**
Some other options are a toggle in the Preferences or a plugin that does automatic anchor insertion.

**Additional context**
I'm using Zim 0.74.2

**Comment by jaap-karssenberg** [comment]
Need to think about this. One bit that might help if that control-z should
also undo the automatic formatting

Op ma 1 nov. 2021 06:24 schreef Boris Joffe ***@***.***>:

**Comment by vossenjp** [comment]
+1 for this for similar reasons.  Our ticket system uses #NNNN, so now when I want to reference a ticket I get this.  I'm doing the highlight, CTRL-9, CTRL-T (for code) for it, but that is a little tedious.

**Comment by lorenrosen** [comment]
Maybe use backslash as an escape character, that is, \#something would not be an anchor?

**Comment by fdt-dev** [comment]
Or better still: Maybe it'd be a good idea to use a double hash symbol for the Zim anchor links (like that: ##anchor). If something has a different meaning in a different context, it might be advisable not to use it at all but rather something else.
(The same would go for the @ tags; but that's unfortunately too late for a correction now.)

Funnily enough I also use Zim to keep track on support tickets as ticketing systems seem to be terribly designed in that regard. For me it is the second ticket system where I have to do that, because it is nearly impossible to find support calls again otherwise. Maybe @jaap-karssenberg  should design a ticket system; that'd be so much better than anything else.

**Comment by ZtzEAcRsND** [comment]
Consider using  a key sequence of ```[[#``` to identify markup for an  anchor link *to be formatted*.  e.g., after entering ```[[#<anchor_text><rtn>``` or ```[[#<anchor_text><space>```, the closing ```]]``` is added automatically to create the anchor link.  Entering  ```#<text>``` is not special markup to be auto formatted..

Using a 3 character key sequence ```[[#``` is consistent with the zim approach (from zim help): ```All markup uses at least two characters to reduce the chance of conflicts between the wiki markup (and) normal typographic use of these characters.``` and ```Type wiki syntax to format on the fly```.

The option to 'auto format wiki syntax' an anchor text ```[[#``` could be included with the option ``` "Reformat wiki format on the fly" in the preferences to enable this feature.```

The approach could also be used to identify the beginning of a page link reference as in ```[[<page link text>``` .

**Comment by borisjoffe** [comment]
@jaap-karssenberg Thank you for the Ctrl-Z tip - it's definitely a better stopgap solution than what I was using.

I also noticed that single letter hashtags like `#a` don't automatically create anchors (but I tend to avoid those to make my tags unique when searching for them).

I still think that using something like a double hash `##` or some of the other suggestions in this thread - `\#` or `[[#` would be a better long term solution. Or at least having a configuration option (although that would probably require more development work and maintenance)

A double hash is probably the best way since it's very quick to type for people that want an anchor link, while also rarely occurring in regular text (minimizing conflicts).

**Comment by jaap-karssenberg** [comment]
In the patch linked above I added options in the preferences dialog to control whether "#name" is turned into a link or not.
