### ISSUE TITLE
[sourceview] Export to markdown using fenced code blocks

### ISSUE THREAD

**Issue by sanjarcode** [zim-desktop-wiki/zim-desktop-wiki#1718]
**Describe the bug**
Exporting notebook to markdown ignores the existing codeblocks.
Codeblocks are not found in the resulting markdown files.
Instead, only spaces and tabs are found.

**To Reproduce**
1. Select Insert -> code block.
2. Write something in the codeblock.
3. Export the notebook.
4. See the corresponding markdown file, "```" cannot be found!

**Expected behavior**
Codeblock _with_ language in exported files, that's what I expected.

**Environment:**
 - Version 0.74.2
 - OS: linux (ubuntu 20.04)
 - Language: English

**Comment by jaap-karssenberg** [comment]
In the test suite we test for markdown export of a code block. The code block content is exported as an indented block in markdown, which is the default way to represent code blocks. You are looking for a "fenced" code block, which isn't necessary for proper markdown.

Although it would be a good improvement to export code blocks as fenced code blocks and also include info on the language. 
See https://github.github.com/gfm/#fenced-code-blocks

**Comment by sanjarcode** [comment]
Hi @jaap-karssenberg, can I know the files to edit/add code to make the necessary changes.
As seen in #483, it'd be good to add a template called 'GitHub markdown', how do I add this?

**Comment by jaap-karssenberg** [comment]
To add a different output format, you copy and modify `zim/formats/markdown.py` if you only make subtle changes to the format, you can also make it a switch via "template_options", this allows to give input options from the template to the serialization code. See `DumperClass` in `zim/formats/__init__.py` for notes on how to use this, or see `zim/formats/html.py` for an example.

Specific for adding fenced code blocks with syntax hints, it is good to realize that the sourceview objects are defined in a plugin `zim/plugins/sourceview.py`. So the default markdown code does not know about them. You can modify the way these objects are serialized by adding a `format_markdown()` method in the `SourceViewObjectType` class. See the `format_html()` method as an example.

Hope this helps,

Jaap
