### ISSUE TITLE
Settings Option to Generally Accommodate Dark Themes

### ISSUE THREAD

**Issue by wattahay** [zim-desktop-wiki/zim-desktop-wiki#1727]
(Alternatively, include a second style file that can replace the default)

### Problem

Users become rapped up in tweaking colors to **get the out-of-the-box features**.

There are various issues with dark theming outside of adopting the system theme. While these can be changed manually, **adoption of dark themes has become very widespread**, and a simple option would provide a great level of convenience cumulatively.

- Link text is too dark, as to blend into the background
- Verbatim text is too dark, as to blend into the background
- Highlighted text is too light, as compared to the system theme's light text
- [Maybe] Horizontal lines and table lines? (not problems for me personally)
- [Maybe] Icons as well? (not problems for me personally

### Related Open issues:

- https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/1404
- https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/1178
- https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/1003
- https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/681
- https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/132

### Solution 1
GUI Dark Theme option to swap style file

### Solution 2
GUI Dark Theme option to swap style file _and_ icons

### Solution 3
Provide alternate style file with dark system themes in mind

**Comment by jaap-karssenberg** [comment]
There is a generic Gtk option to switch to a dark version of the default
theme. We could expose an option in the preferences UI that uses that.

I also support the idea of shipping multiple style configs. To implement
this, the file would need to contain a key with it's name (translatable,
like names in .desktop files) and the preferences could show a dropdown of
the files found.

To address the icons, we could also ship multiple icon sets. In this case I
would prefer the style config file to contain the name / path of the icons
to be used, so you have a single style selection for both font colors and
icons.

-- Jaap

**Comment by manuel-91** [comment]
I would be happy to see a dark mode for zim. However not too many people seem to need it...

The Link text is barely visible, especially on older/darker/cheaper monitors or in nightmode. Can we just set the Link color to this light blue? That would be a quickfix (with much less effort) for those who use a dark system theme... here the comparison of the Help->About menue (light blue) and the dark blue (normal note link):

![image](https://user-images.githubusercontent.com/45081089/159159749-7cfb6aae-d251-4186-ae96-c27b940fe20b.png)

In light mode it look like this:

![image](https://user-images.githubusercontent.com/45081089/159159815-c9427a4b-c117-4ea1-819d-8801fc979a4a.png)

**Comment by felixx9** [comment]
would be great to have dark mode running out-of-box.

E.g. his shows ZIM in manjaro gnome dark mode:

![Screenshot from 2022-09-28 09-11-21](https://user-images.githubusercontent.com/51174875/192713846-9b52d03f-5b33-425e-999f-f859cbb150fa.png)

**Comment by clarfonthey** [comment]
One thing I feel is important to mention is that GTK 3 actually has a link colour by default, and at least for links, we could use this colour instead of relying on having to set it per-theme.

**Comment by jaap-karssenberg** [comment]
Is there a way to query that color from the Gtk API? If so, we could use it
as a default unless overruled from the styles.conf config.

--- Jaap

**Comment by clarfonthey** [comment]
I'm not 100% sure if there's a standard API for it, but my general impression is that you can just include standard `<a>` tags in the markup and they will default to being the right colour. I don't know how zim is currently handling links, or if there's some API to query the CSS directly.

**Comment by jaap-karssenberg** [comment]
Yes, this is true for markup used in labels, but the text view in the
editor does not use this markup interface. The API is more low level, so we
need to know the color code directly.

Op vr 30 jun. 2023 21:40 schreef Clar Fon ***@***.***>:

**Comment by clarfonthey** [comment]
Ah, in that case I would have to do a little more digging. Based on my limited research, it seems that a lot of the issues regarding link styling were put aside to make way for GTK 4, which means there may be a chance this just isn't possible without an upgrade, which is obviously way more work. Will reply if I find out otherwise though.

**Comment by directentis1** [comment]
Is there a list of themes options suitable for Zim in dark variant?
 It's difficult to try each one... and keep skipping the ones where the colors are really bad if the link, code, mark format is in darkmode.

**Comment by LSeelig** [comment]
>     * Verbatim text is too dark, as to blend into the background
I am experiencing this as well. While there is a suggestion here to use style.conf, I think this would affect my light mode as well?

My theme switches every day at sunset, so being able to set a separate style to use when my dark theme is enabled, or proper dark mode accommodation, would be appreciated.

**Comment by dehesselle** [comment]
My suggestion would be to try out different themes from https://www.gnome-look.org/browse/ and see if there is something suitable there for dark mode. If not, use an existing theme as starting point and modify it. Once satisfied, we can start talking about shipping it with Zim.

**Comment by jaap-karssenberg** [comment]
Willing to look into a way to switch colors in zim - either manual in
settings, or follow Gtk dark mode.

Could someone come up with a modified "style.conf" version that works well
with standard dark mode themes ?
We could offer multple pre-defined choices of the config file.

Thanks,

Jaap

**Comment by bruvellu** [comment]
Here are the light and dark `style.conf` that I use: https://github.com/bruvellu/zim-styles

![zim-tomorrow-preview](https://github.com/zim-desktop-wiki/zim-desktop-wiki/assets/361179/14e1e769-5fdf-4934-8d4c-deff549994d7)

They are based on the [Tomorrow Theme](https://github.com/chriskempson/tomorrow-theme).

**Comment by jaap-karssenberg** [comment]
Just merged support to toggle dark theme variant from zim. I've also added syntax to the 'style.conf' to allow specifying in one file both the regular and dark theme version of the colors.

@bruvellu afraid I did not check your proposed style config, that would be an additional patch on top of this one - but you did trigger me in "kicking the ball forward" on this topic - feel free to open a PR with style changes

**Comment by LSeelig** [comment]
> Just merged support to toggle dark theme variant from zim. I've also added syntax to the 'style.conf' to allow specifying in one file both the regular and dark theme version of the colors.
> 
> @bruvellu afraid I did not check your proposed style config, that would be an additional patch on top of this one - but you did trigger me in "kicking the ball forward" on this topic - feel free to open a PR with style changes

My system auto-switches from light to dark mode. GTK3 theme is switched to the adw-gtk3-dark variant. Is there any way to only use the dark variant when system theme is dark?

**Comment by dehesselle** [comment]
> My system auto-switches from light to dark mode. GTK3 theme is switched to the adw-gtk3-dark variant. Is there any way to only use the dark variant when system theme is dark?

I don't understand. Your system automatically switches from light to dark mode. Your GTK3 theme switches to dark. So you are already using a dark variant when your system is dark. Did you mean to say to say "only use dark variant regardless of the system setting"?

**Comment by LSeelig** [comment]
> > My system auto-switches from light to dark mode. GTK3 theme is switched to the adw-gtk3-dark variant. Is there any way to only use the dark variant when system theme is dark?
> 
> I don't understand. Your system automatically switches from light to dark mode. Your GTK3 theme switches to dark. So you are already using a dark variant when your system is dark. Did you mean to say to say "only use dark variant regardless of the system setting"?

Currently, when my system switches to dark theme, all apps switch, but Zim's text breaks. Some elements, like monospaced/code blocks, are illegible on the dark background. I was under the impression that this is what the pull request fixes. It provides a text color theme that appears on a dark background.

No. I am asking if Zim's new dark theme text support will automatically apply when my system switches Zim's interface to a dark theme.  I am sorry if I am not being clear.

**Comment by jaap-karssenberg** [comment]
Not automatically, but if you turn on the new preference it will work
together.

Regards,

Jaap

Op ma 18 mrt. 2024 22:34 schreef Lee ***@***.***>:

**Comment by bruvellu** [comment]
> @bruvellu afraid I did not check your proposed style config, that would be an additional patch on top of this one - but you did trigger me in "kicking the ball forward" on this topic - feel free to open a PR with style changes

Hi @jaap-karssenberg, do you mean opening a PR replacing the default colors in `style.conf` with the ones above?

**Comment by jaap-karssenberg** [comment]
@bruvellu yes, there might be some fine tuning needed to make the darkmode colors work. These are now defined directly in the standard `style.conf`. So far I adhere to the "Tango" palette to blend in with the default color theme across operating systems - bit there is freedom which shades to use for which elements.

Alternative would be to e.g. put alternative style configurations somewhere else - e.g. on the wiki ? So users can download them if they want a more specific look.

**Comment by directentis1** [comment]
Any suggestions on which GTK Themes are best suited to Zim-wiki?
 I'm not sure if there is a better way than trial and error?

**Comment by jaap-karssenberg** [comment]
I'm just using the default theme on both windows an Ubuntu. Both light and
dark work fine with the development version that implements dark theme for
the zim style config.

Op wo 22 mei 2024 12:43 schreef directentis1 ***@***.***>:

**Comment by directentis1** [comment]
> I'm just using the default theme on both windows an Ubuntu. Both light and dark work fine with the development version that implements dark theme for the zim style config. Op wo 22 mei 2024 12:43 schreef directentis1 ***@***.***>:


I get it.. Because I installed many different themes, not all of them are compatible with Zim.
 Choosing the right color palette for the interface is a subjective feeling, but based on certain criteria it will be better.
