### ISSUE TITLE
Ctrl + backspace won't erase non-word characters that begin lines

### ISSUE THREAD

**Issue by introt** [zim-desktop-wiki/zim-desktop-wiki#1738]
**Describe the bug**
If a line begins with non-word characters (indentation included), Ctrl + backspace won't erase them. Adding a letter between the non-word characters makes Ctrl + backspace erase everything up to where the letter once was.

**To Reproduce**
1. Begin a line with `~/hello/world/`
2. Hold down Ctrl
3. Repeatedly press backspace
4. The `~/` persist

**Expected behavior**
Non-word characters would get erased. With word characters, Ctrl + backspace even removes all whitespace; here, pressing Ctrl + backspace erases the whole of `\tasdf\n` at once:

```
	asdf
|

```
**Screenshots**
> ~#|

**Environment (please complete the following information):**
 - Version 0.74.2
 - OS: Linux
 - Language: en_US.UTF-8

**Comment by jaap-karssenberg** [comment]
I believe this is GTK generic key binding, not Zim specific.

Op wo 10 nov. 2021 12:40 schreef introt ***@***.***>:

**Comment by ZtzEAcRsND** [comment]
@introt Thanks! I'd forgotten about the `<ctrl><bkspace>` shortcut/binding. 

I can't duplicate the not deleting `~/` non-word characters at line beginnings (they get deleted).  I can duplicate the same behavior in other GTK apps such as libreoffice, ghostwriter, gedit, mousepad, and thunderbird (and firefox with this GFM comment box) under Windows 10 and ubuntu 21.04. 

However--Maybe this is your bug?-- between the GTK apps there are differences in which characters are considered 'white space' or word boundaries. Zim seems to be the most aggressive in that it seems all non-printable characters and usually all non-word characters are considered white space (e.g., repeated lines with non-printable characters or non-word characters are all deleted with one `<ctrl><backspace>`, which is fine by me).  Other GTK apps vary on what is white space (e.g., a new line is a new word boundary).   Zim seems consistent regarding which printable non-word characters are considered words or word boundaries.

**Comment by introt** [comment]
Closing due to no longer being able to reproduce - weird that it didn't affect other GTK apps (eg. Mousepad) but glad it's gone.
