### ISSUE TITLE
Notebook editable toggle state is not stored on exit

### ISSUE THREAD

**Issue by VandaloftheVoid** [zim-desktop-wiki/zim-desktop-wiki#1739]
New behavior in 0.74.2 is that setting Read Only in the View menu and then saving the file doesn't carry over to the next session. That is to say, I set a notebook to be Read Only and save it. I close the notebook and reopen it. It is no longer Read Only. In previous versions reopening the notebook present the notebook still as Read Only. This is handy when using one set of notebooks as references or templates from which to copy and paste data into editable notebooks.

**To Reproduce**
1. Set notebook as Read Only.
2. Close notebook.
3. Reopen notebook.
4. Notebook is editable instead of being Read Only.

**Expected behavior**
Status of notebook would, ideally, be unchanged from Read Only.

**Screenshots**

**Environment (please complete the following information):**
 - Version 0.74.2 in Devuan Daedalus/Ceres, GNU/Linux 5.14.0-4-amd64 #1 SMP Debian 5.14.16-1 (2021-11-03) x86_64 GNU/Linux
 - Language: EN-US

**Additional context**
Also seen in Void GNU/Linux.

No obvious (to me) errors in zim -D output in terminal.

**Comment by jaap-karssenberg** [comment]
Confirm - notebook editable state is not stored correctly on exit

**Comment by VandaloftheVoid** [comment]
Thank you for confirming that this was not intended behavior.

Zim is far-and-away the most useful and versatile of the applications I have ever used. It has been my mainstay application for, I guess, a couple of decades? Your work is appreciated!
