### ISSUE TITLE
Wrong icon in filemanager

### ISSUE THREAD

**Issue by helge42** [zim-desktop-wiki/zim-desktop-wiki#1743]
**Describe the bug**
Filemanager shows for notebook.zim an icon with blank page

Icon Theme: Adwaita (the default of gnome)

If I change to e.g. the icon theme breeze, the right icon is shown.

**To Reproduce**
1. see above
2. 
**Expected behavior**
The default icon should be shown in every theme.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/19750682/141798829-f0ba4a35-ab55-4b0c-b0bb-5bac28e0d195.png)

**Environment (please complete the following information):**
 - every Version
 - OS: System Debian 11, gnome, X11

**Comment by jaap-karssenberg** [comment]
Not sure this is an issue with zim itself. We install the icon in "hicolor", which is the fallback for all icon themes. Seems like either Adwaita does not use hicolor, or it is overruled somehow. In my own testing on Ubuntu I cannot confirm the issue.

**Comment by helge42** [comment]
Yes, you are right. It is a [problem by adwaita](https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/issues/108).
