### ISSUE TITLE
How to manage homebrew package of Zim (that works on M1s)

### ISSUE THREAD

**Issue by reagle** [zim-desktop-wiki/zim-desktop-wiki#1746]
@dehesselle is kindly providing an "official" [MacOS DMG file](https://zim-wiki.org/downloads.html) for zim, which works with M1 Macs. As discussed in #1712, he will not be providing a homebrew package. Questions:

1. What should be done with the [existing brew](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/zim.rb)? I assume it still works well for folks on x86, but it will frustrate and confuse M1 users. I suggest it be removed and we create a binary cask instead using the officially released DMG file.
2. Who "owns" the existing brew? Can we delete it in favor of a cask?
3. Does anyone have experience [creating a cask](https://nicedoc.io/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md)? It *looks* straightforward, and I've used `bump-cask-pr` to request version updates to existing casks, but am otherwise a newbie.

**Comment by dehesselle** [comment]
If creating a cask is rather simple, that is something I can look into, but it's not my top priority TBH. I guess once a cask is created (sorry can't look at it myself right now), keeping it updated is a matter of changing a link, a version number and a checksum - basically low maintenance.

My concern lies with questions/issues like "xyz doesn't work with my non-cask installation of Zim from Homebrew", which are beyond my scope/capacity.

**Comment by reagle** [comment]
Yes, changing a cask is done via a simple command:

    brew bump-cask-pr --version <new_version> <outdated_cask>

I've done that before for packages/casks I have nothing to do with as it is largely automated.

**Comment by jaap-karssenberg** [comment]
Sorry, but I'm converting this to a discussions. Discussions belong in the forum, not in the issue tracker.
