### ISSUE TITLE
Error while attempting to create a subpage.

### ISSUE THREAD

**Issue by tscahill** [zim-desktop-wiki/zim-desktop-wiki#1760]
![image](https://user-images.githubusercontent.com/92868777/142945978-c82c4603-9c81-4c01-9e73-6b38cf25647a.png)

**Comment by tscahill** [comment]
Somehow adding the screenshot resulted in blowing away the supporting text. I've lost most of the details now.
4 steps involved. 
1. Attempted to save a subpage. Clicked "OK". 
2. 2 The error "Could not save page: "....." appeared. 
3. I attempted to save a copy. That caused a detailed error message to appear that I took the trouble to transcribe, but cannot now remember. 
4. Attempting to save the page visible in the backround of the screen shot caused a final error message about not being able to create a lock file because it was there already, and git was at fault. Sorry I can't provide more than that, but if it happens again I'll just screen shot those errors and append them to this error report.

**Comment by tscahill** [comment]
I can now reproduce the error by copying the following text (this was the last edit to that page, which was lost) at the bottom of the page:

78. Kay, Canada and Palestine, 152 
79. Bercuson, Canada and the Birth of Israel, 209 
80. Heinbecker, Canada and the Middle East, 12 
81. Hilāl, Canadian Foreign Policy and the Palestine Problem, 13 
82. Hull, The Fall and Rise of Israel, 383 
83. Kay, Canada and Palestine, 2 
84. Kay, Canada and Palestine, 160 
85. Tauber, Personal Policy Making, 84 
86. Stursberg, Lester Pearson and the American dilemma, X 
87. Pearson, Four Faces of Peace, 23 
88. Abella, None is Too Many, 205 
89. Abella, None is Too Many, 136 
90. Tauber, Personal Policy Making, 85 
91. Anderson, Pearson and the myth of neutrality, Toronto Star Nov 5 2006 
92. Tauber, Personal Policy Making, 81 
93. Tauber, Personal Policy Making, 30 
94. Tauber, Personal Policy Making, 30 
95. Taras, The Domestic Battleground, 31/137 
96. Bristman, In the Strategic Interests of Canada, 52 
97. Bristman, In the Strategic Interests of Canada, 52 
98. Pearson, Memoirs 2, 219  Chapter 3

**Comment by tscahill** [comment]
Yup. Created a new notebook. Pasted the above text into the home page. Threw the same initial error. Attempted to save a copy of the file, It produced the second error: 
"   This is zim 0.74.2
Platform: posix
Locale: en_CA UTF-8
FS encoding: utf-8
Python: (3, 9, 7, 'final', 0)
PyGObject: (3, 42, 0)

======= Traceback =======
  File "/usr/lib/python3.9/site-packages/zim/gui/widgets.py", line 3086, in do_response
    destroy = self.do_response_ok()
  File "/usr/lib/python3.9/site-packages/zim/gui/uiactions.py", line 576, in do_response_ok
    lines = self.page.dump(format)
  File "/usr/lib/python3.9/site-packages/zim/notebook/page.py", line 728, in dump
    tree = self.get_parsetree()
  File "/usr/lib/python3.9/site-packages/zim/notebook/page.py", line 599, in get_parsetree
    self._parsetree = self._textbuffer.get_parsetree()
  File "/usr/lib/python3.9/site-packages/zim/gui/pageview/__init__.py", line 2937, in get_parsetree
    tree = parser.parse(text, partial=tree.ispartial)
  File "/usr/lib/python3.9/site-packages/zim/formats/wiki.py", line 654, in parse
    mywikiparser(builder, input)
  File "/usr/lib/python3.9/site-packages/zim/formats/wiki.py", line 201, in __call__
    self.block_parser(builder, text)
  File "/usr/lib/python3.9/site-packages/zim/parser.py", line 452, in __call__
    self._raise_exception(error, text, iter, end, builder)
  File "/usr/lib/python3.9/site-packages/zim/parser.py", line 450, in __call__
    self.process_unmatched(builder, text[iter:])
  File "/usr/lib/python3.9/site-packages/zim/formats/wiki.py", line 480, in parse_para
    self.list_and_indent_parser(builder, block)
  File "/usr/lib/python3.9/site-packages/zim/parser.py", line 442, in __call__
    self._raise_exception(error, text, mstart, mend, builder, self.rules[i])
  File "/usr/lib/python3.9/site-packages/zim/parser.py", line 464, in _raise_exception
    error = ParserError(error.message)
AttributeError: 'AssertionError' object has no attribute 'message'
"

**Comment by tscahill** [comment]
Just rebooted. Opened the new notebook. Pasted the same text in. Same error when trying to save the page.

**Comment by tscahill** [comment]
Pasting other text doesn't cause the error.

**Comment by tscahill** [comment]
Zim didn't try to blame git this time. I guess they made up.

**Comment by dehesselle** [comment]
Please STOP creating new posts, use the "edit" function!

**Comment by tscahill** [comment]
Sorry if I've offended. I lost a great deal of issue reporting text using this interface, and I wasn't ready to risk loosing it all over again. Thanks for your rapid response to the truely important.

**Comment by dehesselle** [comment]
> Thanks for your rapid response to the truely important.
Maintainers do get emails for every single post. So yes, it is important that we don't get dozens of emails for what is essentially one single issue report.

**Comment by jaap-karssenberg** [comment]
I can confirm the bug. The issue is caused by the presence of this unicode character in the last line: https://codepoints.net/U+2029?lang=en

This character is seen as end-of-line by `text.splitlines()` but is not matching end-of-line in regex parsing.
