### ISSUE TITLE
keyboard shortcut for selecting currently shown page in PageIndex

### ISSUE THREAD

**Issue by mtill** [zim-desktop-wiki/zim-desktop-wiki#1775]
I would propose to add some keyboard shortcut for selecting the currently opened page in the PageIndex.
This would be quite useful if the option "Automatically expand sections on open page" is deactivated.

![image](https://user-images.githubusercontent.com/5305673/144701752-1a936450-76d6-4854-a0f5-ad0173287ee3.png)

**Comment by introt** [comment]
Fixed by [5e74986](https://github.com/zim-desktop-wiki/zim-desktop-wiki/commit/5e74986fbf8411ae55629bd052d8264449c89a51)
