### ISSUE TITLE
Add drag'n' drop to tag side pane too

### ISSUE THREAD

**Issue by sojusnik** [zim-desktop-wiki/zim-desktop-wiki#1781]
While the index side pane (page index) has a setting to enable/disable to drag'n'drop pages, the tag side pane is missing this setting. Would be great if you could add it there as well, for obvious reasons!

**Comment by sojusnik** [comment]
Can somebody confirm that drag'n'drop pages is working with the tag side pane? It's working with the normal page index side pane at the moment, but not with the tag pane.

Using `0.74.3-SNAPSHOT-t202202171846~ubuntu21.10.1`

**Comment by jaap-karssenberg** [comment]
There is no drag&drop supprot in the tag index. Moving pages there would potentially require changing tags in the text, so not supported.

**Comment by sojusnik** [comment]
@jaap-karssenberg

The tag index pane allows **not** to sort pages by tags and in this case you'll see the same structure of pages, as in the default page index pane. So I don't want to change tags on pages by drag'n'dropping them, but only the position of pages, like it's done in the page index pane.

Drag'n'drop in the tag index pane was already possible before an update long ago, so this issue seems to be an easily fixable bug.

**Comment by sojusnik** [comment]
@jaap-karssenberg

For clarification: the first picture shows the tag index pane (with deactivated "sort pages by tags" in the context menu of the tag index pane) with the same page structure, as the second picture, which shows the page index pane (which usually serves as the default navigation bar in Zim). While it's possible to drag'n'drop pages in the latter, it's still not possible to do it in the former, although they have the identical page structure and function.

tag index:
![grafik](https://user-images.githubusercontent.com/1245718/211776846-84f68f2a-06f7-4593-b620-c016af41c986.png)

page index:
![grafik](https://user-images.githubusercontent.com/1245718/211776966-d785d907-089f-447a-aded-88cc044c1f3d.png)
