### ISSUE TITLE
AssertionError: Failed to start server (spawning)

### ISSUE THREAD

**Issue by stillconfused1** [zim-desktop-wiki/zim-desktop-wiki#1789]
After rebooting my desktop PC (i7-4790, 12GB RAM, 1TB HDD, Windows Home 64-bit 21H1 19043.1348), I attempted to launch Zim 0.65 from its taskbar icon, and got the "Looks like you found a bug" window with the following contents, see below.  This is the first time Zim has raised an exception on launch, for me.

Full disclosure: prior to booting, I ran sfc /scannow to fix integrity violations, and ran diskpart to remove the active flag from a connected external USB HDD.  Zim is installed on C:, the internal HDD (boot drive).  There are no Zim notebooks or other files used by Zim on the connected external USB HDD.

**Edit**: When the error occurred, I was attempting to launch Zim from the Windows taskbar, just after the desktop appeared, and the taskbar had been populated.  My windows desktop is not always responsive at this point in the boot process.  After submitting this bug report, I was able to launch Zim, without issue.

from the Zim error window:
```
This is zim 0.65
Platform: nt
Locale: en_US cp1252
FS encoding: mbcs
Python: (2, 7, 11, 'final', 0)
Gtk: (2, 24, 10)
Pygtk: (2, 24, 0)
Zim revision is:
  branch: 065
  revision: 805 jaap.karssenberg@gmail.com-20151101144245-0g7s8a7qjt5xu1d0
  date: 2015-11-01 15:42:45 +0100

======= Traceback =======
  File "zim\main.pyo", line 446, in main
  File "zim\main.pyo", line 211, in run
  File "zim\ipc.pyo", line 283, in start_server_if_not_running
AssertionError: Failed to start server (spawning)
```

**Comment by dehesselle** [comment]
Do I understand you correctly: while that error just happened out of the blue, it happened once and everything is fine again right now? With a really ancient version of Zim?

I'm sorry to say, but there's nothing we can do about that. Consider updating Zim.

**Comment by jaap-karssenberg** [comment]
Agree, anything before 0.70 is won't fix by default.
