### ISSUE TITLE
[Mac OS] automatic tests fail with segfault for Mac OS

### ISSUE THREAD

**Issue by jaap-karssenberg** [zim-desktop-wiki/zim-desktop-wiki#1797]
Automatic test suite as run on Github fails with segfault for Mac OS. Failure started after merging from master branch. See https://github.com/zim-desktop-wiki/zim-desktop-wiki/actions

Would need confirmation of offline run of the test suite on Mac OS and a `git bisect` to determine the change that causes this.

For info: a segfault is by default a bug in a lower level library or in the interpreter, not an issue raised within python. Therefore it is hard to troubleshoot. Hopefully the bisect narrows done the piece of code triggering it and might suggest a work around to avoid this.

**Comment by dehesselle** [comment]
I've run the test suite a couple of times and I'm not getting a segmentation fault.

```plaintext
Ran 896 tests in 67.033s

FAILED (failures=49, errors=3, skipped=24, expected failures=21)
```

**Comment by jaap-karssenberg** [comment]
Hmm, than it is specific for the GitHub environment - will be hard to
troubleshoot :(

**Comment by dehesselle** [comment]
My current take on the situation: cannot promise a timeframe, but I'll make something from my CI reusable for GitHub so we can have automatic tests.
