### ISSUE TITLE
Pathbar Can Show Portions of Page Hierarchy Twice

### ISSUE THREAD

**Issue by VandaloftheVoid** [zim-desktop-wiki/zim-desktop-wiki#1804]
Description:

In the Journal, apparently, for 1 day each month on the date where month and day are the same number, the pathbar can show the following:

Journal - "year" - "year":"month" - "month":"day"

instead of the expected

Journal - "year" - "month" - "day"

To reproduce:

1. Set Pathbar to show Page Hierarchy (in the Journal).
2.  Go to the day of the month that has the same number as the month, i.e. December twelfth.
3. Observe the Pathbar.

**Screenshots**

**Environment (please complete the following information):**
 - Version 74.2
 - OS: Void Gnu/Linux fully up-to-date.
 - Xfce4 DE/DM
 - Language: EN-US

**Additional context**
Have not seen similar issues with Page Hierarchy display outside of Journal, but have not attempted to find a way to duplicate the behavior there.

Screenshots below:

![Screenshot_2021-12-13_16-54-06](https://user-images.githubusercontent.com/75048121/145895169-42aec835-624a-44d3-8949-1e270103b485.png)
![Screenshot_2021-12-13_16-54-46](https://user-images.githubusercontent.com/75048121/145895173-ced7d501-a4d7-4dbe-a3e2-2f9a3282f8ff.png)

**Comment by introt** [comment]
This seems to be due to the anti-ambiguity feature introduced by bc27b6db6b294d961ad51616a2b304558b8ff5ca triggering unnecessarily. Fix is to skip the check if the Path bar is set to show hierarchy.

**Comment by VandaloftheVoid** [comment]
Many thanks! I know it's a minor issue, but I wanted to report it in case there might be ramifications more important than mere appearance.
