### ISSUE TITLE
0.73.5: scroolwheel does not scroll page

### ISSUE THREAD

**Issue by zwieblum** [zim-desktop-wiki/zim-desktop-wiki#1825]
As of version 0.73.5 the scrollwheel does not scroll the visible page any more. Keeping the left mouse button pressed and scrolling with the wheel scrolls the page but also selects text.

**Comment by introt** [comment]
Weird bug, can't reproduce here. What's your OS and how did you install Zim? Care to try if scrolling works on the latest release, 0.74.3?

**Comment by zwieblum** [comment]
Ok, works on 0.74.3. But I can't get rid of the clientside decorations :(

**Comment by dehesselle** [comment]
Disable `Preferences|Plugins|Tool Bar|Configure|Show controls in the window decoration` and restart the application.
