### ISSUE TITLE
'Back' mouse button doesn't work on the textarea, does work on the tree to the left

### ISSUE THREAD

**Issue by quesada** [zim-desktop-wiki/zim-desktop-wiki#1826]
**To Reproduce**
1. Go to the text area
2. Click on back button. Nothing happens

**Expected behavior**
Zim should go back to the last visited page

**Environment (please complete the following information):**
 - Version  0.74.2
 - OS: archlinux
 - Language: EN

**Comment by sojusnik** [comment]
See https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/610
Jaap assumes that it's an upstream issue, but I don't know where to report it.

**Comment by introt** [comment]
Duplicate of #610
