### ISSUE TITLE
Code blocks don't render unless you place them at the start of a new line

### ISSUE THREAD

**Issue by qyra** [zim-desktop-wiki/zim-desktop-wiki#184]
When you place the cursor at the end of a line containing 1 or more characters and select "Insert->Code Block" then it will initially render on a new line. But if you switch to another page and then back, you see something like this:

asdf{{{code: lang="diff" linenumbers="True"

}}}

After playing around a bit, it seems the parser always expects new code blocks to begin on their own line, but when it saves a code block to the file, it just places it wherever the cursor was, even if that was not at the start of a line. Manually adding newlines before {{{ will cause it to render correctly next time you load the page.

**Comment by jaap-karssenberg** [comment]
Yes, interface should prevent you from placing blocks mid sentence

Code blocks are treated as paragraphs, so conceptually doesn't make sense to allow them otherwise.

**Comment by jaap-karssenberg** [comment]
* Fix by making serialization force blocks to new line
  * And let insert action insert newline

**Comment by jaap-karssenberg** [comment]
I believe this issue to be fixed in development branch.
