### ISSUE TITLE
[develop] Text remains formatted as heading after pressing Enter

### ISSUE THREAD

**Issue by nelas** [zim-desktop-wiki/zim-desktop-wiki#1845]
**Describe the bug**
After pressing Enter at the end of a heading, the text on the next line keeps the heading formatting. This began after 9a4328e25cb42887448478b5b874e3f3d09b14af. It only happens if a newline already exists after the heading (even if empty). When the heading is the last line of the page, the issue doesn't occur (i.e. next line has no formatting). Please see the screen recording below.

**To Reproduce**

1. Create a heading in the middle of the page
2. Press enter to go to the next line
3. Type anything
4. The text will be formatted as a heading

**Expected behavior**
The text below a heading shouldn't be auto-formatted as a heading after pressing Enter.

**Screen recording**

https://user-images.githubusercontent.com/361179/147673468-ad4dad90-235b-4297-a3a0-5714706a32fc.mp4

**Environment (please complete the following information):**
 - Version: 0.74.3-SNAPSHOT-t202112282007~ubuntu21.10.1
 - OS: Linux Ubuntu running GNOME/Wayland

**Comment by jaap-karssenberg** [comment]
Thanks for reporting and thanks for being very specific about the behavior, helps a lot tracing it quickly. Committed a fix and added a test case to prevent breaking again.

**Comment by nelas** [comment]
Great, thanks Jaap!
