### ISSUE TITLE
Wiki-Format: oscillating from zim 0.4 and 0.6

### ISSUE THREAD

**Issue by wadih** [zim-desktop-wiki/zim-desktop-wiki#1846]
**Describe the bug**
Pages oscillating from
Wiki-Format: zim 0.4
to
Wiki-Format: zim 0.6
Depending if I save the page using my Windows Zim 0.74.3 or my Ubuntu Zim 0.72.0
Which messes up my content, for example when I have a TAB followed by Verbatim text, as I modify the page from my Windows machine and Ubuntu machine, the page incrementally messes itself up 

**To Reproduce**
- Create a page in Ubuntu, default version Wiki-Format: zim 0.4
- Put a line with a tab followed by Verbatim text
- Modify the page with a Windows version, changes to Wiki-Format: zim 0.6
- Open back the page in Ubuntu, now all the places with verbatim show with two single quotes

**Expected behavior**
When working on the same notebook using different versions of zim, perhaps the newer versions should take into account that the page is in format 0.4, and keep it in format 0.4, instead of automatically updating it to version 0.6. 
Because other machines working on the same zim notebook might be using older versions. 
Or perhaps give an option in notebook.zim to force zim to use a specific Wiki-Format version for all pages in that notebook

**Environment (please complete the following information):**
Windows 10 - Zim 0.74.3 
Ubuntu - Zim 0.72.0

**Additional context**
I have a shared notebook amongst multiple machines.

**Page Headers**
```
Content-Type: text/x-zim-wiki
Wiki-Format: zim 0.4
```
and
```
Content-Type: text/x-zim-wiki
Wiki-Format: zim 0.6
```

**Comment by dehesselle** [comment]
What about the easiest solution: use the same version of Zim on all your machines?

**Comment by wadih** [comment]
> What about the easiest solution: use the same version of Zim on all your machines?

Yes, I can confirm that solution works. Only issue was the default packaged one in Ubuntu store was older, that forced me to use the older one. But today I uninstalled the one from the ubuntu store and installed the latest .deb and it works great. 

Not sure what Jaap will want to do about it, but at least using the same version works. 

But in scenarios where that's not possible, perhaps honoring the version at the page level would be a good default to avoid the oscillation between page versions and content issues.

**Comment by dehesselle** [comment]
My guess is this is a "won't fix". I assume that if what you are asking was easily possible, it would have been implemented that way from the start.

Having a program full of feature flags and different code paths to stay compatible to old versions/behaviors is a nightmare. What you want - no offense - is a corner case that can easily be avoided by keeping versions identical, either by sticking to the lowest common denominator or updating something manually if the distribution doesn't offer the latest version. The 10 minutes it took you to uninstall/install a deb package simply do not compare to the many many hours of work and increase in ongoing maintenance burden to have such a feature.

However, a warning as in "you have opened an older notebook, if you continue this will be updated and no longer compatible" is probably the best thing to come out of this. You should not bear the risk of losing your work / your functioning multi-machine setup because you upgraded something and weren't aware of the consequences.

**Comment by vossenjp** [comment]
> ... default packaged one in Ubuntu store was older ... installed the latest .deb ...

For Ubuntu and derived distros like Mint, etc., just use the PPA!

**Comment by wadih** [comment]
No worries, no action required other than me sharing my story. There's nothing to fix. Just bringing up my experience as a contribution in case someone else runs into the same problem. 

Because it took me a few months of silent suffering, gathering clues over time, making sure it wasn't me that was misclicking, then thinking perhaps if it was a CRLF vs LF unix/dos encoding, to finally see the pattern and get to the bottom of it.

If that thread can save someone some time, all the best. Also I would advise against starting to put compatibility warnings all over the place as well, talking about adding useless code paths, that would be one of them. 

In my opinion, either the behaviour stays the same and it continues to update the page version silently and perhaps in the FAQ we add a line saying that if you're planning to use the same notebook on many machines, to use the same version of Zim on all of them to avoid file formats incompatibilities, or we keep the previous rendering functions in the source code and use the right one accordingly for reverse compatibility. But it depends on the bigger picture of if the author was ever planning to have full reverse compatibility at all or not, because as you said, it is an extra time investment for reverse compatibility, so he knows best. I'm genuinely good with both. No serious data was being lost, it was just the formatting that would be off at times. 

> For Ubuntu and derived distros like Mint, etc., just use the PPA!

Awesome for the PPA, that's very true!
