### ISSUE TITLE
[develop] Deleted line with checkbox creates an empty line after a page refresh

### ISSUE THREAD

**Issue by sojusnik** [zim-desktop-wiki/zim-desktop-wiki#1849]
**Describe the bug**
When a line with a checkbox is deleted, then it leaves an empty line after a page refresh.

**To Reproduce**
See video: https://user-images.githubusercontent.com/1245718/147956304-ab97de08-cb1a-43ea-8964-0f9c9b4fc260.mp4

**Environment**
Version: 0.74.3-SNAPSHOT-t202112291320~ubuntu21.10.1

**Comment by jaap-karssenberg** [comment]
Thanks for reporting, just committed a fix
