### ISSUE TITLE
easier way for creating bullet lists

### ISSUE THREAD

**Issue by mtill** [zim-desktop-wiki/zim-desktop-wiki#1851]
Hi!
I would really love to have an easier way on how to create bullet lists in ZIM.
E.g., when starting a new line with "- sometext", that could be automatically converted to a bullet list when pressing "enter"

Please take that input just as an idea.
What do you think?
BR
mtill

**Comment by jaap-karssenberg** [comment]
This already exist. Just use a * to type a bullet.



Op ma 3 jan. 2022 23:35 schreef mtill ***@***.***>:

**Comment by mtill** [comment]
Can this be configured ? I mean, the character? On a German Keyboard, "-" would be way more convenient

**Comment by jaap-karssenberg** [comment]
At the moment this is hard coded

Op di 4 jan. 2022 12:19 schreef mtill ***@***.***>:
