### ISSUE TITLE
Zim-clip does not activate (Windows)

### ISSUE THREAD

**Issue by andrescg2sj** [zim-desktop-wiki/zim-desktop-wiki#1857]
I am working on Windows 10, Zim version 0.73.0. I have installed zim-clip Firefox extension (Firefox 95.0.2), and also downloaded zimclip-1.3.3.tar.gz. I have uncompressed the plugin and installed it in my Zim plugins folder.

When I open Edit / Preferences, I see Zim Clip in the list of plugins, but when I click on it, it doesn't become enabled (the box does not get checked).

Any help is appreciated.

**Comment by jaap-karssenberg** [comment]
Please contact the author of Zim clip, it is not part of the default
package.

Op ma 10 jan. 2022 18:55 schreef andrescg2sj ***@***.***>:

**Comment by andrescg2sj** [comment]
Ok, I will do that, thank you.
