### ISSUE TITLE
Distraction free plugin does not work on OSX 

### ISSUE THREAD

**Issue by Enrico68** [zim-desktop-wiki/zim-desktop-wiki#1864]
I have just installed  Zim 0.74.3 using homebrew on OSX 10.15. I have tried to use the distraction free plugin with no success. When I press `F11` I have no effect. Even from the menu-bar -->Fullscreen.

**Comment by dehesselle** [comment]
While I don't use it personally, there's definitely a difference in fullscreen when I enable that plugin. Can you test our app https://zim-wiki.org/downloads.html ?

**Comment by Enrico68** [comment]
Just tried but still cannot get this option working. It behaves in the same way as the brew version with eventually more problems (not recognizing R, Gnuplot, LaTex for equations, DiTaa, seqdiag). I will remain with brew version using Emacs with zim-mode (perfect integration).

**Comment by introt** [comment]
Could you post a screen recording and debug logs?

**Comment by Enrico68** [comment]
[Here](https://pastebin.com/tf8t89WN) you get the debug logs and [here](https://imgur.com/Hh6gXq4) the screen. 
P.S. the `F-11` key on OSX (like the other functions keys) are not available.

**Comment by introt** [comment]
Thank you! The plugin seems to lack any and all logging, but your log also shows a concerning lack of `DEBUG: Action: toggle_fullscreen(True)` (which should show up whether you toggle via the function key or the menu item, regardless of the plugin).

The window seems to be maximized in your recording. Could you try resizing the window to be tiny and then triggering the menu item?

**Comment by Enrico68** [comment]
> The window seems to be maximized in your recording. Could you try resizing the window to be tiny and then triggering the menu item?

Minimizing and maximizing the window is working correctly using the window frame button. But the menu item is not responding.

**Comment by introt** [comment]
Seems there is a larger (not limited to the plugin) issue here. Are you using some window management related software? The menu item is really basic, so there might perhaps be an upstream issue. I can only extrapolate so much, as I don't have a Mac to test with :/

**Comment by Enrico68** [comment]
could be interesting but with the [Zim Markdown version](https://github.com/pfalcon/zim-desktop-wiki-markdown) is working. Here is the [debug](https://pastebin.com/R9LtXLdv)

**Comment by introt** [comment]
Doesn't look like `toggle_fullscreen` is present there either. I'm not familiar with the fork's code base, but hope it offers clues for the devs with OS X.

**Comment by dehesselle** [comment]
This is a comparison of "normal mode" and "distraction free mode":
![zim_distraction_free](https://user-images.githubusercontent.com/11375494/149953748-458b8688-46f2-4e8c-b7f3-ce13381525ff.gif)

(Don't pay attention to some artifacts, especially around window borders, that's the GIF compression.)

Is this not what it's supposed to do?

**Comment by introt** [comment]
I was under the impression that the menu item didn't make the window go full screen at all - thus the inquiry upon the usage of window management software. Might have something to do with the window decorations -- didn't 0.74 introduce client side decorations? @dehesselle has them disabled, you might want to try that @Enrico68

**Comment by Enrico68** [comment]
@introt window decoration ? I am not aware that is possible under OSX.  @dehesselle under which version of OSX are you testing ?

**Comment by dehesselle** [comment]
The GIF was recorded on High Sierra since that was the easiest thing for me to do (=my test system). I've also tested on Monterey.
Decorations can be disabled by enabling the toolbar plugin and unchecking the first item there ("show elements in title bar" or something, I don't have the English version in front of me right now). If people miss out on this option, I can add a note to the readme (I already have instructions on how to enable plugins with external dependencies).

**Comment by Enrico68** [comment]
I cannot see any _toolbar plugin_. Are you referringto the `Tray Icon`?

**Comment by dehesselle** [comment]
![toolbar_plugin](https://user-images.githubusercontent.com/11375494/150016995-b2d1233e-5fa7-4ee9-b1c5-b8451e10928a.png)

If you don't have that, you can't possibly be on 0.74.3, it's part of Zim.

For the sake of testing, please use our app (Homebrew is unsupported at this time). I'm not convinced yet that there is even an issue with distraction free editing.

**Comment by Enrico68** [comment]
Thanks @dehesselle it is working. I have installed the `HEAD` version and everything is _in Ordnung_

**Comment by introt** [comment]
Glad that the issue got resolved :+1: 

@dehesselle would you mind checking if toggling fullscreen works with the decorations enabled? If not, that's a separate issue not related to the plugin and needs its own ticket.

**Comment by dehesselle** [comment]
Fullscreen in general does not work with CSD enabled, regardless of distraction free mode. Clicking the menu item simply doesn't do anything. I wasn't aware of that.

**Comment by introt** [comment]
@dehesselle Roger that!

@jaap-karssenberg Could we get operating system labels for platform-dependant issues?

**Comment by jaap-karssenberg** [comment]
Please use a prefix like "[OS X]" for the subject for platform specific
issues. I try to use the labels for status tracking and I think this is
relevant info to see in the subject line when scanning new issues / emails
about issues.

**Comment by jaap-karssenberg** [comment]
Ah, I wasn't aware of that limitation in triage. In that case it indeed
makes sense to add tags for OSX and Windows specific issues.

-- Jaap
