### ISSUE TITLE
In 'Jump to page' dialog select the first item automatically 

### ISSUE THREAD

**Issue by tehkonst** [zim-desktop-wiki/zim-desktop-wiki#1874]
When I press `ctrl+j` and start typing I need to press `Down` button to choose the page, even if it's the first page in the list.
It will be much more convenient if the first element of the list is active immediately.

**Comment by sojusnik** [comment]
Yes to this 100x, but I'm afraid this is a technical limitation, according to Jaap.

**Comment by introt** [comment]
Duplicate of #1242
