### ISSUE TITLE
[develop] Applying heading style breaks first list/checkbox item

### ISSUE THREAD

**Issue by nelas** [zim-desktop-wiki/zim-desktop-wiki#1876]
**Describe the bug**
Applying heading style to a line above an existing list or checkbox will break the first item. As soon as the style is applied, the first item becomes misaligned, shifting to the left. The first checkbox disappears from the source code.

**To Reproduce**
1. Create list/checkbox with two items
2. Write something at the top of the list and apply a heading style
3. The first item will be displaced
4. Toggling the heading style doesn't work anymore

**Expected behavior**
Toggling heading style shouldn't alter list/checkbox items below.

**Screenshots**

Recording of the issue:

https://user-images.githubusercontent.com/361179/150563056-d1d8e032-207c-4b16-a3e4-e260c2d55e03.mp4

The screenshot below shows what the source code looks like after the bug appears. Note the first items of the list and checkbox under `Abnormal` became misaligned (shifted to the left). There is no apparent problem with the list in the source code, but the checkbox of the first item has gone missing. Accordingly, reloading the page makes the checkbox disappear and the list item returns to its original position (aligned with other items).

![heading-checkbox-bug](https://user-images.githubusercontent.com/361179/150563626-e4f3f65c-0f89-41d5-b182-ee055a93b5a6.png)

An error message appears in DEBUG:

```
DEBUG: Action: apply_format_h4
DEBUG: Action: apply_format_h4 (toggle_format action)
WARNING: BUG: Checkbox outside of indent ?
```

**Environment:**
 - Version 0.74.3-SNAPSHOT-t202201130939~ubuntu21.10.1
 - OS: Linux Ubuntu 21.10

**Comment by jaap-karssenberg** [comment]
Good catch!
