### ISSUE TITLE
[develop] Toggling heading style mostly broken

### ISSUE THREAD

**Issue by nelas** [zim-desktop-wiki/zim-desktop-wiki#1885]
Hi Jaap, this is a small follow-up that seems related to #1845 and #1876.

**Describe the bug**
Toggling heading style only works if it's on the last line of the page. If the text is anywhere else, I can apply a heading style (via Format or CTRL+4, for example), but can't toggle it issuing the same command.

**To Reproduce**
1. Write "header" in the last line of the page
2. Press CTRL+4 twice to apply and remove the heading style
3. It'll work
4. Now ẅrite "header" anywhere else on the page
5. Do step 2 above.
6. Style will be applied but not removed

**Expected behavior**
Toggling heading style should work anywhere on the page.

**Environment (please complete the following information):**
 - Version: 0.74.3-SNAPSHOT-t202201251855~ubuntu21.10.1
 - OS: Linux Ubuntu 21.10

**Debug log**
Nothing unusual, this appears:
```
DEBUG: Action: apply_format_h4
DEBUG: Action: apply_format_h4 (toggle_format action)
```

**Comment by jaap-karssenberg** [comment]
Thanks for reporting - I observed it as well yesterday, but could not
reproduce on my other system, so wanted to go back and check for a fluke.
Let me sort it out today.

**Comment by jaap-karssenberg** [comment]
Fix committed

**Comment by nelas** [comment]
Thanks!
