### ISSUE TITLE
Code block plugin not working MacOS

### ISSUE THREAD

**Issue by ozonil** [zim-desktop-wiki/zim-desktop-wiki#1887]
I turned the plugin on in preferences and tried to create a new block.
After I selected the syntax and ID, and pressed OK, I'm getting a bug report window:
```
This is zim 0.74.3
Platform: posix
Locale: None None
FS encoding: utf-8
Python: (3, 9, 9, 'final', 0)
PyGObject: (3, 42, 0)

======= Traceback =======
  File "/Applications/Zim.app/Contents/Resources/lib/python3.9/site-packages/zim/gui/insertedobjects.py", line 438, in _action_handler
    self.pageview.insert_object_model(otype, model)
  File "/Applications/Zim.app/Contents/Resources/lib/python3.9/site-packages/zim/gui/pageview/__init__.py", line 6991, in insert_object_model
    with buffer.user_action:
AttributeError: 'TextBuffer' object has no attribute 'user_action'
```
Environment:
 - OS: MacOS Monterey 12.0.1 Intel

**Comment by dehesselle** [comment]
Check the about screen, what is the complete version number there? Looks like this: `0.74.3 (?)`

**Comment by ozonil** [comment]
It says this: 0.74.3 (9)

**Comment by dehesselle** [comment]
I cannot reproduce your issue. Can you give me more details? What syntax and what ID are you setting, do you have any special configuration (e.g. `zimapp.ini`)?

![codeblock](https://user-images.githubusercontent.com/11375494/151401001-fee51650-1af1-4033-87d6-527a6782e247.gif)

**Comment by ozonil** [comment]
Most of the menu options in insert and format are whited out. I haven't configured it besides changing the font.
![2022-01-27 22-52-37](https://user-images.githubusercontent.com/25461347/151412277-73b495c9-3a5a-4273-b27b-5a5b9830423a.gif)

**Comment by dehesselle** [comment]
I'm always suspicious of locales messing things up. Launch Zim from the Terminal...
```
LANG=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /Applications/Zim.app/Contents/MacOS/Zim
```
...and try again.

**Comment by ozonil** [comment]
Thanks a lot! It works. It is not working when opening it from the applications though. I'm making an alias for the command you've provided for now.

**Comment by dehesselle** [comment]
There is a more comfortable way to configure this so it works when opening the app by double clicking it. Create a file named `~/Library/Application Support/org.zim-wiki.Zim/zimapp.ini` with the following content:
```ini
[environment]
LC_MESSAGES=en_US.UTF-8
LANG=en_US.UTF-8
```

Can you tell me what locale you are usually on (like output from `locale` in the terminal)? I'm guessing Python either gets confused or it's just not handled correctly at some point.

**Comment by ozonil** [comment]
I'm getting this output:
```bash
> locale
LANG=""
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

Also, I created the file following your instructions. App is still not working properly.
```bash
> pwd
/Users/tarunreddy/Library/Application Support/org.zim-wiki.Zim
> cat zimapp.ini 
[environment]
LC_MESSAGES=en_US.UTF-8
LANG=en_US.UTF-8
> 
```
