### ISSUE TITLE
[develop] Verbatim formatting applied to a sentence is rendered as a block

### ISSUE THREAD

**Issue by sojusnik** [zim-desktop-wiki/zim-desktop-wiki#1888]
**Describe the bug**
When formatting a sentence as verbatim, then the whole sentence is rendered as a block (with `'''`), but actually should be rendered how a single or several words usually are (with `''`), at least that was the case with previous versions.
Intented text gets also unintented, when applying the verbatim formatting, which wasn't happening before either.

See this recording for clarification:

https://user-images.githubusercontent.com/1245718/151344310-4c1e8ca6-1245-4e53-9e0a-af34e1ffd1cc.mp4

Happens on 0.74.3-SNAPSHOT-t202201261845~ubuntu21.10.1

**Comment by jaap-karssenberg** [comment]
Yes, made this change on purpose. It did happen in the previous release as
well, but slightly different rule about what is a full line. My thinking is
that selecting a full line typically means that you want a block.

Open to proposals how to tweak the behavior.

-- Jaap

**Comment by sojusnik** [comment]
Can't say for the technical aspect, but I would prefer to have a full line always to be rendered normal, so not as a block. The block formatting only makes sense with 2 or more lines.

**Comment by jaap-karssenberg** [comment]
When you say full line, do you include the trailing newline at the end?

Op do 27 jan. 2022 20:56 schreef sojusnik ***@***.***>:

**Comment by sojusnik** [comment]
Can you give an example what a trailing newline looks like in context of Zim? Searched around, but without a matching result.

**Comment by jaap-karssenberg** [comment]
Well, of you select a line, the cursor at the end of the selection can be
at the end of the line or at the first position of the next line. This is a
subtle difference, but important when we distinguish between single or
multiple lines.

Op vr 28 jan. 2022 10:33 schreef sojusnik ***@***.***>:

**Comment by sojusnik** [comment]
Are we speaking about this?

https://user-images.githubusercontent.com/1245718/151695533-7b89aa23-de96-4b4a-8cc9-087e16e21f2a.mp4

**Comment by jaap-karssenberg** [comment]
No, wrapped lines don;t change the behavior. It is the difference between
selecting a line from the start by <Shift><End> which places the end of the
selection at the end of the line versus selecting a line from the start by
<Shift><Down> which places the end of the selection on the start position
of the next line.

**Comment by sojusnik** [comment]
So we are speaking about this?
https://user-images.githubusercontent.com/1245718/151721425-69eb8ae9-21de-4005-8222-9cb1ddb55266.mp4

**Comment by sojusnik** [comment]
So we are speaking about this?
https://user-images.githubusercontent.com/1245718/151721611-1a7a0eea-c701-4440-b211-5616bd3d55a4.mp4

After selecting the line/paragraph and applying verbatim, I can choose with left or right keys where my cursor should appear. In both examples in the video I've pressed left, but after undoing the formatting (with ctrl+z = going one step back), the cursor jumped to the end of the line or to the beginning of the next paragraph respectively.

**Comment by introt** [comment]
(Slightly off-topic, but re:
>after undoing the formatting (with ctrl+z = going one step back), the cursor jumped to the end of the line or to the beginning of the next paragraph respectively.

; that's an [older issue](https://github.com/zim-desktop-wiki/zim-desktop-wiki/discussions/1731#discussioncomment-1708905))

**Comment by introt** [comment]
I think Jaap meant this:

```
|The pipe represents the cursor and the backspace-n an invisible newline char\nThis is the second line\n
```
> |The pipe represents the cursor and the backspace-n an invisible newline char
> This is the second line

#### shift + end:

```
The pipe represents the cursor and the backspace-n an invisible newline char|\nThis is the second line\n
```
> **The pipe represents the cursor and the backspace-n an invisible newline char**|
> This is the second line

#### shift + down

```
The pipe represents the cursor and the backspace-n an invisible newline char\n|This is the second line\n
```
> **The pipe represents the cursor and the backspace-n an invisible newline char**
> |This is the second line

Both only "paint" (represented here by bolding) the visible line, while the latter selection includes the newline char

**Comment by sojusnik** [comment]
I see, thanks! The issue described by me is already resolved in the new version, so we can close this one and maybe continue the shift+end/down behaviour in a new discussion?

**Comment by jaap-karssenberg** [comment]
The patch that I committed makes a subtle difference: selecting the text of
a single line will keep "code" formatting, but selecting the new line as
well (visibly the selection goes to the full width of the view) it will
switch to "Verbatim block" formatting.

Maybe subtle, but my rationale is that this allows a user to do both and it
makes sense implementation wise.
