### ISSUE TITLE
More advanced matching for Jump To autocompletion

### ISSUE THREAD

**Issue by ipsod** [zim-desktop-wiki/zim-desktop-wiki#189]
If I have a page `Home:Goals` and I open the Jump To menu and type `home goals`, it does not offer `Home:Goals` as a possible result for that search.  It would be expected that it would, and it would be nice if even a search for `h goa` brought up a result for `Home:Goals` (or even a more deeply nested `Home:Planning:Goals`).

Using Zim 0.67

**Comment by jaap-karssenberg** [comment]
See the atom editor for an example of "smart" matching in action - e.g. in the "<Ctrl>P" file selection popup

**Comment by introt** [comment]
Such matching should also be used in eg. the link dialog. This should cover the use case described in #1102

**Comment by ipsod** [comment]
I was looking into fuzzy searching for other purposes, and found this library which might be useful:
https://github.com/seatgeek/thefuzz

This would require loading everything into memory, instead of a database - is Zim using something like that, or is there an sqlite db or something?  If it's using sqlite, I haven't found a good solution for fuzzy search.

**Comment by introt** [comment]
Page names are cached in index.db using sqlite afaik

**Comment by jaap-karssenberg** [comment]
Fixed in [fe7a797](https://github.com/zim-desktop-wiki/zim-desktop-wiki/commit/fe7a7972f49b0312c3597347757ba60ce91b220b)
