### ISSUE TITLE
[develop] Indented text with checkboxes can't be copied in certain situation 

### ISSUE THREAD

**Issue by sojusnik** [zim-desktop-wiki/zim-desktop-wiki#1895]
**Describe the bug**
In the situation shown in the following video, only two lines with checkboxes can be copied, but not if you select all three lines:

https://user-images.githubusercontent.com/1245718/151715874-37cbf507-98a5-423d-951a-d355af5a6a50.mp4

You'll also see that after pasting the text, the last checkbox isn't rendered, which shouldn't happen.

Happens on 0.74.3-SNAPSHOT-t202201290925~ubuntu21.10.1

**Comment by nelas** [comment]
This also occurs for un-indented lists. If the last item's newline character isn't copied, its asterisk won't be rendered when pasted.
