### ISSUE TITLE
0.66 crashing on reindex

### ISSUE THREAD

**Issue by MurrayVK3** [zim-desktop-wiki/zim-desktop-wiki#19]
Running zim --index /PathToMy(large)ZimFolder outputs:

INFO: This is zim 0.66
INFO: Flushing index
INFO: Indexing None
INFO: Indexing None
INFO: Indexing None
INFO: Indexing None
<snip many many many pages of this repeating>
INFO: Indexing None
INFO: Indexing None
INFO: Indexing None
INFO: Indexing None
INFO: Indexing None
ERROR: Exception in signal handler for finish-update on <zim.notebook.index.files.FilesIndexer object at 0x7f94e011a210>
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/zim/signals.py", line 338, in emit
    r = handler(self, *args)
  File "/usr/lib/python2.7/dist-packages/zim/notebook/index/links.py", line 146, in on_finish_update
    target_id = self._pagesindexer.insert_link_placeholder(targetname)
  File "/usr/lib/python2.7/dist-packages/zim/notebook/index/pages.py", line 141, in insert_link_placeholder
    return self._insert_page(pagename, True)
  File "/usr/lib/python2.7/dist-packages/zim/notebook/index/pages.py", line 167, in _insert_page
    (pagename.name, sortkey, parent_row['id'], is_link_placeholder, file_id)
IntegrityError: UNIQUE constraint failed: pages.name

This is on Mint 17 using the deb from http://zim-wiki.org/downloads/zim_0.66_all.deb

Thanks
Murray

**Comment by jaap-karssenberg** [comment]
Not sure what causes this error, but added code to catch it in patch 0c76cd948cf7f228896509f512ce5e06319725bf

**Comment by MurrayVK3** [comment]
Tested again after your patch:

python ./zim.py --index /media/localHDD/MurraysPersonalStuff/Dropbox/Zim/
INFO: This is zim 0.66
INFO: Flushing index
ERROR: Exception in signal handler for finish-update on <zim.notebook.index.files.FilesIndexer object at 0x7fa05a93d210>
Traceback (most recent call last):
  File "/home/murray/Downloads/zim-desktop-wiki-master/zim/signals.py", line 338, in emit
    r = handler(self, *args)
  File "/home/murray/Downloads/zim-desktop-wiki-master/zim/notebook/index/links.py", line 146, in on_finish_update
    target_id = self._pagesindexer.insert_link_placeholder(targetname)
  File "/home/murray/Downloads/zim-desktop-wiki-master/zim/notebook/index/pages.py", line 141, in insert_link_placeholder
    return self._insert_page(pagename, True)
  File "/home/murray/Downloads/zim-desktop-wiki-master/zim/notebook/index/pages.py", line 167, in _insert_page
    (pagename.name, sortkey, parent_row['id'], is_link_placeholder, file_id)
IntegrityError: UNIQUE constraint failed: pages.name

To be fair, I didn't 'install' this version of zim, just ran it from the the unzipped folder.  I presume thats a valid thing to do?



As a further test I created a new notebook which seemed to work OK, generated two new pages.  Then clicking back on the first page I made did this:

python ./zim.py ~/pop
INFO: This is zim 0.66
INFO: No VCS detected
INFO: Open page: another:under one (another:under one)
INFO: Loading template from: /home/murray/Downloads/zim-desktop-wiki-master/data/templates/wiki/Default.txt
INFO: Loading template from: /home/murray/Downloads/zim-desktop-wiki-master/data/templates/wiki/Default.txt
INFO: Open page: a new page (a new page)
INFO: Loading template from: /home/murray/Downloads/zim-desktop-wiki-master/data/templates/wiki/Default.txt
INFO: Open page: a new page:a new sub page (a new page:a new sub page)
INFO: Open page: a new page (a new page)
INFO: Open page: a new page:a new sub page (a new page:a new sub page)
Traceback (most recent call last):
  File "/home/murray/Downloads/zim-desktop-wiki-master/zim/gui/pageindex.py", line 404, in do_page_activated
    self.ui.open_page(path)
  File "/home/murray/Downloads/zim-desktop-wiki-master/zim/actions.py", line 132, in func
    self.func(instance, *args, **kwargs)
  File "/home/murray/Downloads/zim-desktop-wiki-master/zim/gui/__init__.py", line 732, in open_page
    raise AssertionError, 'Could not close page'
AssertionError: Could not close page


Let me know if theres anything else I can do to help.
Thanks
Murray

**Comment by jaap-karssenberg** [comment]
Sorry, afraid the patch I mentioned above was not uploaded correctly to github, it is now - see 2638b099962a6224c05d8333519071110d8c531b or latest commit on master

**Comment by jaap-karssenberg** [comment]
Not seen any output of the error logging - closing for now. Please re-open this issue if you can reproduce the situation leading to logging a "#19" warning.

**Comment by Osndok** [comment]
I see a constant stream of these warnings whenever I use KDE, should I be concerned?
```
ERROR: BUG: issue #19 seen: (<Path: >, [u'Journal', u'2019', u'01']) -> (None, <Path: Journal:2019:01>) - branch 1 !
ERROR: BUG: issue #19 seen: (<Path: >, [u'Journal', u'2019', u'01', u'19']) -> (None, <Path: Journal:2019:01:19>) - branch 1 !
ERROR: BUG: issue #19 seen: (<Path: >, [u'Journal', u'2019', u'01', u'20']) -> (None, <Path: Journal:2019:01:20>) - branch 1 !
```

**Comment by jaap-karssenberg** [comment]
It should not affect functioning, but does mean there is something
unexpected. I'll look into it.

**Comment by jaap-karssenberg** [comment]
Still observed in latest version
