### ISSUE TITLE
external changes cause gtkspellchecker-related freezes

### ISSUE THREAD

**Issue by zauberparacelsus** [zim-desktop-wiki/zim-desktop-wiki#1902]
**Describe the bug**
I use git to manage my notes in Zim, though I do not use the version control plugin because it does not work to my liking.  When I do a git revert or reset on my notebook's directory, Zim will freeze for up to a few minutes when I try to view a page that was changed by the revert or reset.

When this issue occurs while running Zim on the command line with the verbose flag, I see the output like this spammed for _thousands_ of lines:
```
(zim:19633): Gtk-CRITICAL **: 15:57:51.163: gtk_text_buffer_set_mark: assertion 'gtk_text_iter_get_buffer (iter) == buffer' failed
(zim:19633): Gtk-CRITICAL **: 15:57:51.163: gtk_text_buffer_set_mark: assertion 'gtk_text_iter_get_buffer (iter) == buffer' failed
(zim:19633): Gtk-CRITICAL **: 15:57:51.163: gtk_text_buffer_remove_tag: assertion 'gtk_text_iter_get_buffer (end) == buffer' failed
```

Investigating further, when opening *almost any* page I see those messages above spamming in the console, but for only a split second.  However, I also see this warning appear once during page loading:
`(zim:19893): Gtk-WARNING **: 16:01:13.060: A tag named 'gtkspellchecker-misspelled' is already in the tag table.`

When I disable the spell checker plugin, this issue disappears entirely.

**Environment (please complete the following information):**
 - Version 0.74.3
 - OS: Manjaro Linux, kernel 5.15.16
 - Language: US English

**Additional context**
- If I close and reopen zim before trying to open an altered page, or if I run git revert or reset while the notebook is not open in Zim and then try to open an altered page, the issue does not occur.
- Maybe related to issue #1497

**Comment by jaap-karssenberg** [comment]
Applied fix that works for me. But since I do not perfectly can reproduce your issue it may require some testing and further testing.
