### ISSUE TITLE
Zim Desktop Wicki fail after install

### ISSUE THREAD

**Issue by Bob1946** [zim-desktop-wiki/zim-desktop-wiki#1905]
it Loads and starts ok in Zorin 16 but all text is greyed out so you can use it 4-2-2022

**Comment by introt** [comment]
Hi! Could you post a screenshot and logs (Tools > View debug log)? Which version of Zim is this and how did you install it? Thanks!

**Comment by Bob1946** [comment]
Thanks for your I have solved the problem with Zim I have uninstalled Zim and use another program for my notes

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
