### ISSUE TITLE
Edit source does not work on MacOS

### ISSUE THREAD

**Issue by fladd** [zim-desktop-wiki/zim-desktop-wiki#1909]
**Describe the bug**
There seems to be no way to edit the source with an external editor under MacOS.

**To Reproduce**
1. Go to Preferences and add the editor command (e.g. '/Applications/MacVim.app/Contents/bin/mvim')
2. Run the shortcut to edit source (e.g. the default Ctrl-E)
3. Nothing happens

**Expected behavior**
I expect MacVim to open (or any other editor I set in the preferences) the currently edited Zim page.

**Environment (please complete the following information):**
 - Version 0.74.3
 - OS: mac os (Catalina)
 - Language: English (UK I think)

**Additional context**
I also remember that there used to be an entry in the menu under "Tools/Edit source". This is also not there anymore it seems.

There is nothing related in the debug messages.

**Comment by dehesselle** [comment]
I cannot reproduce your issue.

![zim_edit_source](https://user-images.githubusercontent.com/11375494/152702062-1634e809-f66b-4e88-8e56-2b977f03df80.gif)

**Comment by fladd** [comment]
@dehesselle Mmh, you also seem to be able to get the Mac menu working...Interesting, that also doesn't work for me (it will just remove the normal menu, but that is another story).

Here is how things look for me, with the entry missing also entirely from the Tools menu:

![zim_macos_bug2](https://user-images.githubusercontent.com/2971539/152704552-d8507ebc-355b-4355-a607-85c82ad7cafe.gif)

**Comment by dehesselle** [comment]
From your "About" screen I can tell you're not using our app (see [Downloads](https://zim-wiki.org/downloads.html) on the website), it's supposed to say `0.74.3 (9)`. If you cannot make the switch to our app, I'd be interested to know the reason (as in: possible improvements for our app).

**Comment by fladd** [comment]
Oh, I just installed it with Homebrew...didn't realize that this was not the official version. Wasn't Homebrew even mentioned on the website as a way to install on MacOS in the past? If that has changed and the Homebrew version is not official, then maybe this could be mentioned explicitly on the Download page as a warning?

So yes, having the "official" application installed, it works now as expected :-) Thanks!

**Comment by dehesselle** [comment]
Neither Homebrew nor MacPorts were ever official releases of Zim, but in the absence of one, that was simply all that people had.  
All mentions of "installing with Homebrew" have been removed from the website when the official app was released.
