### ISSUE TITLE
Journal lanugage set to Dutch

### ISSUE THREAD

**Issue by fladd** [zim-desktop-wiki/zim-desktop-wiki#1910]
**Describe the bug**
I switched recently from the Homebrew version to the downloadable vesion of ZIM. The new version switched my language (but only for the Calendar and Journal pages) to Dutch. I don't want that (and I also didn't set that). I assume ZIM somehow checked that I am currently located in the Netherlands and adjusted this. I could not find a way to set the language anywhere, and searching the documentation did not yield any results.

**To Reproduce**
1. Install new MacOS version of ZIM
2. Calendar and Journal (headings) are in Dutch
3.
**Expected behavior**
Everything should be in English.

**Screenshots**
<img width="924" alt="image" src="https://user-images.githubusercontent.com/2971539/152804832-e44cf8b2-c464-403f-820e-64c21dba755f.png">

**Environment (please complete the following information):**
 - Version 0.74.3 (9)
 - OS: MacOS
 - Language: English

```
~ % locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```

**Comment by fladd** [comment]
> That is why the default behavior for the app is "read locale data from macOS and set `LC_MESSAGES` accordingly" as that is what most people would want.

Yes, except that my locale is en_US.UTF-8 and not Dutch...

**Comment by fladd** [comment]
Also, adding the zimapp.ini file with the content you mentioned does unfortunately not solve the issue.

**Comment by dehesselle** [comment]
Adjusting `LC_MESSAGES` is the only thing that I have implemented, everything else is up to Python/GTK/... magic. You can try setting more of those locale related variables in `zimapp.ini`, e.g. `LC_TIME="en_US.UTF-8"`. You need to restart Zim for changes to take effect.

**Comment by fladd** [comment]
Okay, dumping all my locale information into the file (including quotes) worked:
```
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```

But I still would like to understand where it gets the Dutch language from to begin with, as all my system locales are set to English already....

**Comment by dehesselle** [comment]
I can only tell you that the environment you see in your terminal/shell - where you ran `locale` - is not what Finder presents to a program when it's launched via GUI. For example, my system is configured to `de_DE.UTF-8` everywhere and Zim won't launch in German for me without that mechanism that sets `LC_MESSAGES` in the background.

I think nobody had to deal with that before because everybody has been launching Zim via terminal/shell or wrappers (which ran scripts in a shell), where all locale related variables are set.
