### ISSUE TITLE
[develop] Handling of non-actionable-tasks

### ISSUE THREAD

**Issue by introt** [zim-desktop-wiki/zim-desktop-wiki#1917]
**Describe the bug**
I'm seeing greyed-out tasks in the Active list. They inherit one of my non_actionable_tags from their parent. Given the option to set these tags is missing from the UI, seems they are to be migrated to waiting_labels?

**To Reproduce**
1. Have the following in `notebook.zim`:

        [TaskListPlugin]
        nonactionable_tags=@na

2. Add the tag to tasks
3. Open the tasklist plugin and list active tasks (if needed, filter by aforementioned tag)
4. See the tagged tasks listed, grayed-out

Also:
* open plugin settings/notebook prefs and see no way to edit these tags

**Expected behavior**
Nonactionable tasks shouldn't be included in the Active list. Waiting feels a bit wrong, but then again the UI for this feature has been removed so not sure what's the correct call here.

**Environment (please complete the following information):**
 - Version ae884829337092f410a3a287f5ebd32290a12461
 - OS: linux
 - Language: especially for errors that might relate to character encoding or other locale specific issues

**Additional context**
https://github.com/zim-desktop-wiki/zim-desktop-wiki/discussions/1863#discussioncomment-1975911

**Comment by jaap-karssenberg** [comment]
Fixed by 7ceaa7de0881e6baadd230ad3530f876d14a2d47
