### ISSUE TITLE
[develop] Adding a new project causes "Updating Index" to freak out

### ISSUE THREAD

**Issue by reagle** [zim-desktop-wiki/zim-desktop-wiki#1918]
I'm using today's dev version and went to create a new/fresh wiki for the purposes of testing. Upon launch of the new wiki the "Updating index" dialogue opened and the blue progress bar flickered back-and-forth for 5 seconds until I canceled. Clicking  "Check and update index" did the the same.

After doing this a couple of times, it finally terminated naturally (after about 10 seconds) and seem to work correctly.

**Comment by introt** [comment]
@reagle please elaborate, thanks

**Comment by reagle** [comment]
I haven't experience this in a while, so I'll close.
