### ISSUE TITLE
Crash when editing code "Defaults" code block

### ISSUE THREAD

**Issue by chelmich** [zim-desktop-wiki/zim-desktop-wiki#1921]
**Describe the bug**
Typing anything a code block with syntax highlighting set to "Defaults" immediately crashes the program.

**To Reproduce**
1. Enable the "Source View" plugin if it is not already enabled.
2. Insert -> Code Block
3. Select "Defaults" in the syntax field of the dialog, confirm
4. Place the cursor in the newly created code block
5. Type anything
6. Observe crash

**Environment:**
 - Version 0.74.3, Windows binary installer from website
 - OS: Windows 10
 - Language: en-us

**Additional context**
Nothing is written to the debug log. I assume this is because Zim crashes before anything can be written.

Edit: This bug appears to be very similar to another issue on [Launchpad](https://bugs.launchpad.net/zim/+bug/1478215).

**Comment by introt** [comment]
Hi and thanks for the report!

I can reproduce this on Linux as well, so Windows can be removed from the title.

If you try to manually insert code into a "Defaults" block, you get the same crash on page load without interacting with the block. The following errors were logged before crash:

```
GtkSourceView:ERROR:gtksourcecontextengine.c:5446:update_syntax: assertion failed: (state->context != NULL)
Bail out! GtkSourceView:ERROR:gtksourcecontextengine.c:5446:update_syntax: assertion failed: (state->context != NULL)
```

Note that this is not recoverable without removing the code block from the page source file.

Here's one such offending block for reference:

```
{{{code: lang="def" linenumbers="True"
Hello, World!
}}}
```

The "Defaults", as all other languages, come from GtkSource's LanguageManager, so this _might_ be an upstream bug.

**Comment by chelmich** [comment]
Sure @dehesselle! I have an interest in programming language design, so I was writing down some notes for potential syntax of a toy language. Because it wouldn't match any existing highlighting I was looking for an option that would just disable highlighting for the code block entirely. "Defaults" seemed like a plausible name for that kind of thing.

I was considering opening a feature suggestion issue for that, but I hadn't gotten around to it yet.

**Comment by dehesselle** [comment]
> I was looking for an option that would just disable highlighting for the code block entirely. "Defaults" seemed like a plausible name for that kind of thing.

Good, that's what I expected. See https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/451 how to add plaintext as a language.

**Comment by chelmich** [comment]
Perfect, thanks!
