### ISSUE TITLE
[develop] Clear formatting doesn't affect verbatim blocks

### ISSUE THREAD

**Issue by introt** [zim-desktop-wiki/zim-desktop-wiki#1927]
**Describe the bug**
There's no way to undo existing verbatim formatting (Ctrl+Z still works directly after). Additionally, text copied out of such block keeps its formatting (workaround for single lines: paste on a non-empty line), so un-verbatimizing is quite laborious.

**To Reproduce**
1. Select text inside a verbatim block or the whole block
2. Ctrl+9
3. Nothing happens

**Expected behavior**
Verbatim formatting gets cleared, breaking up the block if needed, as it did on earlier versions.

**Environment (please complete the following information):**
 - Version 11d78a509307191457c77b7a7ea3afbb4af9df86
 - OS: linux
 
**Additional context**
Somewhat related to #1888

**Comment by introt** [comment]
I also recall getting stuck inside an intended verbatim block at the end of a note where enter kept creating more verbatim lines, but can't reproduce.

**Comment by jaap-karssenberg** [comment]
Fix committed
