### ISSUE TITLE
[tasklist] Make TaskList save state between uses

### ISSUE THREAD

**Issue by ipsod** [zim-desktop-wiki/zim-desktop-wiki#193]
TaskList loses state every time it's closed.  I've got a lot of tasks, and as I'm working through them, I have to find my place again every time I close the TaskList pop-up.  It's not good for the workflow.

Using Zim 0.67.

**Comment by BadHairDay85** [comment]
I have encountered this issue as well. As a temporary workaround, minimizing the TaskList instead of closing it works for me, though.

**Comment by mikem23** [comment]
I've been noticing this since I started using the tasks plugin recently. I will collapse a list of subtasks, then later find that the list has expanded. This seems to happen whenever the list is updated due to a task state change (not one of the subtasks that has been folded).
