### ISSUE TITLE
Zim fails to play together with Vim (and probably other console based applications) as default text editor

### ISSUE THREAD

**Issue by dirdi** [zim-desktop-wiki/zim-desktop-wiki#1931]
**Describe the bug**
Editing source or viewing debug log with Vim.

**To Reproduce**
1. Configure Vim to be the default text editor:
![image](https://user-images.githubusercontent.com/7914030/153967122-04964b3e-bd7e-49fc-bd6d-7a6bb784c762.png)
2. Click on 'Tools'
3. Click on 'Edit Source'
4. See error:
![image](https://user-images.githubusercontent.com/7914030/153967298-ed814f2f-74f2-4db7-a013-2a94a1c1e8e3.png)
Zim debug log:
    ```
    DEBUG: Action: edit_page_source
    DEBUG: open_file(/home/username/.zim/Shopping.txt, text/plain)
    DEBUG: Loading config from: /usr/share/applications/vim.desktop
    INFO: Spawning: ('vim', '/home/username/.zim/Shopping.txt') (cwd: /home/username)
    DEBUG: Process started with PID: 1239851
    DEBUG: Running MessageDialog
    Vim: Warning: Output is not to a terminal
    Vim: Warning: Input is not from a terminal
    [m[m[0m[H[2J[23;1H"~/.zim/Shopping.txt" 7L, 151B[1;1H[33m1   [0mContent-Type: text/x-zim-wiki[1m[34m↲[0m
    [33m  1 [0mWiki-Format: zim 0.6[1m[34m↲[0m
    [33m  2 [0mCreation-Date: 2022-02-12T21:02:42+01:00[1m[34m↲[0m
    [33m  3 [0m[1m[34m↲[0m
    [33m  4 [0m====== Shopping ======[1m[34m↲[0m
    [33m  5 [0mCreated Saturday 12 February 2022[1m[34m↲[0m
    [33m  6 [0m[1m[34m↲
    ~                                                                               [9;1H~                                                                               [10;1H~                                                                               [11;1H~                                                                               [12;1H~                                                                               [13;1H~                                                                               [14;1H~                                                                               [15;1H~                                                                               [16;1H~                                                                               [17;1H~                                                                               [18;1H~                                                                               [19;1H~                                                                               [20;1H~                                                                               [21;1H~                                                                               [0m[22;1H[1m[7m.zim/Shopping.txt                                             1,1            All[1;5H[24;1H[0mVim: Error reading input, exiting...
    Vim: Finished.
    [24;1H
    DEBUG: Running ErrorDialog
    DEBUG: Could not open: Shopping.txt
    NoneType: None
    ERROR: Could not open: Shopping.txt
    ```
    journalctl log:
    ```
    Feb 15 01:01:18 hostname vim[1519767]: *** err
    Feb 15 01:01:18 hostname vim[1519767]: checking tty name failed
    Feb 15 01:01:18 hostname vim[1519767]: *** err
    Feb 15 01:01:18 hostname vim[1519767]: Oh, oh, it's an error! possibly I die!
    ```

**Expected behavior**
Zim should start up Vim to edit the source file.

**Environment:**
 - Version
 ![image](https://user-images.githubusercontent.com/7914030/153967904-6c46a6be-e5c6-462d-99b3-3ad488e6ffab.png)
 - OS:
 ```
$ uname -a
Linux hostname 5.15.0-3-amd64 #1 SMP Debian 5.15.15-2 (2022-01-30) x86_64 GNU/Linux
```
- Language: EN-US
- WM: i3

**Additional context**
Vim has  been configured as a terminal application (the vim.desktop file contains `Terminal=true`) and other graphical applications, like Firefox, do not struggle to open e.g. downloaded text files with Vim.

If one starts Zim from a terminal, the Vim instance will be launched inside this terminal. This is *not* expected behavior, too. One would expect Zim to open another terminal window to run Vim inside.

I suspect that this bug could be solved, by leveraging a tool like xdg-open, instead of implementing all the [open-file-with-default-application-logic](https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/f27bbd73cce48668283ccfd42c43af5d06cdeca4/zim/gui/applications.py#L248) by itself. Otherwise, Zim should parse application's .desktop files and handle terminal applications properly.

**Comment by jaap-karssenberg** [comment]
Fixing this with *minimal* support for the "Terminal" option. However since there is no canonical way to know what terminal to call (and how to call it) I don't want to invest in making it smart enough under all circumstances. Still recommend to just create a ".desktop" entry which explicitly states the terminal emulator you want to use in the "Exec" field.

**Comment by dirdi** [comment]
Thank you for implementing this feature!

I just want to add two hints / remarks for future development:
1. You are completely right about a missing "canonical way". I hope that some day, xdg-open will be "smart enough" to handle this and that other applications (like Zim) can rely upon it (cf. [this bug report](https://gitlab.freedesktop.org/xdg/xdg-utils/-/issues/84)).

2. The i3 developers mitigated this problem by means of a helper script: https://github.com/i3/i3/blob/next/i3-sensible-terminal
