### ISSUE TITLE
[develop] Pasted text isn't respecting indention

### ISSUE THREAD

**Issue by sojusnik** [zim-desktop-wiki/zim-desktop-wiki#1934]
**Describe the bug**
A pasted text removes indention (regardless if it's copied from Zim or another place), while a pasted picture (in the form of a black square in this example) isn't, as shown here:

https://user-images.githubusercontent.com/1245718/154551649-98d88bbe-b011-4056-995f-64a4d7ce269a.mp4

**Expected behavior**
The pasted text should respect the indention, read, the pasted text should be inserted after the indention, as shown with the picture in the example above.

**Environment (please complete the following information):**
0.74.3-SNAPSHOT-t202202152011~ubuntu21.10.1

**Comment by introt** [comment]
Can repro on release version too, selecting parts inside word vs. a whole line doesn't make a difference.

Test case should include pasting multiple lines too
