### ISSUE TITLE
[develop] Moving a header creates = signs

### ISSUE THREAD

**Issue by sojusnik** [zim-desktop-wiki/zim-desktop-wiki#1935]
**Describe the bug**
Moving a header creates `=`, as shown here:

https://user-images.githubusercontent.com/1245718/154553676-4f501013-a832-4e04-9d9e-ae204fab5a58.mp4

Move the cursor to the beginning of the header and press one or several times enter. Refresh the site and you'll see those `=` signs.

**Environment (please complete the following information):**
0.74.3-SNAPSHOT-t202202152011~ubuntu21.10.1

**Comment by introt** [comment]
Confirmed w/ commit 458688c2042602ba4a0c94dab8b1e11f9008911d, can't repro on release version

**Comment by introt** [comment]
Not present in the release version, fixed in `develop`
