### ISSUE TITLE
[develop] Make filter active again in tasklist plugin

### ISSUE THREAD

**Issue by releve1403** [zim-desktop-wiki/zim-desktop-wiki#1945]
**Describe the bug**
In Master version, in tasklist plugin, the text filter was active by default, allowing typing of words to directly filter tasks. This is not the case in develop branch.

**Screenshots**
See arrow #2 in following screenchot from Master.
![image](https://user-images.githubusercontent.com/98767445/155029841-89143e07-fbb2-49c1-8174-34bebdc2e79d.png)

**Environment**
    Version 0.74.3
    Develop branch
    Linux Ubuntu 20.04

**Comment by jaap-karssenberg** [comment]
Not sure if I want to focus it be default - could argue the focus should be
on either the selection pane or on the tasks themselves for keyboard
browsing the list.

However I can easily add an accelerator like Alt-F and/or Ctrl-F to focus
the filter.

-- Jaap

**Comment by releve1403** [comment]
Hi Jaap,
I was just observing that this is the default behavior on the master branch, and I was used to type to filter directly. 
I think it is kind of natural to begin typing to filter on the tasks list view, but having a shortcut like Ctrl-F would be good as well, just a little bit longer.
Thanks again.
--Renaud L.

**Comment by jaap-karssenberg** [comment]
Fixed by c93e708e1400182837ccdb937ff711d91465b0d2 (mistyped issue number in commit message)
