### ISSUE TITLE
[develop] Regression: Image scaling doesn't work

### ISSUE THREAD

**Issue by introt** [zim-desktop-wiki/zim-desktop-wiki#1951]
**Describe the bug**
524907ff2916f9ec52373be4cf997e93b1ff4e18 broke image scaling and all images now appear at their native resolution

**To Reproduce**
1. Have an image on a page
2. Try to resize it
3. The image stays the same size, regardless of restarting the application. The new size is saved in the wikitext.

**Environment (please complete the following information):**
 - Version 524907ff2916f9ec52373be4cf997e93b1ff4e18
 - OS: linux
 
**Additional context**
Image scaling works on 25b0d197a85113a4a4cb4f22d82cfd065c7c5d0a

**Comment by jaap-karssenberg** [comment]
GdkPixbuf-CRITICAL **: 17:20:36.409: gdk_pixbuf_scale_simple: assertion
'dest_height > 0' failed

... handling of "0" width / height fails

**Comment by introt** [comment]
Since we override only one of the two, the other needs to be calculated using the pixbuf's properties before passing it to `scale_simple` - should be a _simple_ fix (pun intended) ;)

Are you on this or do you want me to submit a patch?
