### ISSUE TITLE
[develop] ParseTree regression: Header after horizontal line produces 'Missing "\n" before new block' errors

### ISSUE THREAD

**Issue by introt** [zim-desktop-wiki/zim-desktop-wiki#1960]
**Describe the bug**
If a header follows directly after a horizontal line, the warning `Missing "\n" before new block (h)` appears in the logs. This alone is harmless, but will mess with line-based actions over indefinite distance (which made the bug really fun to track down!). See screenshots.

**To Reproduce**
0. Make sure you have the Line Sorter plugin activated
1. Type `Foo` and press newline
2. Type `---` and press newline
3. Type `Bar` and toggle h2
4. Reload page
5. Check log
6. Press newline
7. Type `* foo` and press newline
8. Type `* bar`
9. Trigger Move Line Up
10. Notice the lines getting merged
11. Undo
12. Notice that the bullets don't line up

**Expected behavior**
Not broken like on 0.74.3, but also no forced newline above headings like on 0.74.3.

**Screenshots**
For clarity: images are _followed_ by captions in italics.

![image](https://user-images.githubusercontent.com/26069787/155960217-1dc72e17-e94e-491b-a77f-9cd5080a2962.png)
_After number 9_

![image](https://user-images.githubusercontent.com/26069787/155960671-9ef0db51-1080-441b-b833-48dd6e49bffa.png)
_After undo_

![image](https://user-images.githubusercontent.com/26069787/155960786-f776b861-172a-4ebd-aa0e-1967ceeaa477.png)
_For comparison: on 0.74.3, the bullets don't break; the reason is revealed after a page reload, as an empty line appears above the header._

**Environment (please complete the following information):**
 - Version d7078e5162565a1495f3807130f6135c9e290962
 - OS: linux

**Additional context**
A test is available: https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/1960#issuecomment-1054447152

Debug log after first reload:
```
DEBUG: Action: apply_format_h2
DEBUG: Action: apply_format_h2 (toggle_format action)
DEBUG: Action: reload_page
DEBUG: Saving page: Home:NewTest
DEBUG: Store page: Home:NewTest
WARNING: Missing "\n" before new block (h)
```

Debug log after the rest of the steps:
```
DEBUG: Action: move_line_up
WARNING: Missing "\n" before new block (h)
```

**Comment by introt** [comment]
While drafting a test, I noticed two things:

* Unlike other tags, the end tag is before the newline: `<line>--------------------</line>\n`
* I really dislike the change to put the newline before the end tag

**Comment by introt** [comment]
After some amount of back-and-forth between `linesorter.TestLineSorterWindowExtension` and `pageview.TestTextView`, I came up with the following tests:

The first one reproduces the bullet bug, but is completely unnecessary going forward as the bug only arises when the plugin is presented with invalid input:

```python3
    def testBulletsAfterHeadingAfterLine(self):
        # doesn't err on 0.74.3
        # (when modified to account for parsetree differences)
        self.set_buffer(self.buffer, '''\
Foo
<line>--------------------</line>
<h level="2">Bar
</h><li bullet="*" indent="0"> foo
</li><li bullet="*" indent="0"> bar</li>''') # XXX: no newline on either side of </li>
        self.place_cursor(20)
        self.extension.move_line_up()
        self.assertBufferEquals(self.buffer, '''\
Foo
<line>--------------------</line>
<h level="2">Bar
</h><li bullet="*" indent="0"> bar
</li><li bullet="*" indent="0"> foo</li>''')
```

Anyhow, it's always nice to see such a faithful reproduction:

```diff
AssertionError: '<?xm[144 chars]="0"> bar• foo\n</li></zim-tree>' != '<?xm[144 chars]="0"> bar\n</li><li bullet="*" indent="0"> foo</li></zim-tree>' 
  <?xml version='1.0' encoding='utf-8'?>                                                                                                             
  <zim-tree raw="True">Foo                                                                                                                           
  <line>--------------------</line>                                                                                                                  
  <h level="2">Bar                                                                                                                                   
- </h><li bullet="*" indent="0"> bar• foo                                                                                                            
?                                   -----                                                                                                            
+ </h><li bullet="*" indent="0"> bar                                                                                                                 
- </li></zim-tree>+ </li><li bullet="*" indent="0"> foo</li></zim-tree>
```

---

The second test starts with some copypasta from `testTyping`. It can either be included, or, as the todos in the aforementioned test case recommend, properly split off as its own test. The test as follows represents the current buggy behavior, and should be altered with the missing `\n` to confirm the effectiveness of implemented fixes.

```python3
    def testHorizontalLineHeaderBulletIssue(self):
        view = TextView(self.preferences)
        notebook = self.setUpNotebook()
        page = notebook.get_page(Path('NewTest'))
        buffer = TextBuffer(notebook, page)
        view.set_buffer(buffer)
        undomanager = UndoStackManager(buffer)

        # Need a window to get the widget realized
        window = Gtk.Window()
        window.add(view)
        view.realize()

        press(view, 'Foo\n')
        start, end = buffer.get_bounds()
        self.assertEqual(buffer.get_text(start, end, True), 'Foo\n')
            # Just checking test routines work
            
        press(view, '---\n')
        buffer.toggle_format_tag_by_name('h2')
        press(view, 'Bar')
        press(view, '\n* foo\n* bar')
        tree = buffer.get_parsetree(raw=True)
        self.assertEqual(tree.tostring(), '''\
<?xml version='1.0' encoding='utf-8'?>
<zim-tree raw="True">Foo
<line>--------------------</line>
<h level="2">Bar
</h><li bullet="*" indent="0"> foo
</li><li bullet="*" indent="0"> bar</li></zim-tree>''')
# I suppose a '\n' is missing here ^ 
```
---
Interestingly, the only time I encountered the `WARNING: Missing "\n" before new block` error while writing these tests was when I miscopied the parsetree from the `pageview` tests to the `linesorter` tests.

**Comment by jaap-karssenberg** [comment]
Will fix.

In my opinion, the `<line>` element should not have text at all - it is like an embedded object without content.

**Comment by introt** [comment]
Needs a newline for moving lines as well:

![image](https://user-images.githubusercontent.com/26069787/156244186-0ac459b3-d619-459e-8ed9-62eecaea1162.png)

![image](https://user-images.githubusercontent.com/26069787/156244259-510fa6ae-102d-4e2d-ae24-a00b90999080.png)
