### ISSUE TITLE
Update custom tools documentation about modifying wiki content using temporary selector %f

### ISSUE THREAD

**Issue by Sylvain303** [zim-desktop-wiki/zim-desktop-wiki#1966]
**This is a documentation feature it seems to work as expected**

Following #969

I was in the same issue. I was using `%s` (path to wiki page) to modify page in some previous version of zim, within my custom tool call. May be, it has always been `%f` (temporary file) for triggering auto reload, I'm not sure.

If your custom tool modify the Zim page it has to be done in `%f` (temporary file), that will  trigger auto-reload.

[Actual documentation for custom Tools](https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/789e259c5be2862a1e27c27fa1b3d4c04a692462/data/manual/Help/Custom_Tools.txt) (master branch at the time of creating the issue)

> _Then there is the checkbox **Command does not modify data**. Enable this option if your tool only read data but does not modify it. In that case zim will execute the application in the background and keep running. Otherwise, if your tool does modify data, zim has to wait for it to finish and reload the current page_.

What could be added (text suggestion):

> When your custom tools is modifying the wiki page and you want to trigger a page reload, use `%f` (temporary page copy) as a destination file. Zim will compare the source and destination and trigger a page reload if some changes has been made. You will loose actual cursor position and scroll offset.

Some extra link to the git repository pointing to the related code could be some good extra informations too.
* custom call code
* reload trigger code
* sample next step: write a plugin code to access advanced feature

**Comment by jaap-karssenberg** [comment]
I don't think this is a documentation fix - instead the `%s` behavior should be treated as a bug. If the source is modified, zim should reload the page, else you get errors when you next try to edit it.

**Comment by jaap-karssenberg** [comment]
Based on code review there is no special handling of "`%f`" versus "`%s`". If the option "Command does not modify data" is not checked the page is always reloaded based on timestamp checking after the tool has run.

Just tested it with "gedit %s" as custom tool and does update + reload the file as expected.

Closing this ticket, because documentation update is definitely not the way to go.
