### ISSUE TITLE
Trailing quote breaks URL link

### ISSUE THREAD

**Issue by nelas** [zim-desktop-wiki/zim-desktop-wiki#1976]
**Describe the bug**
When an URL is surrounded by quotes, the trailing quote is recognized as part of the URL. This breaks the link for most sites.

**To Reproduce**
1. Surround URL with quotes (single, double, straight, or curly)
2. The trailing quote will become part of the link
3. Click on the URL link
4. See 404 on browser

**Example**
Here's an example of what I have on my notes:

Expected rendering:
url = "http://www.biodiversitylibrary.org/item/92582"

Current rendering:
url = "[http://www.biodiversitylibrary.org/item/92582"](http://www.biodiversitylibrary.org/item/92582")

**Expected behavior**
That trailing quotes don't get wrapped into the link.

**Environment (please complete the following information):**
 - Version 0.74.3-SNAPSHOT-t202203041844~ubuntu21.10.1
 - OS Linux/Ubuntu

**Comment by jaap-karssenberg** [comment]
Agree it needs fixing, but it is not an issue with the development branch
