### ISSUE TITLE
Allow notebook document root to be relative to notebook folder location

### ISSUE THREAD

**Issue by brandonmack111** [zim-desktop-wiki/zim-desktop-wiki#198]
I use zim frequently in conjunction with Google Drive Sync. It's not necessarily designed to work in this way, but it easily could (and be made more _portable_ in general) if the notebook root was either:

1. able to be set to a path relative to the opened directory (such as `../`, which is what I would like to use)
**or**
2. defaulted to the opened directory when left empty, such that links starting with `/` link to the base of the notebook structure, rather than the OS root. The OS root could still be accessed with `file:///`, which is really more correct anyhow.

**Comment by Osndok** [comment]
I've been musing about a similar concept for aggregating zim repos as git submodules (or subtrees), which would probably need a similar mechanism.

**Comment by jaap-karssenberg** [comment]
Afraid I don't understand the issue in this use case - what is limiting when you when you use a notebook on a shared drive ?

**Comment by brandonmack111** [comment]
In this particular case, Google Drive sync is the particular use case, but the problem also applies with shared drives that might be assigned a different drive letter in different machines.

So imagine it like this. On computer a, I have drive installed in the default windows install directory. That's C:\Users\<username>\Google Drive. Alright, so I put my Zim wiki in there. Now, let's say my username is Bob. That means, on my computer, my directory is C:\Users\bob\Google Drive\zimWiki or whatever. I set that as the root for my wiki, since for whatever reason my wiki is deeper into the structure, and I want to be able to access files out here - most likely for something like linking the same images from multiple subpages inside my wiki. 

Now, on computer b, I also have Google Drive installed in the default directory - however my username here is Fred. Even if I have the shared drive folder located in the exact same place inside MY Google Drive directory (which is not necessarily the case), my Google drive directory is instead C:\Users\fred\Google Drive\zimWiki, and the root directory is broken, the images don't work, and non-relative links are also broken.

If I had a relative root, however, it would work regardless of the location of the file on my machine, as long as the notebook's directory heirarchy is left untouched. I could use /../../../ instead of C:\Users\bob\Google Drive\zimWiki as my root and have no problems.

The same applies to a shared drive in windows. User a may have it labelled as drive F:\, but user b already had a drive F, so he mapped it to G:\. Now, when user a sets the root path to F:\zimWiki, it doesn't work for user b, who has the wiki in G:\zimWiki\

In both cases, a relative root would solve the problem.

**Comment by jaap-karssenberg** [comment]
So you are thinking about links to files and pages from a specific wiki page, correct ?

In that case you can already use relative links with "./" or "../" as in your example as long as the link is within the notebook folder.

For links outside the notebook folder you can use the "document root" property - this allows you to define a specific folder as the root for links starting with "/"  (see the manual for more details).

Regards,

Jaap

**Comment by jaap-karssenberg** [comment]
I believe what you are looking for is the "document root" that can be set in the notebook properties (see http://zim-wiki.org/manual/Help/Properties.html).  This root can be relative to the notebook folder.

**Comment by brandonmack111** [comment]
I specifically stated that I was talking about the document for, and that it does *not* work with relative paths. I have tried it (specifically on Windows) and it did not work correctly. That was the point of the entire issue...

**Comment by jaap-karssenberg** [comment]
Sorry but I can't find the term "document root" in any of the above comments. You are talking about a "notebook root" which is not a term I recognized to mean the same thing. I feel your frustation on not being understood, but please consider that I'm honestly trying to make sense of the request and translate it into what it means in the application code.

Re-reading your posts I'm still not sure that we are talking about the same thing. But will look into allowing the "document root" to be relative to the "notebook location". Specifically this mean one can have a parent folder of the notebook as "root" and link to files below that root with a "/file" syntax. 

Be aware that for links within the notebook this is not needed. One can always link relative to the page location to other folders within the notebook. E.g. images should work if they are part of the notebook. You do not need a "document root" for that.

**Comment by krizoek** [comment]
if your using linux you can use symbolic link

**Comment by jaap-karssenberg** [comment]
This should work in recent versions, although need to fix #1146 to allow configuring it
