### ISSUE TITLE
Themes no longer functional

### ISSUE THREAD

**Issue by atyfaz** [zim-desktop-wiki/zim-desktop-wiki#1984]
I've tried everything I can to make Zim use a dark theme (which I really need if I intend to use the program extensively) and it just doesn't seem like it works anymore.

I tried to use the instructions on this link ( [https://github.com/jaap-karssenberg/zim-wiki/wiki/Set-a-dark-theme-and-background](https://github.com/jaap-karssenberg/zim-wiki/wiki/Set-a-dark-theme-and-background) ) but it seems that this no longer works as gtk-2.0 is no longer in Zim.
![image](https://user-images.githubusercontent.com/63529865/158900978-bf71b24c-e41b-43db-affa-a15d3892532c.png)

Then I found this page ( [https://github.com/jaap-karssenberg/zim-wiki/wiki/Theme-manager-(Windows-Version-of-Zim)](https://github.com/jaap-karssenberg/zim-wiki/wiki/Theme-manager-(Windows-Version-of-Zim)) ) and tried installing the plugin. I placed the plugin in several seemingly applicable locations but it does not show up in Zim's list of plugins.

![image](https://user-images.githubusercontent.com/63529865/158901334-bbb8f961-09fa-4dda-841d-8fda7be84dd6.png)
![image](https://user-images.githubusercontent.com/63529865/158901916-28c952be-aa39-4dac-978b-8b6b57119cb0.png)

I've found various theme folders in the program file system but nothing i do seems to work.
![image](https://user-images.githubusercontent.com/63529865/158902065-2cb7dc6f-c20b-4e95-9dc5-afbbe836e7ef.png)

I even went into gtk 3.0's folder and replaced all the text in all the xml's with the text found in solarized-dark.xml, so that all the themes are solarized dark.
![image](https://user-images.githubusercontent.com/63529865/158902249-ee08c968-691b-459b-a804-bf3e44cc2136.png)

I'd really like to use this program over commercial alternatives, but excessive eye strain is a bit of a deal breaker for me. If there's anything I can do to get a dark theme working, please let me know.

**Comment by dehesselle** [comment]
Create a `gtk-3.0/settings.ini` file in Zim's configuration folder with the content
```ini
[Settings]
gtk-application-prefer-dark-theme=1
```

source: https://unix.stackexchange.com/a/71255

**Comment by atyfaz** [comment]
that works, thank you.
