### ISSUE TITLE
Unable to search content after importing 4,000 files

### ISSUE THREAD

**Issue by goodev2021** [zim-desktop-wiki/zim-desktop-wiki#1990]
**Describe the bug**
I have imported 4,000 text files in zim. The files got successfully imported without any issues. 

**To Reproduce**
1. Import any 4,000 text files
2. Do the search - It takes a very huge time and hangs.

**Expected behavior**
The search should bring the results in less than a second

**Screenshots**
Reproduceable anytime

**Environment (please complete the following information):**
Latest version, Tested with windows 10 and windows 11

**Additional context**
Looks the root cause is due to the content should be indexed for full text search

**Comment by introt** [comment]
Known issue, tracked by #64. You can try out the [Instant Search plugin](https://github.com/e3rd/zim-plugin-instantsearch) in the meanwhile.
