### ISSUE TITLE
Virtual desktop switching moves main window on Windows 10

### ISSUE THREAD

**Issue by fmos** [zim-desktop-wiki/zim-desktop-wiki#2004]
When switching between virtual desktops on Win 10 with Windows+Ctrl+Right/Left Arrow, the Zim main window reacts as if Windows+Right/Left Arrow (without Ctrl) had been pressed and undocks/moves accordingly. 

**To reproduce:**
1. Create a second virtual desktop if you don't have one already (tap Windows-Tab, click "new desktop")
2. Move to the first virtual desktop (tap Windows+Ctrl+Left Arrow until you are there)
3. Start Zim 
4. Snap Zim to the left half of the screen (tap Windows+Left Arrow)
5. Switch to next virtual desktop (tap Windows+Ctrl+Right Arrow)
6. Switch back to previous virtual desktop (tap Windows+Ctrl+Left Arrow)

Zim is now floating free somewhere on the desktop.

**Expected behavior**
Zim should have stayed snapped to the left half of the screen.

**Environment**
 - Version 0.74.3, official download
 - OS: Windows 10

**Context**
I suspect that this behaviour is due to a default GTK hotkey for snapping. It seems, the Windows-specific hotkeys for snapping left and right (Windows+Left/Right Arrow) are active *in addition to* any GTK hotkeys, and not replacing them.

General problems with snapping windows have been mentioned by @arigit in https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/840#issuecomment-500281626_

**Comment by fmos** [comment]
Interestingly, the pyGTK example I tested ([application_example.py](https://github.com/sebp/PyGObject-Tutorial/blob/master/examples/application_example.py)) behaves differently, snaps properly and stays in place when switching virtual desktops.

Unfortunately, my testing setup is different from my production setup (from which I reported this issue): Win 11 on ARM running within Parallels on a M1 MacBook. Turns out that on this testing setup, Zim does not react at all to any hotkeys, neither for snapping nor for switching desktops. Hence, strictly speaking I could not reproduce the behaviour reported above. 

However, it is noteworth that the pyGTK example behaves correctly on all hotkeys (i.e. it does support snapping and stays in place on desktop switching). 

As you can see in the screeshot below, the window border of the pyGTK example looks like rendered by Windows, while Zim apparently uses Client Side Decorations. Please note that to the best of my memory I did not set the environment variable GTK_CSD in this setup at all (neither 0 nor 1). The applications behave differently nevertheless.

![Screenshot 2022-04-13 080814](https://user-images.githubusercontent.com/825364/163131997-b7a16877-ba12-4eaf-98e2-3ea09693fcca.png)

**Comment by introt** [comment]
Thanks for your testing effort, seems we've got some ground to cover. Not reacting to hotkeys at all on Win11 might be a separate issue, but in any case closely related. Did you install Zim on Win11 using the installer, and does it behave any differently if run from source via MSYS2?

`application_example.py` seems to define a maximize action which we don't seem to manually do, but then again I have no idea if tiling is equal to maximizing into bounds given by the window manager, and thus even relevant.

**Comment by introt** [comment]
> As you can see in the screeshot below, the window border of the pyGTK example looks like rendered by Windows, while Zim apparently uses Client Side Decorations. Please note that to the best of my memory I did not set the environment variable GTK_CSD in this setup at all (neither 0 nor 1). The applications behave differently nevertheless.

Hold up, could you try Jaap's suggestion from #1836? Might solve the Win11 issue.

> Have you tried whether using the classic window border gives different results? You can configure this with the "toolbar" plugin.

**Comment by fmos** [comment]
> Did you install Zim on Win11 using the installer, and does it behave any differently if run from source via MSYS2?

I tried both, they behave the same.

> Have you tried whether using the classic window border gives different results? You can configure this with the "toolbar" plugin.

Just tested in production: no difference in behaviour. The "classic window border" still looks different than the native Windows 10 border of the example application.

**Comment by introt** [comment]
> Just tested in production: no difference in behaviour. Btw: the "classic window border" still looks different than the native Windows 10 border of the example application.

Oops, GitHub suggestions messed up the issue link - I meant #1639 (Windows window interaction problems). According to users' comments there, enabling the classic window border should result in different tiling behavior (not related to virtual desktops) -- could you test if it restores the hotkeys & snapping functionality on Win11?

**Comment by fmos** [comment]
Enabling the tool bar plugin an disabling the topmost checkbox in its configuration to switch to classic window border solved the issue on Win 11. The window now behaves as expected: snapping works and there is no interference with virtual desktop switching. :) 

![Screenshot 2022-04-14 070215](https://user-images.githubusercontent.com/825364/163317096-d9563dd6-ccf5-4416-9fbb-ba0c967567a6.png)

If only this would be the same on Win 10.

**Comment by fmos** [comment]
Now back on my production machine. There, GTK_CSD was set to =1. I deleted the variable, logout/login: the issue is gone. :)))

Thanks @introt for going along!!

For anyone else with similar window manager issues on Window, try the following:
- Enable the Toolbar plugin
- In the plugin configuration disable/uncheck the checkbox on "Show controls in the window decoration"
- Make sure the environment variable GTK_CSD is not set (e.g. running `set` on the command prompt and looking for it).

**Comment by introt** [comment]
My pleasure @fmos - thank you for doing all the actual work!

I'm going to open a packaging ticket for changing the defaults - imo funtion > form OOTB.
