### ISSUE TITLE
Command line bug for "Fossil open"

### ISSUE THREAD

**Issue by pchemguy** [zim-desktop-wiki/zim-desktop-wiki#2005]
**Describe the bug**
Missing flag "--keep" in the *checkout* method in zim/plugins/versioncontrol/fossil.py

**To Reproduce**
1. Create a new notebook.
2. Add some pages.
3. Try to save a version with Fossil.
4. Throws an error from the "open" command due to non-empty notebook folder and missing "--keep" flag.

**Expected behavior**
The program should properly initialize and open a Fossil repo.

**Screenshots**

**Environment (please complete the following information):**
 - 0.74.3
 - Windows 10
 - Language: English

**Comment by introt** [comment]
Thank you for the very detailed bug [reports](https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/2006)! Took me a second to adjust to the differences between `fossil`'s and `git`'s initialization & committing workflows (as well as _committing_ to reading the `fossil` manual...) but I believe I've now successfully squashed these bugs.

Please try out PR #2008 and let me know if it's adequate. Thanks!

**Comment by pchemguy** [comment]
I use the binary release on Windows. I could neither run Zim from the source from an MSYS environment nor build it. I probably can figure it out, but, unfortunately, I do not really have time to troubleshoot this staff. I would need a compiled version to test its behavior.

**Comment by introt** [comment]
No worries, I'm pretty sure it's alright, and at the very least it shouldn't be more broken ;)
However, if you already happen to know how to install plugins, you can just drop the modified plugin[0] into your plugins folder and Zim should pick it up from there, no compilation needed!

0. https://github.com/zim-desktop-wiki/zim-desktop-wiki/tree/a8311a003f2f981f47efed0d3508e99888772d64/zim/plugins/versioncontrol (just plonk the whole `versioncontrol` directory into the plugin folder)

**Comment by pchemguy** [comment]
The binary release has "ZIMROOT\share\zim\plugins" folder with Python modules, but the application does not really care about it apparently (removing "ZIMROOT\share\zim\plugins\versioncontrol" has no effect). When I press "Open plugins folder" button, it creates "zim\plugins" folder inside the "Data" folder, which is not something I would want. But even copying the modified "versioncontrol" inside that folder has no effect. It appears that plugin loading does not really work (built-in plugins are usable, but it seems that the plugins are not loaded from sources).

**Comment by introt** [comment]
That's too bad. Between this, plugin dependency issues and gtk stuff, I guess I'll have find the time to set up a win vm. Thanks for trying though!
