### ISSUE TITLE
Changing defaults on Windows to work around upstream Gtk window issues

### ISSUE THREAD

**Issue by introt** [zim-desktop-wiki/zim-desktop-wiki#2007]
**Is your feature request related to a problem? Please describe.**
[Window hotkeys & snapping don't work OOTB on Windows 11](https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/2004#issuecomment-1097707397). Switching virtual desktops on Windows 10 also affects tiling (#2004). Changing the defaults seem to also fix other issues experienced by users (see #1639).

**Describe the solution you'd like**
Changing the defaults on new Windows installs to those listed by @fmos, as suggested by @quctex:

> - Enable the Toolbar plugin
> - In the plugin configuration disable/uncheck the checkbox on "Show controls in the window decoration"
> - Make sure the environment variable GTK_CSD is not set (e.g. running set on the command prompt and looking for it).

**Describe alternatives you've considered**
_Only_ documenting the problem in the manual and on the download page. Should be mentioned in the manual in any case.

> [It wasn't clear from the tool bar plugin options that disabling the "show controls in window decoration..." would have this effect.](https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/1639#issuecomment-1000342691)

Alternatively, porting to Gtk4 :P

**Additional context**
See the linked issues.

**Comment by introt** [comment]
Related: Using GitHub actions to build the Windows installer: #1766

@pdecat are you available to tackle this?

**Comment by dehesselle** [comment]
> - Enable the Toolbar plugin
> - In the plugin configuration disable/uncheck the checkbox on "Show controls in the window decoration"

If this can be done from inside Zim (and not by an external setup/installer) it would be useful on macOS as well.

**Comment by introt** [comment]
> If this can be done from inside Zim (and not by an external setup/installer) it would be useful on macOS as well.

Should be doable - do you know the correct way to distinguish Linux and macOS, as os.name returns `posix` for both? `zim.py` seems to just try importing NSBundle.

**Comment by dehesselle** [comment]
You were very close. Use `os.uname().sysname` to get `Darwin` for macOS and `Linux` for Linux.

**Comment by introt** [comment]
Thanks!

Default plugins are listed here, and the toolbar is included. There's also code that should've prevented #2003 - what's up with that?

https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/1b9d3c14b2a2c7184a28ec5cb93fccac2f321b95/zim/main/__init__.py#L305-L314

I'll open a draft PR for the patch.
