### ISSUE TITLE
Plugin installation: There was a problem loading this plugin

### ISSUE THREAD

**Issue by srikandi77** [zim-desktop-wiki/zim-desktop-wiki#2024]
I have download now button plugin and try to  follow up the instruction in the plugin wiki. 
My installation: 
Zim Wiki desktop on my harddisk: D:\Programs\Software

I put plugin file to %AppData%\Roaming\zim\data\zim\plugins
the plugin name shows but when i clicked it there is information There was a problem loading this plugin

NOte: zim version 0.74.3

How do I make the plugin worked?

**Comment by introt** [comment]
Hi! Sorry, but this is not the place for third-party plugin issues. You may reach the plugin developer over at [Osndok/zim-plugin-nowbutton](https://github.com/Osndok/zim-plugin-nowbutton). Given that the plugin hasn't been updated for years, you might want to give one of its forks a try. I'll remove it from the plugin wiki for the time being.
