### ISSUE TITLE
turn off the system beep sound

### ISSUE THREAD

**Issue by corn-nut-birdie** [zim-desktop-wiki/zim-desktop-wiki#2033]
in Win 10, when pressing Ctrl + End twice, or Ctrl + End then PageDown, i.e. scroll down while already at the end of the text, it would trigger a system beep sound, kind of redundant. 

Please remove that tip sound, or provide an option to disable that.

**Comment by introt** [comment]
Workaround: add the following to your `settings.ini` (under `gtk-3.0`, wherever that's on Windows)

```
[Settings]
gtk-enable-event-sounds = 0
```

from https://bbs.archlinux.org/viewtopic.php?id=261938

**Comment by mu-us61** [comment]
the beeping also happens in debian 11 KDE , on a note just press down and system beeps
edit: zim note version : 0.75.0

**Comment by jaap-karssenberg** [comment]
This is a Gtk setting, not an application setting - see comment above how to edit Gtk ini file

However, there is already implemented a hidden preference in zim (needs documentation) that also turns off this sound. Try setting "gtk_bell=False" in the zim preferences config file.

**Comment by introt** [comment]
> However, there is already implemented a hidden preference in zim (needs documentation) that also turns off this sound. Try setting "gtk_bell=False" in the zim preferences config file.

https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/4110a13c391c24aa92c8b4edfc77bb79563d4368/zim/gui/mainwindow.py#L446-L452

This should be the default; if you're hearing the bell, please report whether you have `gtk_bell=False` in `preferences.conf` under `[GtkInterface]`.

**Comment by ZbyszekS** [comment]
Unfortunatelly it doesn't work. Sound is still heard when top or bottom of the not is being "hit". Windows 10, Zim 0.75.2. 
1. ~\AppData\Local\gtk-3.0\settings.ini 
[Settings]
gtk-enable-event-sounds=0
gtk-application-prefer-dark-theme=1

2. ~\AppData\Roaming\zim\config\zim\preferences.conf
[GtkInterface]
show_headerbar=True
toggle_on_ctrlspace=True
always_use_last_cursor_pos=True
gtk_bell=False

**Comment by greenyleaf** [comment]
Now my solution is just that, Control Panel -> Sound -> ... mute all sound.
