### ISSUE TITLE
Weird characters show in Zim wiki

### ISSUE THREAD

**Issue by reagle** [zim-desktop-wiki/zim-desktop-wiki#2042]
For some reason, many pages in a notebook is showing odd characters on my pages.

<img width="281" alt="Screen Shot 2022-05-11 at 10 27 02" src="https://user-images.githubusercontent.com/596814/167873856-8b78d514-d14c-423e-ac44-18dd2cc0da0f.png">

When I edit [the source][ts], Sublime Text is showing UTF-8 and `chardetect` shows "ascii with confidence 1.0". (That is, it's only using the ASCII subset of UTF-8.) The [resulting HTML][rh] also looks fine. So I'm not sure what is going on.

[ts]: https://reagle.org/joseph/zim/Teaching/Best_Practices/Learning/Bibliography.txt
[rh]: https://reagle.org/joseph/zwiki/Teaching/Best_Practices/Learning/Bibliography.html

Please try putting [the source][ts] in a notebook of yours, does it look weird?

Using 0.74.3 (120) on macOS 12.3.1 21E258 arm64. The metadata for this page, for example, shows:

    Content-Type: text/x-zim-wiki
    Wiki-Format: zim 0.4
    Creation-Date: 2011-11-28T15:02:36-05:00

**Comment by introt** [comment]
Can't reproduce on Linux. Given #321, please post your `style.conf` - your modifications might be the trigger. May be macOS specific.

**Comment by reagle** [comment]
Style is attached. The odd thing is I don't have this problem with my notebook I use daily. This is with a less frequently used notebook.

`/Users/reagle/Library/Application Support/org.zim-wiki.Zim/zim/style.conf`

[style.conf.txt](https://github.com/zim-desktop-wiki/zim-desktop-wiki/files/8693708/style.conf.txt)

**Comment by dehesselle** [comment]
I cannot reproduce this on macOS.
