### ISSUE TITLE
Windows Installer doesn't set DisplayVersion

### ISSUE THREAD

**Issue by ajkajk** [zim-desktop-wiki/zim-desktop-wiki#2077]
The Windows installer sets up fields in `[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\404fbece-3a0a-4f4f-b1f1-82ce46af9696]` e.g. `"DisplayName"="Zim Desktop Wiki"`. However it doesn't currently set up a DisplayVersion string e.g. `"DisplayVersion"="0.74.3"`.

As a result the windows package manager (winget) can't determine the currently installed version.  This means it attempts to update zim as the version available is always more promising than the "unknown" version. The effort in making zim available in the "winget" package source effectively does not support detecting if a new version of zim is available for update.  

Would it be possible to change the installer to set up a `DisplayVersion` string and support use of winget to update zim?

**Comment by introt** [comment]
Thanks for the report!

`grep` returns

    windows/src/zim-installer.nsi:        WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${UNINSTKEY}" "DisplayName" "${APPNAME}"

so the fix is likely just adding another `WriteRegStr` - could you confirm this to work and open a PR? I don't have a Windows box handy.

**Comment by ajkajk** [comment]
Thanks for your response.

I'll give it a go.  However, I have no experience in any of this, so it will likely take some time to get up to speed....

**Comment by introt** [comment]
You can find the steps here: https://github.com/zim-desktop-wiki/zim-desktop-wiki/tree/master/windows

Instead of `git clone https://github.com/zim-desktop-wiki/zim-desktop-wiki.git`, run `git clone https://github.com/introt/zim-desktop-wiki.git --branch displayversion` to fetch my patched version with the fix.

Thanks for taking initiative!

**Comment by ajkajk** [comment]
I've tried building the installer.  `build.sh` fails for me at line 168 `pip install PyGObject pyinstaller==3.6 # Fix pyinstaller version, latest has bug` i.e. nothing to do with the extra line in `zim-installer.nsi` 
I can run that `pip install` from the command line OK. I tried playing with the line in the script, including leaving it out altogether, but never got the environment set-up to create the installer.  
The error reported is `error: --plat-name must be one of ('win32', 'win-amd64', 'win-arm32', 'win-arm64')` I don't know what value is passed, or where it comes from.
Sorry.
Below is the log of the failure, followed by running the line that is reported as failing. 

```

...
Successfully installed pip-22.1.1
Collecting PyGObject
  Using cached PyGObject-3.42.1.tar.gz (718 kB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [38 lines of output]
      Collecting setuptools
        Using cached setuptools-62.3.2-py3-none-any.whl (1.2 MB)
      Collecting wheel
        Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
      Collecting pycairo
        Using cached pycairo-1.21.0.tar.gz (340 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Building wheels for collected packages: pycairo
        Building wheel for pycairo (pyproject.toml): started
        Building wheel for pycairo (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        × Building wheel for pycairo (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [12 lines of output]
            running bdist_wheel
            running build
            running build_py
            creating build
            creating build/lib.mingw_x86_64-cpython-39
            creating build/lib.mingw_x86_64-cpython-39/cairo
            copying cairo/__init__.py -> build/lib.mingw_x86_64-cpython-39/cairo
            copying cairo/__init__.pyi -> build/lib.mingw_x86_64-cpython-39/cairo
            copying cairo/py.typed -> build/lib.mingw_x86_64-cpython-39/cairo
            running build_ext
            building 'cairo._cairo' extension
            error: --plat-name must be one of ('win32', 'win-amd64', 'win-arm32', 'win-arm64')
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for pycairo
      Failed to build pycairo
      ERROR: Could not build wheels for pycairo, which is required to install pyproject.toml-based projects
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
2022-05-28 14:06:02 UTC [    error] Error in /zim-desktop-wiki/windows/build.sh in function . on line 170
2022-05-28 14:06:02 UTC [     info] Cleaning up.
2022-05-28 14:06:02 UTC [     info] Done.

msajk@AJK-Desktop MINGW64 /zim-desktop-wiki/windows
$ pip install PyGObject pyinstaller==3.6
Requirement already satisfied: PyGObject in c:/sw/scoop/apps/msys2/2022-05-03/mingw64/lib/python3.9/site-packages (3.42.1)
Requirement already satisfied: pyinstaller==3.6 in c:/sw/scoop/apps/msys2/2022-05-03/mingw64/lib/python3.9/site-packages (3.6)
Requirement already satisfied: pywin32-ctypes>=0.2.0 in c:/sw/scoop/apps/msys2/2022-05-03/mingw64/lib/python3.9/site-packages (from pyinstaller==3.6) (0.2.0)
Requirement already satisfied: altgraph in c:/sw/scoop/apps/msys2/2022-05-03/mingw64/lib/python3.9/site-packages (from pyinstaller==3.6) (0.17.2)
Requirement already satisfied: setuptools in c:/sw/scoop/apps/msys2/2022-05-03/mingw64/lib/python3.9/site-packages (from pyinstaller==3.6) (59.8.0)
Requirement already satisfied: pefile>=2017.8.1 in c:/sw/scoop/apps/msys2/2022-05-03/mingw64/lib/python3.9/site-packages (from pyinstaller==3.6) (2021.9.3)
Requirement already satisfied: future in c:/sw/scoop/apps/msys2/2022-05-03/mingw64/lib/python3.9/site-packages (from pefile>=2017.8.1->pyinstaller==3.6) (0.18.2)


```

**Comment by introt** [comment]
Thanks for trying!

Looks like [pycairo](https://github.com/pygobject/pycairo/) is failing to install.

@fmos could you take a look at this please?

**Comment by ajkajk** [comment]
Just ran the sequence again in a fresh Windows 10 Sandbox with the same result.  I did notice there was an earlier error whilst installing mingw-w64-x86_64-adwaita-icon-theme  - "command (/usr/bin/bash /usr/bin/bash -c . /tmp/alpm_S2sAHe/.INSTALL; post_install 42.0-1 ) failed to execute correctly".
```
(63/84) installing mingw-w64-x86_64-librsvg                                                    [######################################################] 100%
Optional dependencies for mingw-w64-x86_64-librsvg
    mingw-w64-x86_64-gtk3: for rsvg-view-3 [pending]
(64/84) installing mingw-w64-x86_64-adwaita-icon-theme                                         [######################################################] 100%
error: command (/usr/bin/bash /usr/bin/bash -c . /tmp/alpm_S2sAHe/.INSTALL; post_install 42.0-1 ) failed to execute correctly
(65/84) installing mingw-w64-x86_64-atk                                                        [######################################################] 100%

```
Don't know if that is significant.

**Comment by introt** [comment]
Looks like the upstream packages' scripts are broken - hopefully they'll work that out on their own :)

**Comment by fmos** [comment]
> Thanks for trying!
> 
> Looks like [pycairo](https://github.com/pygobject/pycairo/) is failing to install.
> 
> @fmos could you take a look at this please?

Yes, I've been looking into this and found a workaround. Need to do some testing in the coming evenings and will then provide a PR.
