### ISSUE TITLE
Error when escape pressed in Insert Equation

### ISSUE THREAD

**Issue by Bad-At-Usernames** [zim-desktop-wiki/zim-desktop-wiki#2081]
**Describe the bug**
Sorry if this should be reported in a different repo (or has already been reported and I didn't notice).
Pressing the escape key in the insert equation window causes an error (and the "Looks like you found a bug" popup). 
This only happens with escape (not other non-character keys).

**To Reproduce**
1. Go to Insert > Equation
2. Press escape

**Expected behavior**
The window should close without inserting anything (and without the error popup :p)

**Environment**
 - Version: 0.74.3_1 (latest in xbps (on glibc)).
 - OS: Void Linux, glibc, x11
 - Language: English

**Error Message**
This is zim 0.74.3
Platform: posix
Locale: en_GB UTF-8
FS encoding: utf-8
Python: (3, 10, 4, 'final', 0)
PyGObject: (3, 42, 0)

======= Traceback =======
  File "/usr/lib/python3.10/site-packages/zim/gui/insertedobjects.py", line 435, in _action_handler
    model = otype.new_model_interactive(self.pageview, notebook, page)
  File "/usr/lib/python3.10/site-packages/zim/plugins/base/imagegenerator.py", line 54, in new_model_interactive
    ImageGeneratorDialog.run_dialog_for_model(parent, model, self.label, self.syntax)
  File "/usr/lib/python3.10/site-packages/zim/plugins/base/imagegenerator.py", line 320, in run_dialog_for_model
    model.set_from_generator(text, image_file)
  File "/usr/lib/python3.10/site-packages/zim/plugins/base/imagegenerator.py", line 141, in set_from_generator
    self.script_file.write(text)
  File "/usr/lib/python3.10/site-packages/zim/newfs/local.py", line 389, in write
    fh.write(text)
TypeError: write() argument must be str, not None

**Comment by introt** [comment]
Thanks for the report! #2083 fixes the error by making the esc press behave as if the user pressed "Cancel". This does still result in an empty widget being inserted into the buffer, but imo that's a separate issue.

**Comment by introt** [comment]
@Bad-At-Usernames we keep tickets open till the fix is included in a stable release, but thanks for being active!

**Comment by dehesselle** [comment]
@introt We need to talk about this - that would actually prevent us from using functionalities like "close on commit", which is a well established pattern among all platforms like GitHub, GitLab etc. and is what developers are expecting. I think the pattern should be "close issue once the fix hits the codebase", not a stable release.

**Comment by introt** [comment]
@dehesselle we already did; Jaap prefers the current way: https://github.com/zim-desktop-wiki/zim-desktop-wiki/discussions/1860#discussioncomment-2331565

**Comment by jaap-karssenberg** [comment]
By switching the "develop" branch as the main branch, we can now close on commit
