### ISSUE TITLE
TASKLIST plugin miss counts untagged tasks

### ISSUE THREAD

**Issue by garydee** [zim-desktop-wiki/zim-desktop-wiki#2092]
MacOS 12.4
Zim Desktop 0.74.3

When I open the Talks list plug-in the Tags list shows the same number of tasks under 'All Tasks' as it does under 'Untagged'. Even though there are tasks with tags, and the totals for each tag is correct. I would expect that the Untagged should reflect they number of open check boxes only.

**Comment by introt** [comment]
Hi, thanks for the report. I can't reproduce this on the latest `develop` with the reworked task list plugin, so I'm going to tag this as "fix available" - to be closed after the next release.
