### ISSUE TITLE
Crashes when trying to import a text file.

### ISSUE THREAD

**Issue by ebenezergoose** [zim-desktop-wiki/zim-desktop-wiki#2099]
I'm running Zim v 0.74.3 on Running on Ubuntu 20.04 LTS. I'm trying to import standard text file, with ".txt" extension, no spaces in file name. The import function crashes every time. 

To recreate go "File" > "Import" > select the file you want to import and click "Open" . 

A dialog appears headed "_Looks like you found a bug_", containing the following error message...

This is zim 0.74.3
Platform: posix
Locale: en_GB UTF-8
FS encoding: utf-8
Python: (3, 8, 10, 'final', 0)
PyGObject: (3, 36, 0)

======= Traceback =======
  File "/usr/lib/python3/dist-packages/zim/gui/widgets.py", line 3086, in do_response
    destroy = self.do_response_ok()
  File "/usr/lib/python3/dist-packages/zim/gui/uiactions.py", line 553, in do_response_ok
    page = import_file(file, self.notebook, path)
  File "/usr/lib/python3/dist-packages/zim/import_files.py", line 23, in import_file
    newfile = file.parent().new_file(file.basename + '~')
AttributeError: 'File' object has no attribute 'parent'

**Comment by jaap-karssenberg** [comment]
Need to verify on develop branch since file system code changed (fs ->
newfs module).

-- Jaap

**Comment by jaap-karssenberg** [comment]
Cannot reproduce on latest version

**Comment by m4hmudftw** [comment]
Fixed for me on 0.75.1, thanks !

**Comment by ebenezergoose** [comment]
Same here . Fixed on 0.75.1.

Thank you. :-)

**Comment by jaap-karssenberg** [comment]
Thanks for your confirmation!
