### ISSUE TITLE
Error messages not helpful when Diagram image file missing

### ISSUE THREAD

**Issue by vossenjp** [zim-desktop-wiki/zim-desktop-wiki#2102]
**Describe the bug**
If you have a Zim page with Graphviz/DOT code where the generated image file was deleted outside of Zim, you get odd and unhelpful error messages about that.

**To Reproduce**
1. Enable the "Diagram" plugin and make sure it's happy.
2. Use "Insert > Diagram" to create a diagram (sample code below).
3. Verify everything works in Zim.
4. Find the diagram file outside of Zim (`find /path/to/Zim/ -iname '*.png'`) and delete it.
5. Refresh the page in Zim.
6. The diagram will disappear.
7. Edit the Graphviz/DOT code but do not make changes, and hit OK.
8. Get a dialog that says:
```
An error occurred while generating the image.
Do you want to save the source text anyway?
[No][Yes]
```

Also, once that happens the included image in the Zim page gets very small (since it doesn't exist), so it's hard to click on it to hit "Edit" to get back into the Graphviz/DOT code editor.

**Work around:**
1. Click "Edit" on the image to get into the Graphviz/DOT code editor.
2. Make a change in the Graphviz/DOT code code, e.g., hit enter and then backspace.
3. Hit OK and it will now work.

Sample Graphviz/DOT code you can play with
```graphviz
digraph {
    deploy     [label="Deploy to production?", shape=box]
    is_friday  [label="Is it \n read-only \n Friday?", shape=diamond]
    no_deploy  [label="Do not deploy!",        shape=box]
    ok_deploy  [label="OK to deploy!",         shape=box]
    tgif       [label="Enjoy your weekend!",   shape=box, style=rounded]

    deploy    -> is_friday
    is_friday -> no_deploy  [label="yes"]
    is_friday -> ok_deploy  [label="no"]
    no_deploy -> tgif
    ok_deploy -> tgif
}
```

**Expected behavior**
1. Either Zim should provide a better error message,
2. Or, BETTER, it should notice a missing image file and just re-create it, ideally at index or page-open time, but at least at edit-code time.

**Environment (please complete the following information):**
- zim-0.74.3-t202205241835~ubuntu20.04.1 from PPA
- OS: Mint-20.3
- graphviz-2.42.2-3build2
- xdot-1.1-2

**Additional context**
This happens because of #793 & #1584.  Until I started using "Diagram" I had zero image files in my Zim dir, so when I accidentally paste an image (at least once every couple of weeks), I just run `find /path/to/Zim/ -iname '*.png' -delete` to nuke all images.  Obviosly that nukes the Diagram image too (might be better to output SVG instead of PNG anyway?).  No big deal, I thought, Zim or I will just re-create it when needed.

Except...there is no clue what is wrong, so other folks may be lost if this happens.  Even though I caused the root problem and knew what it was, I found the errors confusing and it took me some thinking to find the (trivially simple) workaround.

When run `zim --debug` errors are not helpful:
```
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck finished
DEBUG: Opening dialog "Edit Diagram"
DEBUG: Dialog response OK
DEBUG: Running QuestionDialog
DEBUG: Q: An error occurred while generating the image.
Do you want to save the source text anyway?
DEBUG: A: True
DEBUG: Closed dialog "Edit Diagram"
INFO: Remove file: /tmp/zim-0xlmyvcm/diagram.dot
INFO: Remove file: /tmp/zim-0xlmyvcm/diagram.png

(zim:239576): Gtk-WARNING **: 15:51:31.974: gtk_widget_size_allocate(): attempt to allocate widget with width -2 and height -2

(zim:239576): Gtk-WARNING **: 15:51:31.974: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node box, owner GtkVBox)

(zim:239576): Gtk-WARNING **: 15:51:31.974: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node box, owner GtkVBox)

(zim:239576): Gtk-WARNING **: 15:51:31.974: gtk_widget_size_allocate(): attempt to allocate widget with width -1 and height 0
```

**Comment by vossenjp** [comment]
You're welcome.  And @introt thanks for all the work you're doing to help out Jaap and the project.  I wish I had more time, but I do what I can.

For what it's worth, the above all sounds good to me, subject to someone having time to dive into the code.  :-)  And the work-around on this one is not that bad, so...

**Comment by introt** [comment]
No problem, it's for the common good :) I feel you, time is my limiting factor as well - issues like this one are trivial to solve on paper, but diving into the code invariably brings up other _quirks and features_ that take up a ton of time (https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/1242#issuecomment-1016827717 comes to mind) - so I'm currently spending my allowance mainly on triage. Hope to dive in deep again soon!
