### ISSUE TITLE
change locale setting for macOS

### ISSUE THREAD

**Issue by dehesselle** [zim-desktop-wiki/zim-desktop-wiki#2106]
This issue is to document a work in progress item and collect feedback from testers.

---

### back story
For the macOS app, the UI language is determined by using [`kCFLocaleIdentifier`](https://developer.apple.com/documentation/corefoundation/kcflocaleidentifier?language=objc) to set `LC_MESSAGES`.

### proposed change
According to the priority order as specified in GNU's [language variable documentation](https://www.gnu.org/software/gettext/manual/html_node/Locale-Environment-Variables.html) 
>  1. LANGUAGE
> 2. LC_ALL
> 3. LC_xxx, according to selected locale category: LC_CTYPE, LC_NUMERIC, LC_TIME, LC_COLLATE, LC_MONETARY, LC_MESSAGES, ...
> 4. LANG

we should rather set `LANG` and leave individual overrides (`LC_*` variables) up to user customization. This also fixes the unwanted side effect that currently setting `LANG` does not affect UI language which is unexpected behavior from a user's perspective.

### next steps
I will create a test release with the aforementioned changes and then revisit the scenario from https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/1910 again to check for side effects.

**Comment by dehesselle** [comment]
Hi @fladd,
can you tell me what settings you have here?
<img width="312" alt="language_region" src="https://user-images.githubusercontent.com/11375494/179568375-d6a5bbf9-8574-4e5a-9dc0-96afccf6fd0c.png">
I assume it's something like this, minus the German.

Also, can you test if / tell me how this build ([arm64](https://gitlab.com/dehesselle/zim_macos/-/jobs/2732344495/artifacts/file/Zim_arm64.dmg), [x86_64](https://gitlab.com/dehesselle/zim_macos/-/jobs/2732344494/artifacts/file/Zim_x86_64.dmg)) works without any locale adjustments in `zimapp.ini`?

**Comment by dehesselle** [comment]
Hi @fladd,
I'm pinging you once more in case this has gone under your radar. It's also ok if you're no longer interested. I' won't bother you again.

**Comment by dehesselle** [comment]
Closing, I'm going to do as I see fit.

**Comment by fladd** [comment]
Hi, sorry, didn't see this before. My settings are:

<img width="780" alt="image" src="https://user-images.githubusercontent.com/2971539/186753263-48314085-4879-429c-9ff1-afc58ce5d61b.png">
