### ISSUE TITLE
Cursor lost after pasting Source View 

### ISSUE THREAD

**Issue by tridian-tn** [zim-desktop-wiki/zim-desktop-wiki#2114]
**Describe the bug**
When cutting and pasting a Code Block, the cursor is no longer visible within that code block, unless you switch to another page and back again.

This behaviour is intermittent - it always happens on the page I'm working with. Sometimes, with the same code block on another notebook, I can't reproduce.

**To Reproduce**
1. Open Zim on Windows (not tested on other platforms). Ensure the Source View plugin is enabled
2. Open a page with a code block present
3. Cut and and then paste that code block
4. The cursor isn't then visible within that code block, until you switch to another page and back again

**Expected behavior**
You'd expect the cursor to always be visible within the code block 

**Screenshots**
![aLEARNING - Master 2022-07-23 19-18-44](https://user-images.githubusercontent.com/10810780/180618126-ee200d3f-6fcf-4854-8f2f-3a541c9ccb3a.gif)

**Environment (please complete the following information):**
 - Version 0.74.3
 - OS: Windows 10
 - Language: English/GB

**Additional context**

Debug log
```
INFO: Open page: aLEARNING (aLEARNING)
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck finished
DEBUG: Store page in background: aLEARNING
DEBUG: Index file: C:\Code\zim\aLEARNING.txt
DEBUG: Action: cut
DEBUG: Action: paste
DEBUG: Targets available for paste: [Gdk.Atom.intern("TIMESTAMP", False), Gdk.Atom.intern("TARGETS", False), Gdk.Atom.intern("MULTIPLE", False), Gdk.Atom.intern("SAVE_TARGETS", False), Gdk.Atom.intern("UTF8_STRING", False), Gdk.Atom.intern("COMPOUND_TEXT", False), Gdk.Atom.intern("TEXT", False), Gdk.Atom.intern("STRING", False), Gdk.Atom.intern("text/plain;charset=utf-8", False), Gdk.Atom.intern("text/plain;charset=CP1252", False), Gdk.Atom.intern("text/plain", False)], we want parsetree
DEBUG: Requesting data for ('text/x-zim-parsetree', 0, 1) -- using set_with_data() workaround
DEBUG: Store page in background: aLEARNING
DEBUG: Index file: C:\Code\zim\aLEARNING.txt
DEBUG: Store page in background: aLEARNING
DEBUG: Index file: C:\Code\zim\aLEARNING.txt
```

Page source:

```
Content-Type: text/x-zim-wiki
Wiki-Format: zim 0.6
Creation-Date: 2022-07-23T19:03:39+01:00

====== aLEARNING ======
Created Saturday 23 July 2022



Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
{{{code: lang="sql" linenumbers="True"
WITH dupRank as (
      SELECT Id, RANK() OVER (PARTITION BY MessageId ORDER BY Id ASC) AS rnk
      FROM MessageLog
    )
    DELETEds
      FROM [dbo].[MessageLog]ds
      WHERE Id IN (SELECT Id FROM dupRank WHERE rnk > 1)ds
}}}
```

**Comment by introt** [comment]
Hi! Thanks for the thorough report. Sounds a lot like #1715 - could you try reproducing the issue using the steps laid out here: https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/1715#issuecomment-1008877834?

**Comment by tridian-tn** [comment]
Thanks @introt

It looks like I've logged a duplicate. I'll take a look in the next day or two and if it's the same I'll add info to the other issue and close this one

**Comment by tridian-tn** [comment]
Issue report copied to https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/1715#issuecomment-1198964654
Closing this one
