### ISSUE TITLE
Opening a page causes other nodes to automatically close

### ISSUE THREAD

**Issue by zogommog** [zim-desktop-wiki/zim-desktop-wiki#2119]
**Description**
When left clicking a node to open page details, other open nodes in the hierarchy of nodes for other branches automatically close. This may not be a bug, but I do not recall it always behaving this way, and it is very frustrating when you need to keep re-opening node branches you've already deliberately opened and may need to move information between pages in different branches of the hierarchy of nodes.

**To Reproduce**
1. Create several nodes and sub-nodes with different branches and a few levels deep.
2. Open the nodes with the arrow icons into two or more different paths into the hierarchy.
3. Left click on a node to view the contents of a page, and other nodes from a different branch automatically close.

**Expected behavior**
I expect that open branches of nodes should remain open until manually closed.

**Environment (please complete the following information):**
Version 0.73.5
X86_64 GNU/Linux - Debian Bullseye 

**Additional context**
I filed this as a bug because I don't recall this behavior in the past and it is the single most frustrating issue I contend with at present. If it were to be a "feature", the feature would be an option to toggle this behavior.

**Comment by introt** [comment]
Hi! Thanks for the report. This sounds like unintended behavior of the "Automatically collapse sections on close page" setting, it shouldn't close manually opened branches. Do you have it turned on? You can find it under Preferences > Plugins > Page Index > Configure.

**Comment by zogommog** [comment]
introt: Yes, that setting was enabled. I disabled the checkbox for  "Automatically collapse sections on close page" and noted that the behavior has stopped. This will save me from gobs of frustration. Thank you very much!!!

**Comment by introt** [comment]
You're welcome!

Confirmed on latest `develop` (0.75.1, 82b7fb978891302e5eeb95ce95bde8d7e857f191). According to the manual, manually opened branches shouldn't close automatically.

**Comment by jaap-karssenberg** [comment]
Testing with 0.75.1 I can't reproduce - can you test again and/or give a
more specific scenario ?

Thanks,

Jaap

**Comment by introt** [comment]
1. Enable both "Automatically expand/close ..." options
2. Open the page `:Foo` of the following hierarchy: `:Foo:Bar:Buzz` `:Foo:Bar:Fizz:Fuzz`
3. Manually expand the rest of the hierarchy
4. Open `Foo:Bar:Buzz`
5. `Foo:Bar:Fizz` erroneously collapses automatically

**Comment by jaap-karssenberg** [comment]
Confirmed, issue is specific for child item of an auto-unfolded parent when navigating to another child
