### ISSUE TITLE
Spelling Plugin Can not Load

### ISSUE THREAD

**Issue by limopc** [zim-desktop-wiki/zim-desktop-wiki#2131]
### Discussed in https://github.com/zim-desktop-wiki/zim-desktop-wiki/discussions/2130

<div type='discussions-op-text'>

<sup>Originally posted by **limopc** August 18, 2022</sup>
Hi all,
First, I am new here, but using Zim for long time.
I am on EndeavourOS, KDE Plasma, BTRFS file system.
I believe I have installed requirements for spell checking and it spell check is working fine on many other apps.

Still, Edit -> Preferences -> Plugins Tab, "Spell" is way down at the bottom below the alphabetical order and I have a red message saying " There was a problem loading this plugin"

What might be wrong?
I will appreciate any help to fix it.
Thank you.</div>

**Comment by introt** [comment]
Please fill out the proper ticket template or use the Discussions for questions, thanks!
