### ISSUE TITLE
Feature Request: Remap Enter key as Confirm Equation instead of newline

### ISSUE THREAD

**Issue by xade93** [zim-desktop-wiki/zim-desktop-wiki#2144]
Hi all, my normal workflow of entering formula is:
1. Type normal text
2. Press "Ctrl+Shift+E" to open new equation menu
3. Type equation 
4. using my mouse, manually find the confirm button  and click it

If there are a lot of equations, the last step significantly slows things down. Considering multiline equation is much less common than inline equations, can we remap Enter button as "confirm equation", and (for instance) map Ctrl+Enter as actual newline? That would accelerate workflow very much.

Thanks!

**Comment by jaap-karssenberg** [comment]
You should be able to confirm the dialog with "Alt - O" for "OK" (Press
"ALT" to see the underlines)

--- Jaap

**Comment by introt** [comment]
https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/157#issuecomment-1193174629 could also work after we've established inline source files for ImageGenerators
