### ISSUE TITLE
Tables (Table Editor plugin) render cells with links incorrectly

### ISSUE THREAD

**Issue by Self-Perfection** [zim-desktop-wiki/zim-desktop-wiki#2146]
**Describe the bug**
Cells with links repeat content from row above instead of actual content.

**To Reproduce**
Enable "Table editor" plugin and insert following snippet:
```
| Foo         | Bar                   |
|:------------|:----------------------|
| 1           | 2345                  |
| abc def hij | klm **nop**           |
| foobar      | http://www.python.org |
```
Refresh the note. You will see "klm **nop**" instead of the link to python.org

**Expected behavior**
I should see the link.

**Screenshots**
![image](https://user-images.githubusercontent.com/3757038/187771793-a66d9feb-398d-4b6b-9273-58092b910072.png)

**Environment (please complete the following information):**
 - Version 0.74.3, from repositories
 - OS: Kubuntu 22.04
 - Xorg
 - Language: Should not matter

**Comment by introt** [comment]
Can be reproduced on latest `develop`

**Comment by kairosdojo** [comment]
I can confirm this - suddenly all the links inside my cells do not work anymore. 

I suspect it has to do with some update of Zim / **Gtk3**. 

## Environment
* **Manjaro Linux** (`5.18.19-3-MANJARO`)
* Zim → **0.74.3**
* Gtk3 → **1:3.24.34-1**

## Example

Running `zim --debug` and creating a new table (and then trying to add a link as explained [here](https://zim-wiki.org/manual/Plugins/Table_Editor/Superior_Table_Operations.html) ):

```
INFO: Open page: Home (Home)
DEBUG: Got page template 'Default' for Home
INFO: Loading template from: /usr/share/zim/templates/wiki/Default.txt
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck found out-of-date
DEBUG: Index folder: /home/raf/Notes
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck finished
DEBUG: Opening dialog "Insert Table"
DEBUG: Opening dialog "Insert Table"
DEBUG: Dialog response OK
DEBUG: Closed dialog "Insert Table"
DEBUG: Store page in background: Home
DEBUG: Index file: /home/raf/Notes/Home.txt

(zim:9850): Gtk-WARNING **: 11:57:37.490: Failed to set text from markup due to error parsing markup: Value of 'size' attribute on <span> tag on line 1 could not be parsed; should be an integer, or a string such as 'small', not '0'

(zim:9850): Gtk-WARNING **: 11:57:37.490: Failed to set text from markup due to error parsing markup: Value of 'size' attribute on <span> tag on line 1 could not be parsed; should be an integer, or a string such as 'small', not '0'

(zim:9850): Gtk-WARNING **: 11:57:37.491: Failed to set text from markup due to error parsing markup: Value of 'size' attribute on <span> tag on line 1 could not be parsed; should be an integer, or a string such as 'small', not '0'

(zim:9850): Gtk-WARNING **: 11:57:37.495: Failed to set text from markup due to error parsing markup: Value of 'size' attribute on <span> tag on line 1 could not be parsed; should be an integer, or a string such as 'small', not '0'

(zim:9850): Gtk-WARNING **: 11:57:37.495: Failed to set text from markup due to error parsing markup: Value of 'size' attribute on <span> tag on line 1 could not be parsed; should be an integer, or a string such as 'small', not '0'

(zim:9850): Gtk-WARNING **: 11:57:39.417: Failed to set text from markup due to error parsing markup: Value of 'size' attribute on <span> tag on line 1 could not be parsed; should be an integer, or a string such as 'small', not '0'

(zim:9850): Gtk-WARNING **: 11:57:39.418: Failed to set text from markup due to error parsing markup: Value of 'size' attribute on <span> tag on line 1 could not be parsed; should be an integer, or a string such as 'small', not '0'

(zim:9850): Gtk-WARNING **: 11:57:39.917: Failed to set text from markup due to error parsing markup: Value of 'size' attribute on <span> tag on line 1 could not be parsed; should be an integer, or a string such as 'small', not '0'

(zim:9850): Gtk-WARNING **: 11:57:39.917: Failed to set text from markup due to error parsing markup: Value of 'size' attribute on <span> tag on line 1 could not be parsed; should be an integer, or a string such as 'small', not '0'
DEBUG: Store page in background: Home
DEBUG: Index file: /home/raf/Notes/Home.txt
```

You can see that Gtk isn't able to parse the content of that cell anymore (that warning arises only when adding a link).

**Comment by introt** [comment]
Thanks for the logs @kairosdojo ! They led me to discover the source:

https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/82b7fb978891302e5eeb95ce95bde8d7e857f191/zim/plugins/tableeditor.py#L37-L50

Changing the size to "small", as suggested by the error message, results in the link being rendered in a different wrong way, ie. progress! ;)

![image](https://user-images.githubusercontent.com/26069787/197332010-67dc32d2-1cd1-42f3-a0e6-6a91f0156361.png)

According to `git blame`, the line hasn't been modified since 2015, so that'd point to a Gtk3 change.

The `size="0"` seems to be a hack to allow lossless two-way transformation between Zim wiki and Pango syntaxes. Unless we want to wait for someone to rewrite the table plugin, we're going to need a new hack :)

Edit:

According to https://docs.gtk.org/Pango/pango_markup.html and https://learn.microsoft.com/en-us/typography/opentype/spec/featurelist, we should be able to set the size to zero via `font_features="size=0"`, but that nor any other sizes work. Does anyone know the Pango syntax?

> font_features
>    A comma-separated list of OpenType font feature settings, in the same syntax as accepted by CSS. E.g: font_features='dlig=1, -kern, afrc on'.

**Comment by introt** [comment]
Sometimes the best hack is the most obvious one - size 1 is small enough to be invisible. @jaap-karssenberg can we include this in 0.75.1?

**Comment by kairosdojo** [comment]
Yeahhhh, @introt ! I would have helped you but I don't know enough the Zim's codebase (...nor Pango syntax to be fair :) ).
