### ISSUE TITLE
Portable version does not install all folders in selected directory

### ISSUE THREAD

**Issue by globules-io** [zim-desktop-wiki/zim-desktop-wiki#2147]
**Describe the bug**
Zim portable version does not install in the proper directory on Windows

**To Reproduce**
1. Install Zim portable in `d:\Docs\Zim`
2. The program installs itself in `d:\Docs\Zim` but the config folders (cache, config, data) are installed a level up in `d:\Docs`

**Expected behavior**
All files and folder should be contained to the selected folder `d:\Docs\Zim`

**Environment (please complete the following information):**
 - Version 0.74.3
 - OS: Windows 10

**Comment by sergeevabc** [comment]
I guess, that's why fellows of PortableFreeware [suggested ](https://www.portablefreeware.com/?id=3044)fixing _environ.ini_ before the first launch by means of replacing its ../ paths with ./ paths.

**Comment by jaap-karssenberg** [comment]
Will update default config paths, but keep default path for notebooks outside the install folder. Otherwise they get removed on uninstall, and that is the worst possible scenario. See #1615
