### ISSUE TITLE
Zim wiki window does not minimize

### ISSUE THREAD

**Issue by TheCoder49** [zim-desktop-wiki/zim-desktop-wiki#2156]
The window cannot be minimized by clicking on the app icon in the taskbar. Instead of getting minimized, the window just apparently loses focus.

**Environment:**
 - Version 0.74.0
 - OS: windows

**Comment by introt** [comment]
Possibly related to #2007, please update to 0.75 and check if the issue persists

**Comment by mtill** [comment]
Hi!
i can confirm that this issue appeared on windows for version 0.74. When recompiling that version 0.74 from sources (with updated packages/dependencies), the issue disappeared.
In 0.75, this has been resolved and it's working.
BR
mtill
