### ISSUE TITLE
Windows installer is marked as not safe with 2 trojans by virustotal.com

### ISSUE THREAD

**Issue by khe817** [zim-desktop-wiki/zim-desktop-wiki#216]
I ran the newest windows installer (`zim-desktop-wiki-setup-0-67.exe`) through `virustotal.com` and got this result:
![image](https://user-images.githubusercontent.com/7119865/31233973-ba5d44b4-a9bb-11e7-90ad-e4cf4609fff3.png)

Not sure if it's an issue.

**Comment by lrq3000** [comment]
Probably because it is packed to get some compression of the executable.

**Comment by jaap-karssenberg** [comment]
Has been discussed on the mailing list, no clear solution how to fix

**Comment by jaap-karssenberg** [comment]
Stale item - as of zim 0.7x there is a new packaging script for windows
