### ISSUE TITLE
Zim 0.75.0 crash on startup when notebook has an icon set

### ISSUE THREAD

**Issue by fdt-dev** [zim-desktop-wiki/zim-desktop-wiki#2165]
**Describe the bug**
Zim 0.75.0 crashes on startup when one notebook has an icon set in its preferences. (I use the German language version, therefore I'll post an example of the German version.) Zim crashes with the error message that the icon does not use an absolute path, which is true (relative paths are to be preferred over absolute paths). But it should be noted here that I set the icon in the preferences by using Zim's own dialogue windows, meaning I didn't set the path to the icon by hand.

**Expected behavior**
Zim 0.75.0 should behave like Zim 0.74.3 in that respect or any of the previous versions.
Or at least ignore the icon and get the application window up and running. Don't crash because of an icon.

**Screenshots**
![Bildschirmfoto von 2022-10-01 22-07-20](https://user-images.githubusercontent.com/35032197/193426701-4ae0b742-b704-469c-904e-ddc0dbb31e54.png)

**Environment (please complete the following information):**
 - Version 0.75.0 -- PPA (I had to manually revert back to 0.74.3)
 - OS: Ubuntu 20.04 LTS
 - Language: German (but I assume that this particular bug will occur in any language)

**Additional context**
Here is the corresponding error message:
[zim-error.txt](https://github.com/zim-desktop-wiki/zim-desktop-wiki/files/9691141/zim-error.txt)

**Comment by zgstyle** [comment]
The same here.
Only way to open a notebook is directly clicking on notebook.zim file.
