### ISSUE TITLE
0.75: CTRL-9/Format > Clear Formatting = does not clear header formatting anymore

### ISSUE THREAD

**Issue by vossenjp** [zim-desktop-wiki/zim-desktop-wiki#2166]
**Describe the bug**
CTRL-9/Format > Clear Formatting = does not clear header formatting anymore, but in 0.74 or older it did.

**To Reproduce**
1. Run 0.75
2. Create a header line, e.g, CTRL-1
3. Highlight the line
4. CTRL-9

**Expected behavior**
Header format should be cleared.  And it is in 0.74, I just tested on a different node before restarting into 0.75.

CTRL-9 still works for bold, italics, etc., but not headers.  I use this a lot because I tend to put something in a header then decide it should be body.  Newline, highlight, CTRL-9 used to do the trick.  Now I have to use newline, highlight, figure out what header level it is, then CTRL-{header level}.  That's not terrible, but CTRL-9 it easier, and should, IMO, just clear all formatting.

**Environment:**
 - Version: 0.74.3-t202207071804~ubuntu20.04.1
 - OS: Linux Mint-20.3
 - Language: English

**Comment by jaap-karssenberg** [comment]
This is intended behavior since headings can also have "nested" formatting.
In the formatting toolbar, there is a new "clear heading" entry to remove
any heading.

The logic being that "clear formatting" also does not e.g. remove list
style. So it only applies to "inline" formatting while list style and
heading style are considered "block level" formatting.

Agree that we could improve keyboard accessibility of the "clear heading"
action.

Regards,

Jaap

**Comment by vossenjp** [comment]
OK, it's this is on purpose then it's fine, I'll get used to a work-around.  And your argument cor consistency makes sense.  I did not notice the new "Remove Heading" in the formatting toolbar.  I did look in the "Format" menu and there's nothing.  That seems odd, since that where the rest of the formatting options, especially "Clear Formatting" are.

So may I suggest:
1. Adding a "Zim > Format > Remove Heading" menu option.
2. Adding a keyboard shortcut for same. maybe CTRL-8?

**Comment by jaap-karssenberg** [comment]
Will use Ctrl-7 with the rationale that html has 6 heading levels, so reserving 6 if we want to extend in the future and use 7 as the "no heading" level.

**Comment by introt** [comment]
> Newline, highlight, CTRL-9

Sidenote: no need to highlight, heading operations always affect the whole line; a previous workaround I used for this was to press ctrl+1 twice (first press turns any line into a title heading, second press removes the heading formatting).
