### ISSUE TITLE
0.75 file links no longer work (possibly because of accents in paths)

### ISSUE THREAD

**Issue by patc3** [zim-desktop-wiki/zim-desktop-wiki#2168]
Links to files that used to work no longer works, and new links created with "browse" don't even work either. I think it might be due to accents. Windows 10 French locale. This is quite a setback.

![image](https://user-images.githubusercontent.com/41131893/193458926-d740b0b2-5da3-4a61-858a-581c575a7122.png)

![image](https://user-images.githubusercontent.com/41131893/193458935-342850e0-15c5-4993-bc25-b1ae76e3bfd0.png)

![image](https://user-images.githubusercontent.com/41131893/193458946-28895899-ee7a-4090-99f6-e4be340d623e.png)

**Comment by jaap-karssenberg** [comment]
I can reproduce this and will try to fix ASAP - did you upgrade from 0.74
or an older version ?

**Comment by patc3** [comment]
Thanks Jaap. I upgraded from 0.74.3 (without uninstalling).
