### ISSUE TITLE
Flatpak: Could not find executable when trying to open files with external application

### ISSUE THREAD

**Issue by trougnouf** [zim-desktop-wiki/zim-desktop-wiki#2169]
**Describe the bug**
When I try to open a linked file (eg: pdf) on the Flatpak version of Zim, I get a prompt to chose an application, but it yields the error "`Could not find executable "/var/lib/flatpak/app/org.gnome.Evince/x86_64/stable/active/files/bin/evince`" (or whatever I set the executable to, also tried with "org.gnome.Evince" which is in the path, its .desktop file, and `/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=evince org.gnome.Evince`).
I tried giving Zim access to "All system files (filesystem=host)" and "All system libraries, executables and static data (filesystem=host-os)" using Flatseal and that seems to have made no difference.

**Expected behavior**
Right click > open with > customize > Add Application (the drop-down list only contains "System Default" which does nothing) > try a path

**Screenshots**
![Screenshot_20221003_102321](https://user-images.githubusercontent.com/6899116/193532530-613d6d56-69cd-423f-9560-0b90227e1925.png)

**Environment (please complete the following information):**
 - Version [e.g. 0.74.3] -- Flatpak
 - OS: Linux SteamOS w/ KDE on the Steam Deck
 - Language: English

**Additional context**

For issues triggered by specific page content, please add an (anonymized) example that allows reproducing this issue.

For issues with no visible output / error, check the debug log for additional logging. This is available via the menu or by running "zim -D" from the commandline.

**Comment by jaap-karssenberg** [comment]
Please report this issue to the flatpak repository. This package had it's
own maintainers.

Regards,

Jaap

Op ma 3 okt. 2022 10:36 schreef Benoit Brummer ***@***.***>:

**Comment by trougnouf** [comment]
Done, it's probably the same issue as https://github.com/flathub/org.zim_wiki.Zim/issues/7 so I linked it there.
