### ISSUE TITLE
More markup for formatting text

### ISSUE THREAD

**Issue by amjr108** [zim-desktop-wiki/zim-desktop-wiki#2178]
Zim's own markup is pretty limited even compared to markdown. For example, there is no quotations (which are very important for deskop wiki) and some "nota bene" boxes (with "!", "?", "??" or some other marks).

Things like "foldable details", "definition list", "footnotes" are, as for me, also important, because they make text more readable.

**Comment by jaap-karssenberg** [comment]
Sorry, but any of the examples you give are not in the markdown standard.
They maybe in specific implementations as an extension, but compared to the
default spec actually zim wiki has more features.

Please do not make generic tickets like this. You can use the "discussions"
forum to talk. Issues should be reserved for more specific issues and
change requests.

--- Jaap

**Comment by amjr108** [comment]
Ok. Thanks for reply!
