### ISSUE TITLE
Show edit bar preference is not saved anymore with 0.75

### ISSUE THREAD

**Issue by kjyv** [zim-desktop-wiki/zim-desktop-wiki#2184]
**Describe the bug**
The edit bar at the bottom of the text section can be shown or hidden with a preference checkmark in the Prefrences window. This works as it should in 0.74.3 and while 0.75 is running. When closing zim and restarting, the setting is still the same in 0.74.3, in 0.75 it is back to showing the edit bar if it was disabled before.

**Expected behavior**
Restarting zim should keep the setting the way it was set.

**Environment (please complete the following information):**
 - Version 0.75, dmg installer
 - OS: macOS 12.6
 - Language: German

**Comment by jaap-karssenberg** [comment]
Do you have the toolbar plugin active? This might overwrite the preference.

--- Jaap

**Comment by kjyv** [comment]
Do you mean the macOS Menu Bar plugin? Then yes. The Pathbar is not enabled.

**Comment by jaap-karssenberg** [comment]
No, I'm talking about the Toolbar plugin. It could be default enabled on
macOS because it handles window decoration as well.

--- Jaap

**Comment by MurrayVK3** [comment]
I have the same issue on Linux.    
show_edit_bar is set to true in the preferences file but on starting Zim it gets set to false and the edit is not displayed (as you'd expect).

**Comment by wadih** [comment]
Happening also on ubuntu linux latest as of the latest update 0.75.0
