### ISSUE TITLE
Force scrollbar visibility

### ISSUE THREAD

**Issue by Veraellyunjie** [zim-desktop-wiki/zim-desktop-wiki#2185]
Modern interfaces from the very best usability experts <sub>sarcasm</sub> hide scrollbars while not scrolling and while mouse is inactive.

Some users like me are used to scrollbars being indicators of the
* size of a document
* current position in the document

So we count on vertical scrollbars being always visible.

Without them I personally feel a bit lost, and when I actually need to see them I have to make additional movements - annoying, poor usability.

E.g. newer Firefox browser hides vertical scrollbars by default but has an `Always show scrollbars` tick box in the settings.

Please make a similar setting in Zim.

**Comment by jaap-karssenberg** [comment]
This is actually in the scope of the GTK theme. So not an application
setting we can change from within Zim. But you can setup GTK with a more
classic looking theme if you want.

Regards,

Jaap

Op zo 9 okt. 2022 23:12 schreef Veraellyunjie ***@***.***>:

**Comment by Atronach** [comment]
What you want is to set the following variable:
GTK_OVERLAY_SCROLLING=0

This is adhered by all GTK3/4 apps and works on both Win+Lin.

**Comment by Veraellyunjie** [comment]
`export GTK_OVERLAY_SCROLLING=0` in `~/.xprofile` does work.

Other methods for this like  
`gtk-overlay-scrolling = false` in `~/.config/gtk-3.0/settings.ini` or  
`gsettings set org.gnome.desktop.interface overlay-scrolling false`  
don't work on my machine…

---

For control from inside app https://github.com/webview/webview/issues/443 uses this approach (the exact app and its architecture are unknown to me):
```
#ifdef WEBVIEW_GTK
    setenv("GTK_OVERLAY_SCROLLING", "0", 1);
#endif
```
I don't know whether such a way would work for Zim

---

For GTK4, `GTK_OVERLAY_SCROLLING` env variable has been dropped
https://github.com/GNOME/gtk/commit/e49615184a9d85bb0bb4e289b3ee8252adee3813#diff-3cf94c6e1eb009e20985034bc2210bfd
Let me [cite](https://ubuntu-mate.community/t/gtk3-changing-the-overlay-momentium-scroll-bar/20298/2) another user:

> That is... until GTK4 where this environment variable is gone. It'll then be up to the developer to expose an option in their application, *if they want*. :man_facepalming:

Thus, if future Zim is gonna "upgrade" to GTK4, please do implement the option to always have scrollbars

---

Thank you kind people who help us fight upstream

**Comment by sergeevabc** [comment]
+1 for more _grippy_ scrollbars.

**Comment by sojusnik** [comment]
I like the scrollbars like they are now. So if implementing autohiding of scrollbars, then do it optional.

**Comment by jaap-karssenberg** [comment]
Will not do anything on this from zim itself - it is a Gtk / theme setting
