### ISSUE TITLE
Opening saved notebook, does not preserve root (opens all notebooks as one)

### ISSUE THREAD

**Issue by juliux-arg** [zim-desktop-wiki/zim-desktop-wiki#2189]
**Opening a notebook saved with previous version, does not preserve root page**
Zim version 0.75. O.S.: Linux Mint 20.3
When I open a notebook (anyone) double clicking on the .zim file in Nemo (Linux Mint default file explorer) I see another notebooks in the **Index section**.

**To Reproduce**
1. In Nemo search for the .zim file
2. Double click  on the .zim file to open it.
3. Select Index tab.
4. I can see another notebooks apart from selected.

**Expected behavior**
Selected notebook is de root page (or home page?)

![image](https://user-images.githubusercontent.com/14987507/195330996-e6cfee54-ef6f-4413-beee-6704cdb44a06.png)

![image](https://user-images.githubusercontent.com/14987507/195331548-0b7df2d4-8cc7-4fb8-a6dd-660759abeb52.png)
As you can see Programación does not show as root page, as was in previous versions.

**Environment:**
 - Version [e.g. 0.75.0] -- deb-src http://ppa.launchpad.net/jaap.karssenberg/zim/ubuntu focal main
 - OS: Linux Mint 20.3
 - Language: Spanish

**Additional context**
.zim file content:

```
[Notebook]
version=0.4
name=Programación
interwiki=
home=Home
icon=
document_root=
shared=True
endofline=unix
disable_trash=False
profile=
```

**Comment by jaap-karssenberg** [comment]
Agree this is not the correct behavior.

Clarifying question: do you have a "notebook.zim" file in the root folder
as well ?

-- jaap

**Comment by juliux-arg** [comment]
![image](https://user-images.githubusercontent.com/14987507/195380040-3e862da5-4828-458e-9720-ef847b143e26.png)
This is the root folder's content. So, the answer is "yes".
