### ISSUE TITLE
Zim Windows 0.75 - "Umlaute" (mutated vowel) äöüß - do not work in german

### ISSUE THREAD

**Issue by installat** [zim-desktop-wiki/zim-desktop-wiki#2192]
**Describe the bug**
Or add the crash report from zim here.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Version [e.g. 0.74.0] -- specifically mention it if you use the development branch or snapshot PPA
 - OS: [e.g. linux/windows/mac os]
 - Language: especially for errors that might relate to character encoding or other locale specific issues

**Additional context**

For issues triggered by specific page content, please add an (anonymized) example that allows reproducing this issue.

For issues with no visible output / error, check the debug log for additional logging. This is available via the menu or by running "zim -D" from the commandline.

**Comment by dehesselle** [comment]
Cannot reproduce. Please fill out the issue template next time.
