### ISSUE TITLE
"Issues" page on the repository's wiki is out-of-date

### ISSUE THREAD

**Issue by introt** [zim-desktop-wiki/zim-desktop-wiki#2206]
**Describe the bug**

See title. Last updated on Jan 3rd, 2020, the wiki page on our Issue workflow is severely out-of-date, starting with the mentions of a `master` branch.

**To Reproduce**
1. Go to this repository's wiki
2. Click on "Issues"
3. Scroll down to "Open versus closed issue"
4. See out-of-date information

**Expected behavior**
The docs represent the current workflow

**Screenshots**
N/A

**Environment (please complete the following information):**
* https://github.com/zim-desktop-wiki/zim-desktop-wiki/wiki/Issues rev Jan 3, 2020
* https://github.com/zim-desktop-wiki/zim-desktop-wiki/discussions/1860
  * https://github.com/zim-desktop-wiki/zim-desktop-wiki/discussions/1860#discussioncomment-3477626

**Additional context**
*  #1610
* We don't have a bug template for documentation issues
* https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/develop/CONTRIBUTING.md should also be looked at

**Comment by introt** [comment]
I also find the document to be internally inconsistent regarding the "fix-available" label (emphasis mine):

> If an issue is **fixed in the "develop" branch** but not yet merged into the "master" branch, it will be tagged with the "fix available" label.

> Fix available --> fix available **as code either in private repository, or in some other place,** once committed to main code base, issue will be closed

Since we can now use GitHub's linked PRs functionality as intended (see screenshots below), should we
* delete the tag
* repurpose it for use with Discussions
* third option?

![image](https://user-images.githubusercontent.com/26069787/197346417-dc418a59-272f-4b1c-95c2-d32198e331a6.png)
_PR view_

![image](https://user-images.githubusercontent.com/26069787/197346449-1114686a-cd0a-4ea4-999f-35bdaeb8c23d.png)
_Issue view_

![image](https://user-images.githubusercontent.com/26069787/197346540-b126c385-6e30-477c-9c2c-733972f5ccc8.png)
_Search view; note the "Milestones" column_

**Comment by jaap-karssenberg** [comment]
Updated issue page

**Comment by introt** [comment]
Thanks! Two small things:

> for feature requests

...open a Discussion?

&& what's the "fix available" label for? Doesn't the linked PR functionality cover this, or is it for marking enhancement-Discussions as "solved"?
