### ISSUE TITLE
Page Refresh (Ctrl-R) behaves differently from 0.75.0 onwards

### ISSUE THREAD

**Issue by fdt-dev** [zim-desktop-wiki/zim-desktop-wiki#2211]
**Description**
Page Refresh (Ctrl-R) behaves differently in 0.75.0 and 0.75.1 compared to previous versions. Let's say there are two page headings in two rows directly following each other, then hitting Ctrl-R in 0.74.3 lead to inserting an empty row between the headings. 0.75.0 and 0.75.1 do no longer insert this empty row.

It's not just a deliberate page refresh: changing pages back and forth should lead to a page refresh. Maybe it happens in the background, but the markup is not being automatically reformatted.

It seems to me that there should be some consistency between the different versions in how the page layout is being created. I would have preferred not to have the empty rows, since it's nothing that I deliberately entered and it's not just page rendering: the empty row is in the file. But since this "feature" had been in Zim for years, most of my pages now contain these empty row before a heading.
I think it should be consistent. Please consider reinserting the empy lines between headings.

**To Reproduce**
1. Open a page
2. Add a heading
3. new line
4. Add another heading
5. new line
6. hit Ctrl-S (to save)
7. hit Ctrl-R (to refresh)

The headings are not separated by an empty row. I think they should be to stay consistent.

**Expected behavior**
A page refresh should lead to an empty row before every heading. Just like it was previously.

**Environment:**
 - Version [e.g. 0.75.1] -- PPA
 - OS: [Ubuntu 20.04, Windows 10]
 - Language: DE (German)

**Comment by jaap-karssenberg** [comment]
This behavior was changed on purpose since the empty row did not serve a
purpose in the parsing and we wanted to stick closer to the
what-you-see-is-what-you-get principle.

--- Jaap

**Comment by fdt-dev** [comment]
Yes, I see. The problem with that is: Pages which were edited with a previous version of Zim do contain these empty rows. Since these are not being removed by a page refresh the headings which were added previously will look different to the ones added afterwards. I can write a script to correct the 5000 pages that I have in my wiki (well, acutally it's more like 12000 pages across all wikis I use), but even then it won't look good anymore. This causes a lot of headache and necessitates manual correcting.

It wouldn't have been so bad if this empy row was purely due to page rendering, but the row is there in the files, thousands of them.
I wasn't happy originally when the page refresh added this row, which as you say doesn't really serve a purpose, except that it makes the page a little more pleasing to read. But now it's there and needs manual removing to be consistent again. That's worse. Sorry to say that.

And it still isn't consistent, because if for example you're typing in a bullet point list: hitting enter once will result in a new bullet point, hitting enter twice will exit out of the bullet point list, leaving an empy row. Then continuing to set a new heading and then this heading has a preceeding empty row. I don't think it will look good.

Thank you for the explanation. Can you please point me to the code part where this line was added? Then I will have to add this code again so that Zim at least behaves the same as previously. Or make it an option. I know, it's difficult. But this will cause a visual mess in existing pages.

**Comment by jaap-karssenberg** [comment]
Sorry, but I really don't see the problem. If you want a newline before a
heading when you are typing a new page, you can just type it - why would
you rely on reload to do that for you !?

If strict consistency in layout between pages is important, you should
realize Zim is not designed for that. It is designed as free-form note
taker. If you want to enforce layout, I would think about an export format
that has more strict rules and use that for "presentation" or "publishing"
purposes. E.g. the html export allows to ignore hard line breaks in the
wiki source completely and you can use CSS to control spacing around
headings.

If you must, the logical class to add this type of reload logic is here:
https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/eea32ce74313c5b8b7a347f6235a04211696df40/zim/formats/__init__.py#L756
. However it is non-trivial to revert to the old behavior; the class has
been completely refactored.

Regards,

Jaap

**Comment by fdt-dev** [comment]
Please look at it from the other side: The existing pages have this new line everywhere because the refresh put it there automatically (which could not be avoided). So now I would have to remove these new lines from thousands of pages. (Because sometimes one wants to add something new to existing pages and in terms of legibility it'd be better to keep in consistent.)

I realize that Zim is not designed for consistency in terms of layout. I realize that it is designed as a sort of free-form note taking utility, but then it didn't exactly behave that way by adding these new lines. Zim enforced these new lines, that's not free-form.
The point is: these new lines are there and adding headings to existing pages will now cause it too look inconsistent. I don't want these new lines anyway, but they coudn't be avoided in previous versions of Zim. Now Zim doesn't put them there, which makes sense. In order to make existing pages look consistent again, I'd have to go through everything and remove these new lines. I mean, I could leave it where it is, sure, I just think it looks untidy. Sure, I can make the new line, but ... Or I could remove the new lines every time I edit an existing page. It's additional work ... fine, it's my problem.

It's fine, I can't explain why that bothers me. (I'm not really concerned with html-Export either, to be honest, because I don't use it that much.)
Sorry for that critizism. I just wanted to note it.

**Comment by jaap-karssenberg** [comment]
I understand the feeling it should be consistent. But looking forward I
rather make it behave like you expected it in the first place then
reverting to the old behavior.

Maybe it is just me, but I type the newline anyway when I start a heading -
seems wrong to have no clear separation - but that might be internalized
training from writing SW ...

--- Jaap

**Comment by fdt-dev** [comment]
I think it is good and it is important to find a positive note. Thank you for that!
I agree with you that moving forward Zim should not automatically change the layout. Wiki Markup should be automatic, but no new lines that the user didn't type. I agree with you there.

At least it gives me now the option to say: I want a new line before an H1 heading, but no new line before an H2 heading if immediately preceeded by an H1 heading. For example. That's good.
I will correct old pages as I go. It won't be consistent any time soon (maybe never), but it's fine.

New lines can keep text more legible. Not always, I agree. If I work on a text in a word processor I'd rather have new lines before a new heading, except if immediately preceeded by another heading.


Python sure need its new lines at the appropriate places, that's true. An interesting concept by itself. I like Python for its rapid prototyping capabilities and also its relatively good performance, but I disagree with some of the design decisions. That's an aside, though.

**Comment by introt** [comment]
Closing as not-a-bug, please use the discussion forum if you need a script/plugin to enforce header newline rules
