### ISSUE TITLE
0.75.1 not installable on debian

### ISSUE THREAD

**Issue by helge42** [zim-desktop-wiki/zim-desktop-wiki#2216]
**install on debian fails**
The deb-file for Version zim_0.75.1_all.deb uses *control.tar.zst* . This throws an error on debian.

zim_0.75.0_all.deb installs ok and nice.

Sincerely, Helge

**Comment by jaap-karssenberg** [comment]
Interestingly the build script did not change between these releases.
However I may have updated my environment.

Can you test the Deb in the Ubuntu PPA archive? These are generated with
the same build script but on a different platform.

Op ma 31 okt. 2022 10:01 schreef helge42 ***@***.***>:

**Comment by helge42** [comment]
Install with zim_0.75.1-....~ubuntu20.04.1_all.deb

works fine.

Btw thank you very much for the Version 0.75!!

Am 1. November 2022 13:45:46 MEZ schrieb Jaap Karssenberg ***@***.***>:

**Comment by sobiejan** [comment]
For Debian look here:
https://github.com/yktoo/indicator-sound-switcher/issues/113#issuecomment-997810115

I did this and it works fine:
cd mydirectory with file zim_0.75.1_all.deb
ar x zim_0.75.1_all.deb
zstd -d < control.tar.zst | xz > control.tar.xz
zstd -d < data.tar.zst | xz > data.tar.xz
ar -m -c -a sdsd zim_0.75.1_all_repacked.deb debian-binary control.tar.xz data.tar.xz
rm debian-binary control.tar.xz data.tar.xz control.tar.zst data.tar.zst
dpkg -i zim_0.75.1_all_repacked.deb
and I have the Zim version 0.75.1

**Comment by jaap-karssenberg** [comment]
Closing for now, will look into build dependencies - see #2209
