### ISSUE TITLE
Drop down menu items in the dialog boxes are not selectable with mouse

### ISSUE THREAD

**Issue by murattepegoz** [zim-desktop-wiki/zim-desktop-wiki#2219]
**Describe the bug**
Drop down menu items in the dialog boxes are not selectable with mouse. It seems like the dialog box looses focus for some reason. See the snapshot for details. Note that up/down keys can select the items, works as expected. 
It is also observed that clicking on Cancel button on the dialog window does not work in the first mouse click but the second click works.

**To Reproduce**
1. click on Cmd+J (Jump To) window
2. type any page title so that drop down shows up
3. click on the items on drop down list
4. See the issue. Observe that clicking on the item in the drop down menu does not work.

**Expected behavior**
Drop down menu items should be selectable with mouse click.

**Screenshots**
![image](https://user-images.githubusercontent.com/3308687/199041359-9153b7e8-ee84-4738-b3b9-dbc82fa2852a.png)

**Environment (please complete the following information):**
 - Version 0.75.1. I think this problem exist on 0.75 as well.
 - OS: macOS Ventura 13.0 (22A380)
 - Language: English

**Comment by dehesselle** [comment]
I can reproduce the issue. I even have to click the "go to" button twice.  
This is an upstream issue, we need to open a ticket with GTK.

![focus_related](https://user-images.githubusercontent.com/11375494/199042425-5c8309d9-dea8-43e7-83f7-ed6539a8409c.gif)

**Comment by dehesselle** [comment]
Upstream issue: https://gitlab.gnome.org/GNOME/gtk/-/issues/5305

**Comment by dehesselle** [comment]
I've just tested the newest GTK version 3.24.36 which includes some fixes to help with the situation, but I don't see any improvement with Zim.

**Comment by dehesselle** [comment]
macOS Ventura is now supported as of [v0.75.1+245](https://gitlab.com/dehesselle/zim_macos/-/releases/v0.75.1+245)

**Comment by murattepegoz** [comment]
Thanks for fixing this, works perfect now.
