### ISSUE TITLE
Unable to edit/remove auto-generated link on path

### ISSUE THREAD

**Issue by sean729** [zim-desktop-wiki/zim-desktop-wiki#2227]
Hello Contributors:

Thanks for all the great features. Noticed this in my recent upgrade to Zim Wiki 7.5.1 on Windows 10. When I paste text that includes a file system path Zim will automatically treat paths as a link. So far that is fine, however that link can only be edited via CTR-L as the option to edit/remove is not listed in the right-click context menu. My issue is that I want to remove the hyperlink of the file path (since I am documenting a path that exists on a remote host and thus is not valid in local host). Thank you.

Kind Regards,
Sean.

**Comment by introt** [comment]
Hi Sean! The option to edit or remove a link is only available to use with `[[wikitext links]]` - what you describe as an "auto-generated link" is actually auto _formatted_. Currently, you have two ways to work around this:

1. Manually format the link as "preformatted" using Format > Verbatim (Ctrl+T).
2. Turn off the "Automatically turn file paths into links" option in Preferences > Editing. If you decide to go with this option, you'll need to manually add `[[` and `]]` around file paths to turn them into `[[./links]]`.

Ps. Please use the bug template(s) or open a discussion next time, thanks!
