### ISSUE TITLE
Documentation: MacOS path incorrectly specified

### ISSUE THREAD

**Issue by reagle** [zim-desktop-wiki/zim-desktop-wiki#2242]
https://zim-wiki.org/manual/Help/Config_Files.html

On macOS the default paths are:

 $XDG_CONFIG_HOME = ~/**Library**/Application Support/org.zim-wiki.Zim/
 $XDG_DATA_HOME = ~/**Library**/Application Support/org.zim-wiki.Zim/share/

**Comment by introt** [comment]
Thanks! Feel free to open direct PRs for further documentation issues if you feel comfortable using the web editor.
