### ISSUE TITLE
incorrect numbered outline label when current entry has children

### ISSUE THREAD

**Issue by Osndok** [zim-desktop-wiki/zim-desktop-wiki#225]
minor & easily worked around;

When you press 'enter' at the end of a line that is both a numbered outline list item and has "child" outline items, the **outline label** style (numeral, upper, lower, etc) is picked for the upper level, but the **indentation** is selected for the lower level.

To reproduce, in a blank area type: ```1.<space>one<enter><tab>sub<up>```

Which yields:

```
1. one<cursor>
    a. sub
```

The bug is then triggered by hitting **ENTER**.

Expected result:
```
1. one
    a. <cursor>
    b. sub
```

Actual result:
```
1. one
    2. <cursor>
    a. sub
```

**Comment by jaap-karssenberg** [comment]
Yes, I have known about this one for quite a while, but afraid to mess with the pageview code at this point. Will come back to it when refactoring that part.
