### ISSUE TITLE
Content not refreshed

### ISSUE THREAD

**Issue by gergelyk** [zim-desktop-wiki/zim-desktop-wiki#228]
Right after opening the page, some of the plugins are not rendered correctly:

![1](https://user-images.githubusercontent.com/11185582/32679246-fcb913d0-c665-11e7-8c87-d64d966bfdb7.png)

After resizing the main window everything looks as expected:

![2](https://user-images.githubusercontent.com/11185582/32679247-fcdbd280-c665-11e7-88fa-77a3ee4a03fc.png)

This is observed under Linux 4.10.13-1-ARCH. zim v0.67

**Comment by jaap-karssenberg** [comment]
I believe this is a duplicate, but can't find the right report right away.

At least it is a known issue to me, will need to re-asses after port to Gtk3

**Comment by jaap-karssenberg** [comment]
I believe this to be gone with Gtk3. Please open a new ticket if similar behavior is seen in 0.70 or newer.
