### ISSUE TITLE
Fwd: Zim fails to build with Python 3.12: ModuleNotFoundError: No module named 'distutils'

### ISSUE THREAD

**Issue by cheese** [zim-desktop-wiki/zim-desktop-wiki#2296]
https://bugzilla.redhat.com/show_bug.cgi?id=2154824

Zim fails to build with Python 3.12.0a3.

+ ./setup.py build
Traceback (most recent call last):
  File "/builddir/build/BUILD/zim-0.75.1/./setup.py", line 13, in <module>
    from distutils.core import setup
ModuleNotFoundError: No module named 'distutils'

Remove the distutils package. It was deprecated in Python 3.10 by PEP 632 “Deprecate distutils module”. For projects still using distutils and cannot be updated to something else, the setuptools project can be installed: it still provides distutils. (Contributed by Victor Stinner in gh-92584.)

If your package is listed in [0], you may workaround this issue by BuildRequiring python-setuptools, note that adding such BuildRequires might however hide some transitive dependency problem, if the distutils import comes from a dependency.
Cooperation with upstream is recommended. Additional context [1].

[0] https://lists.fedoraproject.org/archives/list/python-devel@lists.fedoraproject.org/message/6BHNAWHE7M5VY3YQVJLOYHLY4M7KIFFN/

[1] https://lists.fedoraproject.org/archives/list/python-devel@lists.fedoraproject.org/thread/N6ITYHLRWIDNYNXGPYG2ZHF3ZLQWZN7L/

https://docs.python.org/3.12/whatsnew/3.12.html

For the build logs, see:
https://copr-be.cloud.fedoraproject.org/results/@python/python3.12/fedora-rawhide-x86_64/05133216-Zim/

For all our attempts to build Zim with Python 3.12, see:
https://copr.fedorainfracloud.org/coprs/g/python/python3.12/package/Zim/

Testing and mass rebuild of packages is happening in copr. You can follow these instructions to test locally in mock if your package builds with Python 3.12:
https://copr.fedorainfracloud.org/coprs/g/python/python3.12/

Let us know here if you have any questions.

Python 3.12 is planned to be included in Fedora 39. To make that update smoother, we're building Fedora packages with all pre-releases of Python 3.12.
A build failure prevents us from testing all dependent packages (transitive [Build]Requires), so if this package is required a lot, it's important for us to get it fixed soon.
We'd appreciate help from the people who know this package best, but if you don't want to work on this now, let us know so we can try to work around it on our side.

**Comment by oturpe** [comment]
As the new Fedora maintainer for Zim,
I have applied the `BuildRequires: python3-setuptools` workaround.
All good in Fedora-land now.
I will leave this bug open for now, to track the fact that Zim uses a deprecated buildsystem.
Feel free to close the issue if you do not intend to switch buildsystems anytime soon.

**Comment by jaap-karssenberg** [comment]
Let's keep it open for now. Do want to fix it. Just haven't found an
elegant way to do so.

Specifically for installation in data folders (/usr/share/...) The default
utils have no support -they just install data in the python library folders.



Op do 20 jul. 2023 12:24 schreef Otto Liljalaakso ***@***.***

**Comment by introt** [comment]
> This is in scope of [#2209](https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/2209)
