### ISSUE TITLE
Use of [% headingsection.heading %] or [% headingsection.body %] in template causes HTML-Export to fail when there is no Content below the heading

### ISSUE THREAD

**Issue by bruening-bw** [zim-desktop-wiki/zim-desktop-wiki#2298]
**Describe the bug**
At some point I use the loop

```
[% FOR headingsection IN page.headings(5) %]
		[% headingsection.heading %]
		[% headingsection.body %]
[% END %]
```

in my HTML-Template. However if there is no content below the heading this causes the export to stop right there.

**To Reproduce**
1. Create a template file with the following minimal code.
```
<html>
<head></head>
<body>
[% FOR page IN pages %]
	[% FOR headingsection IN page.headings(5) %]
		[% headingsection.heading %]
		[% headingsection.body %]
	[% END %]
[% END %]
</body>
</html>
```
2. Try to export a zim document with a heading that has no content below.

![something](https://user-images.githubusercontent.com/122959165/213311055-433096ef-905a-497f-97f9-ecf6ccbc1f49.png)
![nothing](https://user-images.githubusercontent.com/122959165/213311083-135d2987-7e45-413a-841e-9d507424adaa.png)

**Expected behavior**
I think [% headingsection.body %] should produce a sort of empty string.

**Environment (please complete the following information):**
 - Version 0.75.1 produces no output on from the empty headingsection.body. I tried Version from Debian testing and Flatpak.
 - Version 0.73.5 from Debian 11 produces normal output.

**Comment by habruening** [comment]
I can reproduce the bug with the release branch of 0.75.1. In the develop branch I cannot reproduce it.

It looks like this bug is already fixed.

**Comment by jaap-karssenberg** [comment]
Yes, this is a duplicate
