### ISSUE TITLE
Spell check plugin incorrectly initializes gtkspellcheck, fails to load.

### ISSUE THREAD

**Issue by faitjx** [zim-desktop-wiki/zim-desktop-wiki#2301]
An import exception occurs when loading the gtkspellcheck extension prerequisite.  
I installed pygtkspellcheck using pip, which installed the latest version of the spellcheck module.  I then checked if I could enable the extension, which failed.  I grabbed a source tarball for Zim, and checked into the code that checks which spell check engine is available.  I attempted to import gtkspellcheck in an interactive python interpreter, and  I found that pygtkspellcheck throws an InportError now requires a minimum version of GDK 3.0, and enforces it using a check with gi.  This may be a bug in the pygtkspellcheck package.
Workaround:
As gi is loaded for the check on Gtkspell, I made the following modifications:

1. move the import of gi to the top level of spell.py
2. added the following before the import of gtkspellcheck:  gi.require_version('Gtk','3.0')

a patch follows.

```
--- plugins.orig/spell.py	2023-01-26 17:57:34.258840092 +0000
+++ plugins/spell.py	2023-01-26 18:00:10.458857408 +0000
@@ -17,15 +17,16 @@
 from zim.gui.pageview import PageViewExtension
 from zim.gui.widgets import ErrorDialog
 
+import gi
 
 # Try which of the two bindings is available
 try:
+        gi.require_version('Gtk','3.0')
 	import gtkspellcheck
 except ImportError:
 	gtkspellcheck = None
 
 	try:
-		import gi
 		gi.require_version('GtkSpell', '3.0')
 		from gi.repository import GtkSpell as gtkspell
 	except:
```

**Comment by faitjx** [comment]
The patch got mangled somewhat.  grab the markup to get the corrected output.

**Comment by introt** [comment]
Please repost the patch with proper quoting (use the three ticks for multiline and see the preview before posting), there's no option to "grab the markup" in GitHub
