### ISSUE TITLE
Indexing at stratup freeze

### ISSUE THREAD

**Issue by OCTOGONE-DEV** [zim-desktop-wiki/zim-desktop-wiki#2315]
**Describe the bug**
when i launch Zim, i have a diolog box saying "indexing", but it does nt index, it's freezed, and i'm forced to "kill" zim. This i'am not able dto use Zim anymore.

**Screenshots**
![image](https://user-images.githubusercontent.com/40270594/216843431-f7b87e73-b9a3-487b-ad06-b3c0a768f10f.png)

**Comment by introt** [comment]
Please open a new ticket with all the details filled out - preferably with debug logs, if you're able to start Zim from the command line using `zim --debug` - otherwise we have little to work with to help you out. Thanks!
