### ISSUE TITLE
clicking link from... https://zim-wiki.org/downloads = Forbidden You don't have permission to access this resource.

### ISSUE THREAD

**Issue by JaymeisterJay** [zim-desktop-wiki/zim-desktop-wiki#2326]
clicking link from...
  https://zim-wiki.org/downloads.html
for 
  "Windows installer"  (also Unofficial ubuntu package)
result: 
  Forbidden You don't have permission to access this resource.

**Comment by jaap-karssenberg** [comment]
Yes this is due to an upgrade of the provider today. Will look into it
tomorrow.


Thanks for the alert!

Op ma 27 feb. 2023 14:42 schreef JaymeisterJay ***@***.***>:

**Comment by jaap-karssenberg** [comment]
Downloads folder is accessible again!
