### ISSUE TITLE
Keyboard not working in Zim Wiki on Windows 10

### ISSUE THREAD

**Issue by JM1978** [zim-desktop-wiki/zim-desktop-wiki#2338]
I am using Zim 0.73.3 on Windows 10 Home.  Suddenly, today, I cannot type in any of my pages; a cursor does not even appear.  I noticed I get a chime from my speaker when I try to type within the Zim pages.  I've checked to make sure I do not have "sticky keys" enabled in Windows, and I do not.

I have no problems with my keyboard in any other applications I am using today.  I rebooted my laptop, but this has not fixed the issue.
Unfortunately, I cannot think of any information that would help re-create this bug (if, indeed, it is a bug) on another system.

**Comment by jaap-karssenberg** [comment]
There is an icon in the toolbar / window border to toggle the window
read-only - have you checked that on accident maybe ?

-- Jaap

**Comment by JM1978** [comment]
Well, this is slightly embarrassing.  Yes, that was absolutely the problem.  I must have inadvertently toggled the Notebook Editable tool.

Thank you for your quick response!
