### ISSUE TITLE
075.1 Does not start

### ISSUE THREAD

**Issue by Teiper** [zim-desktop-wiki/zim-desktop-wiki#2351]
This is zim 0.75.1
Platform: nt
Locale: nl_NL cp1252
FS encoding: utf-8
Python: (3, 10, 8, 'final', 0)
PyGObject: (3, 42, 1)
======= Traceback =======
File "zim/main/__init__.py", line 962, in main
File "zim/main/__init__.py", line 733, in run
File "zim/main/__init__.py", line 764, in _run_cmd
File "zim/main/__init__.py", line 806, in _run_main_loop
File "zim/main/__init__.py", line 278, in run
File "zim/main/__init__.py", line 323, in _run_new_window
File "zim/plugins/__init__.py", line 111, in _init_wrapper
File "zim/gui/mainwindow.py", line 549, in __init__
File "zim/gui/mainwindow.py", line 818, in open_page
File "zim/notebook/index/__init__.py", line 300, in touch_current_page_placeholder
File "zim/notebook/index/pages.py", line 177, in insert_link_placeholder
File "zim/notebook/index/pages.py", line 225, in _insert_page
TypeError: 'NoneType' object is not subscriptable**Describe the bug**

1. After a sudden disconnection in the electrical supply ZIM was opened when that disconnection occured and at the time I was working with it.
2. I started up my computer again. 
3. I clcked the ZIM hotkey an tried to open a notebook
4. I got the bugreport, see above. 
5. I tried an other time and got the same result.
6. I filed my first bugreport ever.

**Expected behavior** I of course expected ZIM to open the notebook I had chosen.

**Screenshots** not available

**Acer laptop **
 - Version [075.1
 - windows
 - Dutch

**Additional context** **none**

For issues triggered by specific page content, **does not apply**

For issues with no visible output / error, **does not apply**

**Comment by introt** [comment]
Since you've closed the ticket, I assume you've solved the issue. Would you care to share the solution with us - was it clearing the cache, reinstalling Zim or running a `fsck` on the disk?

Regardless, I hope you have verified backups - two or more extra copies of your valuable data - in case of data loss or corruption, and a tested method of restoring from one of those.

**Comment by Teiper** [comment]
Well, not having experience with  github? I closed the ticket by accident. Don't know if it can be openend again. So, no solution from this side of the line, sorry.PieterVerzonden vanaf mijn Galaxy
-------- Oorspronkelijk bericht --------Van: introt ***@***.***> Datum: 18-04-2023  16:45  (GMT+01:00) Aan: zim-desktop-wiki/zim-desktop-wiki ***@***.***> Cc: Teiper ***@***.***>, State change ***@***.***> Onderwerp: Re: [zim-desktop-wiki/zim-desktop-wiki] 075.1 Does not start (Issue #2351) 
Since you've closed the ticket, I assume you've solved the issue. Would you care to share the solution with us - was it clearing the cache, reinstalling Zim or running a fsck on the disk?
Regardless, I hope you have verified backups - two or more extra copies of your valuable data - in case of data loss or corruption, and a tested method of restoring from one of those.

**Comment by introt** [comment]
I've reopened the ticket for you. Please back up your wiki, try emptying the cache and reinstalling Zim. You can check whether your wiki files are in a good shape by opening them up in a regular text editor.

**Comment by Teiper** [comment]
Thanks for the suggesties. I'll make backups from now on. Zim is OK now.
