### ISSUE TITLE
[question] Is generation docs from source code supported? 

### ISSUE THREAD

**Issue by kde-baskets-user** [zim-desktop-wiki/zim-desktop-wiki#2354]
"make epydoc" gives errors, Is this supported?

**Comment by introt** [comment]
"Kind of" to the title, "no" to the comment - epydoc is deprecated. See #155 for the current progress on moving to Sphinx (TL;DR: all the automated tools I tested were lacking & we need custom fields for Sphinx to boot) and https://github.com/introt/zim-desktop-wiki/commit/abc8cf12b711cff6fceb26fdd4a941f824137deb for the `pydoctor` command for doc generation. My attempts can be found at https://introt.github.io/zim-desktop-wiki/docs/build/html/ (Sphinx) and https://introt.github.io/zim-desktop-wiki/docs/api/ (pydoctor) - as both predate GitHub Actions, building an automated Workflow for docs on `develop` push would be very cool. See eg. https://github.com/introt/docs/blob/main/.github/workflows/deploy-to-ghpages.yml for reference.
