### ISSUE TITLE
Search function error

### ISSUE THREAD

**Issue by Spheerys** [zim-desktop-wiki/zim-desktop-wiki#2359]
**Describe the bug**
With last version (0.75.1), I can't use the search function.
I get this error : 

> This is zim 0.75.1
> Platform: posix
> Locale: fr_FR UTF-8
> FS encoding: utf-8
> Python: (3, 10, 10, 'final', 0)
> PyGObject: (3, 44, 1)
> 
> ======= Traceback =======
>   File "/usr/lib/python3.10/site-packages/zim/actions.py", line 159, in _on_activate
>   File "/usr/lib/python3.10/site-packages/zim/actions.py", line 130, in __call__
>   File "/usr/lib/python3.10/site-packages/zim/gui/uiactions.py", line 281, in show_search
> ModuleNotFoundError: No module named 'zim.gui.searchdialog'

**To Reproduce**
1. Launch Zim
2. Launch search function with CTRL+F
2. See error

**Expected behavior**
See the search dialog

**Environment (please complete the following information):**
 - Version [e.g. 0.75.1] 
 - OS: Linux/Arch

**Comment by jaap-karssenberg** [comment]
Sounds like an issue with your installation. Please close zim, backup you
notebook and try re-installing the package.

--- Jaap

**Comment by Spheerys** [comment]
The issue is gone mysteriously !
You can clone it...
