### ISSUE TITLE
umldiagrameditor: Error when trying to insert UML diagram

### ISSUE THREAD

**Issue by StaringAtTheSun** [zim-desktop-wiki/zim-desktop-wiki#2361]
I know, umldiagrameditor is a third party plugin, but maybe someone could help me with this problem:

- Using Ubuntu 20.04.6 LTS
- Installed Zim (0.72.0-1) from package manager
- Installed plantuml (1:1.2018.13+ds-2) from package manager (this installed Java openjdk-11-jre)
- Copied [umldiagrameditor.py](https://gitlab.com/Voyvode/zim-umldiagrameditor/-/blob/master/umldiagrameditor.py) to plugin folder
- Plugin "Insert UML Diagram" available in Edit->Preferences->Plugins; enabled

Everytime I try to insert an UML diagram (Insert->UML diagram), a "Looks like you found a bug" window opens with the following information:

> This is zim 0.72.0
> Platform: posix
> Locale: en_US UTF-8
> FS encoding: utf-8
> Python: (3, 8, 10, 'final', 0)
> PyGObject: (3, 36, 0)
> 
> ======= Traceback =======
>   File "/usr/lib/python3/dist-packages/zim/gui/insertedobjects.py", line 441, in _action_handler
>     model = otype.new_model_interactive(self.pageview, notebook, page)
>   File "/usr/lib/python3/dist-packages/zim/plugins/base/imagegenerator.py", line 51, in new_model_interactive
>     model = self.model_from_data(notebook, page, attrib, data)
>   File "/usr/lib/python3/dist-packages/zim/insertedobjects.py", line 82, in _model_from_data_wrapper
>     return self._inner_model_from_data(notebook, page, attrib, data)
>   File "/usr/lib/python3/dist-packages/zim/plugins/base/imagegenerator.py", line 78, in model_from_data
>     return BackwardImageGeneratorModel(notebook, page, generator, attrib, data, self.scriptname, self.imagefile_extension)
>   File "/usr/lib/python3/dist-packages/zim/plugins/base/imagegenerator.py", line 126, in __init__
>     self.script_file = folder.new_file(scriptname, check_image_file)
>   File "/usr/lib/python3/dist-packages/zim/newfs/base.py", line 472, in new_file
>     return self._new_child(path, self.file, check)
>   File "/usr/lib/python3/dist-packages/zim/newfs/base.py", line 502, in _new_child
>     if check is None or check(child):
>   File "/usr/lib/python3/dist-packages/zim/plugins/base/imagegenerator.py", line 122, in check_image_file
>     new_image_file = self._stitch_fileextension(new_script_file, imagefile_extension)
>   File "/usr/lib/python3/dist-packages/zim/plugins/base/imagegenerator.py", line 132, in _stitch_fileextension
>     i = basename.rfind('.')
> AttributeError: 'NoneType' object has no attribute 'rfind'

**Comment by dehesselle** [comment]
Sorry, but that's not how this works. You know it's an external plugin, please report it to the [appropriate issue tracker](https://gitlab.com/Voyvode/zim-umldiagrameditor/-/issues). This way the problem can be fixed for everybody.
