### ISSUE TITLE
Pin Index Page Item to the top of the list

### ISSUE THREAD

**Issue by XexusUs** [zim-desktop-wiki/zim-desktop-wiki#2364]
I would like to be able to Pin my default page (the one that associates with Alt-Home) to the top of the Index List.  Looking over the discussion threads I've found so far, many do it by appending a "1" to the page name, but that looks a bit aesthetically hackish.  

That said, barring a "Pin to Top" preference, I would be happy to just employ a symbol rather than a "1", but all the ones I've tried already have wiki meanings and can't be used.  

edit: When I look at "Move or Rename Page", the default says "<top>", and I wonder if that's what is supposed to be pinning it to the top, and for some reason just isn't

**Comment by introt** [comment]
Thanks for the feature request, please add it to #32 as it's closely related (both concern having the index represent something other than the filesystem layout & order).

> edit: When I look at "Move or Rename Page", the default says "", and I wonder if that's what is supposed to be pinning it to the top, and for some reason just isn't

`<Top>` means the top of the hierarchy, aka `:`/the notebook folder, not the top of the list.

As an alternative workaround, there is the home page button at the menu bar (when the CSD are enabled) so you could also stash it out of sight and use that?

**Comment by XexusUs** [comment]
Eventually I decided what I really needed to do was create multiple notebooks.  Now that I've read over that feature request thread you mentioned, I see that I've been thinking of the Index as a Table of Contents.  Using multiple notebooks has been working out well, but now I know why that was a good idea.

Thanks :)
