### ISSUE TITLE
On start Index keeps forever in a loop

### ISSUE THREAD

**Issue by mesmoiron** [zim-desktop-wiki/zim-desktop-wiki#2367]
Hi,

I'm on Ubuntu 22.04 LTS desktop. After installing the app; it keeps forever indexing and doesn't save, add subpages etc. With each menu choice, it goes back to the indexing issue.

**Comment by jaap-karssenberg** [comment]
Can you provide a bit more info? .

E.g. what do you observe, indexing dialoog?

E.g. any special configuration on the filesystem that could trigger it?

E g. What folder did you define as notebook, does it have existing files?

Op vr 26 mei 2023 11:37 schreef Hèlen Grives ***@***.***>:

**Comment by mesmoiron** [comment]
I am a bit puzzled. This is the 4th time I tried to install the software. However now that I have filed a bug report; it suddenly works. I like the program, so I am happy it has been solved. Thank you for your swift reply.

**Comment by jaap-karssenberg** [comment]
If it comes back, see if you can capture some info from the debug logging
or similar. Thanks for updating us!

--- Jaap
