### ISSUE TITLE
"Move Selected Text" menu option does not work. 

### ISSUE THREAD

**Issue by Eudaimonium** [zim-desktop-wiki/zim-desktop-wiki#2370]
Click Tools / Move Selected Text 

Following window instantly appears:
![image](https://github.com/zim-desktop-wiki/zim-desktop-wiki/assets/1208969/283fb083-6b93-47dc-ba1d-183eb561e454)

**Comment by introt** [comment]
Thanks for the report! The menu option should work, but shouldn't be active unless text is selected. This should have been fixed by #2247 and I can not reproduce the issue on the latest version.
