### ISSUE TITLE
Background color for the TextView in style.conf

### ISSUE THREAD

**Issue by vbuell** [zim-desktop-wiki/zim-desktop-wiki#2378]
It seems like the background color is not configurable for the text viewport. Tried to add background property to the [TextView] and it's being ignored (I guess TextView and Tag use different sets of properties). Having this feature would open a path to have zim's color theme fully configurable (my personal dream feature is zim-notes to to have the theme manager with a few predefined themes available - "light solarized", etc).

**Comment by jaap-karssenberg** [comment]
This is not a bug. For theming beyond text properties, please use Gtk
themes / Gtk CSS configuration.

Regards,

jaap

**Comment by introt** [comment]
Please see https://github.com/zim-desktop-wiki/zim-desktop-wiki/discussions/1802#discussioncomment-1798274 / the TextView styling plugin: https://omacronides.com/projets/zim-plugin-textview-prefs/
