### ISSUE TITLE
Adding a sub-page with + does not work if the 

### ISSUE THREAD

**Issue by bjjanssen** [zim-desktop-wiki/zim-desktop-wiki#2390]
Adding a sub-page with + does not work if the pagename is a number

**Describe the bug**
When adding a sub-page with +, eg. 
`+foo`
Zim creates a link and a placeholder in the pages tree. 

When I try to do the same with a with a name consisting of numbers, it fails. Example:
`+2000`
does not create a link and a placeholder. 

I tried some variations. It works if the number is pre- or postfixed with at least two characters, eg.
`+xx2000`
or
`+2000xx`

A single character is not sufficient, eg.
`+x2000`
and 
`+2000x`
fail.

**To Reproduce**
Open a page in Zim. Type
`+2000`

**Expected behavior**
I expect Zim to create a link.

**Screenshots**
[https://ibb.co/K0Vx523](Screenshot)

**Environment (please complete the following information):**
Package: zim
Version: 0.75.1-1
Debian Bookworm
German Language

**Additional context**
zim -D does not reveal any further information.

**Comment by jaap-karssenberg** [comment]
This is not a bug but expected behavior. A page name must contain some
letters to be recognized when typing. This is to avoid issues with e.g.
time and date notations.


Op di 20 jun. 2023 19:09 schreef Björn Janßen ***@***.***>:

**Comment by bjjanssen** [comment]
OK, thank you. If this is intended behaviour, I think the manual should be updated. I guess this one,  data/manual/Help/Links.txt, is the relevant source file?

Haven't used git for a good time now, so bear with me if it takes a while.

**Comment by jaap-karssenberg** [comment]
Good point. I can do the update myself as I'm preparing a new point release
anyway .

Regards,

Jasp

Op wo 21 jun. 2023 08:49 schreef Björn Janßen ***@***.***>:

**Comment by jaap-karssenberg** [comment]
P.S. you can create links to pages with only numbers in the name using the
"Insert Link" dialog ( <Ctrl>L )

--- Jaap

**Comment by jaap-karssenberg** [comment]
Ironically, when checking I found out that the intended behavior to exclude
links like "10:20PM" was in fact broken. So will also do a small patch to
make it work as intended and document the limitations of auto-formatting
links.

--- Jaap

**Comment by bjjanssen** [comment]
I suppose +10:20PM should not become a link? ;) Anyway, if you update the manual, I'll strike it from my todo-list. Thank you for a great piece of software.
