### ISSUE TITLE
Error on update to 0.75.2 debian 11

### ISSUE THREAD

**Issue by MarcFaidherbe** [zim-desktop-wiki/zim-desktop-wiki#2413]
**Describe the bug**
When I try to update from 0.75.1 to 0.75.2 on debian 11 I get an error

> dpkg-deb: error: archive 'zim_0.75.2_all.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive zim_0.75.2_all.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 zim_0.75.2_all.deb

> /usr/bin/gdebi:113: FutureWarning: Possible nested set at position 1
  c = findall("[[(](\S+)/\S+[])]", msg)[0].lower()
dpkg-deb: error: archive 'zim_0.75.2_all.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive zim_0.75.2_all.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 zim_0.75.2_all.deb

**To Reproduce**

`sudo dpkg -i zim_0.75.2_all.deb`
`sudo gdebi zim_0.75.2_all.deb`

**Comment by dehesselle** [comment]
I assume you have downloaded the `.deb` file from https://zim-wiki.org/downloads.html ? It says "Unofficial **Ubuntu** package", not Debian. Your Debian version does not support `zstd` compression in `.deb` files.

**Comment by MarcFaidherbe** [comment]
Exactly, but previously I downloaded on the same link and it run perfect. Thanks for your return. I close the issue.
