### ISSUE TITLE
Tab indents on lines starting with tab are not aligned with lines not starting with tab

### ISSUE THREAD

**Issue by hsandt** [zim-desktop-wiki/zim-desktop-wiki#2418]
**Describe the bug**
The final position of tab indents differ depending on whether you start a line with a tab, or you inserted the tab after some other characters.

I know that tabs at line start have a special behavior, as you cannot move the caret to their left, and next lines are automatically indented the same way. However, in my case this misalignment causes me troubles as I'm using tabs to simulate a table.

**To Reproduce**
1. Simulate a table by entering column names on a first line, separated with tab indents
2. Add another line filling all entries, separated with tabs
3. Add another line but skip the 1st entry this time (this happens when you don't need to add new info for 1st column, but only for the other columns)
4. Note how you cannot get the next column aligned with the previous line: tab goes either too much to the left, or to the right.

It's easier to explain with an actual example:

Copy-paste the pseudo-table below to Zim (note that it is not displayed at all at in Zim on GitHub, so don't mind the odd layout):
```
Date		Time		Total time
May 5		2h			2h
-			1h			3h
		1h			3h
			1h			3h
```

You will obtain something that look like this (this time, look at layout on GitHub):

```
Date        Time	    Total time
May 5       2h            2h
-           1h            3h
          1h           3h
               1h           3h
```

or better, here is a screenshot:

![image](https://github.com/zim-desktop-wiki/zim-desktop-wiki/assets/1067772/2f736127-5da0-4cd0-98f1-c09435b66e6f)

**Expected behavior**
It should always be possible to align text with tab indents, whether the line starts with an indent or not.

My assumption is that Zim uses previous characters as a reference to determine indent size, so it uses so standard size when the line starts with an indent, different from the size after an actual character.

This would also explain why bold characters lead to different indents and alignments, as noted in https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/703

Unfortunately, those two issues make it hard to use pseudo-table for new users (and I cannot use actual tables because of table issues https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/1677 and https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/591).

Fortunately, like 703, there is a workaround for this:

**Workaround**
Add a dummy character like hyphen `-` at the start of each line.

My worklogs, where I put multiple tasks per day, all look like this:

![image](https://github.com/zim-desktop-wiki/zim-desktop-wiki/assets/1067772/ea9c9334-5846-442f-a144-e705cb576ea7)

**Environment (please complete the following information):**
 - Version 0.75.2
 - OS: Linux Ubuntu 22.04 with Unity desktop
 - Language: English

**Comment by hsandt** [comment]
Oddly enough, it seems that adding a hyphen `-` *then* removing it will keep the aligned indent, although we end with the same state as if we started the line with a tab indent. Maybe final source differs, didn't check.

**Comment by introt** [comment]
> However, in my case this misalignment causes me troubles as I'm using tabs to simulate a table.

Simulating tables using tabs and non-fixed-width fonts is not and will not be supported. If you must, combine verbatim and spaces
