### ISSUE TITLE
distutils is deprecated and it was removed in python 3.12

### ISSUE THREAD

**Issue by topazus** [zim-desktop-wiki/zim-desktop-wiki#2420]
**Describe the bug**

The distutils is deprecated and it was removed in python 3.12.
The Python 3.12 is available in Fedora Rawhide.

https://github.com/python/cpython/issues/92584
https://fedoraproject.org/wiki/Changes/Python3.12

**Comment by jaap-karssenberg** [comment]
This is in scope of #2209

**Comment by introt** [comment]
Duplicate of #2296 which in turn is in scope of #2209
