### ISSUE TITLE
Screenshot plugin fails on Wayland on Fedora 38 

### ISSUE THREAD

**Issue by oturpe** [zim-desktop-wiki/zim-desktop-wiki#2424]
**Describe the bug**
Screenshot plugin fails on Wayland on Fedora Workstation 38.
This is GNOME 44.2 desktop environment.
When using an X session, the screenshot is captured as expected.

The following output appears in the debug log:

```
DEBUG: Action: insert_screenshot
DEBUG: Opening dialog "Insert Screenshot"
DEBUG: Dialog response OK
INFO: Spawning: ('import', '-silent', '-window', 'root', '/tmp/zim-ex3ub765/insert-screenshot.png') (cwd: /home/otto)
DEBUG: Process started with PID: 5239
DEBUG: Closed dialog "Insert Screenshot"
import: unable to read X window image 'root': Resource temporarily unavailable @ error/xwindow.c/XImportImage/5065.
import:  `/tmp/zim-ex3ub765/insert-screenshot.png' @ error/import.c/ImportImageCommand/1289.
DEBUG: Running ErrorDialog
DEBUG: Some error occurred while running "import"
NoneType: None
ERROR: Some error occurred while running "import"
```

**To Reproduce**
1. Start Zim.
2. **Edit** → **Preferences** → **Plugins**, enable _Insert Screenshot_
3. **Insert** → **Screenshot...**
4. **OK**
5. Observe dialog: _Some error occurred when running "import"_
6. **Close**
7. **Tools** → **View Debug Log**
8. Observe the log rows given in description. 

**Expected behavior**
Screenshot is taken and added to current cursor position.

**Screenshots**
n/a

**Environment (please complete the following information):**
 - Version 0.75.2
 - OS: Fedora Workstation 38, GNOME 44.2, Wayland.
 - Language: Initially observed with fi-FI, reproduces also with C.UTF-8. I do not think this is language related.

**Additional context**
Usually, when I have encountered screenshot problems with Fedora,
they have been related to the fact that capturing a screenshot on Wayland is only possible through the screenshot portal.
Perhaps the screenshot plugin is not aware of this and is just attempting to do it as it is done on X?

**Comment by introt** [comment]
> Usually, when I have encountered screenshot problems with Fedora,
they have been related to the fact that capturing a screenshot on Wayland is only possible through the screenshot portal.

The plugin source code references `scrot`, `import`, `boxcutter` and `gnome-screenshot`. According to your logs, its trying to use `import` which in turn tries to use X.

According to this issue, `gnome-screenshot` should work on Wayland as long as you're trying to capture Wayland apps:

https://gitlab.gnome.org/GNOME/gnome-screenshot/-/issues/185

Perhaps the screenshot plugin should evaluate dependencies based on whether we're running on Wayland or X11 in addition to the `nt`/`posix` check (macOS support when??)

**Comment by dehesselle** [comment]
> Perhaps the screenshot plugin should evaluate dependencies based on whether we're running on Wayland or X11 in addition to the `nt`/`posix` check (macOS support when??)

On macOS there is `screencapture` which is quite configurable.


<details>
  <summary>screencapture commandline help</summary>

```text
usage: screencapture [-icMPmwsWxSCUtoa] [files]
  -c         force screen capture to go to the clipboard
  -b         capture Touch Bar - non-interactive modes only
  -C         capture the cursor as well as the screen. only in non-interactive modes
  -d         display errors to the user graphically
  -i         capture screen interactively, by selection or window
               control key - causes screenshot to go to clipboard
               space key   - toggle between mouse selection and
                             window selection modes
               escape key  - cancels interactive screenshot
  -m         only capture the main monitor, undefined if -i is set
  -D<display> screen capture or record from the display specified. -D 1 is main display, -D 2 secondary, etc.
  -o         in window capture mode, do not capture the shadow of the window
  -p         screen capture will use the default settings for capture. The files argument will be ignored
  -M         screen capture output will go to a new Mail message
  -P         screen capture output will open in Preview or QuickTime Player if video
  -I         screen capture output will open in Messages
  -B<bundleid> screen capture output will open in app with bundleid
  -s         only allow mouse selection mode
  -S         in window capture mode, capture the screen not the window
  -J<style>  sets the starting of interfactive capture
               selection       - captures screen in selection mode
               window          - captures screen in window mode
               video           - records screen in selection mode
  -t<format> image format to create, default is png (other options include pdf, jpg, tiff and other formats)
  -T<seconds> take the picture after a delay of <seconds>, default is 5
  -w         only allow window selection mode
  -W         start interaction in window selection mode
  -x         do not play sounds
  -a         do not include windows attached to selected windows
  -r         do not add dpi meta data to image
  -l<windowid> capture this windowsid
  -R<x,y,w,h> capture screen rect
  -v        capture video recording of the screen
  -V<seconds> limits video capture to specified seconds
  -g        captures audio during a video recording using default input.
  -G<id>    captures audio during a video recording using audio id specified.
  -k        show clicks in video recording mode
  -U        Show interactive toolbar in interactive mode
  -u        present UI after screencapture is complete. files passed to command line will be ignored
  files   where to save the screen capture, 1 file per screen
```  

</details>

**Comment by introt** [comment]
> On macOS there is screencapture which is quite configurable.

@dehesselle Do you want to submit a PR or open a new issue for this? I don't have a Mac to test with.

Afaik just needs to be listed here:

https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/c88cf3cb53896bf272e87704826b77e82eddb3ef/zim/plugins/screenshot.py#L30-L33

And here:

https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/c88cf3cb53896bf272e87704826b77e82eddb3ef/zim/plugins/screenshot.py#L39-L65
