### ISSUE TITLE
Add a task and have it show up on journal

### ISSUE THREAD

**Issue by jungle-boogie** [zim-desktop-wiki/zim-desktop-wiki#2438]
Hello,

Discussion link: https://github.com/zim-desktop-wiki/zim-desktop-wiki/discussions/2430

Basic idea is to have a single page, "my tasks", with things to do and due dates.
Then those items will appear on the corresponding journal page.

The advantage of this is that you won't have to go into the journal for future events, since the "my tasks" page will have the due date.

Thanks for the consideration!

**Comment by introt** [comment]
Please use the Discussions to propose new features, the Issues are meant for bugs and features being actively worked on by developers requiring input from other developers (see #1610 for why)
