### ISSUE TITLE
source_view - Slow scrolling

### ISSUE THREAD

**Issue by plegrand1** [zim-desktop-wiki/zim-desktop-wiki#2459]
ZIM 0.75.2
Windows 11 pro

------------------

Hello,
I was looking for a solution that would allow me to insert code into a ZIM page while respecting the various characters and, above all, the indentation.
I noticed that by default, spaces were all replaced by tabs.
One proposed solution was to use the "Verbatim" format, but I have the impression that even in verbatim, spaces are replaced by tabs.
So I activated the "source_view" plugin, which is exactly what I was looking for.
However, I found that inserting a block of code slowed down the scrolling of the page enormously. (mouse wheel).
Have you noticed this problem?

Thanks for your help

Pascal

**Comment by introt** [comment]
Might be due to a workaround for #1693

**Comment by introt** [comment]
Closing in favor of #2480
