### ISSUE TITLE
ZIM 74.3:  Pages followed from links showing like a text file rather being properly formatted

### ISSUE THREAD

**Issue by mbluett88** [zim-desktop-wiki/zim-desktop-wiki#2461]
**Describe the bug**
Following a link, pointing at another Notebook page, results in the page displaying as text (rather than as formatted text). This is because the linked page is opened in an external editor rather than in Zim. This did not occur when I was using Linux Mint 20.3.

There does not appear to anything obvious in Edit > Preferences to prevent that from happening.

**To Reproduce**
1. Create a link pointing at any other Notebook page
2. Click on the link

**Expected behavior**
I expect to see the page open within Zim (and not in an external text editor).

**Screenshots**
What I expect:
![image](https://github.com/zim-desktop-wiki/zim-desktop-wiki/assets/64982429/5ebe76c0-da0d-4d2d-8b9b-44d1e5c18dc8)
What actually occurs:
![image](https://github.com/zim-desktop-wiki/zim-desktop-wiki/assets/64982429/4cf4de3d-135f-4e63-9a15-044b8fe0dc8b)

**Environment (please complete the following information):**
 - Version: 74.3
 - OS: Linux Mint 21.2
 - Language: English

**ZIM Log File section:**
```
DEBUG: Action: insert_link
DEBUG: Opening dialog "Edit Link"
DEBUG: Opening dialog "Select File"
DEBUG: Dialog response OK
DEBUG: Closed dialog "Select File"
DEBUG: Dialog response OK
DEBUG: Closed dialog "Edit Link"
DEBUG: Action: save_page
DEBUG: Saving page: Books:The Unusual
DEBUG: Store page: Books:The Unusual
DEBUG: Index file: /home/mike/Notebooks/Books/The_Unusual.txt
DEBUG: Action: save_page
DEBUG: Saving page: Books:The Unusual
DEBUG: Store page: Books:The Unusual
DEBUG: Index file: /home/mike/Notebooks/Books/The_Unusual.txt
DEBUG: Activate link: ../../Book_Contents/N/91_Predictions_-_The_Fate_of_the_World_and_Its_People_in_the_Next_Half_Century_(2020).txt
DEBUG: open_file(/home/mike/Notebooks/Book_Contents/N/91_Predictions_-_The_Fate_of_the_World_and_Its_People_in_the_Next_Half_Century_(2020).txt, None)
INFO: Spawning: ('xdg-open', '/home/mike/Notebooks/Book_Contents/N/91_Predictions_-_The_Fate_of_the_World_and_Its_People_in_the_Next_Half_Century_(2020).txt') (cwd: /home/mike)
DEBUG: Process started with PID: 78539
```

**Comment by mbluett88** [comment]
UPDATE: I discovered a setting by right-clicking the page link and selecting Open with... > Customize. When that is set to Zim links open as expected (within Zim). Have no idea why this is not set as the default. Nor, why an option is not present within Edit > Preferences. Seems a little counter-intuitive.

**Comment by introt** [comment]
Please see the manual regarding pages[^0] and links[^1] - from your description it seems you're not actually linking to pages (eg. `Home:Page 1`), but instead are linking to their source files (eg. `Home/Page_1.txt`).

[^0]: https://zim-wiki.org/manual/Help/Pages.html
[^1]: https://zim-wiki.org/manual/Help/Links.html

**Comment by mbluett88** [comment]
Did I not close that issue? I thought I did as I had discovered how to fix
it.

**Comment by introt** [comment]
Yes, you did close this issue. However, your fix is actually a workaround; I popped in to guide you towards the proper way to link between pages, as linking to source files instead of pages breaks many of Zims features, including Backlinks, links in exports, and automatic link updates when moving or renaming pages.

This is also why file links are not set to open in Zim by default. If you want to link between notebooks, use InterWiki links of the form `NotebookName?Home:Page`.

**Comment by mbluett88** [comment]
You are making an assumption about what I am doing that is incorrect. I am
linking to pages. In fact, that is all I have ever done as far as I know. I
don't understand how you think I am not doing that.

**Comment by mbluett88** [comment]
Maybe I should have asked you what the difference is between linking
between a source file and a page is. How are these two operations performed
(i.e., How would I know I am doing one and not the other)?

**Comment by mbluett88** [comment]
I use the Insert > Link dialog to create links. I have always done that. If this mechanism is creating file links, as you seem to be suggesting, it seems that whoever devised that mechanism did not design it properly. And I do see that all of the links I have established, using this dialog, are file links.

So, are you saying after I establish a link using this dialog that I should edit it so that it uses colons instead of forward slashes?

Seems like that is a pretty poor implementation.

**Comment by introt** [comment]
I'm afraid you've been using the dialog incorrectly due to its bad UX: our link dialog handles both in-wiki links and file links.

To link to pages, you should start typing in the name of the target page; the "Browse"-button is strictly for linking to files. When used "as intended" the dialog produces page links with colons, plusses etc., no editing needed.

Apologies for the confusion! I'll open a ticket so we can get this fixed.
