### ISSUE TITLE
Shorcut for "open in a new window"

### ISSUE THREAD

**Issue by alfinal** [zim-desktop-wiki/zim-desktop-wiki#2466]
In order to quickly get the page content in a new window, a shortcut would be nice.

**Comment by sojusnik** [comment]
It's already possible. You can find it in settings > shortcuts

**Comment by alfinal** [comment]
> It's already possible. You can find it in settings > shortcuts

Ok, I'm going to update Zim. I'm not using last version, sorry for open an already fixed issue.
