### ISSUE TITLE
:TopLevelPage no longer autoformats as a link

### ISSUE THREAD

**Issue by mikro2nd** [zim-desktop-wiki/zim-desktop-wiki#2469]
`:TopLevelPage` no longer autoformats as a link when typed, making it painful to create links to top-level pages, as link creation has to be done via the (`Ctrl-L`) link dialogue.

**To Reproduce**
In a sub-page, type a link to a top-level page (e.g. `:Home`). The text does *not* get recognised as a link as expected. It makes no difference whether the page already exists or not.

**Expected behavior**
`:TopLevePage` ought to be recognised and formatted as a link to a top-level page (existing or new).

**Environment (please complete the following information):**
 - Version 0.75.2
 - OS: linux (Kubuntu 20.04)
 - Language: en-GB

**Additional context**
Bug seems to have started with 0.75.[12] (from memory, so not totally reliable!)

**Comment by introt** [comment]
Thanks for the thorough report. This regression was introduced by 7418256, I'll submit a PR
