### ISSUE TITLE
Caret/cursor sometimes invisible after clicking elsewhere in the editor

### ISSUE THREAD

**Issue by tridian-tn** [zim-desktop-wiki/zim-desktop-wiki#2470]
**Describe the bug**
The caret doesn't always appear when clicking in the editor.

**To Reproduce**
1. Open a new page in Zim
2. Add some text
3. Click around the text to move the caret 
4. The caret isn't always visible, even though if you then press (e.g.) shift, it reappears.

**Expected behavior**
The caret should always be visible, blinking away.

**Screenshots**
I'm clicking more often here than the caret moves would suggest! Yellow highlights are the click detection in the recorder s/w
![ZimCaretVisibility](https://github.com/zim-desktop-wiki/zim-desktop-wiki/assets/10810780/90d06494-5a15-40d9-9c54-5a70b08aee9a)

**Environment (please complete the following information):**
 - Version: 0.75.2
 - OS: Windows
 - Language: UK English

**Additional context**
Nothing logged in the debug log whilst this is happening

I wondered if it was the same issue as https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/1715 but that issue focuses on the Code Block plugin

**Comment by roland-ruedenauer** [comment]
@tridian-tn can you please check if this problem also disappears when you have disabled the "Textview Preferences" plugin? I experience the sporadic cursor visibility issue when the CssProvider is set on the TextView widget by this plugin.

**Comment by tridian-tn** [comment]
> @tridian-tn can you please check if this problem also disappears when you have disabled the "Textview Preferences" plugin? I experience the sporadic cursor visibility issue when the CssProvider is set on the TextView widget by this plugin.

@roland-ruedenauer Great idea, and yes it does appear to have gone now that the plugin has been disabled. I'll close this issue, and make a note to self that I should disable all unnecessary plugins before raising issues.

@introt @jaap-karssenberg Sorry for tagging both of you but I'm not sure whose remit this falls under: Could this maybe be added to the default issue text template? e.g. "Is the issue reproducible when all Zim plugins are disabled?" or something similar

**Comment by introt** [comment]
Makes sense, perhaps under environment?

https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md and https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/develop/.github/ISSUE_TEMPLATE/bug-report-for-development-branch-or-snapshot-ppa.md are the files

**Comment by tridian-tn** [comment]
> Makes sense, perhaps under environment?
> 
> https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md and https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/develop/.github/ISSUE_TEMPLATE/bug-report-for-development-branch-or-snapshot-ppa.md are the files

Thanks. I'll raise a PR
