### ISSUE TITLE
[feature request ] drag and drop files not appearing in cursor position .its appearing in top of the editor page

### ISSUE THREAD

**Issue by keralaboy123** [zim-desktop-wiki/zim-desktop-wiki#2475]
when we drag and drop files/images from explorer/firefox or other softwares  to zim editor.
its path/image is appearing in top of editor page. its not in current mouse cursor position

**Describe the solution you'd like**

when drag and drop any file and its not image  then only a link should appear in the current mouse  cursor position. its text shouldbe ""name of that file""  and link should be pointed to  its location on filesystem

**Comment by keralaboy123** [comment]
hi can you point me to source code where it is handling.i might able to develope this feature.

**Comment by introt** [comment]
Hi! The dragged-and-dropped content should show up at the cursor position (not where the cursor was, but where the cursor would be if the mouse was clicked then ending the drag). If this isn't happening, it's a bug. If so, please fill out a bug ticket, as this contains necessary information about your setup; feature requests should begin over at Discussions. Thanks!

**Comment by introt** [comment]
> hi can you point me to source code where it is handling.i might able to develope this feature.

I believe this is the code responsible for the behavior you described:

https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/64f2206e57505a5129206b7725983b780771a599/zim/gui/pageview/__init__.py#L7230-L7270

You might also find this helpful:

https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/64f2206e57505a5129206b7725983b780771a599/zim/gui/pageview/__init__.py#L4234-L4236

There are also drag-and-drop related tests in `tests/pageindex.py`: `testDragAndDropCallbacks` and `testDragAndDropCallbacksWithWorkaround`.

Hope this helps you. Happy Hacking!
