### ISSUE TITLE
Arithmetic: limit decimal points precision

### ISSUE THREAD

**Issue by jtoppine** [zim-desktop-wiki/zim-desktop-wiki#2476]
**Is your feature request related to a problem? Please describe.**

The otherwise excellent Arithmetic plugin results in messy looking and hard to read notes due to  needless precision in calculations.

For example:

```
4500/21.5/8*11*21.5=6,187.499999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999998
```

Desired result:
`4500/21.5/8*11*21.5=6,187.50`

Or perhaps even:
`4500/21.5/8*11*21.5=6,188`

**Describe the solution you'd like**

Perhaps a setting to limit precision / round calculation results to certain amount of decimals (2 is usually enough although YMMV).

**Describe alternatives you've considered**

Some kind of built in function, if implemented, could satisfy the same need to limit precision, although less elegantly. round(), ceil(), floor() or the like: 

`floor(4500/21.5/8*11*21.5)=6,187`

or perhaps with configurable precision

`round(4500/21.5/8*11*21.5, 2)=6,187.50`

**Comment by introt** [comment]
The precision is hardcoded here:

https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/c88cf3cb53896bf272e87704826b77e82eddb3ef/zim/inc/arithmetic.py#L137-L138

The documentation seems to suggest setting the desired precision after the calculation before printing the result, but given how `arithmetic.py` evaluates the "resultado", I decided to sidestep the issue by re-formatting the result string:

https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/64f2206e57505a5129206b7725983b780771a599/zim/inc/arithmetic.py#L491-L495

To avoid adding extra zeros after the decimal point, I'm simply comparing the length of the strings - I'm not sure whether this results in correct behavior when exponents are involved, but I'm taking the gander that anyone doing such math will double-check their results elsewhere anyway.
