### ISSUE TITLE
Windows User donesn't have "Dark theme" - pls prioritize

### ISSUE THREAD

**Issue by 4l3xx54nd3r** [zim-desktop-wiki/zim-desktop-wiki#2485]
Hello, 

I was on linux before and that's how your software got pitched.
The problem is most windows applications have two View modes - Dark mode and Light mode. 

If you could add a dark mode with ( eg: grey text background and white text ) it would be very 
nice when I switch to dark mode at night. (eg: you can choose yourself a good set of colors )

**Comment by 4l3xx54nd3r** [comment]
Thank you for consideration. 

I conclude that my plead will be satisfied.

**Comment by introt** [comment]
Please follow #1727 for updates
