### ISSUE TITLE
"find_next" keyboard shortcut doesn't work in its main use case

### ISSUE THREAD

**Issue by rzwisler** [zim-desktop-wiki/zim-desktop-wiki#2491]
**Describe the bug**
"find_next" keyboard shortcut doesn't work in its main use case

**To Reproduce**
1. In the main window, hit ctrl-f to open the "find" dialog on the bottom of the screen.
2. Type your search string
3. hit ctrl-g or whatever keyboard shortcut you have mapped to the "find_next" action.

The search will not progress to the next instance of your search string.

This used to work in older versions of Zim (0.73.5), and this DOES work on secondary windows opened via "File" > "Open in New Window".

You can work around this by using your mouse to move focus from the Find bar back to the main page, and then they keyboard shortcut for find_next does work.

**Environment (please complete the following information):**
Linux, via git at the current latest commit:

c88cf3cb (HEAD, tag: 0.75.2, origin/release, origin/develop) fixup release

**Comment by introt** [comment]
Thanks for the report! This is fixed by #2473

**Comment by sojusnik** [comment]
After updating to 0.76.0 on Ubuntu 24.04 the "find next" shortcut stopped working, although "find previous" still does. Applies to main window and extra windows.

Mapped those to:
![grafik](https://github.com/user-attachments/assets/a3cc073b-c55f-44dc-9dd1-d5005378816e)
