### ISSUE TITLE
cut and paste not working suddenly

### ISSUE THREAD

**Issue by michaelyhu-anl** [zim-desktop-wiki/zim-desktop-wiki#2531]
This is zim 0.75.1
Platform: posix
Locale: en_US UTF-8
FS encoding: utf-8
Python: (3, 10, 8, 'final', 0)
PyGObject: (3, 42, 2)

======= Traceback =======
  File "/Applications/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/gui/pageview/__init__.py", line 6610, in do_activate_link
    self._do_activate_link(link, hints)
  File "/Applications/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/gui/pageview/__init__.py", line 6619, in _do_activate_link
    href = HRef.new_from_wiki_link(link)
  File "/Applications/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/notebook/page.py", line 375, in new_from_wiki_link
    names = Path.makeValidPageName(href.lstrip('+')) if href else ""
  File "/Applications/Zim.app/Contents/Resources/lib/python3.10/site-packages/zim/notebook/page.py", line 155, in makeValidPageName
    raise ValueError('Not a valid page name: %s (was: %s)' % (newname, name))
ValueError: Not a valid page name:  (was: )

**Comment by dehesselle** [comment]
Is this reproducible on the latest version as well (0.75.2)? Also what are the exact steps to reproduce this?

**Comment by michaelyhu-anl** [comment]
Later I realized that 'cut-n-paste' did not work on the text that I just made linked to another page. however the link failed, the link location is missing in the syntax.
instead of 
[[link-location|title-text]]
the location portion is missing, so it looks like
[[|title-text]]
and the text is highlighted.

After I fix the link, cut-n-paste worked.

Help this helps.

Thanks.
-Michael

________________________________________

**Comment by dehesselle** [comment]
Sounds like there is no more issue, closing.

**Comment by michaelyhu-anl** [comment]
That's okay. Though the linking process did not work is kind of a bug too.
Well, we wait until it happens again.
Thanks,
-Michael
________________________________________

**Comment by dehesselle** [comment]
To keep the work manageable it's important to report only problem per issue, that's why I've closed this one. Feel free to report the problem with link creation in a new issue. But please keep in mind to test with the latest version first and give clear, precise steps on how to reproduce (click this, type here, etc.).
