### ISSUE TITLE
Links to local folders are not opened

### ISSUE THREAD

**Issue by EureDudeheit** [zim-desktop-wiki/zim-desktop-wiki#2533]
**Describe the bug**

Hello,

when i want to use a linked folder from a wiki page, nothing happens. Usually the folder should be opened in the default file manager (Dolphin in Kubuntu 22.04)

the log says:

```
DEBUG: Activate link: `/home/felix/.local/share/plasma/plasmoids/org.kde.plasma.ticki/`
DEBUG: open_file(/home/felix/.local/share/plasma/plasmoids/org.kde.plasma.ticki, None)
INFO: Spawning: ('xdg-open', '/home/felix/.local/share/plasma/plasmoids/org.kde.plasma.ticki') (cwd: /home/felix)
DEBUG: Process started with PID: 65681
grep: /proc/sys/fs/binfmt_misc/WSLInterop: No such file or directory
WSL Interopability is disabled. Please enable it before using WSL.
grep: /proc/sys/fs/binfmt_misc/WSLInterop: No such file or directory
[31m[1m[error] WSL Interoperability is disabled. Please enable it before using WSL.(B[m
/usr/bin/wslview: line 216: /mnt/c/Windows/System32/reg.exe: No such file or directory
/usr/bin/wslview: line 308: [: -ge: unary operator expected
[31m[error](B[m This protocol is not supported before version 1903.
```

**To Reproduce**
1. open a page in the wiki
2. Click on link

> /home/felix/.local/share/plasma/plasmoids/org.kde.plasma.ticki/

5. See error

**Expected behavior**
Dolphin should open the folder

**Screenshots**
not necessary

**Environment (please complete the following information):**
 - Version 0.74.3 from ubuntu sources
 - OS: ubuntu 22.04
 - Language: german
 - Plugins: disabling plugins has no effect

**Additional context**
N/A

Thank you in advance

**Comment by introt** [comment]
Can't reproduce on Ubuntu. According to your logs, you're using Windows Subsystem for Linux, is this correct? Something called "WSLInterop" seems to be missing, which seems to be where the issue stems from.

**Comment by EureDudeheit** [comment]
That's what surprises me -> i am using Ubuntu. I Installed the newest version (0.75.2) which shows the same behaviour.

**Comment by dehesselle** [comment]
Please answer the question if you're running Ubuntu through WSL or not.

**Comment by EureDudeheit** [comment]
Sorry, maybe this was misunderstanding:  i **don't** run Ubuntu through WSL

**Comment by dehesselle** [comment]
Thanks for clarifying. Did you Google your problem? I have found https://askubuntu.com/questions/1410764/ubuntu-22-04-fresh-install-desktop-entries-do-not-open
which leads me to believe this is a Ubuntu problem and not a Zim problem.

**Comment by EureDudeheit** [comment]
Thank you for suggesting.
I was wondering what WSL is needed for on a Linux system

so a

`sudo apt purge wslu`

as mentoned in the first answer to your linked post did the trick. 
Files are now opened with Kate, folder links with Dolphin as it should.
Thank you!

The second answer in your link led me to a related problem with GIMP
https://forum.ubuntuusers.de/topic/start-icons-in-der-kontrolleiste-funktionieren/ 

-> so it is a ubuntu-problem
Thank You!
