### ISSUE TITLE
High cpu usage after editing with extrnal editor

### ISSUE THREAD

**Issue by mid-kid** [zim-desktop-wiki/zim-desktop-wiki#2538]
**Describe the bug**
When using the Tools->Edit source function, my laptop's fans flare up, remaining this way even after I've closed the external editor.

**To Reproduce**
1. Open zim, click on Tools->Edit source
2. Close editor, press OK in the dialog
3. Open task manager
4. See zim using an entire core at 100%

**Expected behavior**
Normal CPU usage

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Version 0.75.2
 - OS: windows, installed using https://scoop.sh from the extras bucket
 - Language: N/A
 - Plugins: Nope

**Additional context**
No additional output is shown when running zim.exe -D on the command line.

**Comment by introt** [comment]
Sounds related to #1697 - the patch therein might solve this one as well

**Comment by jaap-karssenberg** [comment]
Assume double
