### ISSUE TITLE
Add option to web server dialog to select template

### ISSUE THREAD

**Issue by jhojen26** [zim-desktop-wiki/zim-desktop-wiki#255]
How to select a theme for the web server, just run me with the one that comes by default.

thank you very much

**Comment by Osndok** [comment]
This is for the built-in web server, as indicated in 254... there is no option to select a template, or the like.

![no-template-selection](https://user-images.githubusercontent.com/24486935/33765624-bf179a64-dbe7-11e7-958a-964e4d71740a.png)

**Comment by jaap-karssenberg** [comment]
Indeed the GUI does not have this option, should be added. When starting from commandline options you can specify the template.
