### ISSUE TITLE
中文乱码

### ISSUE THREAD

**Issue by Franklyn1987** [zim-desktop-wiki/zim-desktop-wiki#2578]
I just use the original code and msys2 run the zim. when it run successful ,I find the Jornal occur unreadable codes because it has Chinese code.
![PixPin_2024-02-25_23-41-29](https://github.com/zim-desktop-wiki/zim-desktop-wiki/assets/20518283/c5fa7e6f-2af9-44bc-bc0b-542331fb2a71)

**Comment by Toggoren** [comment]
With 99% probability it's a regression bug caused by [my contribution](https://github.com/zim-desktop-wiki/zim-desktop-wiki/commit/a9dfdcd3c15b845725605bc9eb4ee6e4b54dd8bc).
I'll deal with it
