### ISSUE TITLE
Selection is lost when formatting is applied

### ISSUE THREAD

**Issue by hansiglaser** [zim-desktop-wiki/zim-desktop-wiki#2581]
**Describe the bug**
To format some text, it is selected (e.g., with the mouse or with Shift-Arrowkeys) and then a formatting is selected (e.g., bold, strikethrough). Sometimes the selected text stays selected, and sometimes it is unselected.

If only a few words within a line are selected, then the selected text stays selected.

If the end of the selection is in a new line, then the text is unselected after applying the formatting.

**Expected behavior**
Selected text stays selected after applying a formatting.

**Environment (please complete the following information):**
 - Zim 0.75.2 on Windows, but this also happens on Linux and with earlier verions

**Comment by introt** [comment]
Can't reproduce on 2016dc92159581ddb009028d5d3bc2e8d30bc3ad, though if the end of the selection is a newline, it does move the end to the last text on the previous line which is to be expected given how the wiki syntax works.

**Comment by hansiglaser** [comment]
Sounds good!
Could you please also try with a short selection which ends with a space? Changing its formatting also deselects the whole text.

**Comment by introt** [comment]
Doesn't do that on my system, could you make a screen recording and upload it here?

**Comment by hansiglaser** [comment]
Unfortunately I don't have a screen recording tool. But could you please provide a daily build (for Debian AMD64 or Windows), so that I can try it?

**Comment by introt** [comment]
I'll do you one better: since you have Zim installed from your package manager, you have all the runtime requirements. And because Zim is written in Python, you can simply download the latest source and run `zim.py`:

```bash
git clone https://github.com/zim-desktop-wiki/zim-desktop-wiki
cd zim-desktop-wiki
chmod +x zim.py
./zim.py
```

**Comment by hansiglaser** [comment]
Oh, that was great, thanks!

I tried it and the selection is now kept. The selection is only changed in a way, so that the trailing spaces or newlines are not selected any more. But the actual text stays selected.

Thanks a lot! Looks like the bug was fixed already.
