### ISSUE TITLE
Links unreadable in dark mode

### ISSUE THREAD

**Issue by nixuser58** [zim-desktop-wiki/zim-desktop-wiki#2605]
**Describe the bug**
In Zim 0.75.2 under Fedora using Xfce in Adwaita-dark mode links in the wiki are unreadable due to the blue being way too dark.  The web site link on the "About Zim" page looks fine because it is using a lighter blue.

**To Reproduce**
Use a dark mode them such as Adwaita-dark and observe what links look like.  I believe this problem is common across a wide range of DEs and dark themes.

**Expected behavior**
If links were colored like the web site link on the "About Zim" dialog it would be ideal.

**Screenshots**
Attached.  Font size and monitor obviously impact on readability,
![Screenshot_2024-04-29_13-46-06](https://github.com/zim-desktop-wiki/zim-desktop-wiki/assets/61274410/01ce545b-0728-4158-b56b-64ab21861bcd)

**Environment (please complete the following information):**
Zim 0.75.2
Fedora 40 (in my case, but any recent version)
Xfce
Adwaita-dark theme selected in Xfce.

**Comment by jaap-karssenberg** [comment]
You can configure the link color via the "style.conf" config file, please see the manual for more information how to do this.
