### ISSUE TITLE
OSX Package download links are broken.

### ISSUE THREAD

**Issue by sclamons** [zim-desktop-wiki/zim-desktop-wiki#2616]
**Describe the bug**
The OSX application download links here do not work: https://gitlab.com/dehesselle/zim_macos/-/releases

**To Reproduce**
1. Go to https://gitlab.com/dehesselle/zim_macos/-/releases
2. Click the most recent "Packages" link.

**Screenshots**
Instead of a download, I get this: 
<img width="1236" alt="image" src="https://github.com/zim-desktop-wiki/zim-desktop-wiki/assets/1700307/6cb515aa-0a83-4ade-9d02-94002a32c0e9">

**Comment by dehesselle** [comment]
Something happened on GitLab's site which broke lots of my releases across all my projects. I'll have to create a new release.
In the meantime, you can access the downloads via the package registry: https://gitlab.com/dehesselle/zim_macos/-/packages/16217234

**Comment by dehesselle** [comment]
GitLab has confirmed it's a regression introduced by a recent change on their end. They're working on a fix.

**Comment by dehesselle** [comment]
Issue was fixed by GitLab.
https://gitlab.com/gitlab-org/gitlab/-/merge_requests/154248
