### ISSUE TITLE
Can't start Zim after long absence

### ISSUE THREAD

**Issue by chainria** [zim-desktop-wiki/zim-desktop-wiki#2624]
**Describe the bug**
I was not using Zim for a long time, but wanted to start using it again. However, The application does not start, and I get the following output in the console:

Traceback (most recent call last):
  File "/usr/bin/zim", line 137, in <module>
    main()
  File "/usr/bin/zim", line 114, in main
    import zim.main
  File "/usr/lib/python3.11/site-packages/zim/main/__init__.py", line 18, in <module>
    import zim.newfs
  File "/usr/lib/python3.11/site-packages/zim/newfs/__init__.py", line 19, in <module>
    from .base import *
  File "/usr/lib/python3.11/site-packages/zim/newfs/base.py", line 573, in <module>
    mytype = xdgmime.get_type('image.png', name_pri=80)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/xdg/Mime.py", line 616, in get_type
    update_cache()
  File "/usr/lib/python3.11/site-packages/xdg/Mime.py", line 575, in update_cache
    _cache_database()
  File "/usr/lib/python3.11/site-packages/xdg/Mime.py", line 557, in _cache_database
    globs.merge_file(path)
  File "/usr/lib/python3.11/site-packages/xdg/Mime.py", line 421, in merge_file
    weight, type_name, pattern = fields[:3]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 3, got 2)

This is under Gentoo, using the version 0.75.2.

Trying to start it as another user works. What can I do to make it start under my user account again?

**To Reproduce**
1. Start Zim with an ancient home folder
2. Crash

**Expected behavior**
The application should start.

**Screenshots**
Only the output above is shown

**Environment (please complete the following information):**
 - Version [e.g. 0.75.2-r1] -- specifically mention it if you use the development branch or snapshot PPA
 - OS: [e.g. linux/windows/mac os] Linux/Gentoo
 - Language: especially for errors that might relate to character encoding or other locale specific issues de_AT
 - Plugins: do you use any custom plugins that were not included with zim? Can the bug be reproduced when these custom plugins are disabled? Unknown.

**Additional context**
Nothing more to say.

**Comment by jaap-karssenberg** [comment]
This happens in the xdg.Mime library module, not in the zim code itself.
Apparently this module uses some kind of cache. Probably cleaning the cache
in your home folder would get it unstuck.

Quick code inspection of the module doesn't give a clear suspect. But since
it must be a user specific file, I would start with looking at
"~/.local/mime" and "~/.cache/mime" and remove (or backup) those files to
see if it helps.

Hope this helps, otherwise, please reach out to support for "xdg.Mime"

Could add patch in zim to make us robust for this error, but can't fix the
root cause in zim.

--- Jaap

**Comment by chainria** [comment]
Thank you for the very quick response. Yes, I was already fearing something like this. I couldn't find anything though and even strace didn't help at all.

That being said, you absolutely pointed me to the right direction. Basically I followed https://bbs.archlinux.org/viewtopic.php?pid=2131634#p2131634 and now Zim is back in all it's glory. Those mime files in the archived directory are just as old as my notebooks - they are from 2009. Just wondering how everything else could work on this system :)
