### ISSUE TITLE
Right align jump window matches

### ISSUE THREAD

**Issue by nbeaver** [zim-desktop-wiki/zim-desktop-wiki#264]
When using the jump window,
sometimes the match results are too long,
and the matched page name might not be visible.
For example, a search for "power-manager" might show

    projects:software:bugs-and-feature-requests:debian-sections:xfce:xfce4
    projects:software:bugs-and-feature-requests:debian-sections:xfce:xfce4

when the full paths are

    projects:software:bugs-and-feature-requests:debian-sections:xfce:xfce4-power-manager
    projects:software:bugs-and-feature-requests:debian-sections:xfce:xfce4-power-manager-plugins

Here are screen shots to illustrate:

![jump-window-too-small](https://user-images.githubusercontent.com/3036798/34191327-bc5d6ed4-e50b-11e7-9f07-a9ad5a5c3d0d.png)

![jump-window-expanded](https://user-images.githubusercontent.com/3036798/34191349-dcbb77e8-e50b-11e7-9e43-73f7dbf28a8e.png)

One option is just to make the jump window wider
so that the full path is visible.
However, this can be ungainly and is limited by screen size.

One alternative is to right-align the matched text in the jump window,
so a search for "power-manager" would display

    are:bugs-and-feature-requests:debian-sections:xfce:xfce4-power-manager
    -and-feature-requests:debian-sections:xfce:xfce4-power-manager-plugins

This way, the matching text is always visible. 

![jump-window-right-aligned](https://user-images.githubusercontent.com/3036798/34191353-e5e0f118-e50b-11e7-8960-f01883a44573.png)

Alternately, Zim could show the beginning and end
but truncate and ellipsize identical intermediate parts,
something like this:

    projects...xfce4-power-manager
    projects...xfce4-power-manager-plugins

**Comment by Osndok** [comment]
I think the ellipsis is a better option, but I don't know how much work that would be (if gtk has the right hooks), and it might have to wait until gtk3.

Personally, I think a secondary issue here is that the jump & insert utility windows appear too small to begin with... it seems that I am routinely resizing them, and they always manage to shrink again.

:)

**Comment by Self-Perfection** [comment]
Indeed some zim dialogs are too small. Luckily I use KDE, KWin allows to configure rules for specific windows, so I set it to expand horizontally windows with title "Jump to - Zim". I also use custom size rules for insert date and edit link dialogs.

**Comment by jaap-karssenberg** [comment]
The drop down is essentially a treeview, so it should allow for ellipsis to be turned on.

**Comment by jaap-karssenberg** [comment]
Afraid this is harder to fix than I thought - the treeview is a private implementation of the widget, so cannot just turn on the ellipsis.
