### ISSUE TITLE
Multi-window version

### ISSUE THREAD

**Issue by Nick222** [zim-desktop-wiki/zim-desktop-wiki#2649]
Could you make a multi-window version of your program (Unix-way) - to work simultaneously on several monitors ?

For example:
- Left panel
- Main editor
- Right panel

**Comment by jaap-karssenberg** [comment]
Not entirely sure what you mean here. Zim does allow to open pages in their
own window and as far as I'm aware you can drag those to other monitors as
well.

If you looking to detach the panels, from a user interface guideline I do
not see any precedents for that (except maybe Gimp), and it adds quite a
bit of complexity.

--- Jaap

**Comment by Nick222** [comment]
OK :)
