### ISSUE TITLE
Unable to translate Zim Wiki to PT-BR

### ISSUE THREAD

**Issue by eduardomozart** [zim-desktop-wiki/zim-desktop-wiki#2706]
**Describe the bug**
The message that there's pending commit requests are shown in Weblate, but I believe that the repo URL maybe changed and it was never fixed.

**To Reproduce**
1. Go to 'Portuguese-Brasil' transation on Weblate
2. Attempt to save translation

**Expected behavior**
The "save" button is available to save the translation.

**Screenshots**

<img width="811" alt="image" src="https://github.com/user-attachments/assets/1a96bd24-7ee8-436f-8eb1-68e1fb795c60" />

**Environment (please complete the following information):**
 - Version [e.g. 0.74.0] -- 0.74.2
 - OS: macOS
 - Language: pt_BR
 - Plugins: None

**Additional context**
None.

**Comment by jaap-karssenberg** [comment]
Please see https://hosted.weblate.org/projects/zim/develop/ the "master" branch is no longer in use

**Comment by eduardomozart** [comment]
Hello,
This issue was closed but the issue hasn't been fixed. There is nothing I can do to fix it and the issue still persists. Please fix it for PT-BR language.
Thank you.

**Comment by eduardomozart** [comment]
The issue still persists for some strings, so I believe this issue shouldn't be closed yet until it's fixed. I believe it won't affect the translation I'm doing there but I believe the master branch should be removed if it's not in use to remove this message.
<img width="723" alt="image" src="https://github.com/user-attachments/assets/f9770ce9-9a6f-4272-836a-c2ec61468fb7" />

**Comment by jaap-karssenberg** [comment]
I don't think this message is actually an issue. The master branch is no
longer used and we pull directly from the develop branch when syncing.

Op di 24 dec. 2024 02:30 schreef Eduardo Mozart de Oliveira <
***@***.***>:
