### ISSUE TITLE
can't create journal with Weekly

### ISSUE THREAD

**Issue by romantist** [zim-desktop-wiki/zim-desktop-wiki#286]
Hi.
it can not work when I want to write a journal.
I choose "Week" on 'Use a page for each' option in journal plugin configure.
and I want create journal by Alt+D, it occurs error.
this is log message via on debug mode bellows;

INFO: This is zim 0.67
DEBUG: Python version is sys.version_info(major=2, minor=7, micro=13, releaselevel='final', serial=0)
DEBUG: Platform is nt
DEBUG: No bzr version-info found
DEBUG: Running from a source dir: C:\Program Files (x86)\Zim Desktop Wiki
DEBUG: Set XDG_DATA_HOME to C:\Users\sec\AppData\Roaming\zim\data
DEBUG: Set XDG_DATA_DIRS to [<Dir: C:\Users\sec\.local\share>]
DEBUG: Set XDG_CONFIG_HOME to C:\Users\sec\AppData\Roaming\zim\config
DEBUG: Set XDG_CONFIG_DIRS to [<Dir: C:\Users\sec\.config>]
DEBUG: Set XDG_CACHE_HOME to C:\Users\sec\AppData\Roaming\zim\cache
DEBUG: Registered object line
DEBUG: Starting standalone process
DEBUG: Loading config from: <zim.notebook.info.VirtualFile object at 0x03F5F670>
DEBUG: Loading config from: D:\Romantist\notebook.zim
DEBUG: Wrote C:\Users\sec\AppData\Roaming\zim\config\zim\notebooks.list
DEBUG: Loading config from: D:\Romantist\notebook.zim
DEBUG: Wrote D:\Romantist\.zim.tmp
INFO: Remove file: D:\Romantist\.zim.tmp
DEBUG: Opening notebook: <zim.notebook.notebook.Notebook object at 0x0498AC90>
DEBUG: Loading config from: <ConfigFile: C:\Users\sec\AppData\Roaming\zim\config\zim\preferences.conf>
DEBUG: Loading plugin: attachmentbrowser
DEBUG: Loading plugin: backlinkpane
DEBUG: Loading plugin: calendar
DEBUG: Loading plugin: diagrameditor
DEBUG: Loading plugin: distractionfree
DEBUG: Loading plugin: linesorter
DEBUG: Loading plugin: linkmap
DEBUG: Loading plugin: quicknote
DEBUG: Loading plugin: sourceview
DEBUG: Registered object code
DEBUG: Loading plugin: tableeditor
DEBUG: Registered object table
DEBUG: Loading plugin: tableofcontents
DEBUG: Loading plugin: tags
DEBUG: Loading plugin: tasklist
DEBUG: Gtk version is (2, 24, 10)
DEBUG: Pygtk version is (2, 24, 0)
DEBUG: Loading config from: <ConfigFile: C:\Users\sec\AppData\Roaming\zim\config\zim\style.conf>
DEBUG: Autosave interval: 15 - use threads: True
DEBUG: Loading config from: C:\Users\sec\AppData\Roaming\zim\cache\zim\notebook-D_Romantist\state.conf
DEBUG: Registered plugin <zim.plugins.base.imagegenerator.DiagramMainWindowExtension object at 0x04B5C450> for image type "diagram"
WARNING: C:\Program Files (x86)\Zim Desktop Wiki\zim.exe\zim\plugins\__init__.py:766: GtkWarning: Inserting action group 'MainWindowExtension' into UI manager which already has a group with this name

DEBUG: Wrote C:\Users\sec\AppData\Roaming\zim\config\zim\preferences.conf
WARNING: C:\Program Files (x86)\Zim Desktop Wiki\zim.exe\zim\gui\__init__.py:2308: GtkWarning: open_page_back_alt1: missing action open_page_back_alt1

WARNING: C:\Program Files (x86)\Zim Desktop Wiki\zim.exe\zim\gui\__init__.py:2308: GtkWarning: open_page_forward_alt1: missing action open_page_forward_alt1

DEBUG: Accelmap: C:\Users\sec\AppData\Roaming\zim\config\zim\accelmap
WARNING: C:\Program Files (x86)\Zim Desktop Wiki\zim.exe\zim\gui\widgets.py:2900: PangoWarning: couldn't load font "맑은 고딕 Not-Rotated 9", falling back to "Sans Not-Rotated 9", expect ugly output.

WARNING: C:\Program Files (x86)\Zim Desktop Wiki\zim.exe\zim\gui\widgets.py:2900: PangoWarning: couldn't load font "맑은 고딕 9", falling back to "Sans 9", expect ugly output.

WARNING: C:\Program Files (x86)\Zim Desktop Wiki\zim.exe\zim\gui\widgets.py:2900: PangoWarning: failed to choose a font, expect ugly output. engine-type='PangoRenderWin32', script='common'

INFO: Open page: Home:WORK:MaaP:grafana (Home:WORK:MaaP:grafana)
DEBUG: Add window: MainWindow
WARNING: C:\Program Files (x86)\Zim Desktop Wiki\zim.exe\zim\main\__init__.py:702: GtkWarning: gdkdrawable-win32.c:2013 drawable is not a pixmap or window

DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck found out-of-date
DEBUG: Index folder: D:\Romantist
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck found out-of-date
DEBUG: Index folder: D:\Romantist\Home\WORK\MaaP
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck finished
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck finished
DEBUG: Action: go_page_today
DEBUG: Exception during action: go_page_today
Traceback (most recent call last):
  File "zim\actions.pyo", line 157, in do_activate
  File "zim\actions.pyo", line 140, in func
  File "zim\plugins\calendar.pyo", line 246, in go_page_today
  File "zim\plugins\calendar.pyo", line 131, in path_from_date
  File "zim\datetimetz.pyo", line 167, in weekcalendar
  File "zim\datetimetz.pyo", line 87, in init_first_day_of_week
  File "babel\core.pyo", line 166, in __init__
  File "babel\localedata.pyo", line 50, in exists
  File "babel\localedata.pyo", line 35, in normalize_locale
  File "babel\localedata.pyo", line 62, in locale_identifiers
WindowsError: [Error 3] : 'C:\\Program Files (x86)\\Zim Desktop Wiki\\zim.exe\\babel\\locale-data/*.*'
ERROR: : C:\Program Files (x86)\Zim Desktop Wiki\zim.exe\babel\locale-data/*.*
DEBUG: Running ErrorDialog
DEBUG: Action: close (delete-event)
DEBUG: Wrote C:\Users\sec\AppData\Roaming\zim\cache\zim\notebook-D_Romantist\state.conf
WARNING: C:\Program Files (x86)\Zim Desktop Wiki\zim.exe\zim\gui\__init__.py:1908: Warning: g_object_set_qdata: assertion `G_IS_OBJECT (object)' failed

WARNING: C:\Program Files (x86)\Zim Desktop Wiki\zim.exe\zim\plugins\__init__.py:783: GtkWarning: gtk_ui_manager_remove_action_group: assertion `g_list_find (self->private_data->action_groups, action_group) != NULL' failed

DEBUG: Removed plugin <zim.plugins.base.imagegenerator.DiagramMainWindowExtension object at 0x04B5C450> for image type "diagram"
DEBUG: Remove window: MainWindow
DEBUG: Last toplevel destroyed, quit

**Comment by jaap-karssenberg** [comment]
The error happens in the "babel" library. Afraid not much I an do about that. Might be good to check again when we package a new version.

**Comment by jaap-karssenberg** [comment]
Please test again with zim 0.70 or newer

**Comment by romantist** [comment]
same issue appeared on 0.6.91 (windows 7 64).
but 0.6.8 is working well.
just FYI.
I hope I'll meet 0.7.0 windows version soon :)
thanks.

**Comment by jaap-karssenberg** [comment]
Only thing we can do is wrap library call with `try .. except .`. and make it less fatal
