### ISSUE TITLE
Feature request: Centered images in the editor

### ISSUE THREAD

**Issue by jfromero** [zim-desktop-wiki/zim-desktop-wiki#315]
Hi!

Is it possible to center all images in the editor? Currently all of them are in the left of the page.

Thank you so much!

**Comment by itmuckel** [comment]
As a hack, you could just use tabs and normal whitespace before the picture in order to center it.

**Comment by jaap-karssenberg** [comment]
Zim has no alignment properties for text regions, which includes images. So for me this is a "won't fix"
