### ISSUE TITLE
source view codeblock freezes page

### ISSUE THREAD

**Issue by markfink** [zim-desktop-wiki/zim-desktop-wiki#316]
I am a new user, just experimenting with the features a bit (can't find the logfile otherwise I would provide more info or help out with some analysis). 

1. on a page I do "Insert > Code Block"
2. I select "Python" 
3. I add a function like "def a():\n    pass"
4. now it does the syntax just fine
5. go to another page and come back (I assume this is when Zim saves a page)
6. now the page is frozen - no highlighting, not possible to switch to edit mode any more

If I can do something to investigate this issue let me know

my system:
* I am using up to date Arch Linux
* Zim 0.67 (installed via pacman)
* I assume Zim uses my system python which would be 3.6.4

update (11.02.2018):
* I ran Zim in -D mode and could not find anything that indicated a problem let alone any info regarding codeblock :(
* only thing I found is this: "DEBUG: Got error in dispatch: No such file or directory"
* looks like I am out of luck trying to install from source: "ImportError: No module named gobject"

**Comment by markfink** [comment]
wow, the old "edit source"  & linenumbers="False" trick worked for me!

**Comment by Self-Perfection** [comment]
This is definitely a duplicate of #296 

Also, Zim is not ported yet to python3 (but the work is in progress). Easy check:
```
$ ps -o cmd -C zim
CMD
/usr/bin/python2 /usr/bin/zim
```

**Comment by waldauf** [comment]
Hello,

I have the same problem with freezing Zim. Where should I put this line `edit source" & linenumbers="False`?

**Comment by Self-Perfection** [comment]
@walduf just right click on sourceview object and deselect "Show Line Numbers" option. Or manually disable display of linenumbers in note file. E.g. edit it with menu->tools->edit source.

**Comment by waldauf** [comment]
@Self-Perfection Many thanks! :]

**Comment by jaap-karssenberg** [comment]
Closing as this is a duplicate of #296. Hope this to be gone in Gtk3 port - fingers crossed.
