### ISSUE TITLE
"Find" search box next occurrence shortcut

### ISSUE THREAD

**Issue by seihtam** [zim-desktop-wiki/zim-desktop-wiki#317]
This issue is about the "Find" search box found in "Search->Find...".

Currently \<Alt\>N can be used to go to the next occurrence of the search. In most other applications \<Enter\> can be used to go to the next result (examples: Chrome, Firefox, Sublime Text, Word and many more). Currently Zim will highlight the next result when pressing enter and the find search box will loose focus. This is annoying for me since I'm used to keep pressing enter when searching through text. Since \<Enter\> will go to next occurrence in many other widely used applications I assume that I'm not the only one who often makes this mistake when using Zim.

So i suppose the following: Keep the current shortcuts and make \<Enter\> go to the next occurrence like \<Alt\>N.

**Comment by Osndok** [comment]
Yeah, that's a nuisance for me too...
* https://bugs.launchpad.net/zim/+bug/1685371

**Comment by sojusnik** [comment]
Or just repair the focus [issue](https://github.com/jaap-karssenberg/zim-desktop-wiki/issues/128) and Ctrl+G will work fine. Also mentioned [here](https://bugs.launchpad.net/zim/+bug/1036821) and [here](https://bugs.launchpad.net/zim/+bug/1589085).

**Comment by Osndok** [comment]
I forgot to reference this issue, but this is how I addressed it (not in mainline zim):
* https://github.com/Osndok/zim-desktop-wiki/commit/4f7233ace8666bd29c118289bd6c0c2258453339
