### ISSUE TITLE
Keybindings for XF86Back and XF86Forward doesn't work on Windows

### ISSUE THREAD

**Issue by seihtam** [zim-desktop-wiki/zim-desktop-wiki#319]
I can see in the changelog that keybindings for XF86Back and XF86Forward was added in 0.61 but it doesn't work the two different Windows 10 machines i tried.

**Comment by jaap-karssenberg** [comment]
Afraid I don't have a hardware setup that allows me to test and fix this issue myself. Anyone wanting to pick it up?

**Comment by jaap-karssenberg** [comment]
In the develop branch there is a new tab in the preferences to change keybindings (commit  92d433ecf059d262e289020b2a0631f469e6fd52). Can you test whether that helps to resolve the issue?

P.S. if you use the "snapshot" PPA you now automatically get develop branch commits for testing.

**Comment by seihtam** [comment]
The default of "open_page_back_alt1" is "Backward" and "open_page_forward_alt1" is "Forward".

They still don't work and when double clicking the keybinding to try and change it to the forward and backward button on my mouse nothing happens and it keeps saying "New accelerator...".

**Comment by jaap-karssenberg** [comment]
In that case I'm afraid it is an issue in handling those keys in the Gtk
layer, as the widget to change keybindings is not zim specific.

Regards,

Jaap
