### ISSUE TITLE
Feature Request: Keybinding for inserting Equations

### ISSUE THREAD

**Issue by AndrewPfeil** [zim-desktop-wiki/zim-desktop-wiki#322]
Would it be possible to add a keybinding to auto-open the insert equation dialog box? I'm using a lot of equations in my notes and it would streamline the process quite a bit.

Thank you

**Comment by Osndok** [comment]
FYI, there is a standard way to change the shortcuts using the gtk rc file. Check out the 'key bindings' page in the zim manual (and probably elsewhere for other common gtk apps).

**Comment by AndrewPfeil** [comment]
I have attempted to pursue this, but I am fairly new to Ubuntu and cannot
find the gtk rc file even after installing gtk2.0 and trying to follow
methods described in the zim manual and other sources. I was hoping it
could be added as a feature to zim because it appears to be a relatively
complex process for someone who doesn't have much experience making changes
like that.

If it truly isn't something that will be added to zim, could you help to
guide me through the standard way to change shortcuts using the gtk rc
file? Or possibly a link to one.

Thank you,
Andrew Pfeil

**Comment by Osndok** [comment]
@ipsod suggests trying hovering your mouse cursor over the item you want to change the key binding for and hitting the key-combo you like for it.
