### ISSUE TITLE
Zim for Windows does not display svg images

### ISSUE THREAD

**Issue by ecodiv** [zim-desktop-wiki/zim-desktop-wiki#323]
I am using the Zim build for Windows by Brendan (https://zim.glump.net/windows/) version 0.68 RC1 (but the same applies for the previous version).

Zim for Windows does not display svg images. This has been reported before, and seems to be a gtk issue (see htps://bugs.launchpad.net/zim/+bug/1424829). Gtk supports svg display, so the problem lies in the way gtk is compiled I assume.

**Comment by ecodiv** [comment]
Just installed version 0.68, problem remains. Any idea how this can be solved @bkidwell ?

**Comment by bkidwell** [comment]
@ecodiv I just saw your message in IRC and I read the GitHub notice about your comment here 15 days ago. I'm so sorry for just sitting on it without responding at all.

I don't know why SVG is failing to be built into the build package, and I don't know when I'll have time to look at fixing the build. You can try doing your own partial build by following the instructions [here](https://github.com/jaap-karssenberg/zim-desktop-wiki/blob/0.68/windows/README-BUILD-win32.txt) in the ./windows source folder, up until you're testing the unpackaged build and it works. I have a feeling SVG will be available to you in that state.
