### ISSUE TITLE
[TableEditor]  Move cursor to next cell when tab is pressed

### ISSUE THREAD

**Issue by DanielPower** [zim-desktop-wiki/zim-desktop-wiki#325]
Please make it possible to quickly switch to the next cell of a table by pressing tab.
The current implementation requires switching to the mouse after every cell, which is very counter-productive.

**Comment by Self-Perfection** [comment]
Indeed cell switching with tab would be nice, but current implementation does not require switching to a mouse. You can switch to another cell after cell editing by pressing enter (to finish cell content editing) and moving active cell cursor with arrow keys.

**Comment by jaap-karssenberg** [comment]
Afraid I have to make this a "won't fix" as the widget now used for tables is not suited to add normal text editing key bindings on top. Only way forward is to replace the whole widget.
