### ISSUE TITLE
auto complete for tags - Zim Wiki

### ISSUE THREAD

**Issue by threed777** [zim-desktop-wiki/zim-desktop-wiki#355]
I am using version .68, and have the tags and tasklist plugin activated. I cannot get the auto complete for tags to work. I've tried "alt+q" but nothing happens. Thank you very much for your help.

Best regards, Tim

**Comment by muguu** [comment]
Please use this version:
https://gist.github.com/muguu/6502aa7064dc0795a684adaac3d65212#file-autocompletion-py

Regards,
Murat

**Comment by threed777** [comment]
Thank you very much. That worked. The ability to select

multiple tags by holding down the control key does not work.

As soon as I select one tag, the tag is placed in my note and

the select tag box closes. Thanks again for your help.



Regards,

Tim



Sent using Zoho Mail






---- On Mon, 26 Feb 2018 07:04:31 -0800 muratg &lt;notifications@github.com&gt; wrote ----




Please use this version:

 https://gist.github.com/muguu/6502aa7064dc0795a684adaac3d65212#file-autocompletion-py


Regards,

 Murat

**Comment by muguu** [comment]
> The ability to select multiple tags by holding down the control key does not work.

Interesting idea.  How would you expect the tags to be added into the note, if you could select multiple tags?

**Comment by threed777** [comment]
The information below is from zim wiki on GitHub:







Information on zim 0.66

Please note that the task list plugin within zim 0.66 does not have the additional features implemented which are described here!

I'm working on updating the plugins to work with zim 0.66 or greater.

I added an extra tag entry field with auto completion into the tasklist plugin which makes it easier to select tags.

In addition you can now select several tags by using the STRG key. Keep STRG pressed and multi select with the mouse.


According to GitHub, you can select "several tags" by using the STRG key which is the control key.

I normally enter tags like this:



@tag1

@tag2

@tag3



Most every note I enter will have multiple tags. It would be more convenient

to be able to select multiple tags. Thanks for your response and help.





Tim





Sent using Zoho Mail






---- On Tue, 27 Feb 2018 06:51:49 -0800 muratg &lt;notifications@github.com&gt; wrote ----




The ability to select multiple tags by holding down the control key does not work.

Interesting idea. How would you expect the tags to be added into the note, if you could select multiple tags?

**Comment by muguu** [comment]
I see, this is referring to the task list plugin, where the tags are shown within a tree on the left. Here I tweaked a previous version to allow multiple selection of tags and show all tasks with selected tags.

>It would be more convenient to be able to select multiple tags. Thanks for your response and help.

I will have a look

**Comment by LeoUfimtsev** [comment]
bump!
I updated my zim and updated the old autocomplete .72 to this newer one and it works well. (verified on Linux, Fedora with Gtk3.22)

The multi-tag-select is not a bad idea, but inserting tags one by one works well for me either.

It would be really great to  have this available nativley.

**Comment by jaap-karssenberg** [comment]
Closing here as the "autocomplete" plugin is not part of the core zim code. Please move to it's own repository with issue tracking.

Kind regards,

Jaap

**Comment by shivams** [comment]
The referenced version of plugin doesn't work with Zim v0.70+. I've ported it to the latest Zim release. All further discussions on can now go to: https://github.com/shivams/zim-tag-autocompletion
