### ISSUE TITLE
Could not save page

### ISSUE THREAD

**Issue by puneet858p** [zim-desktop-wiki/zim-desktop-wiki#360]
This is zim 0.68-rc1
Platform: nt
Locale: en_US cp1252
FS encoding: mbcs
Python: (2, 7, 14, 'final', 0)
Gtk: (2, 24, 10)
Pygtk: (2, 24, 0)
No bzr version-info found

======= Traceback =======
  File "zim\gui\pageview.pyo", line 5603, in do_link_clicked
  File "zim\actions.pyo", line 140, in func
  File "zim\gui\__init__.pyo", line 730, in open_page
AssertionError: Could not close page

**Comment by puneet858p** [comment]
It shows it could not save nontype letters. I was trying to use hindi language

**Comment by jaap-karssenberg** [comment]
Hmm, that is weird, in general everything is unicode proof. Do you have a piece of text that I can copy-paste to reproduce the issue? (Afraid I can't type hindi characters in my configuration)

**Comment by puneet858p** [comment]
मुझे इससे बहुत समस्या हो रही है।

**Comment by jaap-karssenberg** [comment]
When I copy-paste that text in a page and try to save it no error occurs. Does the issue occur every time ?

**Comment by puneet858p** [comment]
I have recorded my screen have a look at it. Also even after changing the
font the part where i link the words in that small window fonts are not
shown.

In addition i want to ask how can i add more fonts in zim.

**Comment by jaap-karssenberg** [comment]
Still cannot reproduce this issue. Please check with the to-be-release zim 0.70 version and open an new issue if similar problems are seen.
