### ISSUE TITLE
plugins with same/different dependencies?

### ISSUE THREAD

**Issue by Marcus-Sonntag** [zim-desktop-wiki/zim-desktop-wiki#365]
Hi,
I'm new to zim.
I wanted to install some plugins, but they react strange/different:
the plugin "Diagram" depends on GraphViz and works fine
the plug in "Link Map" depends on GraphViz aswell, but it can't be installed
can you tell me, what's the difference?

If you wish, I can add screenshots

Thanks a lot,
Marcus

**Comment by jaap-karssenberg** [comment]
The difference is that although both use the GraphViz tools, the diagram editor uses the "dot" command while the linkmap uses the "fdp" command.

In your case apparently only executable for "dot" is found but not "fdp".

**Comment by Marcus-Sonntag** [comment]
in GraphViz subfolder bin both files can be found: dot.exe and fdp.exe

**Comment by jaap-karssenberg** [comment]
Double checked the code, lookup is exactly the same except for the command
name.

- Do both commands have same permissions / executable flag set?
- Are you positive the folder you are looking at is the one used by zim?

Regards,

Jaap

**Comment by Marcus-Sonntag** [comment]
seems so:
![zim-folder](https://user-images.githubusercontent.com/36955746/36901330-13cb0bf0-1e27-11e8-8c2c-151e32981530.png)

**Comment by jaap-karssenberg** [comment]
That is weird, can you check for error messages?

If you run from source, running "--debug" should do. If you are running from the installer, try "--debug" and check for a "zim.exe.log" file in your temporary files.

Regards,

Jaap

**Comment by Marcus-Sonntag** [comment]
[zim.exe.log](https://github.com/jaap-karssenberg/zim-desktop-wiki/files/1781114/zim.exe.log)

**Comment by jaap-karssenberg** [comment]
Afraid this log file only shows zim starting. Suggests you still had a process running. To get a proper log file with debug info need start fresh without any zim instances running.

**Comment by jaap-karssenberg** [comment]
Closing for now. Please re-open if you have the error log that shows messages when loading the plugin list in the preferences dialog.
