### ISSUE TITLE
Tasklist: option to hide or sort not-yet-due tasks

### ISSUE THREAD

**Issue by bitinerant** [zim-desktop-wiki/zim-desktop-wiki#368]
The tasklist would be much more useful to me if I could do any of these 3 things:
* hide tasks which have a due date in the future
* when sorting tasks by due date, tasks with no due date show up __between__ tasks due today and tasks due tomorrow
* allow setting due dates such as "<now" or "<soon" which act as "today" and "in 2 weeks", respectively

Use case:  I don't need to see the task to renew my passport in 18 months.  My due and overdue tasks should be at the top of the list, and then other tasks that don't have a due date.

**Comment by jaap-karssenberg** [comment]
The tasklist supports a "start date" at which time a task becomes active - and the view allows to hide tasks that are not yet active. 

I believe this serves the same use case.

**Comment by bitinerant** [comment]
I don't believe this is the same. For example, how do I see a list of tasks which are not yet started, but need to be started this week?
