### ISSUE TITLE
Feature Request: Task List Plugin - Marking tasks done from the task list window

### ISSUE THREAD

**Issue by tecepe** [zim-desktop-wiki/zim-desktop-wiki#370]
Hi,

I was trying to complete tasks directly from the task list window but I couldn't find my way for that. I've found this thread from 2015 and it seems to accomplish that. 

https://lists.launchpad.net/zim-wiki/msg04178.html

Is that true for the current version of zim task list? BTW, I'm using Jaap's Ubuntu PPA, which gives me "Zim 0.68-rc1" in the "about" menu.

Thank you very much for your hard work. =)

**Comment by muguu** [comment]
Hi,

I added this function (ticking tasks within the task list) into an older version of the task list plugin. After a major update of the plugin from Jaap I haven't re-added this function any more.

You may want to add this as a feature request.

**Comment by tecepe** [comment]
Hi @muguu , thanks for your answer. I believe this is a very nice addition. It makes much easier to work with the Task List in my opinion. 

How should I proceed to add this as a feature request?

**Comment by muguu** [comment]
I suggest to rename the title to "Feature Request: Task List Plugin - Marking tasks done from the task list window" and describe your use case in detail.

Either Jaap will pick it up and considers it as a new function or I find the time to digg into the new task list plugin version.

**Comment by tecepe** [comment]
Thanks, @muguu . I'll write the description here, please let me know if there is a better place for that (maybe changing the first comment?).

The idea is to be able to complete a task from the "Task List" summary window, instead of going back and forth from that window to the content of the notebook itself where the task is. An extra column on the left of the current columns in the "Task List" window with a check-box where we could cycle through zim check-box states per task would do. 

Talking more specifically about my environment, I use i3wm and my zim notebook is always closed to the tray, except when I'm reviewing my projects. I'm able to tie the Task List window to a "scratchpad" (floating window that can be hidden in i3wm) and send it to the background or bring it back with just one key. It will improve very much my workflow if I don't need to open the notebook to mark the related task as done.

**Comment by muguu** [comment]
Perhaps you want to have a look at this implementation and see if this is what you are looking for:

https://gist.github.com/muguu/1d5910ef05259595fe49cde4c9db9d39

Please note that this is for Zim Wiki >=V0.61 and < V0.66

**Comment by tecepe** [comment]
Hi, @muguu . I'm willing to take a look at that. Just one question before: is there any risk to break my current zim notebooks since they are more recent than this version you pointed out?

I'm assuming that I just need to download the code and run it as a standalone python script. Is there anything else that I need to do?

**Comment by muguu** [comment]
Hi,

>Just one question before: is there any risk to break my current zim notebooks since they are more recent than this version you pointed out?

no, the notebook will be untouched. You will see an index update, which is normal. If you return to a newer version of zim, another index update will be done.

You may want to create a backup of your notebook and index if you want to feel better.

> I'm assuming that I just need to download the code and run it as a standalone python script. Is there anything else that I need to do?

Get a copy of an older version of ZIM and run zim.py
http://zim-wiki.org/downloads/



The plugin needs to be copied into the plugin folder.

**Comment by tecepe** [comment]
Hi, @muguu . Thank you very much for pointing that out. That version of the task list is very close of what I was talking about.

**Comment by jaap-karssenberg** [comment]
For now I'm marking this as "Won't fix" - open to new discussion, but please start on the discussion forum and open a ticket if there is someone working on it.
