### ISSUE TITLE
Show links to subpages with only the subpage's name displayed

### ISSUE THREAD

**Issue by utybo** [zim-desktop-wiki/zim-desktop-wiki#373]
Hello

By default, Zim shows a link to a subpage like this : 

```
[[Foo:Bar]] --> Foo:Bar
```

Is it possible through an option or a switch somewhere to instead have them like this ?

```
[[Foo:Bar]] --> Bar
```

This is especially useful in my workflow : create a page at the root, edit it there, link to it from other pages in the wiki, and then later on move it to its appropriate page. The problem is it ruins all the links previously made as it adds all of the parent page(s) in the links... 

I know that you can just edit all the links to [[Foo:Bar|Bar]], but this is extremely inconvenient when having to edit dozens of links just so that they're displayed properly, especially when they are a subpage of a subpage of a subpage.

**Comment by utybo** [comment]
Understandable. I am not actively using Zim anymore -- if this feature is not requested by anyone other than me, feel free to close it, no hard feelings! :)

**Comment by introt** [comment]
This is actually fixed in recent versions by the addition of the "Prefer short link names for pages" option in the link dialog
