### ISSUE TITLE
zim crach with spell checker plugin

### ISSUE THREAD

**Issue by trent30** [zim-desktop-wiki/zim-desktop-wiki#376]
Hi,

If "é <mail@d>" in the file it's OK but if "éé <mail@d>" is present, F7 (spell check) crash zim :/

I'm with zim 0.65 on xubuntu 16.04

**Comment by genodeftest** [comment]
This issue is not present with zim 0.67. Please update your installation of Zim or report this issue downstream (i.e. to your distribution) so they know they should update their version of Zim.

**Comment by trent30** [comment]
Yes, it works perfectly with last version. Thank you !

**Comment by miselico** [comment]
I am having a similar issue in 0.68. The only output in the console is: Trace/breakpoint trap (core dumped)
I narrowed it down to a text similar to:

```
* EX5555D11111
* http://www.google.com 
```
In the page. The crash only happens when the spelling checker is turned on or pages are switched.
I am using gtkspellcheck.

**Comment by jaap-karssenberg** [comment]
Afraid that is an error in the spell check library itself, not fixable from zim
