### ISSUE TITLE
Hotkeys don't work when started in non-Latin keyboard layout (Windows 10)

### ISSUE THREAD

**Issue by tehkonst** [zim-desktop-wiki/zim-desktop-wiki#381]
Hello.
When I start Zim on Windows with Russian keyboard layout, hotkeys don't work completely. Even Ctrl+C Ctrl+V doesn't work. So then I need to close Zim, switch the language and run it again. It's a little annoying.

**Comment by jaap-karssenberg** [comment]
Afraid this is a Gtk generic issue which I can't fix from zim. Upcoming release 0.70 is switching to the latest Gtk3 version, if problems persist with that version please re-open this ticket.
