### ISSUE TITLE
Shell Hangs if Network Path is Unavailable

### ISSUE THREAD

**Issue by Redoubts** [zim-desktop-wiki/zim-desktop-wiki#397]
If I try to do `cd /my/network/path` and then press up to do a prefix search of my history, the search can stall when the network is down or slow. I don't think there should be a path search here, so this seems like a bug.

zimrc:
```
zmodules=(directory environment history input \
          syntax-highlighting history-substring-search completion)
setopt CORRECT
ztermtitle='%n@%m:%~'
zhighlighters=(main brackets cursor)
```

**Comment by Self-Perfection** [comment]
I do not see how this issue might be related to this project. It seems to me you confused this repo with https://github.com/zimfw/zimfw
