### ISSUE TITLE
Apostrophe breaks clickable url

### ISSUE THREAD

**Issue by seihtam** [zim-desktop-wiki/zim-desktop-wiki#400]
You can reproduce the issue by opening the following URL and copy-paste it into Zim: https://da.sharelatex.com/templates/books/springer's-monograph-type-svm

Zim now only highlights the first part of the URL until the apostrophe.

**Comment by jaap-karssenberg** [comment]
Proper behavior would be to check whether the apostrophe is inside the link or at the end. Similar logic as described in https://github.github.com/gfm/#autolinks-extension- for puntuation

**Comment by jaap-karssenberg** [comment]
Part of solution of issue #219
