### ISSUE TITLE
Customizable wrap mode in Code Block

### ISSUE THREAD

**Issue by aaferrari** [zim-desktop-wiki/zim-desktop-wiki#401]
It would be very useful if in the Source View plugin options you could configure the lines wrap mode so you don't have to use the horizontal scroll bar when a code has very long lines. I found out that it can be done by adding the function `set_wrap_mode()` to sourceview.py in this way:
```
@@ -294,6 +294,7 @@
 		self.view.set_right_margin_position(80)
 		self.view.set_show_right_margin(True)
 		self.view.set_tab_width(4)
+		self.view.set_wrap_mode(Gtk.WrapMode.WORD_CHAR)
 
 		# simple toolbar
 		#~ bar = gtk.HBox() # FIXME: use gtk.Toolbar stuff
```
Instead of `Gtk.WrapMode.WORD_CHAR` you can also choose between `Gtk.WrapMode.NONE` (wrap lines never), `Gtk.WrapMode.CHAR` (at character boundaries) and `Gtk.WrapMode.WORD` (at word boundaries).

**Comment by jaap-karssenberg** [comment]
Patch merged
