### ISSUE TITLE
Export to LaTeX fails because of TIFF image

### ISSUE THREAD

**Issue by banan314** [zim-desktop-wiki/zim-desktop-wiki#409]
If you have images with extension TIFF (I guess it concerns mainly Mac OS users), Zim fails to export a notebook to LaTeX.
The code is generated as follows:
```
\includegraphics[]{./Tips/pasted_image.tiff}
```
and it causes the following error:
```
Unknown graphics extension: .tiff. \includegraphics[]{./Tips/pasted_image.tiff}
```
I looked it up and it turns out that the TIFF images have to be converted to another format before the LaTeX document can be compiled.

**Comment by jaap-karssenberg** [comment]
Don't think we should attempt doing the conversion in zim. Easy step would be to replace this image with a link on export.

**Comment by jaap-karssenberg** [comment]
Dev notes:
 * Latex only supports limited image formats by default
 * Whitelist pdf, png, jpg & eps -- all else should become a link
