### ISSUE TITLE
Data Disappers\is hidden with Dropbox Sync iPhone When spaces are in  filename

### ISSUE THREAD

**Issue by brianbraatz** [zim-desktop-wiki/zim-desktop-wiki#411]
**Duplication steps**
- Use dropbox app on iphone (probably dropbox app on android )
- with iphone dropbox app:
- Create a new file inside of a Zim notebook folder, with a space and with data inside like this:
"a new file.txt" 
"here is data inside new file from iphone"
- upload on iphone dropbox app
- go to your pc and open up zim- sync update index etc..
- look at the "a new file" inside ZIM-
- look at the file with explorer (or finder) - you will see "a new file.txt" in the expected place
- in zim UI the file is EMPTY - but if you use a OS level editor like notepad- you will see "a new file.txt" has the contents "here is data inside new file from iphone"
- if you EDIT the file in ZIM- zim makes a new file named "a_new_file.txt" 
- if you look in ZIM you - the "a new file" page is EMPTY - the data "here is data inside new file from iphone" never makes it to the ZIM page and is never viewable
     the data STILL is inside the "a new file.txt" on the disk- but you cannot get to the data via ZIM UI- nor can you easily (as a normal user) find your missing data if you have alot of pages..

**EXPECTED:**

"a new file" should have the contents of "here is data inside new file from iphone" when viewed in ZIM- 
when zim makes a new _ file - it should carry over the original data and paste it into the new file 

also note: the "files" table in the mysqllite db- has a listing for BOTH "a new file.txt" and "a_new_file.txt"

**What is going on?**
it looks like when zim sees an outside file- that does NOT have the expected heade-r it displays nothing in the ui- it also does not import that data when converting the file from spaces to underscore file names..

**Expected behavior**
I would expect - when I first go to the pc to see the file I added on the iphone- that zime would display 
"here is data inside new file from iphone" for the  "a new file"  page

**Why this sucks:**
I have a TON of pages total (20K) and many I have added on iphone- literally over the last year- 
and many of them - the data i entered via another pc or iphone or android is "missing" inside the Zim ui
(its not completely gone- but its not easily accessible or easy to find)

I am probably going to have to write some kinda program which looks at sqllite files table and tries to find filenames that were converted to _ from spaces - and then pull the data out of those files and I guess append it to the new files (maybe a select where files.name contains a space character or something?)

I love Zimwiki and took the time to write up this bug so that people who maintain the code are aware

I am a C# developer and not great at python- otherwise I would try to be more helpful :) 

also- if this gets fixed - I would be happy to help test- just shoot me an email :)

**Comment by brianbraatz** [comment]
if it helps anyone find "missing data" - with a sqllite client if you run the following query against the index.db files table - it will show you files that have spaces in them (which are files where your hidden data will be)

SELECT *
  FROM files  
 WHERE instr(path, ' ') > 0;

**Comment by jaap-karssenberg** [comment]
As far as I'm aware zim has never supported file names with whitespace for page names in the index. If it did it was unintentional. Commit 3d9f179 only affects links, but not the indexing itself.

So my question is, did it change - if so at what version upgrade - or is it something you expected to work but didn't.

**Comment by jaap-karssenberg** [comment]
Stale item - please open a new item if same or similar problem is seen in latest version of zim
