### ISSUE TITLE
Superscript formatting doesn't persist and leaves garbage characters

### ISSUE THREAD

**Issue by BrentonEarl** [zim-desktop-wiki/zim-desktop-wiki#416]
OS: Slackware x86_64
Python: python-2.7.14 
Zim: 0.68

I am writing up some documentation for a project I just completed.  The superscript formatting does not persist between page loads or when zim is closed and reopened..  When the superscript in zim is saved, closed, and reopened some unexpected characters are added to the original text.

Text that I am trying to superscript:
```
sbopkg -i hostap
chmod +x /etc/rc.d/rc.hostapd
/etc/rc.d/rc.hostapd start
```
Example problematic text:
```
^{sbopkg -i hostap
chmod +x /etc/rc.d/rc.hostapd
/etc/rc.d/rc.hostapd start}}
```
You will notice that a **^{** is add to the start and a **}}** is added at the end.  In the past I used verbatim formatting for such cases.  However, the indentation is all off for that, as reported in ticket #414.

**Comment by DocSalvager** [comment]
The extra characters are the actual markdown codes.

Looking at the pure markdown below in an example from my system, note that the "Created..." and "Revised" lines are individually formatted (enclosed in `^{ ... }`) the first time and selected together the second. The first displays using the proper formatting but the second doesn't. It just displays the raw markdown.

====== Login ======
^{Created Tuesday 08 September 2015}
^{Revised Saturday 22 September 2018}

^{Created Tuesday 08 September 2015
Revised Saturday 22 September 2018}

**Comment by jaap-karssenberg** [comment]
Zim does not support multi-line code in a inline format, so it breaks at the end of line. That is expected behavior.
