### ISSUE TITLE
When cut/pasting diagrams (graphviz) into another page the images show as missing

### ISSUE THREAD

**Issue by ziggystar** [zim-desktop-wiki/zim-desktop-wiki#418]
### Actions 

1. cut multiple diagrams from a page
2. paste into another page

### Result

- The diagrams are missing from the first page `p1` (expected)
- The diagrams show up as missing-image symbols in the destination page `p2`
- The dot-source cannot be edited or accessed in the `p2` (no option in context menu)
- The dot-source cannot be accessed in `p1` (items have been cut)

This is effectively data loss for the user.

### Workaround

I could repair the situation in the file-system, by creating a new attachment directory for `p2` and copy the respective files from the attachment directory of `p1`. This is quite annoying, if you have many dot files in `p1` and you have to sort out which ones are the copied ones.

While trying to fix this, I also found it difficult to associate the `*.dot` files with the figures within the page: #419

**Comment by jaap-karssenberg** [comment]
For current objects this will be "won't" fix as neither solution for #45 or #46 will solve this in a generic way.

Planning to make these objects inline rather than based on external sources, that makes this easier to fix

**Comment by jaap-karssenberg** [comment]
To be solved by implementing #841

**Comment by pfalcon** [comment]
> To be solved by implementing #841

Even if this particular case (image-generator plugins) will be solved by #841 (which IMHO will be sad, as I explained in it), there still remains the case of the normal images inserted into page (aka image attachments) themselves. #1312 was posted which tries to solve that in a particular (among at least 2 possible) ways.
