### ISSUE TITLE
Link ending with a dash (-)

### ISSUE THREAD

**Issue by jennerwein** [zim-desktop-wiki/zim-desktop-wiki#421]
If I have a link in my Zim page which is ending with a dash, for example
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#container-core-v1-
then the last dash is not contained in the URL when I click the link in Zim.
In the case above this results in a wrong position on the clicked web page.

**Comment by jaap-karssenberg** [comment]
Part of solution to issue #219
