### ISSUE TITLE
Linux & windows end of line

### ISSUE THREAD

**Issue by whatsthecraic** [zim-desktop-wiki/zim-desktop-wiki#428]
Hi there,
I have a set of notebooks that I share, through a main git repository, among different Linux & Windows computers. All files have the Unix line ending (a single \n), but when altered on Windows, all the line endings in the same file are changed to the Windows encoding. Is there a setting to avoid this behaviour, and preserve the line encoding across the whole wiki?

**Comment by banan314** [comment]
From the help page of Zim: 

> There is a notebook specific config files called "notebook.zim" which should be in the notebook folder. This file contains a section "[Notebook]" which contains the properties that can be set in the properties dialog.
> One hidden property is "end_of_line" which determines the end-of-line convention for files written by zim within the scope of this notebook. The value can be either "dos" or "unix". For newly created notebooks this value is set depending on the platform on which zim is running. Main purpose of this property is to ensure that a notebook which is shared between e.g. linux and windows machines does not change the full file on every write. When desired the property can be changed manually, which will affect all pages edited after the change.

In my `notebook.zim` config file there is a property `endofline=unix`. Tell us what is in your config file.

**Comment by ISInminkler** [comment]
I noticed that zim doesn't create new files properly with this option. It will still use windows line endings even when the notebook.zim config file property endofline=unix is set.

**Comment by fladd** [comment]
My notebook does not have this file (anymore). How can I recreate it?

**Comment by keeper-dev** [comment]
I have the same issue on windows 7 (as @ISInminkler reported): When adding "endofline=unix" to notebook.zim it has no effect.
Even when i convert the eol's withhin the files myself into LF, after opening the notebook and applying one change, the entire file is converted back to CRLF
