### ISSUE TITLE
When i drag the border to make the bottom scroll bars disappear, zim crashed 

### ISSUE THREAD

**Issue by exp2kernel** [zim-desktop-wiki/zim-desktop-wiki#430]
![image](https://user-images.githubusercontent.com/38710044/39288488-c618d8ce-495a-11e8-927c-df9fad79d946.png)
![image](https://user-images.githubusercontent.com/38710044/39288533-f9b49254-495a-11e8-82c3-bdb02dadbda9.png)

**Comment by jaap-karssenberg** [comment]
Afraid there is no information in this error that I can use to fix something. When it happens again please try running zim with the "--debug" option and add the error log.
