### ISSUE TITLE
Detect and delete empty journal pages

### ISSUE THREAD

**Issue by hellocatfood** [zim-desktop-wiki/zim-desktop-wiki#431]
I use the journal extension in Zim to write notes from lectures and meetings. Once I have finished with the notes I will either delete it or create a separate page to move the notes to. This leaves the journal page empty again (except for the page title/date).

However, the corresponding .txt file for the journal page still exists with no easy way to delete it.

Could Zim have an easy way to detect and delete empty journal pages?

**Comment by Osndok** [comment]
Have you tried selecting 'delete page' from the file menu? or (by the same name) in a context menu when you right-click on the page in the index or navbar?

**Comment by jaap-karssenberg** [comment]
When you delete *all* content of a page - including the title - it will be
automatically deleted.

-- Jaap
