### ISSUE TITLE
Font property not working.

### ISSUE THREAD

**Issue by Tralen** [zim-desktop-wiki/zim-desktop-wiki#435]
I've read that the font property would be available for all tags in 0.68, but it doesn't seem to work for the **Pre** and **Code** tags. I'm unable to override them.

I'm running Void Linux, with Zim 0.68-1.

**Comment by Tralen** [comment]
There is something wrong with the Code tag in general, it also doesn't respond to zoom properly. The characters stay the same size no matter how much I zoom in or out.

**Comment by jaap-karssenberg** [comment]
Are you talking about code blocks (inserted objects) or about "verbatim" formatting ?

**Comment by jaap-karssenberg** [comment]
Interesting - code blocks don't follow the default font changes because we set them to "monospace" and hence they have their own font.

- Allow to set font config per tag
- Need zoom to address each tag individually

**Comment by jaap-karssenberg** [comment]
Re-tested with zim 0.70, now works as described in the manual page as far as I can judge.
