### ISSUE TITLE
Missing trayicon icon for flathub package

### ISSUE THREAD

**Issue by thecursedfly** [zim-desktop-wiki/zim-desktop-wiki#437]
Launching Zim with
`flatpak run org.zim_wiki.Zim --plugin trayicon`
the application opens minimized in the trayicon, but **no icon** is visible; there is an empty space which can be clicked to get the normal Zim options and maximize it.
The following message appears in the terminal, which I guess is related:
"_WARNING: Could not find all icon sizes for the application icon_"
**Edit:** this message appears also with the distro packaged zim, not only the flatpak. And with that one the trayicon is shown.

Background info:
- Fedora 28 x64 KDE, kernel 4.16.6
- flatpak package, Zim version 0.68
- two separate notebooks

On an unrelated note (not sure if it's an issue with flatpak or Zim), it's not possible (or I don't know how to do it) to set the flatpak Zim with the Trayicon plugin in Autostart (when booting the OS) so that it starts _minimized_ instead of maximized. I configured it to use a startup script with the "flatpak run" command instead.

**Comment by cheese** [comment]
This is fixed in the next Flathub update.
