### ISSUE TITLE
Cursor position forgotten.

### ISSUE THREAD

**Issue by Tralen** [zim-desktop-wiki/zim-desktop-wiki#439]
On Zim 0.68 when I leave a page and then return, the position of the cursor, the scrolling position, is forgotten, and I'm returned to the top of the page. It doesn't matter if I return via a link, the index pane, or a bookmark, the position is consistently returned to the top.

The only way I can make the last position be remembered is if I explicitly save the page, while on 0.65, just having the notebook editable would suffice. Perhaps this is related to the current problems with the notebook editable feature.

Running Zim 0.68 on Void Linux.

**Comment by nelas** [comment]
This is also occurring to me with the latest master commit: 425395d

- [x] Always use last cursor position when opening a page

...is checked. On Ubuntu 18.10.

**Comment by jaap-karssenberg** [comment]
Believe this to be fixed in f5ebaf800b101cdba23baa4abaf40c9b94c8b592
