### ISSUE TITLE
Cannot launch flatpak with different system locale

### ISSUE THREAD

**Issue by thecursedfly** [zim-desktop-wiki/zim-desktop-wiki#442]
When the system locale is en_US.UTF8 the Zim flatpak opens without problems.
If the system locale is changed (in my case to it_IT.UTF8), after logout&login and launching the Zim flatpak again, the following error is given:

[antani@localhost ~]$ flatpak run org.zim_wiki.Zim
Traceback (most recent call last):
  File "/app/bin/zim", line 42, in <module>
    import zim
  File "/app/lib/python2.7/site-packages/zim/__init__.py", line 147, in <module>
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

Then, the following works fine and Zim opens:

[antani@localhost ~]$ flatpak run --env=LC_ALL=en_US.utf8 org.zim_wiki.Zim
WARNING: Could not find all icon sizes for the application icon
[antani@localhost ~]$ 

I believe that the Zim flatpak should still open even if the system locale is changed, and if the language is not supported, default to English.

My system:
Fedora 28 KDE 64bit
flatpak 0.11.7
Linux 4.16.7
Zim flatpak 0.68

**Comment by thecursedfly** [comment]
The same issue happens in a mixed locale situation (I like to have local formats only for date/money/etc), such as:

[antani@localhost ~]$ locale
LANG=en_GB.UTF-8
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC=it_IT.UTF-8
LC_TIME=it_IT.UTF-8
LC_COLLATE=it_IT.UTF-8
LC_MONETARY=it_IT.UTF-8
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT=it_IT.UTF-8
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=

**Comment by jaap-karssenberg** [comment]
Is this flatpak specific, or also happens when running from source ?

**Comment by jaap-karssenberg** [comment]
I believe this to be the same issue adressed in 56029de9f77bcfabc5c008b1310d749766909add
