### ISSUE TITLE
Apply labels to a whole list

### ISSUE THREAD

**Issue by schiessle** [zim-desktop-wiki/zim-desktop-wiki#445]
According to the documentation labels can be used to flag a whole list as a task list http://zim-wiki.org/manual/Plugins/Task_List.html

````
 TODO: @home

   []  Call Susan to invite for diner <2017-05-01 !
   []  Print menu @desk

````

Will add the `@home` tag to all list items. But the label will not be added to all items. Not sure if this is intended or a bug, but it would be nice if the label would be added to all items als well so that something like this would be possible:

````
 TODO:

   []  Call Susan to invite for diner <2017-05-01 !
   []  Print menu @desk

````

Background: Tasks with a label get separated in  the task list window at the top and in bold before all the other tags and pages are listed in the right hand sidebar "Tags". This would be really handy in order to have a better overview over my tasks for "today", "tomorrow", and "this week". Adding this label to every task individually is really bulky. It would be nice to have something like:

````
Today:
  [] task1
  [] task2
  ...

Tomorrow:
  [] task3
  [] task4
  ...

 week:
  [] task5
  [] task6
  ...
````

Which would result in having the three categories (aka labels) at the top of the "Tags" list of the task list window.

**Comment by jaap-karssenberg** [comment]
Works as documented in the latest master revision. Be aware that for this feature to work there should be no empty line between the "heading" and the checkbox list.
