### ISSUE TITLE
[Feature request] Distinct bullets for each level in a multilevel lists

### ISSUE THREAD

**Issue by leafcutterant** [zim-desktop-wiki/zim-desktop-wiki#447]
It would be very helpful to have multilevel lists in Zim. I'm referring to the style of multilevel lists you can find in MS Word or LibreOffice Writer, where each level has its own bullet symbol and the selected line(s) can be demoted (down) or promoted (up) in the hierarchy.

To avoid word processor-style complexity, I'd propose to use this with bullet lists only. Zim could include a default set of bullet symbols which would certainly satisfy most needs (let's say 15-20 levels), after which symbols would be recycled in the same order. Two buttons on the toolbar would enable demoting and promoting lines. When the cursor is in a line which is not bullet-pointed, promoting would be disabled, and demoting would transform the line into a level 1 bullet point.

What do you think?

**Comment by Osndok** [comment]
Numbered lists already alternate between alphas and numerics for different tab levels automatically, and one can already format a sub-list as a different type (bullet/numbered/checked)... Is that what you mean? Or is this specifically for **custom** list decorators?

**Comment by leafcutterant** [comment]
I don't mean custom list decorators. I meant simply a multi-level bullet list option and a potential review of how Zim makes lists. I was unaware of the alternation you mentioned, but that has several shortcomings and is far from what I described.

* Just numbers and letters (two "symbols") is very repetitive and makes it hard to ascertain which level you are in.
* You can't delete the tab to promote the line; the line will join the previous line, and if you press enter again, you are where you started from. Demotion/promotion is therefore not present.
* If you delete a previous line or insert a new one between two previous ones, Zim will do all kinds of weird and inconsistent stuff. I was able to create this with random monkeying around:
![0](https://user-images.githubusercontent.com/7106231/40391534-e7bc8854-5e18-11e8-863e-ac306ae42365.png)
* In addition, doing this with bullet symbols carries the advantage that Zim can't screw up the serialization and you will have clear, visual impression of which list level you are in.

**Comment by Osndok** [comment]
I don't know, man... the enumeration can definitely be quirky at times... and I'm **100% sure** there is room for improvement... but I find it to be a **lot** more usable that it seems to be for you. It makes me wonder if your python/platform is a bit broken.

In particular, tab, shift-tab, and delete all work as expected for promotion/demotion... and there are probably easier and more effective ways to help the disorientation (like having faint/colored 'indent lines', or accordions) ... and I find that zim does a pretty good job of letting you **manually** change whatever number/character is on the line (cursor, arrow keys, etc) for those cases where you want to change the decorator (like, to all caps) or to start at a different number/letter.

Come to think of it, I'm pretty sure that (most of the time) I only use one-or-two outline indentation levels... and even then, I usually just use checkbox decorators (as I often want the functionality later). Beyond that, you are probably brainstorming (in which case a MindMap would be better), or maybe using subpages.

Speaking of subpages... I can't put my finger on it, but (to me) there has always been just a **small bit** of disharmony between the zim page index (which itself is an outline) and making outlines in zim... which are often later converted to subpages... which sorta just shifts the outline into the page index... but is quite awkward to do, and then loses ordering.

IMO, higher priorities would be: (1) roman numerals [ughh], and (2) not starting an outline on a number that is likely a year (try: "1990. ").... or in the far-off-futurism land... integrating solid mind maps w/ each node being a zim page, but that's probably quite a bit more work than anything else mentioned here.

**Comment by leafcutterant** [comment]
I use the "official" Windows builds (the ones linked to on the site), I don't know if the builder's platform is broken.

I like to be proven wrong and I didn't know about the Shift + Tab combo for promotion. This brought me closer to what I want to achieve, so thanks! Unfortunately, the same quirks remain. (I gave up on numbered/lettered lists, now going with just bullet points, those suffice my needs.) If I don't edit the list linearly, meaning I insert new lines or delete old ones, then I experience the following:
* sometimes these line can't be promoted or demoted
* sometimes, they can only be demoted, but not promoted
* sometimes demotion/promotion moves subpoints together with the main point to preserve their relative position, and sometimes, it doesn't
* sometimes lines above/below a inserted line exhibit random inconsistent behavior
* if I accidentally delete the bullet symbol or the space after the symbol, Zim stops treating the line *and* its subpoints as part of the list. Trying to re-integrate them into the list hierarchy is a nightmare.

This makes me think that Zim doesn't track list hierarchy positions strongly, it just puts some visuals on top of the present tab system.

I'd still find multiple decorators very useful. And you are right, I could insert them myself, but that's vary inconvenient, to check the hierarchy level and manually insert the corresponding symbol every time you make a new line in the list.

>like having faint/colored 'indent lines', or accordions
I'm not sure what those are. Could you explain them more elaborately?

> you are probably brainstorming (in which case a MindMap would be better), or maybe using subpages.
I know mind maps, but they don't fit my purpose (I'm not brainstorming). I mean, I *could* represent my stuff as a mind map, but it would be a very inefficient way of going about it. Hierarchical lists are just what I need, but for now for that I have to scatter my things around different in systems/applications. I think consistent multilevel lists would really be a fitting addition to Zim as it already has something that comes close to it.

>there has always been just a small bit of disharmony between the zim page index (which itself is an outline) and making outlines in zim
Indeed, the discontinuity between the page index and the in-page outlines is a very interesting issue. It kinda begs an option to make a subpage from a Heading 1 header and promote all other headers one level up when a heading section becomes too big. But for that I think the collective promotion/demotion of headings has to be solved first — which is analogous to my problem here. Namely, it would be also helpful to be able to change the heading level of a heading in a way that all of its subheadings would be promoted/demoted one level together with it.

>not starting an outline on a number that is likely a year (try: "1990. ")
I came across that so many times it's frustrating how Zim wants to make a numbered list after every line that starts with <number(s)><dot>.

**Comment by jaap-karssenberg** [comment]
Not sure I understand the request. Zim has multi-level bullet lists with <Tab> and <Shift><Tab> for basic promoting / demoting.

Is the key point here to render sub items with different bullet style or is there something else to it?

**Comment by leafcutterant** [comment]
> Is the key point here to render sub items with different bullet style or is there something else to it?

Yes, that's part of it. I guess this is my tl;dr:

* render different levels with different symbols
* remove the possibility for inconsistencies mentioned [here](https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/447#issuecomment-391150480) and [here](https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/447#issuecomment-392267745)
* if the Tab is deleted with Baskspace, make sure the line is promoted
