### ISSUE TITLE
new tags are not added to database

### ISSUE THREAD

**Issue by kareliot** [zim-desktop-wiki/zim-desktop-wiki#448]
Is there a limit for the number of tags (@example) one can have?

I have noticed that new tags are not added to the tag list, the tag cloud or the tag-autocomplete list anymore. The are still rendered in the style of tags, though (orange font colour).

Where are tags stored? I could not find the database for them. Would it be possible that it got corrupted – maybe through my nextcloud sync?

**Comment by kareliot** [comment]
I have found out  that the problem seems to be with too many tags on one page. I can still add tags on new pages but not on a page where I have a lot of text and a lot of tags already. Is there a limit for the number of tags on a single page or is this a bug?

I am using Zim 0.68 on Arch Linux.

**Comment by jaap-karssenberg** [comment]
Can't reproduce this issue. Do you have a ballpark at how many tags per page we are talking about when it breaks ?

**Comment by jaap-karssenberg** [comment]
Stale item - please open a new item if same or similar problem is seen in latest version of zim
