### ISSUE TITLE
zim file extension already in use

### ISSUE THREAD

**Issue by KatjaD-CH** [zim-desktop-wiki/zim-desktop-wiki#449]
Choosing __zim__ as file extension for notebooks was unfortunate because it's already in use. ([ZIM file format](https://en.wikipedia.org/wiki/ZIM_(file_format))

This file extension is in use by the application [Kiwix](https://en.wikipedia.org/wiki/Kiwix) that I use for reading the wikipedia and other wikimedia wikis offline.

Until now I haven't tested if interwiki links to Kiwix will be an additional problem.

**Comment by dgasaway** [comment]
Near as I can tell, Zim has been using the "notebook.zim" name since 2009. The ZIM file format you speak of started 2012 or 2013.  Kiwix was first released in 2014.

**Comment by jaap-karssenberg** [comment]
Won't fix, as per comment above, we used it long before "the other zim project" started doing so.
