### ISSUE TITLE
Show link destination for keyboard navigation

### ISSUE THREAD

**Issue by e3rd** [zim-desktop-wiki/zim-desktop-wiki#452]
I love using Zim for years!  

When mouse cursor is on a link, its destination is visible in the status bar.  
However, when I navigate keyboard caret on a link, nothing changes.

In what files would you advise me to change it in so that I may prepare a pull request?

**Comment by jaap-karssenberg** [comment]
This is controlled by the "link-enter" and "link-leave" signals in the "pageview" module. The statusbar monitors these signals and displays the destination.

**Comment by e3rd** [comment]
Thanks, I'll try to prepare a PR in few weeks.
