### ISSUE TITLE
[feature request] Add key shortcut to making a line into a bullet list

### ISSUE THREAD

**Issue by leafcutterant** [zim-desktop-wiki/zim-desktop-wiki#453]
As the title says.

**Comment by KangarooCreativeTeam** [comment]
Also another shortcut to make line (/ all selected lines) into checkboxes (I use these _way too much_).

Thank you for Zim!

**Comment by Osndok** [comment]
Have you tried either of the generic methods of setting a keyboard shortcut, such as that in #81 or #211 ?

**Comment by KangarooCreativeTeam** [comment]
Thank you for the advice.  

I've tested; setting custom keybindings via enabling the flag (mentioned in #211) `gtk-can-change-accels = 1` in `$HOME/.gtkrc-2.0` (& then restarting Zim) works.
(I set by placing the cursor over the relevant menu item & pressing my desired shortcut key).
(For reference; I'm using KDE as my DE).

I've tested further; I see this feature is implemented for bulletlists (select text & type '*'), however is not implemented for checkbox lists.  The current line / selected text (even multi-line selection) does not convert to checkboxes, but ignores the selection & simply adds a new empty checkbox item.

Thank you.

**Comment by Osndok** [comment]
> I see this feature is implemented for bulletlists (select text & type '*')

Interesting... I'm on the other side with this one... I would rather disable (or change the shortcut for) that feature, as the only time I run into it is when I actually want to replace the current selection with an '*', or on occasion it will bug-out and always indent a line even without a selection (so you can't use a '*' at all) being guarded by selection and not a ctrl/alt modifier key.

I've actually looked through the source hunting for this effect, but not found where this is implemented, or if it is actually intentional.

**Comment by jaap-karssenberg** [comment]
When you select multiple lines and hit "*" it will become a bullet list.
Might be nice to do the same with "[" for checkboxes

**Comment by jaap-karssenberg** [comment]
@Osndok: currently it is implemented low-level here: https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/1e564acb91d6d1a75ed523b95db94688a7799f44/zim/gui/pageview.py#L3862

But if accelerators give the same effect, that is a preferred solution in my opinion.

**Comment by vossenjp** [comment]
FWIW I have defined the following and can't live without them:
* CTRL-L for Bullet
* CTRL-N for Number
* CTRL-K for Checklist

**Comment by fmaximo** [comment]
Hey Guys.
If a line starts with "[" folowed by "]" and a space, it will turn in to a selection box.

**Comment by jaap-karssenberg** [comment]
Since it is so easy to type a bullet ("*") a numbered item ("1.") or a checkbox ("[]") I don't see reason to add more keybindings. Also when selected typing "*" can toggle list behavior on multiple lines.
