### ISSUE TITLE
Do not show tasks with task label but without checkbox

### ISSUE THREAD

**Issue by fladd** [zim-desktop-wiki/zim-desktop-wiki#454]
If I enable task labels (like NEXT, WAITING, SOMEDAY), then typing these words in the absence of a task (i.e. a checkbox) will still put the line they occur in into the task list.

For instance, consider a page with the following content:
```
NEXT CHAPTER
------------

This is the next chapter.
```

This will put a task named `NEXT CHAPTER` into the task list.

I think there should at least be an option to prevent this. And potentially this should also not be the default behaviour.

**Comment by jaap-karssenberg** [comment]
This is a "won't fix" for me. You can either choose labels that do not appear normally in your text, or not use labels at all and only use checkboxes.

**Comment by fladd** [comment]
True, but unfortunately there is not "Next" checkbox type.
