### ISSUE TITLE
Task label not inherited when using it to denote a whole list as task list

### ISSUE THREAD

**Issue by fladd** [zim-desktop-wiki/zim-desktop-wiki#456]
When I use a task label in its special case to mark a whole list as task list, then the label I use is not given to the tasks on that list.

For instance:
```
NEXT: @test
[ ] some test
```

The task `some test` is not marked with the NEXT label. It will be a task without any label and the tag @test.

**Comment by jaap-karssenberg** [comment]
This is the intended behavior
