### ISSUE TITLE
Gnuplot plugin cannot plot file

### ISSUE THREAD

**Issue by xvusrmqj** [zim-desktop-wiki/zim-desktop-wiki#457]
I am using **windows 10**. and Zim 0.67 and gnuplot 5.2 .
I **can** `plot sin(x),cos(x)`, but **cannot** plot a file, eg. `plot 'C:\Users\lv\Desktop\testGnuplotZimPlugin.txt'`. 

I also need to plot the current directory file. I find the site :https://bugs.launchpad.net/zim/+bug/1017872
It is a bug fixed in ubuntu.  I hope it works in windows. 

In general, I hope the gnuplot plugin can plot file in both absolute path or relative path .

---------------------

after `plot sin(x),cos(x)`  successful to plot a image . I cannot repeat it .  now the gnuplot plugin can plot nothing.....

**Comment by jaap-karssenberg** [comment]
Relative files indeed do not work currently because the script is executed in a temporary folder. But absolute file names works fine in my testing.

Can you give exact steps to reproduce?

**Comment by jaap-karssenberg** [comment]
Stale item - please open a new item if same or similar problem is seen in latest version of zim
