### ISSUE TITLE
Task label not case sensitive

### ISSUE THREAD

**Issue by fladd** [zim-desktop-wiki/zim-desktop-wiki#458]
If setting up the task label NEXT, the following task will incorrectly be shown in the NEXT list of that task list plugin:
```
[ ] TODO Plan next steps
```

**Comment by jaap-karssenberg** [comment]
Closing because the "Next" label feature has been removed in latest version because it didn't work well.

**Comment by fladd** [comment]
This is **not** about the "Next" feature. It is in the latest version of Zim, when just setting up my own label called "NEXT". Writing the word "Next" then will result in the behaviour described above. Please reopen.

**Comment by jaap-karssenberg** [comment]
Tested with latest version but in the example you gave it just shows up as
"TODO". And the parsing is fully case sensitive, e.g. starting with "todo"
does not match the TODO label.

-- Jaap

**Comment by fladd** [comment]
I am afraid that this needs reopening. Tested in the newest version and task labels are definitely **not** case sensitive:

<img width="886" alt="image" src="https://user-images.githubusercontent.com/2971539/72677147-986e6380-3a99-11ea-8ea8-4dea46acea9f.png">

As you can see in the screenshot, the task plugin somehow knows that these are different labels (it lists them individually, and also has the correct number of items behind them), but when actually listing the tasks, it shows tasks for both, upper and lower case labels.
