### ISSUE TITLE
On copy-paste update relative links 

### ISSUE THREAD

**Issue by jaap-karssenberg** [zim-desktop-wiki/zim-desktop-wiki#46]
Copy-paste pastes relative links as-is and thus can break. Would be more consistent to update those links on paste to refer to the same page as before.

**Comment by jaap-karssenberg** [comment]
https://bugs.launchpad.net/zim/+bug/501496

**Comment by jaap-karssenberg** [comment]
Other variation: https://bugs.launchpad.net/zim/+bug/1133365

**Comment by ziggystar** [comment]
Maybe related:  #418

**Comment by jaap-karssenberg** [comment]
* Both page and file links (related to #48)
