### ISSUE TITLE
Date appears in task name in task list

### ISSUE THREAD

**Issue by fladd** [zim-desktop-wiki/zim-desktop-wiki#460]
When a task has a starting as well as a due date, the one of those that is last written will appear as part of the task name.

For example:
```
A task >2018-07-01 <2018-07-02
```

Will lead to a task name of `A task <2018-07-02` in the task list.

**Comment by druedin** [comment]
I do this all the time and don't have the issue described. Have you checked you don't have the "due date" or "start date" twice? In this case, one of the dates appears in the task list.

**Comment by fladd** [comment]
![image](https://user-images.githubusercontent.com/2971539/43401083-9274683a-940f-11e8-9044-921e254d5d9d.png)

**Comment by druedin** [comment]
Sorry for the misunderstanding. This is how it appear here, too.

**Comment by jaap-karssenberg** [comment]
dev note:   need to update text filter
