### ISSUE TITLE
Table of Contents expands/unfolds all items after every save (including autosaves)

### ISSUE THREAD

**Issue by Shane-Optima** [zim-desktop-wiki/zim-desktop-wiki#462]
As originally mentioned in a Launchpad bug [here](https://bugs.launchpad.net/zim/+bug/1577252), the ability to collapse/fold items in the Table of Contents plugin by clicking on the little arrows is nearly useless in all versions and on all platforms because all of the collapsed items (">") will automatically expand themselves ("V") immediately after Zim autosaves, which usually happens immediately after the user starts typing.  

Being able to jump around to the different ToC headings within a long page is, for me, one of the most useful features that Zim offers over a plain text editor, but this makes long pages with lots of headings very cumbersome to navigate.

I had an idea for a simple band-aid fix via skipping the refresh process whenever it detects that there haven't been any changes to the ToC / headings since the last time it was refreshed. (In other words: str1 = [iterate through and cat all entries in listed in ToC], str2 = [iterate through and cat all current headings in the document], if str1 == str2, skip the refresh process as unnecessary, else refresh the ToC as normal).   But I just don't have the experience to make [much headway](https://github.com/jaap-karssenberg/zim-desktop-wiki/blob/master/zim/plugins/tableofcontents.py).

Thanks for all your hard work.

**Comment by vossenjp** [comment]
I was going to open a bug called "ToC focus keeps jumping to the top (on autosave?)" but found this one...  So I agree.  I'd say this "feels" even worse with 0.70 because up to 0.69.1 this was only mildly noticeable to me and not it's driving me nuts with 0.70.

**Comment by Shane-Optima** [comment]
Jaap-karssenberg was of course correct in tagging this as a "good first issue." I described above how the patch could function, and I'm 99% sure it would fix the problem. (Find the refresh code, then surround it with an "If" that checks to see if the ToC actually needs refreshing. If it doesn't need a refresh--i.e. if the ToC lines on the page matches the ToC entires in the ToC pane--then you skip the refresh.)

I'd do it myself, but I have zero Python experience and more importantly very little experience with Github and in non-trivial collaborative coding project environments in general. Admittedly, I also tend to be confused and annoyed by many popular OO design patterns  (I'm not a professional; I'm just a solo tinker-er who dislikes much of C++-ish OO in general. ) 

That said, I'll gladly write the patch myself if someone ever found the time to get me started. If someone else familiar with Python and/or the codebase could tell me:

1) Exactly where the refresh happens
2) How to retrieve the full raw text (with hidden markup characters included) of the current page from that point in the code
3) How to retrieve all of the text currently displaying in the ToC pane (with indents included) from that point in the code

...I will gladly sit down with a Python reference book, puzzle it out and submit a patch!

After you find those three essential things, the rest would simply consist of: looking up Python's string manipulation methods, parsing the relevant strings to set up the comparison, wrapping the ToC refresh code in an "if" based on the string comparison (the current ToC title strings vs. a concatenated string of titles taken from the current version of the article), and then debugging the result.  

(The best and cleanest method of setting up the string comparison would to re-use whatever code the ToC plugin is using to generate the titles in the first place, but if for some reason that weren't clear or easy I think it would be simple enough to just re-invent the wheel.)

I know y'all are busy and this is OSS; I'm not claiming this should be high priority. I just wanted to put this out there to any Python devs who happen to read this. Even if you're a novice with Python, if you can figure out #1, #2 and #3, then you can write the patch that fixes this. (Or, if you could explain those three things to me, I'll write it.)

(There might be other ways to fix this issue, like measuring the current state of the arrows ( collapsed ">" vs. expanded "V"), but my gut assumption is that it's cleaner to do it as I describe above.)

**Comment by jaap-karssenberg** [comment]
Dev notes:
  * On update create new model and compare per node with existing one
  * Update changes in existing model
  * Only on change page reload fresh model
