### ISSUE TITLE
Attachment browser: Drag & Drop not working under Windows

### ISSUE THREAD

**Issue by mayonezo** [zim-desktop-wiki/zim-desktop-wiki#464]
Dragging files from Windows Explorer to the attachment browser does not work under portable version 0.68, nothing happens.

**Comment by jaap-karssenberg** [comment]
Needs re-testing with version 0.70 or newer

**Comment by jaap-karssenberg** [comment]
Works fine in my windows install with 0.70. However, be aware of issue #390
