### ISSUE TITLE
Impossible to write \name into a table cell

### ISSUE THREAD

**Issue by KatjaD-CH** [zim-desktop-wiki/zim-desktop-wiki#467]
As the title says it isn't possible to create a table like this one:

Meaning|Form|Example
--------|-----|-----
downward|\name|\LINE

**Comment by Osndok** [comment]
In my testing, only the center column had issue "\name". Is that your experience too?

It seems to be that "\n" is being interpreted as a newline, which is subsequently filtered out.

**Comment by KatjaD-CH** [comment]
Under Windows (Zim version 0.68) the following code
```
| Meaning    |      Form      | Example         |
|------------|----------------|-----------------|
| \name      |    \name       |  \name          |
| \\name     |    \\name      | \\name          |
| ''\name''  |  ''\name''     | ''\name''       |
| ''\\name'' |  ''\\name''    | ''\\name''      |
```
gives me
```
+---------+-------+---------+
| Meaning | Form  | Example |
+---------+-------+---------+
| ame     | ame   | ame     |
+---------+-------+---------+
| \       | \     | \       |
| ame     | ame   | ame     |
+---------+-------+---------+
| ''      | ''    | ''      |
| ame''   | ame'' | ame''   |
+---------+------+----------+
| ''\     | ''\   | ''\     |
| ame''   | ame'' | ame''   |
+---------+------+----------+
```

It looks as if the parser doesn't consume the second backslash of `\\` and interprets the following "n" as `\n`.

I haven't done extensive testing with the table editor. Usualy I write tables in a separate text editor.
(Would be nice when zim had the possibility to edit source code inside the application)

**Comment by jaap-karssenberg** [comment]
dev notes:   Add test, find string eval in serialization

**Comment by jaap-karssenberg** [comment]
Need rewrite of table escape code to properly fix this issue
