### ISSUE TITLE
Spell checker doesn't recognize contractions

### ISSUE THREAD

**Issue by BlindWanderer** [zim-desktop-wiki/zim-desktop-wiki#471]
I wouldn't normally complain but when the spell checking won't handle such a simple sentence as this and doesn't want to behave nicely I kind of have to.

I'm running version 0.68 on lubuntu with gtkspellcheck installed.

**Comment by jaap-karssenberg** [comment]
Afraid the spellchecker is a generic component that we re-use. It uses the "enchant" backend and depends on the installed libraries. This is outside the scope of the zim application.
