### ISSUE TITLE
zim don't manage to open when a book note was deleted

### ISSUE THREAD

**Issue by lalebarde** [zim-desktop-wiki/zim-desktop-wiki#476]
It seems that zim always tries to open the first book note created, even if it has been deleted from the file system.

Steps to reproduce : 

1. install a brand new linux
2. install zim wiki
3. Create two book notes
4. Close zim
5. Delete the first book note from the filesystem
6. Open zim, it crashes

This makes zim unable to work anymore, and other book notes cannot be accessed.

**Comment by jaap-karssenberg** [comment]
Zim behaves correctly when deleting the default notebook with release 0.70
