### ISSUE TITLE
Preserve undo / redo stack after switching pages or editing equation (reload)

### ISSUE THREAD

**Issue by Will-1012** [zim-desktop-wiki/zim-desktop-wiki#478]
I can't undo changes of a modified note when I come back on it after modifying another one, which I do very frequently (switching). I just loose some data because of that (and my mistake of course).
For instance, Firefox supports this feature in the opened tabs.
(edit) The issue also happens after having edited an equation.

Addressing this problem might involve to attach different undo/redo histories to each note during the session, but this is only an idea, I don't know the code behind.

(version 0.68)

Thanks

PS : Thanks to the involved community for this great tool by the way !

**Comment by ssavinel** [comment]
I got the same issue with a table.
A missclick removing a table of over ~100 items made me cry a little...

**Comment by Osndok** [comment]
Version control... it sounds like you need version control. Far fewer tears when (in the worst case) you can just revert a page to it's state "one hour ago".

**Comment by Zilwil** [comment]
Control version (that I use by the way) is a workaround, but does not solve the issue which happens with recent changes. I do not want to commit every minute my changes (hence the great auto-save functionality)...

**Comment by jaap-karssenberg** [comment]
Plan to fix this by keeping buffer for recent pages in memory. Will be a limit to the amount of pages though.

Note: should be smart and let the caching prefer edited pages, so it does not flush on browsing.
