### ISSUE TITLE
How to change default text font colour?!

### ISSUE THREAD

**Issue by zambala** [zim-desktop-wiki/zim-desktop-wiki#480]
Hello,

Yesterday I started to use Zim and it is a very good app in general, thank you.

But - how to change the default font color (blue or skyblue) in text?!

I have found %APPDATA%\zim\config\ and style.config file - I see I can change all Link colours and H1-H6 colours and some others - but I cannot find how to change the default  paragraph font colour...

**Comment by RadoslavCap** [comment]
According this thread looks like it isn't possible now: https://github.com/jaap-karssenberg/zim-desktop-wiki/issues/268

**Comment by zambala** [comment]
Radoslav;
I have read I cannot make Text colours for markup; I don't worry about this, I would assign additional markup colours to the Unused Formatting Tags like Mark, H4-H6 etc... 

This thread is about the genral Default Text Colour only - how to change the Defaukt Text Font Colour, not about additional markup colours...

**Comment by zambala** [comment]
Hello, anybody there?!

**Comment by Self-Perfection** [comment]
I bet your desire might be accomplished by running zim with custom gtkrc file. GTK applications read theme and style info from these files. Though I can't help you with exact steps, google for gtkrc and how to change it on your OS.

**Comment by Osndok** [comment]
Quoting http://zim-wiki.org/manual/FAQ.html

## Can I change the colors used for links, underline etc. ?

Yes. Copy "/usr/share/zim/style.conf" to "~/.config/zim/" and edit as you see fit. See the [Config Files](http://zim-wiki.org/manual/Help/Config_Files.html "Config Files") page for the syntax of this file.

**Comment by zambala** [comment]
Hello,

I am on Win 7 and I have changed everything like color of Links, H3 etc, exceept the very Standart and simple Font color which is Blue... and Grey/ black color instead would be good..... I cannot find standard Font color in Configuration with Links, H3 etc.

**Comment by hugke729** [comment]
@Self-Perfection has the right idea. 
At least for me, default text color is determined from my GTK2 theme (specifically the gtkrc file), unlike all the special font colors, which are determined by style.conf. How you change this on Windows, I'm not sure.

**Comment by jaap-karssenberg** [comment]
The base color of the text and e.g. the background is indeed determined by the Gtk theme. With Gtk2 it can be changed through the gtkrc file, with Gtk3 it can be changed using CSS config. See the manual for pointers on those config files.

**Comment by quesada** [comment]
I have tried following the instructions:
### GUI style config file
Zim has certain defaults on how to display styles. For example it displays links as blue text without underline. To change this style copy "``/usr/share/zim/style.conf``" to "``~/.config/zim/``" and edit it. Each style has it's own section which starts with the style name between square brackets and contains key value pairs for the various display properties.

Example:

	[TextView]
	tabs = 40
	font = **Sans 10**

No matter what value I assign to font, in ~/.config/zim/style.conf, after restarting zim I see no changes
