### ISSUE TITLE
"table of content" plugin can not identify titles with the same name.

### ISSUE THREAD

**Issue by xvusrmqj** [zim-desktop-wiki/zim-desktop-wiki#485]
I have such "table of content"
```
aaa (title)
      xxx (subtitle)
      yyy (subtitle)
bbb(title)
      xxx (subtitle)
      yyy (subtitle)
```
when i click the **xxx under bbb**. it enter the content of **xxx under aaa**. 
In short, 
**_"table of content" plugin can not identify titles with the same name._**

**Comment by ssavinel** [comment]
Just encoutered this issue, I temporarly solved it by adding a number in parenthesis after the title.

**Comment by jaap-karssenberg** [comment]
dev notes:
  * select heading method should get integer for nth occurrence and always start searching from the top
  * when clicking model, check model for duplicates above

**Comment by vossenjp** [comment]
This now works in 0.72.0, thanks!
