### ISSUE TITLE
Add transparency to Table Of Contents box

### ISSUE THREAD

**Issue by leafcutterant** [zim-desktop-wiki/zim-desktop-wiki#489]
I can't read text behind it even if I close it.

I propose adding transparency (50%?) to it, definitely when it's closed, but maybe that's also useful when it's open.

Other idea: if it helps usability, make it transparent by default, and remove the transparency when the mouse is hovered over it.

**Comment by jaap-karssenberg** [comment]
With Gtk3 you can probably try this out with CSS config.

**Comment by mouseb** [comment]
i recently upgraded to zim 0.72, and the floating TOC is now transparent, which makes reading it and the text below it impossible...

![image](https://user-images.githubusercontent.com/48327705/65894732-c79d7f80-e399-11e9-8992-0d1e3bb340ad.png)

hovering over the toc doesn't make it opaque.

**Comment by jaap-karssenberg** [comment]
See https://zim-wiki.org/manual/Help/Config_Files.html for info on changing background by CSS
