### ISSUE TITLE
Zim randomly gets stuck in a minimized state

### ISSUE THREAD

**Issue by leafcutterant** [zim-desktop-wiki/zim-desktop-wiki#490]
Win 7, Zim 0.68

From time to time, seemingly randomly, I can't get the application windows to show (=I click it and it does nothing) once it has been minimized either to the task bar or the tray icon area. The tray icon right-click menu remains accessible and quitting then starting lets me continue where I left off.

**Comment by jaap-karssenberg** [comment]
Cannot reproduce with latest version on Win10.

**Comment by leafcutterant** [comment]
It may need an extended period of use to show. I'd say I get it at every 50th minimizing/maximizing.

**Comment by fwolfst** [comment]
Issue is stale, Win7 EOL and it seems that others do not report similiar problems ~> imho this issue can be closed.
