### ISSUE TITLE
Feature Request...

### ISSUE THREAD

**Issue by ordric** [zim-desktop-wiki/zim-desktop-wiki#496]
Would it be possible to add a general highlighting for xml tags?

It doesn't matter if the tags all look the same, just so that they stand out and are easier to locate when going back through a page later. 

It wouldn't make any difference to Zim users who don't create their own xml tags, but would be helpful when you are using them to process documents.

Just an idea.

Ordric

**Comment by Osndok** [comment]
The "source view" plugin (via "Insert > Code Block") has XML syntax highlighting. Is that basically what you want? except... loose on the page-at-large?

BTW, "Feature Request..." is a pretty poor title. "XML Highlighting" would probably have been better.

Seems related to #186 & #268

**Comment by ordric** [comment]
Sort of. It would be really useful if it were possible to accentuate in someway anything between tags so that I can see them easily as I am scrolling up and down. I am not writing code though.

What I am asking for isn't really #186 or #268. I am just asking if it is possible to add to Zim, the ability to recognise <?> </?> tag pairs and accentuate in someway, the tags and the text between. 

For example, I am tagging a digital copy of a travel journal and I have created a set of tags so that I can generate an index and itinerary:
<da>Date</da>
<pe>People</pe>
<lo>Location</lo>
<tr>Transport Method</tr>
<fl>Flora</fl>
<fa>Fauna</fa>

Problem is, I keep getting asked to index other aspects and have to keep going back and altering the tags, so <pe>People</pe> has now become: 
<psw>People Stayed With</psw>
<pm>People Met</pm>
and I have to go back through the document and find all of the <pe></pe> and change them. 

An arbitrary method of accentuating an xml tag would be helpful. Doesn't really matter how, so long as it makes them visible.

**Comment by Osndok** [comment]
Ahh... I think I understand where you are going with this.

I think you are needing to use Zim as an "abstract database". I have several applications that use Zim similarly.

Consider using **page links** as an alternative!

It's not a direct conversion, and sometimes it yields "backwards english" hierarchies... but if you are more concerned with organization than grammar, suppose you made a journal entry like this (it doesn't have to be a narrative, it could just be one link per line):
```
At :Location:LasVegas w/ :Person:Alice:StayedWith , :Person:Alice & I :Person:Bob:Met 
...while in :TravelMethod:Car we saw:
* :Flora:Lilacs
* :Flora:Rose
* :Fauna:CattusDomesticus

:Person:Charlie came later.
```

This will grant you several features that you may wonder how you ever lived without:

* It will create "gray" pages (that you never have to build out) for each type & value, and if you navigate to any one of the pages (say, ":Flora:Rose"), the 'backlinks' page/menu will conveniently **list all pages that reference a particular item** (roses, in this case).
* It will let you correct & re-organize subjects "en masse". So if you later decide that you need more specificity, you can just move all your ":Flora:Rose" to ":Flora:Rose:Common" (or 'unknown'/'unspecified' & start using "one level deeper" specifications. Or to take your example, you could have moved ":Person" to ":PeopleMet" (though probably not the best way to organize such a thing).
* It lets you nest related data in a way that cannot easily be done with xml. As in the above example, there is a reference to staying with 'bob'...
* It will let you build arbitrarily complex inter-related notes. As in the above example... if you found it notable that 'bob' likes 'roses', you could somewhat-quickly stash a link in either location to form that cross-reference (i.e. either put ":Person:Bob:Likes" in the rose page, or ":Flora:Rose" in the ":Person:Bob:Likes" page).
* It lets you start building a **navigable** database, as each of the strange page-links (unlike xml tags) can be clicked on & browsed... a 'rose' is it's own entity, as is 'bob'... and they all link to each other in relevant ways.

It doesn't work too well with numerical data types, and I would blanketly recommend **using Jaap's "Journal" plugin for the time dimension** (just put the entries in the correct day's journal page).

Also, I recommend keeping such repos under version control, as there are still a few lingering Zim quirks (and easy operator errors) that might wreck your day.

**Comment by Osndok** [comment]
I probably should have made this explicit, but if you decide to go with page links, then I would recommend (at least initially) that you stick with a basic ```:Type:Name``` & ```:Type:Name:Verb``` reference structure, as in my experience it will save you headaches down the road (compared to deep & elaborate hierarchies of organizational layers & multiple/ambiguous filing locations).

**Comment by theoky** [comment]
Thanks for giving that example with the types and links, @Osndok, That reminds me of TagglyTagging and TiddlyWiki and I was in search of a related approach for Zim. I think I'll try that.

**Comment by KangarooCreativeTeam** [comment]
@ordric - Can you please rename this ticket?;

> Feature Request - General Highlighting for XML Tags

This would be more helpful in the issue queue to easily identify the intent of the ticket. 

Thanks

**Comment by jaap-karssenberg** [comment]
Closing this for now as the top level request does not reflect the discussion. Please open a more crisp request to capture the real question.

Regards,

Jaap
