### ISSUE TITLE
Export text math symbols from Zim to LaTex

### ISSUE THREAD

**Issue by GCamp6** [zim-desktop-wiki/zim-desktop-wiki#497]
I tried to export a Zim page containing arrows (→ as `\rarr` or `-->`,⇒ as `\rArr` or `==>` ) and math symbols (∀ `\forall` , ∃ `\exist`, ∧ `\and`) within the text into LaTex file. These symbols are not exported in a math environment but just copied as they appear and I had to manually change them in the LaTex file adding the `$ $` .
I don't know exactly how this is done but would it be possible to adapt the exporting LaTex function to make the work in automatic?
Where is it placed this function within Zim folders?

PS: It is possible to add the gender (♂, ♀) symbols?

**Comment by theoky** [comment]
If you insert your math symbols, e.g. `\rightarrow` using the LaTex Equation Editor (see Preferences / Plugins / Insert Equation to enable it and Insert / Equation for inserting a LaTex formula), you can export the page for LaTeX. Zim will place your LaTex code within a math environment, e.g.
```
\begin{math}
\rightarrow
\end{math}
```
For gender symbols you probably need to modify the `C:\Users\...\AppData\Roaming\zim\data\zim\templates\plugins\equationeditor.tex ` template file of Zim to include the package wasysym. Then you should be able to use gender symbols (\male, \female) as well. For the export you need to modify the export template accordingly.

Hope that helps.

**Comment by GCamp6** [comment]
It is a bit tangled but probably getting used will help. IMHO it is not very efficient but copy pasting the same symbol can make it more functional.
 
For gender symbols: I modified `data/templates/plugins/equationeditor.tex` (I'm in linux) as suggested but in zim the visualization doesn't work. In the exported tex file they are present and correctly rendered.

Thanks for the tips!
