### ISSUE TITLE
Option: To now show ghost-(grayed out) pages for linked items 

### ISSUE THREAD

**Issue by LeoUfimtsev** [zim-desktop-wiki/zim-desktop-wiki#499]
I use zim for  technical documentation, which often contains ':'

E.g    url.com:port 

This generates a lot of 'gray' ghost pages. I cannot find a way to turn off these ghost pages. 
(is there? I checked all options, plugins and extra plugins I could find).

Could you perhaps add an option to not show them?
(I usually always create links via drag and drop and/or bookmark bar anyway).
(I scanned through the git issues, but couldn't find on like this. Let me know if I missed it).

Or considering I have some gtk-3 development experience, could someone point me in the right direction on how to get started with writing a patch (would someone review?)

Thank you!

**Comment by Osndok** [comment]
There are some regular expressions that govern automatic link conversion, if it is creating page stubs, then it is probably page_re:
* https://github.com/jaap-karssenberg/zim-desktop-wiki/blob/master/zim/gui/pageview.py#L249

I would suggest removing the period from the acceptable characters, but I don't know about the acceptability of such a change (Jaap might want it controlled by a configuration option, for example).

**Comment by jaap-karssenberg** [comment]
Changing the index view for this is a "won't fix" for me. I think the solution is to not link these examples.

Easiest is when you type this expression and you see it turn blue to hit "Ctrl-Z" to undo the auto formatting. Else you can also use the "Remove link" item in the context menu.

See also issue #80

**Comment by LeoUfimtsev** [comment]
Thank you for looking into this issue and linking to #80. 
Good point, disabling automatic linking would be a much better solution than changing the behavior of the index since that's really kinda the core issue.
