### ISSUE TITLE
create a new page without date under the title

### ISSUE THREAD

**Issue by jerome-diver** [zim-desktop-wiki/zim-desktop-wiki#500]
Please, i read all of your doc/manual (much more a doc than a real manual) and i don't find how to just stop to automatically write the actual date under the title of the created page.
Could you please tell me how to disable this feature (i think it is not a obligation who push users to absolutely have it) ?

thank you for your help.

**Comment by krisztianmukli** [comment]
Click Edit/Templates and in the popup window choose the Default template under wiki section. Click the Edit button. The edited template will be similar:
======= [% page.basename %] =======
Created [% strftime("%A %d %B %Y") %]

Just delete the last line and save it, so it should be look like:
======= [% page.basename %] =======

Save it and that all. It won't be delete the date from existed pages. It must be do at manually.

**Comment by jerome-diver** [comment]
@Osndok, thank you i allready looked there, but it was confused to me.
But now, after @krisztianmukli provide some nice precision, now it looks like very clear and also, because of @krisztianmukli answer with example provided, i understand better.
I had also inside this models templates some markdown templates and html templates (default.html doesn't match "Created" word...) and i missed these txt templates.
And also, i read that templates are for export files... and when i create a note in the zim notebook, i was thinking that i used some specific other templates... because it is NOT an export bit a creation.
Lot of way for confusions when you are new, but now ok, i feel better.
Thank you @Osndok to helped me by linked me on the manual i didn't understood.
And thank you very much @krisztianmukli to show me the way to go (you make me understand by practice example, that way help me a lot).

For other one like me who feel loose, i can maybe contribute a little by provide a Unix/Linux command to find these files out of zim application:
``` bash
find ~/ -name "Default.txt" 2>/dev/null
```
it should be inside a home directory who's name include "zim" and "templates".
But i think i saw it also inside the preferencies of application.
I see also there is a way to choose the editor we would like for edit files (it doesn't use the EDITOR env var maybe).
good, i'm happy.
