### ISSUE TITLE
Shortcut for task due on a specific day (enhancement)

### ISSUE THREAD

**Issue by druedin** [zim-desktop-wiki/zim-desktop-wiki#501]
We can mark tasks with two kind of due dates:
A due date is prefixed by a "<": you must complete the task before that date.
A start date is prefixed with ">": you should start the task after that date. 

We can combine the two:
[ ] task <2018-07-29 >2018-07-29

This task will be inactive until it's due.

Request for enhancement: could we have a single prefix, like "<>" for such dates?

**Comment by jaap-karssenberg** [comment]
This is for me a "won't fix" because I can't really see the use case for this. Also the "<>" shortcut seems not right to me.
