### ISSUE TITLE
Plugin Tasks List shows Tags(plugin) in "Task List" view v.068 (windows 10)

### ISSUE THREAD

**Issue by lanmand** [zim-desktop-wiki/zim-desktop-wiki#504]
installed via .exe downloaded from https://zim.glump.net/windows/

**Comment by jaap-karssenberg** [comment]
Sorry, but I have no idea what you try to say here. Could you please explain in more detail?

**Comment by jaap-karssenberg** [comment]
Stale item - please open a new item if same or similar problem is seen in latest version of zim
