### ISSUE TITLE
Web publishing templates - some testing results

### ISSUE THREAD

**Issue by astrogenealogist** [zim-desktop-wiki/zim-desktop-wiki#505]
Hello,
I am quite new at this, but my intentions are good. I have been using Zim to generate a website. My observations are in the attached pdf. They describe behaviors that may be bugs or they may be user errors. 

I am very appreciative of this software. 

Craig Rhombs

[ZimWikiTemplatesTesting.pdf](https://github.com/jaap-karssenberg/zim-desktop-wiki/files/2275060/ZimWikiTemplatesTesting.pdf)

**Comment by ecodiv** [comment]
Hi Craig,

Thanks for testing / commenting on the templates. I have created some of them (the ecodiv ones), but that was a while back and haven't used them recently. I will look into the issues you mentioned to see if I can solve them.  

Cheers,

Paulo

**Comment by jaap-karssenberg** [comment]
Closing report here because the mentioned templates are not in the default distribution.

Regards,

Jaap
