### ISSUE TITLE
Multiple tabs or windows with easy switching

### ISSUE THREAD

**Issue by WinAuthFan** [zim-desktop-wiki/zim-desktop-wiki#511]
In many text editors, you can have multiple tabs that you can easily switch between, using something like Control + Tab. Alternatively, you can have multiple instances of the text editor open and switch between them using Alt + Tab. 

It would be **very** useful for Zim to have a similar functionality: multiple tabs or windows that you can switch between very easily. 

Currently, 
* you can right click on a page in the Index pane, and say "Open in New Window". That opens a read-only version of the page without any Zim functionality.
* you cannot start a second instance of Zim.
* there is the "Go" menu, but it only allows moving between nearby pages, not between arbitrary pages.

**Comment by Osndok** [comment]
Yeah... the pathbar can sorta work as tabs, but I have found that putting links under the 'home' page (which you can always access by clicking the home button) puts them only 2 clicks away.... not as good as one, but far easier to maintain than a custom gui element.

**Comment by jaap-karssenberg** [comment]
Yes there are plans for this. Closing this ticket as it is generic and duplicate.

Regards,

Jaap
