### ISSUE TITLE
Background color for verbatim text in paragraph

### ISSUE THREAD

**Issue by sojusnik** [zim-desktop-wiki/zim-desktop-wiki#512]
Is it currently possible to define the background color of a whole paragraph with verbatim text (see `pre` tag in "Config Files" of Zim's manual) in it?

As far as I can see there is only the `background` property for a tag, which only changes the background color of a word ([example](https://i.imgur.com/agcevJT.png)) and not of the whole paragraph.

Ideally the colored area should have the width of the longest sentence written in verbatim text and not extend till the scroll bar by default.

If not, then such an option would be very useful!

**Comment by Osndok** [comment]
Sure thing!

First, you can set the color in the ```~/.config/zim/style.conf``` by adding an entry/modifying an entry like this that includes your chosen colors:

```
[Tag pre]
foreground=#000000
background=#e8e8e8
indent=10
wrap-mode=GTK_WRAP_NONE
family=monospace
```
(you might only want the color, but I have given examples of some other things you can tweak)

Restart zim, and then you can start/end a block with that color by using three single quotes. You won't be able to see the effect until the page is reloaded (you can hit Ctrl-R, or just rest confident in the fact that it will format itself next time you visit the page).

**Comment by jaap-karssenberg** [comment]
In the example it looks like the region is not continuous formatted with "pre". Might help to check the wiki source. Still it will not look perfect, e.g. line spacing remains. Afraid that cannot be changed as it is how text tags render in the gtk textview. Alternatively the sourceview plugin may give more attractive interface for this.

**Comment by NeoProgramming** [comment]
It is a pity that this problem cannot be solved in a simple way. I also wanted to open issue about paragraph background color for a verbatim/code blocks.
