### ISSUE TITLE
Windows installer link not working

### ISSUE THREAD

**Issue by bzupp** [zim-desktop-wiki/zim-desktop-wiki#514]
Hi, 

The windows installer link:

https://zim.glump.net/windows/

has been broken for a while I believe. Any alternative windows installer sites?

I LOVE ZIM DESKTOP WIKI! I use it on a Linux Mint as well as windows. 

**Cheers!**
Brent

**Comment by krisztianmukli** [comment]
The links works for me. Otherwise, you can use this way for installing Zim from source: https://github.com/jaap-karssenberg/zim-wiki/wiki/Install-the-full-Zim-Desktop-Wiki-Suite-on-Windows

**Comment by jaap-karssenberg** [comment]
Link works correctly now as far as I can see
