### ISSUE TITLE
Plugins not working on win 10

### ISSUE THREAD

**Issue by byebyebyebye** [zim-desktop-wiki/zim-desktop-wiki#518]
Hi guys, I'm trying to install some plugins (a language translation and instant search). I copy plugins into plugins folder... nothing happens I can't see them!
I'm under windows 10
ty

**Comment by byebyebyebye** [comment]
Yes it is. But plugins does not work

**Comment by muguu** [comment]
You need to create and copy the plugins to the %appdata% folder into following folder structure:
%appdata%\zim\data\zim\plugins\

**Comment by byebyebyebye** [comment]
I did!! That is btw the folder that zim opens when I click "open plugins folder" under preferences.
I put .yo files inside, I run zim and nothing happens. Plugins aren't in the plugins list.
A .pyo appears.
Thank you

**Comment by jaap-karssenberg** [comment]
If "pyo" appears zim is trying to load the plugins, but apparently hits an error in the plugin code while loading. The error log may provide more info.

Closing here as these are not default plugins.
