### ISSUE TITLE
Zim-wiki cannot work with symlink ?

### ISSUE THREAD

**Issue by Nick222** [zim-desktop-wiki/zim-desktop-wiki#520]
Xubuntu 18.04 Zim 0.68

I start Zim-wiki and create one page in it.
Then I move it to another folder and in old folder create symlink on this file.
When then I open my Zim-notebook, I see this moved page (by it`s symlink).
But when I change this page and then save my Zim-notebook, this symlink overwrites by new variant of my page. And in file manager I can see changed page in my Zim-notebook folder and source page in another folder.

How can I use symlinks in Zim-wiki-notebooks correctly?

**Comment by Angular-Angel** [comment]
I, too, would greatly appreciate the ability to use symlinks. I have lots of pages that I would like to show up in multiple places in the file tree, and text links are insufficient.

**Comment by jaap-karssenberg** [comment]
Zim cannot deal with symlinks to files because of the way it is implemented for writing files. We first write a temporary file and then rename it in order to make the write "atomic". 

You can use symlink'ed folders though.

**Comment by Angular-Angel** [comment]
Would it be possible to make it work with symlinks? This would be super useful to me. I know I can get much the same functionality with regular links, but then they don't show up on the sidebar.

**Comment by Xunius** [comment]
I stumbled on this when trying to integrate the software I'm developing with vim, and I was assuming that by using symlinks I could make the same note appear multiple places so they are "synced" in a way. And I was also faced with the same difficulty as Angular-Angel that using zim links doesn't make the note appear in the sidebar.

**Comment by Xunius** [comment]
Would this fix work? 

In `AtomicWriteContent.__exit__()`:
Replace
```
_replace_file(self.tmppath, self.path)
```
with
```
_replace_file(self.tmppath, os.path.realpath(self.path))
```

**Comment by jaap-karssenberg** [comment]
No that goes wrong when you move across mount points and also can lead to
unexpected behavior.

As stated in other threads support of symlinks will be restricted to
folders.

Organizing files in alternative hierarchies will need a different approach
than linking. E.g. tags support this kind of organization.

Regards,

Jaap

Op za 18 mei 2019 05:29 schreef Xunius <notifications@github.com>:

**Comment by Xunius** [comment]
So why not using `shutil.remove` instead of `os.rename`, that get you across mounts.

**Comment by jaap-karssenberg** [comment]
Sorry but I did not mean to say that there is no technical solution
possible. However I feel that the filesystem layer is not the right place
for the complexity of aliases (which is what symlinks effectively are). To
have a page appear in multiple places you should look towards links and
tags within the application.

I simply do not intend to support file symlinks as I see no good use case
for a desktop application using those.

Kind regards,

Jaap

Op za 18 mei 2019 11:02 schreef Xunius <notifications@github.com>:
