### ISSUE TITLE
Copying text formatted as verbatim copies nbsp instead of spaces

### ISSUE THREAD

**Issue by alexivkin** [zim-desktop-wiki/zim-desktop-wiki#521]
I use "verbatim" to highlight code in Zim. When selecting text that was formatted as "verbatim" and copy/pasting it to a linux console, the spaces come as the Unicode Character 'NO-BREAK SPACE' (00A0), not the normal 0x20, which screws up all the scripts. Reminds me of the horrible way Word copies a unicode long dash.

Could we please change the behavior back to a normal space?

**Comment by jaap-karssenberg** [comment]
Can't reproduce here. Also the behavior you describe is not implemented in zim itself, so could be due to the specific Gtk version or something else in your environment. Can you add specific that might help pinpointing the cause?

**Comment by alexivkin** [comment]
Looking at the hexdump of the notebook text files I can see that they do store "U+C2A0", instead of "U+0020" for the spaces inside two single quote ''...'' text.
So I suspect that the reason it works for you is because something in your system does the conversion normal spaces, where is mine just copies them straight. 
This is likely be broken on all other systems that does not do that copy/paste filtering.

To reproduce, try running zim on KDE and pasting verbatim formatted line with spaces into konsole. It wlll **appear** that there are spaces, but when you try to run it shell will treat the line as if it does not have spaces

**Comment by jaap-karssenberg** [comment]
Is it possible that the source from which you copied into zim already
contained the non breaking characters?

**Comment by alexivkin** [comment]
You are right, I've created a new file and the spaces were normal. I use the pandoc zimwiki converter that's probably to blame. 

The bad news is that I am also the author of that converter ;) - https://github.com/jgm/pandoc/blob/37a82b0b11b0214f00cdcd232e33c0a1e9f79361/src/Text/Pandoc/Writers/ZimWiki.hs 

You can close this issue.

**Comment by jaap-karssenberg** [comment]
might be good to check for this in zim paste and text conversion functions
as well
