### ISSUE TITLE
Format chinese string  with Strong is not show

### ISSUE THREAD

**Issue by renzuo** [zim-desktop-wiki/zim-desktop-wiki#525]
Bold Chinese does not show in edit, but English and numbers are all right.
version: Zim 0.68

I remember old version is no problem, but forgot which one

**Comment by jaap-karssenberg** [comment]
Tested with some unicode examples, but cannot reproduce. Do you have some test data that shows the issue?

**Comment by renzuo** [comment]
It's worked now by update
