### ISSUE TITLE
Turn Word Into Web Link Through Shortcut

### ISSUE THREAD

**Issue by DvP17** [zim-desktop-wiki/zim-desktop-wiki#526]
I really love Zim, what a great and also simple tool at once! Thank you very much for creating this!

I only have had some idea: How about making copying of links a little bit faster? I am copying a lot of links and it bothers me a little bit to always click ctrl+L and then insert my link and the corresponding text for this link.

How about writing a word and entering a shortcut right behind that word like ctrl+shift+V (link address is in RAM) and the word turns into the link? Would be really great!

Best regards!

**Comment by Osndok** [comment]
Have you considered using the wikitext method, either:
* type '[[', paste your link, ']]', or
* type '[[', paste your link, '|', type link-text, ']]'

...you can just hit ctrl-r to reload the page & see the links.

**Comment by DvP17** [comment]
No, I have not discovered this solution yet. Thank you very much! 

However, when I use this solution I must type even more than if I use the shortcut ctrl+L. This is why I suggested a more faster way of inserting links.

**Comment by krisztianmukli** [comment]
Use CamelCase words! It will be links automatically!
Use with following signs:
* Links containing a '/' are considered links to external files
* Links that start with a ':' are resolved from the top level of the notebook
* Links that start with a '+' are resolved as sub-pages below the current page
* Links that contain a '?' are interwiki links, see help.
* All other links are resolved within the path from the root to the current page

**Comment by DvP17** [comment]
Thank you Krisztian! I know how to use CamelCase words. This was not, I was looking for. 
I had an idea how to implement weblinks faster.

**Comment by jaap-karssenberg** [comment]
URLs are always recognized, but you may need to reload the page to see it.
