### ISSUE TITLE
TaskList plugin does not update list of tags

### ISSUE THREAD

**Issue by kevin77v** [zim-desktop-wiki/zim-desktop-wiki#533]
Previously, the TaskList plugin would update tags as I added them in pages.  Now, nothing I do updates the list of tags in the TaskList.  Either typing new tags in a page, nor updating the index.  Though, I can see them all in the "Tags" tab in the sidebar.

When loading the TaskList, I see the following text in the debugging output:

```
WARNING: /usr/lib/python2.7/site-packages/zim/plugins/__init__.py:815: GtkWarning: IA__gtk_container_remove: assertion 'GTK_IS_TOOLBAR (container) || widget->parent == GTK_WIDGET (container)' failed
  self.window.action_area.remove(b)
```

When I type a new tag in a page, I see the following error messages:
```
WARNING: /usr/lib/python2.7/site-packages/zim/gui/pageindex.py:390: GtkWarning: gtk_tree_view_unref_tree_helper: assertion 'node != NULL' failed
  BrowserTreeView.set_model(self, model)
```

While clicking around various entries in the TaskList, I see this:
```
WARNING: /usr/lib/python2.7/site-packages/zim/main/__init__.py:708: GtkWarning: gtktreeview.c:6075 (validate_visible_area): assertion `has_next' failed.
There is a disparity between the internal view of the GtkTreeView,
and the GtkTreeModel.  This generally means that the model has changed
without letting the view know.  Any display from now on is likely to
be incorrect.
```

I'm using Zim 0.68-1 on Manjaro/Arch Linux 
Kernel: 4.14.69-1-MANJARO x86_64 bits: 64 Desktop: i3 4.15.0.1 
pygtk 2.24.0-8
Python version being referred to above is python2 2.7.15-2.
I have python 3.7.0-3 but it seems zim or the TaskList plugin points to 2.7?  Not sure if that matters.

Not sure if this is an error in Zim or in the Manjaro/Arch system I have.
Let me know if there's any more info that would be helpful.

**Comment by kevin77v** [comment]
Some more errors as I closed the application:
```
WARNING: /usr/lib/python2.7/site-packages/zim/plugins/__init__.py:783: GtkWarning: IA__gtk_ui_manager_remove_action_group: assertion 'g_list_find (self->private_data->action_groups, action_group) != NULL' failed
  self.window.uimanager.remove_action_group(self.actiongroup)

```
```
WARNING: /usr/lib/python2.7/site-packages/zim/gui/__init__.py:1901: GtkWarning: IA__gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed
  gtk.main_iteration(block=False)
```

**Comment by kevin77v** [comment]
Some further notes, the task list shows a partial list of the tags.  I've checked the tag list in the index databalse file and they are all there.  It would seem that TaskList is failing the middle of parsing the database?   Perhaps due to gtk errors above which seem similar to another recent bug report about gtk.

**Comment by jaap-karssenberg** [comment]
Have not observed this behavior myself. Do you have some test data that is sure to reproduce? If not, could you re-test with zim 0.70 or newer?

Thanks,

Jaap

**Comment by jaap-karssenberg** [comment]
Stale item - please open a new item if same or similar problem is seen in latest version of zim
