### ISSUE TITLE
Crash on past of certain text in Kubuntu

### ISSUE THREAD

**Issue by prairietree** [zim-desktop-wiki/zim-desktop-wiki#535]
Hello

I just installed Zim. After reading some reviews and comparing some similar alternative, I thought it looked like what I needed. After making a simple todo list and trying a few other things I decided to copy in some server logs and start using it for some real stuff. However, it crashed whenever I try to past that file in. After playing around I figured out that it was the fallowing line and another similar one that was making it crash. 

`│ https://www.ssllabs.com/ssltest/analyze.html?d=www.dynu.com      │  `

I am using Zim 0.68 installed form the zim_0.68_all.deb package downloaded about two days ago.

I am running it on Kubuntu 16.04.

In /tmp/zim-user/zim.log all it says is:

WARNING: Using gtkspellcheck 3.0. Versions before 4.0.3 might cause memory leak.
WARNING: Invalid config value for toggle_panes: "['left_pane']" - Unknown pane names in: ['left_pane']

Any suggestions?

Thanks

**Comment by jaap-karssenberg** [comment]
Could you run zim for a terminal with "zim --debug" and add the exact error message? (The warnings in the log are not related.) 

Thanks,

Jaap

**Comment by prairietree** [comment]
I am sorry, I have not been unable to make it crash again. I do not think I updated it since when I originally installed it, so it may be that I changed some configurations or the original text file.

**Comment by jaap-karssenberg** [comment]
Stale item - please open a new item if same or similar problem is seen in latest version of zim
