### ISSUE TITLE
Find and Replace keyboard shortcut doesn't work on mac

### ISSUE THREAD

**Issue by charlierlee** [zim-desktop-wiki/zim-desktop-wiki#538]
I can't figure out how to get the Find and Replace window up using a keyboard shortcut on a mac. Please help.

**Comment by jaap-karssenberg** [comment]
The default key binding is Ctrl-H - what happens in your case?

**Comment by jaap-karssenberg** [comment]
Stale item - please open a new item if same or similar problem is seen in latest version of zim
