### ISSUE TITLE
Incompatible with Orca Screen reader

### ISSUE THREAD

**Issue by accessibility-bug-reports** [zim-desktop-wiki/zim-desktop-wiki#542]
##The Problem
When focus is moved to Zim, Orca's keyboard shortcuts do not perform their assigned actions, and they simply enter the text of the keyboard shortcut, e.g. caps + / enters a slash. 

##Expected behavior
Since Orca uses caps lock as its modifier key and as far as I know Zim doesn't, the screen reader keyboard shortcuts should function as they are mapped even when in Zim. 

##Potential fix
Orca has a mode for "pass the next command to the application you're in" so perhaps that could be used to switch between entering text and and using a keyboard shortcut. There may be another way, because Orca is working fine with Firefox, and I'm not using that shortcut, I'm just typing.

##Potentially relevant information
OS: Manjaro Linux, up to date
Zim version: 0.68
Desktop environment: KDE 5
Orca version: 3.28.1-2

**Comment by jaap-karssenberg** [comment]
Please re-test with zim 0.70 or newer

**Comment by jaap-karssenberg** [comment]
Needs testing in newer releases. Without activity will move to close this issue.
