### ISSUE TITLE
Export does not work in ubuntu 18.04

### ISSUE THREAD

**Issue by AakeJon49** [zim-desktop-wiki/zim-desktop-wiki#543]
I have used export before but after upgrade to Ubuntu 18.04 it doesn't work anymore. I get a html page but the only thing that appear is a link to table  of content that doesn't work.

![selection_099](https://user-images.githubusercontent.com/38993117/46558959-1a5f6b00-c8ef-11e8-8ef8-3bdd57d2cea8.jpg)

**Comment by jaap-karssenberg** [comment]
Pleas run zim with "--debug" and include relevant output here

**Comment by AakeJon49** [comment]
Sorry for late answer. I must have made something. When I tested just now It seems to work.
Maybe with some minor defects, but I have to do a more serious investigation.
For now you can mute this thread. I'll be back if I find anything new.
Thank You for the reply and for a very useful notebook!!!

**Comment by AakeJon49** [comment]
The Export function works.
