### ISSUE TITLE
Source View/gtksourecview style selection

### ISSUE THREAD

**Issue by machin3io** [zim-desktop-wiki/zim-desktop-wiki#544]
I'm looking for a way to set the style used by the Source View plugin. 

There are a few different ones in /usr/share/gtksourceview-2.0/styles and more can be found onlines. 

I'm just not sure how to tell zim/Source View which one to use. I'd appreciate any pointers, thanks.

**Comment by jaap-karssenberg** [comment]
This would require patch of the plugin to add style selection to the preferences.

Since there are custom widget for this, will require overloading the default plugin preferences dialog.

**Comment by shermanbowling** [comment]
I'd like to second this feature request. As it stands, I can't read dark blue code comments with my dark gtk theme, and the selected syntax colors are all around fugly.
