### ISSUE TITLE
Pages Not Showing on Sync'd Notebooks

### ISSUE THREAD

**Issue by mike1777** [zim-desktop-wiki/zim-desktop-wiki#545]
I am using Zim on two computers while using Syncthing to synchronize files between the two.  My Zim notebooks are stored in folders that are being sync'd.  For the most part, things work fine and I can see notebooks one one computer that have been created on the other.  However, in some instances, pages from one of the notebooks may not show up in Zim, even when the associated text files and folders are present on the device.

**Comment by jaap-karssenberg** [comment]
Try re-building the index, or click "Tools --> Update Index". The indexer checks timestamps of files and folders to find updates.

**Comment by michaelpradel** [comment]
I'm having the same problem, and re-building the index via "Tools --> Update Index" doesn't help. What helps, though, is to force an index update with "zim --index -V /path/to/notebook", as suggested in https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/697.

Further information that may help debug the problem: I'm using zim 0.70. The file system timestamps of the added files that aren't visible in zim are younger than the last time zim was running (and hence, the index may have been build).

Please let me know if there's additional information I can provide. Being a heavy user of both zim and synchronizing files between machines, I'd love to see this issue fixed.

**Comment by aNDy-Squirrel** [comment]
I have the same problem under Zim 0.72.0,  "Tools --> Update Index" doesn't recognise a file change done at a mirror and synced to the local machine, the change is not propagated to the page. Strangely, switching to another page, and then switching back apparently re-reads the file and updates the page (and loses all changes without warning!).
