### ISSUE TITLE
Feature request: Interface for git integration

### ISSUE THREAD

**Issue by frankenstein91** [zim-desktop-wiki/zim-desktop-wiki#547]
We are using Git for Wiki-Management in our Team.
It would be really nice if there would be an interface which can be used to do pull / push / commits.
Getting updates and making updates would more easier for us.

It would be nice if this feature would be considered.

**Comment by jaap-karssenberg** [comment]
Have you looked at the "custom tools" feature in the "tools" menu? THis should make it relatively easy to add your own scripts that match your way of working.

**Comment by jaap-karssenberg** [comment]
Closing as "won't fix" because I believe there are many good tools for this already that can be used as a "custom tool" in zim. Re-writing such functions in zim is unnecessary complexity.
