### ISSUE TITLE
Slow Source View plugin

### ISSUE THREAD

**Issue by mke21** [zim-desktop-wiki/zim-desktop-wiki#548]
On my Ubuntu 16.04 installation, pages containing a source view hang when opened. The cursor cannot be moved and the syntax highlighting doesn't work. Usually after a while, seconds to minutes it suddenly reacts and everything works again. If I then open another page that includes a source view, it stops working again and show the behaviour that I described again.
I use ZIM 0.68 on said Ubuntu 16.04.
The same notebook synced to Windows works perfectly on ZIM under that OS. 
It's probably something with my system, but I have now clue how to find the problem. I did reinstall python-gtksourceview2   and tried to reinstall zim. Doesn't help. Any clue how to debug this?

**Comment by mke21** [comment]
Yeah, that seems to be the case. Strange that it did work before on Kubuntu, So how do I change this option over all my  (a few hundreds)? Do I have to do sed on that?

**Comment by Self-Perfection** [comment]
I used to fix notes with something like this:
`find "$NOTEBOOK_DIR" -name '*.txt' -exec sed -i 's/^{{{code: lang="\(.*\)" linenumbers="true"$/{{{code: lang="\1" linenumbers="false"/' {} +`

**Comment by jaap-karssenberg** [comment]
Closing because I believe this to be fixed in 0.70. See #296
