### ISSUE TITLE
Zim 0.68 in Windows 10 1803 cannot remember last window position

### ISSUE THREAD

**Issue by IanGoo** [zim-desktop-wiki/zim-desktop-wiki#551]
Everytime I close Zim and reopen it, it can remember the window size, but not the position. The window will always appear in the up left corner of the left screen(I have two monitors connected).
Even if I closed Zim with the window maximized on the right screen, it will still appear on the left screen when I reopen it.

**Comment by IanGoo** [comment]
Well I tried it in Linux (Manjaro Latest Stable Release), this problem also happened...

**Comment by Osndok** [comment]
AFAIK, in Linux... it is usually up to the **window manager** to place/position windows.

**Comment by IanGoo** [comment]
I'm using Xfce4, the window manager is xfwm4. But it cannot explain why this happens in Windows.

**Comment by pdwilso** [comment]
It's been a few years, but iirc window position on application start up
under Windows was read (in older versions going back to 3.1) from an .INI
file, then later from the registry.

Under Linux (X11) window managers, the initialization files have *rc type
names and are hidden in user home directory or in a, .config directory.

Some X11 window managers also have a registry type arrangement which i am
not familiar with.

I'm not sure which init/config arrangement Zim uses under X11.

Finally: many X11 systems and probably windows, too, have a window manager
setting to either always open a new window in the same spot or to save the
last position of a window, and re- place it there.

Initial Window size should also be configurable alongside position.

Hth
