### ISSUE TITLE
Resizing fails on MacOS Sierra

### ISSUE THREAD

**Issue by skyblue002** [zim-desktop-wiki/zim-desktop-wiki#552]
I installed the prerequisites using home-brew. I followed the directions from other bugs listed and instead of just running `zim.py`, I ran `setup.py build` first. This kept zim from crashing (which it had been doing), but the resizing is still really problematic. There is a long time gap when resizing using the bottom right corner of the window. Sometimes, it won't resize at all, then after trying another corner, it'll snap into a tiny window where no text is visible. The only errors I get are these and they are on load, not when this problem with resizing occurs:

`WARNING: Can not import 'xdg.Mime' - falling back to 'mimetypes'`
`WARNING: Can not import 'xdg.Mime' - falling back to 'mimetypes'`

Because of this extreme issue with responsiveness, I'm worried that it's not stable and may end up losing my data. (The startup time is also extremely slow — much more so than what I remember when I was running Linux and using zim.)

If you need more information, just let me know. (And, please let me know how to gather it for you.)

Here is some additional information that you might find useful:

**MacOS**: Sierra 10.12.6
**Python**: 2.7.15 (installed through homebrew)

**gtk-mac-integration** installed through homebrew
**pyxdg** installed through pip as specified on the installation page

**Comment by jaap-karssenberg** [comment]
Afraid this is not in zim itself but probably in the Gtk toolkit, so can't fix it. Best bet is to re-test with zim 0.70 or newer which switches to newer Gtk toolkit.

Data is always stored as text files. So even if zim breaks the data is still there.
