### ISSUE TITLE
Editing a link also renames the link's name when both are identical

### ISSUE THREAD

**Issue by sojusnik** [zim-desktop-wiki/zim-desktop-wiki#555]
1. Create `Planets:Earth` and `Planets:Venus`
2. In `Planets:Venus` write `Earth` (if you'll write something else, then you won't be able to reproduce this bug), select this text, open the link menu and write `Earth` in the "link to" field, apply
3. Edit this link again. When you'll edit the "link to" field, then you'll see that the name of the link will change simultaneously. This only happens when both field are identical.

This behavior is very annoying, since you normally don't want to change the name of the link, but only the link itself.

Happens with Zim 0.68 on Ubuntu 18.10.

**Comment by jaap-karssenberg** [comment]
Afraid this is a feature since many users actually want to change the link and the name at the same time.
