### ISSUE TITLE
Tags in headings

### ISSUE THREAD

**Issue by fmos** [zim-desktop-wiki/zim-desktop-wiki#556]
The tag syntax (@ prefix) does not work when used in headings.

I use zim pages for tracking projects of a limited number of types, where the type and project stage is mapped to headings on each page. Presently I use additional tags to quickly find and refer to similar, earlier activities in other projects.

If tags could be used in headings, not only would this make the above workflow more efficient, but it would also allow to jump to those tags via the ToC-plugin's view. 

The (orange) coloring of tags could be applied in headings as well, while the font would otherwise be maintained according to the heading level.

As this would presumably be a core feature, I would like to know if this would have a chance to get merged, if I were to provide a pull request. What do you think @jaap-karssenberg ?

**Comment by jaap-karssenberg** [comment]
I think is a good suggestion, but requires quite some code changes. Good to take along in #305

**Comment by jaap-karssenberg** [comment]
Fix merged in develop as commit 52554cc7e610000b3e1777b46367487f23692e7a
