### ISSUE TITLE
macOS Menubar: ctrl+v/pasting a URL in link dialog misdirected

### ISSUE THREAD

**Issue by reagle** [zim-desktop-wiki/zim-desktop-wiki#560]
Encountered using Zim 0.68 on MacOS HighSierra using macOS Menubar plugin via gtk-mac-integration 2.0.7 brew.

If the link dialog is open and I paste a URL in the "Link to:" field via ctrl+v the URL is pasted into the document behind the dialog rather than the dialog itself.

Disabling the macOS Menubar plugin restores proper behavior.

**Comment by jaap-karssenberg** [comment]
Closing as this plugin is removed in zim 0.70
