### ISSUE TITLE
Keep formatting when copying wiki page to clipboard

### ISSUE THREAD

**Issue by sh2ka** [zim-desktop-wiki/zim-desktop-wiki#561]
For pasting as text it can be copied as wiki markup.
For pasting as rich text it can be copied as rendered page.

Now the selection of the zim page snippet with indentation doesn't select Tabs and when I paste that text into any text editor I lose indents.

**Comment by sh2ka** [comment]
I tried to use "Print to Browser" function, but it shows an expected result - there is no formatting in verbatim block.
The same can be found in source of the wiki page:

```
'''
package:
'''
	'''
	name
	version
	source:
	'''
	'''
	git_url
	git_tag
	sha256
	url
	git_rev
	fn
	md5
	patches
	sha1
	path
	build:
	'''
```

but should be something like that I guess:
```
'''
package:
'''
	'''
	name
	version
source:
'''
	'''
	git_url
	git_tag
	sha256
	url
	git_rev
	fn
	md5
	patches
	sha1
	path
build:
'''
	...
```
Note that the problem relates to a Verbatim formatted fragment. Numbered and bulleted lists work well, but still indentations (Tab characters) can't selected and I can't move cursor to the line beginning. I think that such a behavior should be optional.

**Comment by jaap-karssenberg** [comment]
Afraid your description is a bit to cryptic for me to understand the exact issue. Can you explain step by step what you do and what goes wrong?

**Comment by sh2ka** [comment]
I tried to explain that text lines in preformatted block don't contain tab characters. Now I can't reproduce that behaviour.

**Comment by jaap-karssenberg** [comment]
Stale item - please open a new item if same or similar problem is seen in latest version of zim
