### ISSUE TITLE
zim crashes upon start when system-wide version of Python is 3.6

### ISSUE THREAD

**Issue by bytinbit** [zim-desktop-wiki/zim-desktop-wiki#562]
I recently upgraded from Linux Mint 16 (Ubuntu 16.04) to Linux Mint Tara (Ubuntu 18.04). I switched the python version for the whole system to 3.6, along 2.7 that is still installed.

When the system uses version 3.6, zim does not start and crashes immediately upon start with the following error message:

```
Traceback (most recent call last):
  File "/usr/bin/zim", line 15, in <module>
    assert version_info < (3, 0)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/zim", line 17, in <module>
    print >> sys.stderr, 'ERROR: zim needs python >= 2.6   (but < 3.0)'
TypeError: unsupported operand type(s) for >>: 'builtin_function_or_method' and '_io.TextIOWrapper'. Did you mean "print(<message>, file=<output_stream>)"?
```
However, when I switch the system version to 2.7, zim starts and works.

**Comment by Self-Perfection** [comment]
Looks like a bug that should be posted to your Linux dsitribution bugtracker. Zim is still being ported to python3. Your distribution package maintainer should have packaged zim in a way that it explicitly runs via `python2`, rather than plain `python`.

**Comment by jaap-karssenberg** [comment]
Distribution issue we cannot solve from zim. The good news is that starting with 0.70 zim is ported to python3.
