### ISSUE TITLE
svg attachments crash (segfault) Fedora 29 Linux (Zim 0.68) -- solution here

### ISSUE THREAD

**Issue by BehindTheBrain** [zim-desktop-wiki/zim-desktop-wiki#563]
svg attachments crash Zim, even when the are not displayed as images in the page.

The fix is already noted in the code (from Windows):

In /usr/lib/python2.7/site-packages/zim/plugins/attachmentbrowser/thumbnailer.py
line 29: -- change it to this:
 or (file.basename.endswith('.svg')):

**Comment by jaap-karssenberg** [comment]
Need at least an option for this

**Comment by jaap-karssenberg** [comment]
Dev notes:
  * Add option to thumbnail svg, default off
  * Re-test svg support on windows with Gtk3 under msys
