### ISSUE TITLE
Text is ridiculously tiny

### ISSUE THREAD

**Issue by Denise51781** [zim-desktop-wiki/zim-desktop-wiki#566]
I understand simplicity, and I appreciate it. However, I consider the extremely tiny text in Zim to be a serious flaw. Aging eyes cannot read text designed for an ant. I can read a sentence or two, but it is useless for anything more extensive.

**Comment by Osndok** [comment]
I imagine that you might have a hi-dpi display... are there any other apps with super-tiny text and/or controls?

Otherwise, have you tried the 'zoom in' option from the view menu? (ctrl-plus)

**Comment by vatterspun** [comment]
![image](https://user-images.githubusercontent.com/1289134/48983314-d39e1e00-f0b2-11e8-8afd-d65f1782ffe6.png)

**Comment by Denise51781** [comment]
Honestly, do you think that you can just dismiss such a serious usability issue so simply? My eyes are in pretty good shape and I am having trouble. My 22-year-old godson said that it was too small. How many people will not be able to see it at all? Usability comes before features. It is standard procedure to have at least a simple way to permanently make the text readable. It does not have to be complicated. Just a simple small-medium-large setting (as long as large is no smaller than 12 pt) will suffice.


Yvonne (Denise) Roche

denise@deniseroche.net


________________________________

**Comment by vatterspun** [comment]
> do you think that you can just dismiss such a serious usability issue so simply

I thought we were addressing it, not dismissing it.  Does the zoom feature not fix that?  If the default seems absurd, it may be that you have a high resolution monitor, where the program's text will seem very, very small.  On my low resolution, older machine for example, the default text looks fine so it's not a question of absurdity but being backwards-compatible.

**Comment by Denise51781** [comment]
I don't think you understand. I was testing this program out. I do not find it useful because of this issue. Like most people, I will not take it any further. I uninstalled it. If you want the program to be used then you have to make it so that people will want to use it. Most people would do as I did: take one look and uninstall it. I happened to be nice enough to tell you why. Most people would not bother.


Yvonne (Denise) Roche

denise@deniseroche.net


________________________________

**Comment by Osndok** [comment]
@Denise51781 ; Thank you for your bug report, it will be valued particularly if we find that anyone else experiences the same issue.

As a point of fact, most people do not have this "tiny text" issue, and it is unclear what is causing it (zim does not intentionally make its text small).

If you could provide details about your operating system and hardware, that might help.

However, if you decide to give up, we understand and wish you the best, and are even sorry to see you go, that you did not find immediately and freely benefit from all the hard work put into zim over many years.
