### ISSUE TITLE
Blue highlight on black text (Windows version)

### ISSUE THREAD

**Issue by vatterspun** [zim-desktop-wiki/zim-desktop-wiki#568]
**Setup**: Win7x86, Zim 0.68

**Issue**: Difficult to read menu items.  See screenshot.

![2018-11-25 12_59_22-notebooks - zim](https://user-images.githubusercontent.com/1289134/48983268-3ba03480-f0b2-11e8-9e35-003fe9d0454a.png)

**Expected results:** White text (as with LibreOffice menu below):

![image](https://user-images.githubusercontent.com/1289134/48983274-4fe43180-f0b2-11e8-950f-a114c4d38097.png)

**Comment by jaap-karssenberg** [comment]
Afraid this is in the Gtk theming, not zim itself, so can't fix that.

Next release will be Gtk3 based, hope that changes it.
