### ISSUE TITLE
zim crashes with two notebooks opened

### ISSUE THREAD

**Issue by Disasm** [zim-desktop-wiki/zim-desktop-wiki#569]
Zim version: 0.68 (package version: 0.68-1)
OS: ArchLinux Rolling Release
Python version: 2.7.15 (package version: 2.7.15-2)

Steps to reproduce:
* Launch zim, it will open "main" notebook
* Open another notebook (File->Open Another Notebook...)
* Make some changes to the second notebook
* Save (Ctrl+S)
* Observe crash (with small probability)
* Launch zim again
* Observe significant delay (~20s) before zim window will appear

I synchronize second notebook with ownCloud, if it somehow related. First, "main" notebook is local.
When I opened the second notebook and closed the first, crash never happened.

Console output on crash is as simple as "[1]    2174 segmentation fault (core dumped)  zim"
Despite this bug is hard to reproduce, it happens every day I use both notebooks, often multiple times per day. It's very annoying.

**Comment by jaap-karssenberg** [comment]
Maybe additional debug output (zim --debug) could help pinpointing this issue. But in general segmentation faults are not caused by zim itself, but by one of the libraries we depend on, so may be hard to solve.

**Comment by Disasm** [comment]
I haven't experienced this problem for a ~month, so maybe we can close this issue.

**Comment by jaap-karssenberg** [comment]
Thanks for checking!
