### ISSUE TITLE
Include text editor in flatpak

### ISSUE THREAD

**Issue by robertvazan** [zim-desktop-wiki/zim-desktop-wiki#574]
Zim relies on external editor for editing templates. Until there is a dedicated UI for this, it would be useful to package some GUI editor in the flatpak package. The same goes for common attachment formats.

It would make sense for flatpak to have an ability to launch other apps. I don't know of any project to implement this in flatpak. Meantime, it makes sense to package all helper apps in the flatpak the same way libraries are packaged.

**Comment by jaap-karssenberg** [comment]
Afraid I do not handle flatpack packaging myself so will close this report here. Please report towards packager.

**Comment by robertvazan** [comment]
Opened [new issue](https://github.com/flathub/org.zim_wiki.Zim/issues/5) for the flatpak package.
