### ISSUE TITLE
Zim.exe not starting -- "unsupported locale setting" Windows10 Home, Version 1809, Build 17763.194

### ISSUE THREAD

**Issue by kstrieder** [zim-desktop-wiki/zim-desktop-wiki#580]
Zim.exe doesn't show any activity and closes immediately after launch.
Manually starting Zim.exe from within Powershell: same result - no output.

First observed after update to 17763.194

Machine: Microsoft Surface GO

From the Zim Debug file:
Traceback (most recent call last):
  File "zim.py", line 42, in <module>
  File "zim\__init__.pyo", line 147, in <module>
  File "locale.pyo", line 581, in setlocale
locale.Error: unsupported locale setting

**Comment by kstrieder** [comment]
Interesting: other machine with Windows version 1803, build 17134.471 works like a charm.

Both systems are on locale en-GB (LCID 2057)
PS > Get-WinSystemLocale

LCID             Name             DisplayName
----             ----             -----------
2057             en-GB            English (United Kingdom)

**Comment by Olaf987** [comment]
Dear all:

I just experienced the same thing last night. ZIM 0.68 has problens with win 10 pro 1809. All systems with 1803 work fine. I noticed 2 things:

1. Zim tries to write an error log in the program directory were zim is installed. Windows does not allow that.
2. When you change the rights to the folder, the error log displays the locale error.

I did not have time to investigate further last night but I fear the problem might go deeper than just the few things we have seen here. The current build chain may not have been designed for windows 1809 or it may just be another set of bugs in 1809. So I expect we will see perhaps more programs failing than just ZIM.

**Comment by kstrieder** [comment]
Todays Windows update with OS build 17763.195 - v1809

No change, still same error message in debug with Zim 0.68
Traceback (most recent call last):
  File "zim.py", line 42, in <module>
  File "zim\__init__.pyo", line 147, in <module>
  File "locale.pyo", line 581, in setlocale
locale.Error: unsupported locale setting

**Comment by Tomvish** [comment]
Да, тоже самое на 4.18.16-arch1-1-ARCH
$ zim
Traceback (most recent call last):
  File "/usr/bin/zim", line 42, in <module>
    import zim
  File "/usr/lib/python2.7/site-packages/zim/__init__.py", line 147, in <module>
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

**Comment by sempiterna** [comment]
I'm also no longer able to start Zim after the last forced Windows 10 update. I'm currently on 10.0.17763.

**Comment by Osndok** [comment]
I got this error in Fedora 29 (linux) with the KDE desktop environment.

For me, launching zim in this way works around the issue:
```
LC_ALL=C zim
```

...which is roughly equivalent to:
```
export LC_ALL=C
zim
```

I know that Windows also has environment variables, but that they are a bit more obscure... so maybe this will help the windows users too?
