### ISSUE TITLE
Header loose formating when indented

### ISSUE THREAD

**Issue by SemperRoto** [zim-desktop-wiki/zim-desktop-wiki#581]
Whenever I indent a header **ctrl+ 1-5** (german translation) I loose the formatting when returning to the file.

So from:
_tab stop_ **HEADLINE**

I get:
 _tab stop_ ==== HEADLINE ====

It is also not possible to indent a Line when it is already formatted as header. It is possible to have tabstops within a formatted header.

Using Windows 10 and Zim 0.68

**Comment by jaap-karssenberg** [comment]
Will fix by ensuring headings are never indented - this is how the wiki format expects them.

**Comment by jaap-karssenberg** [comment]
8786cbdcab3900037aa77387113356dc3c10d164

**Comment by sojusnik** [comment]
It's connected to [this](https://bugs.launchpad.net/zim/+bug/1124666) issue on Launchpad.

At the moment applying a number to an already formatted header is working, but not when turning a list item into a header.

**Comment by jaap-karssenberg** [comment]
@sojusnik: This ticket is about indenting, not numbering. You are probably
thinking of ticket #133

**Comment by sojusnik** [comment]
> @sojusnik: This ticket is about indenting, not numbering. You are probably thinking of ticket #133

Indeed :)
