### ISSUE TITLE
Zim fails to open a notebook in a path with Unicode characters

### ISSUE THREAD

**Issue by dogancelik** [zim-desktop-wiki/zim-desktop-wiki#593]
[Here's the report](https://gist.github.com/dogancelik/110cf5458b96fef11d8f5e100dfc1369) for `.zim` association in Windows Registry.

When you open a Notebook in Windows Explorer:
![windows explorer](https://user-images.githubusercontent.com/486818/50491761-f5c5eb80-0a24-11e9-85c9-d0181410e415.png)

You get an error:
![path error](https://user-images.githubusercontent.com/486818/50491757-f1013780-0a24-11e9-83ff-2c8c3c5b5c0a.png)

Actual path is:
```
D:\Dropbox\Yazılar\Zim\Şarkılar
```

#### Version Info
* Zim: version 0.68
* OS: Windows 10, 64-bit

**Comment by jaap-karssenberg** [comment]
Tested with latest master branch and seems to work correctly now. Please re-open if similar issue seen with zim 0.70 or newer
