### ISSUE TITLE
"Open in new window" for link on another note as automatic text baloon

### ISSUE THREAD

**Issue by Nick222** [zim-desktop-wiki/zim-desktop-wiki#600]
Can You make "Open in new window" for link on another note as automatic popup text window (text baloon) - may be as option ?
Now it is Wikipedia style...

**Comment by jaap-karssenberg** [comment]
Sorry, but you will have to explain in a bit more words. Afraid I do not
understand what you are thinking about.

-- Jaap

**Comment by Nick222** [comment]
Excuse me - my English is very bad :(

Now I can open right-click-mouse menu on link (which lead to another note) and by command "Open in new window" open note from link in new small window.

Can this small window open automatic when mouse-cursor is over this link?

**Comment by jaap-karssenberg** [comment]
You mean a floating pre-view popup (like wikipedia) ?  Afraid that is a "won't fix" for me.
