### ISSUE TITLE
Zim broken on Ubuntu 18.10

### ISSUE THREAD

**Issue by SamD** [zim-desktop-wiki/zim-desktop-wiki#605]
I didn't realize there an update, checking dpkg.log shows

```
2019-01-15 21:54:44 status installed zim:all 0.70~rc1-SNAPSHOT-t201901151858~ubuntu18.10.1                                                                                                  
```
When I started today Zim opens only with the tags displayed and only matching tags shows in the navigator, I can't see anything else or any other notes, removing the tags plugin results in nothing being
viewable in Zim, it's totally broken.

What's the best way to rever this update ?

**Comment by SamD** [comment]
Ah, I had added `http://ppa.launchpad.net/jaap.karssenberg/zim-snapshots/ubuntu`, purging the ppa brought be back to stable release.

Phew, I had many notes over the years stored in Zim, this was a scary moment and seeing this was the first time this has happened, makes me ask the question what is the long-term support for Zim? 

Perhaps having Zim as a `snap` package might be safer?

**Comment by sojusnik** [comment]
Experienced the same :) The index sidebar is a plugin now. So you have to go to the settings and enable it under plugins.

The 0.7rc has some bugs, but it's quite stable, so you can safely use the RC with the snapshots PPA. At least I do.

**Comment by SamD** [comment]
@sojusnik Thanks for the update, yeah it was a bit strange, probably should have digged around for release notes after seeing the update
