### ISSUE TITLE
Text cursor always jumps to page title …

### ISSUE THREAD

**Issue by sojusnik** [zim-desktop-wiki/zim-desktop-wiki#611]
… when a new page is opened or a page is refreshed.

Ideally, Zim should remember the last position within a page, see [here](https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/92) for details.

Happens with Zim 0.70-rc1 on Ubuntu 18.10.

**Comment by sojusnik** [comment]
Still doesn't work as expected.

Just write something and then reload the page or jump to another one. You'll see that the page view won't stay where the text cursor is, but jumps somewhere else.

**Comment by jaap-karssenberg** [comment]
Works fine in my testing - are you on the right patch level ?

**Comment by jaap-karssenberg** [comment]
Should be up-to-date now, but can have up to 24h delay in syncing with
GitHub and building the packages.

-- Jaap

**Comment by sojusnik** [comment]
It's still not working reliably :/

The cursor stays at its place when changing from one page to another, but not after a new page was created and then Zim was closed.

To reproduce: create a new page (the page title must not have been used before), then fill some text that spans over the whole page so that you have to scroll, save and quit = the cursor will appear before the page title.
Open Zim, write something somewhere on this page and close Zim = the cursor will appear again before the page title.
Open Zim, write something somewhere on this page or just change the position of the cursor and then switch to another page and come back = the cursor position is finally saved!
But if you'll write something or change the cursor position after that, and then close Zim, then the position won't be saved again. The cursor will appear at the place before the switch to another page happened (see the preceding paragraph).

**Comment by sojusnik** [comment]
The same is true for saving window size and state – it is only saved after changing to another page and not after quitting. Happens even with the help window.

**Comment by sojusnik** [comment]
Is there a certain reason why this issue isn't reopened? It's still there in 0.70+

**Comment by aqeeliz** [comment]
Did a quick test, it seems zim only saves cursor position when switching page, it doesn't save it when quitting. 

An easier test would be, open any page, let's say cursor is initially at position A, move cursor around to position B.
Now, if you quit without switching to another page, when you next open zim, cursor will be back at position A.
But, if you switch to another page, and then quit (or directly return to page), it will now be at position B.

**Comment by jaap-karssenberg** [comment]
@aqeeliz thanks, that helped finding the issue. Just committed a fix.

Any further discussion of similar behavior, please start a new ticket.
