### ISSUE TITLE
Tag autocompletion stopped working

### ISSUE THREAD

**Issue by sojusnik** [zim-desktop-wiki/zim-desktop-wiki#615]
Tags aren't autocompleted any more after @.

This would be a good opportunity to accept it as an official plugin, after fixing it.

Happens with Zim 0.70-rc1 on Ubuntu 18.10.

**Comment by jaap-karssenberg** [comment]
Since the port to Gtk3 & python3 is non-compatible in API all external plugins are expected to be broken an need update.

Closing here as it is not (yet) part of core repository.

**Comment by sojusnik** [comment]
Where do we have to report this instead?

**Comment by jaap-karssenberg** [comment]
Please check with the author of the plugin. My preference would be for
external plugins to have their own repository; that would allow tracking
bugs there.

-- Jaap

**Comment by sojusnik** [comment]
Let's hope that @muguu will soon have a look on it, since he's the one [in charge](https://gist.github.com/muguu/6502aa7064dc0795a684adaac3d65212).

**Comment by sojusnik** [comment]
@gesellkammer [released an updated version](https://github.com/gesellkammer/zim-plugins) recently that is working with zim 0.70.
