### ISSUE TITLE
Optimise the pane at the bottom

### ISSUE THREAD

**Issue by sojusnik** [zim-desktop-wiki/zim-desktop-wiki#618]
The sections in the pane at the bottom should be [without borders](https://i.imgur.com/NJdD6RN.png) and also slightly lower.

**Comment by jaap-karssenberg** [comment]
They are normal buttons. Afraid rendering depends on theme settings, so may look different for different people. Probably possible to improve using the CSS styling of Gtk3, but low prio item for me.

**Comment by sojusnik** [comment]
Even if they are "normal" buttons, those borders look out of place. As if a theme isn't applied properly. Additionally, if the "attachments" field is removed (by deactivating the plugin), then the height of the bottom pane is reduced and looks better.

Maybe a design-oriented Zim user with coding experience will have a look on this.

**Comment by jaap-karssenberg** [comment]
You can experiment with the CSS theming if you want. I've updated the
manual with some pointers how to do that but do have much experience with
it either. If you find the CSS code to make it look better it is an easy
patch to add that as a default.

Regards,

Jaap

**Comment by sojusnik** [comment]
I don't have any CSS knowledge, so let's hope that somebody else will have a look on that. Maybe tag this as "good first issue"?
