### ISSUE TITLE
Deleting last page twice will show ghost page

### ISSUE THREAD

**Issue by hsandt** [zim-desktop-wiki/zim-desktop-wiki#619]
**Repro:**

1. Create 2 pages at the end of your notebook (I named them z1 and z2 so they are at the end). You get this:

![grafik](https://user-images.githubusercontent.com/1067772/51347800-018f5580-1a99-11e9-88c1-9ea07b18e6ef.png)

2. Right-click > delete last page z2. You get this:

![grafik](https://user-images.githubusercontent.com/1067772/51347809-081dcd00-1a99-11e9-9806-178674fb8723.png)

3. Right-click > delete last page z1. You get this:

![grafik](https://user-images.githubusercontent.com/1067772/51347827-11a73500-1a99-11e9-9a97-9ed768ef0bc4.png)

![grafik](https://user-images.githubusercontent.com/1067772/51347960-5fbc3880-1a99-11e9-8612-5323fbbe7420.png)

**Result:**

Ghost page z2 appears in italics, as revived. But that is temporary. Unless you force-save it, clicking elsewhere will have it disappear again.

**Expected:**

z1 should disappear, and the page above should be selected (if any)

**Notes:**

Surprisingly, the ghost page appears in italics, making me think showing a page ready to be deleted is somewhat an expected behaviour. But that is probably just part of a feature allowing deleted pages to be restored?

Sometimes it doesn't happen. In this case, add a last page z3 and reiterate.

**Comment by jaap-karssenberg** [comment]
I think what happens is that you jump back to the previous page ("z2" in
this case) - and when you navigate to a non-existing page it is shown
temporarily in italics. When you navigate away, it disappears again. Seems
to me the expected behavior.

-- Jaap

**Comment by hsandt** [comment]
OK, I admit I would have expected to focus on the non-deleted page just above of the last focused page.
But knowing this, the workaround should be to focus another page before deleting the current one.
