### ISSUE TITLE
where can I fix translation in 0.70-rc1?

### ISSUE THREAD

**Issue by a11g0rhythm** [zim-desktop-wiki/zim-desktop-wiki#620]
Hi,
where can I fix translation in 0.70-rc1?
![zrzut ekranu z 2019-01-18 16-16-13](https://user-images.githubusercontent.com/1868730/51395378-00afff80-1b3d-11e9-96d2-23672d0498a2.png)
there are issue with polish

**Comment by jaap-karssenberg** [comment]
https://translations.launchpad.net/zim

**Comment by a11g0rhythm** [comment]
Ok, and how I can get access to translation on launchpad ?

**Comment by sojusnik** [comment]
You have to register there: https://launchpad.net/+login

**Comment by a11g0rhythm** [comment]
I'm register, from my side it looks like this:
![zrzut ekranu z 2019-01-20 11-12-30](https://user-images.githubusercontent.com/1868730/51438338-2bb86180-1cab-11e9-871b-d4656777e640.png)

**Comment by sojusnik** [comment]
Does https://translations.launchpad.net/zim/pyzim/+pots/zim/pl/+translate help?

**Comment by a11g0rhythm** [comment]
nope
![51438338-2bb86180-1cab-11e9-871b-d4656777e640](https://user-images.githubusercontent.com/1868730/51443502-ef582600-1ce9-11e9-8950-9f59bf0b368a.png)

**Comment by sojusnik** [comment]
If I go to the link mentioned above, I see [this](https://i.imgur.com/oc7Mu30.png).
Something seems to be with your settings.

**Comment by a11g0rhythm** [comment]
I use my second account on launchpad and it's  working :)
