### ISSUE TITLE
Ask for Help: Zim can't find my LaTeX

### ISSUE THREAD

**Issue by gapplef** [zim-desktop-wiki/zim-desktop-wiki#621]
Ubuntu 18.04
Zim 0.68-rc1

I already have TeXLive installed under my home directory, and add the path into PATH.
When I try to enable `Insert Equation` plugin, zim still showing miss dependence `latex`, `dvipng`.
What should I do?

**Comment by jaap-karssenberg** [comment]
Have you restarted zim (including closing tray icon) since adding them to PATH? If not zim won't know about the new PATH.

If that doesn't help, make sure the PATH you set is the one that affects applications that get started through the desktop, and not just for the command shell.

**Comment by gapplef** [comment]
> make sure the PATH you set is the one that affects applications that get started through the desktop, and not just for the command shell.
How to do that? Which setting or file control the PATH of desktop application?
I only add the texlive path into my .zshrc and .bashrc.
