### ISSUE TITLE
No right-click on bookmarks bar

### ISSUE THREAD

**Issue by PierreRust** [zim-desktop-wiki/zim-desktop-wiki#625]
There is no popup menu when I right-click on a bookmark in the bookmark bar. 
However, the popup menu works on the '+' button , which means I can add new bookmarks but not remove them.

Zim 0.70-rc1on kubuntu. 
freshly updated from github (commit c93305646189d81833149a534d6b5a3b1227a2d8)

Let me know if you need more details.

**Comment by PierreRust** [comment]
Actually, the problem is trivial when looking at the logs : 
Traceback (most recent call last):
  File "/home/pierre/Tools/zim-desktop-wiki/zim/plugins/bookmarksbar.py", line 391, in do_bookmarks_popup_menu
    _button_width = button.size_request()[0]
TypeError: 'Requisition' object does not support indexing
DEBUG: Action: close (delete-event)

I'll submit a PR.

**Comment by PierreRust** [comment]
Submitted  PR #626 for this issue.

**Comment by jaap-karssenberg** [comment]
Merged PR
