### ISSUE TITLE
Can't save a page containing a specific text.

### ISSUE THREAD

**Issue by Xeizzen** [zim-desktop-wiki/zim-desktop-wiki#628]
For some reason a zim wiki can't save a page containing the text that can be found in the next comment.
I will paste it as it is, because I'm not sure what causes the problem.

**Comment by Xeizzen** [comment]
Xeizzen_: now I at least understand how the science works. because the term "theory" isn't used in the way many people associate it with. because in scientific meaning it is more like a "descriptive picture" of something. "description of something". not necessarily complete, but still this is something that can be used in practice.
Xeizzen_: And if we want to check whether the theory is true we can ask epistemology. Because there are two types of knowledge: precisive and descriptive. first based on math and logic methods, it precise, but doesn't evolve. It just IS. The second one based on the description. Of an experience, experiment and/or observation. So... It tend to change.

**Comment by PierreRust** [comment]
I'm just tried creating a new page and pasting your text in it, it worked without any issue.
Could you describe more precisely what did not work in your case, and how to reproduce ot ? with zim version, etc.

**Comment by Xeizzen** [comment]
@PierreRust The way to reproduce it is just to copy-paste the exact text from my message to any empty (newly created) page in the wiki, and hit ctrl+s after that.
And for the record: I've done it on windows 10 x64 enterprise.
Maybe the bug isn't reproducible on *nix machines.

**Comment by Xeizzen** [comment]
Thank you. Maybe the problem isn't related to zim-wiki at all. Maybe it being deleted for the other reason.
Anyway thank you all and sorry for the inconvenience.
