### ISSUE TITLE
Leading zero missing from %V in template strftime implementation

### ISSUE THREAD

**Issue by robla** [zim-desktop-wiki/zim-desktop-wiki#631]
When I add the following markup to my `~/.local/share/zim/templates/wiki/Journal.txt` template in the latest checkout of Zim (master rev c933056461, roughly 0.70rc1):
```
* strftime("%gW%V %yW%W %Y-%m-%d %s", journal_plugin.end_date):
  [% strftime("%gW%V %yW%W %Y-%m-%d %s", journal_plugin.end_date) %]

```
...then I visit "Journal/Week_04".  What I see:
* strftime("%gW%V %yW%W %Y-%m-%d %s", journal_plugin.end_date):
  19W4 19W03 2019-01-26 1548489600

Note the lack of leading zero in the %gW%V version.  Expected behavior should be the same as Python with the same timestamp:
```
>>> foo=datetime.datetime.fromtimestamp(1548489600)
>>> foo.strftime("%gW%V %yW%W %Y-%m-%d %s")
'19W04 19W03 2019-01-26 1548489600'
```
Note the leading zero for %V, which is the ISO-8601-compliant week number.

**Comment by jaap-karssenberg** [comment]
Thanks for pointing out that python3 supports %V - python2 does not, so I had a hack on top.
