### ISSUE TITLE
'Save version' modal dialog should have a way to 'save' without using the mouse

### ISSUE THREAD

**Issue by quesada** [zim-desktop-wiki/zim-desktop-wiki#636]
This is a crucial operation I do dozens of times per hour.
It'd be a great timesaver if there was a keyboard shortcut to save. Like 'ctrl enter' or similar.

**Comment by Self-Perfection** [comment]
@quesada I have not tried gtk3 port yet, but in gtk2 version you can press
1. `ctrl-shift-S` to open "save version dialog
2. then `ctrl-tab` (that is tricky part) and 3 more tabs will move focus to "save" button
3. then just hit space or enter

To save keypresses you can create custom tool with script that launches `git commit` as you like it and assign it hotkey that you want (see `accelmap` zim config file or `gtk-can-change-accels=1` feature in your gtkrc).

**Comment by quesada** [comment]
Thanks

**Comment by jaap-karssenberg** [comment]
The buttons have shortcuts using "Alt" (like many menu items). So when the
dialog is open "ALT-S" will hit the "Save" button. Pressing "Alt" alone
will underline the shortcut keys.

- Jaap
