### ISSUE TITLE
Gtk3: clicking on "source view" object does not place the cursor inside

### ISSUE THREAD

**Issue by jaap-karssenberg** [zim-desktop-wiki/zim-desktop-wiki#637]
Something goes wrong with the event handling for inserted objects that contain a textview. CLicking the embedded textview does not place the cursor inside, but just outside in the parent textview.

Clicking e.g. button in embedded object does work.

Also the cursor is not changed when going over the object, may or may not be related.

**Comment by krizoek** [comment]
this seem to work here. what versions do you have for gtk, and the gtk sourceview??

**Comment by krizoek** [comment]
i'm running zim-0.70_rc1

**Comment by jaap-karssenberg** [comment]
Interesting, Testing now on ubuntu, python 3.6.7 and
libgtk 3.22.30-1ubuntu1

What is your environment?

**Comment by krizoek** [comment]
it was a mixed version, seems the problem do exist here with zim 0.70-rc1
