### ISSUE TITLE
Spellchecker plugin doesn't find gtkspell nor gtkspellcheck. Zim on arch 

### ISSUE THREAD

**Issue by quesada** [zim-desktop-wiki/zim-desktop-wiki#643]
I followed:
https://wiki.archlinux.org/index.php/Zim#Spell_checker
"The requirements for the Spell Checker plugin are as follows: gtkspell, python2-gtkspellcheck and aspell-en.

Change aspell-en to your desired language support. Now you can configure the Spell Checker and define the default language, in my case en_GB."

These requirements don't satisfy zim 0.69. Was it because we moved to python 3? Did we? 
I tried installing the python3 versions and it didn't solve the problem.

**Comment by jaap-karssenberg** [comment]
Version 0.69 is still python2 - we move to python3 with version 0.70

**Comment by quesada** [comment]
Good to know. It doesn't find the python2 dependencies then. At least not the ones described in the Arch wiki. Any way to figure out which dependencies I need in Arch?

**Comment by jaap-karssenberg** [comment]
I would try the alternative dependency, which is "python-gtkspellcheck" quick search shows this package is available in Arch

**Comment by quesada** [comment]
> I would try the alternative dependency, which is "python-gtkspellcheck" quick search shows this package is available in Arch

Nope, this didin't work. It still shows 'gtkspell - Failed' and spellcheck doesn't work. Maybe it installed the python 3 version (that's the system's python)?

**Comment by s1291** [comment]
Just wondering why this was closed.
I am using zim version 0.74.2 and have installed `python-gtkspellcheck` and still experience the same problem as the OP
(I am running Ubuntu 20.04)
![image](https://user-images.githubusercontent.com/17838489/140733724-5f538566-5656-4d48-b2dc-c0c35cf5e37e.png)

But it doesn't work: when I click on Properties, it shows:
![image](https://user-images.githubusercontent.com/17838489/140733876-3502b157-a9c1-42bf-80d2-8b9d72857861.png)

It seems to me that this plugin is broken.

**Comment by lachlanA** [comment]
I will second that, broken on Debian 11,

**Comment by jaap-karssenberg** [comment]
Sorry to pick this up so much later, but from the screenshot it looks working to me. The plugin is clearly loaded (else there would not be a properties section for it) using the gtkspellcheck library as a dependency. Go ahead and set a language code see if that works.
