### ISSUE TITLE
Does Zim search scale well?

### ISSUE THREAD

**Issue by quesada** [zim-desktop-wiki/zim-desktop-wiki#645]
I have 505 files (and a .git folder that bumps that up another 1000)... and the search takes about a second on a modern computer. Is this representative? If we had 10k files, would search be really slow? I'm trying to get away from web apps for that reason, friction.

**Comment by jaap-karssenberg** [comment]
Zim search is relatively slow at the moment if you do a content search.
There is an improvement proposal based on a low level "grep" before parsing
text in the notebook.

Searching for index properties (names, tags, links) is optimized using the
database and very fast.

-- Jaap

**Comment by quesada** [comment]
Thanks, very good to know. Maybe calling 'the silver searcher' in a pipe (or any of these grep alternatives) would be faster?

Is the improvement proposal coming up in 0.7?

**Comment by quesada** [comment]
It really is a pity that the search is not faster (SublimeText 'find in files is about 10x faster). Searching from the command line is not ideal because there are headers etc (noise) that a non-zim searcher will not understand. 

Discoverability (the index panel, with its alphabetical order) is not a strong point either. So we are in between a rock and a hard place.

**Comment by quesada** [comment]
Ripgrep seems to be the one to beat. Maybe a plugin that does a system call to rg and displays the information as is now would work great and be a relatively low hanging fruit.

**Comment by jaap-karssenberg** [comment]
See issue #64
