### ISSUE TITLE
Tray menu

### ISSUE THREAD

**Issue by lockie** [zim-desktop-wiki/zim-desktop-wiki#653]
Hello!
I've been using zim for a very long time. Recently zim's version in my distro upgraded (I'm using Gentoo) to 0.70-rc1, and there's a problem - the tray menu does not appear, neither with left click or right click on the tray icon. So I have to activate zim by manually running `zim` command, which is not so convenient. What can be the source of the problem?
I'm using Python 3.6, gtk+ 3.24.1 and PyGObject 3.28.3.

**Comment by jaap-karssenberg** [comment]
What desktop are you using?

**Comment by lockie** [comment]
Sorry, forgot to mention it. I'm using i3 with polybar panel (the latter shows tray icons).

**Comment by jaap-karssenberg** [comment]
Do you by any change now whether that panel is using the ubuntu "appindicator" library? If in doubt set the trayicon in zim to "classic" (plugin preferences).

**Comment by lockie** [comment]
> Do you by any chance know whether that panel is using the ubuntu "appindicator" library?

I'm almost 100% sure it does not.

Turns out I've already had "classic" tick box on in Zim settings; tried to turn it off (just in case) - no luck, tray menu still does not appear.

**Comment by jaap-karssenberg** [comment]
in zim/trayicon.py replace "Gtk.statusicon_position_menu" with
"Gtk.StatusIcon.position_menu" should fix - my testing shows the menu is
buggy anyway - afraid also trayicon is being deprecated in Gtk, so will
need to find correct library to keep same functionality

-- Jaap

**Comment by lockie** [comment]
I did the change you've proposed in 0.70-rc1 version checked out from repo, and it had fixed the problem - menu does appear as it did before.
I guess I'll downgrade to 0.69 for the time being.
Thanks for your help!
