### ISSUE TITLE
Disable all auto-link creation

### ISSUE THREAD

**Issue by Spheerys** [zim-desktop-wiki/zim-desktop-wiki#654]
Hi,

I have code like [[+CamelCase]] to insert but it always convert as link to a sub-page
I want to disable the auto-link creation but I don't find the option !

Thanks for your help :)

**Comment by jaap-karssenberg** [comment]
This is not possible. Zim pages are stored as wiki text, so if you insert
wiki like text, it will be formatted.

If you want to insert codes you should use the "verbatim" formatting or the
plugin for source code blocks.

-- Jaap

**Comment by Spheerys** [comment]
Hummm too bad....
I make the deal with "verbatim", but I had to did it carefully to not forget formatted code with [[+something]]

Thanks for your answer anyway :)
