### ISSUE TITLE
White space with one result in "jump to" window

### ISSUE THREAD

**Issue by sojusnik** [zim-desktop-wiki/zim-desktop-wiki#656]
If the "jump to" (ctrl+j) window shows only one result, then below the result there is a white space that should be removed, as my mouse cursor is showing [here](https://i.imgur.com/YlltrN1.png).

Ideally, the result should be already selected, so that you don't have to select it, but instead only press enter to switch to it.

**Comment by jaap-karssenberg** [comment]
This is a "won't" fix for me as this is default Gtk behavior and does not impact functionality at all. Would not be surprised if it was done intentionally to make the dropdown more visible.
