### ISSUE TITLE
No index updating to zim_0.70

### ISSUE THREAD

**Issue by Allanmarbaniang** [zim-desktop-wiki/zim-desktop-wiki#658]
Just installed Zim 0.70RC
![screenshot from 2019-02-09 10-22-10](https://user-images.githubusercontent.com/38316728/52516599-3899f680-2c54-11e9-871a-b7bd43d1da69.png)
2 but no index can be found after installing it. What could be the issue???

**Comment by jaap-karssenberg** [comment]
You need to enable the "pageindex" plugin
