### ISSUE TITLE
Headers are still copied with formatting

### ISSUE THREAD

**Issue by sojusnik** [zim-desktop-wiki/zim-desktop-wiki#661]
Although the settings are set to copy text to the clipboard as plain text, it doesn't apply to headers. To reproduce, double-click on a header and copy it. Paste into a plain text editor, like Gedit, and you'll see that the formatting signs are still copied. Other formatted text like bold, italic are correctly copied without any formatting though.

Observed in v0.70-rc2 under Ubuntu 18.10.

**Comment by jaap-karssenberg** [comment]
This is intentional, can argue whether it is correct or not. But for now I'm happy with this behavior.

**Comment by sojusnik** [comment]
What is the use case to having headers as an exception?

If I want headers to be copied with formatting, I would choose to copy the text as Wiki or Markdown from the context menu and certainly not expecting to have headers with formatting when "plain text" is explicitly set in the settings of Zim or chosen in the context menu of a text when copying.

Would love to hear the opinion of others on that.
