### ISSUE TITLE
Sorting of umlauts in the tag cloud

### ISSUE THREAD

**Issue by sojusnik** [zim-desktop-wiki/zim-desktop-wiki#667]
Tags starting with a capital umlaut (Ö, Ä etc.) are shown after tags with lower letters. To reproduce, create:

```
@ab
@AAA
@äb
@ÄÄÄ
```

They will appear in the following order in the tag cloud (if it's sorted alphabetically): AAA, ab, ÄÄÄ, äb. But actually they should appear as AAA, ÄÄÄ, ab, äb.

I really like that alphabetical sorting is case-sensitive, so that tags with capital letters come before lower letters. Please keep that or at least make it switchable in the settings, if you plan to change that.

**Comment by sojusnik** [comment]
The new release solved the sorting with umlauts, but is case-insensitive now :/

@jaap-karssenberg did you overlook my comment?

> I really like that alphabetical sorting is case-sensitive, so that tags with capital letters come before lower letters. Please keep that or at least make it switchable in the settings, if you plan to change that.

**Comment by jaap-karssenberg** [comment]
Sorry, but all alphabetical sorting in zim is case-insensitive, so made it
consistent here as well.

-- Jaap

**Comment by sojusnik** [comment]
Can you make it at least an option to toggle it for the tag cloud? Like it was before, but without the umlaut sorting bug?

**Comment by sojusnik** [comment]
Would be very helpful if you could reopen this issue, so that a good soul would hopefully implement a toggle to switch between case-sensitive/insensitive sorting in the right-click menu of the tag cloud. This customization seems trivial to me, but I have to rely on somebody else's help in order to restore the previous sorting behaviour. :crossed_fingers:

**Comment by sojusnik** [comment]
@jaap-karssenberg haven't you received the previous messages? I would appreciate a response.

**Comment by jaap-karssenberg** [comment]
@sojusnik <dmt.lsv@gmail.com> I'm sorry if you don't agree, but I remain of
the opinion that sorting should be case insensitive. I won't make a
case-sensitive sorting option.

The case you mention where you use the case to distinguish different types
of tags does not match well with the current implementation. For e.g. tags
are handled by the index case-insensitive as well, so the same name with
different case is still the same tag.

In the future I plan to support both "@" and "#" tags - that should help
with use cases like yours.

Regards,

Jaap

**Comment by sojusnik** [comment]
Thanks for the response @jaap-karssenberg!

Can't wait to have `@` and `#` tags then!
