### ISSUE TITLE
Show failed plugins in plugin list in preferences dialog

### ISSUE THREAD

**Issue by jaap-karssenberg** [zim-desktop-wiki/zim-desktop-wiki#668]
When a plugin fails to load, it will not be shown in the plugin list in the preferences dialog. Errors are printed to error log, but not always visible to the user. Therefore it would be better to show all plugins in the plugin list. If plugin modules fail to load, show the error where normally the description is (with some explanation).

**Comment by eightytwo** [comment]
@jaap-karssenberg: I have a couple of questions about the solution for this issue that I was hoping you might be able answer.

1. What sort of helpful error message can be shown to the user as to why a particular plugin failed to load? As far as I can tell a plugin will fail to load if an exception occurs [here](https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/7d7d1364dc74c892bc81ef1399957406d1be4c61/zim/gui/preferencesdialog.py#L370-L373), in which case there will only be an exception message available which may not be helpful to the user. That said, an exception message could be helpful for reporting issues to this repo.

2. Should the error message be shown for plugins that do load but have missing dependencies? Zim already displays missing dependencies in red so perhaps this isn't necessary. If it would be useful the error message can include this detail about missing dependencies.
