### ISSUE TITLE
Dragging links from Index not working 0.70R2

### ISSUE THREAD

**Issue by Allanmarbaniang** [zim-desktop-wiki/zim-desktop-wiki#669]
When I drag a link from the index to a page, it does not come up as a link?
Love your work!!!

Thanks,

**Comment by jaap-karssenberg** [comment]
Probably related to #390

**Comment by fdt-dev** [comment]
I seem to have the same issue. 0.70RC3 running under Ubuntu 18.04

**Comment by jaap-karssenberg** [comment]
Duplicate
