### ISSUE TITLE
"Ignore Sections" in Task List prevents task removal

### ISSUE THREAD

**Issue by SuperCuber** [zim-desktop-wiki/zim-desktop-wiki#676]
When adding a section to `Section(s) to ignore` option of task list, the tasks inside that section are not removed and cannot be removed or checked off.
The solution to that currently is to un-ignore that section, somehow mark them all off (for example remove the "all checkboxes are todos" option), then when they are off the list ignore the section again.

**Comment by jaap-karssenberg** [comment]
Duplicate of #687
