### ISSUE TITLE
Request updating md5 hash use to a more robust modern hash, such as sha256

### ISSUE THREAD

**Issue by laeccan** [zim-desktop-wiki/zim-desktop-wiki#679]
Could hashlib.md5() references be updated to a more robust, modern hash, such as hashlib.sha256() per https://docs.python.org/3/library/hashlib.html .

**Comment by jaap-karssenberg** [comment]
Why?  We use MD5 for file comparison, not for security.

Also be aware that for thumbnailing there is a standard that specifies use
of md5.

**Comment by laeccan** [comment]
Thank you for the feedback. Found the 2012 0.8.0 spec https://specifications.freedesktop.org/thumbnail-spec/thumbnail-spec-0.8.0.html stating 'The thumbnail filename is determined by a hashfunction. This proposal utilizes MD5 as hash mechanism in the following way.' (https://specifications.freedesktop.org/thumbnail-spec/thumbnail-spec-latest.html#DIRECTORY has the same text.)
