### ISSUE TITLE
New Page always appears last

### ISSUE THREAD

**Issue by DocSalvager** [zim-desktop-wiki/zim-desktop-wiki#680]
I've been using Zim for many years without seeing this issue.

On creating a new page in Zim 0.68, the page now always appears last in the index list in the left pane instead of where it should be alphabetically. I have tried reindexing, collapsing all levels, and exiting and reentering Zim but the new page remains out of order. I checked the actual file listing to insure no unprintable characters got inserted at front of name but none were found. The directory displays the page .txt file in the correct location.

**Comment by jaap-karssenberg** [comment]
I believe this is due a discrepancy in how the index handles the "sortkey"
which should be fixed in version 0.70 or newer. What version are you using?

**Comment by DocSalvager** [comment]
Version 0.68.

**Comment by DocSalvager** [comment]
Since posting this, I've been regularly checking all the antiX (v17.1) and Debian repositories, including unstable and sid, for Zim 0.70 but 0.68-1 is the most recent I can find.

I've been a developer in other languages for over 30 years so thought I'd just install from source, but the nightmare of Python packaging has stopped me. None of your instructions work on my system since it doesn't have pip, setuptools, virtualenv, etc. though of course it has many Python packages installed as well as the Python 2.7 and 3.6 environments.

I would like to install Zim 0.70 to Python 3.6 solely to get this bug fix. But the rest of the system needs to remain stable.

Can you direct me to step-by-step instructions that include the necessary prerequisites to accomplish this?

**Comment by jaap-karssenberg** [comment]
Version 0.70 is still in "release candidate" stage, so not yet picked up in
all distributions.

Please checkout the git repository and check README for instructions to
run, it doesn't mention any of the " pip, setuptools, virtualenv, etc." you
mention. Instead it lists pre-requisite packages that are available in
Debian apt repository. If those are installed you can even run from source
folder without installing.

Regards,

Jaap

**Comment by DocSalvager** [comment]
Just realized I had not closed this. Now on v0.72 and problem is resolved.
