### ISSUE TITLE
Clicking the "Table of Contents" button triggers content below (flying widget)

### ISSUE THREAD

**Issue by fredericjacob** [zim-desktop-wiki/zim-desktop-wiki#682]
If the "Table of Contents" plugin for the contents of a single page is configured to "Show ToC as floating widget instead of in sidepane", clicking it (to expand or collapse the table of contents) fires a click event on the actual page content below, too.

I noticed this when a link was below the button, and clicking it repeatedly caused a website to be opened multiple times in the browser.

**Comment by jaap-karssenberg** [comment]
What version of zim are you using?

**Comment by fredericjacob** [comment]
Sorry for the late response... I'm on Linux Mint 19.1, using Zim version 0.69.1
