### ISSUE TITLE
Close opened pages from page context menu

### ISSUE THREAD

**Issue by NeoProgramming** [zim-desktop-wiki/zim-desktop-wiki#683]
Sometimes I open pages accidentally, or open pages that I don’t need for current work. They remain on the tabs bar. 
Each tab bar has context menu, which is opened by clicking the right mouse button on the tab. Menu contains items "New page", "New sub page" etc.
But this menu does not contain an element to close the page. 
I propose to add "Close" command to the end of the menu. At this command, the tab will be closed and disappear from the tabs bar. Thus, it is possible to close the pages that are not needed at the moment and that distract attention.

**Comment by Osndok** [comment]
Yeah, I think that confused me when I first tried zim, so this might be a good addition, and the bookmarks plugin/bar already has such a context menu option (called "Remove").

FWIW, the theory of operation is not really 'opened tabs' so much as a 'utility queue'... the default is "recently visited", but you might find an option you like better in the "View -> Pathbar" submenu. For example, "recently changed" would not show accidental clicks, tends to show more relevant entries (what you are working on), and will probably force you to use the 'back' button/shortcut more frequently.

**Comment by NeoProgramming** [comment]
By the way, "Remove" option from context menu is dangerous: this command deletes the file without asking for confirmation.

**Comment by jaap-karssenberg** [comment]
The remove option _trashes_ the file without confirmation - you can restore it from your desktop trashcan.
But I see you point, reduced menu in da0d034ff0bfb315647373d2f32d0708e3940364

**Comment by jaap-karssenberg** [comment]
Closing as "wont't fix" since implementation of pathbar does not allow easily modify list; it represents the history.
