### ISSUE TITLE
Zim Verison plugin does not see git installation

### ISSUE THREAD

**Issue by RuubixO** [zim-desktop-wiki/zim-desktop-wiki#686]
Summary:
The Verison plugin does not detect git from the plugins menu, even after using bash to git init a repo manually.

Current System:

- Fedora 29, up-to-date (as of this posting)
-Git, version 2.20.1
-Zim 0.69.1 (installed through the flatpaks option in the Fedora "Software" app).

Steps taken:
-Attempted to add Version plugin from Zim menu, says Git it not detected.
-From bash cli, I made a "git init" from the desired notebook @ cd: "/Notebooks/Notes"
-"which git" confirmed git was present. Plugin did not work.
-I then did "git add" and "git commit" on available files. Plugin was still unavailable.

Let me know the best next steps for me to resolve this, thank you!

**Comment by Osndok** [comment]
When you run zim with the debug flag ("zim --debug"), do you get any relevant diagnostic output?

**Comment by Osndok** [comment]
IIRC, flatpaks use docker containers, so it probably can't reach the git binary which is outside of the container... I think the packager/maintainer of the zim flatpak would be the person to address this.

**Comment by cheese** [comment]
As noted in https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/622#issuecomment-460764135, flatpak can call host command through dbus.

A basic sample looks like this:

```
#!/usr/bin/python3
import gi.repository
from gi.repository import Gio
from gi.repository import GLib

def hostc(proxy, result, _):
    print("%d started" % result)

def signal(_, sender_name, signal_name, params):
    print("Signal from %s, %s" % (sender_name, signal_name))
    print("params %s %s" % (params.get_child_value(0).get_uint32(), params.get_child_value(1).get_uint32()))


def run(pro, args):
    args_bytes = [arg.encode("UTF-8") + b"\0" for arg in args]
    pro.HostCommand(r'(ayaaya{uh}a{ss}u)', [], args_bytes, [], [], 0, result_handler=hostc)

def main():
    bus = Gio.bus_get_sync(Gio.BusType.SESSION, None)
    pro = Gio.DBusProxy.new_sync(bus, Gio.DBusProxyFlags.NONE, None,  'org.freedesktop.Flatpak', '/org/freedesktop/Flatpak/Development', 'org.freedesktop.Flatpak.Development', None)
    try:
        pro.HostCommand(r'(ayaaya{uh}a{ss}u)', [], [b"which\0", b"which\0"], [], [], 0)
    except GLib.Error:
        print("HostCommand method is not available")
        return
    print("HostCommand method is available")

    pro.connect("g-signal", signal)

    run(pro, ["ls", "/"])
    GLib.MainLoop().run()

main()

```

**Comment by RuubixO** [comment]
So Fedora/bash ended up installing another instance of Zim, but natively, onto my system when I ran that command! And now versioning works! It looks like the docker container was probably the source of the isolation.

**Comment by cheese** [comment]
> As noted in [#622 (comment)](https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/622#issuecomment-460764135), flatpak can call host command through dbus.
HostCommand called by D-Bus may be too verbose and tricky. An alternative method is run host commond under 'flatpak-spawn --host'. For example:

```
$ flatpak run --filesystem=host --talk-name=org.freedesktop.Flatpak --command=bash org.zim_wiki.Zim 
bash-4.4$ which git
which: no git in (/app/bin:/usr/bin:/app/texlive-bin:/app/texlive/bin)
bash-4.4$ flatpak-spawn --host which git
/usr/bin/git
bash-4.4$ flatpak-spawn --host git --version
git version 2.17.2
```

**Comment by Osndok** [comment]
@cheese I don't think it is Zim's responsibility to bend over backwards to support a flatpak distribution, it is far more likely that the flatpak maintainer just needs to add 'git' to the flatpak.

@RuubixO I'm glad you got it working! Did you ever report it to the flatpak maintainer? They might value the bug report. Also, consider closing this ticket, if you are satisfied with the current solution.

**Comment by cheese** [comment]
> @cheese I don't think it is Zim's responsibility to bend over backwards to support a flatpak distribution, it is far more likely that the flatpak maintainer just needs to add 'git' to the flatpak.
> 
I am the packager of that flatpak. As Zim plugins use too many external commands, bundling them all in the flatpak is a heavy job and hard to maintain. It Zim can call host command, it would be more flatpak-friendly.
For the special case of git, running flatpak under the Sdk runtime instead of Platform runtime is the easiest way to get git for Zim at present.

**Comment by RuubixO** [comment]
@cheese (btw your screen name is glorious) I'm not as familiar with Docker or flatpak as of yet--HostCommand is a component of which one of these two platforms?

**Comment by RuubixO** [comment]
@Osndok @cheese I would prefer to use the flatpak, since that would give me a clean way to update to newer versions down the road. I noticed the flatpak cli commands, what should I use to make flatpak more compatible?

**Comment by jaap-karssenberg** [comment]
Closing this issue, see #693 for follow up
