### ISSUE TITLE
Website up-to-dateness

### ISSUE THREAD

**Issue by Bogi30** [zim-desktop-wiki/zim-desktop-wiki#692]
Maybe it seems to you that it is only a very small detail, but I think that it is **really** important:
Directly on the home page it says: "Although zim now exists for over 3 years there is no "1.0" version yet."
On the "About"-page, you can read "(c) 2010-2014".

As I read this, I already thought: Another dead project! So propably not worth testing the program :-(

In order to not scare other users, please update the page soon!

Maybe it would also be advisable to put a date on the download page beside the version number?

**Comment by jaap-karssenberg** [comment]
Thanks for the prompt. Pushed changes into repository, will be visible on website with next release.
