### ISSUE TITLE
source visualizer color scheme

### ISSUE THREAD

**Issue by e-belair** [zim-desktop-wiki/zim-desktop-wiki#695]
Hi, Is that possible to custom the color scheme on the source visualizer plugin?
I'm using a dark theme and some of code is hard to see like this example:
![image](https://user-images.githubusercontent.com/596562/53723964-2123e700-3e69-11e9-97fc-a2cdcb16282b.png)
The blues line is hard to see

**Comment by Self-Perfection** [comment]
Looks like a duplicate of #544
