### ISSUE TITLE
imported files don't show up

### ISSUE THREAD

**Issue by tracing-home** [zim-desktop-wiki/zim-desktop-wiki#697]
After placing a folder with about 20 *.txt files into the ZIM folder only some files show up on next start. All the files are UTF8. At first they had names like: 2010-12-18-142147Z.html.txt They imported fine. For clarity I renamed them within Linux (mv a.txt b.txt) to a sensible name containing no spaces. Those names were extracted and cleaned up in a lua script which then batch renames the files. Initially about 10 files were properly seen.

example:

mv "./2010-11-8-104708Z.html.txt" 'Wie_lange_eine_Sache_dauert.txt'

Wie_lange_eine_Sache_dauert.txt
That did not show at first.

Creating a new page with exactly the same name within ZIM and pasting the name to the file causing issues, does not necessarily work. (using Krusader)

Zim 0.68-rc1 on Ubuntu.

I realize this is not strictly a ZIM problem, but something in the interaction between ZIM and the file system is not quite right

Thanks for any pointers
Martin

**Comment by jaap-karssenberg** [comment]
Try forcing an index update with "zim --index -V /path/to/notebook"

**Comment by jaap-karssenberg** [comment]
Need confirmation & how to reproduce in zim > 0.70
