### ISSUE TITLE
Import .JSON notes from Vivaldi(browser)

### ISSUE THREAD

**Issue by RealDrJester** [zim-desktop-wiki/zim-desktop-wiki#698]
I would like to request a feature, an ability to import Vivaldi's notes to ZIM(and export them for those who want it). They are in .json format. I'm switching from the native option to ZIM due to the massive size (around 80MB), and how much is dragging down the browser. 

Thank you in advance for considering this.

**Comment by jaap-karssenberg** [comment]
Good idea, but will close the ticket unless someone is actively working on this
