### ISSUE TITLE
Moving pages by drag and drop in index pane does not work on windows

### ISSUE THREAD

**Issue by jmoseman01** [zim-desktop-wiki/zim-desktop-wiki#70]
On windows when I try to drag and drop the pages in the side pane it won't work on windows 10.

**Comment by RoyalJL** [comment]
This also happens to me (Windows 10), I can't rearrange the pages. I am going to revert to the previous version until this bug is fixed.

**Comment by Osndok** [comment]
I assume that you are referring to moving pages (i.e. to a new parent), as opposed to simple reordering them (which is not supported ATM).

**Comment by RoyalJL** [comment]
Yes, I mean move pages through the "tree" hierarchy of the book. Also, I can't drag and drop from the side panel to a page to create a link.

**Comment by jaap-karssenberg** [comment]
Known issue, no clue how to solve.

**Comment by jaap-karssenberg** [comment]
See also #150

**Comment by jaap-karssenberg** [comment]
Testing with 0.70-RC1 this works on windows as well (windows 10).
