### ISSUE TITLE
How do I use a key combination for inserting equations?

### ISSUE THREAD

**Issue by evan54** [zim-desktop-wiki/zim-desktop-wiki#700]
For most of the items that don't have direct hotkeys I can use something like ALT+T M (eg instead of clicking on Tools > Evaluate Math).

However some of the selections don't correspond to a key, for example Insert > Equation.

Is there a way to assign a hotkey to something like this?

**Comment by Osndok** [comment]
There is an old gnome feature (that I think the have or are removing) that lets you easily assign your own shortcuts (see #81 & #211), but if those don't work you could just patch your local install... adding a shortcut to a menu item is pretty straight forward, but it would get clobbered on every update.

**Comment by evan54** [comment]
sorry if this is very obvious but is there an easy way to see which part of the code I would need to patch? I'm not too familiar with which part of the code I would need to change, my thinking is that I'd need to find the part of the code that creates the "M" shortcut in my example above for the "evaluate math" and copy it over wherever the "Equation" part in the menu is created

**Comment by Osndok** [comment]
Ahh... looks like I spoke too soon... the equation editor uses the ```ImageGeneratorPlugin``` base class, which would make it a bit tricky to add an accelerator (not a one-line tweak). :(

**Comment by jaap-karssenberg** [comment]
The accelerator mapping is stored in `zim/.config/accelmap` that file can be modified to change them

**Comment by fanaticode** [comment]
> The accelerator mapping is stored in `zim/.config/accelmap` that file can be modified to change them

Simply editing the file and uncommenting didn't work. 
For this to work the setting  `gtk-can-change-accels=1` needs to be added in the file `~/.gtkrc-2.0`

However this syntax is depreciated since gtk-3.10 
This setting needs to be activated and the best way is to use  `dconf-editor` and search for `can-change-settings`.

It should work after this.
