### ISSUE TITLE
Tab alignment is offset by bold font

### ISSUE THREAD

**Issue by hsandt** [zim-desktop-wiki/zim-desktop-wiki#703]
Making the text preceding some tabs bold will increase the resulting width of the text, while keeping the same tab space as when the text was not bold, resulting in offsetting the following text a bit to the right.

The offset cumulates if multiple texts are made bold between tabs.

This makes it hard to make a table using tabs while making the headers bold. (I know there is a table plugin but it's not convenient to use when I don't need the heavy header/sorting feature, and there is that bug #591 too)

Example of tab-based hand-made table: 
![grafik](https://user-images.githubusercontent.com/1067772/54085541-356b5680-4337-11e9-920f-c5fd22339618.png)

Now if the headers are bold:
![grafik](https://user-images.githubusercontent.com/1067772/54085546-4320dc00-4337-11e9-9b21-63c96f254079.png)

**Comment by jaap-karssenberg** [comment]
Yes, afraid that is "won't fix" - never expect tab alignment to work without fixed with font

**Comment by hsandt** [comment]
I'll add this workaround for people having this issue: add a space before the first bold character, at the beginning of the line:

![image](https://github.com/zim-desktop-wiki/zim-desktop-wiki/assets/1067772/e3b72c30-9f87-412b-a368-0665bca7da16)

Since it's that simple, I wonder if we could not have an option to just simulate that, by having a fixed indent size independent of the first character's size and font.

**Comment by hsandt** [comment]
I found two new workarounds:
- use monospace font, by switching to verbatim lines. Unfortunately, multiline verbatim `pre` blocks do not support bold font, so in this case, only single line verbatim `code` block will work. You need to remember to re-apply verbatim on each new line (press Ctrl+T before filling the line). See https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/2419#issuecomment-1661967817
- set [TextView] tabs=[value] in config for a fixed tabs value in pixels (in my case, I picked 39 which was perfect for 4 characters of monospace font Fira Code at scale 0.8, but YMMV). There is no measurement in number of characters, so make sure to pass a big number in the range 20-80 or so, so a small number like 2 or 4. Apparently, this fixes the issue even with non-monospace fonts!

Demo using single-line verbatim + non-verbatim with fixed tabs value:

![image](https://github.com/zim-desktop-wiki/zim-desktop-wiki/assets/1067772/71c46916-f982-4b23-9ce7-2b6f18e79d21)

**Comment by jgneff** [comment]
> I'll add this workaround for people having this issue: add a space before the first bold character, at the beginning of the line:

Even the zero-width space (U+200B) does the trick, and you can't even see it. Works very nicely. Thanks for the hint.
