### ISSUE TITLE
Feature Request: "Include Page Content" (from some other page into "this" page)

### ISSUE THREAD

**Issue by CharlieJV** [zim-desktop-wiki/zim-desktop-wiki#712]
G'day,

First: I've only been playing around with ZIM for the last few days.  WOW !  I love this thing!

The most useful thing (well, for the way my mind works...) I'd love to see added to ZIM: the ability to "include" content from some other page into the currently viewed page.

For example, thinking of maintaining a change log for software:

Say I create a software update page on 2019-03-15 (a Journal entry, NICE !).

I also have a "Recent Updates" page, to which I'd like to include the contents from the "2019-03-15" page (along with the last few software updates.)

I also have a "Work Log 2019" page, and it includes the content from every page for the year.

It would be good for included content to show the content comes from some other page (maybe a very light-grey border around the content), and it would be pretty sweet if a click of that content opened up the page of origin.  It would also be awesome if that included content appeared in exports too.

Cheers and best regards !

**Comment by jaap-karssenberg** [comment]
For me this is a "won't fix" as the idea is very broad and therefore hard to capture. Rendering content of many pages together is non trivial to get right from a performance point of view.

May I suggest thinking about the usage of tags to address your use case?  Else a plugin could be thought up that relates pages based on some criteria and shows links or line items without loading the full content.
