### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by shafeeq8085** [zim-desktop-wiki/zim-desktop-wiki#713]
Hallo Team,

Whether Fonts works in ZIM? Could you please let me know some details?

Thanks,
Shafeeque

**Comment by jaap-karssenberg** [comment]
What is your question precisely?

**Comment by shafeeq8085** [comment]
Hallo,
I would like to have font 'AREAL Monospace' in my ZIM portable version, but i cannot see an option for selecting the Font in my ZIM. Is there an option or should i use a diffrent version ?

**Comment by jaap-karssenberg** [comment]
Afraid I can't help you there as this is not Zim specific. Fonts are part
of system install of Gtk. In the portable version a number of default fonts
will be included but no idea how to extend. But also for regular install
you will have to c check Gtk install docs for fonts.

Regards,

Jaap

Op di 19 mrt. 2019 10:56 schreef shafeeque Kandy <notifications@github.com>:
