### ISSUE TITLE
(cosmetic) Index tree: context menu doesn't have "New Sub Page..."

### ISSUE THREAD

**Issue by alk0** [zim-desktop-wiki/zim-desktop-wiki#723]
Linux Mint 19.1 Cinnamon, zim 0.70~ubuntu18.04.1 from ppa:jaap.karssenberg/zim

Index tree: context menu doesn't have "New Sub Page..." anymore. Is there a reason for it?

![2019-03-29-035831](https://user-images.githubusercontent.com/10332037/55198266-2d386580-51d7-11e9-825b-db0dd781d8ca.png)

**Comment by jaap-karssenberg** [comment]
Yes, "new page" now fills in the path of the selected page, so it doubles for both "new page" and "new sub page"
