### ISSUE TITLE
No index side pane after upgrade to 0.70

### ISSUE THREAD

**Issue by banan314** [zim-desktop-wiki/zim-desktop-wiki#726]
I can see no index side pane after I upgraded to release 0.70, although it was before the upgrade. 

![image](https://user-images.githubusercontent.com/17968722/55239257-93a0a080-5236-11e9-97ed-b20b93d52c89.png)

### I solved by adding `Page Index` plugin.
![image](https://user-images.githubusercontent.com/17968722/55239287-a87d3400-5236-11e9-9fae-6053eb5c16c1.png)

Anyway, it's a strange behaviour. The upgrade to 0.70 shouldn't remove the page index.

**Comment by pmarlowe99** [comment]
Had same problem after upgrade to .70 on Xubuntu 18.04. The page index plug in worked.

**Comment by jaap-karssenberg** [comment]
Yes, the changelog mentions this, you need to enable the plugin. Zim tries to do this for you when upgrading, but not 100% fool proof I'm afraid.
