### ISSUE TITLE
Task List plugin from previous version?

### ISSUE THREAD

**Issue by fladd** [zim-desktop-wiki/zim-desktop-wiki#729]
It seems the task list plugin in 0.7.0 misses some essential feature from the one in 0.6.9: The ability to define keywords in addition to tags. This is essential to my workflow (as it allows to implement a pretty decent GTD system with Zim). Where can I get the previous version of the task list plugin and how can I install it into 0.7.0?

**Comment by Self-Perfection** [comment]
Have you checked "File -> Properties -> Tas List"? Missing features might be there.

Several plugins in 0.70 made their settings notebook properties instead of global settings for whole zim.

**Comment by fladd** [comment]
Indeed, the setting has been moved. Thanks!
