### ISSUE TITLE
Keybinding to copy line

### ISSUE THREAD

**Issue by Rafal1** [zim-desktop-wiki/zim-desktop-wiki#730]
Minor issue but extremely useful. Could you tell me if is it a convenient way to copy a whole line of text in zim?

**Comment by jaap-karssenberg** [comment]
No such keybinding is implemented at the moment.

**Comment by sojusnik** [comment]
The line sorter plugin does this. You can configure the keyboard shortcut in ~/.config/zim/accelmap

**Comment by jaap-karssenberg** [comment]
It has a "duplicate line" - I read the request as a "copy line to clipboard"

**Comment by sojusnik** [comment]
@jaap-karssenberg True!

**Comment by Self-Perfection** [comment]
@Rafal1 though there is no "single shortcut" general text editor navigation works. So you can press:
Home -> Shift+End -> Ctrl-C

Or with mouse: triple click on any word in line to copy -> right click -> "copy"

**Comment by Rafal1** [comment]
Thank you for your answers, the issue was "copy line to clipboard" :).
