### ISSUE TITLE
Exception thrown when right-clicking in the index pane in 0.70

### ISSUE THREAD

**Issue by nasedil** [zim-desktop-wiki/zim-desktop-wiki#731]
In zim 0.70, every time I right-click in the index pane it does nothing but showing crash report (in ppa version) or nothing happens (when running from source).  When running `XDG_CONFIG_HOME=/tmp zim -V -D`, there's the following:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/gui/widgets.py", line 563, in do_button_press_event
    menu.popup_at_pointer(event)
AttributeError: 'Menu' object has no attribute 'popup_at_pointer'
```

OS: UbuntuStudio 16.04 (xfce4 desktop), Python 3.5.2

### Full debug output when running from source
```
/tmp/zim-desktop-wiki$ XDG_CONFIG_HOME=/tmp XDG_DATA_HOME=/tmp XDG_CACHE_HOME=/tmp ./zim.py -V -D
INFO: This is zim 0.70
DEBUG: Python version is sys.version_info(major=3, minor=5, micro=2, releaselevel='final', serial=0)
DEBUG: Platform is posix
DEBUG: Running from a source dir: /tmp/zim-desktop-wiki
DEBUG: Set XDG_DATA_HOME to /tmp
DEBUG: Set XDG_DATA_DIRS to [<Dir: /usr/share/ubuntustudio>, <Dir: /usr/share/xfce4>, <Dir: /usr/local/share>, <Dir: /usr/share>, <Dir: /var/lib/snapd/desktop>, <Dir: /var/lib/snapd/desktop>, <Dir: /usr/share>]
DEBUG: Set XDG_CONFIG_HOME to /tmp
DEBUG: Set XDG_CONFIG_DIRS to [<Dir: /etc/xdg/xdg-ubuntustudio>, <Dir: /usr/share/upstart/xdg>, <Dir: /etc/xdg>, <Dir: /etc/xdg>]
DEBUG: Set XDG_CACHE_HOME to /tmp
DEBUG: Connecting to /tmp/zim-genio/primary-0.70-a040bd60
DEBUG: Got error in dispatch: No such file or directory
DEBUG: Starting primary process
DEBUG: Start listening on: /tmp/zim-genio/primary-0.70-a040bd60
DEBUG: Loading config from: <zim.notebook.info.VirtualFile object at 0x7f1b4582eef0>
DEBUG: Loading config from: /tmp/notes/notebook.zim
DEBUG: Loading config from: /tmp/notes/notebook.zim
DEBUG: Operational error, init tabels
DEBUG: (Re-)Initializing database for index
DEBUG: Loading config from: /tmp/zim/notebook-tmp_notes/state.conf
DEBUG: New extendable: <zim.notebook.notebook.Notebook object at 0x7f1b4583ad30>
DEBUG: Load extension: <class 'zim.plugins.journal.JournalNotebookExtension'>
DEBUG: Load extension: <class 'zim.plugins.tasklist.TaskListNotebookExtension'>
DEBUG: Load extension: <class 'zim.plugins.versioncontrol.VersionControlNotebookExtension'>
INFO: No VCS detected
DEBUG: Loading config from: <ConfigFile: /tmp/zim/style.conf>
DEBUG: Autosave interval: 15 - use threads: True
DEBUG: New extendable: <pageview.PageView object at 0x7f1b457db438 (zim+gui+pageview+PageView at 0x317e6c0)>
DEBUG: Load extension: <class 'zim.plugins.arithmetic.ArithmeticPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.attachmentbrowser.AttachmentBrowserWindowExtension'>
DEBUG: Load extension: <class 'zim.plugins.backlinkpane.BackLinksPanePageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.inlinecalculator.InlineCalculatorPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.insertsymbol.InsertSymbolPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.journal.JournalPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.linesorter.LineSorterPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.pageindex.PageIndexPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.printtobrowser.PrintToBrowserPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.screenshot.ScreenshotPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.tableofcontents.ToCPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.tags.TagsPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.tasklist.TaskListPageViewExtension'>
DEBUG: Action: toggle_panes(False)
DEBUG: Action: toggle_panes(True)
INFO: Open page: Home (Home)
DEBUG: New extendable: <mainwindow.MainWindow object at 0x7f1b4582de58 (zim+gui+mainwindow+MainWindow at 0x314c240)>
DEBUG: Load extension: <class 'zim.plugins.bookmarksbar.BookmarksBarMainWindowExtension'>
DEBUG: Load extension: <class 'zim.plugins.pathbar.PathBarMainWindowExtension'>
DEBUG: Load extension: <class 'zim.plugins.trayicon.TrayIconMainWindowExtension'>
DEBUG: Loading config from: <zim.notebook.info.VirtualFile object at 0x7f1b452b32b0>
DEBUG: Loading config from: /tmp/notes/notebook.zim
DEBUG: Add window: AppIndicatorTrayIcon
DEBUG: Load extension: <class 'zim.plugins.versioncontrol.VersionControlMainWindowExtension'>
DEBUG: Accelmap: /tmp/zim/accelmap
DEBUG: Opening ProgressDialog: Updating index
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck found out-of-date
DEBUG: Index folder: /tmp/notes
DEBUG: Index file: /tmp/notes/Home.txt
DEBUG: Index file: /tmp/notes/notebook.zim
DEBUG: Add window: MainWindow
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck finished
Traceback (most recent call last):
  File "/tmp/zim-desktop-wiki/zim/gui/widgets.py", line 563, in do_button_press_event
    menu.popup_at_pointer(event)
AttributeError: 'Menu' object has no attribute 'popup_at_pointer'
DEBUG: Action: quit
DEBUG: Remove window: AppIndicatorTrayIcon
DEBUG: Remove window: MainWindow
DEBUG: Last toplevel destroyed, quit
DEBUG: Remove window: AppIndicatorTrayIcon
DEBUG: Last toplevel destroyed, quit
```

**Comment by jaap-karssenberg** [comment]
What Gtk version do you have?

This method was introduced in gtk 3.22, so probably needs a fallback for older Gtk versions

**Comment by tildagail** [comment]
I have this problem too on xubuntu 16.04, with gtk version 3.18.9.

**Comment by nasedil** [comment]
Checked my gtk3 version, also have 3.18.9.

**Comment by olissongs** [comment]
any workarounds for that, while waiting for .71?

**Comment by tildagail** [comment]
I ended up just reinstalling 0.69.1 for now. Alternatively, there's supposed to be a fix in the snapshots repository (didn't work on my computer, though). Or, upgrade to an OS version that has the gtk3.22.

**Comment by olissongs** [comment]
ok done.
uninstalled .70
dropped ppa
apt update
installed .69.1 from download.

works again, thanks.

**Comment by demaddis** [comment]
Although there are no more exceptions, right-clicking on the index items in Zim 0.71 (from ppa) on Ubuntu 16.04 (gtk 3.18.9) does not bring up a menu.

**Comment by jaap-karssenberg** [comment]
Please check the error log (zim --debug) for errors when you perform this
click.

-- Jaap

**Comment by demaddis** [comment]
Sorry, should have mentioned this earlier: there is no debug output on click.

> Please check the error log (zim --debug) for errors when you perform this click.

**Comment by olissongs** [comment]
ok tested .71 from ppa

no error on roght click anymore, but no right-click-menu shown. behavier as before .70

my debug log (some data deletion)

INFO: This is zim 0.71.0
DEBUG: Python version is sys.version_info(major=3, minor=5, micro=2, releaselevel='final', serial=0)
DEBUG: Platform is posix
DEBUG: Not running from a source dir
DEBUG: Set XDG_DATA_HOME to /home/oliver/.local/share
DEBUG: Set XDG_DATA_DIRS to [<Dir: /home/oliver/.local/share/flatpak/exports/share>, <Dir: /var/lib/flatpak/exports/share>, <Dir: /usr/share/ubuntu>, <Dir: /usr/share/gnome>, <Dir: /home/oliver/.local/share/flatpak/exports/share>, <Dir: /var/lib/flatpak/exports/share>, <Dir: /usr/local/share>, <Dir: /usr/share>, <Dir: /var/lib/snapd/desktop>, <Dir: /var/lib/snapd/desktop>]
DEBUG: Set XDG_CONFIG_HOME to /home/oliver/.config
DEBUG: Set XDG_CONFIG_DIRS to [<Dir: /etc/xdg/xdg-ubuntu>, <Dir: /usr/share/upstart/xdg>, <Dir: /etc/xdg>]
DEBUG: Set XDG_CACHE_HOME to /home/oliver/.cache
DEBUG: Connecting to /tmp/zim-oliver/primary-0.71.0-e63203e4
DEBUG: Got error in dispatch: No such file or directory
WARNING: Could not find all icon sizes for the application icon
DEBUG: Starting primary process
DEBUG: Start listening on: /tmp/zim-oliver/primary-0.71.0-e63203e4
DEBUG: Loading config from: <zim.notebook.info.VirtualFile object at 0x7f04340470b8>
DEBUG: Loading config from: notebook.zim
DEBUG: Loading config from: notebook.zim
<DELETED FROM ME>
DEBUG: Opening dialog "Notizbuch öffnen"
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
DEBUG: Opening dialog "Notizbuch öffnen"
DEBUG: Dialog response OK
DEBUG: Closed dialog "Notizbuch öffnen"
DEBUG: Loading config from: notebook.zim
DEBUG: Loading config from: state.conf
DEBUG: New extendable: <zim.notebook.notebook.Notebook object at 0x7f0424f10ba8>
DEBUG: Load extension: <class 'zim.plugins.journal.JournalNotebookExtension'>
DEBUG: Load extension: <class 'zim.plugins.tasklist.TaskListNotebookExtension'>
DEBUG: Loading config from: <ConfigFile: /home/oliver/.config/zim/style.conf>
DEBUG: Autosave interval: 10 - use threads: True
DEBUG: New extendable: <pageview.PageView object at 0x7f0424f204c8 (zim+gui+pageview+PageView at 0x1f146c0)>
DEBUG: Load extension: <class 'zim.plugins.arithmetic.ArithmeticPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.attachmentbrowser.AttachmentBrowserWindowExtension'>
DEBUG: Load extension: <class 'zim.plugins.inlinecalculator.InlineCalculatorPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.insertsymbol.InsertSymbolPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.journal.JournalPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.pageindex.PageIndexPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.printtobrowser.PrintToBrowserPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.screenshot.ScreenshotPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.tableofcontents.ToCPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.tasklist.TaskListPageViewExtension'>
DEBUG: Action: toggle_panes(False)
DEBUG: Action: toggle_panes(True)
INFO: Open page: xxx (xxx:getTermine)
DEBUG: New extendable: <mainwindow.MainWindow object at 0x7f0424fe6b40 (zim+gui+mainwindow+MainWindow at 0x1fa2720)>
DEBUG: Load extension: <class 'zim.plugins.distractionfree.DistractionFreeMainWindowExtension'>
DEBUG: Load extension: <class 'zim.plugins.pathbar.PathBarMainWindowExtension'>
DEBUG: Accelmap: /home/oliver/.config/zim/accelmap
DEBUG: Add window: MainWindow
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck finished
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck finished
INFO: Open page: xxx :registerLead (xxx:registerLead)
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck finished
INFO: Open page: xxx (xxx)
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck finished

**Comment by olissongs** [comment]
should this be reopened?

**Comment by jaap-karssenberg** [comment]
Only if you have errors that are indeed the same error as above.

Op vr 26 apr. 2019 16:56 schreef olissongs <notifications@github.com>:

**Comment by jaap-karssenberg** [comment]
Just re-tested and popup menu works with both versions - so definitely this one is fixed. Popup not showing is something new.

**Comment by jaap-karssenberg** [comment]
See issue #816 for follow up
