### ISSUE TITLE
Jump-to completion is broken for some letters (й, ё, å, probably more) in 0.70

### ISSUE THREAD

**Issue by nasedil** [zim-desktop-wiki/zim-desktop-wiki#732]
In Zim 0.70 I've noticed that whenever I type letter `й` into 'jump to' dialog, it stops showing suggestions (even though there are many pages which match).  Interestingly enough, same goes for letter `ё` (both from Cyrillic), and for `å` (from Norwegian), and probably these are not the only letters for which search is broken.  All these letters are in fact proper letters in the respective alphabets, and search works correctly in Zim versions prior to 0.70.

OS: UbuntuStudio 16.04 (xfce4 desktop), Python 3.5.2

**Comment by jaap-karssenberg** [comment]
In my tests with random unicode this seems to work. What gtk version are you using?

**Comment by sojusnik** [comment]
See also https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/84#issuecomment-460991400

**Comment by nasedil** [comment]
@jaap-karssenberg here is my gtk3 version:
```
libgtk-3-0:
  Installed: 3.18.9-1ubuntu3.3
  Candidate: 3.18.9-1ubuntu3.3
```

**Comment by robertvazan** [comment]
I can confirm this bug in 0.70 as shipped by flathub.org and running under latest Fedora. The issue affects all non-ASCII characters: š, á, ľ, ...

**Comment by jaap-karssenberg** [comment]
Since I have no keyboard setup for typing non-ascii characters. So I test
by copy pasting characters from the page into the entry. In my testing
there is no issue. Could someone compare copy-paste characters versus
typing characters?

Thanks,

Jaap

**Comment by robertvazan** [comment]
I tested it. There's no difference between copy-n-paste and direct typing. BTW, foreign keyboard layout is trivial to setup on both Windows and Linux.

**Comment by jaap-karssenberg** [comment]
In that case the next question is why it works in my testing (both Linux &
window) and doesn't work for you. E.g. what exact locale settings are you
using?

Just to be fully unambiguous my testing sequence is:
- insert some greek letters using the "insert symbol" plugin
- turn text into link
- copy first letter
- open "jump to" dialog
- paste
- result: completion shows full link

Tested on both Linux and Windows with default (English) locale and UTF-8
encoding.

-- Jaap

**Comment by robertvazan** [comment]
Greek letters work for me. Try page name žžž.

If that doesn't help, try the flatpak from flathub.org for a well-isolated testing environment.

I am running it with Wayland socket blocked due to #746:
`sudo flatpak override --nosocket=wayland org.zim_wiki.Zim`

Regional settings: language = English, formats = Slovakia, input sources = English+Slovak

If that doesn't help reproduce the problem, try to run a VM with fresh install of the latest Fedora.

**Comment by jaap-karssenberg** [comment]
OK, so it does not affect _all_ non-ascii letter. Might be that only
non-ascii letters with an accent are affected.

That helps :)

**Comment by jaap-karssenberg** [comment]
See #84 for follow up
