### ISSUE TITLE
Table of contents plugin is not working when floating option is chosen in 0.70

### ISSUE THREAD

**Issue by nasedil** [zim-desktop-wiki/zim-desktop-wiki#733]
When 'show ToC as floating widget' is selected it is not shown at all in zim 0.70.

OS: UbuntuStudio 16.04 (xfce4 desktop), Python 3.5.2

**Comment by jaap-karssenberg** [comment]
Do you get any error messages?

**Comment by nasedil** [comment]
@jaap-karssenberg I've ran it with `-V -D` arguments, but got no error messages.  When I changed configuration back to 'pane' and then again to 'float' here's the output:
```
DEBUG: Opening dialog "Preferences"
DEBUG: Loading description for plugin: tableofcontents
DEBUG: Opening dialog "Configure Plugin"
DEBUG: Dialog response OK
DEBUG: Closed dialog "Configure Plugin"
DEBUG: Opening dialog "Configure Plugin"
DEBUG: Dialog response OK
DEBUG: Closed dialog "Configure Plugin"
DEBUG: Dialog response OK
DEBUG: Closed dialog "Preferences"
```

**Comment by nasedil** [comment]
Gtk3 is version 3.18.9

**Comment by lyrz** [comment]
Same problem happened with Zim version 0.70 and now with version 0.71 on my system.
Linux Mint 18.3 KDE 64-bit-based on ubuntu 16.04.1
KDE plasma 5.8.9 - KDE frameworks 5.36.0 - Qt 5.6.1
Python 3.5.2 - Gtk version 3.18.9
Debugging v 0.71 same as nasedil when changing from 'pane' to 'float'.
No error output when unloading/reloading plugin with 'float' option active.

**Comment by lyrz** [comment]
Seems to be a Gtk Problem as I upgraded Gtk to 3.20.8 and I can now seem my floating ToC :-)

**Comment by salaun-urennes1** [comment]
I have the same problem with Zim 0.72.0 on ubuntu 16

**Comment by unndreay** [comment]
Same with Zim 0.72.1 on Mint 18.3 with GTK 3.18.9. The cursor changes its appearance from caret to arrow when moving to the place where I would expect the widget. Even clicks on this place let the textview jump to the heading that has been clicked. Clicking a little lower or upper let the textview jump to the respective preceding or succeeding heading. It seems that the widget exists. It is just not visible.

**Comment by jaap-karssenberg** [comment]
Last version the rendering of the ToC was changed. Please confirm whether this is still happening with version >= 0.74.3

See commit 660e574d37c81c3e215cdbc1f7b7f1f2f86c1fdf

**Comment by lyrz** [comment]
Hello, I upgraded my system, I now use Linux Mint 20.2 Mate (w Python 3.8.10 and Gtk 3.24.20). On this system Zim (v0.74.3) and the TOC plugin are working fine.
