### ISSUE TITLE
Double-up of backlinks button?

### ISSUE THREAD

**Issue by tildagail** [zim-desktop-wiki/zim-desktop-wiki#735]
When the BackLinks plugin is enabled, there are 2 backlinks buttons in the statusbar. The 2 buttons are shown in the screenshot below. Disabling the BackLinks plugin only removes the button labelled 'BackLinks', not the one that says '0 Backlinks'.

![zim backlinks buttons](https://user-images.githubusercontent.com/14209557/55330637-3ed28380-54dd-11e9-880e-5b7032b50009.jpg)

When pressed, 'BackLinks' opens the backlinks pane. The other ('0 Backlinks') seems to do nothing and causes an error in Zim -D

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/gui/mainwindow.py", line 941, in popup_menu
    MenuButton.popup_menu(self, event)
  File "/usr/lib/python3/dist-packages/zim/gui/widgets.py", line 802, in popup_menu
    self.menu.popup_at_widget(self, Gdk.Gravity.NORTH_WEST, Gdk.Gravity.SOUTH_WEST, event)
AttributeError: 'Menu' object has no attribute 'popup_at_widget'

The error message seems likely to be related to the gtk issue mentioned in #731, where the gtk version required is 3.22, but ubuntu 16.04 only goes up to 3.19. I have xubuntu 16.04, so using the older gtk.

1. Does this look the same on newer gtk versions? (I'm guessing no...)
2. Is it correct for the '0 backlinks' button to still display when the plugin is deactivated, and does this also happen on newer versions?

**Comment by jaap-karssenberg** [comment]
Yes, this is correct. There is a building button for backlink menu and there is the plugin tab. Agree it would be nice to integrate the two, but works as intended.

Error is indeed double of #731
