### ISSUE TITLE
Search GUI button locale

### ISSUE THREAD

**Issue by spinone** [zim-desktop-wiki/zim-desktop-wiki#736]
Since updating to v0.7 (running on Ubuntu 16.04), the Zim Search GUI shows buttons labelled "mégse" and "keresés" instead of Cancel and Search. Other button titles are in English. My locale is set correctly [ locale.setlocale(locale.LC_ALL, '') gives me 'en_GB.UTF-8' ] and is included in the [locale -a] listing and is picked up properly in \_\_init\_\_.py.
![image](https://user-images.githubusercontent.com/15798560/55332317-07d48180-548d-11e9-8f87-23c33f7a3cd2.png)

**Comment by jaap-karssenberg** [comment]
Probably a double of #664
