### ISSUE TITLE
journal template does not see calendar_plugin.page_type variale

### ISSUE THREAD

**Issue by alpinekid** [zim-desktop-wiki/zim-desktop-wiki#737]
Using ver 0.70; ubuntu 16.4 
repository; jaap.karssenberg
plugin: journal
The old template file no longer works.
The variable **calendar_plugin.page_type** is set to none.
This was used to get the type of page, [day, week, month, year] and adjust the journal page template.
The template file is still found but this variable is always none.
Not sure how the reference to calender plugin applies, I dont see a plugin named calendar.
I also dont see the calenda
[Journal.txt](https://github.com/zim-desktop-wiki/zim-desktop-wiki/files/3030070/Journal.txt)
r widget.

The work around for now is to use the else clause but that defeats the purpose of having different journal views based on how the journal is viewed.

**Comment by Self-Perfection** [comment]
In release 0.70 calendar plugin [was renamed to journal](https://github.com/zim-desktop-wiki/zim-desktop-wiki/commit/4dc1a5368f570b5c26b110c43d5c8e12001f8884), and this variable was renamed accordingly to `journal_plugin.page_type`.

**Comment by jaap-karssenberg** [comment]
fix merged
