### ISSUE TITLE
can't move items in index view to any sub folder

### ISSUE THREAD

**Issue by galenthurber** [zim-desktop-wiki/zim-desktop-wiki#739]
also after creating a sub page it immediately moves to root folder, it should stay where it is created.

also getting several program crashes, tried restarting, still a problem
note: bleachbit was not used to wipe /tmp folder

0.70 Linux

**Comment by jaap-karssenberg** [comment]
Please submit 1 issue per ticket and include all relevant details like how to reproduce, any error messages, etc.

**Comment by galenthurber** [comment]
thanks for closing this
