### ISSUE TITLE
Source View - Python-sourceview2 no longer developed

### ISSUE THREAD

**Issue by rakor** [zim-desktop-wiki/zim-desktop-wiki#740]
Hey there,

i installed zim on debian-buster. I can not activate the Source View plugin.

The Pluginbrowser says gtksourceview2 is needed.

currently installed is:
libgtksourceview-3.0-1
libgtksourceview-3.0-common
libgtksourceview2.0-0
libgtksourceview2.0-common

python-gtksourceview2 is not available in debian-buster, because it is not active developed anymore. See: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=878698

**Comment by jaap-karssenberg** [comment]
As of zim 0.70 we moved to python3

**Comment by Erriez** [comment]
Solution for Zim 0.72.1 on Ubuntu 20.04 is to install `libgtksourceview-3.0`:

```
sudo apt-get install libgtksourceview-3.0
```

Restart Zim and `Source View` plugin can be enabled in the `Edit | Preferences | Plugins` menu.

**Comment by lucvtzel** [comment]
may be (cf. #975):

    $ sudo apt-get install gir1.2-gtksource-3.0
