### ISSUE TITLE
can't move items in index view to any sub folder 

### ISSUE THREAD

**Issue by galenthurber** [zim-desktop-wiki/zim-desktop-wiki#741]
version 0.70
attempting to move an item from one folder to another.
item will not move

including movie .zip
[zim070-bug-2019-04-01_18.mkv.zip](https://github.com/zim-desktop-wiki/zim-desktop-wiki/files/3031342/zim070-bug-2019-04-01_18.mkv.zip)

**Comment by jaap-karssenberg** [comment]
Double of #390
