### ISSUE TITLE
Bookmarks popup menu does not appear on right click in v7.0

### ISSUE THREAD

**Issue by bkilinc** [zim-desktop-wiki/zim-desktop-wiki#742]
Cannot delete or edit bookmarks, because bookmarks popup menu does not appear when right clicking on bookmarks. Also right click does not work on Plus sign. 
Correct behavour should be
"If right mouse button is pressed on a bookmark in the bar the popup menu will appear."
"If right mouse button is pressed on the "Plus button" in the bar the popup menu will appear."
https://zim-wiki.org/manual/Plugins/BookmarksBar.html

**Comment by jaap-karssenberg** [comment]
Double of #731
