### ISSUE TITLE
Editable accelerators / keybindings

### ISSUE THREAD

**Issue by multixrulz** [zim-desktop-wiki/zim-desktop-wiki#743]
It seems that zim just recently moved to gtk3.  As a result, the free "editable accelerators" that gtk2 supplied don't work anymore, and zim needs to implement this itself to get the feature back.

I used to use a few of these, and now there's no way to get an accelerator for things like "remove line", which I used quite heavily.

**Comment by jaap-karssenberg** [comment]
Have a look in the manual about the "accelmap" configuration

**Comment by multixrulz** [comment]
I didn't find anything in the manual about that (by doing a websearch within zim-wiki.org), but I did find a reference in this bug tracker.

Within my ~/.config/zim/accelmap file is this line
`(gtk_accel_path "<Actions>/MainWindowExtension/remove_line" "<Primary>y")`
But this key combination has no effect within zim 0.70-2 on ArchLinux, gtk3 version 1:3.24.7+25+g17665f06e3-1.  And yes, the line-sorter plugin is active and the menu item for "remove line" is displayed.

**Comment by sojusnik** [comment]
That's strange. I've noticed that some actions changed after upgrading to 0.7. The corresponding entry looks like the following now:

`(gtk_accel_path "<Actions>/LineSorterPageViewExtension/remove_line" "<Primary>y")`

Pay attention to remove the `;` before that line and it should work, it does at least here, with the recent version from the Launchpad PPA on Ubuntu 18.10.

**Comment by multixrulz** [comment]
OK, so the accelmap file _is_ being used, but I had an incorrect action path.  I tried renaming the file and restarting Zim, but that didn't recreate it.  How does one work out how to create this file?  It doesn't seem to be documented anywhere, and reading the source code doesn't make it immediately obvious.

Nevertheless, my problem is solved, so this ticket can be closed if you like.

**Comment by AKSoo** [comment]
> OK, so the accelmap file _is_ being used, but I had an incorrect action path. I tried renaming the file and restarting Zim, but that didn't recreate it. How does one work out how to create this file? It doesn't seem to be documented anywhere, and reading the source code doesn't make it immediately obvious.
> 
> Nevertheless, my problem is solved, so this ticket can be closed if you like.

Just wanted to note that accelmap does not regenerate after deletion.
