### ISSUE TITLE
Added files do not show up

### ISSUE THREAD

**Issue by uspoma** [zim-desktop-wiki/zim-desktop-wiki#744]
Hello!

Thanks for the great work. I installed version 0.70 today (took your provided deb) over an old 0.68 installation.

Now, when I press the 'Attach files' button I get the file selector and select a pdf to add to a page.
I can see something like this in the terminal: 

> Copy /home/xx/xx/Book.pdf to /home/xx/.local/share/zim/books/Book.pdf

This obviously works, however in zim the attached file does not show up. There's just nothing to see. What the problem here?

**Comment by jaap-karssenberg** [comment]
What do you expect to see ?

**Comment by uspoma** [comment]
Good question. I expect to see this blue link to the file like it was with version 0.68. This is the thing that is missing. Is this supposed to be like this in version 0.70?

**Comment by jaap-karssenberg** [comment]
Dev notes:
  * Regression because previous behavior was to insert a link in the pageview
  * Requires "attach_file" to be a pageview action
  * Move it to the "insert" menu as well
  * To attach without inserting link, look at functions in the Attachmentsbrowser

**Comment by eAndrius** [comment]
Seems like https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/931 is copy of the same problem.
