### ISSUE TITLE
Multiple errors dealing with notes in label-view

### ISSUE THREAD

**Issue by Roboron3042** [zim-desktop-wiki/zim-desktop-wiki#745]
EDIT: When i first reported the issue i thought i was working in the "classic" tree view, but now zim opens with the label view as default. I was confused by this (please consider changing this), so you can ignore my complaints about zim not showing my notes and go directly to the errors  when you try to create/rename/move a note while you are in label-view.

_Outdated info_

> I've found Zim to be unusable in the current version with my previous notebooks. Zim can't even open my main notebook and return the following error:
> 
> > This is zim 0.70
> > Platform: posix
> > Locale: es_ES UTF-8
> > FS encoding: utf-8
> > Python: (3, 7, 3, 'final', 0)
> > PyGObject: (3, 32, 0)
> > 
> > ======= Traceback =======
> >   File "/usr/lib/python3.7/site-packages/zim/gui/widgets.py", line 2997, in do_response
> >     destroy = self.do_response_ok()
> >   File "/usr/lib/python3.7/site-packages/zim/gui/notebookdialog.py", line 367, in do_response_ok
> >     self.callback(self.result)
> >   File "/usr/lib/python3.7/site-packages/zim/gui/uiactions.py", line 134, in open_notebook
> >     ZIM_APPLICATION.run('--gui', uri)
> >   File "/usr/lib/python3.7/site-packages/zim/main/__init__.py", line 684, in run
> >     self._run_cmd(cmd, args) # test seam
> >   File "/usr/lib/python3.7/site-packages/zim/main/__init__.py", line 695, in _run_cmd
> >     w = cmd.run()
> >   File "/usr/lib/python3.7/site-packages/zim/main/__init__.py", line 277, in run
> >     return self._run_new_window(notebook, page)
> >   File "/usr/lib/python3.7/site-packages/zim/main/__init__.py", line 324, in _run_new_window
> >     **self.get_options('geometry', 'fullscreen')
> >   File "/usr/lib/python3.7/site-packages/zim/plugins/__init__.py", line 101, in _init_wrapper
> >     orig_init(self, *arg, **kwarg)
> >   File "/usr/lib/python3.7/site-packages/zim/gui/mainwindow.py", line 328, in __init__
> >     self.open_page(page)
> >   File "/usr/lib/python3.7/site-packages/zim/gui/mainwindow.py", line 768, in open_page
> >     self.notebook.index.touch_current_page_placeholder(path)
> >   File "/usr/lib/python3.7/site-packages/zim/notebook/index/__init__.py", line 269, in touch_current_page_placeholder
> >     self.update_iter.links.update() # clean up placeholder
> >   File "/usr/lib/python3.7/site-packages/zim/notebook/index/base.py", line 49, in update
> >     for i in self.update_iter():
> >   File "/usr/lib/python3.7/site-packages/zim/notebook/index/links.py", line 171, in update_iter
> >     target_id = self._pagesindexer.insert_link_placeholder(targetname)
> >   File "/usr/lib/python3.7/site-packages/zim/notebook/index/pages.py", line 176, in insert_link_placeholder
> >     return self._insert_page(pagename, True)
> >   File "/usr/lib/python3.7/site-packages/zim/notebook/index/pages.py", line 203, in _insert_page
> >     (pagename.name, lowerbasename, sortkey, parent_row['id'], is_link_placeholder, file_id)
> > IntegrityError: UNIQUE constraint failed: pages.name
> 
> With another notebook, Zim is able to open it, but all notes are missing, **except the journal notes (!!!)** which show as sub-notes of other main notes that for some reason Zim won't display (see the following link).
> 
> [link](https://i.imgur.com/LLyCSCe.png)

When i try to rename a page, the following error is displayed:

> This is zim 0.70
> Platform: posix
> Locale: es_ES UTF-8
> FS encoding: utf-8
> Python: (3, 7, 3, 'final', 0)
> PyGObject: (3, 32, 0)
> 
> ======= Traceback =======
>   File "/usr/lib/python3.7/site-packages/zim/actions.py", line 115, in do_activate
>     self.__get__(instance, instance.__class__)()
>   File "/usr/lib/python3.7/site-packages/zim/actions.py", line 98, in func
>     return self.func(instance, *args, **kwargs)
>   File "/usr/lib/python3.7/site-packages/zim/gui/uiactions.py", line 186, in rename_page
>     RenamePageDialog(self.widget, self.notebook, path or self.page).run()
>   File "/usr/lib/python3.7/site-packages/zim/gui/uiactions.py", line 583, in __init__
>     page = self.notebook.get_page(self.path)
>   File "/usr/lib/python3.7/site-packages/zim/notebook/notebook.py", line 406, in get_page
>     assert isinstance(path, Path)
> AssertionError: 

When i try to create a new page, the following error happens:

> This is zim 0.70
> Platform: posix
> Locale: es_ES UTF-8
> FS encoding: utf-8
> Python: (3, 7, 3, 'final', 0)
> PyGObject: (3, 32, 0)
> 
> ======= Traceback =======
>   File "/usr/lib/python3.7/site-packages/zim/actions.py", line 115, in do_activate
>     self.__get__(instance, instance.__class__)()
>   File "/usr/lib/python3.7/site-packages/zim/actions.py", line 98, in func
>     return self.func(instance, *args, **kwargs)
>   File "/usr/lib/python3.7/site-packages/zim/gui/uiactions.py", line 110, in new_page_here
>     if self.page is None or self.page.isroot:
> AttributeError: 'IndexTag' object has no attribute 'isroot'

And when i try to "rename" a page...

> This is zim 0.70
> Platform: posix
> Locale: es_ES UTF-8
> FS encoding: utf-8
> Python: (3, 7, 3, 'final', 0)
> PyGObject: (3, 32, 0)
> 
> ======= Traceback =======
>   File "/usr/lib/python3.7/site-packages/zim/actions.py", line 115, in do_activate
>     self.__get__(instance, instance.__class__)()
>   File "/usr/lib/python3.7/site-packages/zim/actions.py", line 98, in func
>     return self.func(instance, *args, **kwargs)
>   File "/usr/lib/python3.7/site-packages/zim/gui/uiactions.py", line 195, in move_page
>     MovePageDialog(self.widget, self.notebook, path or self.page).run()
>   File "/usr/lib/python3.7/site-packages/zim/gui/uiactions.py", line 661, in __init__
>     ('parent', 'namespace', _('Section'), self.path.parent),
> AttributeError: 'IndexTag' object has no attribute 'parent'

**Comment by Roboron3042** [comment]
Okay I've been messing around a bit more and i now feel really stupid. It seems that now Zim group notes in labels by default - that's the reason I was only seeing Journal pages (since is the only place where i use labels - and labels are mostly called as my main pages so there was the confusion). 

All the previous errors also stopped happening when i switched back to the "classic" view, so i think that i should change the name of the issue.

**Comment by jaap-karssenberg** [comment]
Will look into the issues with the tags pane

The startup issue you mention is a separate issue, please put it in another ticket. I believe this should go away when you run "zim --index" on the notebook first. But should not occur at all of course.

**Comment by Roboron3042** [comment]
> Will look into the issues with the tags pane
> 
> The startup issue you mention is a separate issue, please put it in another ticket. I believe this should go away when you run "zim --index" on the notebook first. But should not occur at all of course.

Indeed I resolved it reindexing the notebook (tho i was tying to resolve the "problem" of pages not showing first and accidentally resolved it xD). I will open a new issue.
