### ISSUE TITLE
Custom tool bug replace selected non-ASCII characters

### ISSUE THREAD

**Issue by tehkonst** [zim-desktop-wiki/zim-desktop-wiki#748]
When I try to use custom tool script to replace lines with non-ASCII characters  I get this error:

> This is zim 0.70
Platform: posix
Locale: None None
FS encoding: ascii
Python: (3, 6, 7, 'final', 0)
PyGObject: (3, 26, 1)

> ======= Traceback =======
>   File "/usr/lib/python3/dist-packages/zim/gui/customtools.py", line 480, in _action_handler
>     self._exec_custom_tool(tool)
>   File "/usr/lib/python3/dist-packages/zim/gui/customtools.py", line 494, in _exec_custom_tool
>     output = tool.pipe(args, cwd=cwd)
>   File "/usr/lib/python3/dist-packages/zim/applications.py", line 292, in pipe
>     p = subprocess.Popen(argv, cwd=cwd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
>   File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
>     restore_signals, start_new_session)
>   File "/usr/lib/python3.6/subprocess.py", line 1275, in _execute_child
>     restore_signals, start_new_session, preexec_fn)
> UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)

An example of a line for tests: !"№;!"!"№;;;№%№;?:*?*:№;"""№?? еуыф'''двла"""рлжаж

**Comment by jaap-karssenberg** [comment]
Looking at the line where the error occurs, I don't think the selected content itself is the problem. Might be the encoding of the working directory name.

 Are you sure it works for ascii text selections in the same page?

**Comment by tehkonst** [comment]
It happened only when I launched zim with default locale. 
> LC_ALL=C zim

And I don't know why the system decided that default locale is None. 

> Locale: None None
> FS encoding: ascii

On other computer don't have such problem because the default locale has standard utf-8 encoding.

**Comment by jaap-karssenberg** [comment]
Yes that is exactly what locale C does. It resets the language settings and forces ASCII encoding. So to my understanding the behavior is correct. Typically is you want to use Unicode your locale setting should also support it.

**Comment by tehkonst** [comment]
@jaap-karssenberg, but if I can see these symbols in the program doesn't it mean I can work with them? At least the behavior isn't correct because it shows a big error message :)

**Comment by jaap-karssenberg** [comment]
Ik can fix the error by making a special case and encoding in UTF-8. The
problem is that whatever program is being called is also running under
locale=C and there is no guarantee it will know how to decode this text. So
locale should define an encoding for the content such that all applications
involved know how to decode the text.
