### ISSUE TITLE
Source view plugin wrong view

### ISSUE THREAD

**Issue by tehkonst** [zim-desktop-wiki/zim-desktop-wiki#749]
Zim pages has wrong view with the Source View plugin after reloading page and sometimes it crashes. 
![image](https://user-images.githubusercontent.com/2618162/55442304-af010800-55b6-11e9-8702-dbab821cc62a.png)
Here's an example file:
[0.txt](https://github.com/zim-desktop-wiki/zim-desktop-wiki/files/3036223/0.txt)

**Comment by jaap-karssenberg** [comment]
Double of #642
