### ISSUE TITLE
Problem with copying a header from zim to clipboard

### ISSUE THREAD

**Issue by tehkonst** [zim-desktop-wiki/zim-desktop-wiki#752]
When I copy a part of a header from zim, and paste it somewhere else there are a lot of "=====" characters in the pasted text.

For example: 

> Header============

(I copied this text from zim to the addressbar of the browser)

**Comment by sojusnik** [comment]
See also https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/661

From my point of view headers should be treated like normal text – if "copy as plain text" is set, headers should also be copied as plain text, without being an exclusion.

**Comment by tehkonst** [comment]
The opinion of the author is strange to me. I often use programs for translating texts from one language into another and usually they translate text from clipboard. So it's no good when text comes with formatting symbols.

**Comment by jaap-karssenberg** [comment]
If anyone is willing to work on a patch we can discuss.

**Comment by jaap-karssenberg** [comment]
* Re-open #661, plan for making plain real plain - rename "plain" to "simple" and add real "text" as default
* Make parser round trip for both "simple" and "text"
* New item to make parser for e.g. pasted context more intelligent and also understand wiki and markdown like text
