### ISSUE TITLE
Edit mode and View mode

### ISSUE THREAD

**Issue by Nick222** [zim-desktop-wiki/zim-desktop-wiki#758]
I cannot understand - what is View mode...

May be View mode always switch on - and after edit one page in automatically switch in Edit mode - with temporary change background and font colour (for example) - and this page save after go to another page or manually Save-command ?

**Comment by jaap-karssenberg** [comment]
Sorry, but I have no idea what you are trying to say.

**Comment by Nick222** [comment]
As database - all notebook lock (in View mode) - but one page temporary unlock (in Edit mode).
To switch page to Edit mode user must click on text in it.
After editing this page saved - and switch in View mode...

**Comment by jaap-karssenberg** [comment]
I believe this is the same request as in #623
