### ISSUE TITLE
No 'Create new subpage' menu option

### ISSUE THREAD

**Issue by s1291** [zim-desktop-wiki/zim-desktop-wiki#759]
I am using `zim 0.70` on Ubuntu 18.04. I noticed after upgrading to `zim 0.70` that when I try to right-click on a page to create a new subpage, the option `Create a new subpage` doesn't exist anymore.

Why this option was deleted in v 0.70?

**Comment by jaap-karssenberg** [comment]
Because the "new page" dialog now pre-fills the parent page name and thus doubles as both "new page" and "new sub page"

**Comment by s1291** [comment]
IMO, that's a bad idea (it's more error  prone approach). the new sub page should be back!g

**Comment by jaap-karssenberg** [comment]
Background is that in the context menu I would like a single "new page here" that relates to the location where you click. Open to suggestions how to improve the dialog, but would like to make it a single function.

**Comment by sphh** [comment]
May I jump in here with a suggestion: The "New page" dialog could gain three options (radiobuttons or drop-down options):

1. Add page at same level as "<current page>"
2. Add page as subpage to "<current page>"
3. Define your own path

For option 1. and 2., the user supplies the new name (without the path) and it will be added appropriately. Option 3. would be as currently implemented (and the full path to the selected page copied into the field).

That might suit everyone... (At least I would like it ;-) ).

**Comment by alk0** [comment]
Can we just have "New sub page" back?..

Usability (or lack of it) example:

I want to add a subpage named, let's say, "Notes" to a page named (for example) "How to calculate the correct size of a loopback device filesystem image for debootstrap" (which in itself is a part of a larger hierarchy), and I use the context menu for that; so, what I get? A dialog showing just "stem image for debootstrap:", all selected. Now what my options are? Press `End` to type in "Notes" - that's one keypress more than I had with "New sub page" and a lot of confusion. Now, what if I really need to add a page on the same level — I'd have to painfully `Ctrl`+`Left` in search of that tiny semicolon (:), then delete all 14 words to the right of it, then type in the name of the page. How on Earth is it better than just two separate "New page" and "New sub page"?

Just ranting, sorry. Maybe there's a better way to do what I'm doing, or a decent way to make it one menu item (in this unfortunate case _I_ would suggest removing "New page" (on the same level), leaving "New sub page" only). Finally, there are still global menu items and keyboard shortcuts, they're just less intuitive...

**Comment by jaap-karssenberg** [comment]
Thinking about it again I tend to agree the "new page" is the real problem,
as it is not really contextual. I tried adding flexibility for any level in
one dialog.

How about two menu items:
- "new page here" - create a page at the same level as the selected page
- "new sub page" - create a page below the selected page

When there is no selected page (white area below the index tree), or the
selected page is at the top level, the "new page here" becomes identical
with "new page" in the file menu

Does that make sense from a usability point of view?

-- Jaap

**Comment by s3rgi** [comment]
I also used that submenu a lot and I want it to come back in some way, I really like this last proposed option!

**Comment by alk0** [comment]
Looks good to me.

A bit more about usability, if I may: _expected_ behavior in many other treeviews is that right-click is primarily used to create a **sub** item. Examples: most file explorers, Windows `regedit` — we always create a child item there, never an item on the same level.

Other outliners, where order of elements is important, may use "Add element" or "Add child" to add a sub-element, and "Add above"/"Add below" for elements on the same level (user expectations are set with "Above" and "Below" words — may be not a perfect wording (could be wrongly understood as "one level above/one level below in the hierarchy"), but generally it works and is used a lot).

Three example screenshots below >>

![2019-04-07-151828](https://user-images.githubusercontent.com/10332037/55709582-12999400-5a02-11e9-83b0-46ed4354bff9.png)

![2019-04-07-152518](https://user-images.githubusercontent.com/10332037/55709596-1cbb9280-5a02-11e9-9cb1-7ebceb375e61.png)

![2019-04-07-144010](https://user-images.githubusercontent.com/10332037/55709605-2218dd00-5a02-11e9-8103-da1e96584c80.png)

<< End of screenshots

**Comment by jaap-karssenberg** [comment]
@alk0 thanks for some examples. Do you have a proposal on naming of the items in zim?

My best option is to show in the dialog clearly on which level the page is created, hope that will clarify the options.

**Comment by alk0** [comment]
To be honest, I don't quite understand what was wrong in 0.69.1 — it takes a minute to understand the difference between "New Page..." and "New Sub Page...", but then everything becomes (kind of) logical and (kind of) convenient (or maybe I just got used to it, dunno).

As for better naming — I was thinking about it, but couldn't come up with anything better (or just good enough). Since we don't add pages "above" or "below" in zim, the index is always alphabetical* (btw, why?), we can't use those. "New Page (same level)" — too long, somewhat clumsy, and still not 100% clear, unless the user already knows what it is. So, my best suggestion is just to leave it as it was in 0.69. Or maybe you or someone else can come up with a better idea.

---

_\* Only it is not — in the newly created notebook pages created in 0.70 come (alphabetically) after pages created in 0.69… but not always. I need to investigate it and maybe report a bug._
