### ISSUE TITLE
Strange characters in menus and buttons

### ISSUE THREAD

**Issue by AakeJon49** [zim-desktop-wiki/zim-desktop-wiki#761]
I have notised it in my laptop, not my desktop (Dell Latitude E7440). The caracters on some buttons and in some menues has changed to something like Thai or Arab characters. I haven't seen it before. The screendump is from the File/Open Another Notebook .
![Skärmbild från 2019-04-04 18-24-09](https://user-images.githubusercontent.com/38993117/55572576-2abe9a00-5708-11e9-9e50-e1bf0ca364c5.png)

**Comment by jaap-karssenberg** [comment]
Double of issue #664
