### ISSUE TITLE
"mid:" links go through the web-browser

### ISSUE THREAD

**Issue by rhertzog** [zim-desktop-wiki/zim-desktop-wiki#762]
On my system, I have configured everything so that "mid:<message-id>" links work, they open my mail application on the email message with the indicated Message-ID.

In Zim 0.69, it seems to rely on "xdg-open" to open the link and everything is fine. With Zim 0.70~rc3, the links are opened through the web browser... the web-browser is relatively smart and calls xdg-open and I get my mail application to start but this process leaves an empty tab in the web browser showing the "mid:" URL that I just clicked. It would be nice if we could avoid this indirection. A simple option to let me configure zim to open links with "xdg-open" would be enough.

**Comment by jaap-karssenberg** [comment]
Should be possible to configure the default application using the "open with" context menu.

**Comment by rhertzog** [comment]
Indeed, it worked. I wasn't aware of this. Is this something specific to zim or something handled by Gtk?

**Comment by jaap-karssenberg** [comment]
No this is zim specific, I use "x-url-scheme" (if I recall correctly)
mimetype to store the bindings

**Comment by rhertzog** [comment]
On Mon, 08 Apr 2019, Jaap Karssenberg wrote:
> No this is zim specific, I use "x-url-scheme" (if I recall correctly)
> mimetype to store the bindings

Hum, on my system I have setup the MIME type "x-scheme-handler/mid":

$ xdg-mime query default x-scheme-handler/mid
open-msgid.desktop
$ xdg-mime query default x-scheme-handler/http
firefox.desktop

But the default doesn't come from .local/share/applications/defaults.list
(that zim seems to respect, that's where the binding was stored) but from my
/usr/share/applications/open-msgid.desktop:
$ grep MimeType /usr/share/applications/open-msgid.desktop
MimeType=x-scheme-handler/mid

The latter is also made available in
/usr/share/applications/mimeinfo.cache:
$ grep x-scheme-handler/mid /usr/share/applications/mimeinfo.cache
x-scheme-handler/mid=open-msgid.desktop;

But the correct way to find the proper handler is to follow this
specification:
https://specifications.freedesktop.org/mime-apps-spec/mime-apps-spec-1.0.html

Cheers,
-- 
Raphaël Hertzog ◈ Debian Developer

Support Debian LTS: https://www.freexian.com/services/debian-lts.html
Learn to master Debian: https://debian-handbook.info/get/

**Comment by jaap-karssenberg** [comment]
I followed the specs at the time but default list was not defined in the
spec so I copied gnome. There is a ticket for updating to the new cache
file.

Op ma 8 apr. 2019 15:36 schreef Raphaël Hertzog <notifications@github.com>:

**Comment by rhertzog** [comment]
Ok, that would be #657 right?

**Comment by jaap-karssenberg** [comment]
Yes that is the one

Op do 11 apr. 2019 14:34 schreef Raphaël Hertzog <notifications@github.com>:

**Comment by nbeaver** [comment]
@rhertzog Just curious, what mail application do you use that has "mid:" URL support?

**Comment by rhertzog** [comment]
On Fri, 07 Jun 2019, Nathaniel M. Beaver wrote:
> @rhertzog Just curious, what mail application do you use that has "mid:" URL support?

None. It's custom integration work: https://github.com/rhertzog/message-id-url

Cheers,
-- 
Raphaël Hertzog ◈ Debian Developer

Support Debian LTS: https://www.freexian.com/services/debian-lts.html
Learn to master Debian: https://debian-handbook.info/get/

**Comment by jaap-karssenberg** [comment]
Propose to close this issue

**Comment by rhertzog** [comment]
I guess it's fine to close since we have some proper behavior respecting the system wide settings now.

**Comment by jaap-karssenberg** [comment]
Thanks!
