### ISSUE TITLE
Notebook opening error after Zim 0.70 update

### ISSUE THREAD

**Issue by Roboron3042** [zim-desktop-wiki/zim-desktop-wiki#764]
After the 0.70 update one of my pre-0.70 notebooks couldn't be opened by Zim, returning the following error.

>     This is zim 0.70
>     Platform: posix
>     Locale: es_ES UTF-8
>     FS encoding: utf-8
>     Python: (3, 7, 3, 'final', 0)
>     PyGObject: (3, 32, 0)
> 
>     ======= Traceback =======
>     File "/usr/lib/python3.7/site-packages/zim/gui/widgets.py", line 2997, in do_response
>     destroy = self.do_response_ok()
>     File "/usr/lib/python3.7/site-packages/zim/gui/notebookdialog.py", line 367, in do_response_ok
>     self.callback(self.result)
>     File "/usr/lib/python3.7/site-packages/zim/gui/uiactions.py", line 134, in open_notebook
>     ZIM_APPLICATION.run('--gui', uri)
>     File "/usr/lib/python3.7/site-packages/zim/main/init.py", line 684, in run
>     self._run_cmd(cmd, args) # test seam
>     File "/usr/lib/python3.7/site-packages/zim/main/init.py", line 695, in _run_cmd
>     w = cmd.run()
>     File "/usr/lib/python3.7/site-packages/zim/main/init.py", line 277, in run
>     return self._run_new_window(notebook, page)
>     File "/usr/lib/python3.7/site-packages/zim/main/init.py", line 324, in _run_new_window
>     **self.get_options('geometry', 'fullscreen')
>     File "/usr/lib/python3.7/site-packages/zim/plugins/init.py", line 101, in _init_wrapper
>     orig_init(self, *arg, **kwarg)
>     File "/usr/lib/python3.7/site-packages/zim/gui/mainwindow.py", line 328, in init
>     self.open_page(page)
>     File "/usr/lib/python3.7/site-packages/zim/gui/mainwindow.py", line 768, in open_page
>     self.notebook.index.touch_current_page_placeholder(path)
>     File "/usr/lib/python3.7/site-packages/zim/notebook/index/init.py", line 269, in touch_current_page_placeholder
>     self.update_iter.links.update() # clean up placeholder
>     File "/usr/lib/python3.7/site-packages/zim/notebook/index/base.py", line 49, in update
>     for i in self.update_iter():
>     File "/usr/lib/python3.7/site-packages/zim/notebook/index/links.py", line 171, in update_iter
>     target_id = self._pagesindexer.insert_link_placeholder(targetname)
>     File "/usr/lib/python3.7/site-packages/zim/notebook/index/pages.py", line 176, in insert_link_placeholder
>     return self._insert_page(pagename, True)
>     File "/usr/lib/python3.7/site-packages/zim/notebook/index/pages.py", line 203, in _insert_page
>     (pagename.name, lowerbasename, sortkey, parent_row['id'], is_link_placeholder, file_id)
>     IntegrityError: UNIQUE constraint failed: pages.name

This is fixable by reindexing the notebook.

**Comment by jaap-karssenberg** [comment]
Expect this kind of error can be fixed with "zim --index" but should not happen

**Comment by jaap-karssenberg** [comment]
Added some guard code in ec652be in order to catch this. @Roboron3042  if you can still reproduce it, please test. Thanks!

**Comment by Roboron3042** [comment]
I'm not able to reproduce this anymore. Sorry :(

**Comment by jaap-karssenberg** [comment]
No problem - I expected index update would flush the item - so much the
better.
