### ISSUE TITLE
Crash when joining 2 lines with bullets

### ISSUE THREAD

**Issue by bitinerant** [zim-desktop-wiki/zim-desktop-wiki#766]
To reproduce:

1. Type the following 2 lines in Zim:
```
* fire
man

```
2. Confirm that Zim reformats this as:
```
• fire
• man

```
3. Move the cursor to immediately after the word 'fire'
4. Press the delete key

Expected result: `• fireman`
Actual result: Zim crashes

**Comment by RlndVt** [comment]
What version of Zim are you using? I just tested with 0.70 and cannot reproduce.

**Comment by Nick222** [comment]
Xubuntu 18.10
Zim 0.70
confirm


(zim:30474): Gtk-WARNING **: 18:22:36.979: Invalid text buffer iterator: either the iterator is uninitialized, or the characters/pixbufs/widgets in the buffer have been modified since the iterator was created.
You must use marks, character numbers, or line numbers to preserve a position across buffer modifications.
You can apply tags and insert marks without invalidating your iterators,
but any mutation that affects 'indexable' buffer contents (contents that can be referred to by character offset)
will invalidate all outstanding iterators

(zim:30474): Gtk-CRITICAL **: 18:22:36.979: _gtk_text_buffer_get_line_log_attrs: assertion 'GTK_IS_TEXT_BUFFER (buffer)' failed

(zim:30474): Gtk-WARNING **: 18:22:36.979: Invalid text buffer iterator: either the iterator is uninitialized, or the characters/pixbufs/widgets in the buffer have been modified since the iterator was created.
You must use marks, character numbers, or line numbers to preserve a position across buffer modifications.
You can apply tags and insert marks without invalidating your iterators,
but any mutation that affects 'indexable' buffer contents (contents that can be referred to by character offset)
will invalidate all outstanding iterators
Ошибка сегментирования (стек памяти сброшен на диск)

**Comment by bitinerant** [comment]
@RlndVt - I am using Zim 0.70-rc3 on Ubuntu 18.04

**Comment by vossenjp** [comment]
This just started after upgrading to 0.70 from PPA for my on my Mint-18 XFCE work VM, and it's driving me crazy because I join lines a lot!  Zim is crashing on me left and right when I'm taking notes while chairing con calls!  (Ouch.)  But I can't reproduce it on my personal Mint-18 host!

I have `zim-0.70~ubuntu16.04.1` on both, but clearly there is some other difference.  I will try to run the crashy one in debug mode from the CLI in the next day or two and see if that sheds any more light than above.  And ideas on what else to look for to narrow this down?

**Comment by jaap-karssenberg** [comment]
If things crash first step is to check Gtk versions.

Op za 6 apr. 2019 23:00 schreef JP Vossen <notifications@github.com>:

**Comment by vossenjp** [comment]
Per `/etc/os-release` both are:
```
NAME="Linux Mint"
VERSION="18.3 (Sylvia)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 18.3"
VERSION_ID="18.3"
HOME_URL="http://www.linuxmint.com/"
SUPPORT_URL="http://forums.linuxmint.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/linuxmint/"
VERSION_CODENAME=sylvia
UBUNTU_CODENAME=xenial
```

But personal was upgraded from Mint-17 and switched from Cinnamon to XFCE and work is a new install of Mint-18 XFCE (if I recall correctly).  `dpkg-query --list | grep '^.i' | sort | egrep -i 'gtk' | awk '{OFS = "-"; print $2,$3}'` gives me the attached, but I don't know what to look for there.
[personal-gtk.txt](https://github.com/zim-desktop-wiki/zim-desktop-wiki/files/3051893/personal-gtk.txt)
[work-gtk.txt](https://github.com/zim-desktop-wiki/zim-desktop-wiki/files/3051894/work-gtk.txt)

**Comment by vossenjp** [comment]
I've worked on this a bit more and Zim 0.70 on my personal machine *never* crashes and on my work VM *always* crashes when:
1. Create:
```
* List1
* List2
```
2. Go to the end of "List1" and hit the "del" key

`rm -rf /tmp/zim-jp` does not help.  Debug details on the affected node attached.
[zim-debug.txt](https://github.com/zim-desktop-wiki/zim-desktop-wiki/files/3051989/zim-debug.txt)

The high point is:
```
[### Go to end of "List1" line and hit "del" key = crash]


(zim:1081): Gtk-WARNING **: Invalid text buffer iterator: either the iterator is uninitialized, or the characters/pixbufs/widgets in the buffer have been modified since the iterator was created.
You must use marks, character numbers, or line numbers to preserve a position across buffer modifications.
You can apply tags and insert marks without invalidating your iterators,
but any mutation that affects 'indexable' buffer contents (contents that can be referred to by character offset)
will invalidate all outstanding iterators

(zim:1081): Gtk-CRITICAL **: _gtk_text_buffer_get_line_log_attrs: assertion 'GTK_IS_TEXT_BUFFER (buffer)' failed

(zim:1081): Gtk-WARNING **: Invalid text buffer iterator: either the iterator is uninitialized, or the characters/pixbufs/widgets in the buffer have been modified since the iterator was created.
You must use marks, character numbers, or line numbers to preserve a position across buffer modifications.
You can apply tags and insert marks without invalidating your iterators,
but any mutation that affects 'indexable' buffer contents (contents that can be referred to by character offset)
will invalidate all outstanding iterators
Segmentation fault
```

**Comment by jaap-karssenberg** [comment]
Unfortunately I can't reproduce this myself. (If I could, it would never have slipped past, as I'm already working with 0.70 daily for past 4 months or so...)

The error must occur in the `do_post_delete_range()` method in `zim/gui/pageview.py`. Unfortunately the Gtk crash output doesn't tell me what line exactly. 

Could you put in some `print()` statements in that method to figure out where the crash happens exaclty?

**Comment by vossenjp** [comment]
My first debug attempt both failed and worked.  It failed in that I got it wrong, but it *worked in that it prevented the crash.*  (So I'll use that hack to prevent crashes for now.)  It also prevented "cleaning up the redundant bullet."

Code with stupid copy&paste bug:
```
	def do_post_delete_range(self, start, end):
...
		# Note that 'start' and 'end' refer to the same postion here ...
		print(">>> Enter do_post_delete_range\n", text)  # JP DEBUG #766
```

Debug
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/gui/pageview.py", line 2103, in do_post_delete_range
    print(">>> Enter do_post_delete_range\n", text)  # JP DEBUG #766
NameError: name 'text' is not defined
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/gui/pageview.py", line 2103, in do_post_delete_range
    print(">>> Enter do_post_delete_range\n", text)  # JP DEBUG #766
NameError: name 'text' is not defined
```

I'm not sure what this second try means.  Code:
```
	def do_post_delete_range(self, start, end):
...
		# Note that 'start' and 'end' refer to the same postion here ...
		print(">>> Enter do_post_delete_range\n")  # JP DEBUG #766

		if (
			(
				not start.starts_line()
				and list(filter(_is_line_based_tag, start.get_toggled_tags(True)))
			) or (
				not start.ends_line()
				and list(filter(_is_line_based_tag, start.get_toggled_tags(False)))
			)
		):
			print(">>> _do_lines_merged\n")    # JP DEBUG #766
			self._do_lines_merged(start)

		bullet = self._get_bullet_at_iter(start)
		if bullet is not None:
			if start.starts_line():
				print(">>> _check_renumber.append\n")    # JP DEBUG #766
				self._check_renumber.append(start.get_line())
			else:
				# Clean up the redundant bullet
				print(">>> Clean up the redundant bullet\n")  # JP DEBUG #766
				bound = start.copy()
				self._iter_forward_past_bullet(bound, bullet)
				self.delete(start, bound)
		elif start.starts_line():
			print(">>> in elif start.starts_line\n")  # JP DEBUG #766
			indent_tags = list(filter(_is_indent_tag, start.get_tags()))
			if indent_tags and indent_tags[0].zim_attrib['_bullet']:
				# had a bullet, but no longer (implies we are start of
				# line - case where we are not start of line is
				# handled by _do_lines_merged by extending the indent tag)
				print(">>> update_indent_tag\n")    # JP DEBUG #766
				self.update_indent_tag(start.get_line(), None)

		self._check_edit_mode = True
		print(">>> Exit do_post_delete_range\n")  # JP DEBUG #766
```

Debug:
```
>>> Enter do_post_delete_range

>>> Clean up the redundant bullet

>>> Enter do_post_delete_range

>>> Exit do_post_delete_range

>>> Exit do_post_delete_range


(zim:15295): Gtk-WARNING **: Invalid text buffer iterator: either the iterator is uninitialized, or the characters/pixbufs/widgets in the buffer have been modified since the iterator was created.
You must use marks, character numbers, or line numbers to preserve a position across buffer modifications.
You can apply tags and insert marks without invalidating your iterators,
but any mutation that affects 'indexable' buffer contents (contents that can be referred to by character offset)
will invalidate all outstanding iterators

(zim:15295): Gtk-CRITICAL **: _gtk_text_buffer_get_line_log_attrs: assertion 'GTK_IS_TEXT_BUFFER (buffer)' failed

(zim:15295): Gtk-WARNING **: Invalid text buffer iterator: either the iterator is uninitialized, or the characters/pixbufs/widgets in the buffer have been modified since the iterator was created.
You must use marks, character numbers, or line numbers to preserve a position across buffer modifications.
You can apply tags and insert marks without invalidating your iterators,
but any mutation that affects 'indexable' buffer contents (contents that can be referred to by character offset)
will invalidate all outstanding iterators
Segmentation fault
```

**Comment by jaap-karssenberg** [comment]
Interesting

- Crash occurs *after* `do_post_delete_range()` has completed
- Exiting `do_post_delete_range()` before the bullet replacement avoids the crash

Can you try this patch: https://gist.github.com/jaap-karssenberg/5f99835413aa5aa2d995396ae6d77363 ?

**Comment by bitinerant** [comment]
@jaap-karssenberg - YES! This patch fixes it for me.

I actually have commit 9071483 (2019-03-14) which does not include the "Add test coverage for merging list items" changes which are undone in the above-linked patch, but manually adding the 4 lines under the "Clean up the redundant bullet" comment solved the issue for me. I reproduced the bug, applied the code change, restarted Zim, and then was unable to reproduce the bug using the same data and procedure. Thank you, Jaap. :-)

**Comment by jaap-karssenberg** [comment]
@bitinerant thanks for testing - will commit the fix

**Comment by vossenjp** [comment]
I also had trouble getting the patch to apply so I did it manually.  I looked at 717112c but that was *very* different and I didn't want to change too much.

This patch against pristine 0.70 `pageview.py` **fixed the crash** for me:
```
--- pageview.py.ORIG	2019-04-13 14:30:28.000000000 -0400
+++ pageview.py.766.patch	2019-04-13 14:47:03.000000000 -0400
@@ -2118,9 +2118,13 @@
 				self._check_renumber.append(start.get_line())
 			else:
 				# Clean up the redundant bullet
+				offset = start.get_offset()
 				bound = start.copy()
 				self._iter_forward_past_bullet(bound, bullet)
 				self.delete(start, bound)
+				new = self.get_iter_at_offset(offset)
+				start.assign(new)
+				end.assign(new)
 		elif start.starts_line():
 			indent_tags = list(filter(_is_indent_tag, start.get_tags()))
 			if indent_tags and indent_tags[0].zim_attrib['_bullet']:
```
