### ISSUE TITLE
0.70 loses your place on page switch

### ISSUE THREAD

**Issue by vossenjp** [zim-desktop-wiki/zim-desktop-wiki#770]
I keep my "working" notes in 1 page and my con call notes in another so I switch pages a lot.  0.70 makes that really painful, because it picks some arbitrary seeming focus and always goes there, rather than where I was.  < 0.70 did that for me when using the Pathbar, but the Bookmark buttons saved my place so I just used those and lived with it otherwise.

With 0.70, the only way I can marginally live with it is that I also tend to use enough headers to make getting back to where I need to be using the ToC work.  Sort of.  But it's really painful.

**Comment by sojusnik** [comment]
Maybe also connected to https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/611#issuecomment-461005328

**Comment by jaap-karssenberg** [comment]
Please be more specific on how you switch pages. Current behavior stores the cursor position in the history and goes to the same cursor postion when you switch using back / forward and when using the pathbar in recent pages or history mode.

I do notice some weirdness when there are objects in the page, but can't really pinpoint it down.

**Comment by jaap-karssenberg** [comment]
P.S. if you have the preference "always use last cursor position" enabled the "open_page" method always asks the history for the last position. In my testing works however you open the page.

**Comment by vossenjp** [comment]
I always switch pages by clicking the button in either the bookmark or path bars.

If I uncheck "always use last cursor position" and switch pages it always goes to the top of the new page.  If checked, < 0.70 worked if I switched pages by clicking on the bookmark button, but not the pathbar button.  With 0.70 neither work and I end up and some random previous place, however results from both bookmark and path bar now seem to be the same (just wrong).

I just noticed something...  The *cursor* is actually in the right place, it's just that the *display* is scrolled to the wrong place!  Pressing an arrow key then causes the screen to scroll to the right place, though the cursor location is now at the bottom of the screen instead of the top where I left it.  So this is possibly related to #92?  I can see the point there, but personally for my use-case I always want to go back to where I was working (cursor location) and not where I might have been reading (scroll location).

**Comment by vossenjp** [comment]
Could this have anything to do with fonts or zoom?  My personal Zim was using a zoom of 1 or 2 and Sans Regular 9.  When I dropped the zoom to zero and bumped the font to 11 the offset between display and cursor location got better.  It's still off, but is off less.

For work, I was using a zoom +1 and Verdana Regular 9.  Then I set the zoom to zero and the font to 10 that didn't seem to make a difference.

**Comment by nelas** [comment]
> The _cursor_ is actually in the right place, it's just that the _display_ is scrolled to the wrong place!

Exactly! I also began experiencing this at some point along the 0.70 dev, but never actually managed to track it down. I first noticed in pages with inserted images, but it also happens in other "regular" pages. Changing the zoom did not seem to improve it for me.

**Comment by jaap-karssenberg** [comment]
Seems related to #642 as in my testing this only happens in the presence of inline objects. For a long page with just text all seems well.

That suggest it is timing related and the objects resize after scrolling took place.

**Comment by nelas** [comment]
I had the issue in a page containing only a numbered list of links (I can send it by email if you want to test), but this commit fixes it!

**Comment by vossenjp** [comment]
I don't think I have any *inline* objects, but I have lots and lots of both bullet and checkbox lists, and at least some numbered lists.  Since `_hack_on_inserted_tree` is missing in pristine 0.70 I copied the entire 60e8244 `pageview.py` file into place (on top of pristine) and that **fixes losing your place,** but I now see garbled text on the screen in some cases.  I suspect that's **because** I'm now mixing and matching files from different revisions, so I'll grab a package out of the daily PPA if I need to.

**Comment by vossenjp** [comment]
I take it back.  On my personal node the 60e8244 `pageview.py` file seems to work, though there's an odd "jerk" as it scrolls the screen to the cursor location after all the rendering.  On my work node, it works (with the "jerk") switching from my con call to my work page, but not switching from my work to con call page (and no "jerk").  As above, I have injected that 1 page into otherwise pristine 0.70 code though, so that could be goofy.

It's sounding more like I should grab a daily from the PPA, any specific recommendations?

**Comment by nelas** [comment]
@vossenjp https://launchpad.net/~jaap.karssenberg/+archive/ubuntu/zim-snapshots

**Comment by sojusnik** [comment]
Just recently I've noticed some stuttering while pasting or refreshing, as shown [here](https://mega.nz/#!ysg2BC7Q!SuFSiq4J_gx5wXQzmeP6zkznTWxOa3a_rN61kgbbPYQ). Is this somehow connected to this issue?
Using the most recent version from the snapshots PPA.
