### ISSUE TITLE
0.70 CTRL-R to reload is MUCH slower and also loses your place

### ISSUE THREAD

**Issue by vossenjp** [zim-desktop-wiki/zim-desktop-wiki#772]
CTRL-R feels *much* slower in 0.70 to me.  And like #770, it also loses your place.  For < 0.70 CTRL-R did not lose your place, even though the screen might move around a bit due to rendering pasted in markup.

**Comment by jaap-karssenberg** [comment]
Speed of reload is the same as switching pages - and it does functionally the same in the code. Please open a separate ticket if you have data where reload is slower than switching pages and instructions how to reproduce.

Will address the cursor position.

**Comment by vossenjp** [comment]
Switching pages is pretty slow too, but some of my pages are long and complicated, and I'm mostly running on a VM with only 1 CPU on top of Windows (forced to at work) so it's a bit painful.  It *seems* to take about 3 seconds to CTRL-R and about 4 to switch pages, but that's by eye and stop-watch so it's fuzzy at best.  I have no idea how to reproduce that, other than just creating long, complicated pages.  `wc -l` gives me 2263 for the "work" and 2003" for the con calls pages I'm testing flipping between.

a59b390 does not fix the "lose your place" problem for me, but I think it does make the behavior consistent with page switching, per #770.
