### ISSUE TITLE
Strange language after upgrade to 0.70

### ISSUE THREAD

**Issue by rzelnik** [zim-desktop-wiki/zim-desktop-wiki#773]
After upgrade to 0.70, many phrases that are not translated to my native language yet, are shown in some strange language, probably Italian. I would expect English as fallback language.

My setup:
Ubuntu 18.10 64-bit
Language and Region > Language for menus and windows: Slovak (preferred), also installed: English, Czech
Zim: 0.70

**Comment by Self-Perfection** [comment]
Looks like a duplicate of #664

**Comment by rzelnik** [comment]
Yes, you are right, it's a duplicate, so I am closing it. Thank you for warning.
