### ISSUE TITLE
Copy to Clipboard/CLI then back to Zim now fails in 0.70

### ISSUE THREAD

**Issue by vossenjp** [zim-desktop-wiki/zim-desktop-wiki#774]
I have a shell script "wrapper" that does various text processing for me, so I commonly:
1. Copy test from Zim into the clipboard
2. Switch to a terminal and run the script, which reads then writes the clipboard
3. Switch back to Zim and paste the result from the clipboard

As of 0.70 the paste now fails, but up until that version it just worked in Mint-17 and Mint-18.

Steps to reproduce on Linux:
1. Type "lower case line" in Zim
2. Select and copy that line
3. Switch to a terminal and run: `/usr/bin/xsel -b | perl -ne 'print uc();' | /usr/bin/xsel -bi`
    * (UNTESTED: on Mac try `/usr/bin/pbpaste` and `/usr/bin/pbcopy`)
4. Switch back to Zim and paste

Results = nothing
Expected = Zim should now have `LOWER CASE LINE` pasted in to the page

Hack-around:
1. Use: `/usr/bin/xsel -b | perl -ne 'print uc();'`
2. Copy from the terminal
3. Switch back to Zim and paste = works

**Comment by jaap-karssenberg** [comment]
There are issues with clipboard handling under Gtk3 due to missing API, not sure if this is related.

Have you considered running those scripts as "custom tools" that replace the selection ?

**Comment by jaap-karssenberg** [comment]
Turns out to be simple fix

**Comment by vossenjp** [comment]
I confirm that patch works, thanks!
