### ISSUE TITLE
ToC should handle multiple identical headers correctly

### ISSUE THREAD

**Issue by vossenjp** [zim-desktop-wiki/zim-desktop-wiki#776]
Feature request:
The ToC plugin gets confused if you have multiple identical headers, but it should be able to handle that.

Steps to reproduce:
1. In a Zim page, create:
```
===== Con call 1 =====

==== Attendees ====

==== Notes ====

===== Con call 2 =====

==== Attendees ====

==== Notes ====

```
2. In the ToC, click on the *top* instance of "Notes"

Result = you will jump to the *bottom* "notes" header
Expected: you should go to the correct instance of the header you clicked on

I seem to recall that this was already an open issue, but I'm not finding it in Github and I'm too lazy to go looking in LP.  It seems like the fix would be to use some kind of "index" and have the ToC plugin honor the index, not the potentially duplicate text.

Brain storming the index:
1. Integer counters, but that might require a lot of scanning and potentially re-writing indexes to keep them in order as content is created or moves around.
2. Hash the header text with something, probably the ISO-8601 date/time to create an arbitrary "unique" index, but that requires potentially non-trivial hashing code.
3. Just use the header creation ISO-8601 date/time (or Epoch) as the index.  If we're worried about sub-1-second collisions, more precise time could be used, though I think that's overkill.

So you get something like:
```
===== Con call 1 ===== 2019-04-07_15:08:03 (or 1554664083.991099756)

==== Attendees ==== 2019-04-07_15:08:04 (or 1554664084.046594170 ...etc.)

==== Notes ==== 2019-04-07_15:08:05 (and maybe .246529452?)

===== Con call 2 ===== 2019-04-07_15:08:06.206764633

==== Attendees ==== 2019-04-07_15:08:07

==== Notes ==== 2019-04-07_15:08:08

```

To be honest, I kind of like the human-readable time-stamp idea all on its own, just because it gives clues about when something was written or worked on, much like the default when creating a new Zim page.  I'd think the time-stamp would be re-created if you re-applied (or changed) the header format or level, and that could also be a fix if we ever did have a sub-1-second collision.

OK, I just thought of a problem there.  If I create a bunch of headers in 1 operation, they will all have exactly the same time...unless sub-1-second precision is used and format application is a per-line loop (which I'm guessing it might be).  Example: Add the following to Zim then select and CTRL-2 (which I do every week):
```
2019-04-08 Mon:
2019-04-09 Tue:
2019-04-10 Wed:
2019-04-11 Thu:
2019-04-12 Fri:
2019-04-13 Sat:
2019-04-14 Sun:
```

**Comment by Nick222** [comment]
Let user add number to headers?

**Comment by vossenjp** [comment]
That's what I do manually now, but it's manual and thus tedious and it doesn't really fit.  If you see my con call example, "notes1" and "notes2" or similar really don't make sense.  And since the calls are weekly they are always changing and then being archived.

**Comment by sojusnik** [comment]
See this old bug report as an addition https://bugs.launchpad.net/zim/+bug/1411749

**Comment by jaap-karssenberg** [comment]
Double of #485
