### ISSUE TITLE
Make toolbar customizable

### ISSUE THREAD

**Issue by ghost** [zim-desktop-wiki/zim-desktop-wiki#78]
Include icon for 

1. h1, h2, and h3
2. Bulleted, numbered, and to-do list
etc.

Or make the toolbar more customizable so you can add what need by picking from a list.

**Comment by Osndok** [comment]
You can probably accomplish this with a plugin.

**Comment by krizoek** [comment]
> You can probably accomplish this with a plugin.

Is there a plugin for it?
