### ISSUE TITLE
Feature request: permit easy creation of hardlinks to wiki-files in other directories

### ISSUE THREAD

**Issue by cgoise** [zim-desktop-wiki/zim-desktop-wiki#783]
Hi,

I found that I want very often a new text-file that I created in the wiki could be shown in 2 or more different top-pages in the table of contents. 

For instance, the exact samle snippet of C++ code may belong into the 'C++'-folder/page as well as in the 'Numerics' folder in the same wiki. Using hardlinks this can be achieved easily. 

Of course i can use the terminal for this purpose, but that's a little awkward to do. A right click option or a simple drag-and-drop would be much nicer to use.

Just an idea, thanks for the consideration,
Till

**Comment by jaap-karssenberg** [comment]
Sorry, but using hard links in a desktop application is a bad idea. This kind of classification is better achieved by tagging your snippets.

Won't Fix
