### ISSUE TITLE
Automatic link completion doesn't work with accented characters in Zim 0.70

### ISSUE THREAD

**Issue by rzelnik** [zim-desktop-wiki/zim-desktop-wiki#785]
When I type first letters of name of a page in Insert > Link, it automatically suggests a complete name. When I type a ":" sign, it suggests autocompletion of embedded pages. After upgrade to 0.70, it only works with names which contain basic ASCII letters only. When the name contains accented characters (like á, é, í etc.), the automatic completion doesn't work with embedded pages/links. Before 0.70 it worked well even with accented characters.

**Comment by jaap-karssenberg** [comment]
Double #732
