### ISSUE TITLE
Strange message about color

### ISSUE THREAD

**Issue by Nick222** [zim-desktop-wiki/zim-desktop-wiki#791]
Xubuntu 18.10
Zim 0.70 snapshot 13.04.2019

DEBUG mode - in Terminal I see:

"(zim:1255): Gtk-WARNING **: 00:46:42.397: Don't know color 'none' "

What it is meaning?
What must I do?

**Comment by jaap-karssenberg** [comment]
Sorry but I don't look into Gtk warnings unless they are related to a larger issue. Ideally these should all be resolved, but it is very hard to trace them back to the line in the source code where they originate.
