### ISSUE TITLE
Clicking on tray icon minimizes window

### ISSUE THREAD

**Issue by retosh** [zim-desktop-wiki/zim-desktop-wiki#792]
Not to long ago it was possible to minimize an open window by left clicking the mouse on the tray icon. It was the opposite behaviour to opening an minimized window which still works (I always had one notebook only). One day it vanished without my interfering (like I assume), since then minimizing is possible only by clicking the X on the open window itself. If this is not due to an accidentally lost dependency (like python-appindicator or so), is it possible to bring this behaviour back?

**Comment by jaap-karssenberg** [comment]
Sorry for the *very late* response - afraid the answer depends on the platform (window / linux / gnome / ...).

**Comment by retosh** [comment]
Thanks anyway. I'm running a Linux x64 with xfce.

**Comment by jaap-karssenberg** [comment]
Then you are probably relying on the "old" style tray icon library, not
app-indicator - correct ?

The old style library is no longer supported in Gtk, so afraid it will
break at some point.

Only thing I can think of is that if you have the latest version of zim
with the header bar controls (buttons in the header bar - Gnome style), you
might want to try turning that off using the "toolbar" plugin and see if
that helps the window manager to do the right thing.

Regards,

Jaap

**Comment by retosh** [comment]
I suppose as there is only libayatana-indicator3-7 installed but no e.g. libayatana-appindicator3-1. Is it also a solution to install that package or only the suggestion you mentionned to try out. If so it's unfortunately not clear for me what buttons I could try to turn off.

**Comment by retosh** [comment]
I have the latest version so I could turn off the header bar controls, but that didn't change the behaviour.

As of appindicator, my XFCE has packages like xfce4-indicator-plugin and ayatana-indicator-application. I don't know if this is it, but I tried them out anyway. Result: I couldn't get them to communicate with zim. This is either because they are the wrong packages for what I want or due to my lack of how to. I guess I have to give in and close the issue. Thanks anyway for your support.
