### ISSUE TITLE
Consistent background in distraction free view

### ISSUE THREAD

**Issue by sojusnik** [zim-desktop-wiki/zim-desktop-wiki#797]
The background is not consistent in the distraction free view, as shown [here](https://mega.nz/#!j1YGxKpY!DtWhaYj708BAkfNpzF3U6lpFOZhvIAnigy7BDQhXLdE). In my case, the grey area should match the dark text background.

Happens with 0.70-SNAPSHOT-t201904141243~ubuntu19.04.1

**Comment by introt** [comment]
Can you reproduce this on 0.74? The background is all #eeeeec on my system.

**Comment by sojusnik** [comment]
Works now, thanks!
