### ISSUE TITLE
Can't add new page version 0.70

### ISSUE THREAD

**Issue by deshaion** [zim-desktop-wiki/zim-desktop-wiki#799]
There is no menu after clicking the right mouse button in the Index pane where the "New Page..." button was before upgrade to the 0.70~ubuntu16.04.1 version.

Linux Mint 18.3

**Comment by Statisticonomicon** [comment]
I have the same issue on Linux Mint. The strange thing is I have Mint 18 and on a laptop I have Mint 19 and it works.
I must be missing a library

**Comment by mke21** [comment]
Same issue in Ubuntu 16.04 for me. Popup menu doesn't work anymore.
 ctrl+n and ctrl+Shift+N still works, though, also you can click the 'New Page' and the 'New Sub Page' options in the file menu.

**Comment by Statisticonomicon** [comment]
Update - RESOLVED
I upgraded my Linux Mint 18 to 19 and now everything works.

This is now a backward compatibility issue.

**Comment by mke21** [comment]
I'm curious which dependency has the compatibillity issue. Would like to get it to work again without having to upgrade the whole system, which will introduce a whole lot of new problems.

**Comment by jaap-karssenberg** [comment]
There is an issue with the Gtk dependency, this should be resolved in zim
0.71.0 (see issue #731) but also report of still something NOK (see issue
#810).  Please test with 0.71 if your problem is resolved.

-- jaap

**Comment by jaap-karssenberg** [comment]
Parent was actually about issue #759 - duplicate
