### ISSUE TITLE
zim.py checks for Python >=3.2 but travis only runs tests on Python 3.6

### ISSUE THREAD

**Issue by JoelMon** [zim-desktop-wiki/zim-desktop-wiki#803]
Hello,

I noticed that /zim.py checks for Python >= 3.2 but travis is only running with Python 3.6.
```Python
12 try:
13	assert sys.version_info >= (3, 2)
14 except:
15	print('zim needs python >= 3.2', file=sys.stderr)
16	sys.exit(1)
```

I'm not very experienced but this can lead to broken code, couldn't it?

I know that with travis-ci you can set up a *build matrix* where you can run the code though a list of different python versions. 

ie:
```
language: python
python:
 - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
```
[source](https://docs.travis-ci.com/user/languages/python/)

I'm assuming to speed up the test only 3.6 is used but just putting it out there in case it fell through the cracks.

**Comment by dehesselle** [comment]
Travis CI has ceased its free service and we're transitioning towards GitHub Actions (see https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/1620), so this is no longer necessary. Thank you anyways!
