### ISSUE TITLE
Zim mixing languages in GUI

### ISSUE THREAD

**Issue by domhnallw** [zim-desktop-wiki/zim-desktop-wiki#804]
Using Zim 0.70 on Ubuntu 18.04 x64. Python version is 3.6.7. System language is English (UK).

Getting occasions where Zim is showing incorrect translations for some fields, for example:

![Screenshot from 2019-04-16 16-26-06](https://user-images.githubusercontent.com/10363775/56272893-95ea7200-60f3-11e9-85ec-01b0e51dce4b.png)

(Appears to be Danish or some Scandinavian language, in English it should be "Attachments")

![Screenshot from 2019-04-17 09-30-16](https://user-images.githubusercontent.com/10363775/56272897-971b9f00-60f3-11e9-8d04-1e8b0beb8408.png)

Annuller is French for "Cancel"?

I've been using Zim for three years now (keeping it up to date), this is the first time I've seen it.

**Comment by RlndVt** [comment]
I have a similar issue but then words being translated to German. (e.g. Abbrechen instead of Cancel, Finden instead of Find.)

Using Zim 0.70 on Manjaro w/ KDE. Python version is 3.7.3. System language is English (UK).

**Comment by sojusnik** [comment]
This was already reported several times before, f.i. [here](https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/664). Please use the search before posting bug reports.

**Comment by domhnallw** [comment]
Thank you. I tried using the search, but "Wrong Locale in some windows" wasn't obviously the same error (at least to me).
