### ISSUE TITLE
Problem with updating the index

### ISSUE THREAD

**Issue by aktaboot** [zim-desktop-wiki/zim-desktop-wiki#805]
I have some files that are not showing in the index.
I checked that they do exist, and are in the appropriate Folder/Notebook.
I tried updating the index via "Tools -> Update Index" , to no avail.
I also tried  "zim --index -V /path/to/notebook", as suggested in [#697](https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/697) and I get this error : 
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/notebook/index/files.py", line 113, in _update_iter_inner
    self.update_folder(node_id, folder)
  File "/usr/lib/python3/dist-packages/zim/notebook/index/files.py", line 230, in update_folder
    (path, node_type, STATUS_NEED_UPDATE, node_id),
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 18-19: surrogates not allowed
```

**Comment by jmlups** [comment]
Also tried Removing and Adding the Notebooks with "File -> Open Another Notebook..." and didn't work.
Downgrading back to version 0.68 worked for me ! :smile:

**Comment by jaap-karssenberg** [comment]
Looks like those files might have weird characters in the file name or non-ascii characters in an encoding other than UTF-8 ?

**Comment by aNDy-Squirrel** [comment]
I had something similar when I had a page with spaces in the file name. After realizing that Zim doesn't allow spaces in the file name, I converted them into underscores, but the page was still not appearing in Zim. However, after deleting the corresponding file in the .cache/zim folder, and restarting Zim, if finally appeared.

**Comment by introt** [comment]
Is this resolved? If not, please post the offending filenames.

**Comment by aNDy-Squirrel** [comment]
This was so long ago, that I am not sure whether I can reproduce the same case. I played a bit with filenames with and without spaces, and for what I can see now, everything works fine.

**Comment by introt** [comment]
Thanks for the info! Are you still having issues with yours @aktaboot ?

**Comment by aktaboot** [comment]
I don't have the same Notebook anymore, so can't reproduce anymore, sorry !
I guess you can close this Issue!

**Comment by introt** [comment]
Thanks for the quick reply! Feel free to open a new issue if you later re-encounter the issue.
