### ISSUE TITLE
BUG: page object no longer valid

### ISSUE THREAD

**Issue by raspatan** [zim-desktop-wiki/zim-desktop-wiki#811]
Hi there,

It seems I found a bug, at least according to the program itself. Here is the output:

```
This is zim 0.65
Platform: posix
Locale: en_GB UTF-8
FS encoding: UTF-8
Python: (2, 7, 12, 'final', 0)
Gtk: (2, 24, 30)
Pygtk: (2, 24, 0)
Zim revision is:
  branch: zim-trunk
  revision: 805 jaap.karssenberg@gmail.com-20151101144245-0g7s8a7qjt5xu1d0
  date: 2015-11-01 15:42:45 +0100

======= Traceback =======
  File "/usr/lib/python2.7/dist-packages/zim/gui/widgets.py", line 3106, in do_response
    destroy = self.do_response_ok()
  File "/usr/lib/python2.7/dist-packages/zim/gui/__init__.py", line 3283, in do_response_ok
    lines = self.page.dump(format)
  File "/usr/lib/python2.7/dist-packages/zim/notebook.py", line 2507, in dump
    tree = self.get_parsetree()
  File "/usr/lib/python2.7/dist-packages/zim/notebook.py", line 2409, in get_parsetree
    assert self.valid, 'BUG: page object became invalid'
AssertionError: BUG: page object became invalid
```

This is what I did:

- installed `zim` in Ubuntu 16.04 via `apt-get` 
- created first new notebook
- immediately deleted the Home page it came up by default
- a pop-up window appeared, with an error message:

> **Could not save page: Home**
>
>BUG: page object no longer valid
>
> To continue, you can save a copy of this page or discard
any changes. If you save a copy, changes will also be
discarded, but you can restore the copy later.

- selected Save Copy, from the options in the pop-up window
- selected a folder to save the Home.txt file
- bug window appeared, with the message at the top of the post

Nothing really works now. The pop-up window appears all the time, even after reopening the program. Actually, it appears **even after closing the program**. I had to kill the program in the Task Manager.

I then deleted the zim folders (`Notebooks/...`) and reopened, and the error message appeared:

>No such file: /home/my_user/Notebooks/Notes

My only solution was to remove the `notebook.list` file from `/home/my_user/.config/zim/`, which made the program to behave as a fresh install.

I hope this helps.

**Comment by jaap-karssenberg** [comment]
Sorry but this is an old version, closing as "Won;t Fix" unless same behavior seen in newer version.
