### ISSUE TITLE
0.71.0 tests failed on Fedora 30

### ISSUE THREAD

**Issue by cheese** [zim-desktop-wiki/zim-desktop-wiki#814]
test_report:
[test_report_0.71.0_f30.txt](https://github.com/zim-desktop-wiki/zim-desktop-wiki/files/3120569/test_report_0.71.0_f30.txt)

**Comment by jaap-karssenberg** [comment]
Most of these errors seem to relate to your "builddir" environment. Please
run tests in normal environment to verify.

Only one item that looks locale related should remain.

-- Jaap

**Comment by Bluewind** [comment]
I'm also seeing various test failures when trying to package for Arch Linux. Here's the log: [zim-0.71.0-1-x86_64-check.log](https://github.com/zim-desktop-wiki/zim-desktop-wiki/files/3121767/zim-0.71.0-1-x86_64-check.log).

The tests pass outside of the build container, but I'm not sure why or how I could make them pass inside as well. Could missing dependencies cause these errors? If so, could you tell me which ones? If not, what other reason may be causing this?

**Comment by cheese** [comment]
> Most of these errors seem to relate to your "builddir" environment. Please run tests in normal environment to verify. Only one item that looks locale related should remain.
Yes. All tests run in normal environment. But the 'builddir' is just the standard packaging environment of Fedora. Tests are automatically run during packaging in that environment, since 0.70, which all tests passed.

**Comment by jaap-karssenberg** [comment]
@Bluewind these are indeed the same issues. They are not failures due to dependencies or errors in the application. They are issues with the test suite not being robust for the build environment.

Fix would be to adjust the test to make them pass inside the environment.

**Comment by cookiEoverdose** [comment]
I checked out 0.71.0 on Fedora 30. I got a different report with 5 test failures 

[test_report.git-0.71.0.fedora30.html.txt](https://github.com/zim-desktop-wiki/zim-desktop-wiki/files/3144304/test_report.git-0.71.0.fedora30.html.txt)

 and a few

> (test.py:12774): Gtk-CRITICAL **: 13:36:54.872: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

lines in terminal.

**Comment by oturpe** [comment]
Errors reported by @cookiEoverdose still happen with the current master. However, they are unrelated to Fedora buildroot, and instead caused by language settings. For instance:

> AssertionError: 'Anscheinend haben Sie einen Fehler gefunden' != 'Looks like you found a bug'
> - Anscheinend haben Sie einen Fehler gefunden
> + Looks like you found a bug

 It seems that the tests must be run in English locale to succeed. This command works: `LANG=en_US.UTF-8 ./test.py`

**Comment by oturpe** [comment]
@Bluewind In case you are still involved with packaging Zim in Arch Linux, perhaps you could check if my pull request also makes the tests pass in Arch build environment?

**Comment by Bluewind** [comment]
I'm still the packager for zim on Arch Linux and #1379 also fixes the test suite for us. Thank you!
