### ISSUE TITLE
Drag and Drop from attachments panel to wiki page does not work

### ISSUE THREAD

**Issue by murattepegoz** [zim-desktop-wiki/zim-desktop-wiki#815]
Folks, dragging files from attachment panel into a wiki page is not working for me. The problem started with version 0.70. I am using zim on mac with homebrew. 
Here is the snapshot summarizing the problem.

![56845551-f017cf80-6877-11e9-944f-b39124534156](https://user-images.githubusercontent.com/3308687/56846253-20fd0200-6882-11e9-8b0b-97c5dfd4010c.png)

**Comment by introt** [comment]
Is this still happening with 0.74?

**Comment by jaap-karssenberg** [comment]
Cannot reproduce and test coverage in this area has since improved
