### ISSUE TITLE
No menu in the index pane after clicking right-click zim 0.71

### ISSUE THREAD

**Issue by deshaion** [zim-desktop-wiki/zim-desktop-wiki#816]
In zim 0.71, every time I right-click in the index pane it does nothing.

OS: Mint 18.3 (xfce4 desktop), Python 3.5.2

**Comment by jaap-karssenberg** [comment]
Could you try adding the code "`menu.show_all()`" in the file `zim/gui/widgets.py` in function `gtk_popup_at_pointer()` at line 312 ?

**Comment by jaap-karssenberg** [comment]
Btw. I expect this issue only affects systems with Gtk < 3.22 -- could you confirm?

**Comment by deshaion** [comment]
Yes, the version is 3.18.9
I've added like that:
```python
def gtk_popup_at_pointer(menu, event=None, button=3):
	logger.debug('menu.show_all() was called')
	menu.show_all()
	# Introduced in Gtk 3.22, so wrap our own to be compatible for 3.18 and up
	if hasattr(menu, 'popup_at_pointer'):
		menu.popup_at_pointer(event)
	else:
		time = event.time if event else 0
		menu.popup(None, None, None, None, button, time)
```

So I see in terminal my log but there is no menu appeared

**Comment by jaap-karssenberg** [comment]
Yes, that would be the right place to put it, thanks for testing.

If that doesn't work, I'm at a loss what else to try :(

**Comment by deshaion** [comment]
Well, It's not critical. I can find all the menu items in the main menu.
I'll try to investigate as now I know what to look at.

**Comment by deshaion** [comment]
@jaap-karssenberg I found a solution:
I made menu as member of class in `def do_button_press_event`
```
# Pop menu
self.menu = self.get_popup()
gtk_popup_at_pointer(self.menu, event)
```

**Comment by jaap-karssenberg** [comment]
Weird but apparently we need to keep the ref.

Think this is aan upstream bug that was fixed in later versions. But good
to have a workaround! Will merge over the weekend.

Jaap

Op wo 1 mei 2019 22:35 schreef Ivan Avdonin <notifications@github.com>:

**Comment by jaap-karssenberg** [comment]
I created an alternative patch for #820. This solution keeps all the logic in one place. Can you place test it?

Patch can be found here: https://gist.github.com/jaap-karssenberg/b508c2d747430ebe93bf379f7620b316

**Comment by muaadelsharif** [comment]
Hello, I've installed the latest version of Zim-Wiki 0.71.0-t201905091841~ubuntu16.04.1. 
I am afraid that the issue persists. I'm still unable to right click the index pane.

**Comment by jaap-karssenberg** [comment]
@muaadelsharif yes, I never claimed it was fixed. 

@deshaion if you could confirm whether the alternative patch works, I would be much obliged.

-- Jaap

**Comment by deshaion** [comment]
I'm on vacation now, I'll check as soon as possible on 18th of May

-----
Regards, Ivan Avdonin

**Comment by jaap-karssenberg** [comment]
No worry - will be delays to merge on my side anyway

**Comment by deshaion** [comment]
@jaap-karssenberg I've checked. It works fine.

**Comment by jaap-karssenberg** [comment]
Thanks for testing! Will merge it momentarily.
