### ISSUE TITLE
Move pages between different notebooks

### ISSUE THREAD

**Issue by svenn71** [zim-desktop-wiki/zim-desktop-wiki#823]
Is it possible to move pages between two different notebooks by drag-and-drop in the GUI? I did try to do it, but nothing happened. I read in a different issue that just moving by commands in the operating system lead to problems with links between pages. I have too many fairly equal notebooks, and I would like to reorganize my knowledge into less number of notebooks.

**Comment by veghp** [comment]
A possible workaround in the meantime is to open a new notebook in a directory that contains all existing notebooks, then rearrange the notes in the GUI.
