### ISSUE TITLE
Interpolate field codes in desktop file quoted arguments

### ISSUE THREAD

**Issue by uspoma** [zim-desktop-wiki/zim-desktop-wiki#828]
Hello!

I hope this hasn't been posted already, couldn't find a similar issue.

I can't open links that I insert in a ZIM page. For example I create a new page and write some links on that page. Let's say I write

> https://github.com

The link becomes clickable and I click it. The browser opens but instead of the URL the browser tries to open

> http://www.%u.com/

Using Firefox with Ubuntu. Other applications do open links without problems. Have to say that I had this problem with 0.68 already. Now using 0.71.

Any ideas?

**Comment by vossenjp** [comment]
Links work fine for me (any/all versions of Zim) and I use them all the time.  But Zim has a feature where you can create customer handlers for things, and it sounds to me like that got messed up and is improperly handling your links.  Maybe these will help?
* https://zim-wiki.org/manual/Help/Default_Applications.html
* https://zim-wiki.org/manual/Help/Links.html (especially the Interwiki section and config file?)

**Comment by uspoma** [comment]
@vossenjp Thanks for those links. I think I found the problem. I start firefox with a specific command that is included in the .desktop file. ZIM seems to have a problem in just adding another tabbed page to an already open firefox (or executing that specific command to start firefox in the right way).

I wonder how that comes - with other program I do not have such problems when clicking links.

**Comment by Self-Perfection** [comment]
@uspoma Your exec command is overly complicated. Why would you run shell then tell it to run firefox? Shell gives you 0.002s overhead. You should just start firefox directly with command like `Exec=/external/firefox/firefox %U` (also note that this way quotes does not get in the way)

See https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s07.html and
```bash
grep -i exec /usr/share/applications/firefox.desktop
```
for example.

**Comment by uspoma** [comment]
@Self-Perfection Thanks for your comment. I know, it's not the usual way to start firefox but it has to be like this because shell is executing some other commands. I just removed them from the example.

So in my opinion ZIM should be able to deal with it as other programs do.

**Comment by jaap-karssenberg** [comment]
Looks like zim implementation wrongly interpreted https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s07.html

**Comment by pdecat** [comment]
Can confirm current development branch now work with this:

```
Exec=bash -c "$(which gjs) ~/.local/share/gnome-shell/extensions/bowser-gnome@kronosoul.xyz/bowser.js -o %u"
```

However, it does not with:

```
Exec=bash -c '$(which gjs) ~/.local/share/gnome-shell/extensions/bowser-gnome@kronosoul.xyz/bowser.js -o "%u"'
```

This results in:
```
DEBUG: Loading config from: /home/patrick/.local/share/applications/bowser-gnome.desktop
INFO: Spawning: ('bash', '-c', "'$(which", 'gjs)', '~/.local/share/gnome-shell/extensions/bowser-gnome@kronosoul.xyz/bowser.js', '-o', 'https://stackoverflow.com/', "'") (cwd: /home/patrick)
gjs): -c: line 1: unexpected EOF while looking for matching `''
gjs): -c: line 2: syntax error: unexpected end of file
DEBUG: Process started with PID: 3099101
DEBUG: Running ErrorDialog
DEBUG: Could not open: https://stackoverflow.com/
```

**Comment by jaap-karssenberg** [comment]
Yes, following the desktop entry specification we only support double
quotes for parsing arguments, not single quotes. So behavior is as intended.

Op zo 13 mrt. 2022 11:23 schreef Patrick Decat ***@***.***>:

**Comment by jaap-karssenberg** [comment]
For reference:
https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s07.html

- Quoting uses double quotes
- Interpolating field codes in quoted strings is explicitly unspecified -
our implementation only interpolates for fields with a single argument as
return value
