### ISSUE TITLE
"Open with..." Okular selection can't be saved

### ISSUE THREAD

**Issue by davidfarlow** [zim-desktop-wiki/zim-desktop-wiki#831]
This is a duplicate of issue #208 which was closed for lack of debug info.

I'm having the same issue as that user. Running Xubuntu 16.04. Steps to reproduce:

1. System default for PDFs is Okular
2. Drag a PDF file into Zim to create a link to it
3. Click the link -> PDF opens in Document Viewer
4. Right click link -> open with -> customize
5. Change default in drop-down list from Document Viewer to Okular
6. Click close
7. Click the link -> PDF opens in Document Viewer
8. Right click link -> open with -> customize -> default is back to Document Viewer
9. Repeat steps 4 to 8 but this time selecting System Default instead of Okular (same result).

Output of zim --debug during steps 4 to 7:

DEBUG: Loading config from: /home/davidfarlow/.local/share/applications/mendeleydesktop.desktop
DEBUG: Loading config from: /usr/share/applications/evince-previewer.desktop
DEBUG: Loading config from: /usr/share/applications/zathura-pdf-poppler.desktop
DEBUG: Loading config from: /usr/share/applications/pdfchain.desktop
DEBUG: Loading config from: /usr/share/applications/evince.desktop
DEBUG: Loading config from: /usr/share/applications/xournal.desktop
DEBUG: Loading config from: /usr/share/applications/gimp.desktop
DEBUG: Loading config from: /usr/share/applications/polar-bookshelf.desktop
DEBUG: Loading config from: /usr/share/applications/kde4/okularApplication_pdf.desktop
DEBUG: Loading config from: /usr/share/applications/evince.desktop
DEBUG: Loading config from: /home/davidfarlow/.local/share/applications/mendeleydesktop.desktop
DEBUG: Loading config from: /usr/share/applications/evince-previewer.desktop
DEBUG: Loading config from: /usr/share/applications/zathura-pdf-poppler.desktop
DEBUG: Loading config from: /usr/share/applications/pdfchain.desktop
DEBUG: Loading config from: /usr/share/applications/evince.desktop
DEBUG: Loading config from: /usr/share/applications/xournal.desktop
DEBUG: Loading config from: /usr/share/applications/gimp.desktop
DEBUG: Loading config from: /usr/share/applications/polar-bookshelf.desktop
DEBUG: Loading config from: /usr/share/applications/kde4/okularApplication_pdf.desktop
DEBUG: Opening dialog "Configure Applications"
INFO: Default application for type "application/pdf" changed to: Okular
DEBUG: Closed dialog "Configure Applications"
DEBUG: Activate link: ~/Zotero/storage/ZMAXLWSH/python.org - Python Tutorial Release 3.7.3.pdf
DEBUG: open_file(/home/davidfarlow/Zotero/storage/ZMAXLWSH/python.org - Python Tutorial Release 3.7.3.pdf, None)
DEBUG: Loading config from: /usr/share/applications/evince.desktop
INFO: Spawning: ('evince', 'file:///home/davidfarlow/Zotero/storage/ZMAXLWSH/python.org%20-%20Python%20Tutorial%20Release%203.7.3.pdf') (cwd: None)
DEBUG: Process started with PID: 14289

**Comment by jb-stack** [comment]
I'm having the same issue in Zim 0.72.0 in Ubuntu 20.04.

**Comment by jaap-karssenberg** [comment]
Suppose this to be fixed with recent fix for looking up KDE application bindings.
