### ISSUE TITLE
Zim 0.71 - Delete Page doesn't work

### ISSUE THREAD

**Issue by domhnallw** [zim-desktop-wiki/zim-desktop-wiki#833]
Hi All: 

Using Zim 0.71 on Ubuntu 18.04 (x86-64). Configured language on my system is UK English (en_GB) and the system-wide Python version is 2.7.15rc1. I installed Zim 0.71 from the PPA at http://ppa.launchpad.net/jaap.karssenberg/zim/ubuntu via APT.

When I attempt to delete a page, either using the right-click context menu or using File -> Delete Page from the menu, the page is not deleted, and the the currently open entry sometimes jumps to a different page.

I'm pretty sure this was working in 0.70 but couldn't swear to it. No message is dumped to the console if I try this having started Zim from the command line.

Thanks for your time,
Domhnall.

**Comment by sh2ka** [comment]
Same to me

**Comment by domhnallw** [comment]
Looks to be fixed in the most recent update (0.71.0). Thanks.
