### ISSUE TITLE
Pages with Russian/Cyrillic names won't sort alphabetically

### ISSUE THREAD

**Issue by ross41** [zim-desktop-wiki/zim-desktop-wiki#838]
Version: 0.69.1, Windows.

While English names work perfectly (A -> B - > C) and so on, Russian seem to be completely random. All of the characters are off their place.

Whole index tree becomes an eyesore after you add at least 2-3 pages or sub-pages. Breaks the work flow and reduces usability.

I even took a liberty of writing down how exactly Zim sorts pages right now:

> Б-Л-А-Е-Ж-З-Й-Д-И-К-О-Н-Г-В-П-М-Ё-Т-Ф-Ы-Ш-Х-Ц-Ч-Щ-У-С-Р-Э-Ъ-Ь-Ю-Я

And how it's supposed to be (Russian alphabet, basically):

> А-Б-В-Г-Д-Е-Ё-Ж-З-И-Й-К-Л-М-Н-О-П-Р-С-Т-У-Ф-Х-Ц-Ч-Ш-Щ-Ъ-Ы-Ь-Э-Ю-Я

Totally wrong. Not much else to say. I know this bug is long present.

**Comment by introt** [comment]
Related:  Zim's page sorting is regularly confusing and makes no sense #1442

Can't reproduce in 0.74 - please let me know if this is not the case on your system

![image](https://user-images.githubusercontent.com/26069787/146145753-113890f5-ec29-49b2-b036-649f9aa71382.png)
