### ISSUE TITLE
Feature Request: CSS

### ISSUE THREAD

**Issue by GoddessOfCreation** [zim-desktop-wiki/zim-desktop-wiki#839]
Though my main request is for the editor to have margins so it didn't look silly when in full screen, it would be amazing if Zim could read CSS and have it apply directly to the editor. It would go a long way towards making Zim prettier and more reader-friendly.

**Comment by introt** [comment]
> margins so it didn't look silly when in full screen

The Distraction Free Editing plugin provides this: https://zim-wiki.org/manual/Plugins/Distraction_Free_Editing.html

> read CSS and have it apply directly to the editor

Do you mean instead of/in addition to `style.conf`? Might be possible via a plugin.
