### ISSUE TITLE
Command-Left, Command-Right, Alt-Left and Alt-Right are not working as usual in OSX

### ISSUE THREAD

**Issue by basovink** [zim-desktop-wiki/zim-desktop-wiki#840]
The cursor navigation keys are not working as usual in OSX.
These are the actions that 90% of OSX apps adhere to. I use them constantly and since some are doing nothing, others doing page navigation it makes it very confusing to use Zim

Keypress | Standard OSX behaviour | Zim Behaviour
---------|--------|------
Command-Left | Start of line | none
Command-Right | End of line | none
Alt-Left | Previous word/whitespace | Previous page
Alt-Right  | Next word/whitespace | Next page

**Comment by arigit** [comment]
@basovink which zim version are you testing with?

**Comment by basovink** [comment]
0.69

The newer versions are currently broken on OSX

**Comment by arigit** [comment]
> The newer versions are currently broken on OSX

I tested 0.71.1 on MacOS (mojave) recently, it works fairly well (and looks nicer than <0.7, when gtk3 uses a mojave-dark theme

I ended up going back to GTK2 / 0.69.1. In my setup Cmd+Left/Right works as per the standard osx behavior. 
Alt left/right behaves wrongly, same as you describe.

FWIW, the GTK3 issues I found vs GTK2 are:
	* Drag & drop from Finder not working
	* Menubar integration - MacOS menubar plugin is gone
	* Rich copy/paste from external apps 
	* Page Up/Down key bindings not working on WinKeyboard
	* Window management issues due probably to GTK3, with two consequences: 
		* BTT snapping windows does not kick-in
		* Restoring minimized windows by clicking the icon in the dock does not work,
	* Source View plugin not working (unable to detect gtksourceview)

**Comment by andredasilvapinto** [comment]
I also confirm that zim with gtk3 (current install from brew) is broken in many ways. As suggested by @arigit I moved back to GTK2 and zim 0.69.1.

Fot that you need to install python 2. You might have to do it via a specific commit, eg:

```
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/86a44a0a552c673a05f11018459c9f5faae3becc/Formula/python@2.rb
```

install pygobject gtk pygtk
```
brew install pygobject gtk+ pygtk
```

I also had to install and link libffi
```
brew install libffi
ln -s /usr/local/opt/libffi/lib/libffi.7.dylib /usr/local/opt/libffi/lib/libffi.6.dylib
```

I think that was it... hope it helps other people.

It's sad that we still need to go through all of this to get zim to work on mac after all these years... it tells a lot about the stability of the python ecosystem imo.

**Comment by dehesselle** [comment]
Upgrade to the new Zim.app from the website.

- The behavior of `Alt-Left/Right` can be configured in the preferences (delete the current setting).
- The behavior of `Cmd-Left/Right` works as expected.
