### ISSUE TITLE
When zim started without terminal, crashes with "input/output error"

### ISSUE THREAD

**Issue by facundobatista** [zim-desktop-wiki/zim-desktop-wiki#842]
I have zim 0.71.0 installed from APT under KDE Neon under Ubuntu Bionic.

Starting `zim` from applications (normal procedure after clicking the "window" key) makes it crash.

I tried also from the [Launcherposta](http://launcherposta.taniquetil.com.ar/) project and the behaviour is the same.

I tracked the problem until the `ZimApplication._daemonize` method, where (after deciding it's not started from a terminal) it tries to daemonize, and it just crashes with any of the two following lines: 
```
			sys.stdout.flush()
			sys.stderr.flush()
```

If I comment those two out, all works just fine

**Comment by jaap-karssenberg** [comment]
Testing under Ubuntu Gnome, I don't see any such issue.

I've found this statement in the docs -- could you test a change where
instead of commenting the lines you put "if sys.stdout is not None:"  as a
wrapper ?


*Note*

Under some conditions stdin, stdout and stderr as well as the original
values __stdin__, __stdout__ and __stderr__ can be None. It is usually the
case for Windows GUI apps that aren’t connected to a console and Python
apps started with *pythonw*.


Regards,

Jaap

**Comment by facundobatista** [comment]
They are not None, they are:
stdout: `<_io.TextIOWrapper name='<stdout>' mode='w' encoding='ANSI_X3.4-1968'>`
stderr: `<_io.TextIOWrapper name='<stderr>' mode='w' encoding='ANSI_X3.4-1968'>`

The traceback when flushing is:

```
2019-05-14 10:48:22,573  zim                DEBUG    Exception in main()
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/main/__init__.py", line 917, in main
    ZIM_APPLICATION.run(*argv[1:])
  File "/usr/lib/python3/dist-packages/zim/main/__init__.py", line 684, in run
    self._run_cmd(cmd, args) # test seam
  File "/usr/lib/python3/dist-packages/zim/main/__init__.py", line 714, in _run_cmd
    self._run_main_loop(cmd)
  File "/usr/lib/python3/dist-packages/zim/main/__init__.py", line 751, in _run_main_loop
    self._daemonize()
  File "/usr/lib/python3/dist-packages/zim/main/__init__.py", line 874, in _daemonize
    sys.stderr.flush()
OSError: [Errno 5] Input/output error
```

I'm glad to help you debugging this.

**Comment by jaap-karssenberg** [comment]
In that case I'll patch it by first checking whether they are not None
(just in case) and then wrap in try .. except .. to catch the OSError -
that should make it robust

Thanks for the information!
