### ISSUE TITLE
Third Party Plugins in 0.69.1

### ISSUE THREAD

**Issue by OxeStone** [zim-desktop-wiki/zim-desktop-wiki#843]
Third party plugins such as the 'Theme Manager' show up in zim debug but not in zim. Any suggestions? I am running 'zim portable' on Windows.

**Comment by jaap-karssenberg** [comment]
Sorry but can you elaborate what you mean?

**Comment by OxeStone** [comment]
I put 'Theme Manager' in the 'plugins' folder. When I run 'zim.exe' 'Theme Manager' does not show up in the 'Preferences - > Plugins' menu and no theme is applied. However, when I start zim with the debug option the specified theme is applied and 'Theme Manager' is displayed in the menu.

**Comment by jaap-karssenberg** [comment]
When you say "start zim with the debug option" do you mean you start the
same .exe or a do you e.g. run from source?

-- Jaap

**Comment by OxeStone** [comment]
'zim\App\launch zim with debug mode.exe'

**Comment by jaap-karssenberg** [comment]
As far as I can judge the lookup path for both executables should be the
same. This debug executable is from the portable version, so path for the
plugin folder should be "App\Data\zim\plugins" relative to the install
folder.

One final thing you could check is to see if you use the "open plugin
folder" button in the preferences dialog it comes up with the same folder
in both executables. If this is the case, there is a but that requires a
fix in the code or a ".bat" file to fix the environment before execution.

Regards,

Jaap

**Comment by OxeStone** [comment]
Yes the same folder is opened in both executables. Should I put the '__init.py__' ifile in your link above n the 'zim\App\Data\zim\plugins' folder?

**Comment by jaap-karssenberg** [comment]
That is a good idea, but I'm not sure it will work since the executable
also contains compiled libraries internally.

If that doesn't work I'm afraid I lack sufficient knowledge of how the
executable framework differs from the normal python environment.

-- Jaap

**Comment by fladd** [comment]
Same issue here on a normal install on Windows. Plugin (Journal Now Button) is loaded when using the debug exe, but not when using the normal one.

**Comment by fladd** [comment]
Ironically, the log that is created in debug mode (the mode that **does** load the plugin), puts this into the log:

```
WARNING: C:\Program Files (x86)\Zim Desktop Wiki\zim.exe\zim\plugins\__init__.py:766: GtkWarning: Inserting action group 'MainWindowExtension' into UI manager which already has a group with this name


WARNING: C:\Program Files (x86)\Zim Desktop Wiki\zim.exe\zim\gui\__init__.py:2309: GtkWarning: open_page_back_alt1: missing action open_page_back_alt1

WARNING: C:\Program Files (x86)\Zim Desktop Wiki\zim.exe\zim\gui\__init__.py:2309: GtkWarning: open_page_forward_alt1: missing action open_page_forward_alt1

WARNING: os.startfile does not support a callback
ERROR: Could not load plugin nowbutton
Traceback (most recent call last):
  File "zim\gui\preferencesdialog.pyo", line 323, in __init__
  File "zim\plugins\__init__.pyo", line 211, in get_plugin_class
  File "zim\utils\__init__.pyo", line 39, in get_module
ImportError: No module named nowbutton
WARNING: os.startfile does not support a callback
WARNING: os.startfile does not support a callback
WARNING: os.startfile does not support a callback
ERROR: Could not load plugin nowbutton
Traceback (most recent call last):
  File "zim\gui\preferencesdialog.pyo", line 323, in __init__
  File "zim\plugins\__init__.pyo", line 211, in get_plugin_class
  File "zim\utils\__init__.pyo", line 39, in get_module
ImportError: No module named nowbutton
```

**Comment by introt** [comment]
This issue is related to a Zim version older than 0.70; please open a new issue if the problem persists with later versions.
