### ISSUE TITLE
Box Around Equation

### ISSUE THREAD

**Issue by LouisWAdamsJr** [zim-desktop-wiki/zim-desktop-wiki#848]
After upgrading to Zim 0.71.0 I have boxes around my equations.  This has never happened in previous versions.  See attachment.

![BoxedEquation](https://user-images.githubusercontent.com/50884965/58121473-8cae6280-7bd5-11e9-9d37-c6f894c50c18.png)

How do I remove the boxes?

I use Ubuntu 18.04, GNOME Shell.

**Comment by jaap-karssenberg** [comment]
This is expected behavior since equations are now using inline objects.
These have a slight border.

**Comment by LouisWAdamsJr** [comment]
I use Zim as my computerized research journal, which usually includes many equations.  The pages look very strange to me with boxed equations.  This is not the traditional way that mathematics is presented in books and journals.  Please consider reverting to the original Zim style of presenting equations without boxes in future versions of Zim.  Thank you.

**Comment by pityhero233** [comment]
I actually second this, equation editor would be almost totally unusable in mathematical writting with the box ... Why is this closed?
