### ISSUE TITLE
Full Justification of Text

### ISSUE THREAD

**Issue by LouisWAdamsJr** [zim-desktop-wiki/zim-desktop-wiki#849]
In the past I've modified style.conf so text is fully justified.  After upgrading to version 0.71.0 adding that tag has no effect: the text is left justified.  See style file attached.

[style.txt](https://github.com/zim-desktop-wiki/zim-desktop-wiki/files/3203981/style.txt)

Can you advise me how to get fully justified text?

I use Ubuntu 18.04, GNOME Shell.

**Comment by sphaisell** [comment]
I've also recently upgraded to 0.71.0 and having the same problem.

Is it possible to change the text to fully justified?

**Comment by cheap-glitch** [comment]
Same issue here with 0.72 on Arch Linux. The _justified_ property in the [TextView] section of style.conf is totally ignored by zim.

**Comment by introt** [comment]
I think I accidentally stumbled upon the reason, found this in the logs:

```
ERROR: Exception while setting justification:
Traceback (most recent call last):
  File "/home/introt/repos/zim-desktop-wiki/zim/gui/pageview/__init__.py", line 6066, in on_text_style_changed
    assert hasattr(gtk, const), 'No such constant: Gtk.%s' % const
NameError: name 'gtk' is not defined
```

It's kinda ironic - the assertion should throw an AssertionError, but errors out ifself :P
