### ISSUE TITLE
Spelling Checker

### ISSUE THREAD

**Issue by LouisWAdamsJr** [zim-desktop-wiki/zim-desktop-wiki#851]
I've followed the instructions posted on https://zim-wiki.org/manual/Plugins/Spell_Checker.html: python3-gtkspellcheck and gir1.2-gtkspell3-3.0 are both installed, but Zim continues to report that "gtkspell - Failed".  The spell checker worked fine in previous versions of Zim on my PC.  Any further suggestions?

I use Ubuntu 18.04, GNOME Shell.

**Comment by Self-Perfection** [comment]
Which zim version do you use?

Instructions at https://zim-wiki.org/manual/Plugins/Spell_Checker.html are intended for most recent zim release - 0.71. Ubuntu 18.04 repos provide version around 0.68. And zim was switched to python3 in version 0.70, so dependencies changed.

See instructions in manual bundled with your zim installation (F1).

**Comment by LouisWAdamsJr** [comment]
I'm using Zim 0.71, so the instructions that I used to install the spelling checker are for that version.

**Comment by introt** [comment]
Are you still having this issue with 0.74?

**Comment by introt** [comment]
The plugin needs one of the two; if `pip install gtkspellcheck` doesn't work, please open a new issue
