### ISSUE TITLE
Open with customized application does recognise ~ as pointing to home folder

### ISSUE THREAD

**Issue by davidfarlow** [zim-desktop-wiki/zim-desktop-wiki#852]
Zim version: Zim 0.68-rc1
OS: Xubuntu 18.04

Steps to reproduce:
1. Right click a link > open with > customize > add application
2. Enter something for the name
3. In command, enter path to an executable in your home folder using ~ e.g. "~/myscript.sh"
4. Click ok
5. Get error: Could not find executable "~/myscript.sh"
6. Click close
7. Change command to "/home/yourusername/myscript.sh"
8. Click ok
9. No error.

**Comment by introt** [comment]
Not a Zim issue - expanding `~` to home path is a shell feature; see https://stackoverflow.com/questions/998626/meaning-of-tilde-in-linux-bash-not-home-directory
