### ISSUE TITLE
[Request] When moving a table element up/down, move the selection along.

### ISSUE THREAD

**Issue by magpie514** [zim-desktop-wiki/zim-desktop-wiki#853]
Right now on current git master, trying to move down an element in a table will succeed fine, but leave the cursor in the original position where the former next row is now. Same if you try to move it up.
This means that clicking on the "down" button more than once just creates a loop, as opposed to continue moving the same row down, which could be solved just by moving the selection in the chosen direction.

**Comment by introt** [comment]
Can reproduce with 0.74

**Comment by tridian-tn** [comment]
Related: https://github.com/zim-desktop-wiki/zim-desktop-wiki/discussions/2269
