### ISSUE TITLE
I should able to store data in database

### ISSUE THREAD

**Issue by PiotrGen** [zim-desktop-wiki/zim-desktop-wiki#857]
For the better cooperation purpose I should be able to store notes in database.

PS great soft :D thank you

**Comment by Nick222** [comment]
See CherryTree

**Comment by introt** [comment]
This is out-of-scope for the project: "Zim is a graphical text editor used to maintain a collection of wiki pages. -- All data is stored in plain text files". Please open a discussion for further discussion.
