### ISSUE TITLE
spaces in indentation are translated to tabs

### ISSUE THREAD

**Issue by facundobatista** [zim-desktop-wiki/zim-desktop-wiki#859]
I write some text and then indent some of it using spaces. 

I'd love the editor to respect those spaces. 

But no, they are translated to tabs.

How can I disable that translation?

Thanks!

**Comment by jaap-karssenberg** [comment]
You can't. The Zim wiki syntax is written using tab for indent. There is no
option to change that currently.

Op di 28 mei 2019 19:29 schreef Facundo Batista <notifications@github.com>:

**Comment by facundobatista** [comment]
Ugh, sorry to hear that, these tabs are currently destroying my workflow ... I use zim 99% of the time to store commands that then I copy and paste into the terminal; I split really long commands into several lines, indenting the second and subsequent ones (otherwise it's a mess), and having a tab makes the shell to do strange things when I paste it :(

Maybe there's a way to completely disable the "wikiness" of zim?

Or, something that just thought: send spaces not tabs to the clipboard when copied?

Something a little more complicated would be to detect only "indented blocks" when the previous line is empty.

**Comment by facundobatista** [comment]
I finally started to use "literal" for those blocks, but had to touch the style to make it look better (added this scale in `gui/pageview.py`:

```
 'pre': {'family': 'monospace', 'wrap-mode': Gtk.WrapMode.NONE, 'scale': 0.8},
```

Is there a better way to modify this style? thanks!!

**Comment by jaap-karssenberg** [comment]
See the manual about the "style.conf" config file.

Regards,

Jaap

**Comment by facundobatista** [comment]
Ah, wonderful! I have great control there! I could not only reduce the font size but also eliminate the indent.

Wonderful! Thanks for all the help!!!

**Comment by plegrand1** [comment]
> I finally started to use "literal" for those blocks, but had to touch the style to make it look better (added this scale in `gui/pageview.py`:
> 
> ```
>  'pre': {'family': 'monospace', 'wrap-mode': Gtk.WrapMode.NONE, 'scale': 0.8},
> ```
> 
> Is there a better way to modify this style? thanks!!

Hello, i know that tis issue is very old, but i've got the same problem and i dont know how to solve this problem.
What do you mean by using "literal"?
Thanks for your help
Pascal

**Comment by osky85** [comment]
@plegrand1 I think he means he is using "Verbatim" or pre-formated text. You can right click and choose paste as Verbatim and I think the spaces will be kept.  The reference to gui/pageview.py is just to change the the style of Verbatim so you can ignore that part.

**Comment by plegrand1** [comment]
Hello,
during my research on the internet to try and solve my problem, I discovered that there was a plugin for ZIM "Source_View" (https://zim-wiki.org/manual/Plugins/Source_View.html) which allowed to insert a block code.
This plugin answers my question perfectly.

@osky85, thanks for your help.

Pascal
