### ISSUE TITLE
Make linespacing in wrapped lines configurable

### ISSUE THREAD

**Issue by sojusnik** [zim-desktop-wiki/zim-desktop-wiki#86]
I'm referring to [this](https://bugs.launchpad.net/zim/+bug/1537876) and [this](https://answers.launchpad.net/zim/+question/264064).

**Comment by jaap-karssenberg** [comment]
See http://zim-wiki.org/manual/Help/Config_Files.html - does "linespacing" do what you are looking for ?

**Comment by sojusnik** [comment]
No, see quote from the link above:

> The 'linespacing' option in style.conf only dictates the spacing from one paragraph to the next, which in editorial context is called "space after" or "space below". I honestly think it should be called "paragraph spacing", in both contexts.
> 
> Zim could support a per line spacing, improving the readability of text, as well as allowing us to use alternative fonts that are quite packed. Linux Biolinum, for instance, is too crowded without line spacing, but is very readable when the lines are spread.

**Comment by jaap-karssenberg** [comment]
Implement similar to "linespacing" but use gtk.TextView.set_pixels_inside_wrap

Or make "linespacing" affect both and add a new "paragraphspacing" to set set_pixels_below_lines realtive to linespacing
