### ISSUE TITLE
Renaming a page does not rename referenced links as announced

### ISSUE THREAD

**Issue by kklepper** [zim-desktop-wiki/zim-desktop-wiki#860]
Tested on Windows version 0.69.1

Make some pages, put links on them to first page, then rename first page and check `# links to this page will be adjusted` -- so everything looks as it should -- but it does not happen. So those links are broken.

If you rename again, of course, no links back to this page can be found... Renaming to original name makes all original links work again, not surprisingly.

**Comment by kklepper** [comment]
Moving pages does work like expected.

**Comment by introt** [comment]
Can you reproduce this on 0.74? Please post the wikitext for the links - are they relative or absolute?

**Comment by nelas** [comment]
It seems similar to #1725 which was fixed with cfc7500d0d4cfbb09fc314ab8ae519da0982f17d

**Comment by introt** [comment]
Seems so. Please @ me if you're still experiencing this issue on 0.74.3 @kklepper and I shall reopen the issue
