### ISSUE TITLE
[SOLVED] Include symbols for box-drawing characters

### ISSUE THREAD

**Issue by Enjymon** [zim-desktop-wiki/zim-desktop-wiki#863]
This is more an enhancement suggestion than an issue.

It would be very convenient and useful to have access to the box-drawing characters in the Insert:Symbol... menu:

┘
┐
┌
└
┼
─
├
┤
┴
┬
│

See also: [https://en.wikipedia.org/wiki/Box-drawing_character#Unix,_CP/M,_BBS](https://en.wikipedia.org/wiki/Box-drawing_character#Unix,_CP/M,_BBS)

**Comment by Enjymon** [comment]
I solved it. 
I just inserted the following lines at the end of the file symbols.list:

```
## Box-drawing characters ##
\bdul	9496	# ┘ (box-drawing up and left)
\bddl	9488	# ┐ (box-drawing down and left)
\bddr	9484	# ┌ (box-drawing down and right)
\bdur	9492	# └ (box-drawing up and right)
\bdvh	9532	# ┼ (box-drawing vertical and horizontal)
\bdh	9472	# ─ (box-drawing horizontal)
\bdvr	9500	# ├ (box-drawing vertical and right)
\bdvl	9508	# ┤ (box-drawing vertical and left)
\bduh	9524	# ┴ (box-drawing up and horizontal)
\bddh	9516	# ┬ (box-drawing down and horizontal)
\bdv	9474	# │ (box-drawing vertical) 
```

I referred to those two links:
[https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/846
](https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/846
)[https://www.unicode.org/charts/PDF/U2500.pdf](https://www.unicode.org/charts/PDF/U2500.pdf)

**Comment by dehesselle** [comment]
Nice! I'll create a PR for this.
