### ISSUE TITLE
Insert image fails

### ISSUE THREAD

**Issue by kidspbmm** [zim-desktop-wiki/zim-desktop-wiki#864]
Thank you for a great product.

I am using Zim on a Ubuntu computer. The wiki (notebook and files) is on a network USB attached to my router, so I can use it from multiple computers.

When attaching an image to a wiki text file, if I use the icon (paperclip), I can select the image, and indeed it transfers to a newly created directory, but I get an 'Permission Denied' error that prevents the wiki saving the modified .txt file. It is not a problem with file permissions on the the USB as far as I can tell.

However, If I use the menu (Insert --> Image) I do not get this error, and it all works..

I am not a sophisticated user, so I am not sure where to look for the error log to help with this further.

It doesn't stop me using the product (I just use the menu) but I thought I would share the error.

**Comment by jonasstein** [comment]
you are working on a network mount. How did you exactly mount the drive? Is it NFS?

**Comment by introt** [comment]
@kidspbmm Can you please try to reproduce this with 0.74 and paste the log from Tools > View debug log?
