### ISSUE TITLE
Wrong rendering in small window

### ISSUE THREAD

**Issue by tehkonst** [zim-desktop-wiki/zim-desktop-wiki#865]
When a window of zim is small enough, and I try inserting something from clipboard closer to the end of the file, I always get lines on the wrong places and it's impossible to use the document until full reloading or resizing the window.

To reproduce this behavior, add to a document a lot of text,
then resize window to the minimum,
then try pasting something from clipboard to the end of the file.

**Comment by vossenjp** [comment]
This may be the garbled paste issue I just mentioned in #1276.

**Comment by introt** [comment]
Can you still reproduce this with 0.74?

**Comment by tehkonst** [comment]
No. I'll close this
