### ISSUE TITLE
Inserting latex equation quickly

### ISSUE THREAD

**Issue by MatiasKorn** [zim-desktop-wiki/zim-desktop-wiki#866]
Hello,

Is it possible to maybe have a shortcut that changes the selection or line or something into an image equation?

I am looking at zim and it really feels complete except for things like this.

Am I missing something? 

Thank you

**Comment by jaap-karssenberg** [comment]
Afraid shorted sequence is Ctrl-X, keybinding to open menu, insert equation, Ctrl-V
