### ISSUE TITLE
Alphabetical ordering of pages in MacOS not working

### ISSUE THREAD

**Issue by arigit** [zim-desktop-wiki/zim-desktop-wiki#867]
Alphabetical ordering of pages in the index sidebar is for some reason not working at all on MacOS.
Screenshot from zim 0.69.1:

<img width="138" alt="image" src="https://user-images.githubusercontent.com/652673/58820833-b027d300-8601-11e9-9fc9-84290116a540.png">

Is this the expected behavior? I am pretty sure in Linux and Windows page ordering was working properly.

Wondering - Is there a setting somewhere that needs to be changed for MacOS

**Comment by StephenClayMcGehee** [comment]
Apparently there is the same issue when using Linux.
Zim 0.68
Ubuntu 19.04
It sorted just fine before I updated Ubuntu (and probably Zim, as well). Now, new pages are added at the bottom of the list. All else seems to be working just fine.

**Comment by jaap-karssenberg** [comment]
This can happen if there is a change in the locale settings. See if a
rebuild of the index ("zim --index -V path/to/notebook") helps. In the
latest version there is better detection for this issue triggering
automatic index updates.

-- Jaap

**Comment by arigit** [comment]
I can confirm that zim 0.71.1 on MacOSX does not have this problem.
Closing.
