### ISSUE TITLE
No instructions on how to uninstall on linux

### ISSUE THREAD

**Issue by mrpandey** [zim-desktop-wiki/zim-desktop-wiki#868]
I installed zim from source using `./setup.py install`. It was successfully installed, but now I want to uninstall. I checked the readme, website, github wiki and searched the issues. No information found on how to uninstall the program.

Clearly, `./setup.py uninstall` isn't a valid command. Please help me here. And if possible, please add uninstall information on readme.

**Comment by jaap-karssenberg** [comment]
Please have a look at these suggestions:
https://stackoverflow.com/questions/1550226/python-setup-py-uninstall

**Comment by mrpandey** [comment]
Thank you @jaap-karssenberg. One of the solutions worked. For future references, I have mentioned the steps that worked for me.

1. Change directory to zim source (`zim-desktop-wiki`)
2. Run `sudo python3 setup.py install --record files.txt`. This reinstalls zim and stores location of all the file created in `files.txt`.
3. `sudo rm $(cat files.txt)`

Further, there might be several empty directories at `/usr/local/lib/python3.7/dist-packages/zim/` and `/usr/local/share/zim/` which can be deleted manually.
