### ISSUE TITLE
Issues with equation and rendering

### ISSUE THREAD

**Issue by fanaticode** [zim-desktop-wiki/zim-desktop-wiki#869]
There are 2 issues relating to latex equation editor,

1. The option to edit equation is removed from context menu, which was very handy when editing long equations.

2. Editing text around the equation image causes rendering issues and some lines are removed just by using the arrow keys.

**Comment by jaap-karssenberg** [comment]
Just confirmed that context menu is working on latest version. Maybe you had the plugin disabled and got the "raw" image ?

Rendering issue is reported already on other tickets
