### ISSUE TITLE
add code portions fold/unfold in code blocks

### ISSUE THREAD

**Issue by lalebarde** [zim-desktop-wiki/zim-desktop-wiki#870]
Documenting code or including code snippets in Zim pages may take place and makes the surrounding text (the one not in the code blocks) hard to read. Changing the code block viewer for one managing fold/unfold depending on indentation or block syntax and keeping fold details in memory and allowing full fold/unfold would be a nice new feature.

**Comment by jaap-karssenberg** [comment]
Consider this a duplicte of #474
