### ISSUE TITLE
undo history dissapears when changing notes

### ISSUE THREAD

**Issue by quesada** [zim-desktop-wiki/zim-desktop-wiki#872]
To reproduce:
- do work on note A
- go to note B
- go back to A. try to undo. Nothing happens.

This is a bit dangerous. I'm sure there's no easy fix, but bringing the issue up anyway just in case.

**Comment by quesada** [comment]
Quick ping to remind everyone that this one can bite you.

**Comment by jsosulski** [comment]
Lost a bit of work to this. Fortunately, I had a more or less recent git commit.

Anyone know where the issue is? Have not developed in python-gtk before.

**Comment by introt** [comment]
This should be fixed in the recent versions - IIRC undo stack is preserved for the last 10 pages. Please open a new issue if the problem persists. Thanks!
