### ISSUE TITLE
[tasklist] Add start date column in the TaskList plugin?

### ISSUE THREAD

**Issue by velardevines** [zim-desktop-wiki/zim-desktop-wiki#873]
Recently started using Zim on Window 10 PC. I'm using the Tasklist and Journal plugins and a few others. 

Anyway, would you consider adding the start date as a column in Tasklist? I display the Tasklist in the separate window, not in the side pane. The start date would be a column similar to how the due date is currently displayed. 

--Bill

**Comment by murattepegoz** [comment]
+1

**Comment by dcdevg** [comment]
+1
This would be very helpful

**Comment by jaap-karssenberg** [comment]
Also take along #1283

**Comment by velardevines** [comment]
Thank you.  I will update and take a look.

**Comment by jaap-karssenberg** [comment]
Item is planned, not yet fixed

Op wo 24 nov. 2021 01:24 schreef velardevines ***@***.***>:
