### ISSUE TITLE
Button icons not loading on MacOS with zim 0.71.1

### ISSUE THREAD

**Issue by basovink** [zim-desktop-wiki/zim-desktop-wiki#876]
Working fine with 0.69 on the same machine. I use /usr/local/bin/python3 ./zim.py to start zim 0.71 and /usr/local/bin/python ./zim.py to start zim.69

![image](https://user-images.githubusercontent.com/527774/59298123-18258b80-8c8a-11e9-9109-5cb2a511d75e.png)

**Comment by kjyv** [comment]
This is because gtk3 uses the adwaita theme by default which uses the adwaita-icon-theme which probably needs to be installed on your machine.

**Comment by introt** [comment]
Hi! There's now a new MacOS installer, please open a new issue if the problem persists using it or after installing the icon theme. Thank you!
