### ISSUE TITLE
Zim 0.69.1 missing Table plugin missing

### ISSUE THREAD

**Issue by Enkouyami** [zim-desktop-wiki/zim-desktop-wiki#879]
On Zim 0.69.1 running on Windows 10,  the Table Editor plugin is missing.

[Inserting a table directly](https://zim-wiki.org/manual/Plugins/Table_Editor/Basic_Table_Operations.html) within the textarea, only formats the text, and below it states that "No plugin is available to display this object".

**Comment by jaap-karssenberg** [comment]
Please check the error log to see why the plugin is failing to load. Error
should be logged when you open the preference dialog.

Regards,

Jaap



Op vr 14 jun. 2019 20:30 schreef Ely Lizaire <notifications@github.com>:

**Comment by introt** [comment]
Please open a new issue if the problem persists on later versions. Thanks!
