### ISSUE TITLE
missing calendar icon

### ISSUE THREAD

**Issue by ekuser** [zim-desktop-wiki/zim-desktop-wiki#882]
After an upgrade to Zim 0.71.1 on Fedora 30 the calendar icon is missing from the toolbar. Are there any alternate ways to add new calendar entries to the Journal?

**Comment by jaap-karssenberg** [comment]
The calendar got moved to a side-pane instead of a dialog. To navigate to
the current date you can use the "Alt-D" keybinding.

-- Jaap

**Comment by ekuser** [comment]
Got it. Thank you so much.

**Comment by RadoslavCap** [comment]
Is it the same calendar as is descibed here? 
https://zim-wiki.org/manual/Plugins/Calendar.html

**Comment by krisztianmukli** [comment]
There is a new plugin in 0.7x branch, called Journal, which is similar to the Calendar, but a little different.
https://zim-wiki.org/manual/Plugins/Journal.html

**Comment by RadoslavCap** [comment]
Should we update documentation? It's misleading because there is no standalone calendar plugin.

**Comment by introt** [comment]
While the old link is alive, Calendar is no longer included in the manual.
