### ISSUE TITLE
Show pages immediately while moving through index

### ISSUE THREAD

**Issue by pla220a** [zim-desktop-wiki/zim-desktop-wiki#886]
When the index has focus I would be able to search through the content of the pages. 
After moving from one entry to the next in the index the respective page should immediately show up in the right window. But the focus should stay on the index, so that it is possible to go on walking through the index and see the contents page by page. 
I am used to this behavior from other tree-structured programs. I think it is very helpful.

**Comment by jaap-karssenberg** [comment]
This is a "won't fix" - will break keyboard navigation of the index if each page is opened immediately
