### ISSUE TITLE
Whole part of the toolbar missing since 0.70

### ISSUE THREAD

**Issue by Trimardio** [zim-desktop-wiki/zim-desktop-wiki#888]
Hello!

I'm having this problem since arriving at 0.70. 
![Screenshot_2019-07-04_19-39-47](https://user-images.githubusercontent.com/17239293/60682550-f1770100-9e93-11e9-8226-8207986946ef.png)

Only side panes, home, back and forward are shown.
The "view" menu is empty
"Insert" menu is empty except for the "date and time" option

I'm on xubuntu bionic 18.04

There was some warning when starting from command line but after correcting the problematic lines in the gtk3 file they disappear (like: Theme parsing error: gtk.css:123:31: The :insensitive pseudo-class is deprecated. )

"show_toolbar=True" in the cache file

Maybe there is something obvious I'm not getting because I didn't see anybody else having this problem. someone has an idea?

Thanks a lot by advance for any pointer!

**Comment by jaap-karssenberg** [comment]
Looks like something crashed when loading the editor actions.

Have you run zim with the "--debug" mode to check for more errors in the
terminal ?

-- Jaap

**Comment by Trimardio** [comment]
Thank you! didn't know about the debug option.

The problem was apparently a propriety problem. I had some bugs like: "(zim:3187): Gtk-CRITICAL **: 16:11:33.750: gtk_menu_item_get_submenu: assertion 'GTK_IS_MENU_ITEM (menu_item)' failed
"

Starting with sudo remove the bug. But changing ownership of the zim app doesn't seem to change much to the bug.

Anyway, it seems it must have something to do with how I badly installed my OS and GTK rather than a zim specific problem so I think it's an acceptable workaround!

Thanks a lot!
And thanks for the app btw, your saving my education!
