### ISSUE TITLE
Menuitems dont highlight (undo menu item)

### ISSUE THREAD

**Issue by greencoloured** [zim-desktop-wiki/zim-desktop-wiki#891]
Zim: 0.71.1
Fedora: 30

I'm not sure if this is limited to the Undo menuitem under Edit, but that is the only place that I have seen this happening. The menu item doesn't look disabled (or noticeably greyed out in any way), but doesn't get the blue highlight when hovering the mouse over it and when clicking it initially nothing happens but then after a second the menu disappears.

**Comment by introt** [comment]
Can't reproduce with 0.74 - please open a new issue if the problem persists
