### ISSUE TITLE
I suspect something is wrong with my index. Help with debugging it?

### ISSUE THREAD

**Issue by quesada** [zim-desktop-wiki/zim-desktop-wiki#893]
When I create a new page, it takes about >300 ms. for the popup to come up. This was not the case before, even with an old computer the feeling was instant. I suspect my index is corrupted. I tried recreating index, the problem persists. What else could I be looking at?

Index and search seem to be a sore point in vim now. I totally understand improvement on a feature that 'core' will be hard. I wonder if anyone else would be willing to pool money for a big donation to help Jaap (or anyone else) to justify spending time on search/indexing?

What do you think?

**Comment by quesada** [comment]
Since zim uses external tools really well to gain functionality (eg graphviz) 'the unix way'... here's one interesting idea, using ctags:
https://benoithamelin.tumblr.com/vimlinknotes

**Comment by introt** [comment]
Are you still having this issue with 0.74? What's your operating system?
