### ISSUE TITLE
Crash while formating

### ISSUE THREAD

**Issue by Nick222** [zim-desktop-wiki/zim-desktop-wiki#894]
Package: zim 0.71.1-t201905231912~ubuntu19.04.1 [origin: LP-PPA-jaap.karssenberg-zim]
PackageArchitecture: all
ProcCpuinfoMinimal:
 processor	: 3
 vendor_id	: GenuineIntel
 cpu family	: 6
 model		: 30
 model name	: Intel(R) Core(TM) i5 CPU         760  @ 2.80GHz
 stepping	: 5
 microcode	: 0xa
 cpu MHz		: 3113.458
 cache size	: 8192 KB
 physical id	: 0
 siblings	: 4
 core id		: 3
 cpu cores	: 4
 apicid		: 6
 initial apicid	: 6
 fpu		: yes
 fpu_exception	: yes
 cpuid level	: 11
 wp		: yes
 flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 popcnt lahf_lm pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid dtherm ida flush_l1d
 bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds
 bogomips	: 5619.74
 clflush size	: 64
 cache_alignment	: 64
 address sizes	: 36 bits physical, 48 bits virtual
 power management:
ProcVersionSignature: Ubuntu 5.0.0-20.21-generic 5.0.8
Python3Details: /usr/bin/python3.7, Python 3.7.3, python3-minimal, 3.7.3-1
PythonDetails: /usr/bin/python2.7, Python 2.7.16, python-minimal, 2.7.16-1
SourcePackage: zim
Tags: third-party-packages disco
Title: zim crashed with AssertionError in get_textstyle(): BUG: can not have multiple text styles
Uname: Linux 5.0.0-20-generic x86_64
UnreportableReason: Этот пакет не является официальным пакетом Ubuntu. Пожалуйста, удалите все сторонние пакеты и попробуйте снова.
UpgradeStatus: Upgraded to disco on 2019-04-18 (87 days ago)
_MarkForUpload: True

**Comment by Ygster** [comment]
Can you give us more information ?

- Describe the actions taken to reproduce the problem.
- Run zim in console with `zim --debug` and indicate the result in the console after the crash
