### ISSUE TITLE
How change backgroung of Tag mark without GTK-Warning ?

### ISSUE THREAD

**Issue by Nick222** [zim-desktop-wiki/zim-desktop-wiki#895]
In style.conf I write:

```
[Tag mark]
background=NONE
```
Zim 0.71.1 :
> Gtk-WARNING **: Don't know color 'NONE'

And word with underline have background as other text in normal mode or text-for-edit mode.

If I write in style.conf :

`background=WHITE`

Gtk-WARNING disappeared, but I see word with underline on **white** background in **all** modes.

When I try in style.conf :

`background=RGBA(0,0,0,0)`

I see:

> Gtk-WARNING **: Don't know color 'RGBA(0,0,0,0)'

How can I make background of underline words same as background of all text  - both in normal and text-for-edit modes without any Gtk-WARNING ?

**Comment by Ygster** [comment]
> When I try in style.conf :
> 
> `background=RGBA(0,0,0,0)`
> 
> I see:
> 
> > Gtk-WARNING **: Don't know color 'RGBA(0,0,0,0)'

I do some tests with this webpages as reference :
* https://developer.gnome.org/gtk3/stable/chap-css-overview.html
* https://www.w3.org/TR/css-color-3/#svg-color

I reproduce the same Warning message as you with 

`background=RGBA(0,0,0,0)`

but not with 

`background=rgba(0,0,0,0)`

**Comment by Nick222** [comment]
Thank You!!! :)
