### ISSUE TITLE
page results in tag pane cut off

### ISSUE THREAD

**Issue by ghost** [zim-desktop-wiki/zim-desktop-wiki#898]
when i select a tag in the top frame of the tag pane, in the tree view in the bottom frame, all results are given only as the first five to seven letters of the top level of the tree name followed by "...", even though there is lots of space in the pane for the tree to be displayed.

and if i follow a tree hierarchy down, by the third level there is room for nothing except "..."

if i make the pane really really wide, the results do expand, but there is always a very large blank area that they do not fill up. the tags list in the top frame of the pane do fill out the whole pane as i expand it.

running zim 0.68 on debian 10/xfce.

**Comment by introt** [comment]
Can't reproduce with 0.74 - please open a new issue if the problem persists
