### ISSUE TITLE
backlinks accross different notebooks

### ISSUE THREAD

**Issue by ghost** [zim-desktop-wiki/zim-desktop-wiki#899]
im using zim 0.68 on debian 10 / xfce.

my use case is having a separate bibliography notebook which i then link to when my notes refer to a given text. but when i do this the bibliographic entry linked to shows zero backlinks. it wd be good to be able to see every instance that a given text has been cited, and having a bibliography inside a notebook in order to have backlinks defeats the purpose: the bibliography is (potentially) for many/all notebooks...

**Comment by introt** [comment]
Candidate for moving to discussions

**Comment by jaap-karssenberg** [comment]
Sorry, but this is a "won't fix" for now - backlinks only work within a single notebook
