### ISSUE TITLE
Copying an equation makes it non-editable separately

### ISSUE THREAD

**Issue by cemeroncel** [zim-desktop-wiki/zim-desktop-wiki#901]
**Version:** 0.68
**Operating System:** Ubuntu 19.04

If I create an equation via the Equation Editor and make a copy on the same notebook, I cannot edit the copied equation separately. Instead, every change I made to the copied equation appears on the original too.

**Comment by introt** [comment]
Current development versions will copy both the png as well as the tex source --> [fix available]
