### ISSUE TITLE
Setting window default size too large?

### ISSUE THREAD

**Issue by sdicke** [zim-desktop-wiki/zim-desktop-wiki#902]
My system:
Distribution:          Antergos (respectively Arch Linux)
zim:                      0.71.1
window system:    X
window manager: kwin
localisation:          German
python:                 3.7.3-2
gtik3:                    3.24.10
Linux:                   5.2.2 x86_64

On my system the settings window default size (especially its width) is a bit large for its content.

![settingswindow](https://user-images.githubusercontent.com/23293203/61914311-68a62f00-af40-11e9-80fa-0687b3882cc6.png)

**Comment by jaap-karssenberg** [comment]
The size is remembered, so resizing it back should be fine.
