### ISSUE TITLE
unable to enter euro character on macOS

### ISSUE THREAD

**Issue by kjyv** [zim-desktop-wiki/zim-desktop-wiki#904]
My keyboard layout is german so it has the euro character on alt-e (like e.g. also italian).
Alt-e in zim however opens the Edit menu. 

It's a bit tricky for me to find out if zim or a dependency is to blame. A few things I've noticed:
- gtk3-demo does not include any menus at all that are within the application window, it uses global menus via GtkApplication/GMenu - these are proper Quartz menus without the issue. The currently used classes Gtk.UIManager, Gtk.Action, and Gtk.ActionGroup to create the main menu are apparently outdated since gtk 3.10. That way also main menu plugins would not be necessary anymore (also fixing #874).
- As per https://superuser.com/questions/303525/what-is-the-shortcut-to-access-the-menubar-in-mac-os-x, it seems not to be common that you can open the menus by underscore letter on macOS. If that functionality comes from zim directly (and if the current menus should stay), it should be disabled on macOS to allow shortcuts with alt-<letter>

**Comment by dehesselle** [comment]
The euro character works as expected in our new Zim.app. Check the website to upgrade.

**Comment by kjyv** [comment]
This was already fixed by merging my pull request but thanks for closing the ticket anyway ;)
