### ISSUE TITLE
Ordered List Tag (<ol>) Wrapped in Paragraph Tag (<p>)

### ISSUE THREAD

**Issue by billdotnet** [zim-desktop-wiki/zim-desktop-wiki#908]
OS: Ubuntu 14.04
Zim: Version 0.69.1

When wiki syntax is parsed, it appears that ordered list tags (ol) are always wrapped in paragraph tags (p), which slightly distorts the markup. When I check the source in the browser, the end tag of the paragraph tag is highlighted as a violation. This appears to be a bug that could be easily fixed by removing the paragraph tag wrapping from around the ordered list tag.

I await and appreciate your feedback.

Tek regards,

-/>bill

P.S. The same would probably have to be done for the unordered list tag (ul).

**Comment by introt** [comment]
Can confirm on 0.74, paging Jaap

**Comment by jaap-karssenberg** [comment]
Yes, I recognize this, will fix as part of the "maintenance" action to
refactor etree out in favor of the token iter approach. The token iter
already moves links outside the paragraphs. Might be nice test case to do
html export based on token iter instead of current etree based dumper.
