### ISSUE TITLE
Relative link to home directory doesn't work

### ISSUE THREAD

**Issue by malnvenshorn** [zim-desktop-wiki/zim-desktop-wiki#912]
According to the manual it should work, but using a link like `~/foo/bar` results in `No such file or folder: /foo/bar`. Using the absolute path `/home/user/foo/bar` works as expected.

Also interesting: The option `open` and `open with` is grayed out in the context menu of those links.

```
zim --version
zim 0.71.1
```

**Comment by jaap-karssenberg** [comment]
Just tested it here, but seems to work correctly. Is the HOME environment
parameter set correctly?

-- Jaap

**Comment by malnvenshorn** [comment]
Yes $HOME is set correctly. 

Even more strange some links with `~` work :thinking:

**Comment by jaap-karssenberg** [comment]
In that case maybe have a look at the page source - maybe the link
formatting is broken somehow ?

**Comment by malnvenshorn** [comment]
Yes indeed.

```
~[[file:///Skripte/linux-config-and-scripts/pacman/10-keep-current-kernel-modules-on-upgrade-pre.hook|/Skripte/linux-config-and-scripts/pacman/10-keep-current-kernel-modules-on-upgrade-pre.hook]]
[[~/Skripte/linux-config-and-scripts/pacman/10-keep-current-kernel-modules-on-upgrade-post.hook]]
```

The second link works while the first doesn't. But this has to be a bug in  zim, because all links are entered the same way (typing the path and hitting enter).

**Comment by jaap-karssenberg** [comment]
May be, but then we need a scenario how to reproduce it. Have not observed
same behavior myself.

Regards,

Jaap

**Comment by introt** [comment]
There have been a plethora of changes to link handling since this issue was opened, so please open a new one if the issue persists on 0.74. Thank you!
