### ISSUE TITLE
Option for tab order sorting on side panes

### ISSUE THREAD

**Issue by brianvanderburg2** [zim-desktop-wiki/zim-desktop-wiki#915]
Having recently switched to 0.72 from 0.69, I noticed the index pane is now a plugin.  It would be nice if for each pane we could control the order that any tabs are displayed in..  Or better if the GTK framework supports it, (something like wxAUI from wxWidgets) where the user can add custom panes so we could have an index on the left top, attachments on the left bottom, etc.

**Comment by introt** [comment]
Please see https://github.com/zim-desktop-wiki/zim-desktop-wiki/discussions/1808#discussioncomment-1807346; thanks!
