### ISSUE TITLE
Abillity to change type of list

### ISSUE THREAD

**Issue by Qwertie-** [zim-desktop-wiki/zim-desktop-wiki#922]
Semi frequently I start writing a bullet list and then later decide I want it to be a checkbox list. Presently there doesn't seem to be a way other than changing every item manually. It would be useful if you could select the whole list and then press Insert -> Checkbox List and have it convert all the bullets to checkboxes.

**Comment by fdt-dev** [comment]
I'm also just a user of this great software, but isn't that exactly how it works? Select the whole list and then select from the "Format" menu which kind of list it should be. Have you tried that?

**Comment by Qwertie-** [comment]
So it does. Thanks for the tip.
