### ISSUE TITLE
what's the exact steps to get to the trash can to recover files?

### ISSUE THREAD

**Issue by SolveAllProblemsRightNow** [zim-desktop-wiki/zim-desktop-wiki#924]

**Comment by jaap-karssenberg** [comment]
Depends on your operating system

**Comment by SolveAllProblemsRightNow** [comment]
where's the link/page that shows the steps for the main ones?

**Comment by jaap-karssenberg** [comment]
GO to the generic Thrash can on you system - usually a default icon on the
desktop or in the file browser. Zim does not have it's own trashcan.

**Comment by SolveAllProblemsRightNow** [comment]
how do we know which one is a 'zim' file? what file does zim use?

**Comment by introt** [comment]
Zim uses `.txt` files by default; the file and folder names are those of your page names. Please open a discussion if you need further help. Thank you!
