### ISSUE TITLE
0.71.1 clicks & keyboard does not move to items

### ISSUE THREAD

**Issue by galenthurber** [zim-desktop-wiki/zim-desktop-wiki#927]
0.711.1 after sometime of being idle the GUI seems to be active and in edit mode but clicking or keyboarding does nothing

MX18.3 [Debian 8]

**Comment by galenthurber** [comment]
I've tested this on 0.65 & 0.68
they have this navigation fail as well

Debian 8, MX 18.3

zim is an essential part of my investigations, I need this to work

**Comment by galenthurber** [comment]
log from zim 0.69 attached 
[zim-fail-edit-debug.gz](https://github.com/zim-desktop-wiki/zim-desktop-wiki/files/3664163/zim-fail-edit-debug.gz)

**Comment by galenthurber** [comment]
still an issue on 0.72.1

**Comment by jaap-karssenberg** [comment]
Maybe you can explain in more detail what you are doing, what you expect to
happen, and what is happening. From the report above I honestly have no
idea what you are talking about when you say "move items".

-- Jaap

**Comment by galenthurber** [comment]
I'll have or create a page, create a sub page,
attempt to move that sub page to another page, nothing happens.
after some time zim will become unresponsive

**Comment by jaap-karssenberg** [comment]
This report still sounds like a telegram message to me. Please understand
that I do not see the screen you are seeing. If you want some action on my
side to solve your problem you will at least need to take the time to spell
it out. For example, how are you moving those items, did you try the menu
item, did you look at the error log? And please include what operating
system you are using.


Op vr 8 mei 2020 15:16 schreef Galen Thurber <notifications@github.com>:
