### ISSUE TITLE
Attaching files does not create link in current page anymore

### ISSUE THREAD

**Issue by Korodny** [zim-desktop-wiki/zim-desktop-wiki#931]
With 0.72.0, Tools->Attach File is broken: the selected file will be copied to the notebook folder, but no link will be inserted in the current page. I don't get an error message or any other feedback, even when I start Zim from the Terminal.

**Comment by eAndrius** [comment]
Can confirm. Fresh Ubuntu 19.10 installation, zim 0.72.0 and 0.72.1 affected, same exact issue. No info even with debug flag (-D).

**Comment by oliver-joos** [comment]
I see this bug too in Linux Mint 19.3 MATE (based on Ubuntu 18.04 LTS).

**Comment by eAndrius** [comment]
Problem still persists with Ubuntu 20.04 LTS.

**Comment by eAndrius** [comment]
https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/744 refers to the same problem, and can confirm that compiling from dev branch sources solves it.

**Comment by introt** [comment]
Should be fixed by now, please open a new issue if the problem persists after updating to 0.74. Thank you!
