### ISSUE TITLE
Gtk source view how to addd gnuplot

### ISSUE THREAD

**Issue by ethren** [zim-desktop-wiki/zim-desktop-wiki#938]
Hello,
I am using zim 0.72 on ubuntu and zim 0.68 on windows 10.
In the notebook I want to add a code block using the gtk source view plugin, I cannot see gnuplot in the list of languages!
How can I add it?

**Comment by jaap-karssenberg** [comment]
Sorry but that is outside of Zim, we reuse the gtksourceview library. So
adding language should happen in that library, not in Zim.

Regards,

Jaap

Op wo 25 sep. 2019 21:51 schreef ethren <notifications@github.com>:

**Comment by ethren** [comment]
Fortunately I found the `gnuplot.lang` file [here](https://wiki.gnome.org/Projects/GtkSourceView/LanguageDefinitions?action=AttachFile&do=view&target=gnuplot.lang)

I downloaded it and added it to:
`"C:\Program Files (x86)\Zim Desktop Wiki\share\gtksourceview-2.0\language-specs"`
Now gnuplot syntax highlighting is available.
