### ISSUE TITLE
toc as floating wiget transparent and unreadable

### ISSUE THREAD

**Issue by ghost** [zim-desktop-wiki/zim-desktop-wiki#941]
upon updating to 0.72, the toc is transparent, resulting in a mush of its text and the note underneath it:

![image](https://user-images.githubusercontent.com/48327705/65903583-34ba1080-e3ac-11e9-83a2-b028c2bfbe75.png)

running zim on debian buster/xfce.

**Comment by mouseb** [comment]
huh turns outs this is desktop theme dependent :(
