### ISSUE TITLE
end-of-life for pygtksourceview

### ISSUE THREAD

**Issue by KaiMartin** [zim-desktop-wiki/zim-desktop-wiki#943]
Apparently, python2 is considered obsolete to the point that Debian removed the corresponding packages from repositories. This affects the plugin source_view because it depends on python bindings for gtksourceview.
Starting from buster (the current stable release) the package python-gtksourcereview2 is not available any more. Consequently, the plugin fails to activate. 

Debian maintenance page: https://tracker.debian.org/pkg/pygtksourceview
Bug #878698: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=878698
Bug #937453: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=937453

I hope, zim can regain some kind of syntax highlighting, as this makes code snippets much more readable.

---<)kaimartin(>---

**Comment by Self-Perfection** [comment]
First of all make sure, that you use recent enough version of zim. Since transition to python 3 in zim 0.70 your concern seems to be irrelevant. Sourceview plugin in zim 0.72 in Arch shows source snippets perfectly well via gtksourceview3, without any pygtksourceview wrappers.

**Comment by dehesselle** [comment]
Correct, this has been superseded by the transition to Python 3.
