### ISSUE TITLE
Cannot open my notes after moving from Windows 7 to 2010

### ISSUE THREAD

**Issue by lalebarde** [zim-desktop-wiki/zim-desktop-wiki#944]
Hi,
I have several book notes under Zim, built while I was under Windows 7 with Zim version 0.67.
I have copied all my folder into my new Windows 2010 setup. When I try to open my booknotes, my.zim appears grey and I cannot openned it.

I have tryed with zim portable editions 0.67 and 0.69, and under WSL/Debian Buster 0.68. The behaviour is the same.

Any idea please ?

Cheers,

Laurent

**Comment by jaap-karssenberg** [comment]
Please run zim with the "--debug" commandline switch and check for error
messages.

-- Jaap

**Comment by lalebarde** [comment]
False alert, even if the .zim file appears in grey, the note book opens.
