### ISSUE TITLE
Scroll bar overlaps code blocks with long one-liners

### ISSUE THREAD

**Issue by murrrf** [zim-desktop-wiki/zim-desktop-wiki#951]
If I write a long single-line command to a code block, the scroll bar overlaps the code block, making it completely unreadable.

The red frame is a code block with a long single-line command. The blue frame is verbatim text with copy of previous command.

zim 0.72.0
Linux Mint 19.1
MATE 1.20.1
Default system language - russian.

![scrn](https://user-images.githubusercontent.com/4840415/66642790-119e2500-ec26-11e9-9a3d-823c98ed5425.png)

**Comment by introt** [comment]
Can't reproduce on 0.74 - scroll bars are not shown unless moused over, and even then they don't overlap with the text unless activated. Please open a new ticket if you're still having this issue on the latest version. Thanks!
