### ISSUE TITLE
Is there a way to set the line width in the editor?

### ISSUE THREAD

**Issue by Vetii** [zim-desktop-wiki/zim-desktop-wiki#954]
Hi!

First, thank you for creating zim. It's a very useful tool!

My issue is that by default, zim does not break the line. This is a problem when zim is in fullscreen, because if I don't break lines myself, they become really long and it is hard to read. If you look at most blogs and websites today, the text is contained in a central column that is maybe 2-3 alphabets wide. The reader mode from Firefox does the same.

I have looked at the [config files webpage](https://zim-wiki.org/manual/Help/Config_Files.html), but it seemed like it was not possible to have the text wrap after a certain number of letters, or have the text stick to a certain width. Maybe I should try the css styling of gtk3?

Is there a way to have the text wrap to be under a certain width, even if the editor is wider? Also, is there a way to have the text in the center, as opposed to having it sticking to the left side of the editor?

**Comment by introt** [comment]
Please see the Distraction Free Editing plugin built for this use case. If that doesn't fit your need, feel free to suggest another approach by opening a new Discussion. Thank you!
