### ISSUE TITLE
Natural language auto-detection: Setting a `lang` tag for an entire document

### ISSUE THREAD

**Issue by anasram** [zim-desktop-wiki/zim-desktop-wiki#961]
Zim version: Zim 0.68-rc1

_This proposal is based on a [comment](https://github.com/jgm/pandoc/issues/2847#issuecomment-539412549) I posted in a Pandoc issue_.

## The Problem

Zim doesn't set a `lang` tag to user's documents, like this for example:

```markdown
---
lang: fr
---

# Heading…
```

This means:

1. User needs to tel Zim manually the language being used in the current document for spell-checking.
2. For RTL strings, Zim uses `dir` attribute.

## A Solution

Simply, Zim should follow user's keyboard layouts, just like the way a typical word-processor does. CSS will take care of the rest:

```css
:lang(en) {direction: ltr;}
:lang(ar) {direction: rtl;}
```

However, what about the legacy user's notebooks, which were so far lacking `lang` attributes?

In most cases, an individual user understands and deals with only 1-3 languages.

Suppose we are talking about a Spanish user, a user who understands and deal with only English and Spanish, and wants to set a *language metadata tag* to a set of documents he/she has.

The process could be like this:

1. Zim will check the user's keyboard-layout. In this example, the result will be probably `es` and `en`.
2. Zim will scan these documents by spell-checking each according to available English and Spanish dictionaries.
	* If the **most** words in a specific document belongs to the English dictionary, Zim will set:
		```
		lang: en
		```
	* If the **most** words in this document belongs to the Spanish dictionary, Zim will set:
		```
		lang: es
		```
Finally, two notes:

* For a better performance, I think checking only document's title and headings might be enough.
* Also, code strings and blocks (in `code` and `pre` elements)  should be out of this scanning process.

**Comment by sojusnik** [comment]
Would love to see that! In my case checking only headings won't be enough, the content should also be considered (without code).

**Comment by jaap-karssenberg** [comment]
This is a "won't fix" for me. Open to plugins or pull requests for this if they are practical and straight forward.
