### ISSUE TITLE
Option to reload the page when a custom tool is run

### ISSUE THREAD

**Issue by cheap-glitch** [zim-desktop-wiki/zim-desktop-wiki#969]
It used to be that when a custom tool was used and it modified the content of the current page in some way, the page would reload itself and display the updated content.

Now it needs to be done manually with Ctrl+R, and if this action is not done, running a custom tool twice in a row will almost certainly result in a conflict.

Would it be possible to have an option — e.g. a checkbox in the custom tool configuration window — to automatically reload the current page when the tool is run?

**Comment by Self-Perfection** [comment]
Such checkbox already exists, check https://zim-wiki.org/manual/Help/Custom_Tools.html

>Then there is the checkbox **Command does not modify data**. Enable this option if your tool only read data but does not modify it. In that case zim will execute the application in the background and keep running. **Otherwise, if your tool does modify data, zim has to wait for it to finish and reload the current page.**

**Comment by cheap-glitch** [comment]
Maybe I wasn't very clear, but I'm talking about tools that *do* modify data (e.g. a small script to remove all completed tasks). So this option has no use in this case.

**Comment by Self-Perfection** [comment]
You want zim to wait until your custom tool finishes and reload the current page afterwards, don't you?

That is exactly what zim should do if "Command does not modify data" checkbox is not set.

**Comment by cheap-glitch** [comment]
> That is exactly what zim should do if "Command does not modify data" checkbox is not set.

Which is why I didn't set it, and yet Zim does not reload the page. I assumed it was intended, but I guess it's a bug then.

**Comment by Self-Perfection** [comment]
I tested this on zim 0.72 under GNU/Linux. And it works, but a little bit confusing. You have to use `%f` to access note location, not `%s`
> %f	for page source as a temporary file
> %s	for the real page source file (if any)

I suppose direct modification of note file should also be noticed by zim or manual should have hint, that one should not use `%s` to modify note content. @jaap-karssenberg What is your opinion?

**Comment by cheap-glitch** [comment]
Thank you, that fixed it. But there was definitely a change in behavior at some point, because `%s` used to cause the page to be reloaded too.
