### ISSUE TITLE
ansi escape sequences

### ISSUE THREAD

**Issue by zogommog** [zim-desktop-wiki/zim-desktop-wiki#970]
This isn't an issue per se, but more of a feature request. I do a fair amount of copy/paste from CLI terminals into Zim to create various references. It works, but it does not preserve the colors (for example Linux terminal defaults) which would be nice to save. I'm pretty sure the codes are being picked up by the copy operation because LibreOffice Writer will save them. The only work-around I've found so far is to export the terminal to HTML and then bring it over to Zim, but it seems a bit excessive instead of just saving those ANSI color codes.

Thanks for consideration!

**Comment by introt** [comment]
Ever so slightly related: Import HTML on copy-paste #149

**Comment by jaap-karssenberg** [comment]
Afraid this use case is a "won't fix" for me. Open for a PR if it is straight forward to patch.
