### ISSUE TITLE
Import folder with files

### ISSUE THREAD

**Issue by prog20901** [zim-desktop-wiki/zim-desktop-wiki#971]
How to import a folder with files. Currently am able to import only one single text file

**Comment by jn64** [comment]
You can just move the folder in your file manager into your Zim notebook's folder. But make sure filenames have no spaces, and close Zim first.

See [Moving pages into an existing notebook](https://zim-wiki.org/manual/Help/Importing_external_files.html).

I have done it to merge 2 Zim notebooks without problems.

**Comment by prog20901** [comment]
i tried the above, about 1,500 files pasted in folder inside Zim\notebooks folder..However only file names got imported...Actual content is not imported..This happens in the latest zim. Check if possible

**Comment by jn64** [comment]
I suggest you try with smaller batch of files. (I'm not a developer here, just trying to help)

**Comment by prog20901** [comment]
Not working.. Any way...No response..

**Comment by treborxy** [comment]
Hi prog20901,
not sure if I got your point - but if you want to have (almost) whatever files within a certain zim-folder, use the attachment-plugin to make them accessable, and copy or move the files with your filemanager into the folder in question. Maybe you have to update the view by clicking the circled arrow. This does nor work with files of the same extension like your zim-wiki files.
Regards
