### ISSUE TITLE
Documentation: on syncing via cloud, block-level vs whole file

### ISSUE THREAD

**Issue by barbafa** [zim-desktop-wiki/zim-desktop-wiki#985]
Suggestion on adding info in the documentation that cloud sync of a Zim Notebook might possibly work better if the syncing is done by block-level sync aka differential or delta sync than with whole file sync. 

First, sorry if I submit this the wrong way, but after searching I found no other way to make a suggestion towards the documentation.

When I had my Zim Notebook in my google drive, I often had issues where Zim couldn't save a note. It always resolved after waiting for a while though. This effect seems to be more pronounced on slow connection, f.e. on 4g throttled to <1mbps. 
I suspected it might be something wrong with the syncing, so for a test I moved my Zim Notebook to Dropbox, and this problem totally vanished. 
When googling on dropbox vs google drive I found out that Dropbox has block-level sync while Google Drive has whole-file-level sync. [https://www.cloudwards.net/block-level-file-copying/
]
If my assumption that Google Drives whole-file-level sync was the 'problem' and Dropbox block-level the solution, then I think it might be good to add some info on this difference in the documentation, since it might not be the first thing one might think of. 

Of course, there might be other explanations to my problem and why my solution worked.

**Comment by jaap-karssenberg** [comment]
Thanks for the suggestion, but I'm afraid that the description is not convincing enough to include this in the zim manual for now. Please discuss on the "discussions" forum to compare notes.
