### ISSUE TITLE
text loses formating when pasted into zim

### ISSUE THREAD

**Issue by kareliot** [zim-desktop-wiki/zim-desktop-wiki#988]
when I copy a formatted text from zotero notes to zim all the formating (italics as well as embedded links) gets lost. 
When I copy the same text from zotero to libre office, all the formatting is being preserved, so the problem seems to be on the zim side.
The formating is also lost when I copy formatted text from libre office or any other source and paste it into zim.

This is on linux with gnome (if this helps).

**Comment by introt** [comment]
Related: Import HTML on copy-paste #149

**Comment by jaap-karssenberg** [comment]
Consider this a double of #149
