### ISSUE TITLE
native macOS application bundle

### ISSUE THREAD

**Issue by dehesselle** [zim-desktop-wiki/zim-desktop-wiki#990]
Hello,

I am working on packaging Zim as native macOS application bundle. The goal is to produce

- a completely self-contained and relocatable app,
- supporting OS X Yosemite 10.10 to macOS Catalina 10.15
- without external dependencies (Homebrew, Python, ...),
- without the need for 3rd party launchers or wrappers and to
- distribute it as notarized disk image.

If this is of interest to you, I can offer to contribute macOS releases for the Zim project instead of doing this in a fork on the side. Let me know what you think.

**Comment by jaap-karssenberg** [comment]
Hello René,

I think this will be very welcome for many users. Let's figure out what is
needed to make such bundle part of our standard release procedure.

Regards,

Jaap



Op wo 25 dec. 2019 17:48 schreef René de Hesselle <notifications@github.com

**Comment by dehesselle** [comment]
Hello Jaap,
this is what I know so far:

- The initial prototype is ~65 MiB in size (`.dmg` file).
  - It's not finished, there are still things I need to do and fix.
  - I need a place where I can upload it to.
    - If that's a problem, we could even start with a dropbox link.

- The packaging process will likely introduce issues of its own. This is due to the fact that there is no manual of how to do everything right from start (and me working in iterations) and that I haven't been using Zim in a long time (I am by no means a proficient user, I won't notice them all on my own).
   - We need testers for that.
   - In the beginning, there'll be more frequent updates to the application bundle (unrelated to Zim code) to iron those out.

Is there something I should read about the "standard release procedure" or is this something you are going to tell me about?

**Comment by jaap-karssenberg** [comment]
If you share the package with me I could put it on the website. However for
testing it might be easier and faster to use a location you control - like
a Dropbox link - and announce it on the mailing list for testing by other
Mac users.

The release procedure consists of a few scripts that wrap a new release
with proper info and also compile the Debian/Ubuntu package that goes to
the website.

If you are able to make the package build in a script that can be run
automatically, we can run that on each release and make sure there is
always an up to date package

Regards,

Jaap

Op do 26 dec. 2019 18:40 schreef René de Hesselle <notifications@github.com

**Comment by dehesselle** [comment]
Ok, thanks for the info.

I propose we start with a Dropbox folder and as soon as things have stabilized move over to putting it on the website.

Currently I'm building on a dedicated machine with special configuration in regards to the build environment and my credentials for proper signing/notarization with Apple. I consider further automation and deployability of this setup to "whatever can build macOS apps" (e.g. using GitHub's macOS CI infrastructure) as a (rather far-off) long-term goal as it requires a lot of additional work on my end.

I will report back here once I have the first release available for brave testers.

**Comment by dehesselle** [comment]
This is my Dropbox folder.
https://www.dropbox.com/sh/576fqhsho4qz0ry/AABfXtjRFfXysMLzhK_4FCHAa?dl=0

**Comment by fladd** [comment]
The app does not seem to start (MacBook Pro, MacOS 10.14.5).

**Comment by dehesselle** [comment]
Thank you for testing @fladd - I need you to elaborate as I cannot reproduce your issue.

- Do you get an error message?
- Does Zim appear in the dock?
- Does Zim jump in the dock and then stops?
- Can you try to run `open /Applications/Zim.app` from the Terminal?
- Can you try to run `/Applications/Zim.app/Contents/MacOS/Zim` from Terminal?

**Comment by Self-Perfection** [comment]
I have the same issue. MacBook Pro, macOS 10.15.3

```
$ open /Applications/Zim.app
LSOpenURLsWithRole() failed with error -10810 for the file /Applications/Zim.app.
$ /Applications/Zim.app/Contents/MacOS/Zim
ERROR: Could not set locale settings
Traceback (most recent call last):
  File "/Applications/Zim.app/Contents/Resources/lib/python3.6/site-packages/zim/__init__.py", line 135, in <module>
    locale.setlocale(locale.LC_ALL, '')
  File "/Applications/Zim.app/Contents/Resources/lib/python3.6/locale.py", line 598, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
Traceback (most recent call last):
  File "", line 39, in <module>
  File "/Applications/Zim.app/Contents/Resources/lib/python3.6/site-packages/zim/__init__.py", line 154, in <module>
    _lang, _enc = locale.getlocale()
  File "/Applications/Zim.app/Contents/Resources/lib/python3.6/locale.py", line 581, in getlocale
    return _parse_localename(localename)
  File "/Applications/Zim.app/Contents/Resources/lib/python3.6/locale.py", line 490, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8
```

**Comment by dehesselle** [comment]
Thank you for the log, that's something I can investigate.

**Comment by andrewjbarton** [comment]
Hello René,

I was looking for the best way to install Zim on my Mac when I found your project. Thank you very much for doing this.

I was able to bring Zim up, but the first issue I have found is that the 'Browse' button results in 'Trace/BPT trap: 5'

Terminal Log
--
(base) Bad-Wolf:Applications andrewb$ /Applications/Zim.app/Contents/MacOS/Zim
WARNING: Could not find all icon sizes for the application icon
Trace/BPT trap: 5
(base) Bad-Wolf:Applications andrewb$ /Applications/Zim.app/Contents/MacOS/Zim
WARNING: Could not find all icon sizes for the application icon
Trace/BPT trap: 5
--
This happens when I use the Browse button to try and select a new location for a Notebook and when I use Browse within the link tool. 

I am running on macOS 10.14.6 on 2018 MacBook Pro.

Regards,
Andy

**Comment by marksfox52** [comment]
Hi, Really happy that you are working on this.  I am on a macbook runing 10.15.4. I get the following error when starting Zim.
- Mark

** (process:4149): WARNING **: 10:14:16.318: Failed to load shared library 'libglib-2.0.0.dylib' referenced by the typelib: dlopen(libglib-2.0.0.dylib, 9): no suitable image found.  Did find:
	file system relative paths not allowed in hardened programs
Traceback (most recent call last):
  File "", line 40, in <module>
  File "/Applications/Zim.app/Contents/Resources/lib/python3.6/site-packages/zim/main/__init__.py", line 22, in <module>
    import zim.fs
  File "/Applications/Zim.app/Contents/Resources/lib/python3.6/site-packages/zim/fs.py", line 27, in <module>
    from zim.signals import SignalEmitter, SIGNAL_AFTER
  File "/Applications/Zim.app/Contents/Resources/lib/python3.6/site-packages/zim/signals.py", line 7, in <module>
    from gi.repository import GObject
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/Applications/Zim.app/Contents/Resources/lib/python3.6/site-packages/gi/importer.py", line 145, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/Applications/Zim.app/Contents/Resources/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/Applications/Zim.app/Contents/Resources/lib/python3.6/site-packages/gi/importer.py", line 146, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/Applications/Zim.app/Contents/Resources/lib/python3.6/site-packages/gi/overrides/__init__.py", line 118, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/Applications/Zim.app/Contents/Resources/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Applications/Zim.app/Contents/Resources/lib/python3.6/site-packages/gi/overrides/GLib.py", line 37, in <module>
    from gi import _option as option
  File "/Applications/Zim.app/Contents/Resources/lib/python3.6/site-packages/gi/_option.py", line 41, in <module>
    OPTION_CONTEXT_ERROR_QUARK = GLib.quark_to_string(GLib.option_error_quark())
gi._error.GError: g-invoke-error-quark: Could not locate g_option_error_quark: dlopen(libglib-2.0.0.dylib, 9): no suitable image found.  Did find:
	file system relative paths not allowed in hardened programs (1)

**Comment by dehesselle** [comment]
Progress is slow -  I know - but I'm still working on this. 

It's been a while so the next thing I'll do is creating a new build with updated libraries and then work my way through the reported issues.

**Comment by gagarine** [comment]
Try to run it on macOS Big Sur without success 

```
$ /Applications/Zim.app/Contents/MacOS/Zim ; exit;

** (process:35997): WARNING **: 16:08:18.233: Failed to load shared library 'libgobject-2.0.0.dylib' referenced by the typelib: dlopen(libgobject-2.0.0.dylib, 9): no suitable image found.  Did find:
	file system relative paths not allowed in hardened programs

** (process:35997): WARNING **: 16:08:18.233: Failed to load shared library 'libglib-2.0.0.dylib' referenced by the typelib: dlopen(libglib-2.0.0.dylib, 9): no suitable image found.  Did find:
	file system relative paths not allowed in hardened programs
Traceback (most recent call last):
  File "", line 40, in <module>
  File "/Applications/Zim.app/Contents/Resources/lib/python3.6/site-packages/zim/main/__init__.py", line 22, in <module>
    import zim.fs
  File "/Applications/Zim.app/Contents/Resources/lib/python3.6/site-packages/zim/fs.py", line 27, in <module>
    from zim.signals import SignalEmitter, SIGNAL_AFTER
  File "/Applications/Zim.app/Contents/Resources/lib/python3.6/site-packages/zim/signals.py", line 7, in <module>
    from gi.repository import GObject
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/Applications/Zim.app/Contents/Resources/lib/python3.6/site-packages/gi/importer.py", line 145, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/Applications/Zim.app/Contents/Resources/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/Applications/Zim.app/Contents/Resources/lib/python3.6/site-packages/gi/importer.py", line 146, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/Applications/Zim.app/Contents/Resources/lib/python3.6/site-packages/gi/overrides/__init__.py", line 118, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/Applications/Zim.app/Contents/Resources/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Applications/Zim.app/Contents/Resources/lib/python3.6/site-packages/gi/overrides/GLib.py", line 37, in <module>
    from gi import _option as option
  File "/Applications/Zim.app/Contents/Resources/lib/python3.6/site-packages/gi/_option.py", line 41, in <module>
    OPTION_CONTEXT_ERROR_QUARK = GLib.quark_to_string(GLib.option_error_quark())
gi._error.GError: g-invoke-error-quark: Could not locate g_option_error_quark: dlopen(libglib-2.0.0.dylib, 9): no suitable image found.  Did find:
	file system relative paths not allowed in hardened programs (1)
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...      70 completed.

[Process completed]

```

**Comment by dehesselle** [comment]
I finally got around to resolve a blocking issue, so I'm picking up development again. There's still stuff on the todo list and chances are if it didn't work for you last time, this might still be the case (as "works on my machine" is not a reliable indicator 😉), nevertheless I created a new release to show there's progress. There will be more releases in the coming weeks as I'm ironing out issues, problems with locales being the most major one AFAIK.
The original Dropbox link is still valid, readme and changelog updated.

**Comment by gagarine** [comment]
@dehesselle thanks for this new release. I got this error at launch.

```
Process:               Zim [16753]
Path:                  /Applications/Zim.app/Contents/MacOS/Zim
Identifier:            org.zim-wiki.Zim
Version:               0.73.5 (0.73.5.r1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Zim [16753]
User ID:               501

Date/Time:             2021-03-23 14:08:15.825 +0100
OS Version:            macOS 11.2.3 (20D91)
Report Version:        12
Anonymous UUID:        976D9EFF-7071-229D-85BE-74E028524870

Sleep/Wake UUID:       6A836A28-EC49-48DC-BC8F-80B5D1155289

Time Awake Since Boot: 92000 seconds
Time Since Wake:       3900 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  dyld: Using shared cache: 52762DF1-0E55-3F8B-9588-8169E6D0EB95
Library not loaded: @executable_path/../Resources/lib/libpython3.8.dylib
  Referenced from: /Applications/Zim.app/Contents/MacOS/Zim
  Reason: no suitable image found.  Did find:
	/Applications/Zim.app/Contents/MacOS/../Resources/lib/libpython3.8.dylib: code signing blocked mmap() of '/Applications/Zim.app/Contents/MacOS/../Resources/lib/libpython3.8.dylib'
	/Applications/Zim.app/Contents/MacOS/../Resources/lib/libpython3.8.dylib: stat() failed with errno=1
	/Applications/Zim.app/Contents/MacOS/../Resources/lib/libpython3.8.dylib: code signing blocked mmap() of '/Applications/Zim.app/Contents/MacOS/../Resources/lib/libpython3.8.dylib'
	/Applications/Zim.app/Contents/MacOS/../Resources/lib/libpython3.8.dylib: stat() failed with errno=1
	file system relative paths not allowed in hardened programs

Binary Images:
       0x104ea4000 -        0x104eabfff +org.zim-wiki.Zim (0.73.5 - 0.73.5.r1) <EAB4C6B2-C9D0-34B7-AE83-D29D1356656C> /Applications/Zim.app/Contents/MacOS/Zim
       0x105085000 -        0x105120fff  dyld (832.7.3) <0D4EA85F-7E30-338B-9215-314A5A5539B6> /usr/lib/dyld

```

**Comment by dehesselle** [comment]
Oh boy, what a rookie mistake. One should not make releases late at night (I obviously forgot to test the notarized one before uploading it). Thank you for your patience.
There will be a new release later today to fix this and some other stuff as well. Stay tuned.

**Comment by dehesselle** [comment]
New release uploaded.

**Comment by gagarine** [comment]
I was able to launch Zim on MacOS using the last package! Nice!

It can create and save a notebook and the application seem stable.

**Some Problems:**

- Zim crash when I try to add an attachment (but I can add an image by drag&drop)
- The created time is written in German. Yet my computer interface is in English with region set in Switzerland.
![Screenshot 2021-03-24 at 16 42 41](https://user-images.githubusercontent.com/164074/112339457-f8752100-8cbf-11eb-8922-a5bcb59e1ddb.png)
- submenu do not have the small ">" to indicate their is a submenu
![Screenshot 2021-03-24 at 16 45 52](https://user-images.githubusercontent.com/164074/112340008-733e3c00-8cc0-11eb-9195-f6fdb9e34bdd.png)

Those are small and separated issue I believe. The goal of this issue is to have an automatic build of a macOS application bundle.

**Comment by dehesselle** [comment]
The next release is in the works but not finished yet. Answers I can give so far:
- Configuration files are in `~/Library/Application Support/org.zim-wiki.Zim`.
- Cache files are in `~/Library/Caches/org.zim-wiki.Zim`.
- Crash on adding attachment is a missing entitlement, will be fixed in next release.
- Missing decorations in menubar might be a plugin issue, there's more stuff missing:
  <img width="204" alt="zim_menu" src="https://user-images.githubusercontent.com/11375494/113223475-88e7ce80-9289-11eb-8a5f-b1105cc15491.png">

**Comment by jaap-karssenberg** [comment]
René,

Please send me a personal mail if you need fixes in the main branch to
continue. I'm quite behind on regular bug reports and merge requests
(lockdown with small kids....) But if you send a direct ping I'll do my
best.

Regards,

Jaap

Op do 1 apr. 2021 01:31 schreef René de Hesselle ***@***.***>:

**Comment by dehesselle** [comment]
New release uploaded (see changelog). I wanted to fix more, but I need more time 😉 

---

Thanks for the offer @jaap-karssenberg , I'll do that if I encounter blockers.

**Comment by dehesselle** [comment]
New release uploaded. Fixes https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/1427

**Comment by rsc4** [comment]
Thanks very much for working on this, René.

Latest version (0.73.5.r5) installs great on my M1 Mac Mini (Big Sur 11.2.3).

There is a weird bug in setting a custom font for the notes window. It only lets you add certain custom fonts, but not others (have confirmed the config file is indeed updating, but not all fonts actually work in the GUI). For example, I can't change the font to Andale Mono, Courier or monospace, but I can change it to Menlo. 

I couldn't  install Zim using homebrew or from source due to errors that are beyond my current ability to debug, so I'm not sure whether this minor UI bug is specific to this .app or if it would be the same on a build from source.

If this isn't the appropriate place to put this feedback, please lmk.

Thanks again for your work!

**Comment by dehesselle** [comment]
New release uploaded.

@rsc4 I cannot reproduce this issue. I have tested all the fonts you mentioned. I'm not on Apple Silicon though. Or maybe it just got resolved with the new release?

@gaelbb Crash should be fixed.

**Comment by lmassenet-regad** [comment]
0.73.5r6 works on MacBook Air M1 (11.2.2). Thanks @dehesselle!

**Comment by gagarine** [comment]
Very cool!

Small issue, on dark theme the text is not very readable, the interface is good. Not sure it's a macOS issue. 

(for whatever reason, the screenshot is better than reality, my links are purple. Perhaps night shift..)
![Screenshot 2021-05-13 at 22 48 25](https://user-images.githubusercontent.com/164074/118185884-5a8b1080-b43d-11eb-8984-299bdeede10d.png)


![Screenshot 2021-05-13 at 22 46 53](https://user-images.githubusercontent.com/164074/118185769-33ccda00-b43d-11eb-8e5d-4cd0f2548374.png)

**Comment by dehesselle** [comment]
If it turns out to not be your customized config style but that Adwaita dark is just not suitable, let me know.

**Comment by gaelbb** [comment]
@dehesselle the crash is fixed, it works fine on 10.15.7. Thanks !!
I have also tried on another mac with 11.3.1 without any problem.

**Comment by dehesselle** [comment]
New release uploaded.

I believe we're getting close to calling this "ready". I'm planning one more release to fix a locale issue (date format vs language, [see above](https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/990#issuecomment-805940777)) and do some internal cleanup, but I think that'll be it. The remaining issues are unrelated to my packaging AFAICT, but even if they turn out to be, the only way to know for sure and move forward is to broaden the audience and get more people to use/test and compare it to their unpackaged installations.

Apart from documentation and testing, a decision must be made if the current set of plugins that work out-of-the-box is ok as a baseline, meaning that it'll be up to the users and/or plugin authors to get them to work. Currently this concerns the following plugins that do not work out-of-the-box as I have not integrated their dependencies into the app:
- ditaa diagrams
- formulas (latex)
- gnuplot
- R diagrams
- musical notes (lilypond)
- sequence diagram (seqdiag)

There will be some support to help with that, i.e. a way to add something to `PATH` so Zim can pick up things from a Homebrew or MacPorts installation. But that also needs testing.

**Comment by tmcguire** [comment]
> New release uploaded.

I've just installed the new release and so far it's working great for me.
Thanks a lot for the work of creating an app bundle, much appreciated.

**Comment by tmcguire** [comment]
> That's an issue of the osx-menubar plugin and will be present in a self-compiled/unpackaged version of Zim as well. If someone else can confirm this, we should create a separate issue for that.

The only other version of Zim on macOS that I've tested is the bundle from https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/262#issue-282910129. In that version, the menubar works correctly even with multiple windows/notebooks. It's an old version from 2017 though.

**Comment by dehesselle** [comment]
> The only other version of Zim on macOS that I've tested is the bundle from 262 (comment).

That is only a wrapper that consists of a script launching whatever you have as `/usr/local/bin/zim` on your machine.

But if you are using that, that also means you have an unpackaged Zim installation. Can you give me more details about that? Zim version, package versions (`brew list --versions` or `port installed`), ...? While I'm still pretty certain it is unrelated to my packaging, library versions might make a difference.

**Comment by tmcguire** [comment]
> But if you are using that, that also means you have an unpackaged Zim installation. Can you give me more details about that? Zim version, package versions (`brew list --versions` or `port installed`), ...? While I'm still pretty certain it is unrelated to my packaging, library versions might make a difference.

Currently I'm running the ZIM from https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/262#issue-282910129, with `/usr/local/bin/zim` installed from `brew`. I reverted back to that since the menubar working with multiple windows was essential to me. One thing I manually changed in `/Applications/Zim.app/Contents/MacOS/Zim` is to add `--standalone` to the `exec` line, making it `exec /usr/local/bin/zim --standalone;`. I can't remember why I made the change.

Let me know if there is anything else you'd like to know, or anything I should try out.

```
12:00 $ /usr/local/bin/zim --version
WARNING: XDG_RUNTIME_DIR is not set, using /var/folders/mm/71dxkfm54dld4wgm7gf_xfn40000gn/T/zim-thomas as a fallback
WARNING: /usr/local/Cellar/zim/0.73.5/libexec/lib/python3.9/site-packages/zim/plugins/osx_menubar.py:28: PyGIWarning: GtkosxApplication was imported without specifying a version first. Use gi.require_version('GtkosxApplication', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import GtkosxApplication

zim 0.73.5
```

```
12:01 $ brew list --versions
adwaita-icon-theme 40.1.1
aom 3.1.1
atk 2.36.0
autogen 5.18.16_1
bash-completion 1.3_3
bat 0.18.1
bdw-gc 8.0.4_2
berkeley-db 18.1.40
binutils 2.36.1
bloaty 1.1_7
brotli 1.0.9
c-ares 1.17.1
cairo 1.16.0_5
capstone 4.0.2
cmake 3.20.4
coreutils 8.32
dav1d 0.9.0
dbus 1.12.20
dtrx 7.1
exa 0.10.1
fd 8.2.1
fdupes 2.1.2
ffmpeg 4.4_2
flac 1.3.3
fontconfig 2.13.1
freetype 2.10.4
frei0r 1.7.0
fribidi 1.0.10
fzf 0.27.2
gd 2.3.2
gdbm 1.19
gdk-pixbuf 2.42.6
gettext 0.21
giflib 5.2.1
git 2.32.0
git-delta 0.8.0
git-interactive-rebase-tool 2.1.0
git-lfs 2.13.3
glib 2.68.3
gmp 6.2.1
gnutls 3.6.16
gobject-introspection 1.68.0
graphite2 1.3.14
graphviz 2.47.3
gsettings-desktop-schemas 40.0
gtk+ 2.24.33
gtk+3 3.24.29
gtk-mac-integration 3.0.0
gtksourceview3 3.24.11_3
gts 0.7.6_2
guile 3.0.7
guile@2 2.2.7
harfbuzz 2.8.1
hicolor-icon-theme 0.17
htop 3.0.5
icu4c 69.1
jasper 2.0.32
jemalloc 5.2.1_1
jpeg 9d
jq 1.6
krb5 1.19.1
lame 3.100
leptonica 1.81.1
libao 1.2.2
libass 0.15.1
libbluray 1.3.0
libepoxy 1.5.8
libev 4.33
libevent 2.1.12
libffi 3.3_3
libidn2 2.3.1
libogg 1.3.5
libpng 1.6.37
libpthread-stubs 0.4
librsvg 2.50.7
libsamplerate 0.1.9_1
libsndfile 1.0.31
libsodium 1.0.18_1
libsoxr 0.1.3
libtasn1 4.17.0
libtiff 4.3.0
libtool 2.4.6_3
libunistring 0.9.10
libuv 1.41.0
libvidstab 1.1.0
libvorbis 1.3.7
libvpx 1.10.0
libx11 1.7.2
libxau 1.0.9
libxcb 1.14_1
libxdmcp 1.1.3
libxext 1.3.4
libxrender 0.9.10
little-cms2 2.12
lzo 2.10
m4 1.4.18
media-info 21.03
mono 6.12.0.122
mpdecimal 2.5.1
nano 5.8
ncdu 1.15.1
ncurses 6.2
nethogs 0.8.6
netpbm 10.86.18 10.86.22
nettle 3.7.3
nghttp2 1.43.0
nmap 7.91
node 16.3.0
nvm 0.38.0
oniguruma 6.9.7.1
opencore-amr 0.1.5
openjpeg 2.4.0
openssl@1.1 1.1.1k
opus 1.3.1
p11-kit 0.24.0
p7zip 17.04
pango 1.48.5
pcre 8.45
pcre2 10.37
perl 5.34.0
pixman 0.40.0
pkg-config 0.29.2_3
protobuf 3.17.3
pstree 2.39
py3cairo 1.20.1
pygobject3 3.40.1
python@3.8 3.8.10
python@3.9 3.9.5
rav1e 0.4.1_1
re2 20210601
readline 8.1
rename 1.601
rubberband 1.9.2
sdl2 2.0.14_1
six 1.16.0_1
snappy 1.1.9
speex 1.2.0
sqlite 3.35.5 3.34.0
srt 1.4.3
tcl-tk 8.6.11_1
tesseract 4.1.1
the_silver_searcher 2.2.0
theora 1.1.1
tig 2.5.4
tree 1.8.0
unbound 1.13.1
unrar 5.9.4
vorbis-tools 1.4.2
wabt 1.0.23
webp 1.2.0
wget 1.21.1
x264 r3060
x265 3.5
xorgproto 2021.4
xvid 1.3.7
xz 5.2.5
zeromq 4.3.4
zim 0.73.5
zimg 3.0.1
```

```
12:01 $ port installed
-bash: port: command not found
```

**Comment by dehesselle** [comment]
> One thing I manually changed in `/Applications/Zim.app/Contents/MacOS/Zim` is to add `--standalone` to the `exec` line, making it `exec /usr/local/bin/zim --standalone;`. I can't remember why I made the change.

@tmcguire You made the change to fix your issue! Please remove `--standalone` to verify that the issue resurfaces. Then you can test starting Zim.app from the terminal `Zim.app/Contents/MacOS/Zim --standalone` to verify that it does fix the issue there as well.

@jaap-karssenberg Is it safe to use `--standalone` as default? I've looked at the code but I don't have enough in-depth knowledge to assess the potential drawbacks.

**Comment by jaap-karssenberg** [comment]
The main drawback of the standalone option is that you can open the same
notebook twice in separate instances. In that case you can cause conflicts
in the index and the content.



Op zo 19 sep. 2021 18:19 schreef René de Hesselle ***@***.***

**Comment by tmcguire** [comment]
> @tmcguire You made the change to fix your issue! Please remove --standalone to verify that the issue resurfaces. Then you can test starting Zim.app from the terminal Zim.app/Contents/MacOS/Zim --standalone to verify that it does fix the issue there as well.

I've tested now and can confirm that the menubar works on the correct notebook/window when starting the app from your bundle with `/Applications/Zim.app/Contents/MacOS/Zim --standalone`, and on the wrong window when starting it with `/Applications/Zim.app/Contents/MacOS/Zim`.

**Comment by gagarine** [comment]
Zim_0.73.5.r7.dmg is working great on MacBook Air M1 (apple silicon) but as an Intel binary using Rosetta2 not as a native app.

**Comment by dehesselle** [comment]
Zim 0.74.2 for macOS is ready: 
https://gitlab.com/api/v4/projects/30529415/packages/generic/zim_macos/0.74.2_1/Zim-0.74.2_1.dmg

@jaap-karssenberg With the release above I consider my work to be complete. You can take a look at what I've been doing all this time [here](https://gitlab.com/dehesselle/zim_macos). It's probably a surprise that I'm using GitLab for this, but that's a technical necessity as what I'm doing is not possible with GitHub CI (lack of support for older OS).
How do you want to proceed?

**Comment by jaap-karssenberg** [comment]
Hi Rene,

Look like you put a lot of effort into that build !

The website is part of the zim source archive, so you can add a screenshot
and a link on the "downloads" page via a merge request towards the master
branch. Then I'll build & upload the website.

See "tools/test_website.py" to check how it looks after modifying the
source.

Also partial update is welcome, if you can at least add a screenshot, I can
update the text etc.

Probably for issue tracking we need a specific issue template that shows it
is about the MacOS build. Any specific information you want to request from
submitters ?

Regards,

Jaap

**Comment by dehesselle** [comment]
Hi Jaap,

yes, quite some time went into this. When I originally created this issue (after having built the first prototype), I thought I already had all the necessary parts in place...

I created a pull request for the website. In regards to issue template, I'll get back to you on that.

Talking about issues in general, I can also help with occasional maintenance work like correctly tagging them or closing duplicates (if it's about macOS; I'm not looking to overstep my boundaries). That'd require additional permissions though.

**Comment by dehesselle** [comment]
Thanks everyone for their patience (this was not intended to take almost two years) and testing efforts. The updated website went live today, concluding this issue.
