### ISSUE TITLE
BUG: Can't remove link

### ISSUE THREAD

**Issue by leukios** [zim-desktop-wiki/zim-desktop-wiki#994]
OS: Ubuntu 18.04 LTS
Version: Zim 0.72.1
How to reproduce:
1. Select a page
2. Add link text, like ssh://zim@git.zim.com:26888/zim/manifest
3. Right click and choose remove link. Then the blue colored link disappeared.
4. Select another page
5. Select back the above page. Find the blue colored link reappeared now.

This is a really annoying bug. I don't know clearly know why, but the link even auto-generated some sub-pages. Please help me.

**Comment by mifegui** [comment]
I have the same thing, but with Windows with zim 0.69.1. You can further reproduce it by just writing anything in this format: ***@***.***
Apparently it thinks anything in this format is an email and deserves to be linked, even if you remove the link.

**Comment by leukios** [comment]
Could anyone help?

**Comment by lucvtzel** [comment]
You can try to format the text in verbatim (select the link, followed by `<CTRL>+T`)

**Comment by pdwilso** [comment]
I've seen this auto-convert text to link behavior on URL strings, CaMeL case strings, & file/system/strings - in each case the solution has been to use <Ctrl>+T, <Ctrl>-B, <Ctrl>-I, etc to impose persistent formatting that overwhelms the auto-format.  Also can put strings of characters in quotes -- 'http://foo.bar/etc'

**Comment by leukios** [comment]
> I've seen this auto-convert text to link behavior on URL strings, CaMeL case strings, & file/system/strings - in each case the solution has been to use +T, -B, -I, etc to impose persistent formatting that overwhelms the auto-format. Also can put strings of characters in quotes --
> 
> '''
> "http://foo.bar/etc"
> '''
> <-- Note that this does NOT work in the markdown filter, here.

Yes, this fix really works. Thank you. I use Ctrl + U (Text Highlighting) to format URL strings, and they no longer auto-format now.

**Comment by Plazmin** [comment]
UP! ver. 0.68

**Comment by wadih** [comment]
The Ctrl + T workaround works.

But sometimes I have command lines that get converted to links, e.g. the mail command takes this syntax:

`mail -aFrom:myaddress@example.com -s 'Testing'`

But then adds a link to nowhere.

I've tried disabling in Preference > Editing > Automatically turn CamelCase words into links, but still happens. Wish there was a way to further customize that behavior, or even disable it completely.

**Comment by lucvtzel** [comment]
with the 0.73.4 version, i can remove a link in this way:
1. select the line
2. `<CTRL> +< SHIFT> + 9 ` ? (9 of the top of the keyboard, not the numeric keypad)

**Comment by introt** [comment]
Removing links only affects `[[Wiki links]]`; this is not a bug but a known limitation as other types of links are parsed from text.
